Repository firebase/firebase-android-sdk, pull requests merged in 2018-12, with the labels that each got.

#148 Fix google-services testing tooling.
  gradle/googleServices.gradle
Labels: cla: yes, size/XS

#137 Cleanup a number of warnings in the code.
  firebase-firestore/src/main/java/com/google/firebase/firestore/DocumentReference.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/Query.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/SetOptions.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/EventManager.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/UserData.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/ViewSnapshot.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/IndexedQueryEngine.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/model/BasePath.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/model/Document.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/model/DocumentKey.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/model/DocumentSet.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/model/NoDocument.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/model/UnknownDocument.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/model/mutation/ArrayTransformOperation.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/model/mutation/FieldMask.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/remote/RemoteSerializer.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/remote/WatchChange.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/LocalSerializerTest.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/model/MutationTest.java
  firebase-firestore/src/testUtil/java/com/google/firebase/firestore/testutil/TestUtil.java
Labels: cla: yes, size/L

#151 Add grpc keepalive timeout
  firebase-firestore/src/main/java/com/google/firebase/firestore/remote/Datastore.java
Labels: cla: yes, size/XS

#146 fix tests
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/ArrayTransformsTest.java
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/TransactionTest.java
Labels: cla: yes, size/S

#149 Make schema migrations idempotent
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteSchema.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/SQLiteSchemaTest.java
Labels: cla: yes, size/L

#156 Fix automatic data collection(b/120600091).
  firebase-common/src/main/java/com/google/firebase/FirebaseApp.java
  firebase-common/src/test/java/com/google/firebase/DataCollectionDefaultDisabledTest.java
  firebase-common/src/test/java/com/google/firebase/DataCollectionDefaultEnabledTest.java
  firebase-common/src/test/java/com/google/firebase/DataCollectionTestUtil.java
Labels: cla: yes, size/L

#157 Adding version info to manifest for blaze builds
  firebase-common/src/main/AndroidManifest.xml
  firebase-database-collection/src/main/AndroidManifest.xml
  firebase-database/src/androidTest/AndroidManifest.xml
  firebase-database/src/main/AndroidManifest.xml
  firebase-firestore/src/androidTest/AndroidManifest.xml
  firebase-firestore/src/main/AndroidManifest.xml
  firebase-firestore/src/test/AndroidManifest.xml
  firebase-functions/src/androidTest/AndroidManifest.xml
  firebase-functions/src/main/AndroidManifest.xml
  firebase-inappmessaging-display/src/main/AndroidManifest.xml
  firebase-storage/src/androidTest/AndroidManifest.xml
  firebase-storage/src/main/AndroidManifest.xml
  firebase-storage/src/test/AndroidManifest.xml
Labels: cla: yes, size/M

#162 Port copyright check to python.
  ci/fireci/fireciplugins/copyright.py
  ci/fireci/tests/copyright_test.py
  ci/fireci/tests/fileutil.py
  ci/fireci/tests/integ_tests.py
Labels: cla: yes, size/L

#167 Delete old copyright check.
  root-project.gradle
Labels: cla: yes, size/S

#160 m40 release notes for firestore
  firebase-firestore/CHANGELOG.md
Labels: cla: yes, size/S

#166 Upgrade robolectric to latest version.
  firebase-common/firebase-common.gradle
  firebase-database/firebase-database.gradle
  firebase-firestore/firebase-firestore.gradle
  firebase-inappmessaging-display/firebase-inappmessaging-display.gradle
  firebase-storage/firebase-storage.gradle
  firebase-storage/src/test/java/com/google/firebase/storage/DownloadTest.java
  root-project.gradle
Labels: cla: yes, size/S

#171 update firebase-firestore gradle.properties
  firebase-firestore/gradle.properties
Labels: cla: yes, size/XS

#169 Add the concept of Set-components and dependencies.
  firebase-common/proguard.txt
  firebase-common/src/main/java/com/google/firebase/components/Component.java
  firebase-common/src/main/java/com/google/firebase/components/Dependency.java
  firebase-common/src/test/java/com/google/firebase/components/ComponentTest.java
  firebase-common/src/test/java/com/google/firebase/components/DependencyTest.java
Labels: cla: yes, size/L

#174 Switch default for LRU collection to disabled
  firebase-firestore/src/main/java/com/google/firebase/firestore/FirebaseFirestoreSettings.java
Labels: cla: yes, size/S

#68 Enable LRU GC
  firebase-firestore/src/main/java/com/google/firebase/firestore/FirebaseFirestore.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/FirebaseFirestoreSettings.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/FirestoreClient.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/LocalStore.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/LruDelegate.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/LruGarbageCollector.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/MemoryLruReferenceDelegate.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/MemoryMutationQueue.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/MemoryPersistence.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/MemoryQueryCache.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/MemoryRemoteDocumentCache.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteLruReferenceDelegate.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLitePersistence.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/util/AsyncQueue.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/LruGarbageCollectorTestCase.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/MemoryLruGarbageCollectorTest.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/PersistenceTestHelpers.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/SQLiteLruGarbageCollectorTest.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/spec/SQLiteSpecTest.java
Labels: cla: yes, size/XL
