Repository firebase/firebase-android-sdk, pull requests merged in 2018-10, with the labels that each got.

#54 Held Write Acks Changelog entries
  firebase-firestore/CHANGELOG.md
Labels: size/XS

#50 Add priming logic to integration tests to avoid backend cold start issues.
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/ArrayTransformsTest.java
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/RetryRule.java
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/testutil/IntegrationTestUtil.java
Labels: size/L

#56 Release fixes
  firebase-common/firebase-common.gradle
  firebase-database/src/main/java/com/google/firebase/database/android/package-info.java
  firebase-database/src/main/java/com/google/firebase/database/annotations/package-info.java
  firebase-database/src/main/java/com/google/firebase/database/connection/package-info.java
  firebase-database/src/main/java/com/google/firebase/database/connection/util/package-info.java
  firebase-database/src/main/java/com/google/firebase/database/core/package-info.java
  firebase-database/src/main/java/com/google/firebase/database/logging/package-info.java
  firebase-database/src/main/java/com/google/firebase/database/snapshot/package-info.java
  firebase-database/src/main/java/com/google/firebase/database/tubesock/package-info.java
  firebase-database/src/main/java/com/google/firebase/database/util/package-info.java
  firebase-firestore/firebase-firestore.gradle
  firebase-functions/firebase-functions.gradle
  firebase-storage/src/main/java/com/google/firebase/storage/internal/package-info.java
  firebase-storage/src/main/java/com/google/firebase/storage/network/package-info.java
  root-project.gradle
Labels: size/L

#57 Version bumps after release
  firebase-common/gradle.properties
  firebase-database-collection/gradle.properties
  firebase-database/gradle.properties
  firebase-firestore/gradle.properties
  firebase-functions/gradle.properties
  firebase-storage/gradle.properties
Labels: size/S

#58 Add dependency on empty version of listenablefuture.
  firebase-firestore/firebase-firestore.gradle
Labels: size/XS

#55 Removed unused Android Lifecycle dependencies
  firebase-database/firebase-database.gradle
  firebase-firestore/firebase-firestore.gradle
  firebase-storage/firebase-storage.gradle
Labels: size/S

#62 Small cleanup from lru port to webclient
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteMutationQueue.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/MutationQueueTestCase.java
Labels: size/XS

#64 Add migration to add sequence numbers to documents
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteSchema.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/SQLiteSchemaTest.java
Labels: size/M

#63 Enabled linting on Firestore
  firebase-firestore/firebase-firestore.gradle
  firebase-firestore/lint.xml
Labels: size/M

#67 Enabled linting part2
  firebase-database-collection/firebase-database-collection.gradle
  firebase-database/firebase-database.gradle
  firebase-storage/firebase-storage.gradle
  test-apps/database-test-app/build.gradle
  test-apps/firestore-test-app/build.gradle
  test-apps/firestore-test-app/lint.xml
  test-apps/functions-test-app/build.gradle
  test-apps/storage-test-app/build.gradle
Labels: size/S

#70 Upgrade errorprone to latest version.
  firebase-database/src/androidTest/java/com/google/firebase/database/snapshot/CompoundHashingIntegrationTest.java
  root-project.gradle
Labels: size/S

#75 Backport Protobuf changes
  firebase-firestore/src/proto/google/firebase/firestore/proto/maybe_document.proto
Labels: size/S

#77 Update changelog for 17.1.2 release
  firebase-firestore/CHANGELOG.md
Labels: size/XS

#83 Implement POJO field reads.
  firebase-firestore/CHANGELOG.md
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/POJOTest.java
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/ServerTimestampTest.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/DocumentSnapshot.java
Labels: enhancement, size/L

#76 Allow passing POJOs as field values throughout API.
  firebase-firestore/CHANGELOG.md
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/POJOTest.java
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/ServerTimestampTest.java
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/ValidationTest.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/CollectionReference.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/DocumentReference.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/DocumentSnapshot.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/Transaction.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/UserDataConverter.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/WriteBatch.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/util/CustomClassMapper.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/model/FieldValueTest.java
Labels: size/L

#80 Use orphaned docs as part of GC calculation
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/LruDelegate.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/LruGarbageCollector.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/MemoryLruReferenceDelegate.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteLruReferenceDelegate.java
Labels: size/S

#86 Swap smoke test deps
  test-apps/build.gradle
Labels: size/XS

#85 Make sure primeBackend snapshot listener doesn't fail.
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/testutil/IntegrationTestUtil.java
Labels: size/XS

#88 Fix wrong "should start" check in RemoteStore (watch instead of write stream)
  firebase-firestore/src/main/java/com/google/firebase/firestore/remote/RemoteStore.java
Labels: size/XS

#91 Include fiam display
  README.md
Labels: size/XS

#92 Starting the Mutation Queue in a Transaction
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/LocalStore.java
Labels: size/S

#84 Port structural changes from Multi-Tab
  firebase-firestore/src/main/java/com/google/firebase/firestore/QuerySnapshot.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/FirestoreClient.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/QueryListener.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/SyncEngine.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/TargetIdGenerator.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/View.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/ViewSnapshot.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/LocalStore.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/MemoryMutationQueue.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/MutationQueue.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteMutationQueue.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/QuerySnapshotTest.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/TestUtil.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/core/QueryListenerTest.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/core/TargetIdGeneratorTest.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/core/ViewSnapshotTest.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/spec/SpecTestCase.java
Labels: size/L

#94 Backport android changelog fixes from http://cl/218569645
  firebase-firestore/CHANGELOG.md
Labels: size/S

#93 Project import generated by Copybara.
  firebase-firestore/src/main/java/com/google/cloud/datastore/core/number/NumberComparisonHelper.java
  firebase-firestore/src/main/java/com/google/cloud/datastore/core/number/NumberIndexEncoder.java
  firebase-firestore/src/main/java/com/google/cloud/datastore/core/number/NumberParts.java
  firebase-firestore/src/main/java/com/google/cloud/datastore/core/number/package-info.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/util/Util.java
Labels: size/M

#73 Trying to fix issue #72 - Targeting Android 28, with Android Studio 3.2.1
  buildSrc/build.gradle
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/license/LicenseResolverPlugin.groovy
  firebase-common/firebase-common.gradle
  firebase-common/src/main/AndroidManifest.xml
  firebase-database-collection/firebase-database-collection.gradle
  firebase-database-collection/src/main/AndroidManifest.xml
  firebase-database/firebase-database.gradle
  firebase-database/src/androidTest/AndroidManifest.xml
  firebase-database/src/main/AndroidManifest.xml
  firebase-firestore/firebase-firestore.gradle
  firebase-firestore/lint.xml
  firebase-firestore/src/main/AndroidManifest.xml
  firebase-functions/firebase-functions.gradle
  firebase-functions/src/androidTest/AndroidManifest.xml
  firebase-functions/src/main/AndroidManifest.xml
  firebase-inappmessaging-display/src/main/res/drawable/btn_clear.png
  firebase-inappmessaging-display/src/main/res/drawable/image_placeholder.png
  firebase-storage/firebase-storage.gradle
  firebase-storage/src/androidTest/AndroidManifest.xml
  firebase-storage/src/main/AndroidManifest.xml
  gradle/wrapper/gradle-wrapper.properties
  protolite-well-known-types/protolite-well-known-types.gradle
  root-project.gradle
  test-apps/build.gradle
  test-apps/database-test-app/build.gradle
  test-apps/database-test-app/src/androidTest/java/com/google/firebase/testapps/database/TestActivityTest.java
  test-apps/database-test-app/src/main/java/com/google/firebase/testapps/database/TestActivity.java
  test-apps/firestore-test-app/build.gradle
  test-apps/firestore-test-app/src/androidTest/java/com/google/firebase/testapps/firestore/TestActivityTest.java
  test-apps/functions-test-app/build.gradle
  test-apps/functions-test-app/src/androidTest/java/com/google/firebase/testapps/functions/TestActivityTest.java
  test-apps/gradle/wrapper/gradle-wrapper.properties
  test-apps/storage-test-app/build.gradle
  test-apps/storage-test-app/src/androidTest/java/com/google/firebase/testapps/storage/TestActivityTest.java
  tools/errorprone/errorprone.gradle
Labels: size/L
