Repository firebase/firebase-android-sdk, pull requests merged in 2019-03, with the labels that each got.

#256 Update opencensus
  ci/fireci/setup.py
Labels: cla: yes, size/XS

#182 Add RTDB Changelog
  firebase-database/CHANGELOG.md
Labels: cla: yes, size/XS

#105 Adding FieldValue.numericAdd()
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/NumericTransformsTest.java
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/testutil/IntegrationTestUtil.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/FieldValue.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/UserDataConverter.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/LocalSerializer.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/LocalStore.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/MemoryMutationQueue.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/MutationQueue.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteMutationQueue.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/model/mutation/ArrayTransformOperation.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/model/mutation/DeleteMutation.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/model/mutation/FieldMask.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/model/mutation/FieldTransform.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/model/mutation/Mutation.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/model/mutation/MutationBatch.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/model/mutation/NumericIncrementTransformOperation.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/model/mutation/PatchMutation.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/model/mutation/ServerTimestampOperation.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/model/mutation/SetMutation.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/model/mutation/TransformMutation.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/model/mutation/TransformOperation.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/remote/RemoteSerializer.java
  firebase-firestore/src/proto/google/firebase/firestore/proto/mutation.proto
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/LocalSerializerTest.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/LocalStoreTestCase.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/LruGarbageCollectorTestCase.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/MutationQueueTestCase.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/model/MutationTest.java
Labels: cla: yes, size/XXL

#258 Last released version for common is incorrect
  firebase-common/gradle.properties
Labels: cla: yes, size/XS

#259 Add okhttp3 settings to Functions proguard.
  firebase-functions/proguard.txt
  test-apps/functions-test-app/proguard-rules.pro
Labels: cla: yes, size/S

#257 Added FieldValue.increment() to Changelog
  firebase-firestore/CHANGELOG.md
Labels: cla: yes, size/XS

#263 Add comment to @PublicApi making it clear its only a convention for non-proguarded projects.
  firebase-common/src/main/java/com/google/firebase/annotations/PublicApi.java
Labels: api: core, cla: yes, size/XS

#233 Collection Group Queries
  firebase-firestore/CHANGELOG.md
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/QueryTest.java
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/ValidationTest.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/FirebaseFirestore.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/Query.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/Query.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/IndexManager.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/LocalDocumentsView.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/LocalStore.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/MemoryIndexManager.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/MemoryMutationQueue.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/MemoryPersistence.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/MemoryRemoteDocumentCache.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/Persistence.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteIndexManager.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteMutationQueue.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLitePersistence.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteRemoteDocumentCache.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteSchema.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/model/DocumentKey.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/remote/RemoteSerializer.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/IndexManagerTestCase.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/IndexedQueryEngineTest.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/MemoryIndexManagerTest.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/SQLiteIndexManagerTest.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/SQLiteSchemaTest.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/spec/SpecTestCase.java
  firebase-firestore/src/test/resources/json/query_spec_test.json
Labels: cla: yes, size/XXL

#261 Implement firebase-firestore-ktx Kotlin library.
  firebase-common-ktx/src/test/kotlin/com/google/firebase/ktx/Tests.kt
  firebase-firestore-ktx/firebase-firestore-ktx.gradle
  firebase-firestore-ktx/gradle.properties
  firebase-firestore-ktx/src/main/AndroidManifest.xml
  firebase-firestore-ktx/src/main/kotlin/com/google/firebase/firestore/ktx/Firestore.kt
  firebase-firestore-ktx/src/test/kotlin/com/google/firebase/firestore/ktx/FirestoreTests.kt
  firebase-firestore/firebase-firestore.gradle
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/WriteBatchTest.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/DocumentReference.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/FirebaseFirestore.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/QuerySnapshot.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/SetOptions.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/WriteBatch.java
  firebase-firestore/src/roboUtil/java/com/google/firebase/firestore/TestUtil.java
  root-project.gradle
  subprojects.cfg
Labels: cla: yes, size/L

#268 add transport client
  subprojects.cfg
  transport/transport-api/gradle.properties
  transport/transport-api/src/main/AndroidManifest.xml
  transport/transport-api/src/main/java/com/google/android/datatransport/Event.java
  transport/transport-api/src/main/java/com/google/android/datatransport/Priority.java
  transport/transport-api/src/main/java/com/google/android/datatransport/Transformer.java
  transport/transport-api/src/main/java/com/google/android/datatransport/Transport.java
  transport/transport-api/src/main/java/com/google/android/datatransport/TransportFactory.java
  transport/transport-api/transport-api.gradle
  transport/transport-backend-cct/gradle.properties
  transport/transport-backend-cct/src/main/AndroidManifest.xml
  transport/transport-backend-cct/src/main/java/com/google/android/datatransport/cct/GoogleTransportBackend.java
  transport/transport-backend-cct/src/main/proto/google/cct/google_cct.proto
  transport/transport-backend-cct/src/test/java/com/google/android/datatransport/cct/GoogleTransportBackendTest.java
  transport/transport-backend-cct/transport-backend-cct.gradle
  transport/transport-runtime/gradle.properties
  transport/transport-runtime/src/main/AndroidManifest.xml
  transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/BackendRegistry.java
  transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/BackendResponse.java
  transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/EventInternal.java
  transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/SendRequest.java
  transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/TransportBackend.java
  transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/TransportFactoryImpl.java
  transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/TransportImpl.java
  transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/TransportInternal.java
  transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/TransportRuntime.java
  transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/TransportRuntimeComponent.java
  transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/TransportRuntimeModule.java
  transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/scheduling/DefaultScheduler.java
  transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/scheduling/ImmediateScheduler.java
  transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/scheduling/Scheduler.java
  transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/time/Clock.java
  transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/time/Uptime.java
  transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/time/UptimeClock.java
  transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/time/WallTime.java
  transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/time/WallTimeClock.java
  transport/transport-runtime/src/test/java/com/google/android/datatransport/runtime/TransportRuntimeTest.java
  transport/transport-runtime/transport-runtime.gradle
Labels: cla: yes, size/XXL

#267 firebase-firestore-ktx KDoc improvements.
  firebase-firestore-ktx/src/main/kotlin/com/google/firebase/firestore/ktx/Firestore.kt
Labels: api: firestore, cla: yes, size/M

#266 Adding RestrictTo annotations to Firebase Storage
  firebase-storage/src/main/java/com/google/firebase/storage/DeleteStorageTask.java
  firebase-storage/src/main/java/com/google/firebase/storage/StorageRegistrar.java
  firebase-storage/src/main/java/com/google/firebase/storage/StorageTaskScheduler.java
  firebase-storage/src/main/java/com/google/firebase/storage/internal/package-info.java
  firebase-storage/src/main/java/com/google/firebase/storage/network/connection/package-info.java
  firebase-storage/src/main/java/com/google/firebase/storage/network/package-info.java
Labels: cla: yes, size/S

#262 Reduce visibility of non-public portions of our api.
  firebase-firestore/src/main/java/com/google/firebase/firestore/DocumentReference.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/SetOptions.java
Labels: cla: yes, size/XS

#275 Enable proguard of proto library, various fixes.
  transport/transport-backend-cct/gradle.properties
  transport/transport-backend-cct/preguard.txt
  transport/transport-backend-cct/src/main/AndroidManifest.xml
  transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/BackendRegistry.java
  transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/TransportFactoryImpl.java
  transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/TransportRuntime.java
  transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/TransportRuntimeModule.java
  transport/transport-runtime/src/test/java/com/google/android/datatransport/runtime/TransportRuntimeTest.java
  transport/transport.gradle
Labels: cla: yes, size/M

#269 Add Changelog Entry for Firebase Storage's RestrictTo change
  firebase-storage/CHANGELOG.md
Labels: cla: yes, size/XS

#271 Add RestrictTo annotations to Firestore
  firebase-firestore/CHANGELOG.md
  firebase-firestore/src/main/java/com/google/firebase/firestore/Blob.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/DocumentSnapshot.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/FirestoreRegistrar.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/Query.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/SetOptions.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/UserDataConverter.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/auth/package-info.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/package-info.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/package-info.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/model/mutation/package-info.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/model/package-info.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/model/value/package-info.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/remote/package-info.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/util/package-info.java
Labels: cla: yes, size/M

#272 Reject non-standard Number classes during POJO serialization
  firebase-database/CHANGELOG.md
  firebase-database/src/main/java/com/google/firebase/database/core/utilities/encoding/CustomClassMapper.java
  firebase-firestore/CHANGELOG.md
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/POJOTest.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/util/CustomClassMapper.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/util/MapperTest.java
Labels: api: database, api: firestore, cla: yes, size/L

#276 Add persistence definitions and in-memory store.
  transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/TransportRuntimeModule.java
  transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/scheduling/persistence/BackendNextCallTime.java
  transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/scheduling/persistence/EventStore.java
  transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/scheduling/persistence/InMemoryEventStore.java
  transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/scheduling/persistence/PersistedEvent.java
  transport/transport-runtime/src/test/java/com/google/android/datatransport/runtime/scheduling/persistence/InMemoryEventStoreTest.java
  transport/transport-runtime/transport-runtime.gradle
Labels: cla: yes, size/L

#278 firestore version bump
  firebase-firestore/gradle.properties
Labels: cla: yes, size/XS

#281 Fix Firestore POJO tests
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/POJOTest.java
Labels: cla: yes, size/S

#280 Database: Rename test helpers
  firebase-database/src/androidTest/java/com/google/firebase/database/DataTest.java
  firebase-database/src/androidTest/java/com/google/firebase/database/EventTest.java
  firebase-database/src/androidTest/java/com/google/firebase/database/FirebaseDatabaseTest.java
  firebase-database/src/androidTest/java/com/google/firebase/database/InfoTest.java
  firebase-database/src/androidTest/java/com/google/firebase/database/IntegrationTestHelpers.java
  firebase-database/src/androidTest/java/com/google/firebase/database/OrderByTest.java
  firebase-database/src/androidTest/java/com/google/firebase/database/OrderTest.java
  firebase-database/src/androidTest/java/com/google/firebase/database/PerformanceBenchmarks.java
  firebase-database/src/androidTest/java/com/google/firebase/database/QueryTest.java
  firebase-database/src/androidTest/java/com/google/firebase/database/RealtimeTest.java
  firebase-database/src/androidTest/java/com/google/firebase/database/TransactionTest.java
  firebase-database/src/androidTest/java/com/google/firebase/database/ValueExpectationHelper.java
  firebase-database/src/androidTest/java/com/google/firebase/database/connection/ConnectionTest.java
  firebase-database/src/androidTest/java/com/google/firebase/database/connection/ListenAggregator.java
  firebase-database/src/androidTest/java/com/google/firebase/database/core/AndroidPlatformTest.java
  firebase-database/src/androidTest/java/com/google/firebase/database/core/SynchronousConnection.java
  firebase-database/src/androidTest/java/com/google/firebase/database/core/ZombieVerifier.java
  firebase-database/src/androidTest/java/com/google/firebase/database/core/persistence/KeepSyncedTest.java
  firebase-database/src/androidTest/java/com/google/firebase/database/core/persistence/PersistenceTest.java
  firebase-database/src/androidTest/java/com/google/firebase/database/core/persistence/PruningTest.java
  firebase-database/src/androidTest/java/com/google/firebase/database/core/persistence/SqlPersistenceStorageEngineTest.java
  firebase-database/src/androidTest/java/com/google/firebase/database/future/ReadFuture.java
  firebase-database/src/androidTest/java/com/google/firebase/database/future/WriteFuture.java
  firebase-database/src/androidTest/java/com/google/firebase/database/snapshot/CompoundHashTest.java
  firebase-database/src/androidTest/java/com/google/firebase/database/tubesock/FirebaseClient.java
  firebase-database/src/androidTest/java/com/google/firebase/database/tubesock/TestClient.java
  firebase-database/src/androidTest/java/com/google/firebase/database/tubesock/UpdateClient.java
  firebase-database/src/test/java/com/google/firebase/database/DataSnapshotTest.java
  firebase-database/src/test/java/com/google/firebase/database/MapperTest.java
  firebase-database/src/test/java/com/google/firebase/database/MutableDataTest.java
  firebase-database/src/test/java/com/google/firebase/database/UnitTestHelpers.java
  firebase-database/src/test/java/com/google/firebase/database/core/RangeMergeTest.java
  firebase-database/src/test/java/com/google/firebase/database/core/SyncPointTest.java
  firebase-database/src/test/java/com/google/firebase/database/core/persistence/DefaultPersistenceManagerTest.java
  firebase-database/src/test/java/com/google/firebase/database/core/persistence/PruneForestTest.java
  firebase-database/src/test/java/com/google/firebase/database/core/persistence/RandomPersistenceTest.java
  firebase-database/src/test/java/com/google/firebase/database/core/persistence/TrackedQueryManagerTest.java
  firebase-database/src/test/java/com/google/firebase/database/core/view/QueryParamsTest.java
Labels: cla: yes, size/XXL

#287 Bumping Database Collection Min SDK version to 14
  firebase-database-collection/firebase-database-collection.gradle
Labels: cla: yes, size/XS

#286 Firebase Database Component Registration
  firebase-database/CHANGELOG.md
  firebase-database/firebase-database.gradle
  firebase-database/src/androidTest/java/com/google/firebase/database/FirebaseDatabaseTest.java
  firebase-database/src/androidTest/java/com/google/firebase/database/IntegrationTestHelpers.java
  firebase-database/src/androidTest/java/com/google/firebase/database/TransactionTest.java
  firebase-database/src/main/java/com/google/firebase/database/DatabaseRegistrar.java
  firebase-database/src/main/java/com/google/firebase/database/FirebaseDatabase.java
  firebase-database/src/main/java/com/google/firebase/database/FirebaseDatabaseComponent.java
  firebase-database/src/main/java/com/google/firebase/database/android/AndroidAuthTokenProvider.java
  firebase-database/src/main/java/com/google/firebase/database/android/AndroidPlatform.java
  firebase-database/src/main/java/com/google/firebase/database/core/AuthTokenProvider.java
  firebase-database/src/main/java/com/google/firebase/database/core/Context.java
  firebase-database/src/main/java/com/google/firebase/database/core/Platform.java
  firebase-database/src/main/java/com/google/firebase/database/core/Repo.java
  firebase-database/src/test/java/com/google/firebase/database/UnitTestHelpers.java
  firebase-database/src/testUtil/java/com/google/firebase/database/TestTokenProvider.java
Labels: cla: yes, size/L

#277 Firebase Storage Component Registration
  firebase-storage/CHANGELOG.md
  firebase-storage/firebase-storage.gradle
  firebase-storage/src/main/java/com/google/firebase/storage/DeleteStorageTask.java
  firebase-storage/src/main/java/com/google/firebase/storage/FileDownloadTask.java
  firebase-storage/src/main/java/com/google/firebase/storage/FirebaseStorage.java
  firebase-storage/src/main/java/com/google/firebase/storage/FirebaseStorageComponent.java
  firebase-storage/src/main/java/com/google/firebase/storage/GetDownloadUrlTask.java
  firebase-storage/src/main/java/com/google/firebase/storage/GetMetadataTask.java
  firebase-storage/src/main/java/com/google/firebase/storage/StorageRegistrar.java
  firebase-storage/src/main/java/com/google/firebase/storage/StreamDownloadTask.java
  firebase-storage/src/main/java/com/google/firebase/storage/UpdateMetadataTask.java
  firebase-storage/src/main/java/com/google/firebase/storage/UploadTask.java
  firebase-storage/src/main/java/com/google/firebase/storage/internal/ExponentialBackoffSender.java
  firebase-storage/src/main/java/com/google/firebase/storage/internal/Util.java
  firebase-storage/src/test/java/com/google/firebase/storage/DeleteTest.java
  firebase-storage/src/test/java/com/google/firebase/storage/DownloadTest.java
  firebase-storage/src/test/java/com/google/firebase/storage/MetadataTest.java
  firebase-storage/src/test/java/com/google/firebase/storage/PathingTest.java
  firebase-storage/src/test/java/com/google/firebase/storage/StorageReferenceTest.java
  firebase-storage/src/test/java/com/google/firebase/storage/TestUtil.java
  firebase-storage/src/test/java/com/google/firebase/storage/UploadTest.java
  tools/errorprone/src/main/java/com/google/firebase/errorprone/ComponentsAppGetCheck.java
Labels: cla: yes, size/L

#290 Minor fixes to ktx libs related to kotlindoc.
  firebase-common-ktx/src/main/kotlin/com/google/firebase/ktx/Firebase.kt
  firebase-firestore-ktx/src/main/kotlin/com/google/firebase/firestore/ktx/Firestore.kt
Labels: cla: yes, size/S

#289 Refactor Event Listeners
  firebase-firestore/src/main/java/com/google/firebase/firestore/DocumentReference.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/Query.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/ActivityScope.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/AsyncEventListener.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/ListenerRegistrationImpl.java
Labels: api: firestore, cla: yes, size/L

#284 [datatransport] Implement EventStore backed by SQLite.
  transport/transport-runtime/src/androidTest/AndroidManifest.xml
  transport/transport-runtime/src/androidTest/aidl/com/google/android/datatransport/runtime/ITestRemoteLockRpc.aidl
  transport/transport-runtime/src/androidTest/java/com/google/android/datatransport/runtime/scheduling/Locker.java
  transport/transport-runtime/src/androidTest/java/com/google/android/datatransport/runtime/scheduling/MultiProcessSynchronizationGuardTest.java
  transport/transport-runtime/src/androidTest/java/com/google/android/datatransport/runtime/scheduling/RemoteLockRpc.java
  transport/transport-runtime/src/androidTest/java/com/google/android/datatransport/runtime/scheduling/TestService.java
  transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/TransportRuntime.java
  transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/TransportRuntimeModule.java
  transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/scheduling/persistence/EventStore.java
  transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/scheduling/persistence/InMemoryEventStore.java
  transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/scheduling/persistence/SQLiteEventStore.java
  transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/synchronization/SynchronizationException.java
  transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/synchronization/SynchronizationGuard.java
  transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/time/Monotonic.java
  transport/transport-runtime/src/test/java/com/google/android/datatransport/runtime/TransportRuntimeTest.java
  transport/transport-runtime/src/test/java/com/google/android/datatransport/runtime/scheduling/persistence/InMemoryEventStoreTest.java
  transport/transport-runtime/src/test/java/com/google/android/datatransport/runtime/scheduling/persistence/SQLiteEventStoreTest.java
  transport/transport-runtime/transport-runtime.gradle
Labels: cla: yes, size/XXL

#294 Firebase Test Lab plugin
  buildSrc/resources/dummy.apk
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/ci/ContinuousIntegrationPlugin.groovy
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/ci/device/FirebaseTestLabExtension.groovy
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/ci/device/FirebaseTestLabPlugin.groovy
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/ci/device/FirebaseTestServer.groovy
  transport/transport-runtime/transport-runtime.gradle
Labels: cla: yes, size/L

#300 Enable FTL tests for all projects except functions.
  README.md
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/ci/device/FirebaseTestLabPlugin.groovy
  fiamui-app/fiamui-app.gradle
  firebase-common/firebase-common.gradle
  firebase-database/firebase-database.gradle
  firebase-firestore/firebase-firestore.gradle
  firebase-inappmessaging-display/firebase-inappmessaging-display.gradle
  firebase-storage/firebase-storage.gradle
  gradle/googleServices.gradle
Labels: cla: yes, size/M

#307 Upload FTL results to a specified directory.
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/ci/device/FirebaseTestServer.groovy
Labels: cla: yes, size/S

#309 Expand nested env vars.
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/ci/Environment.groovy
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/ci/device/FirebaseTestServer.groovy
Labels: cla: yes, size/M

#305 b/120793850: "endAfter" => "endBefore" in error message.
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/ValidationTest.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/Query.java
Labels: api: firestore, cla: yes, size/XS

#308 Update ktx versions to match their respective deps.
  firebase-common-ktx/gradle.properties
  firebase-firestore-ktx/gradle.properties
Labels: cla: yes, size/XS

#311 Reduce the number of metrics exported to stackdriver.
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/ci/metrics/Metrics.java
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/ci/metrics/MetricsPlugin.java
Labels: cla: yes, size/M

#321 Correct the version for common ktx
  firebase-common-ktx/gradle.properties
Labels: cla: yes, size/XS

#314 Restructure docs for KTX
  .opensource/project.json
  docs/README.md
  docs/ktx/common.md
  docs/ktx/firestore.md
Labels: cla: yes, size/L

#315 Jobscheduler
  transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/TransportRuntime.java
  transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/TransportRuntimeModule.java
  transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/scheduling/DefaultScheduler.java
  transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/scheduling/jobscheduling/AlarmManagerScheduler.java
  transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/scheduling/jobscheduling/JobInfoScheduler.java
  transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/scheduling/jobscheduling/JobInfoSchedulerService.java
  transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/scheduling/jobscheduling/SchedulerUtil.java
  transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/scheduling/jobscheduling/Uploader.java
  transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/scheduling/jobscheduling/WorkScheduler.java
  transport/transport-runtime/src/test/java/com/google/android/datatransport/runtime/TransportRuntimeTest.java
  transport/transport-runtime/src/test/java/com/google/android/datatransport/runtime/scheduling/jobscheduling/JobInfoSchedulerTest.java
  transport/transport-runtime/src/test/java/com/google/android/datatransport/runtime/scheduling/persistence/InMemoryEventStore.java
Labels: cla: yes, size/L

#325 docs: fix ktx docs urls for firebaseopensource.com
  docs/README.md
Labels: cla: yes, needs-ok-to-test, size/XS
