Repository firebase/firebase-android-sdk, pull requests merged in 2019-08, with the labels that each got.

#677 Release notes for firestore m53 (21.0.0)
  firebase-firestore/CHANGELOG.md
Labels: api: firestore, cla: yes, size/XS

#669 Make component discovery directBootAware
  firebase-common/src/main/AndroidManifest.xml
Labels: cla: yes, size/XS

#678 Remove overrideChannelBuilder
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/testutil/IntegrationTestUtil.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/remote/GrpcCallProvider.java
Labels: cla: yes, size/M

#682 Update error message for IN operators
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/FieldFilter.java
Labels: api: firestore, cla: yes, size/XS

#683 Add spec test for limit query initialization
  firebase-firestore/src/test/resources/json/limit_spec_test.json
Labels: api: firestore, cla: yes, size/L

#684 Update RTDB Error message to point to GitHub
  firebase-database/src/main/java/com/google/firebase/database/core/utilities/DefaultRunLoop.java
Labels: cla: yes, size/XS

#616 Index-Free (3/6): Persist a Query's Sync State
  firebase-firestore/ktx/src/test/java/com/google/firebase/firestore/TestUtil.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/QueryListener.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/View.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/ViewSnapshot.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/LocalSerializer.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/LocalStore.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/LocalViewChanges.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/QueryData.java
  firebase-firestore/src/proto/google/firebase/firestore/proto/target.proto
  firebase-firestore/src/roboUtil/java/com/google/firebase/firestore/TestUtil.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/QuerySnapshotTest.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/core/QueryListenerTest.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/core/ViewSnapshotTest.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/core/ViewTest.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/LocalSerializerTest.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/QueryCacheTestCase.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/remote/RemoteSerializerTest.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/spec/SpecTestCase.java
  firebase-firestore/src/testUtil/java/com/google/firebase/firestore/testutil/TestUtil.java
Labels: api: firestore, cla: yes, size/L

#680 Add support for /?ns= query param in Database URL
  firebase-database/CHANGELOG.md
  firebase-database/src/androidTest/java/com/google/firebase/database/DataTest.java
  firebase-database/src/androidTest/java/com/google/firebase/database/FirebaseDatabaseTest.java
  firebase-database/src/androidTest/java/com/google/firebase/database/RealtimeTest.java
  firebase-database/src/main/java/com/google/firebase/database/core/utilities/ParsedUrl.java
  firebase-database/src/main/java/com/google/firebase/database/core/utilities/Utilities.java
  firebase-database/src/test/java/com/google/firebase/database/core/utilities/ParseUrlTest.java
Labels: cla: yes, size/L

#673 FirebaseSegmentation SDK changes
  firebase-segmentation/src/androidTest/java/com/google/firebase/segmentation/FirebaseSegmentationInstrumentedTest.java
  firebase-segmentation/src/main/java/com/google/firebase/segmentation/FirebaseSegmentation.java
  firebase-segmentation/src/main/java/com/google/firebase/segmentation/SetCustomInstallationIdException.java
  firebase-segmentation/src/main/java/com/google/firebase/segmentation/remote/SegmentationServiceClient.java
Labels: cla: yes, size/M

#690 Restrict Firebase API key to Android app package name.
  firebase-segmentation/src/main/java/com/google/firebase/segmentation/FirebaseSegmentation.java
  firebase-segmentation/src/main/java/com/google/firebase/segmentation/remote/SegmentationServiceClient.java
Labels: cla: yes, size/M

#691 Arete floc
  firebase-segmentation/src/main/AndroidManifest.xml
Labels: cla: yes, size/XS

#687 Add QueryData.with() helpers
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/LocalStore.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/MemoryLruReferenceDelegate.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/QueryData.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteLruReferenceDelegate.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/remote/RemoteStore.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/LruGarbageCollectorTestCase.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/remote/MockDatastore.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/remote/RemoteSerializerTest.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/spec/SpecTestCase.java
Labels: cla: yes, size/L

#694 Implementing cache for FIS SDK
  firebase-installations/firebase-installations.gradle
  firebase-installations/src/androidTest/AndroidManifest.xml
  firebase-installations/src/androidTest/java/com/google/firebase/installation/local/FiidCacheTest.java
  firebase-installations/src/main/java/com/google/firebase/installations/FirebaseInstallations.java
  firebase-installations/src/main/java/com/google/firebase/installations/local/FiidCache.java
  firebase-installations/src/main/java/com/google/firebase/installations/local/FiidCacheEntryValue.java
Labels: cla: yes, size/L

#686 Index-Free: Using readTime instead of updateTime
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/LocalStore.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/MemoryLruReferenceDelegate.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/MemoryRemoteDocumentCache.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/RemoteDocumentCache.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteRemoteDocumentCache.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteSchema.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/IndexedQueryEngineTest.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/LruGarbageCollectorTestCase.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/RemoteDocumentCacheTestCase.java
Labels: api: firestore, cla: yes, size/L

#689 awaitPendingWrites initial revision
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/FirestoreTest.java
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/testutil/IntegrationTestUtil.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/FirebaseFirestore.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/FirestoreClient.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/SyncEngine.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/LocalStore.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/MemoryMutationQueue.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/MutationQueue.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteMutationQueue.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/remote/RemoteStore.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/LocalStoreTestCase.java
Labels: api: firestore, cla: yes, size/L

#693 Add runtime kotlin version detection for platform info purposes.
  firebase-common/firebase-common.gradle
  firebase-common/ktx/ktx.gradle
  firebase-common/ktx/src/main/kotlin/com/google/firebase/ktx/Firebase.kt
  firebase-common/proguard.txt
  firebase-common/src/main/java/com/google/firebase/FirebaseApp.java
  firebase-common/src/main/java/com/google/firebase/components/ComponentRuntime.java
  firebase-common/src/main/java/com/google/firebase/platforminfo/KotlinDetector.java
Labels: cla: yes, size/M

#617 Index-Free (4/6): Filter document queries by read time
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/IndexedQueryEngine.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/LocalDocumentsView.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/MemoryRemoteDocumentCache.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/RemoteDocumentCache.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLitePersistence.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteRemoteDocumentCache.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteSchema.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/SimpleQueryEngine.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/LocalStoreTestCase.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/RemoteDocumentCacheTestCase.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/SQLiteSchemaTest.java
Labels: api: firestore, cla: yes, size/L

#695 Don't persist manufactured documents
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/LocalStore.java
Labels: api: firestore, cla: yes, size/S

#696 Import spec tests
  firebase-firestore/src/test/resources/json/limit_spec_test.json
Labels: cla: yes, size/XXL

#701 Allow user to stop listening after shutdown + other minor fixes.
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/FirestoreTest.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/FirebaseFirestore.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/EventManager.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/FirestoreClient.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/SyncEngine.java
Labels: cla: yes, size/M

#653 Bumping auth interop
  firebase-functions/firebase-functions.gradle
Labels: cla: yes, size/XS

#575 Making transport schemas more testable
  transport/transport-backend-cct/src/main/AndroidManifest.xml
  transport/transport-backend-cct/src/main/java/com/google/android/datatransport/cct/CCTDestination.java
  transport/transport-backend-cct/src/main/java/com/google/android/datatransport/cct/CctBackendFactory.java
  transport/transport-backend-cct/src/main/java/com/google/android/datatransport/cct/CctTransportBackend.java
  transport/transport-backend-cct/src/main/java/com/google/android/datatransport/cct/LegacyFlgDestination.java
  transport/transport-backend-cct/src/main/java/com/google/android/datatransport/cct/StringMerger.java
  transport/transport-backend-cct/src/test/java/com/google/android/datatransport/cct/CctBackendFactoryTest.java
  transport/transport-backend-cct/src/test/java/com/google/android/datatransport/cct/CctTransportBackendTest.java
  transport/transport-backend-cct/src/test/java/com/google/android/datatransport/cct/StringMergerTest.java
  transport/transport-backend-cct/transport-backend-cct.gradle
  transport/transport-runtime/src/androidTest/java/com/google/android/datatransport/runtime/scheduling/persistence/SpyEventStoreModule.java
  transport/transport-runtime/src/androidTest/java/com/google/android/datatransport/runtime/scheduling/persistence/TestEventStoreModule.java
  transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/Destination.java
  transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/TransportContext.java
  transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/TransportRuntime.java
  transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/backends/BackendRequest.java
  transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/backends/CreationContext.java
  transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/scheduling/jobscheduling/AlarmManagerScheduler.java
  transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/scheduling/jobscheduling/AlarmManagerSchedulerBroadcastReceiver.java
  transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/scheduling/jobscheduling/JobInfoScheduler.java
  transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/scheduling/jobscheduling/JobInfoSchedulerService.java
  transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/scheduling/jobscheduling/Uploader.java
  transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/scheduling/persistence/EventStoreModule.java
  transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/scheduling/persistence/SQLiteEventStore.java
  transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/scheduling/persistence/SchemaManager.java
  transport/transport-runtime/src/test/java/com/google/android/datatransport/runtime/scheduling/jobscheduling/AlarmManagerSchedulerTest.java
  transport/transport-runtime/src/test/java/com/google/android/datatransport/runtime/scheduling/jobscheduling/JobInfoSchedulerTest.java
  transport/transport-runtime/src/test/java/com/google/android/datatransport/runtime/scheduling/persistence/SQLiteEventStoreTest.java
  transport/transport-runtime/src/test/java/com/google/android/datatransport/runtime/scheduling/persistence/SchemaManagerTest.java
Labels: cla: yes, size/XXL

#698 Retrying transactions with backoff
  firebase-firestore/CHANGELOG.md
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/TransactionTest.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/FirestoreClient.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/SyncEngine.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/TransactionRunner.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/util/AsyncQueue.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/util/ExponentialBackoff.java
Labels: api: firestore, cla: yes, size/L

#699 Only advance the limbo free snapshot if query is synced
  firebase-firestore/ktx/src/test/java/com/google/firebase/firestore/TestUtil.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/QueryListener.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/View.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/ViewSnapshot.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/LocalStore.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/LocalViewChanges.java
  firebase-firestore/src/roboUtil/java/com/google/firebase/firestore/TestUtil.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/QuerySnapshotTest.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/core/QueryListenerTest.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/core/ViewSnapshotTest.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/core/ViewTest.java
Labels: cla: yes, size/M

#671 add gradle tasks for metalava generation
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/FirebaseLibraryPlugin.java
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/apiinfo/ApiInformationTask.java
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/apiinfo/GenerateApiTxtFileTask.java
  ci/fireci/fireci/commands.py
  ci/fireci/setup.py
  firebase-abt/api.txt
  firebase-common/api.txt
  firebase-config/api.txt
  firebase-database-collection/api.txt
  firebase-database/api.txt
  firebase-datatransport/api.txt
  firebase-firestore/api.txt
  firebase-functions/api.txt
  firebase-inappmessaging-display/api.txt
  firebase-storage/api.txt
  gradle.properties
  transport/transport-api/api.txt
  transport/transport-backend-cct/api.txt
  transport/transport-runtime/api.txt
Labels: cla: yes, size/XXL

#705 Early exit when stopListening after shutdown.
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/FirestoreClient.java
Labels: cla: yes, size/XS

#710 Set delay to 0 for skipping TimerId delays
  firebase-firestore/src/main/java/com/google/firebase/firestore/util/AsyncQueue.java
Labels: api: firestore, cla: yes, size/XS

#713 Propagate error for ListAll
  firebase-storage/CHANGELOG.md
  firebase-storage/src/main/java/com/google/firebase/storage/StorageReference.java
  firebase-storage/src/test/java/com/google/firebase/storage/ListTest.java
  firebase-storage/src/test/resources/activitylogs/listAllFailed_network.txt
  firebase-storage/src/test/resources/activitylogs/listAllFailed_task.txt
  firebase-storage/src/test/resources/activitylogs/listSinglePageFailed_network.txt
  firebase-storage/src/test/resources/activitylogs/listSinglePageFailed_task.txt
  firebase-storage/src/testUtil/java/com/google/firebase/storage/TestCommandHelper.java
  firebase-storage/test-app/src/main/java/com/example/storage/MainActivity.java
  firebase-storage/test-app/test-app.gradle
Labels: api: storage, cla: yes, size/L

#708 Fix JobInfoScheduler not to overwrite jobs(b/139434539).
  transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/scheduling/jobscheduling/JobInfoScheduler.java
  transport/transport-runtime/src/test/java/com/google/android/datatransport/runtime/scheduling/jobscheduling/JobInfoSchedulerTest.java
Labels: cla: yes, size/S

#707 Schedule active context jobs upon initialization(b/139435527).
  transport/transport-runtime/src/androidTest/java/com/google/android/datatransport/runtime/TestRuntimeComponent.java
  transport/transport-runtime/src/androidTest/java/com/google/android/datatransport/runtime/TestSchedulingModule.java
  transport/transport-runtime/src/androidTest/java/com/google/android/datatransport/runtime/TestWorkScheduler.java
  transport/transport-runtime/src/androidTest/java/com/google/android/datatransport/runtime/UploaderIntegrationTest.java
  transport/transport-runtime/src/androidTest/java/com/google/android/datatransport/runtime/UploaderTestRuntimeComponent.java
  transport/transport-runtime/src/androidTest/java/com/google/android/datatransport/runtime/scheduling/persistence/SpyEventStoreModule.java
  transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/TransportRuntime.java
  transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/scheduling/jobscheduling/WorkInitializer.java
  transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/scheduling/persistence/EventStore.java
  transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/scheduling/persistence/SQLiteEventStore.java
  transport/transport-runtime/src/test/java/com/google/android/datatransport/runtime/TransportRuntimeTest.java
  transport/transport-runtime/src/test/java/com/google/android/datatransport/runtime/scheduling/jobscheduling/WorkInitializerTest.java
  transport/transport-runtime/src/test/java/com/google/android/datatransport/runtime/scheduling/persistence/InMemoryEventStore.java
  transport/transport-runtime/src/test/java/com/google/android/datatransport/runtime/scheduling/persistence/SQLiteEventStoreTest.java
Labels: cla: yes, size/L

#714 Download metalava jar before running the command
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/FirebaseLibraryPlugin.java
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/apiinfo/ApiInformationTask.java
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/apiinfo/GenerateApiTxtFileTask.java
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/apiinfo/GetMetalavaJarTask.java
  ci/fireci/fireci/commands.py
Labels: cla: yes, size/L

#716 Use list of files instead of string
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/FirebaseLibraryPlugin.java
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/apiinfo/ApiInformationTask.java
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/apiinfo/GenerateApiTxtFileTask.java
Labels: cla: yes, size/M

#718 Fix issue with UTF8 strings in RC SDK 19.0.0
  firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigFetchHttpClient.java
  firebase-config/src/test/java/com/google/firebase/remoteconfig/internal/ConfigFetchHttpClientTest.java
Labels: cla: yes, size/S

#697 Add Index-Free query engine
  firebase-database-collection/src/main/java/com/google/firebase/database/collection/ImmutableSortedMap.java
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/remote/RemoteStoreTest.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/FirestoreClient.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/Query.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/SyncEngine.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/IndexFreeQueryEngine.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/IndexedQueryEngine.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/LocalDocumentsView.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/LocalStore.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/QueryEngine.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/SimpleQueryEngine.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/core/QueryTest.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/IndexFreeQueryEngineTest.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/IndexedQueryEngineTest.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/LocalStoreTestCase.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/MemoryLocalStoreTest.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/SQLiteLocalStoreTest.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/spec/QueryEvent.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/spec/SpecTestCase.java
  firebase-firestore/src/testUtil/java/com/google/firebase/firestore/testutil/TestUtil.java
Labels: api: firestore, cla: yes, size/XL

#721 Remove unused parameter from LocalStore tests
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/LocalStoreTestCase.java
  firebase-firestore/src/testUtil/java/com/google/firebase/firestore/testutil/TestUtil.java
Labels: api: firestore, cla: yes, size/S

#506 feat: add docs for functions-ktx
  docs/README.md
  docs/ktx/functions.md
Labels: cla: yes, ok-to-test, size/M

#724 Update API text file
  firebase-firestore/api.txt
Labels: cla: yes, size/XS

#720 Don't persist documents that we already have
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/LocalStore.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/LocalStoreTestCase.java
  firebase-firestore/src/test/resources/json/limbo_spec_test.json
  firebase-firestore/src/test/resources/json/listen_spec_test.json
  firebase-firestore/src/testUtil/java/com/google/firebase/firestore/testutil/TestUtil.java
Labels: cla: yes, size/L

#726 Index-free: Use different SQL for non-index free queries
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteRemoteDocumentCache.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/SQLiteSchemaTest.java
Labels: cla: yes, size/L

#728 Whitelist lint warning for missing tools:targetApi attr.
  firebase-common/firebase-common.gradle
  firebase-common/lint-baseline.xml
  firebase-common/src/main/AndroidManifest.xml
Labels: cla: yes, size/S

#729 Remove spurious `tools` schema.
  firebase-common/src/main/AndroidManifest.xml
Labels: cla: yes, size/XS

#734 Index-free: Drop last limbo free snapshot if re-upgraded
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteSchema.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/SQLiteSchemaTest.java
Labels: api: firestore, cla: yes, size/L

#746 Update sdk versions.
  firebase-abt/gradle.properties
  firebase-common/gradle.properties
  firebase-database/gradle.properties
  firebase-datatransport/gradle.properties
  firebase-firestore/gradle.properties
  firebase-functions/gradle.properties
  firebase-storage/gradle.properties
Labels: cla: yes, size/S

#751 Update firebase-firestore/api.txt based on recent changes
  firebase-firestore/api.txt
Labels: cla: yes, size/XS

#748 Migrate apk size table to metrics database.
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/measurement/apksize/ApkSizeJsonBuilder.groovy
  buildSrc/src/test/groovy/com/google/firebase/gradle/plugins/measurement/apksize/ApkSizeJsonBuilderTest.groovy
Labels: cla: yes, size/S

#752 Add missing deprecation annotation to synchronous setDefaults method
  firebase-config/api.txt
  firebase-config/gradle.properties
  firebase-config/src/main/java/com/google/firebase/remoteconfig/FirebaseRemoteConfig.java
Labels: cla: yes, size/XS

#750 Add http redirect support to the cct transport backend.
  transport/transport-backend-cct/src/main/java/com/google/android/datatransport/cct/CctTransportBackend.java
  transport/transport-backend-cct/src/test/java/com/google/android/datatransport/cct/CctTransportBackendTest.java
  transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/retries/Function.java
  transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/retries/Retries.java
  transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/retries/RetryStrategy.java
  transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/retries/package-info.java
Labels: cla: yes, size/L

#754 Add RunWith to ThrottledForwardingExecutorTest
  firebase-firestore/src/test/java/com/google/firebase/firestore/util/ThrottledForwardingExecutorTest.java
Labels: cla: yes, size/XS

#755 Update SDK versions.
  firebase-config/gradle.properties
  firebase-database/gradle.properties
  firebase-firestore/gradle.properties
Labels: cla: yes, size/XS

#749 Re-add tools:targetApi to firebase-common AndroidManifest.
  firebase-common/lint-baseline.xml
  firebase-common/src/main/AndroidManifest.xml
Labels: cla: yes, size/S

#756 Revert "Remove overrideChannelBuilder"
  firebase-firestore/src/main/java/com/google/firebase/firestore/remote/GrpcCallProvider.java
Labels: cla: yes, size/M

#703 getId() implementation with instrumented tests.
  firebase-installations/firebase-installations.gradle
  firebase-installations/src/androidTest/java/com/google/firebase/installations/FirebaseInstallationsInstrumentedTest.java
  firebase-installations/src/androidTest/java/com/google/firebase/installations/FisAndroidTestConstants.java
  firebase-installations/src/androidTest/java/com/google/firebase/installations/local/FiidCacheTest.java
  firebase-installations/src/androidTest/java/com/google/firebase/installations/local/PersistedFidEntrySubject.java
  firebase-installations/src/androidTest/java/com/google/firebase/installations/local/PersistedFidTest.java
  firebase-installations/src/main/AndroidManifest.xml
  firebase-installations/src/main/java/com/google/firebase/installations/FirebaseInstallations.java
  firebase-installations/src/main/java/com/google/firebase/installations/Utils.java
  firebase-installations/src/main/java/com/google/firebase/installations/local/FiidCacheEntryValue.java
  firebase-installations/src/main/java/com/google/firebase/installations/local/PersistedFid.java
  firebase-installations/src/main/java/com/google/firebase/installations/local/PersistedFidEntry.java
  firebase-installations/src/main/java/com/google/firebase/installations/remote/FirebaseInstallationServiceClient.java
Labels: cla: yes, size/XL
