Repository firebase/firebase-android-sdk, pull requests merged in 2019-01, with the labels that each got.

#186 Commenting out version info
  firebase-common/src/main/AndroidManifest.xml
  firebase-database-collection/src/main/AndroidManifest.xml
  firebase-database/src/androidTest/AndroidManifest.xml
  firebase-database/src/main/AndroidManifest.xml
  firebase-firestore/src/androidTest/AndroidManifest.xml
  firebase-firestore/src/main/AndroidManifest.xml
  firebase-firestore/src/test/AndroidManifest.xml
  firebase-functions/src/androidTest/AndroidManifest.xml
  firebase-functions/src/main/AndroidManifest.xml
  firebase-inappmessaging-display/src/main/AndroidManifest.xml
  firebase-storage/src/androidTest/AndroidManifest.xml
  firebase-storage/src/main/AndroidManifest.xml
  firebase-storage/src/test/AndroidManifest.xml
Labels: cla: yes, size/M

#172 Implement fragment to monitor activity lifecycle
  firebase-firestore/firebase-firestore.gradle
  firebase-firestore/src/androidTest/AndroidManifest.xml
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/ListenerRegistrationTest.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/util/ListenerRegistrationImpl.java
Labels: cla: yes, size/L

#175 Add runtime support for Set-components
  firebase-common/src/main/java/com/google/firebase/components/AbstractComponentContainer.java
  firebase-common/src/main/java/com/google/firebase/components/ComponentContainer.java
  firebase-common/src/main/java/com/google/firebase/components/ComponentRuntime.java
  firebase-common/src/main/java/com/google/firebase/components/CycleDetector.java
  firebase-common/src/main/java/com/google/firebase/components/Lazy.java
  firebase-common/src/main/java/com/google/firebase/components/RestrictedComponentContainer.java
  firebase-common/src/test/java/com/google/firebase/components/ComponentRuntimeTest.java
  firebase-common/src/test/java/com/google/firebase/components/CycleDetectorTest.java
  firebase-common/src/test/java/com/google/firebase/components/LazyTest.java
  firebase-common/src/test/java/com/google/firebase/components/RestrictedComponentContainerTest.java
Labels: cla: yes, size/L

#189 Treat ABORTED writes as retryable
  firebase-firestore/src/main/java/com/google/firebase/firestore/remote/Datastore.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/remote/RemoteStore.java
  firebase-firestore/src/test/resources/json/listen_spec_test.json
  firebase-firestore/src/test/resources/json/write_spec_test.json
Labels: cla: yes, size/L

#190 Change timestampsInSnapshots default to true and deprecate the setting.
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/FieldsTest.java
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/testutil/IntegrationTestUtil.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/FirebaseFirestore.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/FirebaseFirestoreSettings.java
Labels: cla: yes, size/M

#193 Add changelog for timestampsInSnapshots default change.
  firebase-firestore/CHANGELOG.md
Labels: cla: yes, size/XS

#191 Include a trailing /documents on root resource paths
  firebase-firestore/src/main/java/com/google/firebase/firestore/remote/RemoteSerializer.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/remote/RemoteSerializerTest.java
Labels: cla: yes, size/S

#188 Port "Stop persisting last acknowledged batch ID" from iOS
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/MemoryMutationQueue.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/MutationQueue.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteMutationQueue.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteSchema.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/MutationQueueTestCase.java
Labels: cla: yes, size/M

#192 Revert "Revert "Better POJO Support for Document Fields" (#140)"
  firebase-firestore/CHANGELOG.md
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/POJOTest.java
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/ServerTimestampTest.java
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/ValidationTest.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/CollectionReference.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/DocumentReference.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/DocumentSnapshot.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/Transaction.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/UserDataConverter.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/WriteBatch.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/util/CustomClassMapper.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/model/FieldValueTest.java
Labels: cla: yes, size/L

#194 Migrate Firestore to the v1 protocol
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/LocalSerializer.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/model/Document.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/remote/Datastore.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/remote/RemoteSerializer.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/remote/WatchStream.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/remote/WriteStream.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/util/FirestoreChannel.java
  firebase-firestore/src/proto/google/firebase/firestore/proto/maybe_document.proto
  firebase-firestore/src/proto/google/firebase/firestore/proto/mutation.proto
  firebase-firestore/src/proto/google/firebase/firestore/proto/target.proto
  firebase-firestore/src/proto/google/firestore/admin/v1beta1/firestore_admin.proto
  firebase-firestore/src/proto/google/firestore/admin/v1beta1/index.proto
  firebase-firestore/src/proto/google/firestore/v1/common.proto
  firebase-firestore/src/proto/google/firestore/v1/document.proto
  firebase-firestore/src/proto/google/firestore/v1/firestore.proto
  firebase-firestore/src/proto/google/firestore/v1/query.proto
  firebase-firestore/src/proto/google/firestore/v1/write.proto
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/LocalSerializerTest.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/SQLiteSchemaTest.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/remote/RemoteSerializerTest.java
Labels: cla: yes, size/XL

#199 Fixed package info for firestore
  firebase-firestore/src/main/java/com/google/cloud/datastore/core/number/package-info.java
Labels: cla: yes, size/S

#196 Remove licenses that have been wrongly identified as SDKs transitively depending on
  root-project.gradle
  third_party/licenses/apache-2.0.txt
  third_party/licenses/darts_clone.txt
  third_party/licenses/icu.txt
  third_party/licenses/jsr305.txt
  third_party/licenses/nanoproto.txt
  third_party/licenses/pcre.txt
  third_party/licenses/re2.txt
  third_party/licenses/sgi-stl.txt
  third_party/licenses/utf.txt
  third_party/licenses/zlib.txt
Labels: cla: yes, size/XL

#201 bump firestore version so that we can release the right version
  firebase-firestore/gradle.properties
Labels: cla: yes, size/XS

#202 Update firestore version as per launch cal
  firebase-firestore/gradle.properties
Labels: cla: yes, size/XS

#207 Backport changelog fixups from http://cl/229787474
  firebase-firestore/CHANGELOG.md
Labels: cla: yes, size/S

#209 Fix set component registration issue.
  firebase-common/src/main/java/com/google/firebase/components/ComponentRuntime.java
  firebase-common/src/test/java/com/google/firebase/components/ComponentRuntimeTest.java
Labels: cla: yes, size/S

#211 Enable metrics collection for CI builds.
  ci/fireci/fireci/commands.py
  ci/fireci/fireci/emulator.py
  ci/fireci/fireci/gradle.py
  ci/fireci/fireci/internal.py
  ci/fireci/fireci/stats.py
  ci/fireci/setup.py
Labels: cla: yes, size/L

#215 Handle large write batches
  firebase-firestore/CHANGELOG.md
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/WriteBatchTest.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteMutationQueue.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/MutationQueueTestCase.java
Labels: cla: yes, size/L

#217 Allow firestore to recover quicker when a network change occurs
  firebase-firestore/CHANGELOG.md
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/remote/RemoteStoreTest.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/FirestoreClient.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/remote/AndroidConnectivityMonitor.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/remote/ConnectivityMonitor.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/remote/RemoteStore.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/spec/SpecTestCase.java
Labels: cla: yes, size/L

#216 Clean up warnings
  firebase-database-collection/src/main/java/com/google/firebase/database/collection/LLRBValueNode.java
  firebase-database-collection/src/main/java/com/google/firebase/database/collection/RBTreeSortedMap.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/util/ListenerRegistrationImpl.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/DocumentChangeTest.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/TestUtil.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/core/EventManagerTest.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/LruGarbageCollectorTestCase.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/RemoteDocumentCacheTestCase.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/SQLiteSchemaTest.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/model/DocumentSetTest.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/model/FieldValueTest.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/remote/RemoteEventTest.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/util/MapperTest.java
Labels: cla: yes, size/M

#203 Library Version implementation.
  firebase-common/firebase-common.gradle
  firebase-common/src/androidTest/java/com/google/firebase/FirebaseAppTest.java
  firebase-common/src/main/java/com/google/firebase/FirebaseApp.java
  firebase-common/src/main/java/com/google/firebase/platforminfo/DefaultUserAgentPublisher.java
  firebase-common/src/main/java/com/google/firebase/platforminfo/LibraryVersion.java
  firebase-common/src/main/java/com/google/firebase/platforminfo/LibraryVersionComponent.java
  firebase-common/src/main/java/com/google/firebase/platforminfo/OutOfBandLibraryVersionRegistrar.java
  firebase-common/src/main/java/com/google/firebase/platforminfo/UserAgentPublisher.java
  firebase-common/src/main/java/com/google/firebase/platforminfo/package-info.java
  firebase-common/src/test/java/com/google/firebase/platforminfo/DefaultUserAgentPublisherTest.java
  firebase-common/src/test/java/com/google/firebase/platforminfo/OutOfBandLibraryVersionRegistrarTest.java
  firebase-common/src/testUtil/com/google/firebase/components/TestComponentRegistrar.java
  firebase-common/src/testUtil/com/google/firebase/components/TestUserAgentDependentComponent.java
Labels: cla: yes, size/L

#223 Add @RunWith annotations to support non-gradle builds.
  firebase-common/src/test/java/com/google/firebase/VersionGenerationTest.java
  firebase-common/src/test/java/com/google/firebase/platforminfo/DefaultUserAgentPublisherTest.java
  firebase-common/src/test/java/com/google/firebase/platforminfo/OutOfBandLibraryVersionRegistrarTest.java
Labels: cla: yes, size/XS

#214 Instrument Gradle build with metrics.
  buildSrc/build.gradle
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/ci/metrics/DrainingBuildListener.java
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/ci/metrics/MeasuringTaskExecutionListener.java
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/ci/metrics/Metrics.java
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/ci/metrics/MetricsPlugin.java
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/ci/metrics/StackdriverMetrics.java
  ci/fireci/fireci/gradle.py
  ci/fireci/fireci/stats.py
  root-project.gradle
Labels: cla: yes, size/L
