Repository firebase/firebase-android-sdk, pull requests merged in 2019-10, with the labels that each got.

#866 Remove generic parameter from TransportScheduleCallback
  transport/transport-api/src/main/java/com/google/android/datatransport/TransportScheduleCallback.java
Labels: cla: yes, size/XS

#869 Index-Free: Drop last limbo free snapshot version for schema v9
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/LocalStore.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/MemoryRemoteDocumentCache.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteRemoteDocumentCache.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteSchema.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/SQLiteSchemaTest.java
Labels: api: firestore, cla: yes, size/M

#873 Address build warnings.
  transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/TransportContext.java
  transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/scheduling/jobscheduling/JobInfoScheduler.java
Labels: cla: yes, size/XS

#872 Update sample app to use new CCTDestination.
  tools/measurement/apksize/src/transport/java/com.google.apksize/TransportSample.java
Labels: cla: yes, size/XS

#874 Remove unused retries parameter in transactions
  firebase-firestore/src/main/java/com/google/firebase/firestore/FirebaseFirestore.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/FirestoreClient.java
Labels: api: firestore, cla: yes, size/XS

#864 [Smoke-tests] Add build-only tests.
  smoke-tests/build.gradle
  smoke-tests/gradle.properties
  smoke-tests/src/main/java/com/google/firebase/testing/buildonly/BuildOnlyTest.java
  smoke-tests/src/main/java/com/google/firebase/testing/combined/AllTests.java
  smoke-tests/src/main/java/com/google/firebase/testing/inappmessaging/InappMessagingTest.java
Labels: cla: yes, size/L

#876 [Smoke-tests] Move tests into a single package.
  smoke-tests/src/main/AndroidManifest.xml
  smoke-tests/src/main/java/com/google/firebase/testing/BuildOnlyTest.java
  smoke-tests/src/main/java/com/google/firebase/testing/DatabaseTest.java
  smoke-tests/src/main/java/com/google/firebase/testing/DynamicLinksTest.java
  smoke-tests/src/main/java/com/google/firebase/testing/FirestoreTest.java
  smoke-tests/src/main/java/com/google/firebase/testing/FunctionsTest.java
  smoke-tests/src/main/java/com/google/firebase/testing/RemoteConfigTest.java
  smoke-tests/src/main/java/com/google/firebase/testing/StorageTest.java
  smoke-tests/src/main/java/com/google/firebase/testing/TestSuite.java
Labels: cla: yes, size/M

#877 [Smoke-tests] Add local config file.
  smoke-tests/local-runner.config
Labels: cla: yes, size/M

#882 Update versions for release
  firebase-common/gradle.properties
  firebase-config/gradle.properties
  firebase-firestore/gradle.properties
  transport/transport-api/gradle.properties
  transport/transport-backend-cct/gradle.properties
  transport/transport-runtime/gradle.properties
Labels: cla: yes, size/S

#887 Wrap sdk names with double quote as it contains a colon sometimes.
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/measurement/aarsize/AarSizeJsonBuilder.groovy
Labels: cla: yes, size/XS

#884 Updating getAuthToken to return creation timestamp
  firebase-installations-interop/api.txt
  firebase-installations-interop/src/main/java/com/google/firebase/installations/InstallationTokenResult.java
  firebase-installations/src/androidTest/java/com/google/firebase/installations/FirebaseInstallationsInstrumentedTest.java
  firebase-installations/src/androidTest/java/com/google/firebase/installations/FisAndroidTestConstants.java
  firebase-installations/src/main/java/com/google/firebase/installations/FirebaseInstallations.java
  firebase-installations/src/main/java/com/google/firebase/installations/GetAuthTokenListener.java
  firebase-installations/src/main/java/com/google/firebase/installations/remote/FirebaseInstallationServiceClient.java
Labels: cla: yes, size/M

#891 Fix coverage calculation.
  root-project.gradle
Labels: cla: yes, size/XS

#856 Propagating the exceptions to the clients.
  firebase-installations/src/androidTest/java/com/google/firebase/installations/FirebaseInstallationsInstrumentedTest.java
  firebase-installations/src/main/java/com/google/firebase/installations/FirebaseInstallations.java
  firebase-installations/src/main/java/com/google/firebase/installations/GetAuthTokenListener.java
  firebase-installations/src/main/java/com/google/firebase/installations/GetIdListener.java
  firebase-installations/src/main/java/com/google/firebase/installations/StateListener.java
Labels: cla: yes, size/M

#847 Simplifying FirebaseInstallations class by adding listeners.
  firebase-installations-interop/api.txt
  firebase-installations-interop/src/main/java/com/google/firebase/installations/InstallationTokenResult.java
  firebase-installations/api.txt
  firebase-installations/firebase-installations.gradle
  firebase-installations/src/androidTest/java/com/google/firebase/installations/FirebaseInstallationsInstrumentedTest.java
  firebase-installations/src/androidTest/java/com/google/firebase/installations/FisAndroidTestConstants.java
  firebase-installations/src/androidTest/java/com/google/firebase/installations/local/PersistedFidTest.java
  firebase-installations/src/main/java/com/google/firebase/installations/FirebaseInstallations.java
  firebase-installations/src/main/java/com/google/firebase/installations/GetAuthTokenListener.java
  firebase-installations/src/main/java/com/google/firebase/installations/GetIdListener.java
  firebase-installations/src/main/java/com/google/firebase/installations/StateListener.java
  firebase-installations/src/main/java/com/google/firebase/installations/Utils.java
  firebase-installations/src/main/java/com/google/firebase/installations/local/PersistedFid.java
  firebase-installations/src/main/java/com/google/firebase/installations/local/PersistedFidEntry.java
  firebase-installations/src/main/java/com/google/firebase/installations/remote/FirebaseInstallationServiceClient.java
  firebase-installations/src/test/java/com/google/firebase/installations/remote/FirebaseInstallationServiceClientTest.java
Labels: cla: yes, size/XXL

#889 Use auto-generated apks for size measurement.
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/measurement/apksize/ApkSizeTableBuilder.groovy
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/measurement/apksize/GenerateVariantPlugin.groovy
  buildSrc/src/test/groovy/com/google/firebase/gradle/plugins/measurement/apksize/ApkSizeTableBuilderTest.groovy
  tools/measurement/apksize/apksize.gradle
  tools/measurement/apksize/src/base/base.gradle
  tools/measurement/apksize/src/common/common.gradle
  tools/measurement/apksize/src/common/java/com.google.apksize/Common.java
  tools/measurement/apksize/src/common/java/com.google.apksize/SampleCodeLoader.java
  tools/measurement/apksize/src/config/config.gradle
  tools/measurement/apksize/src/config/java/com.google.apksize/Config.java
  tools/measurement/apksize/src/config/java/com.google.apksize/SampleCodeLoader.java
  tools/measurement/apksize/src/database/database.gradle
  tools/measurement/apksize/src/database/java/com.google.apksize/RealtimeDatabase.java
  tools/measurement/apksize/src/database/java/com.google.apksize/SampleCodeLoader.java
  tools/measurement/apksize/src/empty/empty.gradle
  tools/measurement/apksize/src/empty/java/com.google.apksize/SampleCodeLoader.java
  tools/measurement/apksize/src/firestore/firestore.gradle
  tools/measurement/apksize/src/firestore/java/com.google.apksize/Firestore.java
  tools/measurement/apksize/src/firestore/java/com.google.apksize/SampleCodeLoader.java
  tools/measurement/apksize/src/functions/functions.gradle
  tools/measurement/apksize/src/functions/java/com.google.apksize/Functions.java
  tools/measurement/apksize/src/functions/java/com.google.apksize/SampleCodeLoader.java
  tools/measurement/apksize/src/inappmessagingdisplay/inappmessaging-display.gradle
  tools/measurement/apksize/src/inappmessagingdisplay/java/com.google.apksize/InAppMessagingDisplay.java
  tools/measurement/apksize/src/main/java/com.google.apksize/MainActivity.java
  tools/measurement/apksize/src/main/java/com.google.apksize/SampleCode.java
  tools/measurement/apksize/src/storage/java/com.google.apksize/SampleCodeLoader.java
  tools/measurement/apksize/src/storage/java/com.google.apksize/Storage.java
  tools/measurement/apksize/src/storage/res/values/strings.xml
  tools/measurement/apksize/src/storage/storage.gradle
  tools/measurement/apksize/src/transport/java/com.google.apksize/SampleCodeLoader.java
  tools/measurement/apksize/src/transport/java/com.google.apksize/TransportSample.java
  tools/measurement/apksize/src/transport/transport.gradle
Labels: cla: yes, size/XXL

#900 Update Serializer condition to the check for null.
  firebase-functions/src/main/java/com/google/firebase/functions/Serializer.java
Labels: cla: yes, size/XS

#899 Addressing Rayo's comment: Rename PersistedFidEntry to PersistedInstallationEntry.
  firebase-installations/api.txt
  firebase-installations/src/androidTest/java/com/google/firebase/installations/FirebaseInstallationsInstrumentedTest.java
  firebase-installations/src/androidTest/java/com/google/firebase/installations/FisAndroidTestConstants.java
  firebase-installations/src/androidTest/java/com/google/firebase/installations/local/PersistedInstallationEntrySubject.java
  firebase-installations/src/androidTest/java/com/google/firebase/installations/local/PersistedInstallationTest.java
  firebase-installations/src/main/java/com/google/firebase/installations/FirebaseInstallations.java
  firebase-installations/src/main/java/com/google/firebase/installations/GetAuthTokenListener.java
  firebase-installations/src/main/java/com/google/firebase/installations/GetIdListener.java
  firebase-installations/src/main/java/com/google/firebase/installations/StateListener.java
  firebase-installations/src/main/java/com/google/firebase/installations/Utils.java
  firebase-installations/src/main/java/com/google/firebase/installations/local/PersistedInstallation.java
  firebase-installations/src/main/java/com/google/firebase/installations/local/PersistedInstallationEntry.java
Labels: cla: yes, size/XL

#879 Remote Config Fetch event telemetry prototype
  firebase-config/firebase-config.gradle
  firebase-config/src/main/java/com/google/firebase/remoteconfig/RemoteConfigComponent.java
  firebase-config/src/main/java/com/google/firebase/remoteconfig/RemoteConfigRegistrar.java
  firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigFetchHttpClient.java
  firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigLogger.java
  firebase-config/src/proto/com/google/android/gms/config/proto/client_metrics.proto
  firebase-config/src/test/java/com/google/firebase/remoteconfig/RemoteConfigComponentTest.java
  firebase-config/src/test/java/com/google/firebase/remoteconfig/internal/ConfigFetchHttpClientTest.java
  firebase-config/src/test/java/com/google/firebase/remoteconfig/internal/ConfigLoggerTest.java
Labels: api: remoteconfig, cla: yes, size/XXL

#908 Change fiam warning log to info log
  firebase-inappmessaging/src/main/java/com/google/firebase/inappmessaging/internal/ProtoStorageClient.java
Labels: cla: yes, size/XS

#888 Extract FID from FIS createInstallation response
  firebase-installations/api.txt
  firebase-installations/src/androidTest/java/com/google/firebase/installations/FirebaseInstallationsInstrumentedTest.java
  firebase-installations/src/androidTest/java/com/google/firebase/installations/FisAndroidTestConstants.java
  firebase-installations/src/androidTest/java/com/google/firebase/installations/local/PersistedInstallationEntrySubject.java
  firebase-installations/src/androidTest/java/com/google/firebase/installations/local/PersistedInstallationTest.java
  firebase-installations/src/main/java/com/google/firebase/installations/FirebaseInstallations.java
  firebase-installations/src/main/java/com/google/firebase/installations/GetAuthTokenListener.java
  firebase-installations/src/main/java/com/google/firebase/installations/GetIdListener.java
  firebase-installations/src/main/java/com/google/firebase/installations/StateListener.java
  firebase-installations/src/main/java/com/google/firebase/installations/Utils.java
  firebase-installations/src/main/java/com/google/firebase/installations/local/PersistedInstallation.java
  firebase-installations/src/main/java/com/google/firebase/installations/local/PersistedInstallationEntry.java
  firebase-installations/src/main/java/com/google/firebase/installations/remote/FirebaseInstallationServiceClient.java
  firebase-installations/src/main/java/com/google/firebase/installations/remote/InstallationResponse.java
Labels: cla: yes, size/XL

#895 Implementing retry once for FIS Client.
  firebase-installations/api.txt
  firebase-installations/src/androidTest/java/com/google/firebase/installations/FirebaseInstallationsInstrumentedTest.java
  firebase-installations/src/main/java/com/google/firebase/installations/FirebaseInstallations.java
  firebase-installations/src/main/java/com/google/firebase/installations/remote/FirebaseInstallationServiceClient.java
  firebase-installations/src/main/java/com/google/firebase/installations/remote/FirebaseInstallationServiceException.java
Labels: cla: yes, size/L

#910 Merging changes into fis_sdk
  firebase-installations/api.txt
  firebase-installations/src/androidTest/java/com/google/firebase/installations/FirebaseInstallationsInstrumentedTest.java
  firebase-installations/src/androidTest/java/com/google/firebase/installations/FisAndroidTestConstants.java
  firebase-installations/src/androidTest/java/com/google/firebase/installations/local/PersistedInstallationEntrySubject.java
  firebase-installations/src/androidTest/java/com/google/firebase/installations/local/PersistedInstallationTest.java
  firebase-installations/src/main/java/com/google/firebase/installations/FirebaseInstallations.java
  firebase-installations/src/main/java/com/google/firebase/installations/GetAuthTokenListener.java
  firebase-installations/src/main/java/com/google/firebase/installations/GetIdListener.java
  firebase-installations/src/main/java/com/google/firebase/installations/StateListener.java
  firebase-installations/src/main/java/com/google/firebase/installations/Utils.java
  firebase-installations/src/main/java/com/google/firebase/installations/local/PersistedInstallation.java
  firebase-installations/src/main/java/com/google/firebase/installations/local/PersistedInstallationEntry.java
  firebase-installations/src/main/java/com/google/firebase/installations/remote/FirebaseInstallationServiceClient.java
  firebase-installations/src/main/java/com/google/firebase/installations/remote/FirebaseInstallationServiceException.java
  firebase-installations/src/main/java/com/google/firebase/installations/remote/InstallationResponse.java
Labels: cla: yes, size/XL

#903 Fix race condition when fieldValueCache is null
  firebase-firestore/src/main/java/com/google/firebase/firestore/model/Document.java
Labels: api: firestore, cla: yes, ok-to-test, size/XS

#912 Add a CHANGELOG entry for #903.
  firebase-firestore/CHANGELOG.md
Labels: api: firestore, cla: yes, size/XS

#896 Adds custom encodings support to TransportRuntime.
  transport/transport-api/src/main/java/com/google/android/datatransport/Encoding.java
  transport/transport-api/src/main/java/com/google/android/datatransport/TransportFactory.java
  transport/transport-backend-cct/src/main/java/com/google/android/datatransport/cct/CCTDestination.java
  transport/transport-backend-cct/src/main/java/com/google/android/datatransport/cct/CctTransportBackend.java
  transport/transport-backend-cct/src/test/java/com/google/android/datatransport/cct/CctTransportBackendTest.java
  transport/transport-runtime/src/androidTest/java/com/google/android/datatransport/runtime/SchedulerIntegrationTest.java
  transport/transport-runtime/src/androidTest/java/com/google/android/datatransport/runtime/UploaderIntegrationTest.java
  transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/EncodedDestination.java
  transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/EncodedPayload.java
  transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/EventInternal.java
  transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/SendRequest.java
  transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/TransportFactoryImpl.java
  transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/TransportImpl.java
  transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/TransportRuntime.java
  transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/logging/Logging.java
  transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/scheduling/persistence/SQLiteEventStore.java
  transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/scheduling/persistence/SchemaManager.java
  transport/transport-runtime/src/test/java/com/google/android/datatransport/runtime/TransportRuntimeTest.java
  transport/transport-runtime/src/test/java/com/google/android/datatransport/runtime/scheduling/jobscheduling/UploaderTest.java
  transport/transport-runtime/src/test/java/com/google/android/datatransport/runtime/scheduling/persistence/InMemoryEventStoreTest.java
  transport/transport-runtime/src/test/java/com/google/android/datatransport/runtime/scheduling/persistence/SQLiteEventStoreTest.java
  transport/transport-runtime/src/test/java/com/google/android/datatransport/runtime/scheduling/persistence/SchemaManagerTest.java
  transport/transport-runtime/transport-runtime.gradle
Labels: cla: yes, size/XL

#898 Generalize ComponentDiscovery to any android Service.
  firebase-common/src/main/AndroidManifest.xml
  firebase-common/src/main/java/com/google/firebase/FirebaseApp.java
  firebase-common/src/main/java/com/google/firebase/components/ComponentDiscoveryService.java
  firebase-components/src/main/AndroidManifest.xml
  firebase-components/src/main/java/com/google/firebase/components/ComponentDiscovery.java
  firebase-config/ktx/ktx.gradle
  firebase-database/ktx/ktx.gradle
  firebase-dynamic-links/firebase-dynamic-links.gradle
  firebase-inappmessaging-display/ktx/ktx.gradle
  firebase-inappmessaging/firebase-inappmessaging.gradle
  firebase-inappmessaging/ktx/ktx.gradle
  firebase-storage/ktx/ktx.gradle
Labels: cla: yes, size/M

#917 Remove EHOSTUNREACH check from SSLHandshake
  firebase-firestore/CHANGELOG.md
  firebase-firestore/src/main/java/com/google/firebase/firestore/remote/AbstractStream.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/remote/Datastore.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/remote/FirestoreChannel.java
Labels: api: firestore, cla: yes, size/S

#919 Fix race in credentialsProvider.setChangeListener
  firebase-firestore/CHANGELOG.md
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/FirestoreClient.java
Labels: api: firestore, cla: yes, size/M

#911 FIS error handling
  firebase-installations/api.txt
  firebase-installations/src/androidTest/java/com/google/firebase/installations/FirebaseInstallationsInstrumentedTest.java
  firebase-installations/src/androidTest/java/com/google/firebase/installations/FisAndroidTestConstants.java
  firebase-installations/src/main/java/com/google/firebase/installations/FirebaseInstallations.java
  firebase-installations/src/main/java/com/google/firebase/installations/Utils.java
  firebase-installations/src/main/java/com/google/firebase/installations/local/PersistedInstallationEntry.java
  firebase-installations/src/main/java/com/google/firebase/installations/remote/FirebaseInstallationServiceClient.java
  firebase-installations/src/main/java/com/google/firebase/installations/remote/InstallationResponse.java
Labels: cla: yes, size/L

#914 Attempt to fix memory leak referenced in #482
  firebase-inappmessaging-display/src/main/java/com/google/firebase/inappmessaging/display/FirebaseInAppMessagingDisplay.java
Labels: cla: yes, size/S

#909 Update FIAM version of Dagger to address #712
  firebase-inappmessaging-display/firebase-inappmessaging-display.gradle
  firebase-inappmessaging/firebase-inappmessaging.gradle
  transport/transport-runtime/transport-runtime.gradle
Labels: cla: yes, size/S

#923 Fix typo in unit test
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/IndexFreeQueryEngine.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/IndexFreeQueryEngineTest.java
Labels: api: firestore, cla: yes, size/XS

#927 Move changes to the correct release in release notes.
  firebase-firestore/CHANGELOG.md
Labels: api: firestore, cla: yes, size/S

#841 docs: add docs for firebase-database-ktx
  .opensource/project.json
  README.md
  docs/README.md
  docs/ktx/database.md
Labels: cla: yes, ktx:contrib, lang: kotlin, ok-to-test, size/M

#913 Removing license generation
  buildSrc/$project.buildDir/generated/third_party_licenses/third_party_licenses.json
  buildSrc/$project.buildDir/generated/third_party_licenses/third_party_licenses.txt
  buildSrc/build.gradle
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/license/DownloadLicenseTask.groovy
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/license/GenerateLicensesTask.groovy
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/license/GenerateLicensesTask.java
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/license/LicenseResolver.groovy
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/license/LicenseResolverPlugin.groovy
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/license/LicenseResolverPlugin.java
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/license/ProjectLicense.groovy
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/license/RemoteLicenseFetcher.groovy
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/license/ThirdPartyLicensesExtension.groovy
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/license/ThirdPartyLicensesExtension.java
  buildSrc/src/test/groovy/com/google/firebase/gradle/plugins/license/LicenseResolverPluginSpec.groovy
Labels: cla: yes, size/XXL

#928 Add Remote Config's defined TRANSPORT_FINAL number
  firebase-config/src/main/java/com/google/firebase/remoteconfig/RemoteConfigComponent.java
Labels: api: remoteconfig, cla: yes, size/XS

#922 Add smoke tests for Smart Reply.
  smoke-tests/build.gradle
  smoke-tests/src/main/java/com/google/firebase/testing/SmartReplyTest.java
  smoke-tests/src/main/java/com/google/firebase/testing/TestSuite.java
Labels: cla: yes, size/M

#870 feat: add builder ktx for FirebaseRemoteConfigSettings
  docs/ktx/remote-config.md
  firebase-config/api.txt
  firebase-config/ktx/src/main/kotlin/com/google/firebase/remoteconfig/ktx/RemoteConfig.kt
  firebase-config/ktx/src/test/kotlin/com/google/firebase/remoteconfig/ktx/RemoteConfigTests.kt
  firebase-config/src/main/java/com/google/firebase/remoteconfig/FirebaseRemoteConfigSettings.java
Labels: cla: yes, ktx:contrib, lang: kotlin, ok-to-test, size/M

#930 Added unspecified value to EventType enum and set as default.
  firebase-config/src/proto/com/google/android/gms/config/proto/client_metrics.proto
Labels: cla: yes, size/XS

#849 feat: add FirebaseFirestoreSettings builder ktx
  docs/ktx/firestore.md
  firebase-firestore/api.txt
  firebase-firestore/ktx/src/main/kotlin/com/google/firebase/firestore/ktx/Firestore.kt
  firebase-firestore/ktx/src/test/kotlin/com/google/firebase/firestore/ktx/FirestoreTests.kt
  firebase-firestore/src/main/java/com/google/firebase/firestore/FirebaseFirestoreSettings.java
Labels: cla: yes, ktx:contrib, lang: kotlin, needs-ok-to-test, size/M

#934 Update latest released version of firebase-common.
  firebase-common/gradle.properties
Labels: cla: yes, size/XS

#938 Change getHost annotation to match setHost.
  firebase-firestore/src/main/java/com/google/firebase/firestore/FirebaseFirestoreSettings.java
Labels: cla: yes, size/XS

#941 Change FIAM window manager visibility check
  firebase-inappmessaging-display/src/main/java/com/google/firebase/inappmessaging/display/internal/FiamWindowManager.java
Labels: cla: yes, size/XS

#940 Modify ConfigFetchHttpClient to log all successful Fetch calls.
  firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigFetchHttpClient.java
  firebase-config/src/test/java/com/google/firebase/remoteconfig/internal/ConfigFetchHttpClientTest.java
Labels: api: remoteconfig, cla: yes, size/S

#925 Migrate fiam to lflg.
  firebase-datatransport/src/main/java/com/google/firebase/datatransport/TransportRegistrar.java
  firebase-inappmessaging-display/gradle.properties
  firebase-inappmessaging/gradle.properties
Labels: cla: yes, size/S

#931 Add FisError to the persisted installation entry.
  firebase-installations/src/main/java/com/google/firebase/installations/local/PersistedInstallation.java
Labels: cla: yes, size/XS

#924 Reuse existing Iid as Fid
  firebase-installations/api.txt
  firebase-installations/src/androidTest/java/com/google/firebase/installations/FirebaseInstallationsInstrumentedTest.java
  firebase-installations/src/androidTest/java/com/google/firebase/installations/FisAndroidTestConstants.java
  firebase-installations/src/main/java/com/google/firebase/installations/FirebaseInstallations.java
  firebase-installations/src/main/java/com/google/firebase/installations/local/IidStore.java
  firebase-installations/src/main/java/com/google/firebase/installations/local/PersistedInstallation.java
Labels: cla: yes, size/L

#939 Make IN queries publicly available
  firebase-firestore/CHANGELOG.md
  firebase-firestore/api.txt
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/QueryTest.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/Query.java
Labels: api: firestore, cla: yes, size/M

#943 Update release version information for firestore.
  firebase-firestore/gradle.properties
Labels: cla: yes, size/XS

#730 Enable Index-Free queries
  firebase-firestore/CHANGELOG.md
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/FirestoreClient.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteSchema.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/spec/SpecTestCase.java
Labels: api: firestore, cla: yes, size/S

#950 Switch Config to only eagerly initialize in default app
  firebase-config/src/main/java/com/google/firebase/remoteconfig/RemoteConfigRegistrar.java
Labels: cla: yes, size/XS

#949 Sync proto naming with FIAM backend
  firebase-inappmessaging/src/androidTest/java/com/google/firebase/inappmessaging/FirebaseInAppMessagingFlowableTest.java
  firebase-inappmessaging/src/main/java/com/google/firebase/inappmessaging/internal/AnalyticsEventsManager.java
  firebase-inappmessaging/src/main/java/com/google/firebase/inappmessaging/internal/InAppMessageStreamManager.java
  firebase-inappmessaging/src/proto/firebase/inappmessaging/proto/common_types.proto
  firebase-inappmessaging/src/test/java/com/google/firebase/inappmessaging/FirebaseInAppMessagingTest.java
  firebase-inappmessaging/src/test/java/com/google/firebase/inappmessaging/internal/AnalyticsEventsManagerTest.java
  firebase-inappmessaging/src/test/java/com/google/firebase/inappmessaging/internal/DisplayCallbacksImplTest.java
  firebase-inappmessaging/src/test/java/com/google/firebase/inappmessaging/internal/InAppMessageStreamManagerTest.java
Labels: cla: yes, size/M

#955 Bump versions for release.
  firebase-common/gradle.properties
  firebase-firestore/gradle.properties
Labels: cla: yes, size/XS
