Repository firebase/firebase-android-sdk, pull requests merged in 2019-06, with the labels that each got.

#475 Use `Preconditions.checkNotNull` in FirebaseFunctions.
  firebase-functions/src/main/java/com/google/firebase/functions/FirebaseFunctions.java
Labels: cla: yes, size/S

#483 Fix firebase common
  firebase-common/firebase-common.gradle
  firebase-common/src/androidTest/java/com/google/firebase/FirebaseAppTest.java
Labels: cla: yes, size/S

#464 Implement @DocumentId annotation
  firebase-firestore/src/main/java/com/google/firebase/firestore/util/CustomClassMapper.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/util/DocumentId.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/util/MapperTest.java
Labels: cla: yes, size/XL

#485 Storage: Port test changes from cr/250550507
  firebase-database/src/androidTest/java/com/google/firebase/database/InfoTest.java
  firebase-storage/src/test/java/com/google/firebase/storage/AdaptiveStreamBufferTest.java
  firebase-storage/src/test/java/com/google/firebase/storage/DeleteTest.java
  firebase-storage/src/test/java/com/google/firebase/storage/DependencyTest.java
  firebase-storage/src/test/java/com/google/firebase/storage/DownloadTest.java
  firebase-storage/src/test/java/com/google/firebase/storage/ListTest.java
  firebase-storage/src/test/java/com/google/firebase/storage/MetadataTest.java
  firebase-storage/src/test/java/com/google/firebase/storage/PathingTest.java
  firebase-storage/src/test/java/com/google/firebase/storage/StorageReferenceTest.java
  firebase-storage/src/test/java/com/google/firebase/storage/StreamProgressWrapperTest.java
  firebase-storage/src/test/java/com/google/firebase/storage/UploadTest.java
Labels: cla: yes, size/M

#487 Storage: Add TestUtil.await
  firebase-storage/src/test/java/com/google/firebase/storage/AdaptiveStreamBufferTest.java
  firebase-storage/src/test/java/com/google/firebase/storage/DeleteTest.java
  firebase-storage/src/test/java/com/google/firebase/storage/DependencyTest.java
  firebase-storage/src/test/java/com/google/firebase/storage/DownloadTest.java
  firebase-storage/src/test/java/com/google/firebase/storage/ListTest.java
  firebase-storage/src/test/java/com/google/firebase/storage/MetadataTest.java
  firebase-storage/src/test/java/com/google/firebase/storage/PathingTest.java
  firebase-storage/src/test/java/com/google/firebase/storage/StorageReferenceTest.java
  firebase-storage/src/test/java/com/google/firebase/storage/TestUtil.java
  firebase-storage/src/test/java/com/google/firebase/storage/UploadTest.java
  firebase-storage/src/test/java/com/google/firebase/storage/network/MockConnectionFactory.java
  firebase-storage/src/testUtil/java/com/google/firebase/storage/TestUploadHelper.java
Labels: cla: yes, size/XL

#484 Reduce flakiness of license fetcher.
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/license/DownloadLicenseTask.groovy
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/license/RemoteLicenseFetcher.groovy
Labels: cla: yes, size/L

#489 Fix dependency type resolution.
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/FirebaseLibraryExtension.java
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/publish/Publisher.groovy
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/publish/PublishingPlugin.groovy
Labels: cla: yes, size/M

#455 Make clearPersistence() publicly available
  firebase-firestore/CHANGELOG.md
  firebase-firestore/src/main/java/com/google/firebase/firestore/FirebaseFirestore.java
Labels: api: firestore, cla: yes, size/XS

#477 Moving SSL and GRPC Stub initialization to separate thread
  firebase-firestore/CHANGELOG.md
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/testutil/IntegrationTestUtil.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/FirebaseFirestore.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/remote/AbstractStream.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/remote/Datastore.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/remote/FirestoreChannel.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/remote/GrpcCallProvider.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/remote/IncomingStreamObserver.java
Labels: cla: yes, size/XL

#493 Re-enable debug build type.
  root-project.gradle
Labels: cla: yes, size/S

#499 Storage Copybara: Fixing lint errors
  firebase-storage/src/main/java/com/google/firebase/storage/CancellableTask.java
  firebase-storage/src/main/java/com/google/firebase/storage/ControllableTask.java
  firebase-storage/src/main/java/com/google/firebase/storage/OnPausedListener.java
  firebase-storage/src/main/java/com/google/firebase/storage/OnProgressListener.java
  firebase-storage/src/main/java/com/google/firebase/storage/StorageException.java
  firebase-storage/src/main/java/com/google/firebase/storage/StorageTask.java
  firebase-storage/src/main/java/com/google/firebase/storage/StorageTaskManager.java
  firebase-storage/src/main/java/com/google/firebase/storage/TaskListenerImpl.java
  firebase-storage/src/main/java/com/google/firebase/storage/network/ResumableUploadCancelRequest.java
  firebase-storage/src/test/java/com/google/firebase/storage/UploadTest.java
Labels: cla: yes, size/L

#500 Storage Copybara: Fix Javadoc
  firebase-storage/src/main/java/com/google/firebase/storage/internal/AdaptiveStreamBuffer.java
Labels: cla: yes, size/S

#498 Storage Copybara: MissingDefault
  firebase-storage/src/main/java/com/google/firebase/storage/StorageTask.java
Labels: cla: yes, size/XS

#497 Storage Copybara: SuppressWarnings("ThreadPriorityCheck")
  firebase-storage/src/main/java/com/google/firebase/storage/StorageTaskScheduler.java
Labels: cla: yes, size/XS

#496 Storage Copybara: Fix go/errorprone/bugpattern/ParameterName
  firebase-storage/src/main/java/com/google/firebase/storage/ListResult.java
Labels: cla: yes, size/XS

#501 Ignore empty message string in FirebaseFunctionsException
  firebase-functions/src/main/java/com/google/firebase/functions/FirebaseFunctionsException.java
Labels: cla: yes, ok-to-test, size/XS

#490 Fix for coverage collection.
  tools/measurement/coverage/coverage.gradle
Labels: cla: yes, size/XS

#503 Storage Copybara: ThreeLetterTimeZoneID
  firebase-storage/src/testUtil/java/com/google/firebase/storage/TestCommandHelper.java
Labels: cla: yes, size/XS

#504 Copybara Storage: Fix Storage Lint
  firebase-storage/src/androidTest/java/com/google/firebase/storage/IntegrationTest.java
  firebase-storage/src/test/java/com/google/firebase/storage/ListTest.java
  firebase-storage/src/test/java/com/google/firebase/storage/RetryRule.java
  firebase-storage/src/test/java/com/google/firebase/storage/network/NetworkLayerMock.java
  firebase-storage/src/testUtil/java/com/google/firebase/storage/TestDownloadHelper.java
  firebase-storage/src/testUtil/java/com/google/firebase/storage/TestUploadHelper.java
Labels: cla: yes, size/S

#471 Add '-Werror' for main build and suppress one deprecation warning
  firebase-firestore/firebase-firestore.gradle
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/ArrayTransformsServerApplicationTest.java
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/ArrayTransformsTest.java
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/CursorTest.java
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/FieldsTest.java
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/FirestoreTest.java
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/ListenerRegistrationTest.java
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/NumericTransformsTest.java
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/POJOTest.java
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/QueryTest.java
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/ServerTimestampTest.java
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/SmokeTest.java
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/SourceTest.java
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/TransactionTest.java
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/WriteBatchTest.java
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/remote/RemoteStoreTest.java
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/testutil/IntegrationTestUtil.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/remote/AndroidConnectivityMonitor.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/remote/FirestoreCallCredentials.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/FirestoreRegistrarTest.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/EncodedPathTest.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/PersistenceTestHelpers.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/SQLiteSchemaTest.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/spec/SpecTestCase.java
Labels: cla: yes, size/L

#509 Storage Copybara: Fixing ErrorProne Warnings
  firebase-storage/src/test/java/com/google/firebase/storage/TestUtil.java
  firebase-storage/src/test/java/com/google/firebase/storage/network/MockConnectionFactory.java
Labels: cla: yes, size/M

#510 Storage: Fix Preconditions checks in tests
  firebase-storage/src/testUtil/java/com/google/firebase/storage/TestDownloadHelper.java
Labels: cla: yes, size/XS

#512 Fix Apache license fetching.
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/license/RemoteLicenseFetcher.groovy
Labels: cla: yes, size/M

#505 Migrate from is(Not)SameAs to is(Not)SameInstanceAs.
  firebase-common/ktx/src/test/kotlin/com/google/firebase/ktx/Tests.kt
  firebase-common/src/androidTest/java/com/google/firebase/FirebaseAppTest.java
  firebase-common/src/androidTest/java/com/google/firebase/FirebaseOptionsTest.java
  firebase-common/src/test/java/com/google/firebase/components/ComponentRuntimeTest.java
  firebase-common/src/test/java/com/google/firebase/components/ComponentTest.java
  firebase-common/src/test/java/com/google/firebase/components/LazyTest.java
  firebase-common/src/test/java/com/google/firebase/components/RestrictedComponentContainerTest.java
  firebase-firestore/ktx/src/test/kotlin/com/google/firebase/firestore/ktx/FirestoreTests.kt
  firebase-functions/ktx/src/test/kotlin/com/google/firebase/functions/ktx/FunctionsTests.kt
  root-project.gradle
  smoke-tests/build.gradle
Labels: cla: yes, ok-to-test, size/M

#516 Update protos to include IN and ARRAY_CONTAINS_ANY
  firebase-firestore/src/proto/google/firestore/v1/query.proto
Labels: api: firestore, cla: yes, size/S

#514 Add Firebase Segmentation SDK and some skeleton code in Firebase Android SDK
  firebase-segmentation/firebase-segmentation.gradle
  firebase-segmentation/gradle.properties
  firebase-segmentation/lint.xml
  firebase-segmentation/src/androidTest/AndroidManifest.xml
  firebase-segmentation/src/androidTest/java/com/google/firebase/segmentation/FirebaseSegmentationInstrumentedTest.java
  firebase-segmentation/src/main/AndroidManifest.xml
  firebase-segmentation/src/main/java/com/google/firebase/segmentation/FirebaseSegmentation.java
  firebase-segmentation/src/main/java/com/google/firebase/segmentation/FirebaseSegmentationRegistrar.java
  firebase-segmentation/src/test/java/com/google/firebase/segmentation/FirebaseSegmentationRegistrarTest.java
  subprojects.cfg
Labels: cla: yes, size/L

#517 Add type arguments in StorageTaskManager
  firebase-storage/src/main/java/com/google/firebase/storage/StorageTaskManager.java
Labels: cla: yes, size/S

#515 Output artifact list during local publishing.
  buildSrc/build.gradle
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/ci/AffectedProjectFinder.groovy
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/ci/ContinuousIntegrationPlugin.groovy
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/ci/SmokeTestsPlugin.groovy
  root-project.gradle
Labels: cla: yes, size/L

#523 fix functions
  firebase-functions/firebase-functions.gradle
  firebase-functions/gradle.properties
  firebase-functions/ktx/ktx.gradle
  firebase-functions/ktx/src/androidTest/AndroidManifest.xml
  firebase-functions/ktx/src/main/AndroidManifest.xml
  firebase-functions/src/main/AndroidManifest.xml
Labels: cla: yes, size/S

#522 Set test type to release only in CI.
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/FirebaseLibraryPlugin.java
  root-project.gradle
Labels: cla: yes, size/M

#525 Minor fix to error message to match the admin sdk.
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/ValidationTest.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/FieldPath.java
Labels: cla: yes, size/XS

#527 Added clean task to smoke tests.
  smoke-tests/build.gradle
Labels: cla: yes, size/S

#526 Update deps to post-androidx gms versions.
  fiamui-app/fiamui-app.gradle
  firebase-common/firebase-common.gradle
  firebase-common/gradle.properties
  firebase-database-collection/firebase-database-collection.gradle
  firebase-database-collection/gradle.properties
  firebase-database/firebase-database.gradle
  firebase-database/gradle.properties
  firebase-datatransport/gradle.properties
  firebase-firestore/firebase-firestore.gradle
  firebase-firestore/gradle.properties
  firebase-firestore/ktx/ktx.gradle
  firebase-functions/firebase-functions.gradle
  firebase-functions/gradle.properties
  firebase-functions/ktx/ktx.gradle
  firebase-storage/firebase-storage.gradle
  firebase-storage/gradle.properties
  firebase-storage/test-app/test-app.gradle
  protolite-well-known-types/gradle.properties
  tools/measurement/apksize/src/firestore/firestore.gradle
  transport/transport-api/gradle.properties
  transport/transport-backend-cct/gradle.properties
  transport/transport-runtime/gradle.properties
Labels: cla: yes, size/L

#528 Copy firebase-firestore-ktx dependencies on firestore into its own subfolder
  firebase-firestore/ktx/ktx.gradle
  firebase-firestore/ktx/src/test/java/com/google/firebase/firestore/TestAccessHelper.java
  firebase-firestore/ktx/src/test/java/com/google/firebase/firestore/TestUtil.java
  firebase-firestore/ktx/src/test/java/com/google/firebase/firestore/testutil/TestUtil.java
Labels: api: firestore, cla: yes, size/XL

#530 Bump firestore version for release
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/publish/Publisher.groovy
  firebase-firestore/gradle.properties
Labels: cla: yes, size/XS

#524 [Firebase Segmentation] Add custom installation id cache layer and tests for it.
  buildSrc/build.gradle
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/FirebaseLibraryPlugin.java
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/ci/AffectedProjectFinder.groovy
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/ci/ContinuousIntegrationPlugin.groovy
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/ci/SmokeTestsPlugin.groovy
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/publish/Publisher.groovy
  fiamui-app/fiamui-app.gradle
  firebase-common/firebase-common.gradle
  firebase-common/gradle.properties
  firebase-database-collection/firebase-database-collection.gradle
  firebase-database-collection/gradle.properties
  firebase-database/firebase-database.gradle
  firebase-database/gradle.properties
  firebase-datatransport/gradle.properties
  firebase-firestore/firebase-firestore.gradle
  firebase-firestore/gradle.properties
  firebase-firestore/ktx/ktx.gradle
  firebase-firestore/ktx/src/test/java/com/google/firebase/firestore/TestAccessHelper.java
  firebase-firestore/ktx/src/test/java/com/google/firebase/firestore/TestUtil.java
  firebase-firestore/ktx/src/test/java/com/google/firebase/firestore/testutil/TestUtil.java
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/ValidationTest.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/FieldPath.java
  firebase-functions/firebase-functions.gradle
  firebase-functions/gradle.properties
  firebase-functions/ktx/ktx.gradle
  firebase-functions/ktx/src/androidTest/AndroidManifest.xml
  firebase-functions/ktx/src/main/AndroidManifest.xml
  firebase-functions/src/main/AndroidManifest.xml
  firebase-segmentation/firebase-segmentation.gradle
  firebase-segmentation/src/androidTest/java/com/google/firebase/segmentation/CustomInstallationIdCacheTest.java
  firebase-segmentation/src/main/java/com/google/firebase/segmentation/CustomInstallationIdCache.java
  firebase-segmentation/src/main/java/com/google/firebase/segmentation/CustomInstallationIdCacheEntryValue.java
  firebase-storage/firebase-storage.gradle
  firebase-storage/gradle.properties
  firebase-storage/src/main/java/com/google/firebase/storage/StorageTaskManager.java
  firebase-storage/test-app/test-app.gradle
  protolite-well-known-types/gradle.properties
  root-project.gradle
  smoke-tests/build.gradle
  tools/measurement/apksize/src/firestore/firestore.gradle
  transport/transport-api/gradle.properties
  transport/transport-backend-cct/gradle.properties
  transport/transport-runtime/gradle.properties
Labels: cla: yes, size/XXL

#532 Restrict coverage collection to release builds.
  root-project.gradle
Labels: cla: yes, size/XS

#533 Fix some deprecations
  firebase-segmentation/src/androidTest/java/com/google/firebase/segmentation/CustomInstallationIdCacheTest.java
  firebase-segmentation/src/androidTest/java/com/google/firebase/segmentation/FirebaseSegmentationInstrumentedTest.java
Labels: cla: yes, size/S

#534 package refactor
  firebase-segmentation/src/androidTest/java/com/google/firebase/segmentation/local/CustomInstallationIdCacheTest.java
  firebase-segmentation/src/main/java/com/google/firebase/segmentation/local/CustomInstallationIdCache.java
  firebase-segmentation/src/main/java/com/google/firebase/segmentation/local/CustomInstallationIdCacheEntryValue.java
Labels: cla: yes, size/XS

#537 Fix offline transport handling.
  transport/transport-backend-cct/src/main/java/com/google/android/datatransport/cct/CctTransportBackend.java
  transport/transport-backend-cct/src/test/java/com/google/android/datatransport/cct/CctTransportBackendTest.java
Labels: cla: yes, size/M

#536 Backport changelog updates from past few android releases
  firebase-firestore/CHANGELOG.md
Labels: api: firestore, cla: yes, size/S

#508 Fail Firestore client if we can't establish SSL connection
  firebase-firestore/CHANGELOG.md
  firebase-firestore/src/main/java/com/google/firebase/firestore/remote/AbstractStream.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/remote/Datastore.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/remote/FirestoreChannel.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/util/Util.java
Labels: cla: yes, size/M

#538 Include collection time in report. Use product name instead of id.
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/measurement/coverage/GenerateMeasurementsTask.groovy
  buildSrc/src/test/groovy/com/google/firebase/gradle/plugins/measurement/apksize/ApkSizeTestProject.groovy
  tools/measurement/coverage/coverage.gradle
Labels: cla: yes, size/M

#541 Simplify FieldValueOptions
  firebase-firestore/src/main/java/com/google/firebase/firestore/DocumentSnapshot.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/model/value/ArrayValue.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/model/value/FieldValue.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/model/value/FieldValueOptions.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/model/value/ObjectValue.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/model/value/ServerTimestampValue.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/model/value/TimestampValue.java
Labels: cla: yes, size/L

#519 Add IN and ARRAY_CONTAINS_ANY (not publicly exposed)
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/FirestoreTest.java
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/QueryTest.java
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/ValidationTest.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/Query.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/Filter.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/Query.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/RelationFilter.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/remote/RemoteSerializer.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/core/QueryTest.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/remote/RemoteSerializerTest.java
  firebase-firestore/src/testUtil/java/com/google/firebase/firestore/testutil/TestUtil.java
Labels: api: firestore, cla: yes, size/XL

#543 Add Remote Config smoke tests.
  smoke-tests/build.gradle
  smoke-tests/configure.gradle
  smoke-tests/src/combined/java/com/google/firebase/testing/combined/AllTests.java
  smoke-tests/src/remoteConfig/java/com/google/firebase/testing/remoteconfig/RemoteConfigTest.java
Labels: cla: yes, size/M

#548 Generalize parent repository logic.
  smoke-tests/build.gradle
  smoke-tests/configure.gradle
Labels: cla: yes, size/M

#550 Backporting documentation changes
  firebase-firestore/src/main/java/com/google/firebase/firestore/FirebaseFirestore.java
Labels: cla: yes, size/S

#553 Update Remote Config and AB Testing versions
  firebase-abt/gradle.properties
  firebase-remote-config/gradle.properties
Labels: cla: yes, size/XS

#554 Disable FTL for AB Testing
  firebase-abt/firebase-abt.gradle
Labels: cla: yes, size/XS

#556 Fix FirebaseFirestore formatting.
  firebase-firestore/src/main/java/com/google/firebase/firestore/FirebaseFirestore.java
Labels: cla: yes, size/XS

#557 Remove most product flavors from smoke tests.
  smoke-tests/build.gradle
  smoke-tests/src/combined/java/com/google/firebase/testing/database/DatabaseTest.java
  smoke-tests/src/combined/java/com/google/firebase/testing/firestore/FirestoreTest.java
  smoke-tests/src/combined/java/com/google/firebase/testing/functions/FunctionsTest.java
  smoke-tests/src/combined/java/com/google/firebase/testing/remoteconfig/RemoteConfigTest.java
  smoke-tests/src/combined/java/com/google/firebase/testing/storage/StorageTest.java
  smoke-tests/src/database/AndroidManifest.xml
  smoke-tests/src/firestore/AndroidManifest.xml
  smoke-tests/src/storage/AndroidManifest.xml
Labels: cla: yes, size/M

#540 Add option to run tests against emulator
  .idea/runConfigurations/FirestoreProdIntegrationTest.xml
  .idea/runConfigurations/Firestore_Integration_Tests__Firestore_Emulator_.xml
  firebase-firestore/firebase-firestore.gradle
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/testutil/IntegrationTestUtil.java
Labels: api: firestore, cla: yes, size/M

#545 Add the state machine of updating custom installation id in the local cache and update to Firebase Segmentation backend.
  firebase-segmentation/firebase-segmentation.gradle
  firebase-segmentation/src/androidTest/java/com/google/firebase/segmentation/FirebaseSegmentationInstrumentedTest.java
  firebase-segmentation/src/androidTest/java/com/google/firebase/segmentation/local/CustomInstallationIdCacheTest.java
  firebase-segmentation/src/main/java/com/google/firebase/segmentation/FirebaseSegmentation.java
  firebase-segmentation/src/main/java/com/google/firebase/segmentation/SetCustomInstallationIdException.java
  firebase-segmentation/src/main/java/com/google/firebase/segmentation/Utils.java
  firebase-segmentation/src/main/java/com/google/firebase/segmentation/local/CustomInstallationIdCache.java
  firebase-segmentation/src/main/java/com/google/firebase/segmentation/local/CustomInstallationIdCacheEntryValue.java
  firebase-segmentation/src/main/java/com/google/firebase/segmentation/remote/SegmentationServiceClient.java
  firebase-segmentation/src/test/java/com/google/firebase/segmentation/FirebaseSegmentationRegistrarTest.java
Labels: cla: yes, size/XL

#562 Update documentation to reflect emulator is default for integration tests.
  firebase-firestore/README.md
Labels: api: firestore, cla: yes, size/S

#560 Allow IN queries with arrays of documentIds
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/ValidationTest.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/Query.java
Labels: api: firestore, cla: yes, size/L

#563 Migrate ExperimentPayload to AB Testing
  firebase-abt/firebase-abt.gradle
  firebase-abt/src/proto/com/google/protos/developers/mobile/abt/proto/experiment_payload.proto
  firebase-config/firebase-config.gradle
Labels: cla: yes, size/M

#567 Run IN query integration tests only when running against emulator
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/QueryTest.java
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/testutil/IntegrationTestUtil.java
Labels: api: firestore, cla: yes, size/M

#569 Add Inapp Messaging smoke test.
  smoke-tests/build.gradle
  smoke-tests/src/combined/java/com/google/firebase/testing/inappmessaging/InappMessagingTest.java
Labels: cla: yes, size/M

#572 Add Proguard Files to Smoke Tests
  smoke-tests/build.gradle
  smoke-tests/gradle.properties
  smoke-tests/infrastructure-rules.pro
  smoke-tests/smoke-test-rules.pro
  smoke-tests/src/androidTest/java/com/google/firebase/testing/common/SmokeTestSuite.java
Labels: cla: yes, size/M

#571 Move DocumentId to public space
  firebase-firestore/CHANGELOG.md
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/POJOTest.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/DocumentId.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/util/CustomClassMapper.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/util/DocumentId.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/util/MapperTest.java
Labels: cla: yes, size/L

#561 Performance: Don't deserialize full document Proto for Query execution
  firebase-firestore/CHANGELOG.md
  firebase-firestore/ktx/src/test/java/com/google/firebase/firestore/testutil/TestUtil.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/LocalSerializer.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/model/Document.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/model/mutation/PatchMutation.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/model/mutation/SetMutation.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/model/mutation/TransformMutation.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/remote/RemoteSerializer.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/DocumentSnapshotTest.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/QuerySnapshotTest.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/LocalStoreTestCase.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/LruGarbageCollectorTestCase.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/model/DocumentTest.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/model/MutationTest.java
  firebase-firestore/src/test/resources/json/listen_spec_test.json
  firebase-firestore/src/test/resources/json/orderby_spec_test.json
  firebase-firestore/src/testUtil/java/com/google/firebase/firestore/testutil/TestUtil.java
Labels: api: firestore, cla: yes, size/L

#570 Refactor Filters
  firebase-firestore/ktx/src/test/java/com/google/firebase/firestore/testutil/TestUtil.java
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/QueryTest.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/Query.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/ArrayContainsAnyFilter.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/ArrayContainsFilter.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/FieldFilter.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/Filter.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/InFilter.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/KeyFieldFilter.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/KeyFieldInFilter.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/NaNFilter.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/NullFilter.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/Query.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/IndexedQueryEngine.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/remote/RemoteSerializer.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/remote/RemoteSerializerTest.java
  firebase-firestore/src/testUtil/java/com/google/firebase/firestore/testutil/TestUtil.java
Labels: api: firestore, cla: yes, size/XL

#564 Store the coerced base value in the BaseMutation
  firebase-firestore/CHANGELOG.md
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/NumericTransformsTest.java
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/ServerTimestampTest.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/LocalStore.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/model/mutation/ArrayTransformOperation.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/model/mutation/DeleteMutation.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/model/mutation/FieldMask.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/model/mutation/FieldTransform.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/model/mutation/Mutation.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/model/mutation/NumericIncrementTransformOperation.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/model/mutation/PatchMutation.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/model/mutation/ServerTimestampOperation.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/model/mutation/SetMutation.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/model/mutation/TransformMutation.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/model/mutation/TransformOperation.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/model/value/ObjectValue.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/model/FieldValueTest.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/model/MutationTest.java
Labels: api: firestore, cla: yes, size/L

#513 Firebase Storage: Fix typo in method name
  firebase-storage/src/main/java/com/google/firebase/storage/GetDownloadUrlTask.java
  firebase-storage/src/main/java/com/google/firebase/storage/network/NetworkRequest.java
Labels: cla: yes, size/XS

#576 bump versions
  firebase-firestore/gradle.properties
  firebase-storage/gradle.properties
Labels: cla: yes, size/XS
