Repository firebase/firebase-android-sdk, pull requests merged in 2019-02, with the labels that each got.

#226 Port flaky test fix from web.
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/ServerTimestampTest.java
Labels: cla: yes, size/XS

#228 Bumping versions
  firebase-database/gradle.properties
  firebase-firestore/gradle.properties
Labels: cla: yes, size/XS

#236 Rename OutOfBandLibraryVersionRegistrar to GlobalLibraryVersionRegistrar
  firebase-common/src/main/java/com/google/firebase/platforminfo/DefaultUserAgentPublisher.java
  firebase-common/src/main/java/com/google/firebase/platforminfo/GlobalLibraryVersionRegistrar.java
  firebase-common/src/test/java/com/google/firebase/platforminfo/DefaultUserAgentPublisherTest.java
  firebase-common/src/test/java/com/google/firebase/platforminfo/GlobalLibraryVersionRegistrarTest.java
Labels: cla: yes, size/M

#231 Adjust sqlite size calculation to account for WAL
  firebase-firestore/CHANGELOG.md
  firebase-firestore/firebase-firestore.gradle
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLitePersistence.java
Labels: cla: yes, size/S

#234 Implement firebase-common-ktx Kotlin library.
  firebase-common-ktx/firebase-common-ktx.gradle
  firebase-common-ktx/gradle.properties
  firebase-common-ktx/src/main/AndroidManifest.xml
  firebase-common-ktx/src/main/kotlin/com/google/firebase/ktx/Firebase.kt
  firebase-common-ktx/src/test/kotlin/com/google/firebase/ktx/Tests.kt
  firebase-common/src/main/java/com/google/firebase/FirebaseApp.java
  root-project.gradle
  subprojects.cfg
Labels: cla: yes, size/L

#235 Fix version in x-goog-api-client-value and logcat
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/Version.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/util/AsyncQueue.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/util/FirestoreChannel.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/util/Logger.java
Labels: cla: yes, size/M

#218 Registering versions
  firebase-database/firebase-database.gradle
  firebase-database/gradle.properties
  firebase-database/src/main/AndroidManifest.xml
  firebase-database/src/main/java/com/google/firebase/database/DatabaseRegistrar.java
  firebase-database/src/test/java/com/google/firebase/database/DatabaseRegistrarTest.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/FirestoreRegistrar.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/FirestoreRegistrarTest.java
  firebase-functions/firebase-functions.gradle
  firebase-functions/gradle.properties
  firebase-functions/src/main/java/com/google/firebase/functions/FunctionsRegistrar.java
  firebase-functions/src/test/java/com/google/firebase/functions/FunctionsRegistrarTest.java
  firebase-storage/firebase-storage.gradle
  firebase-storage/gradle.properties
  firebase-storage/src/main/AndroidManifest.xml
  firebase-storage/src/main/java/com/google/firebase/storage/StorageRegistrar.java
  firebase-storage/src/test/java/com/google/firebase/storage/StorageRegistrarTest.java
Labels: cla: yes, size/L

#241 Disable verbose stdout logging for storage and rtdb.
  firebase-database/firebase-database.gradle
  firebase-storage/firebase-storage.gradle
Labels: cla: yes, size/S

#242 Rename libs.
  firebase-common/src/androidTest/java/com/google/firebase/FirebaseAppTest.java
  firebase-common/src/main/java/com/google/firebase/FirebaseApp.java
  firebase-database/src/main/java/com/google/firebase/database/DatabaseRegistrar.java
  firebase-database/src/test/java/com/google/firebase/database/DatabaseRegistrarTest.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/FirestoreRegistrar.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/FirestoreRegistrarTest.java
  firebase-functions/src/main/java/com/google/firebase/functions/FunctionsRegistrar.java
  firebase-functions/src/test/java/com/google/firebase/functions/FunctionsRegistrarTest.java
  firebase-storage/src/main/java/com/google/firebase/storage/StorageRegistrar.java
  firebase-storage/src/test/java/com/google/firebase/storage/StorageRegistrarTest.java
Labels: cla: yes, size/S

#245 Update versions for the release.
  firebase-common/gradle.properties
  firebase-database/gradle.properties
  firebase-firestore/gradle.properties
  firebase-functions/gradle.properties
  firebase-storage/gradle.properties
Labels: cla: yes, size/S

#248 Update the versions of functions test app dependencies in package-lock.json.
  test-apps/functions-test-app/functions/package-lock.json
Labels: cla: yes, size/XXL

#243 Add gradle task for generating JaCoCo coverage report for unit tests.
  root-project.gradle
Labels: cla: yes, size/S

#251 Remove the deprecated category attribute from errorprone bug checkers.
  tools/errorprone/src/main/java/com/google/firebase/errorprone/ComponentsAppGetCheck.java
  tools/errorprone/src/main/java/com/google/firebase/errorprone/NoStaticOrDefaultMethodsInInterfaces.java
Labels: cla: yes, size/XS

#224 Implement settable timeouts in Functions.
  firebase-functions/firebase-functions.gradle
  firebase-functions/src/androidTest/AndroidManifest.xml
  firebase-functions/src/androidTest/java/com/google/firebase/functions/CallTest.java
  firebase-functions/src/androidTest/test/index.js
  firebase-functions/src/androidTest/test/start.sh
  firebase-functions/src/main/java/com/google/firebase/functions/FirebaseFunctions.java
  firebase-functions/src/main/java/com/google/firebase/functions/HttpsCallOptions.java
  firebase-functions/src/main/java/com/google/firebase/functions/HttpsCallableReference.java
Labels: cla: yes, size/L

#255 Test how to handle all caps properties
  firebase-firestore/src/test/java/com/google/firebase/firestore/util/MapperTest.java
Labels: cla: yes, size/M

#240 Use PropertyName value for enum serialization/deserialization
  firebase-firestore/src/main/java/com/google/firebase/firestore/util/CustomClassMapper.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/util/MapperTest.java
Labels: cla: yes, size/M
