Repository firebase/firebase-android-sdk, pull requests merged in 2019-11, with the labels that each got.

#960 Add JSON payload support to CCT destination.
  transport/transport-backend-cct/src/main/java/com/google/android/datatransport/cct/CCTDestination.java
  transport/transport-backend-cct/src/main/java/com/google/android/datatransport/cct/CctTransportBackend.java
  transport/transport-backend-cct/src/main/proto/google/cct/google_cct.proto
  transport/transport-backend-cct/src/test/java/com/google/android/datatransport/cct/CctDestinationTest.java
  transport/transport-backend-cct/src/test/java/com/google/android/datatransport/cct/CctTransportBackendTest.java
  transport/transport-backend-cct/transport-backend-cct.gradle
Labels: cla: yes, size/L

#963 [1/3] Split Query and Target and make RemoteStore and LocalStore work with Targets
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/Query.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/SyncEngine.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/Target.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/LocalSerializer.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/LocalStore.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/MemoryQueryCache.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/QueryCache.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/QueryData.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteQueryCache.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/remote/RemoteSerializer.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/remote/RemoteStore.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/remote/WatchChangeAggregator.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/LocalSerializerTest.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/LocalStoreTestCase.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/LruGarbageCollectorTestCase.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/QueryCacheTestCase.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/SQLiteQueryCacheTest.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/remote/MockDatastore.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/remote/RemoteSerializerTest.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/spec/SpecTestCase.java
  firebase-firestore/src/testUtil/java/com/google/firebase/firestore/testutil/TestUtil.java
Labels: api: firestore, cla: yes, size/XL

#962 Json encoder library.
  encoders/api.txt
  encoders/encoders.gradle
  encoders/gradle.properties
  encoders/proguard.txt
  encoders/src/main/AndroidManifest.xml
  encoders/src/main/java/com/google/firebase/encoders/DataEncoder.java
  encoders/src/main/java/com/google/firebase/encoders/Encoder.java
  encoders/src/main/java/com/google/firebase/encoders/EncodingException.java
  encoders/src/main/java/com/google/firebase/encoders/ObjectEncoder.java
  encoders/src/main/java/com/google/firebase/encoders/ObjectEncoderContext.java
  encoders/src/main/java/com/google/firebase/encoders/ValueEncoder.java
  encoders/src/main/java/com/google/firebase/encoders/ValueEncoderContext.java
  encoders/src/main/java/com/google/firebase/encoders/json/JsonDataEncoderBuilder.java
  encoders/src/main/java/com/google/firebase/encoders/json/JsonValueObjectEncoderContext.java
  encoders/src/test/java/com/google/firebase/encoders/json/JsonValueObjectEncoderContextTest.java
  subprojects.cfg
Labels: cla: yes, size/XL

#839 Implement firebase-dynamic-links-ktx
  firebase-dynamic-links/api.txt
  firebase-dynamic-links/ktx/gradle.properties
  firebase-dynamic-links/ktx/ktx.gradle
  firebase-dynamic-links/ktx/src/main/AndroidManifest.xml
  firebase-dynamic-links/ktx/src/main/kotlin/com/google/firebase/dynamiclinks/ktx/FirebaseDynamicLinks.kt
  firebase-dynamic-links/ktx/src/test/kotlin/com/google/firebase/dynamiclinks/ktx/DynamicLinksTests.kt
  firebase-dynamic-links/src/main/java/com/google/firebase/dynamiclinks/DynamicLink.java
  subprojects.cfg
Labels: cla: yes, ktx:contrib, lang: kotlin, ok-to-test, size/XL

#968 Fix modifiers to address warnings
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/measurement/UploadMeasurementsTask.groovy
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/measurement/coverage/GenerateMeasurementsTask.groovy
Labels: cla: yes, size/S

#957 Firebase InAppMessaging KTX extensions docs
  .opensource/project.json
  README.md
  docs/README.md
  docs/ktx/inappmessaging-display.md
  docs/ktx/inappmessaging.md
Labels: cla: yes, size/M

#970 Allow querying for arrays in IN queries
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/QueryTest.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/Query.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/UserDataConverter.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/UserData.java
Labels: api: firestore, cla: yes, size/M

#965 [2/3] Make SyncEngine able to work with both Query and Target
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/SyncEngine.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/LocalStore.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/LocalStoreTestCase.java
Labels: api: firestore, cla: yes, size/L

#967 Move encoders to subproject firebase-encoders
  encoders/encoders.gradle
  encoders/firebase-encoders/api.txt
  encoders/firebase-encoders/firebase-encoders.gradle
  encoders/firebase-encoders/gradle.properties
  encoders/firebase-encoders/proguard.txt
  encoders/firebase-encoders/src/main/AndroidManifest.xml
  encoders/firebase-encoders/src/main/java/com/google/firebase/encoders/DataEncoder.java
  encoders/firebase-encoders/src/main/java/com/google/firebase/encoders/Encoder.java
  encoders/firebase-encoders/src/main/java/com/google/firebase/encoders/EncodingException.java
  encoders/firebase-encoders/src/main/java/com/google/firebase/encoders/ObjectEncoder.java
  encoders/firebase-encoders/src/main/java/com/google/firebase/encoders/ObjectEncoderContext.java
  encoders/firebase-encoders/src/main/java/com/google/firebase/encoders/ValueEncoder.java
  encoders/firebase-encoders/src/main/java/com/google/firebase/encoders/ValueEncoderContext.java
  encoders/firebase-encoders/src/main/java/com/google/firebase/encoders/json/JsonDataEncoderBuilder.java
  encoders/firebase-encoders/src/main/java/com/google/firebase/encoders/json/JsonValueObjectEncoderContext.java
  encoders/firebase-encoders/src/test/java/com/google/firebase/encoders/json/JsonValueObjectEncoderContextTest.java
  subprojects.cfg
Labels: cla: yes, size/M

#978 add 307 support for redirection urls
  transport/transport-backend-cct/src/main/java/com/google/android/datatransport/cct/CctTransportBackend.java
  transport/transport-backend-cct/src/test/java/com/google/android/datatransport/cct/CctTransportBackendTest.java
Labels: cla: yes, size/M

#975 Update versions to match latest released.
  firebase-common/gradle.properties
  firebase-components/gradle.properties
  firebase-datatransport/gradle.properties
  firebase-firestore/gradle.properties
  firebase-inappmessaging-display/gradle.properties
  firebase-inappmessaging/gradle.properties
Labels: cla: yes, size/S

#954 Remove use of EnumSet.
  transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/scheduling/jobscheduling/SchedulerConfig.java
Labels: cla: yes, size/XS

#969 [2.9/3] Implement limitToLast and add unit/integration tests.
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/QueryTest.java
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/ValidationTest.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/Query.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/Query.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/View.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/IndexFreeQueryEngine.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/LocalStore.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/remote/RemoteSerializer.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/remote/RemoteStore.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/core/QueryTest.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/core/ViewTest.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/IndexFreeQueryEngineTest.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/remote/RemoteSerializerTest.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/spec/SpecTestCase.java
Labels: api: firestore, cla: yes, size/L

#984 Merge limitToLast to correct remote branch
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/QueryTest.java
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/ValidationTest.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/Query.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/Query.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/View.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/IndexFreeQueryEngine.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/LocalStore.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/remote/RemoteSerializer.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/remote/RemoteStore.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/core/QueryTest.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/core/ViewTest.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/IndexFreeQueryEngineTest.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/remote/RemoteSerializerTest.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/spec/SpecTestCase.java
Labels: cla: yes, size/L

#983 Fix unnecessary parenthesis warnings for FIAM
  firebase-inappmessaging/src/test/java/com/google/firebase/inappmessaging/internal/CampaignCacheClientTest.java
  firebase-inappmessaging/src/test/java/com/google/firebase/inappmessaging/internal/ImpressionStorageClientTest.java
Labels: cla: yes, size/XS

#985 remove unused test dep (joda) from fiam
  firebase-inappmessaging/firebase-inappmessaging.gradle
Labels: cla: yes, size/XS

#986 Pass User Properties to RC Fetch Request as a JSONObject
  firebase-config/bandwagoner/bandwagoner.gradle
  firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigFetchHttpClient.java
Labels: cla: yes, size/XS

#993 touch file
  firebase-installations/src/androidTest/java/com/google/firebase/installations/FisAndroidTestConstants.java
Labels: cla: yes, size/XS

#998 Add support for bytes in Encoders
  encoders/firebase-encoders/api.txt
  encoders/firebase-encoders/src/main/java/com/google/firebase/encoders/ValueEncoderContext.java
  encoders/firebase-encoders/src/main/java/com/google/firebase/encoders/json/JsonValueObjectEncoderContext.java
  encoders/firebase-encoders/src/test/java/com/google/firebase/encoders/json/JsonValueObjectEncoderContextTest.java
Labels: cla: yes, size/M

#1005 Add encoding support multiple types
  encoders/firebase-encoders/api.txt
  encoders/firebase-encoders/src/main/java/com/google/firebase/encoders/ObjectEncoderContext.java
  encoders/firebase-encoders/src/main/java/com/google/firebase/encoders/ValueEncoderContext.java
  encoders/firebase-encoders/src/main/java/com/google/firebase/encoders/json/JsonDataEncoderBuilder.java
  encoders/firebase-encoders/src/main/java/com/google/firebase/encoders/json/JsonValueObjectEncoderContext.java
  encoders/firebase-encoders/src/test/java/com/google/firebase/encoders/json/JsonValueObjectEncoderContextTest.java
Labels: cla: yes, size/L

#1000 Support for JSON based LogResponse
  transport/transport-backend-cct/src/main/java/com/google/android/datatransport/cct/internal/LogResponse.java
  transport/transport-backend-cct/src/test/java/com/google/android/datatransport/cct/internal/LogResponseTest.java
Labels: cla: yes, size/L

#974 add data bundles to sdk
  fiamui-app/fiamui-app.gradle
  fiamui-app/src/main/java/com/example/firebase/fiamui/MainActivity.java
  firebase-inappmessaging-display/firebase-inappmessaging-display.gradle
  firebase-inappmessaging-display/src/androidTest/java/com/google/firebase/inappmessaging/display/internal/bindingwrappers/CardBindingWrapperTest.java
  firebase-inappmessaging-display/src/androidTest/java/com/google/firebase/inappmessaging/display/internal/bindingwrappers/ModalBindingWrapperTest.java
  firebase-inappmessaging/firebase-inappmessaging.gradle
  firebase-inappmessaging/src/main/java/com/google/firebase/inappmessaging/internal/InAppMessageStreamManager.java
  firebase-inappmessaging/src/main/java/com/google/firebase/inappmessaging/model/BannerMessage.java
  firebase-inappmessaging/src/main/java/com/google/firebase/inappmessaging/model/CardMessage.java
  firebase-inappmessaging/src/main/java/com/google/firebase/inappmessaging/model/ImageOnlyMessage.java
  firebase-inappmessaging/src/main/java/com/google/firebase/inappmessaging/model/InAppMessage.java
  firebase-inappmessaging/src/main/java/com/google/firebase/inappmessaging/model/ModalMessage.java
  firebase-inappmessaging/src/main/java/com/google/firebase/inappmessaging/model/ProtoMarshallerClient.java
  firebase-inappmessaging/src/proto/google/internal/firebase/inappmessaging/v1/campaign.proto
  firebase-inappmessaging/src/test/java/com/google/firebase/inappmessaging/internal/DisplayCallbacksImplTest.java
  firebase-inappmessaging/src/test/java/com/google/firebase/inappmessaging/internal/InAppMessageStreamManagerTest.java
  firebase-inappmessaging/src/test/java/com/google/firebase/inappmessaging/internal/TestDeviceHelperTest.java
  firebase-inappmessaging/src/test/java/com/google/firebase/inappmessaging/model/ProtoMarshallerClientTest.java
  firebase-inappmessaging/src/testData/inappmessaging/testutil/TestData.java
Labels: cla: yes, size/L

#1001 Use JSON LogRequest instead of proto.
  transport/transport-backend-cct/src/main/java/com/google/android/datatransport/cct/CCTDestination.java
  transport/transport-backend-cct/src/main/java/com/google/android/datatransport/cct/CctTransportBackend.java
  transport/transport-backend-cct/src/main/java/com/google/android/datatransport/cct/internal/AndroidClientInfo.java
  transport/transport-backend-cct/src/main/java/com/google/android/datatransport/cct/internal/AndroidClientInfoEncoder.java
  transport/transport-backend-cct/src/main/java/com/google/android/datatransport/cct/internal/BatchedLogRequest.java
  transport/transport-backend-cct/src/main/java/com/google/android/datatransport/cct/internal/BatchedLogRequestEncoder.java
  transport/transport-backend-cct/src/main/java/com/google/android/datatransport/cct/internal/ClientInfo.java
  transport/transport-backend-cct/src/main/java/com/google/android/datatransport/cct/internal/ClientInfoEncoder.java
  transport/transport-backend-cct/src/main/java/com/google/android/datatransport/cct/internal/JsonBatchedLogRequestEncoder.java
  transport/transport-backend-cct/src/main/java/com/google/android/datatransport/cct/internal/LogEvent.java
  transport/transport-backend-cct/src/main/java/com/google/android/datatransport/cct/internal/LogEventEncoder.java
  transport/transport-backend-cct/src/main/java/com/google/android/datatransport/cct/internal/LogRequest.java
  transport/transport-backend-cct/src/main/java/com/google/android/datatransport/cct/internal/LogRequestEncoder.java
  transport/transport-backend-cct/src/main/java/com/google/android/datatransport/cct/internal/LogResponse.java
  transport/transport-backend-cct/src/main/java/com/google/android/datatransport/cct/internal/NetworkConnectionInfo.java
  transport/transport-backend-cct/src/main/java/com/google/android/datatransport/cct/internal/NetworkConnectionInfoEncoder.java
  transport/transport-backend-cct/src/main/java/com/google/android/datatransport/cct/internal/QosTier.java
  transport/transport-backend-cct/src/test/java/com/google/android/datatransport/cct/CctTransportBackendTest.java
  transport/transport-backend-cct/src/test/java/com/google/android/datatransport/cct/internal/LogRequestTest.java
  transport/transport-backend-cct/src/test/java/com/google/android/datatransport/cct/internal/LogResponseTest.java
  transport/transport-backend-cct/src/test/proto/google/cct/google_cct.proto
  transport/transport-backend-cct/transport-backend-cct.gradle
Labels: cla: yes, size/XXL

#991 Add ServerValue.increment() methods.
  firebase-database/src/androidTest/java/com/google/firebase/database/DataTest.java
  firebase-database/src/main/java/com/google/firebase/database/ServerValue.java
  firebase-database/src/main/java/com/google/firebase/database/core/Repo.java
  firebase-database/src/main/java/com/google/firebase/database/core/ServerValues.java
  firebase-database/src/main/java/com/google/firebase/database/core/SyncTree.java
Labels: cla: yes, size/L

#1010 Add json -> proto decoding unit test
  transport/transport-backend-cct/src/test/java/com/google/android/datatransport/cct/internal/LogRequestTest.java
Labels: cla: yes, size/M

#1012 Bumping iid
  firebase-config/bandwagoner/bandwagoner.gradle
  firebase-config/firebase-config.gradle
  firebase-functions/firebase-functions.gradle
  firebase-inappmessaging-display/firebase-inappmessaging-display.gradle
  firebase-inappmessaging/firebase-inappmessaging.gradle
Labels: cla: yes, size/S

#1013 Remove device unsupported by Firebase Test Lab
  firebase-config/bandwagoner/bandwagoner.gradle
Labels: cla: yes, size/XS

#1014 Encode json payload as string instead of byte[]
  transport/transport-backend-cct/src/main/java/com/google/android/datatransport/cct/CctTransportBackend.java
  transport/transport-backend-cct/src/main/java/com/google/android/datatransport/cct/internal/LogEvent.java
  transport/transport-backend-cct/src/main/java/com/google/android/datatransport/cct/internal/LogEventEncoder.java
  transport/transport-backend-cct/src/test/java/com/google/android/datatransport/cct/CctTransportBackendTest.java
  transport/transport-backend-cct/src/test/java/com/google/android/datatransport/cct/internal/LogRequestTest.java
Labels: cla: yes, size/M

#1017 Add `Map<String, Object>` support to JsonEncoder.
  encoders/firebase-encoders/src/main/java/com/google/firebase/encoders/json/JsonValueObjectEncoderContext.java
  encoders/firebase-encoders/src/test/java/com/google/firebase/encoders/json/JsonValueObjectEncoderContextTest.java
Labels: cla: yes, size/M
