Repository firebase/firebase-android-sdk, pull requests merged in 2020-05, with the labels that each got.

#1518 Fix python subprocess call.
  ci/fireci/fireci/uploader.py
Labels: cla: yes, size/XS

#1508 revert "Move precondition to constructor"
  firebase-installations/src/main/java/com/google/firebase/installations/FirebaseInstallations.java
Labels: cla: yes, size/S

#1520 Display prow merge commit info in metric reports.
  ci/fireci/fireci/uploader.py
  ci/fireci/fireciplugins/coverage.py
Labels: cla: yes, size/S

#1521 Fixing Bad File descriptor IOException to avoid app crashes.
  firebase-installations/src/main/java/com/google/firebase/installations/CrossProcessLock.java
Labels: cla: yes, size/XS

#1529 Migrate SmokeTestsPlugin to Java.
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/ci/AffectedProjectFinder.java
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/ci/SmokeTestsPlugin.groovy
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/ci/SmokeTestsPlugin.java
Labels: cla: yes, size/L

#1530 FIAM FIS Integration
  fiamui-app/fiamui-app.gradle
  firebase-inappmessaging-display/firebase-inappmessaging-display.gradle
  firebase-inappmessaging-display/src/main/java/com/google/firebase/inappmessaging/display/FirebaseInAppMessagingDisplay.java
  firebase-inappmessaging/firebase-inappmessaging.gradle
  firebase-inappmessaging/src/androidTest/java/com/google/firebase/inappmessaging/FirebaseInAppMessagingFlowableTest.java
  firebase-inappmessaging/src/androidTest/java/com/google/firebase/inappmessaging/TestApiClientModule.java
  firebase-inappmessaging/src/androidTest/java/com/google/firebase/inappmessaging/TestEngagementMetricsLoggerClientModule.java
  firebase-inappmessaging/src/main/java/com/google/firebase/inappmessaging/FirebaseInAppMessaging.java
  firebase-inappmessaging/src/main/java/com/google/firebase/inappmessaging/FirebaseInAppMessagingRegistrar.java
  firebase-inappmessaging/src/main/java/com/google/firebase/inappmessaging/internal/ApiClient.java
  firebase-inappmessaging/src/main/java/com/google/firebase/inappmessaging/internal/DataCollectionHelper.java
  firebase-inappmessaging/src/main/java/com/google/firebase/inappmessaging/internal/InAppMessageStreamManager.java
  firebase-inappmessaging/src/main/java/com/google/firebase/inappmessaging/internal/InstallationIdResult.java
  firebase-inappmessaging/src/main/java/com/google/firebase/inappmessaging/internal/MetricsLoggerClient.java
  firebase-inappmessaging/src/main/java/com/google/firebase/inappmessaging/internal/injection/modules/ApiClientModule.java
  firebase-inappmessaging/src/main/java/com/google/firebase/inappmessaging/internal/injection/modules/TransportClientModule.java
  firebase-inappmessaging/src/test/java/com/google/firebase/inappmessaging/FirebaseInAppMessagingTest.java
  firebase-inappmessaging/src/test/java/com/google/firebase/inappmessaging/internal/ApiClientTest.java
  firebase-inappmessaging/src/test/java/com/google/firebase/inappmessaging/internal/DataCollectionHelperTest.java
  firebase-inappmessaging/src/test/java/com/google/firebase/inappmessaging/internal/DisplayCallbacksImplTest.java
  firebase-inappmessaging/src/test/java/com/google/firebase/inappmessaging/internal/InAppMessageStreamManagerTest.java
  firebase-inappmessaging/src/test/java/com/google/firebase/inappmessaging/internal/MetricsLoggerClientTest.java
  firebase-inappmessaging/src/testData/inappmessaging/testutil/TestData.java
Labels: cla: yes, size/XXL

#1537 Log the available Firebase options along with the error stream.
  firebase-installations/src/main/java/com/google/firebase/installations/remote/FirebaseInstallationServiceClient.java
Labels: cla: yes, size/S

#1536 Fix OverlappingFileLockException.
  firebase-installations/gradle.properties
  firebase-installations/src/main/java/com/google/firebase/installations/FirebaseInstallations.java
Labels: cla: yes, size/M

#1538 Fix broken FIAM analytics dependencies
  fiamui-app/fiamui-app.gradle
  firebase-inappmessaging-display/firebase-inappmessaging-display.gradle
Labels: cla: yes, size/S

#1539 Fix "changed" tasks.
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/ci/AffectedProjectFinder.java
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/ci/ContinuousIntegrationPlugin.java
Labels: cla: yes, size/S

#1542 Update kotlin library to 1.3.72
  build.gradle
Labels: cla: yes, size/XS

#1543 Rename FDL KTX registrar to match the pattern of other registrars
  firebase-dynamic-links/ktx/src/main/AndroidManifest.xml
  firebase-dynamic-links/ktx/src/main/kotlin/com/google/firebase/dynamiclinks/ktx/FirebaseDynamicLinks.kt
Labels: cla: yes, size/XS

#1544 Update released versions.
  firebase-config/gradle.properties
  firebase-database/gradle.properties
  firebase-datatransport/gradle.properties
  firebase-firestore/gradle.properties
  firebase-inappmessaging-display/gradle.properties
  firebase-inappmessaging/gradle.properties
  transport/transport-backend-cct/gradle.properties
  transport/transport-runtime/gradle.properties
Labels: cla: yes, size/M

#1547 Port Test for increment with merge
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/NumericTransformsTest.java
Labels: api: firestore, cla: yes, size/XS

#1549 Fix dependents task.
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/ci/ContinuousIntegrationPlugin.java
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/ci/device/FirebaseTestServer.java
  firebase-inappmessaging-display/ktx/src/test/kotlin/com/google/firebase/inappmessaging/display/ktx/InAppMessagingDisplayTests.kt
  firebase-inappmessaging/ktx/src/test/kotlin/com/google/firebase/inappmessagging/ktx/InAppMessaggingTests.kt
Labels: cla: yes, size/S

#1553 Remove fiamui app
  fiamui-app/README.md
  fiamui-app/fiamui-app.gradle
  fiamui-app/proguard-rules.pro
  fiamui-app/scripts/run-test-lab.sh
  fiamui-app/src/androidTest/AndroidManifest.xml
  fiamui-app/src/androidTest/java/com/example/firebase/fiamui/BannerTest.java
  fiamui-app/src/androidTest/java/com/example/firebase/fiamui/CardTest.java
  fiamui-app/src/androidTest/java/com/example/firebase/fiamui/ImageTest.java
  fiamui-app/src/androidTest/java/com/example/firebase/fiamui/ModalTest.java
  fiamui-app/src/androidTest/java/com/example/firebase/fiamui/ScreenShotter.java
  fiamui-app/src/androidTest/java/com/example/firebase/fiamui/TestConstants.java
  fiamui-app/src/androidTest/java/com/example/firebase/fiamui/TestUtils.java
  fiamui-app/src/main/AndroidManifest.xml
  fiamui-app/src/main/java/com/example/firebase/fiamui/MainActivity.java
  fiamui-app/src/main/java/com/example/firebase/fiamui/NoOpDisplayCallbacks.java
  fiamui-app/src/main/java/com/example/firebase/fiamui/SampleApplication.java
  fiamui-app/src/main/java/com/example/firebase/fiamui/TestActivity.java
  fiamui-app/src/main/res/layout/activity_main.xml
  fiamui-app/src/main/res/mipmap-hdpi/ic_launcher.png
  fiamui-app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  fiamui-app/src/main/res/mipmap-mdpi/ic_launcher.png
  fiamui-app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  fiamui-app/src/main/res/mipmap-xhdpi/ic_launcher.png
  fiamui-app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  fiamui-app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  fiamui-app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  fiamui-app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  fiamui-app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  fiamui-app/src/main/res/values/colors.xml
  fiamui-app/src/main/res/values/google-services.xml
  fiamui-app/src/main/res/values/strings.xml
  fiamui-app/src/main/res/values/styles.xml
  subprojects.cfg
Labels: cla: yes, size/XXL

#1550 Fix FIAM Display lifecycle interactions
  firebase-inappmessaging-display/firebase-inappmessaging-display.gradle
  firebase-inappmessaging-display/src/main/java/com/google/firebase/inappmessaging/display/FirebaseInAppMessagingDisplay.java
  firebase-inappmessaging-display/src/test/java/com/google/firebase/inappmessaging/display/FirebaseInAppMessagingDisplayTest.java
  firebase-inappmessaging/api.txt
  firebase-inappmessaging/src/main/java/com/google/firebase/inappmessaging/FirebaseInAppMessaging.java
  firebase-inappmessaging/src/main/java/com/google/firebase/inappmessaging/internal/DeveloperListenerManager.java
Labels: cla: yes, size/L

#1554 Remove duplicated inclusion of firebase-components on test-app.
  firebase-storage/test-app/test-app.gradle
Labels: cla: yes, size/XS

#1532 Migrate all tests to kotlin, remove groovy plugin from buildSrc.
  buildSrc/$project.buildDir/generated/third_party_licenses/third_party_licenses.json
  buildSrc/$project.buildDir/generated/third_party_licenses/third_party_licenses.txt
  buildSrc/build.gradle
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/ClosureUtil.java
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/Dokka.java
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/FirebaseLibraryExtension.java
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/FirebaseLibraryPlugin.java
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/FirebaseStaticAnalysis.java
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/LibraryType.java
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/SdkUtil.java
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/apiinfo/ApiInformationTask.java
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/apiinfo/GenerateApiTxtFileTask.java
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/apiinfo/GenerateStubsTask.java
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/apiinfo/GetMetalavaJarTask.java
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/ci/AffectedProjectFinder.java
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/ci/ContinuousIntegrationExtension.java
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/ci/ContinuousIntegrationPlugin.java
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/ci/Coverage.java
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/ci/Environment.java
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/ci/SmokeTestsPlugin.java
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/ci/device/FirebaseTestLabExtension.java
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/ci/device/FirebaseTestLabPlugin.java
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/ci/device/FirebaseTestServer.java
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/ci/metrics/DrainingBuildListener.java
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/ci/metrics/MeasuringTaskExecutionListener.java
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/ci/metrics/Metrics.java
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/ci/metrics/MetricsPlugin.java
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/ci/metrics/StackdriverMetrics.java
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/license/GenerateLicensesTask.java
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/license/LicenseResolverPlugin.java
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/license/ThirdPartyLicensesExtension.java
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/publish/Mode.java
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/publish/Publisher.java
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/publish/PublishingPlugin.java
  buildSrc/src/test/groovy22/com/google/firebase/gradle/plugins/license/LicenseResolverPluginSpec.groovy
  buildSrc/src/test/groovy22/com/google/firebase/gradle/plugins/publish/PublishingPluginSpec.groovy
  buildSrc/src/test/kotlin/com/google/firebase/gradle/plugins/LicenseResolverPluginTests.kt
  buildSrc/src/test/kotlin/com/google/firebase/gradle/plugins/Memoization.kt
  buildSrc/src/test/kotlin/com/google/firebase/gradle/plugins/PublishingPluginTests.kt
  buildSrc/src/test/kotlin/com/google/firebase/gradle/plugins/publishing.kt
Labels: cla: yes, size/XL

#1558 Add missing test annotation and ErrorProne suggestions.
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/FirestoreTest.java
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/ValidationTest.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/IndexedQueryEngineTest.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/SQLiteSchemaTest.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/model/ValuesTest.java
  firebase-firestore/src/testUtil/java/com/google/firebase/firestore/testutil/ComparatorTester.java
  firebase-firestore/src/testUtil/java/com/google/firebase/firestore/testutil/TestUtil.java
Labels: api: firestore, cla: yes, size/M

#1561 Warn when stream is closing due to error, not debug.
  firebase-firestore/src/main/java/com/google/firebase/firestore/remote/AbstractStream.java
Labels: api: firestore, cla: yes, size/XS

#1479 Wait for DataTransport callback task at crash time
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsController.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/SessionReportingCoordinator.java
Labels: cla: yes, size/S

#1572 Make removeSnapshotsInSyncListener run on AQ
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/FirestoreClient.java
Labels: api: firestore, cla: yes, size/XS

#1571 Cache FID to avoid multiple disk reads.
  firebase-installations/src/main/java/com/google/firebase/installations/FirebaseInstallations.java
Labels: cla: yes, size/S

#1570 Completing getId call with the disk reads on the caller thread.
  firebase-installations/src/main/java/com/google/firebase/installations/FirebaseInstallations.java
  firebase-installations/src/main/java/com/google/firebase/installations/GetIdListener.java
Labels: cla: yes, size/L

#1589 Update released versions.
  firebase-inappmessaging-display/gradle.properties
  firebase-inappmessaging/gradle.properties
  firebase-installations/gradle.properties
Labels: cla: yes, size/S

#1590 Update crashlytics released version.
  firebase-crashlytics-ndk/gradle.properties
  firebase-crashlytics/gradle.properties
Labels: cla: yes, size/XS

#1555 Disable FIS network calls to use cached response.
  firebase-installations/src/main/java/com/google/firebase/installations/remote/FirebaseInstallationServiceClient.java
Labels: cla: yes, size/XS

#1591 Initial implementation of FieldDescriptor.
  encoders/firebase-encoders-json/api.txt
  encoders/firebase-encoders-json/src/main/java/com/google/firebase/encoders/FieldDescriptor.java
  encoders/firebase-encoders-json/src/test/java/com/google/firebase/encoders/FieldDescriptorTest.java
Labels: cla: yes, size/L

#1594 Initial implementation of ExtraProperty annotation processor.
  encoders/firebase-encoders-json/api.txt
  encoders/firebase-encoders-json/src/main/java/com/google/firebase/encoders/annotations/ExtraProperty.java
  encoders/firebase-encoders-processor/src/main/java/com/google/firebase/encoders/processor/ExtraPropertyProcessor.java
  encoders/firebase-encoders-processor/src/main/java/com/google/firebase/encoders/processor/annotations/AnnotationBuilder.java
  encoders/firebase-encoders-processor/src/test/java/com/google/firebase/encoders/processor/ExtraPropertyProcessorTest.java
  encoders/firebase-encoders-processor/src/test/resources/ExpectedAtEmptyAnnotation.java
  encoders/firebase-encoders-processor/src/test/resources/ExpectedAtMyAnnotation.java
Labels: cla: yes, size/XL

#1552 Make schemas back and forth compatible
  transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/scheduling/persistence/SchemaManager.java
  transport/transport-runtime/src/test/java/com/google/android/datatransport/runtime/scheduling/persistence/SchemaManagerMigrationTest.java
  transport/transport-runtime/src/test/java/com/google/android/datatransport/runtime/scheduling/persistence/SchemaManagerTest.java
  transport/transport-runtime/src/test/java/com/google/android/datatransport/runtime/scheduling/persistence/StateSimulations.java
Labels: cla: yes, size/L

#1595 Implement equals, hashCode, and toString() methods.
  encoders/firebase-encoders-processor/src/main/java/com/google/firebase/encoders/processor/annotations/AnnotationBuilder.java
  encoders/firebase-encoders-processor/src/main/java/com/google/firebase/encoders/processor/annotations/EqualsMethod.java
  encoders/firebase-encoders-processor/src/main/java/com/google/firebase/encoders/processor/annotations/HashCodeMethod.java
  encoders/firebase-encoders-processor/src/main/java/com/google/firebase/encoders/processor/annotations/ToStringMethod.java
  encoders/firebase-encoders-processor/src/test/java/com/google/firebase/encoders/processor/ExtraPropertyProcessorTest.java
  encoders/firebase-encoders-processor/src/test/resources/ExpectedAtEmptyAnnotation.java
  encoders/firebase-encoders-processor/src/test/resources/ExpectedAtMyAnnotation.java
Labels: cla: yes, size/L

#1557 Fix a multiple-definition linker error in the native API.
  firebase-crashlytics-ndk/src/main/jni/Application.mk
  firebase-crashlytics-ndk/src/main/jni/libcrashlytics/include/crashlytics/external/crashlytics.h
  firebase-crashlytics-ndk/src/main/jni/libcrashlytics/include/crashlytics/handler/maps.h
  firebase-crashlytics-ndk/src/main/jni/libcrashlytics/src/external/api.cpp
Labels: cla: yes, size/L

#1577 Refactor Crashlytics/Analytics integration
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/analytics/AnalyticsConnectorReceiverTest.java
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/CrashlyticsControllerTest.java
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/CrashlyticsCoreInitializationTest.java
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/CrashlyticsCoreTest.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/CrashlyticsAnalyticsListener.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/FirebaseCrashlytics.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/analytics/AnalyticsConnectorReceiver.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/analytics/AnalyticsEventLogger.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/analytics/AnalyticsEventReceiver.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/analytics/AnalyticsReceiver.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/analytics/BlockingAnalyticsEventLogger.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/analytics/BreadcrumbAnalyticsEventReceiver.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/analytics/CrashlyticsOriginAnalyticsEventLogger.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/analytics/UnavailableAnalyticsEventLogger.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/breadcrumbs/BreadcrumbHandler.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/breadcrumbs/BreadcrumbSource.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/breadcrumbs/DisabledBreadcrumbSource.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsController.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsCore.java
Labels: cla: yes, size/XXL

#1600 inital implementation of typeToken for decoder
  encoders/firebase-decoders-json/api.txt
  encoders/firebase-decoders-json/firebase-decoders-json.gradle
  encoders/firebase-decoders-json/gradle.properties
  encoders/firebase-decoders-json/src/main/AndroidManifest.xml
  encoders/firebase-decoders-json/src/main/java/com/google/firebase/decoders/Safe.java
  encoders/firebase-decoders-json/src/main/java/com/google/firebase/decoders/TypeToken.java
  encoders/firebase-decoders-json/src/main/java/com/google/firebase/decoders/TypeTokenContainer.java
  encoders/firebase-decoders-json/src/test/java/com/google/firebase/decoders/TypeTokenTest.java
  subprojects.cfg
Labels: cla: yes, size/L
