Repository firebase/firebase-android-sdk, pull requests merged in 2020-11, with the labels that each got.

#2129 Clarify logging of reports being sent via DataTransport
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/report/ReportUploader.java
Labels: cla: yes, size/XS

#2131 Add support for Application build field in CCT Transport Backend.
  transport/transport-backend-cct/src/main/java/com/google/android/datatransport/cct/CctTransportBackend.java
  transport/transport-backend-cct/src/main/java/com/google/android/datatransport/cct/internal/AndroidClientInfo.java
  transport/transport-backend-cct/src/test/java/com/google/android/datatransport/cct/CctTransportBackendTest.java
  transport/transport-backend-cct/src/test/java/com/google/android/datatransport/cct/internal/LogRequestTest.java
Labels: cla: yes, size/M

#2135 Updrade errorprone
  encoders/firebase-encoders/src/main/java/com/google/firebase/encoders/FieldDescriptor.java
  encoders/firebase-encoders/src/main/java/com/google/firebase/encoders/annotations/Encodable.java
  firebase-database/firebase-database.gradle
  firebase-firestore/firebase-firestore.gradle
  firebase-messaging/src/test/java/com/google/firebase/messaging/SharedPreferencesQueueRoboTest.java
  gradle/errorProne.gradle
Labels: cla: yes, size/S

#2141 Discard tasks run on Crashlytics background executor after shut down
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsBackgroundWorker.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/ExecutorUtils.java
Labels: cla: yes, size/M

#2143 Update Test Lab device for RC Bandwagoner.
  firebase-config/bandwagoner/bandwagoner.gradle
  firebase-config/bandwagoner/src/main/res/layout/api_fragment.xml
Labels: cla: yes, size/S

#1304 Add support for other Firebase products to integrate with Remote Config.
  firebase-config/src/main/java/com/google/firebase/remoteconfig/RemoteConfigComponent.java
  firebase-config/src/main/java/com/google/firebase/remoteconfig/RemoteConfigConstants.java
  firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigContainer.java
  firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigFetchHttpClient.java
  firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigGetParameterHandler.java
  firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/Personalization.java
  firebase-config/src/test/java/com/google/firebase/remoteconfig/FirebaseRemoteConfigTest.java
  firebase-config/src/test/java/com/google/firebase/remoteconfig/internal/ConfigGetParameterHandlerTest.java
  firebase-config/src/test/java/com/google/firebase/remoteconfig/internal/PersonalizationTest.java
Labels: cla: yes, size/L

#2132 Add a ComponentRuntime builder.
  firebase-common/src/main/java/com/google/firebase/FirebaseApp.java
  firebase-components/src/main/java/com/google/firebase/components/ComponentRuntime.java
  firebase-components/src/test/java/com/google/firebase/components/ComponentRuntimeTest.java
Labels: cla: yes, size/L

#2137 Fix a race condition in LazySet.
  firebase-components/src/main/java/com/google/firebase/components/LazySet.java
  firebase-components/src/main/java/com/google/firebase/components/OptionalProvider.java
Labels: cla: yes, size/S

#2148 Update encoders version
  encoders/firebase-encoders/gradle.properties
Labels: cla: yes, size/XS

#2149 Update versions for release.
  firebase-common/gradle.properties
  firebase-crashlytics-ndk/gradle.properties
  firebase-crashlytics/gradle.properties
Labels: cla: yes, size/XS

#2150 M83 RC version update
  firebase-config/gradle.properties
Labels: cla: yes, size/XS

#2151 Include runtimeOnly dependencies in javadocClasspath.
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/Dokka.java
Labels: cla: yes, size/XS

#2156 Add missing Copyright headers to NDK
  firebase-crashlytics-ndk/src/main/jni/libcrashlytics-common/src/crashpad_handler_main.cpp
  firebase-crashlytics-ndk/src/main/jni/libcrashlytics-handler/src/crashpad_handler_main.cpp
  firebase-crashlytics-ndk/src/main/jni/libcrashlytics-trampoline/src/handler_trampoline.cpp
Labels: cla: yes, size/M

#1879 docs(fdl-ktx): document the Kotlin destructuring declarations
  docs/ktx/dynamic-links.md
Labels: cla: yes, ok-to-test, size/M

#2162 Fix broken code links in comments of SetOptions.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/DocumentId.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/SetOptions.java
Labels: cla: yes, size/S

#2100 Add custom domain support to callable functions
  firebase-functions/ktx/api.txt
  firebase-functions/ktx/src/main/kotlin/com/google/firebase/functions/ktx/Functions.kt
  firebase-functions/src/androidTest/java/com/google/firebase/functions/FirebaseFunctionsTest.java
  firebase-functions/src/main/java/com/google/firebase/functions/FirebaseFunctions.java
  firebase-functions/src/main/java/com/google/firebase/functions/FunctionsMultiResourceComponent.java
Labels: cla: yes, size/M

#2167 Add firebase-annotations module.
  firebase-annotations/firebase-annotations.gradle
  firebase-annotations/gradle.properties
  firebase-annotations/src/main/java/com/google/firebase/annotations/DeferredApi.java
  subprojects.cfg
Labels: cla: yes, size/M

#2168 Remove special instructions for requiring NDK r17c.
  README.md
  firebase-crashlytics-ndk/README.md
Labels: cla: yes, size/S

#2154 Add implementation for listDownloadedModels.
  firebase-ml-modeldownloader/firebase-ml-modeldownloader.gradle
  firebase-ml-modeldownloader/src/main/java/com/google/firebase/ml/modeldownloader/FirebaseModelDownloader.java
  firebase-ml-modeldownloader/src/main/java/com/google/firebase/ml/modeldownloader/FirebaseModelDownloaderRegistrar.java
  firebase-ml-modeldownloader/src/main/java/com/google/firebase/ml/modeldownloader/internal/SharedPreferencesUtil.java
  firebase-ml-modeldownloader/src/test/java/com/google/firebase/ml/modeldownloader/FirebaseModelDownloaderTest.java
  firebase-ml-modeldownloader/src/test/java/com/google/firebase/ml/modeldownloader/TestOnCompleteListener.java
  firebase-ml-modeldownloader/src/test/java/com/google/firebase/ml/modeldownloader/internal/SharedPreferencesUtilTest.java
Labels: cla: yes, size/L

#2087 Query get API for RTDB
  firebase-database/src/androidTest/java/com/google/firebase/database/QueryTest.java
  firebase-database/src/main/java/com/google/firebase/database/Query.java
  firebase-database/src/main/java/com/google/firebase/database/connection/PersistentConnection.java
  firebase-database/src/main/java/com/google/firebase/database/connection/PersistentConnectionImpl.java
  firebase-database/src/main/java/com/google/firebase/database/core/Repo.java
  firebase-database/src/main/java/com/google/firebase/database/core/SyncTree.java
Labels: WIP, api: database, cla: yes, size/L

#2172 Update manifest package name for encoders_json
  encoders/firebase-encoders-json/src/main/AndroidManifest.xml
Labels: cla: yes, size/XS

#2174 Fix comment.
  firebase-installations/src/main/java/com/google/firebase/installations/remote/FirebaseInstallationServiceClient.java
Labels: cla: yes, size/XS

#2134 Add new CustomModelDownloadService to retrieve download details about…
  firebase-ml-modeldownloader/firebase-ml-modeldownloader.gradle
  firebase-ml-modeldownloader/src/main/java/com/google/firebase/ml/modeldownloader/CustomModel.java
  firebase-ml-modeldownloader/src/main/java/com/google/firebase/ml/modeldownloader/FirebaseModelDownloaderRegistrar.java
  firebase-ml-modeldownloader/src/main/java/com/google/firebase/ml/modeldownloader/internal/CustomModelDownloadService.java
  firebase-ml-modeldownloader/src/main/java/com/google/firebase/ml/modeldownloader/internal/SharedPreferencesUtil.java
  firebase-ml-modeldownloader/src/test/java/com/google/firebase/ml/modeldownloader/CustomModelTest.java
  firebase-ml-modeldownloader/src/test/java/com/google/firebase/ml/modeldownloader/FirebaseModelDownloaderTest.java
  firebase-ml-modeldownloader/src/test/java/com/google/firebase/ml/modeldownloader/TestOnCompleteListener.java
  firebase-ml-modeldownloader/src/test/java/com/google/firebase/ml/modeldownloader/internal/CustomModelDownloadServiceTest.java
  firebase-ml-modeldownloader/src/test/java/com/google/firebase/ml/modeldownloader/internal/SharedPreferencesUtilTest.java
Labels: cla: yes, size/XL

#2175 Add Proguard rule for Crashlytics NDK
  firebase-crashlytics-ndk/firebase-crashlytics-ndk-proguard.txt
Labels: cla: yes, size/XS

#2180 Migrate to the new DeferredApi annotation.
  firebase-components/firebase-components.gradle
  firebase-components/src/main/java/com/google/firebase/components/annotations/DeferredApi.java
  firebase-components/src/main/java/com/google/firebase/inject/Deferred.java
  tools/lint/src/main/kotlin/DeferredApiDetector.kt
  tools/lint/src/test/kotlin/DeferredApiDetectorTests.kt
Labels: cla: yes, size/M

#1981 Fix ConcurrentModificationException in FirestoreMultiDbComponent.onDeleted()
  firebase-firestore/src/main/java/com/google/firebase/firestore/FirebaseFirestore.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/FirestoreMultiDbComponent.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/FirestoreMultiDbComponentTest.java
Labels: api: firestore, cla: yes, size/M

#2190 Fix build.
  .gitignore
  build.gradle
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/FirebaseLibraryExtension.java
Labels: cla: yes, size/XS

#2196 Cleaning customer-lint check from FIS SDK.
  firebase-installations/customer-lint-checks/customer-lint-checks.gradle
  firebase-installations/customer-lint-checks/src/main/java/com/google/firebase/installations/lint/Checks.kt
  firebase-installations/customer-lint-checks/src/main/java/com/google/firebase/installations/lint/IncompatibleIidVersionDetector.kt
  firebase-installations/customer-lint-checks/src/test/java/com/google/firebase/installations/lint/VersionTests.kt
  firebase-installations/firebase-installations.gradle
  subprojects.cfg
Labels: cla: yes, size/L

#1831 Add platform logging
  firebase-common/src/main/java/com/google/firebase/heartbeatinfo/DefaultHeartBeatInfo.java
  firebase-common/src/main/java/com/google/firebase/heartbeatinfo/HeartBeatConsumer.java
  firebase-common/src/main/java/com/google/firebase/heartbeatinfo/HeartBeatConsumerComponent.java
  firebase-common/src/main/java/com/google/firebase/heartbeatinfo/HeartBeatInfo.java
  firebase-common/src/main/java/com/google/firebase/heartbeatinfo/HeartBeatInfoStorage.java
  firebase-common/src/main/java/com/google/firebase/heartbeatinfo/HeartBeatResult.java
  firebase-common/src/main/java/com/google/firebase/heartbeatinfo/SdkHeartBeatResult.java
  firebase-common/src/test/java/com/google/firebase/heartbeatinfo/DefaultHeartBeatInfoTest.java
  firebase-common/src/test/java/com/google/firebase/heartbeatinfo/HeartBeatInfoStorageTest.java
  firebase-common/src/test/java/com/google/firebase/heartbeatinfo/TestOnCompleteListener.java
Labels: cla: yes, size/XL

#2200 Make Api Information task comment the diff on the PR
  ci/fireci/fireci/commands.py
Labels: cla: yes, size/XS

#2203 Remove SimpleQueryEngine
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/remote/RemoteStoreTest.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/MemoryComponentProvider.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/DefaultQueryEngine.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/LocalDocumentsView.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/SimpleQueryEngine.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/LocalStoreTestCase.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/MemoryLocalStoreTest.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/QueryEngineTest.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/SQLiteLocalStoreTest.java
Labels: api: firestore, cla: yes, size/L

#2208 Add float support to ValueEncoderContext.
  encoders/firebase-encoders-json/src/main/java/com/google/firebase/encoders/json/JsonValueObjectEncoderContext.java
  encoders/firebase-encoders/api.txt
  encoders/firebase-encoders/src/main/java/com/google/firebase/encoders/ValueEncoderContext.java
Labels: cla: yes, size/S

#2206 Initial implementation of firebase-encoders-proto
  encoders/firebase-encoders-proto/api.txt
  encoders/firebase-encoders-proto/firebase-encoders-proto.gradle
  encoders/firebase-encoders-proto/gradle.properties
  encoders/firebase-encoders-proto/src/main/java/com/google/firebase/encoders/proto/LengthCountingOutputStream.java
  encoders/firebase-encoders-proto/src/main/java/com/google/firebase/encoders/proto/ProtoEnum.java
  encoders/firebase-encoders-proto/src/main/java/com/google/firebase/encoders/proto/Protobuf.java
  encoders/firebase-encoders-proto/src/main/java/com/google/firebase/encoders/proto/ProtobufDataEncoderContext.java
  encoders/firebase-encoders-proto/src/main/java/com/google/firebase/encoders/proto/ProtobufEncoder.java
  encoders/firebase-encoders-proto/src/main/java/com/google/firebase/encoders/proto/ProtobufValueEncoderContext.java
  encoders/firebase-encoders-proto/src/test/java/com/google/firebase/encoders/proto/Encoder.java
  encoders/firebase-encoders-proto/src/test/java/com/google/firebase/encoders/proto/FixedEncodingTests.java
  encoders/firebase-encoders-proto/src/test/java/com/google/firebase/encoders/proto/OtherTypesEncodingTests.java
  encoders/firebase-encoders-proto/src/test/java/com/google/firebase/encoders/proto/SimpleEncodingTests.java
  encoders/firebase-encoders-proto/src/test/java/com/google/firebase/encoders/proto/WithCollectionsTests.java
  encoders/firebase-encoders-proto/src/test/java/com/google/firebase/encoders/proto/pojos/Fixed.java
  encoders/firebase-encoders-proto/src/test/java/com/google/firebase/encoders/proto/pojos/OtherTypes.java
  encoders/firebase-encoders-proto/src/test/java/com/google/firebase/encoders/proto/pojos/Simple.java
  encoders/firebase-encoders-proto/src/test/java/com/google/firebase/encoders/proto/pojos/WithCollections.java
  encoders/firebase-encoders-proto/src/test/proto/test.proto
  subprojects.cfg
Labels: cla: yes, size/XXL

#2207 Update protobuf dep to 3.14
  build.gradle
Labels: cla: yes, size/XS
