Repository firebase/firebase-android-sdk, pull requests merged in 2020-07, with the labels that each got.

#1739 check various task states before returning
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/Utils.java
Labels: cla: yes, size/S

#1748 Fix kotlin lint issue.
  firebase-config/ktx/src/test/kotlin/com/google/firebase/remoteconfig/ktx/RemoteConfigTests.kt
Labels: cla: yes, size/S

#1751 Fix missing klint errors.
  firebase-database/ktx/src/main/kotlin/com/google/firebase/database/ktx/Database.kt
  firebase-dynamic-links/ktx/src/main/kotlin/com/google/firebase/dynamiclinks/ktx/FirebaseDynamicLinks.kt
  firebase-firestore/ktx/src/main/kotlin/com/google/firebase/firestore/ktx/Firestore.kt
  firebase-functions/ktx/src/main/kotlin/com/google/firebase/functions/ktx/Functions.kt
  firebase-inappmessaging-display/ktx/src/main/kotlin/com/google/firebase/inappmessaging/display/ktx/InAppMessagingDisplay.kt
  firebase-inappmessaging/ktx/src/main/kotlin/com/google/firebase/inappmessaging/ktx/InAppMessaging.kt
  firebase-storage/ktx/src/main/kotlin/com/google/firebase/storage/ktx/Storage.kt
Labels: cla: yes, size/S

#1752 Klint test fixes.
  firebase-database/ktx/src/test/kotlin/com/google/firebase/database/ktx/DatabaseTests.kt
  firebase-dynamic-links/ktx/src/test/kotlin/com/google/firebase/dynamiclinks/ktx/DynamicLinksTests.kt
  firebase-functions/ktx/src/androidTest/kotlin/com/google/firebase/functions/ktx/CallTests.kt
  firebase-inappmessaging-display/ktx/src/test/kotlin/com/google/firebase/inappmessaging/display/ktx/InAppMessagingDisplayTests.kt
  firebase-inappmessaging/ktx/src/test/kotlin/com/google/firebase/inappmessagging/ktx/InAppMessaggingTests.kt
  firebase-storage/ktx/src/test/kotlin/com/google/firebase/storage/ktx/StorageTest.kt
Labels: cla: yes, size/S

#1754 Fix klint errors not in ktx extensions.
  firebase-installations/customer-lint-checks/src/main/java/com/google/firebase/installations/lint/Checks.kt
  firebase-installations/customer-lint-checks/src/main/java/com/google/firebase/installations/lint/IncompatibleIidVersionDetector.kt
  firebase-installations/customer-lint-checks/src/test/java/com/google/firebase/installations/lint/VersionTests.kt
  tools/lint/src/main/kotlin/KotlinInteropDetector.kt
  tools/lint/src/main/kotlin/ManifestElementHasNoExportedAttributeDetector.kt
  tools/lint/src/main/kotlin/NonAndroidxNullabilityDetector.kt
  tools/lint/src/test/kotlin/ManifestTests.kt
Labels: cla: yes, size/S

#1602 Add ability to publish JAR SDKs
  buildSrc/build.gradle
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/Dokka.java
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/FirebaseJavaLibraryPlugin.java
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/FirebaseLibraryExtension.java
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/LibraryType.java
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/SdkUtil.java
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/apiinfo/ApiInformationTask.java
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/apiinfo/GenerateApiTxtFileTask.java
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/apiinfo/GenerateStubsTask.java
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/ci/SmokeTestsPlugin.java
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/publish/Publisher.java
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/publish/PublishingPlugin.java
  buildSrc/src/test/kotlin/com/google/firebase/gradle/plugins/PublishingPluginTests.kt
  buildSrc/src/test/kotlin/com/google/firebase/gradle/plugins/publishing.kt
Labels: cla: yes, size/XL

#1722 support default value decoding
  encoders/firebase-decoders-json/src/json/java/com/google/firebase/decoders/json/CreationContextImpl.java
  encoders/firebase-decoders-json/src/json/java/com/google/firebase/decoders/json/JsonDataDecoderBuilderContext.java
  encoders/firebase-decoders-json/src/test/java/com/google/firebase/decoders/json/JsonDataDecoderBuilderContextDefaultValueTest.java
  encoders/firebase-decoders-json/src/test/java/com/google/firebase/decoders/json/JsonDataDecoderBuilderContextTest.java
Labels: cla: yes, size/L

#1761 Add missing parenthesis to link.
  firebase-config/src/main/java/com/google/firebase/remoteconfig/FirebaseRemoteConfig.java
Labels: cla: yes, size/XS

#1765 Upgrade to AGP 4.1.0-beta2 + Gradle 6.5.1 for project apk-size.
  apk-size/apk-size.gradle
  apk-size/app/configure.gradle
  apk-size/gradle.properties
  apk-size/gradle/wrapper/gradle-wrapper.jar
  apk-size/gradle/wrapper/gradle-wrapper.properties
  apk-size/gradlew
  apk-size/gradlew.bat
  ci/fireci/fireciplugins/binary_size.py
  firebase-config/src/main/java/com/google/firebase/remoteconfig/FirebaseRemoteConfig.java
Labels: cla: yes, size/L

#1760 Migrate firebase-crashlytics SDK to FIS
  firebase-crashlytics/firebase-crashlytics.gradle
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/CLSUUIDTest.java
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/CommonUtilsTest.java
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/CrashlyticsControllerTest.java
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/CrashlyticsCoreInitializationTest.java
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/CrashlyticsCoreTest.java
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/CrashlyticsReportDataCaptureTest.java
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/IdManagerTest.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/CrashlyticsRegistrar.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/FirebaseCrashlytics.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/IdManager.java
Labels: cla: yes, size/L

#1767 Revert caching fid & disk read on caller thread.
  firebase-installations/src/main/java/com/google/firebase/installations/FirebaseInstallations.java
  firebase-installations/src/main/java/com/google/firebase/installations/GetIdListener.java
Labels: cla: yes, size/M

#1764 Patch caching fid in memory on successful registration.
  firebase-installations/src/main/java/com/google/firebase/installations/FirebaseInstallations.java
  firebase-installations/src/main/java/com/google/firebase/installations/GetIdListener.java
Labels: cla: yes, size/M

#1693 Cleaning up and addressing issues with FIAM docs
  firebase-inappmessaging-display/src/main/java/com/google/firebase/inappmessaging/display/FirebaseInAppMessagingDisplay.java
  firebase-inappmessaging/src/main/java/com/google/firebase/inappmessaging/FirebaseInAppMessaging.java
  firebase-inappmessaging/src/main/java/com/google/firebase/inappmessaging/model/Action.java
  firebase-inappmessaging/src/main/java/com/google/firebase/inappmessaging/model/CampaignMetadata.java
  firebase-inappmessaging/src/main/java/com/google/firebase/inappmessaging/model/CardMessage.java
  firebase-inappmessaging/src/main/java/com/google/firebase/inappmessaging/model/ImageData.java
  firebase-inappmessaging/src/main/java/com/google/firebase/inappmessaging/model/InAppMessage.java
  firebase-inappmessaging/src/main/java/com/google/firebase/inappmessaging/model/TriggeredInAppMessage.java
Labels: cla: yes, size/M

#1774 Adding a descriptive auth error message.
  firebase-installations/src/main/java/com/google/firebase/installations/FirebaseInstallations.java
Labels: cla: yes, size/XS

#1777 Improve kotlindoc rendering.
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/Dokka.java
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/FirebaseLibraryPlugin.java
  firebase-common/firebase-common.gradle
  kotlindoc/package-lists/firebase/package-list
Labels: cla: yes, size/L

#1804 Upgrade dokka to include the external link fix.
  buildSrc/build.gradle
Labels: cla: yes, size/XS

#1803 Migrate reflective encoder to `FieldDescriptor`.
  encoders/firebase-encoders-reflective/firebase-encoders-reflective.gradle
  encoders/firebase-encoders-reflective/src/main/java/com/google/firebase/encoders/reflective/ReflectiveObjectEncoderProvider.java
  encoders/firebase-encoders-reflective/src/test/java/com/google/firebase/encoders/reflective/ReflectiveObjectEncoderTest.java
Labels: cla: yes, size/M

#1800 Disable debug build for apk size measurements.
  apk-size/app/default.gradle
Labels: cla: yes, size/S

#1812 Javadoc fixes.
  firebase-common/ktx/src/main/kotlin/com/google/firebase/ktx/Firebase.kt
  firebase-config/src/main/java/com/google/firebase/remoteconfig/FirebaseRemoteConfig.java
Labels: cla: yes, size/M

#1814 Delete stale unused groovy files.
  buildSrc/src/test/groovy22/com/google/firebase/gradle/plugins/license/LicenseResolverPluginSpec.groovy
  buildSrc/src/test/groovy22/com/google/firebase/gradle/plugins/publish/PublishingPluginSpec.groovy
Labels: cla: yes, size/L

#1717 Support Collections decoding
  encoders/firebase-decoders-json/src/json/java/com/google/firebase/decoders/json/JsonDataDecoderBuilderContext.java
  encoders/firebase-decoders-json/src/test/java/com/google/firebase/decoders/json/JsonDataDecoderBuilderContextCollectionDecodingTest.java
  encoders/firebase-decoders-json/src/test/java/com/google/firebase/decoders/json/JsonDataDecoderBuilderContextMapDecodingTest.java
Labels: cla: yes, size/L

#1816 update versions for release
  firebase-crashlytics-ndk/gradle.properties
  firebase-crashlytics/gradle.properties
Labels: cla: yes, size/XS

#1815 initial implementation of decoder builder
  encoders/firebase-decoders-json/api.txt
  encoders/firebase-decoders-json/src/json/java/com/google/firebase/decoders/json/CreationContextImpl.java
  encoders/firebase-decoders-json/src/json/java/com/google/firebase/decoders/json/JsonDataDecoderBuilder.java
  encoders/firebase-decoders-json/src/json/java/com/google/firebase/decoders/json/JsonDataDecoderContext.java
  encoders/firebase-decoders-json/src/main/java/com/google/firebase/decoders/DecoderConfig.java
  encoders/firebase-decoders-json/src/test/java/com/google/firebase/decoders/json/JsonDataDecoderBuilderContextCollectionDecodingTest.java
  encoders/firebase-decoders-json/src/test/java/com/google/firebase/decoders/json/JsonDataDecoderBuilderContextDefaultValueTest.java
  encoders/firebase-decoders-json/src/test/java/com/google/firebase/decoders/json/JsonDataDecoderBuilderContextMapDecodingTest.java
  encoders/firebase-decoders-json/src/test/java/com/google/firebase/decoders/json/JsonDataDecoderBuilderTest.java
  encoders/firebase-decoders-json/src/test/java/com/google/firebase/decoders/json/JsonDataDecoderContextTest.java
Labels: cla: yes, size/L

#1813 inital implementation of AnnotationFieldHandler
  encoders/firebase-decoders-json/api.txt
  encoders/firebase-decoders-json/src/json/java/com/google/firebase/decoders/json/JsonDataDecoderContext.java
  encoders/firebase-decoders-json/src/json/java/com/google/firebase/decoders/json/ObjectDecoderContextImpl.java
  encoders/firebase-decoders-json/src/main/java/com/google/firebase/decoders/AnnotatedFieldHandler.java
  encoders/firebase-decoders-json/src/test/java/com/google/firebase/decoders/json/JsonDataDecoderExtraPropertyTest.java
  encoders/firebase-encoders-json/api.txt
  encoders/firebase-encoders-json/src/main/java/com/google/firebase/encoders/FieldDescriptor.java
Labels: cla: yes, size/L

#1802 Re-implement Unified Emulator Settings
  docs/ktx/firestore.md
  firebase-common/src/androidTest/java/com/google/firebase/FirebaseAppTest.java
  firebase-common/src/main/java/com/google/firebase/FirebaseApp.java
  firebase-common/src/main/java/com/google/firebase/emulators/EmulatedServiceSettings.java
  firebase-common/src/main/java/com/google/firebase/emulators/EmulatorSettings.java
  firebase-common/src/main/java/com/google/firebase/emulators/FirebaseEmulator.java
  firebase-database/CHANGELOG.md
  firebase-database/api.txt
  firebase-database/gradle.properties
  firebase-database/src/androidTest/java/com/google/firebase/database/FirebaseDatabaseTest.java
  firebase-database/src/main/java/com/google/firebase/database/FirebaseDatabase.java
  firebase-database/src/main/java/com/google/firebase/database/core/RepoInfo.java
  firebase-database/src/main/java/com/google/firebase/database/core/utilities/Utilities.java
  firebase-database/src/test/java/com/google/firebase/database/core/utilities/ParseUrlTest.java
  firebase-firestore/CHANGELOG.md
  firebase-firestore/api.txt
  firebase-firestore/gradle.properties
  firebase-firestore/ktx/src/test/kotlin/com/google/firebase/firestore/ktx/FirestoreTests.kt
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/AccessHelper.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/FirebaseFirestore.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/FirebaseFirestoreTest.java
  firebase-functions/api.txt
  firebase-functions/gradle.properties
  firebase-functions/src/androidTest/java/com/google/firebase/functions/CallTest.java
  firebase-functions/src/androidTest/java/com/google/firebase/functions/FirebaseFunctionsTest.java
  firebase-functions/src/main/java/com/google/firebase/functions/FirebaseFunctions.java
  firebase-functions/src/main/java/com/google/firebase/functions/FunctionsMultiResourceComponent.java
Labels: cla: yes, size/XL

#1829 Properly release storage on exit
  firebase-crashlytics-ndk/src/main/jni/libcrashlytics/include/crashlytics/detail/memory/allocate.h
  firebase-crashlytics-ndk/src/main/jni/libcrashlytics/src/handler/install.cpp
Labels: cla: yes, size/XS

#1434 Update crashlytics global data collection
  firebase-crashlytics/api.txt
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/CrashlyticsControllerTest.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/FirebaseCrashlytics.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsCore.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/DataCollectionArbiter.java
Labels: cla: yes, size/L

#1833 Add support to register AnnotatedFieldHandler in decoder
  encoders/firebase-decoders-json/api.txt
  encoders/firebase-decoders-json/src/json/java/com/google/firebase/decoders/json/JsonDataDecoderBuilder.java
  encoders/firebase-decoders-json/src/json/java/com/google/firebase/decoders/json/JsonDataDecoderContext.java
  encoders/firebase-decoders-json/src/main/java/com/google/firebase/decoders/AnnotatedFieldHandler.java
  encoders/firebase-decoders-json/src/main/java/com/google/firebase/decoders/DecoderConfig.java
  encoders/firebase-decoders-json/src/test/java/com/google/firebase/decoders/json/JsonDataDecoderAnnotatedFieldHandlerTest.java
  encoders/firebase-decoders-json/src/test/java/com/google/firebase/decoders/json/JsonDataDecoderBuilderContextCollectionDecodingTest.java
  encoders/firebase-decoders-json/src/test/java/com/google/firebase/decoders/json/JsonDataDecoderBuilderContextDefaultValueTest.java
  encoders/firebase-decoders-json/src/test/java/com/google/firebase/decoders/json/JsonDataDecoderBuilderContextMapDecodingTest.java
  encoders/firebase-decoders-json/src/test/java/com/google/firebase/decoders/json/JsonDataDecoderContextTest.java
Labels: cla: yes, size/L
