Repository firebase/firebase-android-sdk, pull requests merged in 2020-12, with the labels that each got.

#2214 Update latest released versions.
  encoders/firebase-encoders-json/gradle.properties
  encoders/firebase-encoders/gradle.properties
  firebase-abt/gradle.properties
  firebase-common/gradle.properties
  firebase-components/gradle.properties
  firebase-config/gradle.properties
  firebase-crashlytics-ndk/gradle.properties
  firebase-crashlytics/gradle.properties
  firebase-database/gradle.properties
  firebase-datatransport/gradle.properties
  firebase-firestore/gradle.properties
  firebase-inappmessaging-display/gradle.properties
  firebase-inappmessaging/gradle.properties
  firebase-installations/gradle.properties
  firebase-messaging-directboot/gradle.properties
  firebase-messaging/gradle.properties
  transport/transport-backend-cct/gradle.properties
Labels: cla: yes, size/M

#2215 Throw IOException for deleted files
  firebase-storage/CHANGELOG.md
  firebase-storage/src/main/java/com/google/firebase/storage/FileDownloadTask.java
Labels: api: storage, cla: yes, size/XS

#2195 Adding a FidListener that propagates fid changes to the clients.
  firebase-installations-interop/firebase-installations-interop.gradle
  firebase-installations-interop/src/main/java/com/google/firebase/installations/FirebaseInstallationsApi.java
  firebase-installations-interop/src/main/java/com/google/firebase/installations/internal/FidListener.java
  firebase-installations-interop/src/main/java/com/google/firebase/installations/internal/FidListenerHandle.java
  firebase-installations/api.txt
  firebase-installations/src/main/java/com/google/firebase/installations/FirebaseInstallations.java
  firebase-installations/src/test/java/com/google/firebase/installations/FakeFidListener.java
  firebase-installations/src/test/java/com/google/firebase/installations/FirebaseInstallationsTest.java
Labels: cla: yes, size/L

#2217 Check for missing metadata when constructing ConfigContainer.
  firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigContainer.java
  firebase-config/src/test/java/com/google/firebase/remoteconfig/internal/ConfigStorageClientTest.java
Labels: cla: yes, size/M

#2216 Don't crash SDK is socket.close() fails
  firebase-database/CHANGELOG.md
  firebase-database/src/main/java/com/google/firebase/database/tubesock/WebSocket.java
Labels: api: database, cla: yes, size/S

#2224 Add update transforms proto
  firebase-firestore/src/proto/google/firestore/v1/write.proto
Labels: api: firestore, cla: yes, size/S

#2223 Enabling Test Orchestrator
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/ci/device/FirebaseTestServer.java
Labels: cla: yes, size/XS

#2212 Adding get Model for local downloads
  firebase-ml-modeldownloader/api.txt
  firebase-ml-modeldownloader/firebase-ml-modeldownloader.gradle
  firebase-ml-modeldownloader/src/main/java/com/google/firebase/ml/modeldownloader/CustomModel.java
  firebase-ml-modeldownloader/src/main/java/com/google/firebase/ml/modeldownloader/FirebaseModelDownloader.java
  firebase-ml-modeldownloader/src/main/java/com/google/firebase/ml/modeldownloader/FirebaseModelDownloaderRegistrar.java
  firebase-ml-modeldownloader/src/main/java/com/google/firebase/ml/modeldownloader/internal/CustomModelDownloadService.java
  firebase-ml-modeldownloader/src/main/java/com/google/firebase/ml/modeldownloader/internal/ModelFileDownloadService.java
  firebase-ml-modeldownloader/src/main/java/com/google/firebase/ml/modeldownloader/internal/ModelFileManager.java
  firebase-ml-modeldownloader/src/main/java/com/google/firebase/ml/modeldownloader/internal/SharedPreferencesUtil.java
  firebase-ml-modeldownloader/src/test/java/com/google/firebase/ml/modeldownloader/CustomModelDownloadConditionsTest.java
  firebase-ml-modeldownloader/src/test/java/com/google/firebase/ml/modeldownloader/CustomModelTest.java
  firebase-ml-modeldownloader/src/test/java/com/google/firebase/ml/modeldownloader/FirebaseModelDownloaderTest.java
  firebase-ml-modeldownloader/src/test/java/com/google/firebase/ml/modeldownloader/TestOnCompleteListener.java
  firebase-ml-modeldownloader/src/test/java/com/google/firebase/ml/modeldownloader/internal/CustomModelDownloadServiceTest.java
  firebase-ml-modeldownloader/src/test/java/com/google/firebase/ml/modeldownloader/internal/ModelFileDownloadServiceTest.java
  firebase-ml-modeldownloader/src/test/java/com/google/firebase/ml/modeldownloader/internal/ModelFileManagerTest.java
  firebase-ml-modeldownloader/src/test/java/com/google/firebase/ml/modeldownloader/internal/SharedPreferencesUtilTest.java
Labels: cla: yes, size/XXL

#2231 RTDB Query get method must be public
  firebase-database/src/main/java/com/google/firebase/database/Query.java
Labels: cla: yes, size/XS

#2232 Add query get() to api text file for firebase-database
  firebase-database/api.txt
Labels: cla: yes, size/XS

#2229 Add unit test for Unauthenticated error unit.
  firebase-ml-modeldownloader/src/test/java/com/google/firebase/ml/modeldownloader/internal/CustomModelDownloadServiceTest.java
Labels: cla: yes, size/M

#2235 Fix deadlock issue.
  firebase-components/src/main/java/com/google/firebase/components/ComponentRuntime.java
  firebase-components/src/test/java/com/google/firebase/components/threading/AnotherEagerComponent.java
  firebase-components/src/test/java/com/google/firebase/components/threading/DeadlockTests.java
  firebase-components/src/test/java/com/google/firebase/components/threading/EagerComponent.java
Labels: cla: yes, size/L

#2237 Add support for non-primitive Booleans.
  encoders/firebase-encoders-proto/src/main/java/com/google/firebase/encoders/proto/ProtobufDataEncoderContext.java
  encoders/firebase-encoders-proto/src/test/java/com/google/firebase/encoders/proto/Encoder.java
  encoders/firebase-encoders-proto/src/test/java/com/google/firebase/encoders/proto/OtherTypesEncodingTests.java
  encoders/firebase-encoders-proto/src/test/java/com/google/firebase/encoders/proto/WithCollectionsTests.java
  encoders/firebase-encoders-proto/src/test/java/com/google/firebase/encoders/proto/pojos/OtherTypes.java
  encoders/firebase-encoders-proto/src/test/proto/test.proto
Labels: cla: yes, size/M

#2242 Fix the smoke tests.
  smoke-tests/build.gradle
  smoke-tests/src/main/java/com/google/firebase/testing/BuildOnlyTest.java
  smoke-tests/src/main/java/com/google/firebase/testing/PerformanceMonitoringTest.java
  smoke-tests/src/main/java/com/google/firebase/testing/TestSuite.java
Labels: cla: yes, size/M

#2248 Grammar fixes for database comments.
  firebase-database/src/main/java/com/google/firebase/database/Query.java
Labels: cla: yes, size/XS

#2236 Delete model
  firebase-ml-modeldownloader/api.txt
  firebase-ml-modeldownloader/src/main/java/com/google/firebase/ml/modeldownloader/CustomModel.java
  firebase-ml-modeldownloader/src/main/java/com/google/firebase/ml/modeldownloader/FirebaseModelDownloader.java
  firebase-ml-modeldownloader/src/main/java/com/google/firebase/ml/modeldownloader/internal/ModelFileManager.java
  firebase-ml-modeldownloader/src/main/java/com/google/firebase/ml/modeldownloader/internal/SharedPreferencesUtil.java
  firebase-ml-modeldownloader/src/test/java/com/google/firebase/ml/modeldownloader/CustomModelTest.java
  firebase-ml-modeldownloader/src/test/java/com/google/firebase/ml/modeldownloader/FirebaseModelDownloaderTest.java
  firebase-ml-modeldownloader/src/test/java/com/google/firebase/ml/modeldownloader/internal/ModelFileDownloadServiceTest.java
  firebase-ml-modeldownloader/src/test/java/com/google/firebase/ml/modeldownloader/internal/ModelFileManagerTest.java
  firebase-ml-modeldownloader/src/test/java/com/google/firebase/ml/modeldownloader/internal/SharedPreferencesUtilTest.java
Labels: cla: yes, size/L

#2228 Update split install listener to high priority.
  firebase-components/firebase-dynamic-module-support/firebase-dynamic-module-support.gradle
  firebase-components/firebase-dynamic-module-support/gradle.properties
  firebase-components/firebase-dynamic-module-support/src/main/java/com/google/firebase/dynamicloading/DynamicLoadingSupport.java
Labels: cla: yes, size/S

#2246 Reflection tests to verify LoadBundleTask implement all interface of Task
  firebase-firestore/src/main/java/com/google/firebase/firestore/LoadBundleTask.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/LoadBundleTaskProgress.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/LoadBundleTaskTest.java
Labels: cla: yes, size/L

#2260 Don't include stacktrace in class load failure log
  firebase-components/src/main/java/com/google/firebase/components/ComponentDiscovery.java
Labels: cla: yes, size/XS

#2263 Catch null on queryIntentServices to fix NPE
  firebase-inappmessaging-display/src/main/java/com/google/firebase/inappmessaging/display/FirebaseInAppMessagingDisplay.java
Labels: cla: yes, size/XS

#2262 Replace usage of transform with updateTransforms
  firebase-firestore/CHANGELOG.md
  firebase-firestore/src/main/java/com/google/firebase/firestore/DocumentReference.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/UserDataReader.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/WriteBatch.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/Transaction.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/UserData.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/LocalSerializer.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/LocalStore.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/model/ServerTimestamps.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/model/mutation/DeleteMutation.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/model/mutation/Mutation.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/model/mutation/MutationResult.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/model/mutation/PatchMutation.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/model/mutation/SetMutation.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/model/mutation/TransformMutation.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/model/mutation/TransformOperation.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/model/mutation/VerifyMutation.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/remote/RemoteSerializer.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/LocalSerializerTest.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/LocalStoreTestCase.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/model/MutationTest.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/remote/RemoteSerializerTest.java
  firebase-firestore/src/testUtil/java/com/google/firebase/firestore/testutil/TestUtil.java
Labels: api: firestore, cla: yes, size/XXL

#2272 Update issue templates
  .github/ISSUE_TEMPLATE/bug.md
Labels: cla: yes, size/XS

#2254 Background update
  firebase-ml-modeldownloader/src/main/java/com/google/firebase/ml/modeldownloader/FirebaseModelDownloader.java
  firebase-ml-modeldownloader/src/main/java/com/google/firebase/ml/modeldownloader/internal/ModelFileDownloadService.java
  firebase-ml-modeldownloader/src/main/java/com/google/firebase/ml/modeldownloader/internal/ModelFileManager.java
  firebase-ml-modeldownloader/src/test/java/com/google/firebase/ml/modeldownloader/FirebaseModelDownloaderTest.java
Labels: cla: yes, size/XL
