Repository firebase/firebase-android-sdk, pull requests merged in 2020-08, with the labels that each got.

#1841 Add logging of data collection state
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsCore.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/DataCollectionArbiter.java
Labels: cla: yes, size/M

#1850 Update Javadocs for setCrashlyticsCollectionEnabled API
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/FirebaseCrashlytics.java
Labels: cla: yes, size/S

#1851 Update latest released versions.
  firebase-abt/gradle.properties
  firebase-config/gradle.properties
  firebase-crashlytics-ndk/gradle.properties
  firebase-crashlytics/gradle.properties
  firebase-database/gradle.properties
  firebase-firestore/gradle.properties
  firebase-functions/gradle.properties
  firebase-inappmessaging-display/gradle.properties
  firebase-inappmessaging/gradle.properties
  firebase-installations/gradle.properties
  firebase-messaging-directboot/gradle.properties
  firebase-messaging/gradle.properties
  protolite-well-known-types/gradle.properties
  transport/transport-backend-cct/gradle.properties
Labels: cla: yes, size/M

#1856 Add protos for != queries
  firebase-firestore/src/proto/google/firestore/v1/query.proto
Labels: api: firestore, cla: yes, size/M

#1834 Fix Double Logging of FCM
  firebase-messaging/src/main/java/com/google/firebase/messaging/FirebaseMessagingService.java
  firebase-messaging/src/main/java/com/google/firebase/messaging/MessagingAnalytics.java
  firebase-messaging/src/test/java/com/google/firebase/messaging/MessagingAnalyticsRoboTest.java
Labels: cla: yes, size/L

#1852 Added support channels to contacts
  .github/config.yml
Labels: cla: yes, size/XS

#1827 initial implementation of reflective decoder
  encoders/firebase-decoders-json/api.txt
  encoders/firebase-decoders-json/src/json/java/com/google/firebase/decoders/json/JsonDataDecoderBuilder.java
  encoders/firebase-decoders-json/src/json/java/com/google/firebase/decoders/json/JsonDataDecoderContext.java
  encoders/firebase-decoders-json/src/main/java/com/google/firebase/decoders/TypeToken.java
  encoders/firebase-encoders-reflective/api.txt
  encoders/firebase-encoders-reflective/firebase-encoders-reflective.gradle
  encoders/firebase-encoders-reflective/src/main/java/com/google/firebase/encoders/reflective/ReflectiveDecoderFieldContext.java
  encoders/firebase-encoders-reflective/src/main/java/com/google/firebase/encoders/reflective/ReflectiveInitializer.java
  encoders/firebase-encoders-reflective/src/main/java/com/google/firebase/encoders/reflective/ReflectiveObjectDecoder.java
  encoders/firebase-encoders-reflective/src/main/java/com/google/firebase/encoders/reflective/ReflectiveObjectDecoderImpl.java
  encoders/firebase-encoders-reflective/src/main/java/com/google/firebase/encoders/reflective/ReflectiveSetter.java
  encoders/firebase-encoders-reflective/src/test/java/com/google/firebase/encoders/reflective/ReflectiveObjectDecoderTest.java
Labels: cla: yes, size/XL

#1855 Log-adjusted backoff logic.
  transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/scheduling/jobscheduling/SchedulerConfig.java
  transport/transport-runtime/src/test/java/com/google/android/datatransport/runtime/scheduling/jobscheduling/ScheduleDelayTest.java
  transport/transport-runtime/src/test/java/com/google/android/datatransport/runtime/scheduling/jobscheduling/SchedulerConfigTest.java
Labels: cla: yes, size/L

#1840 Initialize Firebase in direct boot mode
  firebase-common/src/main/AndroidManifest.xml
  firebase-common/src/main/java/com/google/firebase/FirebaseApp.java
Labels: cla: yes, size/S

#1753 add more extension functions for dynamic-links-ktx
  firebase-dynamic-links/ktx/api.txt
  firebase-dynamic-links/ktx/src/main/kotlin/com/google/firebase/dynamiclinks/ktx/FirebaseDynamicLinks.kt
  firebase-dynamic-links/ktx/src/test/kotlin/com/google/firebase/dynamiclinks/ktx/DynamicLinksTests.kt
Labels: cla: yes, ok-to-test, size/M

#1870 Fix formatting error with messaging
  firebase-messaging/src/test/java/com/google/firebase/messaging/MessagingAnalyticsRoboTest.java
Labels: cla: yes, size/XS

#1862 docs: add ktx/crashlytics.md to .opensource/project.json
  .opensource/project.json
Labels: cla: yes, ok-to-test, size/XS

#1871 Remove `@hide` javadoc from generated classes
  encoders/firebase-encoders-processor/src/main/java/com/google/firebase/encoders/processor/EncodableProcessor.java
Labels: cla: yes, size/XS

#1866 Address RTDB Lint violations
  firebase-database/src/main/java/com/google/firebase/database/DatabaseError.java
  firebase-database/src/main/java/com/google/firebase/database/Query.java
  firebase-database/src/main/java/com/google/firebase/database/android/SqlPersistenceStorageEngine.java
  firebase-database/src/main/java/com/google/firebase/database/connection/PersistentConnectionImpl.java
  firebase-database/src/main/java/com/google/firebase/database/core/CompoundWrite.java
  firebase-database/src/main/java/com/google/firebase/database/core/EventRegistration.java
  firebase-database/src/main/java/com/google/firebase/database/core/Path.java
  firebase-database/src/main/java/com/google/firebase/database/core/Repo.java
  firebase-database/src/main/java/com/google/firebase/database/core/SyncPoint.java
  firebase-database/src/main/java/com/google/firebase/database/core/SyncTree.java
  firebase-database/src/main/java/com/google/firebase/database/core/WriteTree.java
  firebase-database/src/main/java/com/google/firebase/database/core/ZombieEventManager.java
  firebase-database/src/main/java/com/google/firebase/database/core/operation/ListenComplete.java
  firebase-database/src/main/java/com/google/firebase/database/core/operation/OperationSource.java
  firebase-database/src/main/java/com/google/firebase/database/core/persistence/DefaultPersistenceManager.java
  firebase-database/src/main/java/com/google/firebase/database/core/persistence/TrackedQueryManager.java
  firebase-database/src/main/java/com/google/firebase/database/core/utilities/NodeSizeEstimator.java
  firebase-database/src/main/java/com/google/firebase/database/core/utilities/PushIdGenerator.java
  firebase-database/src/main/java/com/google/firebase/database/core/utilities/Tree.java
  firebase-database/src/main/java/com/google/firebase/database/core/utilities/Utilities.java
  firebase-database/src/main/java/com/google/firebase/database/core/utilities/encoding/CustomClassMapper.java
  firebase-database/src/main/java/com/google/firebase/database/core/view/EventGenerator.java
  firebase-database/src/main/java/com/google/firebase/database/core/view/QueryParams.java
  firebase-database/src/main/java/com/google/firebase/database/core/view/View.java
  firebase-database/src/main/java/com/google/firebase/database/core/view/ViewProcessor.java
  firebase-database/src/main/java/com/google/firebase/database/core/view/filter/ChildChangeAccumulator.java
  firebase-database/src/main/java/com/google/firebase/database/core/view/filter/IndexedFilter.java
  firebase-database/src/main/java/com/google/firebase/database/core/view/filter/LimitedFilter.java
  firebase-database/src/main/java/com/google/firebase/database/snapshot/ChildKey.java
  firebase-database/src/main/java/com/google/firebase/database/snapshot/ChildrenNode.java
  firebase-database/src/main/java/com/google/firebase/database/snapshot/DeferredValueNode.java
  firebase-database/src/main/java/com/google/firebase/database/snapshot/DoubleNode.java
  firebase-database/src/main/java/com/google/firebase/database/snapshot/KeyIndex.java
  firebase-database/src/main/java/com/google/firebase/database/snapshot/LeafNode.java
  firebase-database/src/main/java/com/google/firebase/database/snapshot/RangeMerge.java
Labels: cla: yes, size/L

#1873 Fix FIAM API Definition
  firebase-inappmessaging/api.txt
Labels: cla: yes, size/XS

#1788 Migrate metalava download to gradle's resolution process.
  build.gradle
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/FirebaseJavaLibraryPlugin.java
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/FirebaseLibraryPlugin.java
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/Metalava.kt
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/SdkUtil.java
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/SdkUtil.kt
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/apiinfo/ApiInformationTask.java
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/apiinfo/GenerateApiTxtFileTask.java
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/apiinfo/GenerateStubsTask.java
  buildSrc/src/test/kotlin/com/google/firebase/gradle/plugins/PublishingPluginTests.kt
  buildSrc/src/test/kotlin/com/google/firebase/gradle/plugins/publishing.kt
Labels: cla: yes, size/L

#1872 Add != and NOT_IN queries (not public)
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/QueryTest.java
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/ValidationTest.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/Query.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/FieldFilter.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/Filter.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/KeyFieldInFilter.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/KeyFieldNotInFilter.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/NotInFilter.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/remote/RemoteSerializer.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/core/QueryTest.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/remote/RemoteSerializerTest.java
  firebase-firestore/src/testUtil/java/com/google/firebase/firestore/testutil/TestUtil.java
Labels: api: firestore, cla: yes, size/XL

#1880 Updated latest release versions.
  firebase-common/gradle.properties
  firebase-crashlytics-ndk/gradle.properties
  firebase-crashlytics/gradle.properties
  firebase-datatransport/gradle.properties
  transport/transport-api/gradle.properties
  transport/transport-backend-cct/gradle.properties
  transport/transport-runtime/gradle.properties
Labels: cla: yes, size/S

#1644 feat(storage-ktx): destructure ListResult and TaskSnapshots
  firebase-storage/ktx/api.txt
  firebase-storage/ktx/ktx.gradle
  firebase-storage/ktx/src/main/kotlin/com/google/firebase/storage/ktx/Storage.kt
  firebase-storage/ktx/src/test/kotlin/com/google/firebase/storage/ktx/StorageTest.kt
  firebase-storage/src/testUtil/java/com/google/firebase/storage/KtxTestUtil.java
Labels: cla: yes, ok-to-test, size/L

#1821 Add dependency vendoring support.
  buildSrc/build.gradle
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/VendorPlugin.kt
  buildSrc/src/test/kotlin/com/google/firebase/gradle/plugins/VendorTests.kt
  firebase-inappmessaging-display/firebase-inappmessaging-display.gradle
  firebase-inappmessaging/firebase-inappmessaging.gradle
  transport/transport-runtime/transport-runtime.gradle
Labels: cla: yes, size/L

#1897 Add third_party_licenses for libraries that vendor Dagger.
  buildSrc/build.gradle
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/VendorPlugin.kt
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/license/ThirdPartyLicensesExtension.java
  firebase-inappmessaging-display/firebase-inappmessaging-display.gradle
  firebase-inappmessaging/firebase-inappmessaging.gradle
  third_party/jsoup/LICENSE
  third_party/jsoup/src/main/java/org/jsoup/examples/HtmlToPlainText.java
  third_party/licenses/apache-2.0.txt
  transport/transport-runtime/transport-runtime.gradle
Labels: cla: yes, size/XXL

#1898 Infer database URL from Project ID
  firebase-database/CHANGELOG.md
  firebase-database/src/androidTest/java/com/google/firebase/database/FirebaseDatabaseTest.java
  firebase-database/src/main/java/com/google/firebase/database/FirebaseDatabase.java
Labels: api: firestore, cla: yes, size/S

#1902 update versions
  firebase-database/gradle.properties
  firebase-firestore/gradle.properties
  firebase-functions/gradle.properties
  firebase-storage/gradle.properties
Labels: cla: yes, size/XS

#1892 Play service plugin version check ?
  smoke-tests/build.gradle
Labels: cla: yes, size/XS

#1916 Handling AssertionError thrown by JsonReader causing Play Games app-crashes.
  firebase-installations/src/main/java/com/google/firebase/installations/remote/FirebaseInstallationServiceClient.java
Labels: cla: yes, size/S

#1901 Add FIS Kotlin Extensions SDK.
  firebase-installations/ktx/api.txt
  firebase-installations/ktx/ktx.gradle
  firebase-installations/ktx/src/main/AndroidManifest.xml
  firebase-installations/ktx/src/main/kotlin/com/google/firebase/installations/ktx/Installations.kt
  firebase-installations/ktx/src/test/kotlin/com/google/firebase/installations/ktx/InstallationsTests.kt
  subprojects.cfg
Labels: cla: yes, size/L

#1899 Add FCM ktx library.
  firebase-messaging-directboot/src/main/AndroidManifest.xml
  firebase-messaging/api.txt
  firebase-messaging/ktx/api.txt
  firebase-messaging/ktx/gradle.properties
  firebase-messaging/ktx/ktx.gradle
  firebase-messaging/ktx/src/main/AndroidManifest.xml
  firebase-messaging/ktx/src/main/kotlin/com/google/firebase/messaging/ktx/Messaging.kt
  firebase-messaging/ktx/src/test/kotlin/com/google/firebase/messaging/ktx/MessagingTests.kt
  firebase-messaging/src/main/java/com/google/firebase/messaging/FirebaseMessaging.java
  firebase-messaging/src/main/java/com/google/firebase/messaging/RemoteMessage.java
  subprojects.cfg
Labels: cla: yes, size/L

#1920 Remove usages of Protobuf equals
  firebase-firestore/src/main/java/com/google/firebase/firestore/model/Values.java
Labels: api: firestore, cla: yes, size/XS

#1919 Address reference doc review comments
  firebase-database/src/main/java/com/google/firebase/database/FirebaseDatabase.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/FirebaseFirestore.java
  firebase-functions/src/main/java/com/google/firebase/functions/FirebaseFunctions.java
Labels: cla: yes, size/S

#1925 lazy initialization of heartbeat
  firebase-installations/src/main/java/com/google/firebase/installations/FirebaseInstallations.java
  firebase-installations/src/main/java/com/google/firebase/installations/FirebaseInstallationsRegistrar.java
  firebase-installations/src/main/java/com/google/firebase/installations/remote/FirebaseInstallationServiceClient.java
Labels: cla: yes, size/M
