Repository firebase/firebase-android-sdk, pull requests merged in 2020-06, with the labels that each got.

#1606 Changed TypeTokenContainer from interface to class
  encoders/firebase-decoders-json/api.txt
  encoders/firebase-decoders-json/src/main/java/com/google/firebase/decoders/TypeToken.java
  encoders/firebase-decoders-json/src/main/java/com/google/firebase/decoders/TypeTokenContainer.java
  encoders/firebase-decoders-json/src/test/java/com/google/firebase/decoders/TypeTokenTest.java
Labels: cla: yes, size/M

#1563 Remove pom deps after iteration.
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/publish/Publisher.java
Labels: cla: yes, size/XS

#1612 implemented hashcode, equals, toString methods for TypeToken in decoders
  encoders/firebase-decoders-json/src/main/java/com/google/firebase/decoders/TypeToken.java
  encoders/firebase-decoders-json/src/main/java/com/google/firebase/decoders/TypeTokenContainer.java
Labels: cla: yes, size/M

#1609 Avoid throwing explcit IOExceptions.
  firebase-installations/src/main/java/com/google/firebase/installations/FirebaseInstallations.java
  firebase-installations/src/main/java/com/google/firebase/installations/FirebaseInstallationsException.java
  firebase-installations/src/main/java/com/google/firebase/installations/remote/FirebaseInstallationServiceClient.java
  firebase-installations/src/test/java/com/google/firebase/installations/FirebaseInstallationsTest.java
Labels: cla: yes, size/L

#1613 Synchronize cached fid
  firebase-installations/src/main/java/com/google/firebase/installations/FirebaseInstallations.java
  firebase-installations/src/main/java/com/google/firebase/installations/FirebaseInstallationsException.java
Labels: cla: yes, size/S

#1503 feat: Implement firebase-crashlytics-ktx
  firebase-crashlytics/ktx/api.txt
  firebase-crashlytics/ktx/build.gradle
  firebase-crashlytics/ktx/gradle.properties
  firebase-crashlytics/ktx/src/main/AndroidManifest.xml
  firebase-crashlytics/ktx/src/main/kotlin/com/google/firebase/crashlytics/ktx/FirebaseCrashlytics.kt
  firebase-crashlytics/ktx/src/main/kotlin/com/google/firebase/crashlytics/ktx/KeyValueBuilder.kt
  firebase-crashlytics/ktx/src/test/java/com/google/firebase/crashlytics/ktx/CrashlyticsTests.kt
  subprojects.cfg
Labels: cla: yes, ok-to-test, size/L

#1618 Update latest released versions.
  firebase-crashlytics-ndk/gradle.properties
  firebase-crashlytics/gradle.properties
  firebase-datatransport/gradle.properties
  firebase-installations/gradle.properties
  transport/transport-backend-cct/gradle.properties
  transport/transport-runtime/gradle.properties
Labels: cla: yes, size/S

#1617 Add a deprecated setter for the data collection
  firebase-common/src/main/java/com/google/firebase/FirebaseApp.java
Labels: cla: yes, size/S

#1610 Add GMPID header to the RTDB SDK
  firebase-database/CHANGELOG.md
  firebase-database/src/main/java/com/google/firebase/database/connection/ConnectionContext.java
  firebase-database/src/main/java/com/google/firebase/database/connection/WebsocketConnection.java
  firebase-database/src/main/java/com/google/firebase/database/core/Context.java
Labels: cla: yes, size/S

#1627 Restore Java 8 support in encoders lib
  encoders/firebase-encoders-processor/src/main/java/com/google/firebase/encoders/processor/getters/GetterFactory.java
Labels: cla: yes, size/XS

#1628 Refetch token if attempt was invalidated
  firebase-firestore/CHANGELOG.md
  firebase-firestore/src/main/java/com/google/firebase/firestore/auth/FirebaseAuthCredentialsProvider.java
Labels: cla: yes, size/S

#1605 Send app_exception events based on a marker file
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsController.java
Labels: cla: yes, size/M

#1629 Have fiamd-ktx depend on fiam-ktx.
  firebase-inappmessaging-display/ktx/ktx.gradle
Labels: cla: yes, size/XS

#1630 Add tests for analytics integration
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/CrashlyticsAnalyticsListenerTest.java
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/analytics/BlockingAnalyticsEventLoggerTest.java
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/analytics/BreadcrumbAnalyticsEventReceiverTest.java
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/analytics/CrashlyticsOriginAnalyticsEventLoggerTest.java
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/CrashlyticsCoreTest.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/CrashlyticsAnalyticsListener.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/analytics/BlockingAnalyticsEventLogger.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/analytics/CrashlyticsOriginAnalyticsEventLogger.java
Labels: cla: yes, size/L

#1633 Merge Crashlytics/Analytics integration feature branch.
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/CrashlyticsAnalyticsListenerTest.java
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/analytics/AnalyticsConnectorReceiverTest.java
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/analytics/BlockingAnalyticsEventLoggerTest.java
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/analytics/BreadcrumbAnalyticsEventReceiverTest.java
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/analytics/CrashlyticsOriginAnalyticsEventLoggerTest.java
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/CrashlyticsControllerTest.java
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/CrashlyticsCoreInitializationTest.java
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/CrashlyticsCoreTest.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/CrashlyticsAnalyticsListener.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/FirebaseCrashlytics.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/analytics/AnalyticsConnectorReceiver.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/analytics/AnalyticsEventLogger.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/analytics/AnalyticsEventReceiver.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/analytics/AnalyticsReceiver.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/analytics/BlockingAnalyticsEventLogger.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/analytics/BreadcrumbAnalyticsEventReceiver.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/analytics/CrashlyticsOriginAnalyticsEventLogger.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/analytics/UnavailableAnalyticsEventLogger.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/breadcrumbs/BreadcrumbHandler.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/breadcrumbs/BreadcrumbSource.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/breadcrumbs/DisabledBreadcrumbSource.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsController.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsCore.java
Labels: cla: yes, size/XXL

#1636 Tweaks to the Crashlytics/FA integration
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/FirebaseCrashlytics.java
Labels: cla: yes, size/XS

#1635 Check for user ID file before trying to read it
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/persistence/CrashlyticsReportPersistence.java
Labels: cla: yes, size/S

#1639 Move crashlytics ktx test to androidTest
  firebase-crashlytics/ktx/ktx.gradle
  firebase-crashlytics/ktx/src/androidTest/AndroidManifest.xml
  firebase-crashlytics/ktx/src/androidTest/kotlin/com/google/firebase/crashlytics/ktx/CrashlyticsTests.kt
  firebase-crashlytics/ktx/src/androidTest/res/values/strings.xml
  firebase-crashlytics/ktx/src/main/kotlin/com/google/firebase/crashlytics/ktx/KeyValueBuilder.kt
  firebase-crashlytics/ktx/src/test/java/com/google/firebase/crashlytics/ktx/CrashlyticsTests.kt
Labels: cla: yes, size/L

#1649 Revert "Restore Java 8 support in encoders lib"
  encoders/firebase-encoders-processor/src/main/java/com/google/firebase/encoders/processor/getters/GetterFactory.java
Labels: cla: yes, size/XS

#1648 Revert "Add `FieldDescriptor` support to DataEncoder."
  encoders/firebase-encoders-json/api.txt
  encoders/firebase-encoders-json/src/json/java/com/google/firebase/encoders/json/JsonValueObjectEncoderContext.java
  encoders/firebase-encoders-json/src/main/java/com/google/firebase/encoders/FieldDescriptor.java
  encoders/firebase-encoders-json/src/main/java/com/google/firebase/encoders/ObjectEncoderContext.java
  encoders/firebase-encoders-processor/src/main/java/com/google/firebase/encoders/processor/EncodableProcessor.java
  encoders/firebase-encoders-processor/src/main/java/com/google/firebase/encoders/processor/annotations/AnnotationBuilder.java
  encoders/firebase-encoders-processor/src/main/java/com/google/firebase/encoders/processor/annotations/ToStringMethod.java
  encoders/firebase-encoders-processor/src/main/java/com/google/firebase/encoders/processor/getters/AnnotationDescriptor.java
  encoders/firebase-encoders-processor/src/main/java/com/google/firebase/encoders/processor/getters/AnnotationProperty.java
  encoders/firebase-encoders-processor/src/main/java/com/google/firebase/encoders/processor/getters/Getter.java
  encoders/firebase-encoders-processor/src/main/java/com/google/firebase/encoders/processor/getters/GetterFactory.java
  encoders/firebase-encoders-processor/src/test/java/com/google/firebase/encoders/processor/EncodableProcessorTest.java
  encoders/firebase-encoders-processor/src/test/resources/ExpectedGenericsEncoder.java
  encoders/firebase-encoders-processor/src/test/resources/ExpectedGenericsEncoderWithUnknownType.java
  encoders/firebase-encoders-processor/src/test/resources/ExpectedMyClassEncoderWithExtraProperty.java
  encoders/firebase-encoders-processor/src/test/resources/ExpectedRecursiveGenericEncoder.java
  encoders/firebase-encoders-processor/src/test/resources/ExpectedSimpleClassEncoder.java
  encoders/firebase-encoders-processor/src/test/resources/ExpectedTypeWithListEncoder.java
Labels: cla: yes, size/XL

#1655 Add missing package-info.java for new package
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/breadcrumbs/package-info.java
Labels: cla: yes, size/S

#1624 init implementation for decoder
  encoders/firebase-decoders-json/api.txt
  encoders/firebase-decoders-json/firebase-decoders-json.gradle
  encoders/firebase-decoders-json/src/json/java/com/google/firebase/decoders/json/CreationContextImpl.java
  encoders/firebase-decoders-json/src/json/java/com/google/firebase/decoders/json/JsonDataDecoderBuilderContext.java
  encoders/firebase-decoders-json/src/json/java/com/google/firebase/decoders/json/ObjectDecoderContextImpl.java
  encoders/firebase-decoders-json/src/main/java/com/google/firebase/decoders/CreationContext.java
  encoders/firebase-decoders-json/src/main/java/com/google/firebase/decoders/DataDecoder.java
  encoders/firebase-decoders-json/src/main/java/com/google/firebase/decoders/FieldRef.java
  encoders/firebase-decoders-json/src/main/java/com/google/firebase/decoders/ObjectDecoder.java
  encoders/firebase-decoders-json/src/main/java/com/google/firebase/decoders/ObjectDecoderContext.java
  encoders/firebase-decoders-json/src/main/java/com/google/firebase/decoders/TypeCreator.java
  encoders/firebase-decoders-json/src/test/java/com/google/firebase/decoders/FieldRefTest.java
  encoders/firebase-decoders-json/src/test/java/com/google/firebase/decoders/json/JsonDataDecoderBuilderContextTest.java
  encoders/firebase-encoders-json/firebase-encoders-json.gradle
Labels: cla: yes, size/XXL

#1665 Revert "Revert "Restore Java 8 support in encoders lib""
  encoders/firebase-encoders-processor/src/main/java/com/google/firebase/encoders/processor/getters/GetterFactory.java
Labels: cla: yes, size/XS

#1674 Check java version running the build.
  build.gradle
Labels: cla: yes, size/XS

#1579 Migrate RC to depend directly on Installations SDK.
  firebase-config/bandwagoner/bandwagoner.gradle
  firebase-config/bandwagoner/src/main/AndroidManifest.xml
  firebase-config/bandwagoner/src/main/java/com/googletest/firebase/remoteconfig/bandwagoner/ApiFragment.java
  firebase-config/firebase-config.gradle
  firebase-config/ktx/ktx.gradle
  firebase-config/ktx/src/test/kotlin/com/google/firebase/remoteconfig/TestConstructorUtil.kt
  firebase-config/ktx/src/test/kotlin/com/google/firebase/remoteconfig/ktx/RemoteConfigTests.kt
  firebase-config/src/androidTest/java/com/google/firebase/remoteconfig/FirebaseRemoteConfigIntegrationTest.java
  firebase-config/src/main/java/com/google/firebase/remoteconfig/FirebaseRemoteConfig.java
  firebase-config/src/main/java/com/google/firebase/remoteconfig/RemoteConfigComponent.java
  firebase-config/src/main/java/com/google/firebase/remoteconfig/RemoteConfigRegistrar.java
  firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigFetchHandler.java
  firebase-config/src/test/java/com/google/firebase/remoteconfig/FakeInstanceIdResult.java
  firebase-config/src/test/java/com/google/firebase/remoteconfig/FirebaseRemoteConfigTest.java
  firebase-config/src/test/java/com/google/firebase/remoteconfig/MockFirebaseInstallationsApiRegistrar.java
  firebase-config/src/test/java/com/google/firebase/remoteconfig/RemoteConfigComponentTest.java
  firebase-config/src/test/java/com/google/firebase/remoteconfig/internal/ConfigFetchHandlerTest.java
Labels: cla: yes, size/L

#1673 Use the javaversion constant instead of string.
  transport/transport-runtime/transport-runtime.gradle
Labels: cla: yes, size/XS

#892 Update android gradle plugin to 3.6.2 and gradle to 5.6.4
  apk-size/apk-size.gradle
  build.gradle
  buildSrc/build.gradle
  firebase-crashlytics-ndk/firebase-crashlytics-ndk.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: cla: yes, size/M

#1672 Unified emulator settings for Database
  firebase-common/src/androidTest/java/com/google/firebase/FirebaseAppTest.java
  firebase-common/src/main/java/com/google/firebase/FirebaseApp.java
  firebase-common/src/main/java/com/google/firebase/emulators/EmulatedServiceSettings.java
  firebase-common/src/main/java/com/google/firebase/emulators/EmulatorSettings.java
  firebase-common/src/main/java/com/google/firebase/emulators/FirebaseEmulator.java
  firebase-database/src/androidTest/java/com/google/firebase/database/FirebaseDatabaseTest.java
  firebase-database/src/main/java/com/google/firebase/database/FirebaseDatabase.java
  firebase-database/src/main/java/com/google/firebase/database/core/utilities/Utilities.java
  firebase-database/src/test/java/com/google/firebase/database/core/utilities/ParseUrlTest.java
Labels: api: core, api: database, cla: yes, size/L

#1685 Move `rawType` to `TypeToken`
  encoders/firebase-decoders-json/api.txt
  encoders/firebase-decoders-json/src/main/java/com/google/firebase/decoders/TypeToken.java
  encoders/firebase-decoders-json/src/test/java/com/google/firebase/decoders/TypeTokenTest.java
Labels: cla: yes, size/M

#1689 Temporarily change back to 3.4.2
  apk-size/apk-size.gradle
  build.gradle
  buildSrc/build.gradle
Labels: cla: yes, size/XS

#1687 Update NDK r17c installation instructions
  firebase-crashlytics-ndk/README.md
Labels: cla: yes, size/XS

#1691 Update Crashlytics changelogs and source versions
  firebase-crashlytics-ndk/CHANGELOG.md
  firebase-crashlytics-ndk/gradle.properties
  firebase-crashlytics/CHANGELOG.md
  firebase-crashlytics/gradle.properties
Labels: cla: yes, size/M

#1688 Functions unified emulator settings
  firebase-functions/src/androidTest/java/com/google/firebase/functions/CallTest.java
  firebase-functions/src/androidTest/java/com/google/firebase/functions/FirebaseFunctionsTest.java
  firebase-functions/src/main/java/com/google/firebase/functions/FirebaseFunctions.java
  firebase-functions/src/main/java/com/google/firebase/functions/FunctionsMultiResourceComponent.java
  firebase-functions/src/main/java/com/google/firebase/functions/FunctionsRegistrar.java
Labels: cla: yes, size/L

#1683 support decode array token
  encoders/firebase-decoders-json/src/json/java/com/google/firebase/decoders/json/CreationContextImpl.java
  encoders/firebase-decoders-json/src/json/java/com/google/firebase/decoders/json/JsonDataDecoderBuilderContext.java
  encoders/firebase-decoders-json/src/test/java/com/google/firebase/decoders/json/JsonDataDecoderBuilderContextTest.java
Labels: cla: yes, size/L

#1692 re-generate rtdb's api.txt and fail build if an error occurs parsing the file
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/apiinfo/ApiInformationTask.java
  firebase-database/api.txt
  firebase-database/src/main/java/com/google/firebase/database/FirebaseDatabase.java
Labels: cla: yes, needs-ok-to-test, size/S

#1699 chore(fiam + fiamd): re-generate api.txt files
  firebase-inappmessaging-display/api.txt
  firebase-inappmessaging/api.txt
Labels: cla: yes, ok-to-test, size/S

#1619 Move Preconditions check to FirebaseInstallations constructor.
  firebase-installations/src/main/java/com/google/firebase/installations/FirebaseInstallations.java
Labels: cla: yes, size/XS

#1534 Migrating to new protolite runtime
  build.gradle
  firebase-abt/firebase-abt.gradle
  firebase-config/bandwagoner/bandwagoner.gradle
  firebase-config/firebase-config.gradle
  firebase-crashlytics-ndk/firebase-crashlytics-ndk.gradle
  firebase-firestore/firebase-firestore.gradle
  firebase-firestore/ktx/ktx.gradle
  firebase-firestore/src/main/java/com/google/firebase/firestore/remote/GrpcCallProvider.java
  firebase-inappmessaging/firebase-inappmessaging.gradle
  protolite-well-known-types/README.md
  protolite-well-known-types/api.txt
  protolite-well-known-types/fix-javalite/proto/google/protobuf/duration.proto
  protolite-well-known-types/proguard-rules.pro
  protolite-well-known-types/protolite-well-known-types.gradle
  protolite-well-known-types/src/main/proto/google/protobuf/descriptor.proto
  tools/lint/lint.gradle
  transport/transport-backend-cct/transport-backend-cct.gradle
Labels: cla: yes, size/XXL

#1707 Revert "Move Preconditions check to FirebaseInstallations constructor."
  firebase-installations/src/main/java/com/google/firebase/installations/FirebaseInstallations.java
Labels: cla: yes, size/XS

#1705 Retry GoogleDataTransport Connection Errors
  transport/transport-backend-cct/src/main/java/com/google/android/datatransport/cct/CctTransportBackend.java
Labels: cla: yes, size/XS

#1708 Increase number of retries before deleting events
  transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/scheduling/persistence/SQLiteEventStore.java
Labels: cla: yes, size/XS

#1646 Send the FIS auth token in the RC fetch headers.
  firebase-config/ktx/src/test/kotlin/com/google/firebase/remoteconfig/ktx/RemoteConfigTests.kt
  firebase-config/src/androidTest/java/com/google/firebase/remoteconfig/FirebaseRemoteConfigIntegrationTest.java
  firebase-config/src/main/java/com/google/firebase/remoteconfig/RemoteConfigConstants.java
  firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigFetchHttpClient.java
  firebase-config/src/test/java/com/google/firebase/remoteconfig/FirebaseRemoteConfigTest.java
  firebase-config/src/test/java/com/google/firebase/remoteconfig/RemoteConfigComponentTest.java
  firebase-config/src/test/java/com/google/firebase/remoteconfig/internal/ConfigFetchHttpClientTest.java
Labels: cla: yes, size/L

#1690 Unified emulator settings for Firestore
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/AccessHelper.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/FirebaseFirestore.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/FirebaseFirestoreSettings.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/FirebaseFirestoreTest.java
Labels: cla: yes, size/L

#1706 Reset backoff when connectivity status changes
  firebase-firestore/CHANGELOG.md
  firebase-firestore/src/main/java/com/google/firebase/firestore/remote/RemoteStore.java
Labels: api: firestore, cla: yes, size/XS

#1712 Un-hide EmulatorSettings API
  firebase-common/api.txt
  firebase-common/gradle.properties
  firebase-common/src/main/java/com/google/firebase/FirebaseApp.java
  firebase-common/src/main/java/com/google/firebase/emulators/EmulatedServiceSettings.java
  firebase-common/src/main/java/com/google/firebase/emulators/EmulatorSettings.java
  firebase-common/src/main/java/com/google/firebase/emulators/FirebaseEmulator.java
  firebase-database/CHANGELOG.md
  firebase-database/api.txt
  firebase-database/gradle.properties
  firebase-database/src/main/java/com/google/firebase/database/FirebaseDatabase.java
  firebase-firestore/CHANGELOG.md
  firebase-firestore/api.txt
  firebase-firestore/gradle.properties
  firebase-firestore/src/main/java/com/google/firebase/firestore/FirebaseFirestore.java
  firebase-functions/api.txt
  firebase-functions/gradle.properties
  firebase-functions/src/main/java/com/google/firebase/functions/FirebaseFunctions.java
Labels: cla: yes, size/L

#1715 Adding descriptive error messaging for preconditions check.
  firebase-installations/src/main/java/com/google/firebase/installations/FirebaseInstallations.java
Labels: cla: yes, size/M

#1714 Fixing NPE and correcting corresponding annotations.
  firebase-installations/src/main/java/com/google/firebase/installations/FirebaseInstallations.java
  firebase-installations/src/main/java/com/google/firebase/installations/remote/FirebaseInstallationServiceClient.java
Labels: cla: yes, size/S

#1704 support inline decode
  encoders/firebase-decoders-json/api.txt
  encoders/firebase-decoders-json/src/json/java/com/google/firebase/decoders/json/JsonDataDecoderBuilderContext.java
  encoders/firebase-decoders-json/src/json/java/com/google/firebase/decoders/json/ObjectDecoderContextImpl.java
  encoders/firebase-decoders-json/src/main/java/com/google/firebase/decoders/ObjectDecoderContext.java
  encoders/firebase-decoders-json/src/test/java/com/google/firebase/decoders/json/JsonDataDecoderBuilderContextTest.java
Labels: cla: yes, size/M

#1723 Create dependabot.yaml
  .github/dependabot.yml
Labels: cla: yes, size/S

#1734 Update kotlin in buildsrc
  buildSrc/build.gradle
  firebase-dynamic-links/ktx/src/test/kotlin/com/google/firebase/dynamiclinks/ktx/DynamicLinksTests.kt
Labels: cla: yes, size/XS

#1620 docs(crashlytics-ktx): add crashlytics-ktx to FOSDC
  README.md
  docs/README.md
  docs/ktx/crashlytics.md
Labels: cla: yes, ok-to-test, size/M

#1719 Repack apk files into zip format to generate stable size measurements.
  apk-size/apk-size.gradle
  apk-size/app/configure.gradle
  ci/fireci/fireciplugins/binary_size.py
Labels: cla: yes, size/M

#1737 Revert "Un-hide EmulatorSettings API"
  firebase-common/api.txt
  firebase-common/gradle.properties
  firebase-common/src/main/java/com/google/firebase/FirebaseApp.java
  firebase-common/src/main/java/com/google/firebase/emulators/EmulatedServiceSettings.java
  firebase-common/src/main/java/com/google/firebase/emulators/EmulatorSettings.java
  firebase-common/src/main/java/com/google/firebase/emulators/FirebaseEmulator.java
  firebase-database/CHANGELOG.md
  firebase-database/api.txt
  firebase-database/gradle.properties
  firebase-database/src/main/java/com/google/firebase/database/FirebaseDatabase.java
  firebase-firestore/CHANGELOG.md
  firebase-firestore/api.txt
  firebase-firestore/gradle.properties
  firebase-firestore/src/main/java/com/google/firebase/firestore/FirebaseFirestore.java
  firebase-functions/api.txt
  firebase-functions/gradle.properties
  firebase-functions/src/main/java/com/google/firebase/functions/FirebaseFunctions.java
Labels: cla: yes, size/L
