Repository firebase/firebase-android-sdk, pull requests merged in 2020-09, with the labels that each got.

#1945 Clear setInManifest flag if data collection value is set by API
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/DataCollectionArbiter.java
Labels: cla: yes, size/XS

#1946 Also infer Database URL for default App
  firebase-database/src/main/java/com/google/firebase/database/FirebaseDatabase.java
Labels: api: database, cla: yes, size/XS

#1950 Fix auto-value codegen.
  encoders/firebase-encoders-processor/src/main/java/com/google/firebase/encoders/processor/EncodableProcessor.java
  encoders/firebase-encoders-processor/src/test/java/com/google/firebase/encoders/processor/EncodableProcessorTest.java
Labels: cla: yes, size/S

#1951 Read stdout of the process before waiting for it to complete.
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/ci/AffectedProjectFinder.java
Labels: cla: yes, size/S

#1947 Fix NotInFilter matching
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/QueryTest.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/NotInFilter.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/remote/RemoteSerializerTest.java
Labels: api: firestore, cla: yes, size/M

#1939 Update the README instructions to clarify the importance of pulling submodules
  README.md
Labels: cla: yes, size/XS

#1970 Adding Fireperf to Firehorn
  smoke-tests/build.gradle
  smoke-tests/src/main/java/com/google/firebase/testing/BuildOnlyTest.java
  smoke-tests/src/main/java/com/google/firebase/testing/PerformanceMonitoringTest.java
  smoke-tests/src/main/java/com/google/firebase/testing/TestSuite.java
Labels: cla: yes, size/M

#1974 Update Firestore README with new emulator command
  firebase-firestore/README.md
Labels: api: firestore, cla: yes, size/XS

#1979 Fix Crashlytics crash when using built in launcher icon
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CommonUtils.java
Labels: cla: yes, size/XS

#1972 Make the language reported via headers configurable
  firebase-firestore/src/main/java/com/google/firebase/firestore/FirebaseFirestore.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/remote/FirestoreChannel.java
Labels: cla: yes, size/M

#1980 Remove session ID tracking from session reporting coordinator.
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/SessionReportingCoordinatorTest.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsController.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsLifecycleEvents.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/SessionReportingCoordinator.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/persistence/CrashlyticsReportPersistence.java
Labels: cla: yes, size/L

#1975 Make != and NOT_in filters public
  firebase-firestore/CHANGELOG.md
  firebase-firestore/api.txt
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/QueryTest.java
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/ValidationTest.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/Query.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/FieldFilter.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/core/QueryTest.java
Labels: api: firestore, cla: yes, size/L

#1986 Fix Crashlytics Javadoc annotations
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/FirebaseCrashlytics.java
Labels: cla: yes, size/XS

#1983 Doc: s/Firebase Database/Realtime Database
  firebase-database/src/main/java/com/google/firebase/database/Logger.java
Labels: api: database, cla: yes

#1988 Clarifying why FIS SDK reads SHA1 hash.
  firebase-installations/src/main/java/com/google/firebase/installations/local/IidStore.java
Labels: cla: yes, size/XS

#1954 Adding ResponseHandler to implement backoff retry strageies based on response code.
  firebase-installations/src/main/java/com/google/firebase/installations/Utils.java
  firebase-installations/src/main/java/com/google/firebase/installations/remote/RequestLimiter.java
  firebase-installations/src/test/java/com/google/firebase/installations/remote/RequestLimiterTest.java
Labels: cla: yes, size/L

#1989 Call `setDoOutput(true)` on auth POSTs
  firebase-installations/src/main/java/com/google/firebase/installations/remote/FirebaseInstallationServiceClient.java
Labels: cla: yes, size/XS

#1991 Fix NotEquals tests to use deterministic document ordering
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/QueryTest.java
  firebase-firestore/src/testUtil/java/com/google/firebase/firestore/testutil/TestUtil.java
Labels: api: firestore, cla: yes, size/S

#1999 DynamicLinks documentation updates and simple code changes
  firebase-dynamic-links/src/main/java/com/google/firebase/dynamiclinks/DynamicLink.java
  firebase-dynamic-links/src/main/java/com/google/firebase/dynamiclinks/internal/FirebaseDynamicLinkRegistrar.java
  firebase-dynamic-links/src/main/java/com/google/firebase/dynamiclinks/internal/ShortDynamicLinkImpl.java
Labels: cla: yes, size/L

#2000 Import spec tests
  firebase-firestore/src/test/java/com/google/firebase/firestore/spec/SpecTestCase.java
  firebase-firestore/src/test/resources/json/listen_spec_test.json
  firebase-firestore/src/test/resources/json/offline_spec_test.json
  firebase-firestore/src/test/resources/json/write_spec_test.json
Labels: api: firestore, cla: yes

#2006 Floc master
  firebase-segmentation/firebase-segmentation.gradle
  firebase-segmentation/gradle.properties
Labels: cla: yes, size/XS

#2007 fix versions for release
  firebase-installations/gradle.properties
  firebase-messaging/gradle.properties
Labels: cla: yes, size/XS

#1333 Adding a TimeSource in Utils to easily inject and test the auth token expiration.
  firebase-installations/src/main/java/com/google/firebase/installations/FirebaseInstallations.java
  firebase-installations/src/main/java/com/google/firebase/installations/Utils.java
  firebase-installations/src/main/java/com/google/firebase/installations/time/Clock.java
  firebase-installations/src/main/java/com/google/firebase/installations/time/SystemClock.java
  firebase-installations/src/test/java/com/google/firebase/installations/FakeCalendar.java
  firebase-installations/src/test/java/com/google/firebase/installations/FakeClock.java
  firebase-installations/src/test/java/com/google/firebase/installations/FirebaseInstallationsTest.java
Labels: cla: yes, size/L

#2002 Minor fixes addressing previous comments during cl review
  firebase-installations/src/main/AndroidManifest.xml
  firebase-installations/src/main/java/com/google/firebase/installations/Utils.java
  firebase-installations/src/main/java/com/google/firebase/installations/remote/RequestLimiter.java
  firebase-installations/src/test/java/com/google/firebase/installations/remote/RequestLimiterTest.java
Labels: cla: yes, size/S

#2009 Send the GMP app ID along with user agent
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/remote/FirebaseClientGrpcMetadataProviderTest.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/FirestoreRegistrar.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/remote/FirebaseClientGrpcMetadataProvider.java
Labels: api: firestore, cla: yes, size/M

#2012 Always send the user agent regardless of the heartbeat value
  firebase-firestore/src/main/java/com/google/firebase/firestore/remote/FirebaseClientGrpcMetadataProvider.java
Labels: api: firestore, cla: yes, size/XS

#2018 Add a changelog entry for Firestore platform logging
  firebase-firestore/CHANGELOG.md
Labels: api: firestore, cla: yes, size/S

#2022 Update released versions.
  encoders/firebase-encoders-json/gradle.properties
  encoders/firebase-encoders/gradle.properties
  firebase-crashlytics-ndk/gradle.properties
  firebase-crashlytics/gradle.properties
  firebase-database/gradle.properties
  firebase-datatransport/gradle.properties
  firebase-functions/gradle.properties
  firebase-inappmessaging-display/gradle.properties
  firebase-inappmessaging/gradle.properties
  firebase-installations/gradle.properties
  firebase-messaging-directboot/gradle.properties
  firebase-messaging/gradle.properties
  firebase-storage/gradle.properties
  transport/transport-runtime/gradle.properties
Labels: cla: yes, size/M

#2024 Fix the heartbeat integration test in Firestore
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/remote/FirebaseClientGrpcMetadataProviderTest.java
Labels: cla: yes, size/XS

#2023 Add StrictModeRule for use by SDKs.
  firebase-common/firebase-common.gradle
  firebase-common/src/androidTest/java/com/google/firebase/StrictModeTest.java
  integ-testing/gradle.properties
  integ-testing/integ-testing.gradle
  integ-testing/src/main/AndroidManifest.xml
  integ-testing/src/main/java/com/google/firebase/testing/integ/MaybeThrowingCallable.java
  integ-testing/src/main/java/com/google/firebase/testing/integ/MaybeThrowingRunnable.java
  integ-testing/src/main/java/com/google/firebase/testing/integ/StrictModeRule.java
  subprojects.cfg
Labels: cla: yes, size/L

#2025 Fix remaining lint failures (mostly in tests)
  firebase-database/src/androidTest/java/com/google/firebase/database/IntegrationTestHelpers.java
  firebase-database/src/androidTest/java/com/google/firebase/database/snapshot/CompoundHashingIntegrationTest.java
  firebase-database/src/main/java/com/google/firebase/database/android/SqlPersistenceStorageEngine.java
  firebase-database/src/test/java/com/google/firebase/database/core/SyncPointTest.java
  firebase-database/src/test/java/com/google/firebase/database/core/persistence/RandomPersistenceTest.java
  firebase-database/src/testUtil/java/com/google/firebase/database/core/RandomOperationGenerator.java
  firebase-database/src/testUtil/java/com/google/firebase/database/core/persistence/MockPersistenceStorageEngine.java
Labels: api: database, cla: yes, size/L
