Repository firebase/firebase-android-sdk, pull requests merged in 2020-04, with the labels that each got.

#1404 Pre-gzip the crashlytics payloads before sending them up
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/BytesBackedNativeSessionFileTest.java
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/FileBackedNativeSessionFileTest.java
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/SessionReportingCoordinatorTest.java
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/TestUtils.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/BytesBackedNativeSessionFile.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/FileBackedNativeSessionFile.java
Labels: cla: yes, size/M

#1405 Revert FIS Integration for FIAM
  fiamui-app/fiamui-app.gradle
  firebase-inappmessaging-display/firebase-inappmessaging-display.gradle
  firebase-inappmessaging-display/src/main/java/com/google/firebase/inappmessaging/display/FirebaseInAppMessagingDisplay.java
  firebase-inappmessaging/firebase-inappmessaging.gradle
  firebase-inappmessaging/src/androidTest/java/com/google/firebase/inappmessaging/FirebaseInAppMessagingFlowableTest.java
  firebase-inappmessaging/src/androidTest/java/com/google/firebase/inappmessaging/TestApiClientModule.java
  firebase-inappmessaging/src/androidTest/java/com/google/firebase/inappmessaging/TestEngagementMetricsLoggerClientModule.java
  firebase-inappmessaging/src/main/java/com/google/firebase/inappmessaging/FirebaseInAppMessaging.java
  firebase-inappmessaging/src/main/java/com/google/firebase/inappmessaging/FirebaseInAppMessagingRegistrar.java
  firebase-inappmessaging/src/main/java/com/google/firebase/inappmessaging/internal/ApiClient.java
  firebase-inappmessaging/src/main/java/com/google/firebase/inappmessaging/internal/DataCollectionHelper.java
  firebase-inappmessaging/src/main/java/com/google/firebase/inappmessaging/internal/MetricsLoggerClient.java
  firebase-inappmessaging/src/main/java/com/google/firebase/inappmessaging/internal/injection/modules/ApiClientModule.java
  firebase-inappmessaging/src/main/java/com/google/firebase/inappmessaging/internal/injection/modules/TransportClientModule.java
  firebase-inappmessaging/src/test/java/com/google/firebase/inappmessaging/FirebaseInAppMessagingTest.java
  firebase-inappmessaging/src/test/java/com/google/firebase/inappmessaging/internal/ApiClientTest.java
  firebase-inappmessaging/src/test/java/com/google/firebase/inappmessaging/internal/DataCollectionHelperTest.java
  firebase-inappmessaging/src/test/java/com/google/firebase/inappmessaging/internal/DisplayCallbacksImplTest.java
  firebase-inappmessaging/src/test/java/com/google/firebase/inappmessaging/internal/MetricsLoggerClientTest.java
Labels: cla: yes, size/L

#1402 Remove impressions for Campaigns delivered by backend service
  firebase-inappmessaging/src/androidTest/java/com/google/firebase/inappmessaging/FirebaseInAppMessagingFlowableTest.java
  firebase-inappmessaging/src/main/java/com/google/firebase/inappmessaging/internal/ImpressionStorageClient.java
  firebase-inappmessaging/src/main/java/com/google/firebase/inappmessaging/internal/InAppMessageStreamManager.java
  firebase-inappmessaging/src/test/java/com/google/firebase/inappmessaging/internal/ImpressionStorageClientTest.java
  firebase-inappmessaging/src/test/java/com/google/firebase/inappmessaging/internal/InAppMessageStreamManagerTest.java
Labels: cla: yes, size/L

#1414 Remove impressions for Campaigns delivered by backend service
  firebase-inappmessaging/src/androidTest/java/com/google/firebase/inappmessaging/FirebaseInAppMessagingFlowableTest.java
  firebase-inappmessaging/src/main/java/com/google/firebase/inappmessaging/internal/ImpressionStorageClient.java
  firebase-inappmessaging/src/main/java/com/google/firebase/inappmessaging/internal/InAppMessageStreamManager.java
  firebase-inappmessaging/src/test/java/com/google/firebase/inappmessaging/internal/ImpressionStorageClientTest.java
  firebase-inappmessaging/src/test/java/com/google/firebase/inappmessaging/internal/InAppMessageStreamManagerTest.java
Labels: cla: yes, size/L

#1409 Support AGP 3.6+ in the iid compatibility check.
  firebase-installations/customer-lint-checks/customer-lint-checks.gradle
  firebase-installations/customer-lint-checks/src/main/java/com/google/firebase/installations/lint/Checks.kt
  firebase-installations/customer-lint-checks/src/main/java/com/google/firebase/installations/lint/IncompatibleIidVersionDetector.kt
  firebase-installations/customer-lint-checks/src/test/java/com/google/firebase/installations/lint/VersionTests.kt
Labels: cla: yes, size/L

#1411 Remove organization ID from DataTransport payloads
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/SessionReportingCoordinatorTest.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsController.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/SessionReportingCoordinator.java
Labels: cla: yes, size/M

#1415 DeferredValue changes for ServerValue.increment()
  firebase-database/src/androidTest/java/com/google/firebase/database/DataTest.java
  firebase-database/src/main/java/com/google/firebase/database/ServerValue.java
  firebase-database/src/main/java/com/google/firebase/database/core/Repo.java
  firebase-database/src/main/java/com/google/firebase/database/core/ServerValues.java
  firebase-database/src/main/java/com/google/firebase/database/core/SyncTree.java
  firebase-database/src/main/java/com/google/firebase/database/core/ValueProvider.java
  firebase-database/src/main/java/com/google/firebase/database/core/utilities/Utilities.java
Labels: api: database, cla: yes, size/L

#1417 Make ServerValue.increment() public
  firebase-database/CHANGELOG.md
  firebase-database/api.txt
  firebase-database/src/main/java/com/google/firebase/database/ServerValue.java
Labels: api: database, cla: yes

#1422 Only iterate across active targets in WatchChangeAggregator
  firebase-firestore/src/main/java/com/google/firebase/firestore/remote/WatchChangeAggregator.java
Labels: api: firestore, cla: yes, size/XS

#1423 Optimize output stream encoding.
  transport/transport-backend-cct/src/main/java/com/google/android/datatransport/cct/CctTransportBackend.java
  transport/transport-backend-cct/src/main/java/com/google/android/datatransport/cct/internal/LogResponse.java
  transport/transport-backend-cct/transport-backend-cct.gradle
Labels: cla: yes, size/L

#1400 Firebase Segmentation SDK switches to depend on FIS, from depending on IID
  firebase-segmentation/firebase-segmentation.gradle
  firebase-segmentation/gradle.properties
  firebase-segmentation/src/main/java/com/google/firebase/segmentation/FirebaseSegmentation.java
  firebase-segmentation/src/main/java/com/google/firebase/segmentation/FirebaseSegmentationRegistrar.java
  firebase-segmentation/src/test/java/com/google/firebase/segmentation/FirebaseSegmentationTest.java
Labels: cla: yes, size/L

#1425 Update and improved instructions to fix API restrictions problem for FIS
  firebase-installations/API_KEY_RESTRICTIONS.md
Labels: cla: yes, size/S

#1374 Implement limbo resolution listen throttling.
  firebase-firestore/CHANGELOG.md
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/FirestoreClient.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/SyncEngine.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/spec/SpecTestCase.java
  firebase-firestore/src/test/resources/json/limbo_spec_test.json
Labels: api: firestore, cla: yes, size/L

#1345 Improving FISServiceClient by closing all acquired connection resources
  firebase-installations/src/main/java/com/google/firebase/installations/remote/FirebaseInstallationServiceClient.java
Labels: cla: yes, size/L

#1427 Migrate transport backend to auto @Encodable codegen.
  transport/transport-backend-cct/src/main/java/com/google/android/datatransport/cct/CctTransportBackend.java
  transport/transport-backend-cct/src/main/java/com/google/android/datatransport/cct/internal/AndroidClientInfo.java
  transport/transport-backend-cct/src/main/java/com/google/android/datatransport/cct/internal/AndroidClientInfoEncoder.java
  transport/transport-backend-cct/src/main/java/com/google/android/datatransport/cct/internal/BatchedLogRequest.java
  transport/transport-backend-cct/src/main/java/com/google/android/datatransport/cct/internal/BatchedLogRequestEncoder.java
  transport/transport-backend-cct/src/main/java/com/google/android/datatransport/cct/internal/ClientInfoEncoder.java
  transport/transport-backend-cct/src/main/java/com/google/android/datatransport/cct/internal/JsonBatchedLogRequestEncoder.java
  transport/transport-backend-cct/src/main/java/com/google/android/datatransport/cct/internal/LogEvent.java
  transport/transport-backend-cct/src/main/java/com/google/android/datatransport/cct/internal/LogEventEncoder.java
  transport/transport-backend-cct/src/main/java/com/google/android/datatransport/cct/internal/LogRequest.java
  transport/transport-backend-cct/src/main/java/com/google/android/datatransport/cct/internal/LogRequestEncoder.java
  transport/transport-backend-cct/src/main/java/com/google/android/datatransport/cct/internal/NetworkConnectionInfoEncoder.java
  transport/transport-backend-cct/src/test/java/com/google/android/datatransport/cct/internal/LogRequestTest.java
  transport/transport-backend-cct/transport-backend-cct.gradle
Labels: cla: yes, size/L

#1424 Firebase Data Collection:- Add tri states to the data collection api
  firebase-common/data-collection-tests/data-collection-tests.gradle
  firebase-common/data-collection-tests/src/test/java/com/google/firebase/DataCollectionPostNDefaultDisabledTest.java
  firebase-common/data-collection-tests/src/test/java/com/google/firebase/DataCollectionPreNDefaultDisabledTest.java
  firebase-common/data-collection-tests/src/test/java/com/google/firebase/DataCollectionTestUtil.java
  firebase-common/src/androidTest/java/com/google/firebase/FirebaseAppTest.java
  firebase-common/src/main/java/com/google/firebase/FirebaseApp.java
  firebase-common/src/main/java/com/google/firebase/internal/DataCollectionConfigStorage.java
  firebase-common/src/test/java/com/google/firebase/DataCollectionPostNDefaultEnabledTest.java
  firebase-common/src/test/java/com/google/firebase/DataCollectionPreNDefaultEnabledTest.java
  firebase-common/src/test/java/com/google/firebase/DataCollectionTestUtil.java
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/CrashlyticsControllerTest.java
Labels: cla: yes, size/L

#1444 Fix flaky transaction tests
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/TransactionTest.java
Labels: api: firestore, cla: yes, size/XS

#1438 Remove a hard assert that no longer holds due to mirror queries.
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/SyncEngine.java
Labels: api: firestore, cla: yes, size/XS

#1446 Bump crashlytics to use the latest version of IID
  firebase-crashlytics/firebase-crashlytics.gradle
Labels: cla: yes, size/XS

#1443 Logging error response from FIS servers
  firebase-installations/src/main/java/com/google/firebase/installations/remote/FirebaseInstallationServiceClient.java
Labels: cla: yes, size/M

#1448 Update source changelogs and versions for Crashlytics
  firebase-crashlytics-ndk/CHANGELOG.md
  firebase-crashlytics-ndk/gradle.properties
  firebase-crashlytics/CHANGELOG.md
  firebase-crashlytics/gradle.properties
Labels: cla: yes, size/M

#1445 Bump IID SDK version to 20.1.5 in RC SDK.
  firebase-config/bandwagoner/bandwagoner.gradle
  firebase-config/firebase-config.gradle
  firebase-config/ktx/ktx.gradle
Labels: cla: yes, size/S

#1450 Created REQUIRED_FIREBASE_OPTIONS_ANDROID.md
  firebase-installations/REQUIRED_FIREBASE_OPTIONS_ANDROID.md
Labels: cla: yes, size/M

#1435 Expanding preconditions checks description to help 3p developers
  firebase-installations/src/main/java/com/google/firebase/installations/FirebaseInstallations.java
Labels: cla: yes, size/S

#1455 Update FIS SDK version
  firebase-installations/gradle.properties
Labels: cla: yes, size/XS

#1459 Add precondition format checks for AppId and API Key
  firebase-installations/src/main/java/com/google/firebase/installations/FirebaseInstallations.java
  firebase-installations/src/main/java/com/google/firebase/installations/Utils.java
  firebase-installations/src/test/java/com/google/firebase/installations/FirebaseInstallationsTest.java
Labels: cla: yes, size/M

#1431 Add large payload support to datatransport.
  transport/transport-runtime/src/androidTest/java/com/google/android/datatransport/runtime/scheduling/persistence/SQLiteEventStoreTest.java
  transport/transport-runtime/src/androidTest/java/com/google/android/datatransport/runtime/scheduling/persistence/SpyEventStoreModule.java
  transport/transport-runtime/src/androidTest/java/com/google/android/datatransport/runtime/scheduling/persistence/TestEventStoreModule.java
  transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/scheduling/persistence/EventStoreConfig.java
  transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/scheduling/persistence/EventStoreModule.java
  transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/scheduling/persistence/SQLiteEventStore.java
  transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/scheduling/persistence/SchemaManager.java
  transport/transport-runtime/src/test/java/com/google/android/datatransport/runtime/scheduling/persistence/SchemaManagerTest.java
  transport/transport-runtime/transport-runtime.gradle
Labels: cla: yes, size/L

#1439 Remove hard limit on Crashlytics payload size
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/send/DataTransportCrashlyticsReportSenderTest.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/send/DataTransportCrashlyticsReportSender.java
Labels: cla: yes, size/M

#1458 Removing try-with-resources
  firebase-installations/src/main/java/com/google/firebase/installations/FirebaseInstallations.java
  firebase-installations/src/main/java/com/google/firebase/installations/Utils.java
  firebase-installations/src/main/java/com/google/firebase/installations/remote/FirebaseInstallationServiceClient.java
  firebase-installations/src/test/java/com/google/firebase/installations/FirebaseInstallationsTest.java
Labels: cla: yes, size/M

#1463 add a comment on regex import
  firebase-installations/src/main/java/com/google/firebase/installations/Utils.java
Labels: cla: yes, size/XS

#1464 rollback format checks for AppId and ApiKey, which will be added back…
  firebase-installations/src/main/java/com/google/firebase/installations/FirebaseInstallations.java
  firebase-installations/src/main/java/com/google/firebase/installations/Utils.java
  firebase-installations/src/test/java/com/google/firebase/installations/FirebaseInstallationsTest.java
Labels: cla: yes, size/M

#1442 Keep CHANGELOG.md in update-to-date.
  firebase-firestore/CHANGELOG.md
Labels: api: firestore, cla: yes, size/S

#1467 Formatting installations test
  firebase-installations/src/test/java/com/google/firebase/installations/FirebaseInstallationsTest.java
Labels: cla: yes, size/XS

#1461 Enable errorprone only by request.
  README.md
  build.gradle
  firebase-abt/src/main/java/com/google/firebase/abt/FirebaseABTesting.java
  firebase-config/src/main/java/com/google/firebase/remoteconfig/RemoteConfigConstants.java
  gradle/errorProne.gradle
Labels: cla: yes, size/L

#1426 Add new version of setAutomaticDataCollectionEnabled api
  firebase-inappmessaging/api.txt
  firebase-inappmessaging/gradle.properties
  firebase-inappmessaging/src/main/java/com/google/firebase/inappmessaging/FirebaseInAppMessaging.java
  firebase-inappmessaging/src/main/java/com/google/firebase/inappmessaging/internal/DataCollectionHelper.java
  firebase-inappmessaging/src/main/java/com/google/firebase/inappmessaging/internal/SharedPreferencesUtils.java
  firebase-inappmessaging/src/test/java/com/google/firebase/inappmessaging/FirebaseInAppMessagingTest.java
  firebase-inappmessaging/src/test/java/com/google/firebase/inappmessaging/internal/DataCollectionHelperTest.java
  firebase-inappmessaging/src/test/java/com/google/firebase/inappmessaging/internal/SharedPreferencesUtilsTest.java
Labels: cla: yes, size/L

#1486 Datatransport failures should not crash the app.
  transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/ExecutionModule.java
  transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/SafeLoggingExecutor.java
  transport/transport-runtime/src/test/java/com/google/android/datatransport/runtime/SafeLoggingExecutorTest.java
Labels: cla: yes, size/M

#1480 Rewrite code for binary size collection.
  apk-size/apk-size.gradle
  apk-size/app/build.gradle
  apk-size/app/configure.gradle
  apk-size/app/default.gradle
  apk-size/app/proguard-rules-aggressive.pro
  apk-size/app/src/base/base.gradle
  apk-size/app/src/main/AndroidManifest.xml
  apk-size/app/src/main/java/com.google.apksize/MainActivity.java
  apk-size/app/src/main/res/layout/activity_main.xml
  apk-size/app/src/main/res/mipmap-hdpi/ic_launcher.png
  apk-size/app/src/main/res/values/colors.xml
  apk-size/app/src/main/res/values/dimens.xml
  apk-size/app/src/main/res/values/strings.xml
  apk-size/app/src/main/res/values/styles.xml
  apk-size/app/src/main/res/xml/remote_config_defaults.xml
  apk-size/settings.gradle
  build.gradle
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/ci/CheckCoveragePlugin.groovy
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/measurement/MetricsReportUploader.java
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/measurement/MetricsServiceApi.java
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/measurement/TestLogFinder.java
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/measurement/UploadMeasurementsTask.groovy
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/measurement/aarsize/AarSizeJsonBuilder.groovy
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/measurement/aarsize/AarSizeTableBuilder.groovy
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/measurement/aarsize/GenerateMeasurementsTask.groovy
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/measurement/apksize/ApkSizeJsonBuilder.groovy
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/measurement/apksize/ApkSizeTableBuilder.groovy
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/measurement/apksize/GenerateMeasurementsTask.groovy
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/measurement/apksize/GenerateVariantPlugin.groovy
  ci/fireci/fireci/gradle.py
  ci/fireci/fireci/prow_utils.py
  ci/fireci/fireci/uploader.py
  ci/fireci/fireciplugins/binary_size.py
  ci/fireci/fireciplugins/coverage.py
  ci/fireci/tests/gradle_test.py
  codecov.yml
  gradle.properties
  subprojects.cfg
  tools/measurement/apksize/README.md
  tools/measurement/apksize/apksize.gradle
  tools/measurement/apksize/debug.keystore
  tools/measurement/apksize/sdks.csv
Labels: cla: yes, size/XXL

#1470 Added precondition format checks for App-Id and Api-Key
  firebase-installations/src/main/java/com/google/firebase/installations/FirebaseInstallations.java
  firebase-installations/src/main/java/com/google/firebase/installations/Utils.java
Labels: cla: yes, size/S

#1491 Clean up FIAM async flow
  firebase-inappmessaging/src/main/java/com/google/firebase/inappmessaging/internal/InAppMessageStreamManager.java
Labels: cla: yes, size/XS

#1492 Fix JavaDoc for Increment
  firebase-database/src/main/java/com/google/firebase/database/ServerValue.java
Labels: api: firestore, cla: yes

#1496 Update FIAM Transport name
  firebase-inappmessaging/src/main/java/com/google/firebase/inappmessaging/internal/injection/modules/TransportClientModule.java
Labels: cla: yes, size/XS

#1497 Crash licenses
  firebase-crashlytics/firebase-crashlytics.gradle
  firebase-crashlytics/third_party_licenses/protocol_buffers/LICENSE
  firebase-crashlytics/third_party_licenses/tape/LICENSE
Labels: cla: yes, size/L

#1209 Fix ClassNotFoundException for com.google.firebase.remoteconfig.ktx.…
  firebase-config/ktx/src/main/AndroidManifest.xml
Labels: cla: yes, ok-to-test, size/XS

#1502 Add tests for FIS format check
  firebase-installations/src/test/java/com/google/firebase/installations/FirebaseInstallationsTest.java
Labels: cla: yes, size/M

#1495 Add clarifying javadoc to FirebaseCrashlytics#setCrashlyticsCollectionEnabled
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/FirebaseCrashlytics.java
Labels: cla: yes, size/XS

#1498 Port ComponentProvider
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/ComponentProvider.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/FirestoreClient.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/MemoryComponentProvider.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/SQLiteComponentProvider.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/GarbageCollectionScheduler.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/LruGarbageCollector.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/PersistenceTestHelpers.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/remote/MockDatastore.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/spec/MemorySpecTest.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/spec/SQLiteSpecTest.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/spec/SpecTestCase.java
Labels: api: firestore, cla: yes, size/XL

#1507 Move FIS precondition format check to installation constructor
  firebase-installations/src/main/java/com/google/firebase/installations/FirebaseInstallations.java
Labels: cla: yes, size/S

#1511 fix googleJavaFormat
  firebase-database/src/main/java/com/google/firebase/database/ServerValue.java
Labels: cla: yes, size/XS

#1510 Migrate build logic to java.
  .gitignore
  build.gradle
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/FirebaseLibraryExtension.java
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/FirebaseLibraryPlugin.java
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/LibraryType.java
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/ci/AffectedProjectFinder.groovy
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/ci/AffectedProjectFinder.java
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/ci/CheckCoveragePlugin.groovy
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/ci/ContinuousIntegrationExtension.java
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/ci/ContinuousIntegrationPlugin.groovy
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/ci/ContinuousIntegrationPlugin.java
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/ci/Coverage.java
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/ci/Environment.groovy
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/ci/Environment.java
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/ci/device/FirebaseTestServer.groovy
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/ci/device/FirebaseTestServer.java
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/license/GenerateLicensesTask.java
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/publish/Mode.java
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/publish/Publisher.groovy
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/publish/Publisher.java
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/publish/PublishingPlugin.groovy
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/publish/PublishingPlugin.java
  buildSrc/src/test/groovy/com/google/firebase/gradle/plugins/publish/PublishingPluginSpec.groovy
Labels: cla: yes, size/XXL

#1501 Add missing test to RemoteConfig KTX
  firebase-config/ktx/src/test/kotlin/com/google/firebase/remoteconfig/ktx/RemoteConfigTests.kt
Labels: cla: yes, size/S

#1513 Reverting java refactor
  .gitignore
  build.gradle
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/FirebaseLibraryExtension.java
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/FirebaseLibraryPlugin.java
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/LibraryType.java
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/ci/AffectedProjectFinder.groovy
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/ci/AffectedProjectFinder.java
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/ci/CheckCoveragePlugin.groovy
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/ci/ContinuousIntegrationExtension.groovy
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/ci/ContinuousIntegrationExtension.java
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/ci/ContinuousIntegrationPlugin.groovy
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/ci/ContinuousIntegrationPlugin.java
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/ci/Coverage.java
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/ci/Environment.groovy
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/ci/Environment.java
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/ci/device/FirebaseTestServer.groovy
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/ci/device/FirebaseTestServer.java
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/license/GenerateLicensesTask.java
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/publish/Publisher.groovy
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/publish/Publisher.java
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/publish/PublishingPlugin.groovy
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/publish/PublishingPlugin.java
  buildSrc/src/test/groovy/com/google/firebase/gradle/plugins/publish/PublishingPluginSpec.groovy
Labels: cla: yes, size/XXL

#1516 Migrate build logic to Java
  .gitignore
  build.gradle
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/FirebaseLibraryExtension.java
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/FirebaseLibraryPlugin.java
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/LibraryType.java
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/ci/AffectedProjectFinder.groovy
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/ci/AffectedProjectFinder.java
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/ci/CheckCoveragePlugin.groovy
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/ci/ContinuousIntegrationExtension.java
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/ci/ContinuousIntegrationPlugin.groovy
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/ci/ContinuousIntegrationPlugin.java
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/ci/Coverage.java
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/ci/Environment.groovy
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/ci/Environment.java
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/ci/device/FirebaseTestServer.groovy
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/ci/device/FirebaseTestServer.java
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/license/GenerateLicensesTask.java
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/publish/Mode.java
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/publish/Publisher.groovy
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/publish/Publisher.java
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/publish/PublishingPlugin.groovy
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/publish/PublishingPlugin.java
  buildSrc/src/test/groovy/com/google/firebase/gradle/plugins/publish/PublishingPluginSpec.groovy
Labels: cla: yes, size/XXL

#1465 feat(database-ktx): add reified function getValue() to MutableData
  docs/ktx/database.md
  firebase-database/ktx/api.txt
  firebase-database/ktx/src/main/kotlin/com/google/firebase/database/ktx/Database.kt
  firebase-database/ktx/src/test/kotlin/com/google/firebase/database/DataSnapshotUtil.kt
  firebase-database/ktx/src/test/kotlin/com/google/firebase/database/ktx/DatabaseTests.kt
Labels: cla: yes, ok-to-test, size/M

#1517 Use correct commit hashes when uploading metric reports.
  ci/fireci/fireci/uploader.py
Labels: cla: yes, size/S
