Repository firebase/firebase-android-sdk, pull requests merged in 2020-03, with the labels that each got.

#1297 Fix package name in Crashlytics NDK manifest
  firebase-crashlytics-ndk/src/main/AndroidManifest.xml
  firebase-crashlytics-ndk/src/main/java/com/google/firebase/crashlytics/ndk/CrashlyticsNdkRegistrar.java
Labels: cla: yes, size/XS

#1265 Crashlytics update Update endpoint from api. => update.
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/settings/SettingsJsonParserTest.java
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/settings/SettingsV3JsonTransformTest.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/settings/SettingsV3JsonTransform.java
Labels: cla: yes, size/S

#1296 Connect reporting coordinator to controller
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/core/CrashlyticsControllerTest.java
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/core/CrashlyticsCoreTest.java
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/SessionReportingCoordinatorTest.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/core/CrashlyticsController.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/SessionReportingCoordinator.java
Labels: cla: yes, size/L

#1301 Catching NPE and throwing IOE instead.
  firebase-installations/src/main/java/com/google/firebase/installations/remote/FirebaseInstallationServiceClient.java
Labels: cla: yes, size/S

#1300 Add a limit to the number of currently open sessions
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/persistence/CrashlyticsReportPersistenceTest.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/SessionReportingCoordinator.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/persistence/CrashlyticsReportPersistence.java
Labels: cla: yes, size/L

#1303 Removed erroneous line (missing semicolon).
  firebase-installations/src/main/java/com/google/firebase/installations/remote/FirebaseInstallationServiceClient.java
Labels: cla: yes, size/XS

#1306 Update Crashlytics SDK version for next release
  firebase-crashlytics/gradle.properties
Labels: cla: yes, size/XS

#1307 Fix formatting for FIS NPE changes
  firebase-installations/src/main/java/com/google/firebase/installations/remote/FirebaseInstallationServiceClient.java
Labels: cla: yes, size/S

#1309 Remove file create in coordinator constructor
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/core/CrashlyticsControllerTest.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/SessionReportingCoordinator.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/persistence/FileStore.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/persistence/FileStoreImpl.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/send/DataTransportCrashlyticsReportSender.java
Labels: cla: yes, size/S

#1308 check for all allowable iidtoken scopes, not just *
  firebase-installations/src/main/java/com/google/firebase/installations/local/IidStore.java
  firebase-installations/src/test/java/com/google/firebase/installations/FirebaseInstallationsTest.java
Labels: cla: yes, size/L

#1310 Crashlytics Analytics Connector realtime fixes
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/core/CrashlyticsControllerTest.java
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/analytics/AnalyticsConnectorReceiverTest.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/core/CrashlyticsController.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/core/CrashlyticsCore.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/analytics/AnalyticsConnectorReceiver.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/analytics/AnalyticsReceiver.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/analytics/package-info.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/breadcrumbs/BreadcrumbsReceiver.java
Labels: cla: yes, size/L

#1317 Update latest released versions
  firebase-config/gradle.properties
  firebase-database-collection/gradle.properties
  firebase-database/gradle.properties
  firebase-dynamic-links/gradle.properties
  firebase-firestore/gradle.properties
  firebase-functions/gradle.properties
  firebase-installations-interop/gradle.properties
  firebase-installations/gradle.properties
  firebase-storage/gradle.properties
Labels: cla: yes, size/M

#1322 Make Logging consistent across Crashlytics
  firebase-crashlytics-ndk/src/main/java/com/google/firebase/crashlytics/ndk/BreakpadController.java
  firebase-crashlytics-ndk/src/main/java/com/google/firebase/crashlytics/ndk/FirebaseCrashlyticsNdk.java
  firebase-crashlytics-ndk/src/main/java/com/google/firebase/crashlytics/ndk/JniNativeApi.java
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/settings/network/DefaultSettingsSpiCallTest.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/FirebaseCrashlytics.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/core/CrashlyticsController.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/core/CrashlyticsCore.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/core/CrashlyticsFileMarker.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/core/CrashlyticsUncaughtExceptionHandler.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/core/MetaDataStore.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/core/UserMetadata.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/Logger.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/Onboarding.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/analytics/AnalyticsConnectorReceiver.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CommonUtils.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/DataCollectionArbiter.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/ExecutorUtils.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/IdManager.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/SessionReportingCoordinator.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/log/LogFileManager.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/log/QueueFileLogStore.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/ndk/BinaryImagesConverter.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/ndk/ProcMapEntryParser.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/persistence/FileStoreImpl.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/proto/SessionProtobufHelper.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/report/ReportManager.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/report/ReportUploader.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/report/model/NativeSessionReport.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/report/model/SessionReport.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/report/network/DefaultCreateReportSpiCall.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/report/network/NativeCreateReportSpiCall.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/settings/CachedSettingsIo.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/settings/SettingsController.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/settings/network/AbstractAppSpiCall.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/settings/network/DefaultSettingsSpiCall.java
Labels: cla: yes, size/L

#1318 Add session settings to the persistence layer
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/core/CrashlyticsControllerTest.java
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/persistence/CrashlyticsReportPersistenceTest.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/core/CrashlyticsController.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/core/CrashlyticsCore.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/SessionReportingCoordinator.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/persistence/CrashlyticsReportPersistence.java
Labels: cla: yes, size/L

#1323 Simplify finalizing native reports
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/core/CrashlyticsControllerTest.java
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/core/CrashlyticsCoreTest.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/core/CrashlyticsController.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/core/CrashlyticsCore.java
Labels: cla: yes, size/M

#1327 Add missing latestReleasedVersion property.
  firebase-installations-interop/gradle.properties
  firebase-installations/gradle.properties
Labels: cla: yes, size/XS

#1330 Rename root-project.gradle to build.gradle
  .gitignore
  build.gradle
  gradle/projectSettings.gradle
Labels: cla: yes, size/XS

#1335 Change firebase encoders dep to implementation
  firebase-crashlytics/firebase-crashlytics.gradle
Labels: cla: yes, size/XS

#1331 Add missing package-info to firebase-crashlytics.
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/model/serialization/package-info.java
Labels: cla: yes, size/S

#1336 Consolidate remaining 'core' classes into 'internal/common'
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/core/CommonUtilsTest.java
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/core/TestUtils.java
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/CLSUUIDTest.java
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/CommonUtilsTest.java
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/CrashlyticsControllerTest.java
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/CrashlyticsCoreInitializationTest.java
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/CrashlyticsCoreTest.java
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/MetaDataStoreTest.java
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/SameThreadExecutorService.java
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/SessionReportingCoordinatorTest.java
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/TestNativeReportFilesProvider.java
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/TestReportFilesProvider.java
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/TestUtils.java
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/report/ReportManagerTest.java
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/report/ReportUploaderTest.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/FirebaseCrashlytics.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/Onboarding.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/AbstractSpiCall.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/AppData.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/BatteryState.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CLSUUID.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsBackgroundWorker.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsController.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsCore.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsFileMarker.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsUncaughtExceptionHandler.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/DataCollectionArbiter.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/MetaDataStore.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/SessionReportingCoordinator.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/UserMetadata.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/Utils.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/log/QueueFile.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/log/QueueFileLogStore.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/report/network/NativeCreateReportSpiCall.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/settings/network/DefaultSettingsSpiCall.java
  firebase-crashlytics/src/test/java/com/google/firebase/crashlytics/internal/common/UtilsTest.java
Labels: cla: yes, size/L

#1332 Integrate FIS into FIAM Headless
  firebase-inappmessaging/firebase-inappmessaging.gradle
  firebase-inappmessaging/src/androidTest/java/com/google/firebase/inappmessaging/FirebaseInAppMessagingFlowableTest.java
  firebase-inappmessaging/src/androidTest/java/com/google/firebase/inappmessaging/TestApiClientModule.java
  firebase-inappmessaging/src/androidTest/java/com/google/firebase/inappmessaging/TestEngagementMetricsLoggerClientModule.java
  firebase-inappmessaging/src/main/java/com/google/firebase/inappmessaging/FirebaseInAppMessaging.java
  firebase-inappmessaging/src/main/java/com/google/firebase/inappmessaging/FirebaseInAppMessagingRegistrar.java
  firebase-inappmessaging/src/main/java/com/google/firebase/inappmessaging/internal/AbtIntegrationHelper.java
  firebase-inappmessaging/src/main/java/com/google/firebase/inappmessaging/internal/ApiClient.java
  firebase-inappmessaging/src/main/java/com/google/firebase/inappmessaging/internal/DataCollectionHelper.java
  firebase-inappmessaging/src/main/java/com/google/firebase/inappmessaging/internal/MetricsLoggerClient.java
  firebase-inappmessaging/src/main/java/com/google/firebase/inappmessaging/internal/injection/components/AppComponent.java
  firebase-inappmessaging/src/main/java/com/google/firebase/inappmessaging/internal/injection/modules/AbTestingModule.java
  firebase-inappmessaging/src/main/java/com/google/firebase/inappmessaging/internal/injection/modules/ApiClientModule.java
  firebase-inappmessaging/src/main/java/com/google/firebase/inappmessaging/internal/injection/modules/TransportClientModule.java
  firebase-inappmessaging/src/test/java/com/google/firebase/inappmessaging/FirebaseInAppMessagingTest.java
  firebase-inappmessaging/src/test/java/com/google/firebase/inappmessaging/internal/AbtIntegrationHelperTest.java
  firebase-inappmessaging/src/test/java/com/google/firebase/inappmessaging/internal/ApiClientTest.java
  firebase-inappmessaging/src/test/java/com/google/firebase/inappmessaging/internal/DataCollectionHelperTest.java
  firebase-inappmessaging/src/test/java/com/google/firebase/inappmessaging/internal/DisplayCallbacksImplTest.java
  firebase-inappmessaging/src/test/java/com/google/firebase/inappmessaging/internal/MetricsLoggerClientTest.java
Labels: cla: yes, size/XL

#1340 Update to latest dokka and enable javadoc for all ktx libs.
  buildSrc/build.gradle
  firebase-config/ktx/ktx.gradle
  firebase-database/ktx/ktx.gradle
  firebase-dynamic-links/ktx/ktx.gradle
  firebase-functions/ktx/ktx.gradle
  firebase-inappmessaging-display/ktx/ktx.gradle
  firebase-inappmessaging/ktx/ktx.gradle
  firebase-storage/ktx/ktx.gradle
Labels: cla: yes, size/S

#1319 Make binary size report format compatible with the metrics service.
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/ci/CheckCoveragePlugin.groovy
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/measurement/MetricsReportUploader.java
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/measurement/MetricsServiceApi.java
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/measurement/TestLogFinder.java
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/measurement/aarsize/AarSizeJsonBuilder.groovy
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/measurement/aarsize/GenerateMeasurementsTask.groovy
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/measurement/apksize/ApkSizeJsonBuilder.groovy
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/measurement/apksize/GenerateMeasurementsTask.groovy
  buildSrc/src/test/groovy/com/google/firebase/gradle/plugins/measurement/apksize/ApkSizeJsonBuilderTest.groovy
  buildSrc/src/test/groovy/com/google/firebase/gradle/plugins/measurement/apksize/ApkSizeTableBuilderTest.groovy
  buildSrc/src/test/groovy/com/google/firebase/gradle/plugins/measurement/apksize/ApkSizeTestProject.groovy
  buildSrc/src/test/groovy/com/google/firebase/gradle/plugins/measurement/apksize/GenerateMeasurementsTaskTest.groovy
  tools/measurement/apksize/apksize.gradle
Labels: cla: yes, size/XL

#1338 Annotate FirebaseInstalaltionsApi class
  firebase-installations-interop/src/main/java/com/google/firebase/installations/FirebaseInstallationsApi.java
Labels: cla: yes, size/S

#1342 Remove commented out / unused code in FIAM tests
  firebase-inappmessaging/src/test/java/com/google/firebase/inappmessaging/internal/DisplayCallbacksImplTest.java
Labels: cla: yes, size/XS

#1344 Added latestReleasedVersion in firebase-encoders-json.
  encoders/firebase-encoders-json/gradle.properties
Labels: cla: yes, size/XS

#1346 Prototype a lint check for fis.
  firebase-installations/customer-lint-checks/customer-lint-checks.gradle
  firebase-installations/customer-lint-checks/src/main/java/com/google/firebase/installations/lint/Checks.kt
  firebase-installations/customer-lint-checks/src/main/java/com/google/firebase/installations/lint/IncompatibleIidVersionDetector.kt
  firebase-installations/firebase-installations.gradle
  subprojects.cfg
Labels: cla: yes, size/L

#1353 C++ API for Crashlytics NDK
  firebase-crashlytics-ndk/src/main/jni/libcrashlytics/Android.mk
  firebase-crashlytics-ndk/src/main/jni/libcrashlytics/include/crashlytics/external/crashlytics.h
  firebase-crashlytics-ndk/src/main/jni/libcrashlytics/src/external/api_c.c
Labels: cla: yes, size/L

#1347 Lint jar for IID Version incompatabiltiy
  firebase-installations/customer-lint-checks/customer-lint-checks.gradle
  firebase-installations/customer-lint-checks/src/main/java/com/google/firebase/installations/lint/IncompatibleIidVersionDetector.kt
Labels: cla: yes, size/M

#1337 Remove IID from FIAM Display Dependencies
  firebase-inappmessaging-display/firebase-inappmessaging-display.gradle
  firebase-inappmessaging-display/src/main/java/com/google/firebase/inappmessaging/display/FirebaseInAppMessagingDisplay.java
  firebase-inappmessaging/firebase-inappmessaging.gradle
Labels: cla: yes, size/S

#1355 Moving FIS network calls onto a separate executor
  firebase-installations/gradle.properties
  firebase-installations/src/main/java/com/google/firebase/installations/FirebaseInstallations.java
Labels: cla: yes, size/M

#1358 Add session end fields to Crashlytics reports
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/SessionReportingCoordinatorTest.java
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/model/serialization/CrashlyticsReportJsonTransformTest.java
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/persistence/CrashlyticsReportPersistenceTest.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsController.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/SessionReportingCoordinator.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/model/CrashlyticsReport.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/model/serialization/CrashlyticsReportJsonTransform.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/persistence/CrashlyticsReportPersistence.java
  firebase-crashlytics/src/test/java/com/google/firebase/crashlytics/internal/model/CrashlyticsReportTest.java
Labels: cla: yes, size/L

#1361 Add 'generator type' to CrashlyticsReport
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/model/serialization/CrashlyticsReportJsonTransformTest.java
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/persistence/CrashlyticsReportPersistenceTest.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsReportDataCapture.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/model/CrashlyticsReport.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/model/serialization/CrashlyticsReportJsonTransform.java
  firebase-crashlytics/src/test/java/com/google/firebase/crashlytics/internal/model/CrashlyticsReportTest.java
Labels: cla: yes, size/S

#1343 Remove ABT Experiment Cleanup from FIAM fetch path
  firebase-inappmessaging/src/main/java/com/google/firebase/inappmessaging/internal/ApiClient.java
  firebase-inappmessaging/src/main/java/com/google/firebase/inappmessaging/internal/InAppMessageStreamManager.java
Labels: cla: yes, size/S

#1365 Add proguard.txt for firebase-crashlytics-ndk
  firebase-crashlytics-ndk/firebase-crashlytics-ndk-proguard.txt
  firebase-crashlytics-ndk/firebase-crashlytics-ndk.gradle
Labels: cla: yes, size/S

#1349 Nudge customers to update if on an old Firebase Analytics
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/analytics/AnalyticsConnectorReceiver.java
Labels: cla: yes, size/S

#1366 Making minor changes to Javadoc text.
  firebase-installations/src/main/java/com/google/firebase/installations/FirebaseInstallations.java
Labels: cla: yes, size/S

#1368 Fixing the format and version issue
  firebase-installations/gradle.properties
  firebase-installations/src/main/java/com/google/firebase/installations/FirebaseInstallations.java
Labels: cla: yes, size/S

#1367 Add support for -DexclusiveSpecTest=<TestName> to SpecTestCase.
  firebase-firestore/src/test/java/com/google/firebase/firestore/spec/SpecTestCase.java
Labels: cla: yes, size/M

#1373 Small logging improvements for spec tests.
  firebase-firestore/src/test/java/com/google/firebase/firestore/spec/SpecTestCase.java
Labels: cla: yes, size/S

#1370 Make repository usable on JDK11.
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/ci/CheckCoveragePlugin.groovy
  encoders/firebase-encoders-processor/firebase-encoders-processor.gradle
  encoders/firebase-encoders-processor/src/main/java/com/google/firebase/encoders/processor/EncodableProcessor.java
  encoders/firebase-encoders-processor/src/test/resources/ExpectedGenericsEncoder.java
  encoders/firebase-encoders-processor/src/test/resources/ExpectedGenericsEncoderWithUnknownType.java
  encoders/firebase-encoders-processor/src/test/resources/ExpectedRecursiveGenericEncoder.java
  encoders/firebase-encoders-processor/src/test/resources/ExpectedSimpleClassEncoder.java
  encoders/firebase-encoders-processor/src/test/resources/ExpectedTypeWithListEncoder.java
  fiamui-app/fiamui-app.gradle
  firebase-database-collection/firebase-database-collection.gradle
  firebase-inappmessaging/firebase-inappmessaging.gradle
  gradle.properties
Labels: cla: yes, size/M

#1375 Call onConnectivityStateChange from async queue.
  firebase-firestore/src/main/java/com/google/firebase/firestore/remote/GrpcCallProvider.java
Labels: api: firestore, cla: yes, size/XS

#1356 Crashlytics ndk datatransport
  firebase-crashlytics/src/androidTest/assets/firebase_settings.json
  firebase-crashlytics/src/androidTest/assets/firebase_settings_new.json
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/BytesBackedNativeSessionFileTest.java
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/CrashlyticsControllerTest.java
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/CrashlyticsCoreTest.java
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/FileBackedNativeSessionFileTest.java
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/NativeSessionFileGzipperTest.java
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/SessionReportingCoordinatorTest.java
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/persistence/CrashlyticsReportPersistenceTest.java
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/report/ReportUploaderTest.java
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/send/DataTransportCrashlyticsReportSenderTest.java
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/settings/SettingsV3JsonTransformTest.java
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/settings/TestSettingsData.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/BytesBackedNativeSessionFile.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsController.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsReportDataCapture.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsReportWithSessionId.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/DataTransportState.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/FileBackedNativeSessionFile.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/NativeSessionFile.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/NativeSessionFileGzipper.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/SessionReportingCoordinator.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/model/CrashlyticsReport.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/model/serialization/CrashlyticsReportJsonTransform.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/persistence/CrashlyticsReportPersistence.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/report/ReportUploader.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/send/DataTransportCrashlyticsReportSender.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/settings/SettingsJsonConstants.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/settings/SettingsV3JsonTransform.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/settings/model/AppSettingsData.java
  firebase-crashlytics/src/test/java/com/google/firebase/crashlytics/internal/model/CrashlyticsReportTest.java
Labels: cla: yes, size/XXL

#1379 Backport ServerTimestamp type order changes
  firebase-firestore/src/main/java/com/google/firebase/firestore/UserDataWriter.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/model/Values.java
Labels: api: firestore, cla: yes, size/L

#1387 Clean up error handling for report persistence
  encoders/firebase-encoders-json/gradle.properties
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/CrashlyticsControllerTest.java
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/model/serialization/CrashlyticsReportJsonTransformTest.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/FirebaseCrashlytics.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/BytesBackedNativeSessionFile.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsController.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsCore.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsLifecycleEvents.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsUncaughtExceptionHandler.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/DataTransportState.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/FileBackedNativeSessionFile.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/MetaDataStore.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/SessionReportingCoordinator.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/UserMetadata.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/log/LogFileManager.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/model/serialization/CrashlyticsReportJsonTransform.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/persistence/CrashlyticsReportPersistence.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/report/ReportUploader.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/report/model/CreateReportRequest.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/report/network/NativeCreateReportSpiCall.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/send/DataTransportCrashlyticsReportSender.java
Labels: cla: yes, size/XL

#1386 Fix apk size upload in post-submit runs.
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/measurement/MetricsReportUploader.java
Labels: cla: yes, size/XS

#1377 Improve coverage report format in GitHub pull requests.
  build.gradle
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/ci/CheckCoveragePlugin.groovy
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/measurement/coverage/CheckCoveragePlugin.groovy
  ci/fireci/fireciplugins/coverage.py
  ci/fireci/setup.py
Labels: cla: yes, size/L

#1392 Include branch information in metrics uploading.
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/measurement/MetricsReportUploader.java
Labels: cla: yes, size/S

#1394 Fix for `checkCoverage` not being defined.
  buildSrc/src/main/groovy/com/google/firebase/gradle/plugins/ci/ContinuousIntegrationPlugin.groovy
Labels: cla: yes, size/XS

#1403 Sending api key as a request header and not in the request url
  firebase-installations/gradle.properties
  firebase-installations/src/main/java/com/google/firebase/installations/remote/FirebaseInstallationServiceClient.java
Labels: cla: yes, size/M
