Repository firebase/firebase-android-sdk, pull requests merged in 2020-10, with the labels that each got.

#2016 Fix reflection error in com.google.android.datatransport.Priority when using aggressive Proguard rules.
  transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/util/PriorityMapping.java
Labels: cla: yes, size/XS

#2039 Log FIS auth token instead of displaying it in the RC test app.
  firebase-config/bandwagoner/src/main/java/com/googletest/firebase/remoteconfig/bandwagoner/ApiFragment.java
Labels: cla: yes, size/XS

#2003 Enable request limiter for CreateInstallation, GenerateAuthToken request calls.
  firebase-installations/src/main/java/com/google/firebase/installations/FirebaseInstallations.java
  firebase-installations/src/main/java/com/google/firebase/installations/FirebaseInstallationsException.java
  firebase-installations/src/main/java/com/google/firebase/installations/Utils.java
  firebase-installations/src/main/java/com/google/firebase/installations/remote/FirebaseInstallationServiceClient.java
  firebase-installations/src/main/java/com/google/firebase/installations/remote/RequestLimiter.java
  firebase-installations/src/test/java/com/google/firebase/installations/FirebaseInstallationsTest.java
Labels: cla: yes, size/L

#2040 Double check for events after parsing report data
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/persistence/CrashlyticsReportPersistence.java
Labels: cla: yes, size/XS

#2043 Update released versions.
  firebase-dynamic-links/gradle.properties
  firebase-firestore/gradle.properties
Labels: cla: yes, size/XS

#2038 Make `ComponentRuntime` mutable.
  firebase-components/firebase-components.gradle
  firebase-components/src/main/java/com/google/firebase/components/ComponentRuntime.java
  firebase-components/src/main/java/com/google/firebase/components/Deferred.java
  firebase-components/src/main/java/com/google/firebase/components/LazySet.java
  firebase-components/src/test/java/com/google/firebase/components/ComponentRuntimeTest.java
  firebase-components/src/test/java/com/google/firebase/components/DeferredTest.java
  firebase-components/src/test/java/com/google/firebase/components/LazySetTest.java
  firebase-functions/src/main/java/com/google/firebase/functions/FirebaseContextProvider.java
Labels: cla: yes, size/L

#2042 Remove deprecated methods from RC.
  firebase-config/api.txt
  firebase-config/bandwagoner/src/androidTest/java/com/googletest/firebase/remoteconfig/bandwagoner/BandwagonerEspressoTest.java
  firebase-config/bandwagoner/src/main/java/com/googletest/firebase/remoteconfig/bandwagoner/ApiFragment.java
  firebase-config/src/androidTest/java/com/google/firebase/remoteconfig/FirebaseRemoteConfigIntegrationTest.java
  firebase-config/src/main/java/com/google/firebase/remoteconfig/FirebaseRemoteConfig.java
  firebase-config/src/main/java/com/google/firebase/remoteconfig/FirebaseRemoteConfigFetchException.java
  firebase-config/src/main/java/com/google/firebase/remoteconfig/FirebaseRemoteConfigFetchThrottledException.java
  firebase-config/src/main/java/com/google/firebase/remoteconfig/FirebaseRemoteConfigSettings.java
  firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigCacheClient.java
  firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigFetchHandler.java
  firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigMetadataClient.java
  firebase-config/src/test/java/com/google/firebase/remoteconfig/FirebaseRemoteConfigSettingsTest.java
  firebase-config/src/test/java/com/google/firebase/remoteconfig/FirebaseRemoteConfigTest.java
  firebase-config/src/test/java/com/google/firebase/remoteconfig/internal/ConfigCacheClientTest.java
  firebase-config/src/test/java/com/google/firebase/remoteconfig/internal/ConfigMetadataClientTest.java
Labels: cla: yes, size/XL

#2026 Remove timestampInSnapshots Setting
  firebase-firestore/CHANGELOG.md
  firebase-firestore/api.txt
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/FieldsTest.java
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/testutil/IntegrationTestUtil.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/DocumentSnapshot.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/FirebaseFirestoreSettings.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/UserDataWriter.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/UserDataWriterTest.java
Labels: cla: yes, size/L

#2036 Catch OverlappingFilelockException to prevent app crashes
  firebase-installations/src/main/java/com/google/firebase/installations/CrossProcessLock.java
Labels: cla: yes, size/XS

#2034 Remove protobuf dependency from RC SDK.
  firebase-abt/firebase-abt.gradle
  firebase-config/firebase-config.gradle
  firebase-config/src/main/java/com/google/firebase/remoteconfig/RemoteConfigComponent.java
  firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/LegacyConfigsHandler.java
  firebase-config/src/proto/com/google/android/gms/config/proto/config.proto
  firebase-config/src/proto/com/google/android/gms/config/proto/config_logs.proto
  firebase-config/src/proto/com/google/android/gms/config/proto/config_persistence.proto
  firebase-config/src/test/java/com/google/firebase/remoteconfig/AbtExperimentHelper.java
  firebase-config/src/test/java/com/google/firebase/remoteconfig/RemoteConfigComponentTest.java
  firebase-config/src/test/java/com/google/firebase/remoteconfig/internal/LegacyConfigsHandlerTest.java
  firebase-inappmessaging/src/main/java/com/google/firebase/inappmessaging/internal/AbtIntegrationHelper.java
  firebase-inappmessaging/src/proto/firebase/inappmessaging/proto/experiment_payload.proto
  firebase-inappmessaging/src/proto/google/internal/firebase/inappmessaging/v1/campaign.proto
  firebase-inappmessaging/src/test/java/com/google/firebase/inappmessaging/internal/InAppMessageStreamManagerTest.java
Labels: cla: yes, size/XXL

#2059 Fix Android Manifest formatting
  firebase-installations/src/main/AndroidManifest.xml
Labels: cla: yes, size/XS

#2061 Add support for MCC/MNC and Country fields in CCT Transport Backend.
  transport/transport-backend-cct/src/main/java/com/google/android/datatransport/cct/CctTransportBackend.java
  transport/transport-backend-cct/src/main/java/com/google/android/datatransport/cct/internal/AndroidClientInfo.java
  transport/transport-backend-cct/src/test/java/com/google/android/datatransport/cct/CctTransportBackendTest.java
  transport/transport-backend-cct/src/test/java/com/google/android/datatransport/cct/internal/LogRequestTest.java
Labels: cla: yes, size/M

#2063 Setup firebase ml model downloader directories.
  firebase-ml-modeldownloader/api.txt
  firebase-ml-modeldownloader/firebase-ml-modeldownloader.gradle
  firebase-ml-modeldownloader/gradle.properties
  firebase-ml-modeldownloader/src/main/AndroidManifest.xml
  firebase-ml-modeldownloader/src/main/java/com/google/firebase/ml/modeldownloader/FirebaseMlModelDownloader.java
  firebase-ml-modeldownloader/src/main/java/com/google/firebase/ml/modeldownloader/FirebaseMlModelDownloaderRegistrar.java
  firebase-ml-modeldownloader/src/test/java/com/google/firebase/ml/modeldownloader/FirebaseMlModelDownloaderRegistrarTest.java
  subprojects.cfg
Labels: cla: yes, size/L

#2072 update versions
  firebase-abt/gradle.properties
  firebase-config/gradle.properties
  firebase-firestore/gradle.properties
Labels: cla: yes, size/XS

#2067 Add support for fireperf e2e test in fireci.
  ci/fireci/fireciplugins/fireperf.py
Labels: cla: yes, size/M

#2074 Temporarily delete fireperf fireci command.
  ci/fireci/fireciplugins/fireperf.py
Labels: cla: yes, size/M

#2071 Add dynamic loading support to component discovery.
  firebase-common/src/main/java/com/google/firebase/FirebaseApp.java
  firebase-components/src/main/java/com/google/firebase/components/ComponentDiscovery.java
  firebase-components/src/main/java/com/google/firebase/components/ComponentRuntime.java
  firebase-components/src/main/java/com/google/firebase/components/InvalidRegistrarException.java
  firebase-components/src/main/java/com/google/firebase/components/LazySet.java
  firebase-components/src/main/java/com/google/firebase/components/OptionalProvider.java
  firebase-components/src/main/java/com/google/firebase/components/RestrictedComponentContainer.java
  firebase-components/src/main/java/com/google/firebase/dynamicloading/ComponentLoader.java
  firebase-components/src/main/java/com/google/firebase/dynamicloading/package-info.java
  firebase-components/src/test/java/com/google/firebase/components/ComponentDiscoveryTest.java
  firebase-components/src/test/java/com/google/firebase/components/ComponentRuntimeTest.java
  firebase-components/src/test/java/com/google/firebase/components/OptionalProviderTest.java
  firebase-components/src/test/java/com/google/firebase/components/RestrictedComponentContainerTest.java
Labels: cla: yes, size/XL

#2077 Add tests for Crashlytics DataCollectionArbiter
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/DataCollectionArbiterTest.java
Labels: cla: yes, size/M

#2079 Enforce asserts only in debug builds
  firebase-database/CHANGELOG.md
  firebase-database/src/main/java/com/google/firebase/database/core/utilities/Utilities.java
Labels: api: database, cla: yes, size/S

#2078 Make some changes that were causing build warnings/errors on copybara import
  firebase-crashlytics/ktx/src/androidTest/res/values/strings.xml
  firebase-crashlytics/src/androidTest/res/drawable-hdpi/ic_launcher.png
  firebase-crashlytics/src/androidTest/res/drawable-ldpi/ic_launcher.png
  firebase-crashlytics/src/androidTest/res/drawable-mdpi/ic_launcher.png
  firebase-crashlytics/src/androidTest/res/drawable-xhdpi/ic_launcher.png
  firebase-crashlytics/src/androidTest/res/drawable-xxhdpi/ic_launcher.png
  firebase-crashlytics/src/androidTest/res/values/strings.xml
  firebase-crashlytics/src/main/AndroidManifest.xml
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsBackgroundWorker.java
Labels: cla: yes, size/M

#2076 Adds firebase-dynamic-module-support SDK.
  firebase-common/src/main/AndroidManifest.xml
  firebase-components/firebase-dynamic-module-support/api.txt
  firebase-components/firebase-dynamic-module-support/firebase-dynamic-module-support.gradle
  firebase-components/firebase-dynamic-module-support/src/main/AndroidManifest.xml
  firebase-components/firebase-dynamic-module-support/src/main/java/com/google/firebase/dynamicloading/DynamicLoadingRegistrar.java
  firebase-components/firebase-dynamic-module-support/src/main/java/com/google/firebase/dynamicloading/DynamicLoadingSupport.java
  firebase-components/firebase-dynamic-module-support/src/main/java/com/google/firebase/dynamicloading/package-info.java
  subprojects.cfg
Labels: cla: yes, size/L

#2073 Add CustomModel class framework.
  firebase-ml-modeldownloader/api.txt
  firebase-ml-modeldownloader/src/main/java/com/google/firebase/ml/modeldownloader/CustomModel.java
  firebase-ml-modeldownloader/src/test/java/com/google/firebase/ml/modeldownloader/CustomModelTest.java
Labels: cla: yes, size/L

#2085 Implement Deferred<T> lint check.
  firebase-components/src/main/java/com/google/firebase/components/OptionalProvider.java
  firebase-components/src/main/java/com/google/firebase/components/annotations/DeferredApi.java
  firebase-components/src/main/java/com/google/firebase/inject/Deferred.java
  tools/lint/src/main/kotlin/CheckRegistry.kt
  tools/lint/src/main/kotlin/DeferredApiDetector.kt
  tools/lint/src/test/kotlin/DeferredApiDetectorTests.kt
Labels: cla: yes, size/L

#2083 Refactor FirebaseMlModel* class names to FirebaseModel*.
  firebase-ml-modeldownloader/api.txt
  firebase-ml-modeldownloader/src/main/AndroidManifest.xml
  firebase-ml-modeldownloader/src/main/java/com/google/firebase/ml/modeldownloader/FirebaseModelDownloader.java
  firebase-ml-modeldownloader/src/main/java/com/google/firebase/ml/modeldownloader/FirebaseModelDownloaderRegistrar.java
  firebase-ml-modeldownloader/src/test/java/com/google/firebase/ml/modeldownloader/FirebaseModelDownloaderRegistrarTest.java
Labels: cla: yes, size/M

#2093 Add CustomModelDownloadConditions class.
  firebase-ml-modeldownloader/api.txt
  firebase-ml-modeldownloader/firebase-ml-modeldownloader.gradle
  firebase-ml-modeldownloader/src/main/java/com/google/firebase/ml/modeldownloader/CustomModel.java
  firebase-ml-modeldownloader/src/main/java/com/google/firebase/ml/modeldownloader/CustomModelDownloadConditions.java
  firebase-ml-modeldownloader/src/test/java/com/google/firebase/ml/modeldownloader/CustomModelDownloadConditionsTest.java
Labels: cla: yes, size/L

#2095 Implement Provider.get() assignment lint check.
  tools/lint/src/main/kotlin/CheckRegistry.kt
  tools/lint/src/main/kotlin/ProviderAssignmentDetector.kt
  tools/lint/src/test/kotlin/DeferredApiDetectorTests.kt
  tools/lint/src/test/kotlin/ProviderAssignmentDetectorTests.kt
Labels: cla: yes, size/L

#2094 Fix tests in rc branch
  firebase-config-core/api.txt
  firebase-config-core/src/androidTest/java/com/google/firebase/remoteconfig/core/FirebaseRemoteConfigIntegrationTest.java
Labels: cla: yes, size/M

#2052 test(installations-ktx): Functions --> Installations
  firebase-installations/ktx/src/test/kotlin/com/google/firebase/installations/ktx/InstallationsTests.kt
Labels: cla: yes, ok-to-test, size/XS

#2098 Add FirebaseModelDownloader public API Headers
  firebase-ml-modeldownloader/api.txt
  firebase-ml-modeldownloader/src/main/java/com/google/firebase/ml/modeldownloader/DownloadType.java
  firebase-ml-modeldownloader/src/main/java/com/google/firebase/ml/modeldownloader/FirebaseModelDownloader.java
  firebase-ml-modeldownloader/src/test/java/com/google/firebase/ml/modeldownloader/FirebaseModelDownloaderTest.java
Labels: cla: yes, size/L

#2105 update versions
  firebase-messaging-directboot/gradle.properties
  firebase-messaging/gradle.properties
Labels: cla: yes, size/XS

#2035 Propagate exceptions to the caller if Fis getToken call fails with an exception.
  firebase-installations/src/main/java/com/google/firebase/installations/FirebaseInstallations.java
  firebase-installations/src/main/java/com/google/firebase/installations/GetAuthTokenListener.java
  firebase-installations/src/main/java/com/google/firebase/installations/GetIdListener.java
  firebase-installations/src/main/java/com/google/firebase/installations/StateListener.java
Labels: cla: yes, size/S

#2108 Add development_platform for Unity crash reports
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/CrashlyticsControllerTest.java
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/CrashlyticsReportDataCaptureTest.java
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/model/serialization/CrashlyticsReportJsonTransformTest.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/AppData.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsController.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsCore.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsReportDataCapture.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/model/CrashlyticsReport.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/model/serialization/CrashlyticsReportJsonTransform.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/proto/SessionProtobufHelper.java
Labels: cla: yes, size/L

#2109 Remove firebase-ml-natural-language related smoke tests.
  smoke-tests/build.gradle
  smoke-tests/src/main/java/com/google/firebase/testing/BuildOnlyTest.java
  smoke-tests/src/main/java/com/google/firebase/testing/SmartReplyTest.java
  smoke-tests/src/main/java/com/google/firebase/testing/TestSuite.java
Labels: cla: yes, size/M

#2104 Add Ml shared preferences for custom model storage
  firebase-ml-modeldownloader/firebase-ml-modeldownloader.gradle
  firebase-ml-modeldownloader/src/main/java/com/google/firebase/ml/modeldownloader/CustomModel.java
  firebase-ml-modeldownloader/src/main/java/com/google/firebase/ml/modeldownloader/FirebaseModelDownloaderRegistrar.java
  firebase-ml-modeldownloader/src/main/java/com/google/firebase/ml/modeldownloader/internal/SharedPreferencesUtil.java
  firebase-ml-modeldownloader/src/test/java/com/google/firebase/ml/modeldownloader/CustomModelTest.java
  firebase-ml-modeldownloader/src/test/java/com/google/firebase/ml/modeldownloader/internal/SharedPreferencesUtilTest.java
Labels: cla: yes, size/L

#2119 Remove proguarding for transport-backend-cct
  transport/transport-backend-cct/gradle.properties
  transport/transport-backend-cct/preguard.txt
Labels: cla: yes, size/S

#2112 Add additional platform signals to UserAgent.
  firebase-common/src/androidTest/java/com/google/firebase/FirebaseAppTest.java
  firebase-common/src/main/java/com/google/firebase/FirebaseApp.java
  firebase-common/src/main/java/com/google/firebase/FirebaseCommonRegistrar.java
  firebase-common/src/main/java/com/google/firebase/platforminfo/LibraryVersionComponent.java
  firebase-common/src/test/java/com/google/firebase/FirebaseAppTestUtil.java
  firebase-common/src/test/java/com/google/firebase/platforminfo/FirebasePlatformLoggingTest.java
Labels: cla: yes, size/L

#2115 Allow null and NaN values in filters
  firebase-firestore/CHANGELOG.md
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/QueryTest.java
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/ValidationTest.java
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/testutil/IntegrationTestUtil.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/Query.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/FieldFilter.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/core/QueryTest.java
Labels: api: firestore, cla: yes, size/L
