Repository firebase/firebase-android-sdk, pull requests merged in 2021-05, with the labels that each got.

#2655 Do not publish Javadoc for the App Check interop library
  appcheck/firebase-appcheck-interop/firebase-appcheck-interop.gradle
Labels: cla: yes, size/XS

#2653 Configure google-services.json for macrobenchmark tests.
  ci/fireci/fireciplugins/macrobenchmark.py
  macrobenchmark/config.yaml
Labels: cla: yes, size/M

#2659 App Check Javadoc fixes
  appcheck/firebase-appcheck-debug-testing/src/main/java/com/google/firebase/appcheck/debug/testing/DebugAppCheckTestHelper.java
  appcheck/firebase-appcheck-safetynet/src/main/java/com/google/firebase/appcheck/safetynet/SafetyNetAppCheckProviderFactory.java
  appcheck/firebase-appcheck/src/main/java/com/google/firebase/appcheck/AppCheckProvider.java
  appcheck/firebase-appcheck/src/main/java/com/google/firebase/appcheck/AppCheckProviderFactory.java
  appcheck/firebase-appcheck/src/main/java/com/google/firebase/appcheck/FirebaseAppCheck.java
Labels: cla: yes, size/M

#2661 Cleanup Crashlytics javadocs formatting
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/FirebaseCrashlytics.java
Labels: cla: yes, size/S

#2656 Keep smoke tests up to date.
  smoke-tests/build.gradle
  smoke-tests/src/main/java/com/google/firebase/testing/BuildOnlyTest.java
Labels: cla: yes, size/S

#2667 Updated README to include firebase-crashlytics-ndk build requirements.
  README.md
  firebase-crashlytics-ndk/README.md
Labels: cla: yes, size/S

#2643 Collect, persist and transport ANR ApplicationExitInfo
  .idea/copyright/Apache_2___Google.xml
  .idea/copyright/profiles_settings.xml
  .idea/runConfigurations/FirestoreProdIntegrationTest.xml
  .idea/runConfigurations/Firestore_Integration_Tests__Firestore_Emulator_.xml
  .idea/runConfigurations/Firestore_Unit_Tests.xml
  firebase-crashlytics/firebase-crashlytics.gradle
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/CrashlyticsControllerTest.java
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/persistence/CrashlyticsReportPersistenceTest.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsController.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsCore.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/SessionReportingCoordinator.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/model/CrashlyticsReport.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/persistence/CrashlyticsReportPersistence.java
  firebase-crashlytics/src/test/java/com/google/firebase/crashlytics/internal/common/CrashlyticsControllerRobolectricTest.java
  firebase-crashlytics/src/test/java/com/google/firebase/crashlytics/internal/common/SessionReportingCoordinatorRobolectricTest.java
Labels: cla: yes, size/XL

#2669 Removing FIAM Display SDK dependency on Analytics.
  firebase-inappmessaging-display/firebase-inappmessaging-display.gradle
  firebase-inappmessaging-display/src/main/java/com/google/firebase/inappmessaging/display/FirebaseInAppMessagingDisplayRegistrar.java
Labels: cla: yes, size/XS

#2673 Fetch and parse macrobenchmark results from GCS.
  ci/fireci/fireciplugins/macrobenchmark.py
  ci/fireci/setup.py
Labels: cla: yes, size/M

#2676 Add firebase-common macrobenchmark.
  macrobenchmark/config.yaml
Labels: cla: yes, size/XS

#2662 Fix fireperf RateLimiter replenishment behavior and unit alignment.
  firebase-perf/src/main/java/com/google/firebase/perf/transport/RateLimiter.java
  firebase-perf/src/main/java/com/google/firebase/perf/transport/TransportManager.java
  firebase-perf/src/main/java/com/google/firebase/perf/util/Rate.java
  firebase-perf/src/test/java/com/google/firebase/perf/transport/RateLimiterTest.java
  firebase-perf/src/test/java/com/google/firebase/perf/util/RateTest.java
Labels: cla: yes, size/XL

#2680 Clean up old sessions in the NDK
  firebase-crashlytics-ndk/src/main/java/com/google/firebase/crashlytics/ndk/CrashFilesManager.java
  firebase-crashlytics-ndk/src/main/java/com/google/firebase/crashlytics/ndk/CrashpadController.java
  firebase-crashlytics-ndk/src/main/java/com/google/firebase/crashlytics/ndk/NdkCrashFilesManager.java
Labels: cla: yes, size/S

#2682 Upload macrobenchmark results to the metric service.
  ci/fireci/fireci/uploader.py
  ci/fireci/fireciplugins/macrobenchmark.py
  ci/fireci/setup.py
Labels: cla: yes, size/M

#2677 Add support for ktx dependencies in the recipe generator.
  buildSrc/src/main/java/com/google/firebase/gradle/bomgenerator/RecipeVersionWriter.java
Labels: cla: yes, size/M

#2577 Simplify Mutations
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/LocalStore.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/model/DatabaseId.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/model/DocumentKey.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/model/Values.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/model/mutation/Mutation.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/model/mutation/MutationBatch.java
Labels: api: firestore, cla: yes, size/M

#2692 Fix incremental builds for firebase-crashlytics-ndk
  firebase-crashlytics-ndk/firebase-crashlytics-ndk.gradle
Labels: cla: yes, size/XS

#2671 Crashlytics Add Internal Keys feature for Unity Metadata
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/MetaDataStoreTest.java
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/SessionReportingCoordinatorTest.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsController.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsCore.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/KeysMap.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/MetaDataStore.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/SessionReportingCoordinator.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/UserMetadata.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/model/CrashlyticsReport.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/model/serialization/CrashlyticsReportJsonTransform.java
Labels: cla: yes, size/L

#2694 Update released versions.
  appcheck/firebase-appcheck-debug-testing/gradle.properties
  appcheck/firebase-appcheck-debug/gradle.properties
  appcheck/firebase-appcheck-interop/gradle.properties
  appcheck/firebase-appcheck-safetynet/gradle.properties
  appcheck/firebase-appcheck/gradle.properties
  encoders/firebase-encoders-json/gradle.properties
  encoders/firebase-encoders/gradle.properties
  firebase-abt/gradle.properties
  firebase-common/gradle.properties
  firebase-components/firebase-dynamic-module-support/gradle.properties
  firebase-components/gradle.properties
  firebase-config/gradle.properties
  firebase-crashlytics-ndk/gradle.properties
  firebase-crashlytics/gradle.properties
  firebase-database-collection/gradle.properties
  firebase-database/gradle.properties
  firebase-datatransport/gradle.properties
  firebase-dynamic-links/gradle.properties
  firebase-firestore/gradle.properties
  firebase-functions/gradle.properties
  firebase-inappmessaging-display/gradle.properties
  firebase-inappmessaging/gradle.properties
  firebase-installations-interop/gradle.properties
  firebase-installations/gradle.properties
  firebase-messaging-directboot/gradle.properties
  firebase-messaging/gradle.properties
  firebase-ml-modeldownloader/gradle.properties
  firebase-perf/gradle.properties
  firebase-storage/gradle.properties
  protolite-well-known-types/gradle.properties
  transport/transport-api/gradle.properties
  transport/transport-backend-cct/gradle.properties
  transport/transport-runtime/gradle.properties
Labels: cla: yes, size/L

#2683 Remove application-id from macrobenchmark config file.
  ci/fireci/fireciplugins/macrobenchmark.py
  macrobenchmark/config.yaml
  macrobenchmark/template/app/build.gradle.mustache
  macrobenchmark/template/benchmark/build.gradle
  macrobenchmark/template/benchmark/src/androidTest/java/com/google/firebase/benchmark/BenchmarkTest.kt.mustache
  macrobenchmark/template/benchmark/src/main/AndroidManifest.xml.mustache
  macrobenchmark/template/build.gradle
Labels: cla: yes, size/M

#2693 Skip backoff when App enters Foreground
  firebase-firestore/CHANGELOG.md
  firebase-firestore/src/main/java/com/google/firebase/firestore/remote/AndroidConnectivityMonitor.java
Labels: api: firestore, cla: yes, size/M

#2697 Revert "Crashlytics Add Internal Keys feature for Unity Metadata"
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/MetaDataStoreTest.java
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/SessionReportingCoordinatorTest.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsController.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsCore.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/KeysMap.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/MetaDataStore.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/SessionReportingCoordinator.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/UserMetadata.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/model/CrashlyticsReport.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/model/serialization/CrashlyticsReportJsonTransform.java
Labels: cla: yes, size/L

#2695 Update bom generator task
  buildSrc/src/main/java/com/google/firebase/gradle/bomgenerator/BomGeneratorTask.java
  buildSrc/src/main/java/com/google/firebase/gradle/bomgenerator/RecipeVersionWriter.java
Labels: cla: yes, size/S

#2663 Change Uploader's `logAndUpdateState` to upload all pending events
  transport/transport-runtime/src/androidTest/java/com/google/android/datatransport/runtime/UploaderIntegrationTest.java
  transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/scheduling/jobscheduling/Uploader.java
  transport/transport-runtime/src/test/java/com/google/android/datatransport/runtime/scheduling/jobscheduling/UploaderTest.java
Labels: cla: yes, ok-to-test, size/L
