Repository firebase/firebase-android-sdk, pull requests merged in 2021-08, with the labels that each got.

#2871 FAD refactor update logic into UpdateAppClient
  firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/FirebaseAppDistribution.java
  firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/UpdateAppClient.java
  firebase-app-distribution/src/test/java/com/google/firebase/appdistribution/FirebaseAppDistributionTest.java
  firebase-app-distribution/src/test/java/com/google/firebase/appdistribution/UpdateAppClientTest.java
Labels: cla: yes, size/L

#2878 Check For Update Refactor and tests
  firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/CheckForUpdateClient.java
  firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/TaskUtils.java
  firebase-app-distribution/src/test/java/com/google/firebase/appdistribution/CheckForUpdateClientTest.java
  firebase-app-distribution/src/test/java/com/google/firebase/appdistribution/TestOnCompleteListener.java
Labels: cla: yes, size/L

#2879 Refactor update to latest release
  firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/FirebaseAppDistribution.java
  firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/TesterSignInClient.java
  firebase-app-distribution/src/test/java/com/google/firebase/appdistribution/FirebaseAppDistributionTest.java
  firebase-app-distribution/src/test/java/com/google/firebase/appdistribution/TesterSignInClientTest.java
Labels: cla: yes, size/L

#2881 FAD updateApp for APK MVP
  firebase-app-distribution/firebase-app-distribution.gradle
  firebase-app-distribution/src/main/AndroidManifest.xml
  firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/FirebaseAppDistribution.java
  firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/InstallActivity.java
  firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/UpdateApkClient.java
  firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/UpdateAppClient.java
  firebase-app-distribution/src/main/res/xml/provider_paths.xml
Labels: cla: yes, size/L

#2882 Update API and add methods to UpdateTaskImpl
  firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/AppDistributionRelease.java
  firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/FirebaseAppDistribution.java
  firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/OnProgressListener.java
  firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/UpdateApkClient.java
  firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/UpdateAppClient.java
  firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/UpdateProgress.java
  firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/UpdateStatus.java
  firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/UpdateTask.java
  firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/UpdateTaskImpl.java
  firebase-app-distribution/src/test/java/com/google/firebase/appdistribution/FirebaseAppDistributionTest.java
  firebase-app-distribution/src/test/java/com/google/firebase/appdistribution/UpdateAppClientTest.java
Labels: cla: yes, size/L

#2856 Add IndexConfiguration
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/IndexingTest.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/FirebaseFirestore.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/FirestoreClient.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/IndexManager.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/LocalSerializer.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/LocalStore.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/MemoryIndexManager.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteIndexManager.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLitePersistence.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteSchema.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/model/FieldIndex.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/util/Preconditions.java
  firebase-firestore/src/proto/google/firestore/admin/index.proto
Labels: api: firestore, cla: yes, size/XL

#2886 FAD refactor UpdateApp and UpdateTaskImpl
  firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/FirebaseAppDistribution.java
  firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/UpdateApkClient.java
  firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/UpdateAppClient.java
  firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/UpdateTaskImpl.java
  firebase-app-distribution/src/test/java/com/google/firebase/appdistribution/FirebaseAppDistributionTest.java
  firebase-app-distribution/src/test/java/com/google/firebase/appdistribution/UpdateApkClientTest.java
  firebase-app-distribution/src/test/java/com/google/firebase/appdistribution/UpdateAppClientTest.java
Labels: size/L, cla: yes

#2890 Update released versions.
  firebase-config/gradle.properties
  firebase-crashlytics-ndk/gradle.properties
  firebase-crashlytics/gradle.properties
  firebase-database/gradle.properties
  firebase-datatransport/gradle.properties
  firebase-dynamic-links/gradle.properties
  firebase-firestore/gradle.properties
  firebase-perf/gradle.properties
  transport/transport-runtime/gradle.properties
Labels: size/M, cla: yes

#2891 Migrate AnnotationValue#toString to auto-common's AnnotationValues.toString
  encoders/firebase-encoders-processor/firebase-encoders-processor.gradle
  encoders/firebase-encoders-processor/src/main/java/com/google/firebase/encoders/processor/EncodableProcessor.java
Labels: size/XS, cla: yes

#2892 FAD reintroduce terminal states to UpdateStatus
  firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/UpdateApkClient.java
  firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/UpdateStatus.java
  firebase-app-distribution/src/test/java/com/google/firebase/appdistribution/UpdateApkClientTest.java
Labels: size/L, cla: yes

#2888 Making sure a change in current activity gets propogated to the signIn and updateApp clients
  firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/Constants.java
  firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/FirebaseAppDistribution.java
  firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/TesterSignInClient.java
  firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/UpdateApkClient.java
  firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/UpdateAppClient.java
  firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/UpdateTask.java
  firebase-app-distribution/src/test/java/com/google/firebase/appdistribution/FirebaseAppDistributionTest.java
  firebase-app-distribution/src/test/java/com/google/firebase/appdistribution/TesterSignInClientTest.java
  firebase-app-distribution/src/test/java/com/google/firebase/appdistribution/UpdateApkClientTest.java
  firebase-app-distribution/src/test/java/com/google/firebase/appdistribution/UpdateAppClientTest.java
Labels: size/L, cla: yes

#2889 Increase connected check timeout for Firestore to 30m
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/ci/device/FirebaseTestLabExtension.java
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/ci/device/FirebaseTestServer.java
  firebase-firestore/firebase-firestore.gradle
Labels: size/S, cla: yes, api: firestore

#2898 Change logic in check for update so it correctly prompts on new APKs
  firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/CheckForUpdateClient.java
  firebase-app-distribution/src/test/java/com/google/firebase/appdistribution/CheckForUpdateClientTest.java
Labels: size/S, cla: yes

#2883 Add Index Encoding code from backend
  firebase-firestore/src/main/java/com/google/firebase/firestore/index/DirectionalIndexByteEncoder.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/index/FirestoreIndexValueWriter.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/index/IntMath.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/index/OrderedCodeReader.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/index/OrderedCodeWriter.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/index/package-info.java
Labels: size/XL, cla: yes, api: firestore

#2911 Various app-check fixes.
  appcheck/firebase-appcheck-debug-testing/src/main/AndroidManifest.xml
  appcheck/firebase-appcheck-debug/src/main/AndroidManifest.xml
  appcheck/firebase-appcheck-debug/src/main/java/com/google/firebase/appcheck/debug/internal/DebugAppCheckProvider.java
  appcheck/firebase-appcheck-interop/src/main/AndroidManifest.xml
  appcheck/firebase-appcheck-safetynet/src/main/AndroidManifest.xml
  appcheck/firebase-appcheck-safetynet/src/main/java/com/google/firebase/appcheck/safetynet/internal/SafetyNetAppCheckProvider.java
Labels: size/S, cla: yes

#2905 Implement AAB updateTask completion on app resume
  firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/FirebaseAppDistribution.java
  firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/FirebaseAppDistributionException.java
  firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/ReleaseUtils.java
  firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/UpdateAppClient.java
  firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/UpdateTaskImpl.java
  firebase-app-distribution/src/test/java/com/google/firebase/appdistribution/FirebaseAppDistributionTest.java
  firebase-app-distribution/src/test/java/com/google/firebase/appdistribution/UpdateAppClientTest.java
Labels: size/L, cla: yes

#2906 Fix update app synchronization issues
  firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/FirebaseAppDistribution.java
  firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/FirebaseAppDistributionException.java
  firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/ReleaseUtils.java
  firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/UpdateApkClient.java
  firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/UpdateAppClient.java
  firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/UpdateTaskImpl.java
  firebase-app-distribution/src/test/java/com/google/firebase/appdistribution/FirebaseAppDistributionTest.java
  firebase-app-distribution/src/test/java/com/google/firebase/appdistribution/UpdateApkClientTest.java
  firebase-app-distribution/src/test/java/com/google/firebase/appdistribution/UpdateAppClientTest.java
Labels: size/L, cla: yes

#2910 FAD Add release codeHash verification for APKs
  firebase-app-distribution/firebase-app-distribution.gradle
  firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/CheckForUpdateClient.java
  firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/ReleaseIdentifierStorage.java
  firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/UpdateApkClient.java
  firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/UpdateAppClient.java
  firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/internal/ReleaseIdentificationUtils.java
  firebase-app-distribution/src/test/java/com/google/firebase/appdistribution/CheckForUpdateClientTest.java
  firebase-app-distribution/src/test/java/com/google/firebase/appdistribution/UpdateApkClientTest.java
Labels: size/L, cla: yes

#2861 Add Watch Conformance Tests
  firebase-firestore/firebase-firestore.gradle
  firebase-firestore/src/androidTest/assets/conformance/README.md
  firebase-firestore/src/androidTest/assets/conformance/ignorelist.txt
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/ConformanceTest.java
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/conformance/ActionFilter.java
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/conformance/ConformanceRuntime.java
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/conformance/TestCaseConverter.java
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/conformance/TestCaseIgnoreList.java
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/conformance/TestCollection.java
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/conformance/TestDocument.java
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/conformance/model/Collection.java
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/conformance/model/Mutation.java
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/conformance/model/Order.java
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/conformance/model/Query.java
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/conformance/model/QueryFilter.java
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/conformance/model/Result.java
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/conformance/model/TestCase.java
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/conformance/model/Where.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/UserDataWriter.java
  firebase-firestore/src/proto/google/apphosting/datastore/testing/datastore_test_trace.proto
  firebase-firestore/src/proto/google/firebase/firestore/proto/bundle.proto
  firebase-firestore/src/testUtil/java/com/google/firebase/firestore/testutil/TestUtil.java
Labels: size/XXL, cla: yes, api: firestore

#2900 Add Query Planner
  firebase-firestore/src/main/java/com/google/firebase/firestore/FirebaseFirestore.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/LocalSerializer.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/model/FieldIndex.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/model/TargetIndexMatcher.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/model/TargetIndexMatcherTest.java
Labels: size/XL, cla: yes, api: firestore

#2925 Plumb the executor through waitForDataCollectionPermission in Crashlytics
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/CrashlyticsControllerTest.java
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/settings/DefaultSettingsControllerTest.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/DataCollectionArbiter.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/Utils.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/settings/SettingsController.java
Labels: size/M, cla: yes
