Repository firebase/firebase-android-sdk, pull requests merged in 2021-11, with the labels that each got.

#3095 Post release work M106
  firebase-crashlytics-ndk/gradle.properties
  firebase-crashlytics/gradle.properties
  firebase-dynamic-links/gradle.properties
  firebase-firestore/gradle.properties
  firebase-inappmessaging-display/gradle.properties
  firebase-inappmessaging/gradle.properties
  firebase-messaging-directboot/gradle.properties
  firebase-messaging/gradle.properties
Labels: size/M, cla: yes

#3093 Refactor InstallApkClient to use the central lifecycle methods
  firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/FirebaseAppDistribution.java
  firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/InstallApkClient.java
  firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/UpdateAppClient.java
  firebase-app-distribution/src/test/java/com/google/firebase/appdistribution/InstallApkClientTests.java
Labels: size/M, cla: yes

#3096 Fad remove decentralized lifecycle callbacks
  firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/FirebaseAppDistribution.java
  firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/FirebaseAppDistributionRegistrar.java
  firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/UpdateAabClient.java
  firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/UpdateAppClient.java
  firebase-app-distribution/src/test/java/com/google/firebase/appdistribution/FirebaseAppDistributionTest.java
  firebase-app-distribution/src/test/java/com/google/firebase/appdistribution/UpdateAabClientTest.java
  firebase-app-distribution/src/test/java/com/google/firebase/appdistribution/UpdateAppClientTest.java
Labels: size/L, cla: yes

#3099 Fixes some bugs with the new state managment
  firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/FirebaseAppDistribution.java
  firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/TesterSignInClient.java
  firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/internal/FirebaseAppDistributionLifecycleNotifier.java
  firebase-app-distribution/src/test/java/com/google/firebase/appdistribution/TesterSignInClientTest.java
Labels: size/L, cla: yes

#3100 Handle lower version code
  firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/CheckForNewReleaseClient.java
  firebase-app-distribution/src/test/java/com/google/firebase/appdistribution/CheckForNewReleaseClientTest.java
Labels: size/M, cla: yes

#3101 Create README.md
  apk-size/README.md
Labels: size/S, cla: yes

#3087 User-scoped indices
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/remote/RemoteStoreTest.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/ComponentProvider.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/FirestoreClient.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/MemoryComponentProvider.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/SQLiteComponentProvider.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/DefaultQueryEngine.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/IndexBackfiller.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/IndexManager.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/IndexedQueryEngine.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/LocalStore.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/MemoryIndexManager.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/MemoryMutationQueue.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/MemoryPersistence.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/MemoryRemoteDocumentCache.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/Persistence.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/QueryEngine.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/RemoteDocumentCache.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteIndexManager.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteMutationQueue.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLitePersistence.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteRemoteDocumentCache.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteSchema.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/CountingQueryEngine.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/IndexManagerTestCase.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/IndexedQueryEngineTest.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/LocalStoreTestCase.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/LruGarbageCollectorTestCase.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/QueryEngineTest.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/RemoteDocumentCacheTestCase.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/SQLiteIndexBackfillerTest.java
Labels: size/L, cla: yes, api: firestore

#3088 Write oldest documents to Index first
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/IndexBackfiller.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/IndexManager.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/MemoryIndexManager.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteIndexManager.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/IndexBackfillerTest.java
Labels: size/L, cla: yes, api: firestore

#3102 Sign out tester if check for new releases call has an authentication failure
  firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/FirebaseAppDistribution.java
  firebase-app-distribution/src/test/java/com/google/firebase/appdistribution/FirebaseAppDistributionTest.java
Labels: size/M, cla: yes

#3098 Memoize field indices
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/IndexBackfiller.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/IndexManager.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/LocalStore.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/MemoryIndexManager.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/MemoryPersistence.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/Persistence.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteIndexManager.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteMutationQueue.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLitePersistence.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/model/FieldIndex.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/IndexBackfillerTest.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/IndexManagerTestCase.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/IndexedQueryEngineTest.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/LruGarbageCollectorTestCase.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/MutationQueueTestCase.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/QueryEngineTest.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/RemoteDocumentCacheTestCase.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/SQLiteIndexManagerTest.java
Labels: size/L, cla: yes, api: firestore

#3094 Overlay Data Migration
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/LocalDocumentsView.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/LocalStore.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/MemoryOverlayMigrationManager.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/MemoryPersistence.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/OverlayMigrationManager.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/Persistence.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteOverlayMigrationManager.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLitePersistence.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteSchema.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/PersistenceTestHelpers.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/SQLiteOverlayMigrationManagerTest.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/SQLiteSchemaTest.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/spec/SpecTestCase.java
Labels: size/XL, cla: yes

#3106 Adding Kotlin wrapper to java api
  firebase-app-distribution/firebase-app-distribution.gradle
  firebase-app-distribution/ktx/gradle.properties
  firebase-app-distribution/ktx/ktx.gradle
  firebase-app-distribution/ktx/src/androidTest/AndroidManifest.xml
  firebase-app-distribution/ktx/src/androidTest/kotlin/com/google/firebase/app/distribution/ktx/FirebaseAppDistributionTests.kt
  firebase-app-distribution/ktx/src/main/AndroidManifest.xml
  firebase-app-distribution/ktx/src/main/kotlin/com/google/firebase/app/distribution/ktx/FirebaseAppDistribution.kt
  subprojects.cfg
Labels: size/L, cla: yes

#3110 Adding in api.txt files to ktx and app distribution directories
  firebase-app-distribution/api.txt
  firebase-app-distribution/ktx/api.txt
  firebase-app-distribution/ktx/src/androidTest/kotlin/com/google/firebase/app/distribution/ktx/FirebaseAppDistributionTests.kt
  firebase-app-distribution/ktx/src/main/kotlin/com/google/firebase/app/distribution/ktx/FirebaseAppDistribution.kt
Labels: size/S, cla: yes

#3038 Tag products, bom and release versions during release.
  buildSrc/src/main/java/com/google/firebase/gradle/bomgenerator/BomGeneratorTask.java
  buildSrc/src/main/java/com/google/firebase/gradle/bomgenerator/tagging/GitClient.java
  buildSrc/src/main/java/com/google/firebase/gradle/bomgenerator/tagging/ShellExecutor.java
  buildSrc/src/test/kotlin/com/google/firebase/gradle/bomgenerator/tagging/GitClientTest.kt
Labels: size/L, cla: yes

#3116 Suppress Unicode warnings
  firebase-database/src/test/java/com/google/firebase/database/MapperTest.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/util/MapperTest.java
Labels: size/XS, cla: yes, api: database, api: firestore

#3128 Fix metrics counter reporting.
  transport/transport-runtime/src/androidTest/java/com/google/android/datatransport/runtime/TestDestination.java
  transport/transport-runtime/src/androidTest/java/com/google/android/datatransport/runtime/UploaderIntegrationTest.java
  transport/transport-runtime/src/androidTest/java/com/google/android/datatransport/runtime/UploaderTestRuntimeComponent.java
  transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/scheduling/jobscheduling/Uploader.java
Labels: size/L, cla: yes

#3118 Add ability to delete indexes
  firebase-firestore/src/main/java/com/google/firebase/firestore/FirebaseFirestore.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/FirestoreClient.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/IndexManager.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/LocalStore.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/MemoryIndexManager.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteIndexManager.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/model/FieldIndex.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/util/Util.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/IndexBackfillerTest.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/IndexingEnabledSQLiteLocalStoreTest.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/LocalStoreTestCase.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/model/FieldIndexTest.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/util/UtilTest.java
Labels: size/L, cla: yes, api: firestore

#3083 Support for API key restrictions in FirebaseModelDownloader
  firebase-ml-modeldownloader/src/main/java/com/google/firebase/ml/modeldownloader/internal/CustomModelDownloadService.java
  firebase-ml-modeldownloader/src/test/java/com/google/firebase/ml/modeldownloader/internal/CustomModelDownloadServiceTest.java
Labels: size/L, cla: yes, ok-to-test

#3131 Fix assert in token refresh
  firebase-database/CHANGELOG.md
  firebase-database/src/main/java/com/google/firebase/database/connection/PersistentConnectionImpl.java
Labels: size/S, cla: yes, api: database

#3124 Fix heartbeat reporting for App Check.
  appcheck/firebase-appcheck-debug/src/test/java/com/google/firebase/appcheck/debug/internal/DebugAppCheckProviderTest.java
  appcheck/firebase-appcheck-safetynet/src/main/java/com/google/firebase/appcheck/safetynet/internal/SafetyNetAppCheckProvider.java
  appcheck/firebase-appcheck-safetynet/src/test/java/com/google/firebase/appcheck/safetynet/internal/SafetyNetAppCheckProviderTest.java
  appcheck/firebase-appcheck/src/main/java/com/google/firebase/appcheck/internal/DefaultFirebaseAppCheck.java
  appcheck/firebase-appcheck/src/main/java/com/google/firebase/appcheck/internal/NetworkClient.java
  appcheck/firebase-appcheck/src/test/java/com/google/firebase/appcheck/internal/NetworkClientTest.java
Labels: size/L, cla: yes

#3143 Enforce consistency in creating / managing Crashlytics files
  firebase-crashlytics-ndk/firebase-crashlytics-ndk.gradle
  firebase-crashlytics-ndk/src/androidTest/java/com/google/firebase/crashlytics/ndk/CrashpadControllerTest.java
  firebase-crashlytics-ndk/src/main/java/com/google/firebase/crashlytics/ndk/CrashFilesManager.java
  firebase-crashlytics-ndk/src/main/java/com/google/firebase/crashlytics/ndk/CrashpadController.java
  firebase-crashlytics-ndk/src/main/java/com/google/firebase/crashlytics/ndk/FirebaseCrashlyticsNdk.java
  firebase-crashlytics-ndk/src/main/java/com/google/firebase/crashlytics/ndk/NdkCrashFilesManager.java
  firebase-crashlytics/firebase-crashlytics.gradle
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/CrashlyticsNativeComponentDeferredProxyTest.java
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/CrashlyticsTestCase.java
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/CrashlyticsControllerTest.java
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/CrashlyticsCoreInitializationTest.java
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/CrashlyticsCoreTest.java
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/MetaDataStoreTest.java
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/SessionReportingCoordinatorTest.java
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/log/LogFileManagerTest.java
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/persistence/CrashlyticsReportPersistenceTest.java
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/persistence/FileStoreImplTest.java
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/persistence/FileStoreTest.java
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/send/DataTransportCrashlyticsReportSenderTest.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/FirebaseCrashlytics.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/CrashlyticsNativeComponent.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/CrashlyticsNativeComponentDeferredProxy.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsController.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsCore.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsFileMarker.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsReportWithSessionId.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/MetaDataStore.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/SessionReportingCoordinator.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/log/LogFileManager.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/persistence/CrashlyticsReportPersistence.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/persistence/FileStore.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/persistence/FileStoreImpl.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/settings/CachedSettingsIo.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/settings/SettingsController.java
  firebase-crashlytics/src/test/java/com/google/firebase/crashlytics/internal/common/CrashlyticsControllerRobolectricTest.java
Labels: size/XXL, cla: yes

#3146 Fix messaging tests disabled in the move to GitHub.
  firebase-messaging/firebase-messaging.gradle
  firebase-messaging/src/test/AndroidManifest.xml
  firebase-messaging/src/test/java/com/google/firebase/iid/FirebaseInstanceIdWithFcmReceiverRoboTest.java
  firebase-messaging/src/test/java/com/google/firebase/messaging/CommonNotificationBuilderRoboTest.java
  firebase-messaging/src/test/java/com/google/firebase/messaging/DisplayNotificationRoboTest.java
  firebase-messaging/src/test/java/com/google/firebase/messaging/FirebaseMessagingRoboTest.java
  firebase-messaging/src/test/java/com/google/firebase/messaging/FirebaseMessagingServiceRoboTest.java
  firebase-messaging/src/test/java/com/google/firebase/messaging/MessagingAnalyticsRoboTest.java
  firebase-messaging/src/test/java/com/google/firebase/messaging/WakeLockHolderRoboTest.java
Labels: size/L, cla: yes

#3147 Make FieldIndex an AutoValue
  firebase-firestore/src/main/java/com/google/firebase/firestore/FirebaseFirestore.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/LocalSerializer.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteIndexManager.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/model/FieldIndex.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/core/TargetTest.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/IndexBackfillerTest.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/IndexingEnabledSQLiteLocalStoreTest.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/SQLiteIndexManagerTest.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/model/FieldIndexTest.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/model/TargetIndexMatcherTest.java
  firebase-firestore/src/testUtil/java/com/google/firebase/firestore/testutil/TestUtil.java
Labels: size/XL, cla: yes, api: firestore

#3145 Add API to filter overlays by batch ID
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/DocumentOverlayCache.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/LocalDocumentsView.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/MemoryDocumentOverlayCache.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteDocumentOverlayCache.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/DocumentOverlayCacheTestCase.java
Labels: size/M, cla: yes, api: firestore

#3152 Add more detailed tracing.
  firebase-common/src/main/java/com/google/firebase/FirebaseApp.java
  firebase-common/src/main/java/com/google/firebase/FirebaseOptions.java
  firebase-common/src/main/java/com/google/firebase/internal/ObfuscationUtils.java
  firebase-common/src/main/java/com/google/firebase/monitoring/ComponentMonitoring.java
  firebase-common/src/test/java/com/google/firebase/internal/ObfuscationUtilsTest.java
Labels: size/L, cla: yes

#3154 Update latest released version
  encoders/firebase-encoders-proto/gradle.properties
Labels: size/XS, cla: yes

#3138 Remove shared index entries
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteIndexManager.java
Labels: size/S, cla: yes, api: firestore

#3160 Fix Crashlytics user id serialization bug
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/MetaDataStore.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/persistence/CrashlyticsReportPersistence.java
Labels: size/XS, cla: yes

#3153 Store per-user state for indexes
  firebase-firestore/src/main/java/com/google/firebase/firestore/FirebaseFirestore.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/IndexBackfiller.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/IndexManager.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/IndexedQueryEngine.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/MemoryIndexManager.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/MemoryRemoteDocumentCache.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/RemoteDocumentCache.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteIndexManager.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteRemoteDocumentCache.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteSchema.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/model/FieldIndex.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/CountingQueryEngine.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/IndexBackfillerTest.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/IndexingEnabledSQLiteLocalStoreTest.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/RemoteDocumentCacheTestCase.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/SQLiteIndexManagerTest.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/SQLiteSchemaTest.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/model/FieldIndexTest.java
  firebase-firestore/src/testUtil/java/com/google/firebase/firestore/testutil/TestUtil.java
Labels: size/XL, cla: yes, api: firestore

#3165 Add transport version to user-agent.
  firebase-datatransport/src/main/java/com/google/firebase/datatransport/TransportRegistrar.java
Labels: size/XS, cla: yes

#3157 Don't initialize tracer until device is unlocked.
  firebase-common/src/main/java/com/google/firebase/FirebaseApp.java
  firebase-datatransport/src/main/java/com/google/firebase/datatransport/TransportRegistrar.java
Labels: size/S, cla: yes

#3132 Update document index entries
  firebase-firestore/src/main/java/com/google/firebase/firestore/index/IndexEntry.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/IndexManager.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/MemoryIndexManager.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteIndexManager.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteSchema.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/util/Util.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/IndexedQueryEngineTest.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/SQLiteIndexManagerTest.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/util/UtilTest.java
Labels: size/L, cla: yes

#3168 Remove unused IndexRange
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/IndexRange.java
Labels: size/M, cla: yes, api: firestore

#3179 Don't use JUnit's MultipleViolationsException.
  firebase-installations/firebase-installations.gradle
  firebase-installations/src/androidTest/java/com/google/firebase/installations/StrictModeTest.java
  integ-testing/src/main/java/com/google/firebase/testing/integ/MultipleViolationsException.java
  integ-testing/src/main/java/com/google/firebase/testing/integ/StrictModeRule.java
Labels: size/L, cla: yes

#3182 Fix perf's javadoc.
  firebase-perf/src/main/java/com/google/firebase/perf/application/AppStateUpdateHandler.java
Labels: size/XS, cla: yes

#3177 Synchronize old and new heartbeats
  firebase-common/src/main/java/com/google/firebase/FirebaseCommonRegistrar.java
  firebase-common/src/main/java/com/google/firebase/heartbeatinfo/DefaultHeartBeatController.java
  firebase-common/src/main/java/com/google/firebase/heartbeatinfo/DefaultHeartBeatInfo.java
  firebase-common/src/main/java/com/google/firebase/heartbeatinfo/HeartBeatInfoStorage.java
  firebase-common/src/test/java/com/google/firebase/heartbeatinfo/DefaultHeartBeatControllerTest.java
  firebase-common/src/test/java/com/google/firebase/heartbeatinfo/DefaultHeartBeatInfoTest.java
  firebase-common/src/test/java/com/google/firebase/heartbeatinfo/HeartBeatInfoStorageTest.java
Labels: size/L, cla: yes

#3169 Random changes for Indexing
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/IndexingTest.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/FirebaseFirestore.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/IndexBackfiller.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/LocalStore.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteSchema.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/IndexBackfillerTest.java
Labels: size/L, cla: yes, api: firestore

#3166 Guard mutable fields with synchronization blocks or methods
  firebase-app-distribution/src/main/java/com/google/firebase/app/distribution/FirebaseAppDistribution.java
  firebase-app-distribution/src/main/java/com/google/firebase/app/distribution/TesterSignInClient.java
  firebase-app-distribution/src/main/java/com/google/firebase/app/distribution/UpdateApkClient.java
Labels: size/L, cla: yes

#3178 Use collection_path + document_id in overlay table
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteDocumentOverlayCache.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteSchema.java
Labels: size/M, cla: yes

#3167 Fad removing update app functionality to firebaseAppDistribution class
  firebase-app-distribution/src/main/java/com/google/firebase/app/distribution/FirebaseAppDistribution.java
  firebase-app-distribution/src/main/java/com/google/firebase/app/distribution/UpdateAppClient.java
  firebase-app-distribution/src/test/java/com/google/firebase/app/distribution/FirebaseAppDistributionTest.java
  firebase-app-distribution/src/test/java/com/google/firebase/app/distribution/UpdateAabClientTest.java
  firebase-app-distribution/src/test/java/com/google/firebase/app/distribution/UpdateApkClientTest.java
  firebase-app-distribution/src/test/java/com/google/firebase/app/distribution/UpdateAppClientTest.java
Labels: size/L, cla: yes

#3190 Removing internal package
  firebase-app-distribution/src/main/java/com/google/firebase/app/distribution/AppDistributionReleaseInternal.java
  firebase-app-distribution/src/main/java/com/google/firebase/app/distribution/CheckForNewReleaseClient.java
  firebase-app-distribution/src/main/java/com/google/firebase/app/distribution/FirebaseAppDistribution.java
  firebase-app-distribution/src/main/java/com/google/firebase/app/distribution/FirebaseAppDistributionLifecycleNotifier.java
  firebase-app-distribution/src/main/java/com/google/firebase/app/distribution/FirebaseAppDistributionRegistrar.java
  firebase-app-distribution/src/main/java/com/google/firebase/app/distribution/FirebaseAppDistributionTesterApiClient.java
  firebase-app-distribution/src/main/java/com/google/firebase/app/distribution/InstallApkClient.java
  firebase-app-distribution/src/main/java/com/google/firebase/app/distribution/ReleaseIdentificationUtils.java
  firebase-app-distribution/src/main/java/com/google/firebase/app/distribution/ReleaseIdentifierStorage.java
  firebase-app-distribution/src/main/java/com/google/firebase/app/distribution/ReleaseUtils.java
  firebase-app-distribution/src/main/java/com/google/firebase/app/distribution/TesterSignInClient.java
  firebase-app-distribution/src/main/java/com/google/firebase/app/distribution/UpdateAabClient.java
  firebase-app-distribution/src/main/java/com/google/firebase/app/distribution/UpdateApkClient.java
  firebase-app-distribution/src/test/java/com/google/firebase/app/distribution/CheckForNewReleaseClientTest.java
  firebase-app-distribution/src/test/java/com/google/firebase/app/distribution/FirebaseAppDistributionTest.java
  firebase-app-distribution/src/test/java/com/google/firebase/app/distribution/FirebaseAppDistributionTesterApiClientTest.java
  firebase-app-distribution/src/test/java/com/google/firebase/app/distribution/InstallApkClientTests.java
  firebase-app-distribution/src/test/java/com/google/firebase/app/distribution/TesterSignInClientTest.java
  firebase-app-distribution/src/test/java/com/google/firebase/app/distribution/UpdateAabClientTest.java
  firebase-app-distribution/src/test/java/com/google/firebase/app/distribution/UpdateApkClientTest.java
Labels: size/M, cla: yes

#3195 Simplify MemoryRemoteDocumentCache
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/MemoryRemoteDocumentCache.java
Labels: size/S, cla: yes

#3194 Clean up RemoteDocumentCacheTestCase
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/RemoteDocumentCacheTestCase.java
Labels: size/M, cla: yes
