Repository firebase/firebase-android-sdk, pull requests merged in 2021-12, with the labels that each got.

#3191 [release-tagging] Fix git command to grant push permission on Prow
  buildSrc/src/main/java/com/google/firebase/gradle/bomgenerator/tagging/GitClient.java
Labels: size/XS, cla: yes

#3188 remove the ReleaseIdentifierStorage, rely on apk hash
  firebase-app-distribution/src/main/java/com/google/firebase/app/distribution/CheckForNewReleaseClient.java
  firebase-app-distribution/src/main/java/com/google/firebase/app/distribution/ReleaseIdentifierStorage.java
  firebase-app-distribution/src/main/java/com/google/firebase/app/distribution/UpdateApkClient.java
  firebase-app-distribution/src/test/java/com/google/firebase/app/distribution/CheckForNewReleaseClientTest.java
  firebase-app-distribution/src/test/java/com/google/firebase/app/distribution/UpdateApkClientTest.java
Labels: size/L, cla: yes

#3200 Update Python dependencies before running trigger_workflow script.
  .github/workflows/update-cpp-sdk-on-release.yml
Labels: size/XS, cla: yes

#3192 Use path length to skip scanning subcollections
  firebase-firestore/CHANGELOG.md
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/ConformanceTest.java
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/conformance/TestCaseConverter.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/DocumentReference.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/DocumentSnapshot.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/MemoryMutationQueue.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/MemoryRemoteDocumentCache.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteMutationQueue.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteRemoteDocumentCache.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteSchema.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/model/DocumentKey.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/SQLiteSchemaTest.java
  firebase-firestore/src/testUtil/java/com/google/firebase/firestore/testutil/TestUtil.java
Labels: size/L, cla: yes

#3112 Release Overlay
  firebase-firestore/CHANGELOG.md
  firebase-firestore/firebase-firestore.gradle
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/testutil/IntegrationTestUtil.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/LocalDocumentsView.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/Persistence.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteSchema.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/model/mutation/FieldMask.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/DocumentOverlayCacheTestCase.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/LocalStoreTestCase.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/MemoryLocalStoreTest.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/OverlayEnabledMemoryLocalStoreTest.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/OverlayEnabledSQLiteLocalStoreTest.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/QueryEngineTest.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/SQLiteLocalStoreTest.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/SQLiteOverlayMigrationManagerTest.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/SQLiteSchemaTest.java
Labels: size/L, cla: yes

#3206 Set DevelopmentPlatform info for Flutter apps
  firebase-crashlytics-ndk/src/main/java/com/google/firebase/crashlytics/ndk/CrashlyticsNdkRegistrar.java
  firebase-crashlytics-ndk/src/main/java/com/google/firebase/crashlytics/ndk/CrashpadController.java
  firebase-crashlytics/src/androidTest/assets/flutter_assets/NOTICES.Z
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/CrashlyticsNativeComponentDeferredProxyTest.java
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/DevelopmentPlatformProviderTest.java
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/CrashlyticsControllerTest.java
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/CrashlyticsCoreInitializationTest.java
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/CrashlyticsCoreTest.java
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/CrashlyticsReportDataCaptureTest.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/DevelopmentPlatformProvider.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/AppData.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsController.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsReportDataCapture.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/model/StaticSessionData.java
  firebase-crashlytics/src/test/java/com/google/firebase/crashlytics/internal/common/CrashlyticsControllerRobolectricTest.java
Labels: size/L, cla: yes

#3215 Increase minSdkVersion to 19 to match Google Play service's min version.
  firebase-messaging/firebase-messaging.gradle
  firebase-messaging/ktx/ktx.gradle
Labels: size/XS

#3218 Check for default FirebaseApp before logging to Scion.
  firebase-messaging/src/main/java/com/google/firebase/messaging/MessagingAnalytics.java
  firebase-messaging/src/test/java/com/google/firebase/messaging/MessagingAnalyticsRoboTest.java
Labels: size/S

#3219 Add second "*" to isNotificationDelegationEnabled() Javadoc.
  firebase-messaging/src/main/java/com/google/firebase/messaging/FirebaseMessaging.java
Labels: size/XS

#3198 remove heartbeat unused apis
  firebase-common/src/main/java/com/google/firebase/heartbeatinfo/DefaultHeartBeatInfo.java
  firebase-common/src/main/java/com/google/firebase/heartbeatinfo/HeartBeatInfo.java
  firebase-common/src/test/java/com/google/firebase/heartbeatinfo/DefaultHeartBeatInfoTest.java
  firebase-messaging/src/test/java/com/google/firebase/messaging/GmsRpcRoboTest.java
Labels: size/L, cla: yes

#3214 Add more tests to ComponentMonitoring.
  firebase-common/src/main/java/com/google/firebase/monitoring/ComponentMonitoring.java
  firebase-common/src/test/java/com/google/firebase/monitoring/ComponentMonitoringTest.java
  firebase-common/src/test/java/com/google/firebase/monitoring/DelegatingTracerTest.java
Labels: size/L

#3133 Fireperf: create an activity with fragments in `dev-app` for testing
  firebase-perf/dev-app/dev-app.gradle
  firebase-perf/dev-app/src/main/AndroidManifest.xml
  firebase-perf/dev-app/src/main/java/com/googletest/firebase/perf/testapp/FragmentActivity.java
  firebase-perf/dev-app/src/main/java/com/googletest/firebase/perf/testapp/ListAdapter.java
  firebase-perf/dev-app/src/main/java/com/googletest/firebase/perf/testapp/PerfTestActivity.java
  firebase-perf/dev-app/src/main/java/com/googletest/firebase/perf/testapp/SharedViewModel.java
  firebase-perf/dev-app/src/main/java/com/googletest/firebase/perf/testapp/ui/dashboard/DashboardFragment.java
  firebase-perf/dev-app/src/main/java/com/googletest/firebase/perf/testapp/ui/dashboard/DashboardViewModel.java
  firebase-perf/dev-app/src/main/java/com/googletest/firebase/perf/testapp/ui/home/HomeFragment.java
  firebase-perf/dev-app/src/main/java/com/googletest/firebase/perf/testapp/ui/home/HomeViewModel.java
  firebase-perf/dev-app/src/main/java/com/googletest/firebase/perf/testapp/ui/notifications/NotificationsFragment.java
  firebase-perf/dev-app/src/main/java/com/googletest/firebase/perf/testapp/ui/notifications/NotificationsViewModel.java
  firebase-perf/dev-app/src/main/res/drawable/ic_dashboard_black_24dp.xml
  firebase-perf/dev-app/src/main/res/drawable/ic_home_black_24dp.xml
  firebase-perf/dev-app/src/main/res/drawable/ic_notifications_black_24dp.xml
  firebase-perf/dev-app/src/main/res/layout/activity_fragment.xml
  firebase-perf/dev-app/src/main/res/layout/fragment_dashboard.xml
  firebase-perf/dev-app/src/main/res/layout/fragment_home.xml
  firebase-perf/dev-app/src/main/res/layout/fragment_notifications.xml
  firebase-perf/dev-app/src/main/res/layout/main_activity.xml
  firebase-perf/dev-app/src/main/res/layout/number_list_item.xml
  firebase-perf/dev-app/src/main/res/menu/bottom_nav_menu.xml
  firebase-perf/dev-app/src/main/res/menu/menu.xml
  firebase-perf/dev-app/src/main/res/navigation/mobile_navigation.xml
  firebase-perf/dev-app/src/main/res/values/dimens.xml
  firebase-perf/dev-app/src/main/res/values/strings.xml
Labels: size/XXL, cla: yes

#3211 Delete Overlay Flag
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/LocalDocumentsView.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/LocalStore.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/Persistence.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteOverlayMigrationManager.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteSchema.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/LocalStoreTestCase.java
Labels: size/L

#3201 Optimize query execution by deferring query evaluation
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/LocalDocumentsView.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/MemoryRemoteDocumentCache.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/RemoteDocumentCache.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteRemoteDocumentCache.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/model/MutableDocument.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/CountingQueryEngine.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/LocalStoreTestCase.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/RemoteDocumentCacheTestCase.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/SQLiteSchemaTest.java
Labels: size/L, cla: yes, api: firestore

#3208 Merge the Index Engines
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/remote/RemoteStoreTest.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/MemoryComponentProvider.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/DefaultQueryEngine.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/IndexedQueryEngine.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/LocalStore.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/QueryEngine.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteIndexManager.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/util/Util.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/CountingQueryEngine.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/IndexedQueryEngineTest.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/IndexingEnabledSQLiteLocalStoreTest.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/LocalStoreTestCase.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/QueryEngineTest.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/SQLiteOverlayMigrationManagerTest.java
  firebase-firestore/src/testUtil/java/com/google/firebase/firestore/testutil/TestUtil.java
Labels: size/XL, api: firestore

#3230 Delete unused IndexCursor
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/IndexCursor.java
Labels: api: firestore

#3229 Handle the case where a tester has access to 0 releases
  firebase-app-distribution/src/main/java/com/google/firebase/app/distribution/CheckForNewReleaseClient.java
  firebase-app-distribution/src/main/java/com/google/firebase/app/distribution/FirebaseAppDistributionTesterApiClient.java
  firebase-app-distribution/src/test/assets/testNoReleasesResponse.json
  firebase-app-distribution/src/test/java/com/google/firebase/app/distribution/FirebaseAppDistributionTesterApiClientTest.java
Labels: size/L

#3228 Fad cancel task when dialog closed
  firebase-app-distribution/src/main/java/com/google/firebase/app/distribution/FirebaseAppDistribution.java
  firebase-app-distribution/src/main/java/com/google/firebase/app/distribution/InstallActivity.java
  firebase-app-distribution/src/main/java/com/google/firebase/app/distribution/TesterSignInClient.java
  firebase-app-distribution/src/test/java/com/google/firebase/app/distribution/FirebaseAppDistributionTest.java
  firebase-app-distribution/src/test/java/com/google/firebase/app/distribution/TesterSignInClientTest.java
Labels: size/L

#3196 Audit of classes in firebase app distribution to minimize user access
  firebase-app-distribution/src/main/java/com/google/firebase/app/distribution/AppDistributionReleaseInternal.java
  firebase-app-distribution/src/main/java/com/google/firebase/app/distribution/InstallActivity.java
  firebase-app-distribution/src/main/java/com/google/firebase/app/distribution/LogWrapper.java
  firebase-app-distribution/src/main/java/com/google/firebase/app/distribution/ReleaseIdentificationUtils.java
  firebase-app-distribution/src/main/java/com/google/firebase/app/distribution/UpdateAabClient.java
  firebase-app-distribution/src/main/java/com/google/firebase/app/distribution/UpdateApkClient.java
  firebase-app-distribution/src/test/java/com/google/firebase/app/distribution/UpdateAabClientTest.java
Labels: size/M, cla: yes

#3222 Set fis as an unloader
  firebase-installations/src/main/java/com/google/firebase/installations/FirebaseInstallations.java
  firebase-installations/src/main/java/com/google/firebase/installations/FirebaseInstallationsRegistrar.java
  firebase-installations/src/main/java/com/google/firebase/installations/remote/FirebaseInstallationServiceClient.java
Labels: size/M

#3223 update resources
  firebase-messaging/src/main/res/values/strings.xml
Labels: size/XS

#3234 [test-infra] Fix release tagging implementation
  buildSrc/src/main/java/com/google/firebase/gradle/bomgenerator/tagging/GitClient.java
  buildSrc/src/main/java/com/google/firebase/gradle/bomgenerator/tagging/ShellExecutor.java
  buildSrc/src/test/kotlin/com/google/firebase/gradle/bomgenerator/tagging/GitClientTest.kt
Labels: size/M

#3176 String format with decimal issue in Android 8.1.0
  firebase-perf/src/main/java/com/google/firebase/perf/transport/TransportManager.java
Labels: size/XS, cla: yes

#3210 Perf e2e test app fragments
  firebase-perf/e2e-app/e2e-app.gradle
  firebase-perf/e2e-app/src/androidTest/java/com/google/firebase/testing/fireperf/FirebasePerformanceFragmentScreenTracesTest.java
  firebase-perf/e2e-app/src/androidTest/java/com/google/firebase/testing/fireperf/FirebasePerformanceScreenTracesTest.java
  firebase-perf/e2e-app/src/main/AndroidManifest.xml
  firebase-perf/e2e-app/src/main/java/com/google/firebase/testing/fireperf/FirebasePerfScreenTracesActivity.java
  firebase-perf/e2e-app/src/main/java/com/google/firebase/testing/fireperf/FragmentActivity.java
  firebase-perf/e2e-app/src/main/java/com/google/firebase/testing/fireperf/ListAdapter.java
  firebase-perf/e2e-app/src/main/java/com/google/firebase/testing/fireperf/SlowListAdapter.java
  firebase-perf/e2e-app/src/main/java/com/google/firebase/testing/fireperf/ui/fast/FastFragment.java
  firebase-perf/e2e-app/src/main/java/com/google/firebase/testing/fireperf/ui/fast/FastViewModel.java
  firebase-perf/e2e-app/src/main/java/com/google/firebase/testing/fireperf/ui/home/HomeFragment.java
  firebase-perf/e2e-app/src/main/java/com/google/firebase/testing/fireperf/ui/home/HomeViewModel.java
  firebase-perf/e2e-app/src/main/java/com/google/firebase/testing/fireperf/ui/slow/SlowFragment.java
  firebase-perf/e2e-app/src/main/java/com/google/firebase/testing/fireperf/ui/slow/SlowViewModel.java
  firebase-perf/e2e-app/src/main/res/drawable/ic_dashboard_black_24dp.xml
  firebase-perf/e2e-app/src/main/res/drawable/ic_home_black_24dp.xml
  firebase-perf/e2e-app/src/main/res/drawable/ic_notifications_black_24dp.xml
  firebase-perf/e2e-app/src/main/res/layout/activity_fragment.xml
  firebase-perf/e2e-app/src/main/res/layout/fragment_fast.xml
  firebase-perf/e2e-app/src/main/res/layout/fragment_home.xml
  firebase-perf/e2e-app/src/main/res/layout/fragment_slow.xml
  firebase-perf/e2e-app/src/main/res/menu/bottom_nav_menu.xml
  firebase-perf/e2e-app/src/main/res/navigation/mobile_navigation.xml
  firebase-perf/e2e-app/src/main/res/values/dimens.xml
  firebase-perf/e2e-app/src/main/res/values/strings.xml
Labels: size/XL

#3235 Audit of classes making classes as private as possible
  firebase-app-distribution/api.txt
  firebase-app-distribution/ktx/api.txt
  firebase-app-distribution/src/main/AndroidManifest.xml
  firebase-app-distribution/src/main/java/com/google/firebase/app/distribution/AppDistributionRelease.java
  firebase-app-distribution/src/main/java/com/google/firebase/app/distribution/CheckForNewReleaseClient.java
  firebase-app-distribution/src/main/java/com/google/firebase/app/distribution/FirebaseAppDistribution.java
  firebase-app-distribution/src/main/java/com/google/firebase/app/distribution/FirebaseAppDistributionException.java
  firebase-app-distribution/src/main/java/com/google/firebase/app/distribution/FirebaseAppDistributionLifecycleNotifier.java
  firebase-app-distribution/src/main/java/com/google/firebase/app/distribution/FirebaseAppDistributionNotificationsManager.java
  firebase-app-distribution/src/main/java/com/google/firebase/app/distribution/FirebaseAppDistributionRegistrar.java
  firebase-app-distribution/src/main/java/com/google/firebase/app/distribution/FirebaseAppDistributionTesterApiClient.java
  firebase-app-distribution/src/main/java/com/google/firebase/app/distribution/InstallApkClient.java
  firebase-app-distribution/src/main/java/com/google/firebase/app/distribution/ReleaseIdentificationUtils.java
  firebase-app-distribution/src/main/java/com/google/firebase/app/distribution/TaskUtils.java
  firebase-app-distribution/src/main/java/com/google/firebase/app/distribution/TesterSignInClient.java
  firebase-app-distribution/src/main/java/com/google/firebase/app/distribution/UpdateAabClient.java
  firebase-app-distribution/src/main/java/com/google/firebase/app/distribution/UpdateApkClient.java
  firebase-app-distribution/src/main/java/com/google/firebase/app/distribution/UpdateProgress.java
  firebase-app-distribution/src/main/java/com/google/firebase/app/distribution/internal/FirebaseAppDistributionFileProvider.java
  firebase-app-distribution/src/main/java/com/google/firebase/app/distribution/internal/InstallActivity.java
  firebase-app-distribution/src/main/java/com/google/firebase/app/distribution/internal/LogWrapper.java
  firebase-app-distribution/src/main/java/com/google/firebase/app/distribution/internal/SignInResultActivity.java
  firebase-app-distribution/src/main/java/com/google/firebase/app/distribution/internal/SignInStorage.java
  firebase-app-distribution/src/main/java/com/google/firebase/app/distribution/internal/package-info.java
  firebase-app-distribution/src/test/java/com/google/firebase/app/distribution/FirebaseAppDistributionTest.java
  firebase-app-distribution/src/test/java/com/google/firebase/app/distribution/InstallApkClientTests.java
  firebase-app-distribution/src/test/java/com/google/firebase/app/distribution/TesterSignInClientTest.java
Labels: size/L

#3237 Create firestore/Filter.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/Filter.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/Query.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/bundle/BundleSerializer.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/FieldFilter.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/Filter.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/Query.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/Target.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteIndexManager.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/model/TargetIndexMatcher.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/remote/RemoteSerializer.java
  firebase-firestore/src/testUtil/java/com/google/firebase/firestore/testutil/TestUtil.java
Labels: size/XL

#3247 Fix Typo
  firebase-firestore/src/main/java/com/google/firebase/firestore/index/OrderedCodeWriter.java
Labels: size/XS, api: firestore

#3252 Remove support for multiple sdk instances in Firebase App Distribution
  firebase-app-distribution/api.txt
  firebase-app-distribution/ktx/api.txt
  firebase-app-distribution/ktx/src/androidTest/kotlin/com/google/firebase/app/distribution/ktx/FirebaseAppDistributionTests.kt
  firebase-app-distribution/ktx/src/main/kotlin/com/google/firebase/app/distribution/ktx/FirebaseAppDistribution.kt
  firebase-app-distribution/src/main/java/com/google/firebase/app/distribution/FirebaseAppDistribution.java
Labels: size/S

#3256 Removing androidX=true from gradle.properties
  firebase-app-distribution/gradle.properties
Labels: size/XS

#3253 Clean up executors and add clarifying comments
  firebase-app-distribution/src/main/java/com/google/firebase/app/distribution/CheckForNewReleaseClient.java
  firebase-app-distribution/src/main/java/com/google/firebase/app/distribution/UpdateAabClient.java
  firebase-app-distribution/src/main/java/com/google/firebase/app/distribution/UpdateApkClient.java
  firebase-app-distribution/src/test/java/com/google/firebase/app/distribution/UpdateAabClientTest.java
Labels: size/L

#3255 Rename *Client classes that have business logic
  firebase-app-distribution/src/main/java/com/google/firebase/app/distribution/AabUpdater.java
  firebase-app-distribution/src/main/java/com/google/firebase/app/distribution/ApkInstaller.java
  firebase-app-distribution/src/main/java/com/google/firebase/app/distribution/ApkUpdater.java
  firebase-app-distribution/src/main/java/com/google/firebase/app/distribution/FirebaseAppDistribution.java
  firebase-app-distribution/src/main/java/com/google/firebase/app/distribution/NewReleaseFetcher.java
  firebase-app-distribution/src/main/java/com/google/firebase/app/distribution/TesterSignInManager.java
  firebase-app-distribution/src/main/java/com/google/firebase/app/distribution/internal/InstallActivity.java
  firebase-app-distribution/src/test/java/com/google/firebase/app/distribution/AabUpdaterTest.java
  firebase-app-distribution/src/test/java/com/google/firebase/app/distribution/ApkInstallerTests.java
  firebase-app-distribution/src/test/java/com/google/firebase/app/distribution/ApkUpdaterTest.java
  firebase-app-distribution/src/test/java/com/google/firebase/app/distribution/FirebaseAppDistributionTest.java
  firebase-app-distribution/src/test/java/com/google/firebase/app/distribution/NewReleaseFetcherTest.java
  firebase-app-distribution/src/test/java/com/google/firebase/app/distribution/TesterSignInManagerTest.java
Labels: size/L

#3254 Crashlytics efficient keys
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/CrashlyticsControllerTest.java
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/CrashlyticsCoreTest.java
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/SessionReportingCoordinatorTest.java
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/metadata/LogFileManagerTest.java
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/metadata/MetaDataStoreTest.java
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/persistence/CrashlyticsReportPersistenceTest.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CommonUtils.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsBackgroundWorker.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsController.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsCore.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/SessionReportingCoordinator.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/UserMetadata.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/metadata/FileLogStore.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/metadata/KeysMap.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/metadata/LogFileManager.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/metadata/MetaDataStore.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/metadata/QueueFile.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/metadata/QueueFileLogStore.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/metadata/UserMetadata.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/metadata/package-info.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/persistence/CrashlyticsReportPersistence.java
  firebase-crashlytics/src/test/java/com/google/firebase/crashlytics/internal/common/CrashlyticsControllerRobolectricTest.java
  firebase-crashlytics/src/test/java/com/google/firebase/crashlytics/internal/common/SessionReportingCoordinatorRobolectricTest.java
Labels: size/XL

#3261 Include internal keys even if no custom keys were set.
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/SessionReportingCoordinatorTest.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/SessionReportingCoordinator.java
Labels: size/M

#3259 New build version now includes different version name
  firebase-app-distribution/src/main/java/com/google/firebase/app/distribution/NewReleaseFetcher.java
  firebase-app-distribution/src/test/java/com/google/firebase/app/distribution/NewReleaseFetcherTest.java
Labels: size/M

#3257 docs: improve documentation for merge behavior
  firebase-firestore/src/main/java/com/google/firebase/firestore/SetOptions.java
Labels: size/XS, api: firestore

#3262 Adding clear task flag to fix update app bug
  firebase-app-distribution/src/main/java/com/google/firebase/app/distribution/internal/InstallActivity.java
Labels: size/XS

#3274 Refactor notification tests to be more focused to the classes under test
  firebase-app-distribution/src/main/java/com/google/firebase/app/distribution/ApkUpdater.java
  firebase-app-distribution/src/main/java/com/google/firebase/app/distribution/AppIconSource.java
  firebase-app-distribution/src/main/java/com/google/firebase/app/distribution/FirebaseAppDistributionNotificationsManager.java
  firebase-app-distribution/src/test/java/com/google/firebase/app/distribution/ApkUpdaterTest.java
  firebase-app-distribution/src/test/java/com/google/firebase/app/distribution/AppIconSourceTest.java
  firebase-app-distribution/src/test/java/com/google/firebase/app/distribution/FirebaseAppDistributionNotificationsManagerTest.java
  firebase-app-distribution/src/test/java/com/google/firebase/app/distribution/FirebaseAppDistributionTest.java
Labels: size/XL

#3263 Improve error handling around downloading and installing
  firebase-app-distribution/src/main/java/com/google/firebase/app/distribution/AabUpdater.java
  firebase-app-distribution/src/main/java/com/google/firebase/app/distribution/ApkUpdater.java
  firebase-app-distribution/src/main/java/com/google/firebase/app/distribution/FirebaseAppDistributionTesterApiClient.java
  firebase-app-distribution/src/main/java/com/google/firebase/app/distribution/HttpsUrlConnectionFactory.java
  firebase-app-distribution/src/main/java/com/google/firebase/app/distribution/internal/InstallActivity.java
  firebase-app-distribution/src/test/java/com/google/firebase/app/distribution/AabUpdaterTest.java
  firebase-app-distribution/src/test/java/com/google/firebase/app/distribution/ApkUpdaterTest.java
  firebase-app-distribution/src/test/java/com/google/firebase/app/distribution/NewReleaseFetcherTest.java
Labels: size/XL

#3272 Making firebase installations lazy to initialize
  firebase-app-distribution/firebase-app-distribution.gradle
  firebase-app-distribution/src/main/java/com/google/firebase/app/distribution/FirebaseAppDistribution.java
  firebase-app-distribution/src/main/java/com/google/firebase/app/distribution/FirebaseAppDistributionRegistrar.java
  firebase-app-distribution/src/main/java/com/google/firebase/app/distribution/NewReleaseFetcher.java
  firebase-app-distribution/src/main/java/com/google/firebase/app/distribution/TesterSignInManager.java
  firebase-app-distribution/src/test/java/com/google/firebase/app/distribution/NewReleaseFetcherTest.java
  firebase-app-distribution/src/test/java/com/google/firebase/app/distribution/TesterSignInManagerTest.java
Labels: size/M

#3278 Improve error handling in some more classes
  firebase-app-distribution/src/main/java/com/google/firebase/app/distribution/FirebaseAppDistributionNotificationsManager.java
  firebase-app-distribution/src/main/java/com/google/firebase/app/distribution/FirebaseAppDistributionRegistrar.java
  firebase-app-distribution/src/main/java/com/google/firebase/app/distribution/FirebaseAppDistributionTesterApiClient.java
  firebase-app-distribution/src/main/java/com/google/firebase/app/distribution/NewReleaseFetcher.java
  firebase-app-distribution/src/test/java/com/google/firebase/app/distribution/AabUpdaterTest.java
  firebase-app-distribution/src/test/java/com/google/firebase/app/distribution/ApkUpdaterTest.java
  firebase-app-distribution/src/test/java/com/google/firebase/app/distribution/FirebaseAppDistributionTesterApiClientTest.java
Labels: size/L

#3280 Remove some TODOs
  firebase-app-distribution/src/main/java/com/google/firebase/app/distribution/ApkUpdater.java
  firebase-app-distribution/src/test/java/com/google/firebase/app/distribution/ApkUpdaterTest.java
Labels: size/XS

#3281 Close input stream when fetching new releases
  firebase-app-distribution/src/main/java/com/google/firebase/app/distribution/FirebaseAppDistributionTesterApiClient.java
Labels: size/S

#3282 Close input stream in AabUpdater
  firebase-app-distribution/src/main/java/com/google/firebase/app/distribution/AabUpdater.java
Labels: size/S
