Repository firebase/firebase-android-sdk, pull requests merged in 2021-03, with the labels that each got.

#2473 Don't use Apache Ant in tests
  firebase-firestore/src/test/java/com/google/firebase/firestore/spec/SpecTestCase.java
Labels: api: firestore, cla: yes, size/XS

#2467 Add @Singleton annotation to FirebasePerformance class and component.
  firebase-perf/src/main/java/com/google/firebase/perf/FirebasePerformance.java
  firebase-perf/src/main/java/com/google/firebase/perf/injection/components/FirebasePerformanceComponent.java
Labels: cla: yes, size/XS

#2418 Make Auth an deferred dependency
  firebase-database/firebase-database.gradle
  firebase-database/src/androidTest/java/com/google/firebase/database/IntegrationTestHelpers.java
  firebase-database/src/main/java/com/google/firebase/database/DatabaseRegistrar.java
  firebase-database/src/main/java/com/google/firebase/database/FirebaseDatabaseComponent.java
  firebase-database/src/main/java/com/google/firebase/database/android/AndroidAuthTokenProvider.java
  firebase-database/src/test/java/com/google/firebase/database/UnitTestHelpers.java
Labels: api: database, cla: yes, size/L

#2459 Update perf plugin version to 1.3.5.
  buildSrc/build.gradle
Labels: cla: yes, size/XS

#2474 Making GaugeMetadataManager class DI compatible.
  firebase-perf/src/main/java/com/google/firebase/perf/gauges/GaugeModule.java
  firebase-perf/src/main/java/com/google/firebase/perf/injection/components/FirebasePerformanceComponent.java
  firebase-perf/src/main/java/com/google/firebase/perf/injection/modules/FirebasePerformanceModule.java
  firebase-perf/src/main/java/com/google/firebase/perf/internal/GaugeManager.java
  firebase-perf/src/main/java/com/google/firebase/perf/internal/GaugeMetadataManager.java
  firebase-perf/src/test/java/com/google/firebase/perf/internal/GaugeManagerTest.java
  firebase-perf/src/test/java/com/google/firebase/perf/internal/GaugeMetadataManagerTest.java
Labels: cla: yes, size/L

#2483 update database versions
  firebase-database/gradle.properties
Labels: cla: yes, size/XS

#2491 Update RTDB docs
  firebase-database/src/main/java/com/google/firebase/database/Query.java
Labels: cla: yes, size/L

#2492 Update Javadoc for FirebaseCrashlytics.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/CustomKeysAndValues.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/FirebaseCrashlytics.java
Labels: cla: yes, size/XS

#2496 update versions
  firebase-crashlytics-ndk/gradle.properties
  firebase-crashlytics/gradle.properties
Labels: cla: yes, size/XS

#2493 Key key -> key
  firebase-database/src/main/java/com/google/firebase/database/Query.java
Labels: api: database, cla: yes, size/XS

#2494 Remove test duplication
  firebase-firestore/src/test/java/com/google/firebase/firestore/model/MutableObjectValueTest.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/model/ObjectValueTest.java
Labels: cla: yes, size/L

#2476 Report the correct number of totalBytes for resumed downloads
  firebase-storage/CHANGELOG.md
  firebase-storage/src/main/java/com/google/firebase/storage/FileDownloadTask.java
  firebase-storage/src/main/java/com/google/firebase/storage/StreamDownloadTask.java
  firebase-storage/src/test/resources/activitylogs/emptyDownload_task.txt
  firebase-storage/src/test/resources/activitylogs/emptyStreamDownload_background.txt
  firebase-storage/src/test/resources/activitylogs/emptyStreamDownload_task.txt
  firebase-storage/src/test/resources/activitylogs/fileDownloadCanceled_task.txt
  firebase-storage/src/test/resources/activitylogs/fileDownloadResume_task.txt
  firebase-storage/src/test/resources/activitylogs/fileDownload_task.txt
  firebase-storage/src/test/resources/activitylogs/streamDownloadCanceled_task.txt
  firebase-storage/src/test/resources/activitylogs/streamDownloadWithETagChange_background.txt
  firebase-storage/src/test/resources/activitylogs/streamDownloadWithETagChange_task.txt
  firebase-storage/src/test/resources/activitylogs/streamDownloadWithResumeAndCancel_background.txt
  firebase-storage/src/test/resources/activitylogs/streamDownloadWithResumeAndCancel_task.txt
  firebase-storage/src/test/resources/activitylogs/streamDownloadWithResume_background.txt
  firebase-storage/src/test/resources/activitylogs/streamDownloadWithResume_task.txt
  firebase-storage/src/test/resources/activitylogs/streamDownload_background.txt
  firebase-storage/src/test/resources/activitylogs/streamDownload_task.txt
  firebase-storage/src/testUtil/java/com/google/firebase/storage/TestDownloadHelper.java
Labels: api: storage, cla: yes, size/M

#2498 Fix typo: "22.10" -> "22.1.0"
  firebase-firestore/CHANGELOG.md
Labels: cla: yes, size/S

#2501 Fix "Invalid File Descriptor" warnings when building crashlytics-ndk
  firebase-crashlytics-ndk/firebase-crashlytics-ndk.gradle
Labels: cla: yes, size/XS

#2504 Handle exception when registering too many receivers in Crashlytics.
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/BatteryStateTest.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/BatteryState.java
Labels: cla: yes, size/S

#2515 Make the Crashlytics isEmulator check much more robust.
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CommonUtils.java
Labels: cla: yes, size/XS

#2508 Cleanup the confusing log message
  firebase-perf/src/main/java/com/google/firebase/perf/config/ConfigResolver.java
Labels: cla: yes, size/XS

#2507 Fix test failures from internal presubmit
  firebase-firestore/src/test/java/com/google/firebase/firestore/LoadBundleTaskTest.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/spec/SpecTestCase.java
Labels: cla: yes, size/S

#2522 Moved RemoteConfig class to the Config package.
  firebase-perf/src/main/java/com/google/firebase/perf/FirebasePerformance.java
  firebase-perf/src/main/java/com/google/firebase/perf/config/ConfigResolver.java
  firebase-perf/src/main/java/com/google/firebase/perf/config/RemoteConfigManager.java
  firebase-perf/src/main/java/com/google/firebase/perf/injection/modules/FirebasePerformanceModule.java
  firebase-perf/src/test/java/com/google/firebase/perf/FirebasePerformanceTest.java
  firebase-perf/src/test/java/com/google/firebase/perf/config/ConfigResolverTest.java
  firebase-perf/src/test/java/com/google/firebase/perf/config/RemoteConfigManagerTest.java
Labels: cla: yes, size/S

#2523 Move Validators classes to its own package.
  firebase-perf/src/main/java/com/google/firebase/perf/FirebasePerformance.java
  firebase-perf/src/main/java/com/google/firebase/perf/metrics/HttpMetric.java
  firebase-perf/src/main/java/com/google/firebase/perf/metrics/Trace.java
  firebase-perf/src/main/java/com/google/firebase/perf/metrics/validator/FirebasePerfApplicationInfoValidator.java
  firebase-perf/src/main/java/com/google/firebase/perf/metrics/validator/FirebasePerfGaugeMetricValidator.java
  firebase-perf/src/main/java/com/google/firebase/perf/metrics/validator/FirebasePerfNetworkValidator.java
  firebase-perf/src/main/java/com/google/firebase/perf/metrics/validator/FirebasePerfTraceValidator.java
  firebase-perf/src/main/java/com/google/firebase/perf/metrics/validator/PerfMetricValidator.java
  firebase-perf/src/main/java/com/google/firebase/perf/metrics/validator/package-info.java
  firebase-perf/src/main/java/com/google/firebase/perf/transport/TransportManager.java
  firebase-perf/src/test/java/com/google/firebase/perf/metrics/validator/FirebasePerfApplicationInfoValidatorTest.java
  firebase-perf/src/test/java/com/google/firebase/perf/metrics/validator/FirebasePerfGaugeManagerValidatorTest.java
  firebase-perf/src/test/java/com/google/firebase/perf/metrics/validator/FirebasePerfNetworkValidatorTest.java
  firebase-perf/src/test/java/com/google/firebase/perf/metrics/validator/FirebasePerfTraceValidatorTest.java
Labels: cla: yes, size/L

#2526 Move the NetworkRequestBuilder package inside metrics to unify the builders
  firebase-perf/src/main/java/com/google/firebase/perf/impl/package-info.java
  firebase-perf/src/main/java/com/google/firebase/perf/metrics/HttpMetric.java
  firebase-perf/src/main/java/com/google/firebase/perf/metrics/NetworkRequestMetricBuilder.java
  firebase-perf/src/main/java/com/google/firebase/perf/network/FirebasePerfHttpClient.java
  firebase-perf/src/main/java/com/google/firebase/perf/network/FirebasePerfOkHttpClient.java
  firebase-perf/src/main/java/com/google/firebase/perf/network/FirebasePerfUrlConnection.java
  firebase-perf/src/main/java/com/google/firebase/perf/network/InstrHttpInputStream.java
  firebase-perf/src/main/java/com/google/firebase/perf/network/InstrHttpOutputStream.java
  firebase-perf/src/main/java/com/google/firebase/perf/network/InstrHttpURLConnection.java
  firebase-perf/src/main/java/com/google/firebase/perf/network/InstrHttpsURLConnection.java
  firebase-perf/src/main/java/com/google/firebase/perf/network/InstrURLConnectionBase.java
  firebase-perf/src/main/java/com/google/firebase/perf/network/InstrumentApacheHttpResponseHandler.java
  firebase-perf/src/main/java/com/google/firebase/perf/network/InstrumentOkHttpEnqueueCallback.java
  firebase-perf/src/main/java/com/google/firebase/perf/network/NetworkRequestMetricBuilderUtil.java
  firebase-perf/src/test/java/com/google/firebase/perf/internal/AppStateMonitorTest.java
  firebase-perf/src/test/java/com/google/firebase/perf/metrics/NetworkRequestMetricBuilderTest.java
  firebase-perf/src/test/java/com/google/firebase/perf/metrics/validator/FirebasePerfNetworkValidatorTest.java
  firebase-perf/src/test/java/com/google/firebase/perf/network/FirebasePerfOkHttpClientTest.java
  firebase-perf/src/test/java/com/google/firebase/perf/network/InstrHttpInputStreamTest.java
  firebase-perf/src/test/java/com/google/firebase/perf/network/InstrHttpOutputStreamTest.java
  firebase-perf/src/test/java/com/google/firebase/perf/network/InstrHttpURLConnectionTest.java
  firebase-perf/src/test/java/com/google/firebase/perf/network/InstrHttpsURLConnectionTest.java
  firebase-perf/src/test/java/com/google/firebase/perf/network/InstrURLConnectionBaseTest.java
  firebase-perf/src/test/java/com/google/firebase/perf/network/InstrumentApacheHttpResponseHandlerTest.java
Labels: cla: yes, size/M

#2528 Codegen improvements
  encoders/protoc-gen-firebase-encoders/src/main/kotlin/com/google/firebase/encoders/proto/codegen/CodeGenerator.kt
  encoders/protoc-gen-firebase-encoders/tests/code-gen-cfg.textproto
  encoders/protoc-gen-firebase-encoders/tests/src/test/java/com/google/firebase/testing/e2e/CodeGenTests.java
  encoders/protoc-gen-firebase-encoders/tests/src/test/proto/cycle.proto
  encoders/protoc-gen-firebase-encoders/tests/src/test/proto/simple.proto
  encoders/protoc-gen-firebase-encoders/tests/src/test/proto/types.proto
Labels: cla: yes, size/M

#2527 Create a separate package for Application Handlers
  firebase-perf/ktx/src/test/kotlin/com/google/firebase/perf/ktx/PerformanceTests.kt
  firebase-perf/src/main/java/com/google/firebase/perf/application/AppStateMonitor.java
  firebase-perf/src/main/java/com/google/firebase/perf/application/AppStateUpdateHandler.java
  firebase-perf/src/main/java/com/google/firebase/perf/application/package-info.java
  firebase-perf/src/main/java/com/google/firebase/perf/internal/SessionManager.java
  firebase-perf/src/main/java/com/google/firebase/perf/metrics/NetworkRequestMetricBuilder.java
  firebase-perf/src/main/java/com/google/firebase/perf/metrics/Trace.java
  firebase-perf/src/main/java/com/google/firebase/perf/metrics/resource/ResourceType.java
  firebase-perf/src/main/java/com/google/firebase/perf/metrics/resource/package-info.java
  firebase-perf/src/main/java/com/google/firebase/perf/provider/FirebasePerfProvider.java
  firebase-perf/src/main/java/com/google/firebase/perf/transport/RateLimiter.java
  firebase-perf/src/main/java/com/google/firebase/perf/transport/TransportManager.java
  firebase-perf/src/test/java/com/google/firebase/perf/application/AppStateMonitorTest.java
  firebase-perf/src/test/java/com/google/firebase/perf/internal/SessionManagerTest.java
  firebase-perf/src/test/java/com/google/firebase/perf/metrics/NetworkRequestMetricBuilderTest.java
  firebase-perf/src/test/java/com/google/firebase/perf/metrics/TraceMetricBuilderTest.java
  firebase-perf/src/test/java/com/google/firebase/perf/metrics/TraceTest.java
  firebase-perf/src/test/java/com/google/firebase/perf/metrics/validator/FirebasePerfTraceValidatorTest.java
  firebase-perf/src/test/java/com/google/firebase/perf/transport/RateLimiterTest.java
  firebase-perf/src/test/java/com/google/firebase/perf/transport/TransportManagerTest.java
Labels: cla: yes, size/L

#2529 Organize the session package to be self contained.
  firebase-perf/src/main/java/com/google/firebase/perf/FirebasePerformance.java
  firebase-perf/src/main/java/com/google/firebase/perf/application/AppStateMonitor.java
  firebase-perf/src/main/java/com/google/firebase/perf/injection/modules/FirebasePerformanceModule.java
  firebase-perf/src/main/java/com/google/firebase/perf/metrics/AppStartTrace.java
  firebase-perf/src/main/java/com/google/firebase/perf/metrics/NetworkRequestMetricBuilder.java
  firebase-perf/src/main/java/com/google/firebase/perf/metrics/Trace.java
  firebase-perf/src/main/java/com/google/firebase/perf/metrics/TraceMetricBuilder.java
  firebase-perf/src/main/java/com/google/firebase/perf/provider/FirebasePerfProvider.java
  firebase-perf/src/main/java/com/google/firebase/perf/session/GaugeManager.java
  firebase-perf/src/main/java/com/google/firebase/perf/session/GaugeMetadataManager.java
  firebase-perf/src/main/java/com/google/firebase/perf/session/PerfSession.java
  firebase-perf/src/main/java/com/google/firebase/perf/session/SessionAwareObject.java
  firebase-perf/src/main/java/com/google/firebase/perf/session/SessionManager.java
  firebase-perf/src/main/java/com/google/firebase/perf/session/collectors/CpuGaugeCollector.java
  firebase-perf/src/main/java/com/google/firebase/perf/session/collectors/MemoryGaugeCollector.java
  firebase-perf/src/main/java/com/google/firebase/perf/session/package-info.java
  firebase-perf/src/main/java/com/google/firebase/perf/transport/TransportManager.java
  firebase-perf/src/test/java/com/google/firebase/perf/FirebasePerformanceTest.java
  firebase-perf/src/test/java/com/google/firebase/perf/FirebasePerformanceTestBase.java
  firebase-perf/src/test/java/com/google/firebase/perf/application/AppStateMonitorTest.java
  firebase-perf/src/test/java/com/google/firebase/perf/metrics/AppStartTraceTest.java
  firebase-perf/src/test/java/com/google/firebase/perf/metrics/NetworkRequestMetricBuilderTest.java
  firebase-perf/src/test/java/com/google/firebase/perf/metrics/TraceTest.java
  firebase-perf/src/test/java/com/google/firebase/perf/session/GaugeManagerTest.java
  firebase-perf/src/test/java/com/google/firebase/perf/session/GaugeMetadataManagerTest.java
  firebase-perf/src/test/java/com/google/firebase/perf/session/PerfSessionTest.java
  firebase-perf/src/test/java/com/google/firebase/perf/session/SessionManagerTest.java
  firebase-perf/src/test/java/com/google/firebase/perf/session/collectors/CpuGaugeCollectorTest.java
  firebase-perf/src/test/java/com/google/firebase/perf/session/collectors/MemoryGaugeCollectorTest.java
  firebase-perf/src/test/java/com/google/firebase/perf/transport/TransportManagerTest.java
Labels: cla: yes, size/L

#2524 Make ABT Dynamic-Module compliant.
  firebase-abt/src/main/java/com/google/firebase/abt/FirebaseABTesting.java
  firebase-abt/src/main/java/com/google/firebase/abt/component/AbtComponent.java
  firebase-abt/src/main/java/com/google/firebase/abt/component/AbtRegistrar.java
  firebase-abt/src/test/java/com/google/firebase/abt/FirebaseABTestingTest.java
  tools/lint/src/main/kotlin/ProviderAssignmentDetector.kt
  tools/lint/src/test/kotlin/ProviderAssignmentDetectorTests.kt
Labels: cla: yes, size/M

#2525 Allow provider assignment from `@DeferredApi` methods.
  tools/lint/src/main/kotlin/Annotations.kt
  tools/lint/src/main/kotlin/DeferredApiDetector.kt
  tools/lint/src/main/kotlin/ProviderAssignmentDetector.kt
  tools/lint/src/test/kotlin/DeferredApiDetectorTests.kt
  tools/lint/src/test/kotlin/ProviderAssignmentDetectorTests.kt
Labels: cla: yes, size/L

#2534 Move all the gauges related classes to its own package.
  firebase-perf/src/main/java/com/google/firebase/perf/FirebasePerformance.java
  firebase-perf/src/main/java/com/google/firebase/perf/injection/modules/FirebasePerformanceModule.java
  firebase-perf/src/main/java/com/google/firebase/perf/metrics/NetworkRequestMetricBuilder.java
  firebase-perf/src/main/java/com/google/firebase/perf/metrics/Trace.java
  firebase-perf/src/main/java/com/google/firebase/perf/session/SessionManager.java
  firebase-perf/src/main/java/com/google/firebase/perf/session/gauges/CpuGaugeCollector.java
  firebase-perf/src/main/java/com/google/firebase/perf/session/gauges/GaugeManager.java
  firebase-perf/src/main/java/com/google/firebase/perf/session/gauges/GaugeMetadataManager.java
  firebase-perf/src/main/java/com/google/firebase/perf/session/gauges/MemoryGaugeCollector.java
  firebase-perf/src/main/java/com/google/firebase/perf/session/gauges/package-info.java
  firebase-perf/src/test/java/com/google/firebase/perf/FirebasePerformanceTest.java
  firebase-perf/src/test/java/com/google/firebase/perf/application/AppStateMonitorTest.java
  firebase-perf/src/test/java/com/google/firebase/perf/metrics/NetworkRequestMetricBuilderTest.java
  firebase-perf/src/test/java/com/google/firebase/perf/metrics/TraceTest.java
  firebase-perf/src/test/java/com/google/firebase/perf/session/SessionManagerTest.java
  firebase-perf/src/test/java/com/google/firebase/perf/session/gauges/CpuGaugeCollectorTest.java
  firebase-perf/src/test/java/com/google/firebase/perf/session/gauges/GaugeManagerTest.java
  firebase-perf/src/test/java/com/google/firebase/perf/session/gauges/GaugeMetadataManagerTest.java
  firebase-perf/src/test/java/com/google/firebase/perf/session/gauges/MemoryGaugeCollectorTest.java
Labels: cla: yes, size/M

#2543 Improve Fireperf SDK startup time.
  firebase-perf/src/main/java/com/google/firebase/perf/session/PerfSession.java
  firebase-perf/src/main/java/com/google/firebase/perf/transport/TransportManager.java
Labels: cla: yes, size/S

#2518 Make FirebasePerformance initialization lazy.
  firebase-perf/src/main/java/com/google/firebase/perf/FirebasePerfRegistrar.java
  firebase-perf/src/main/java/com/google/firebase/perf/FirebasePerformanceInitializer.java
  firebase-perf/src/main/java/com/google/firebase/perf/application/AppStateMonitor.java
  firebase-perf/src/main/java/com/google/firebase/perf/provider/FirebasePerfProvider.java
  firebase-perf/src/test/java/com/google/firebase/perf/FirebasePerfRegistrarTest.java
  firebase-perf/src/test/java/com/google/firebase/perf/application/AppStateMonitorTest.java
Labels: cla: yes, size/L

#2546 Updating variable names from the test classes to follow Java's code convention (b/177441811)
  firebase-perf/src/test/java/com/google/firebase/perf/FirebasePerformanceTestBase.java
  firebase-perf/src/test/java/com/google/firebase/perf/application/AppStateMonitorTest.java
  firebase-perf/src/test/java/com/google/firebase/perf/config/DeviceCacheManagerTest.java
  firebase-perf/src/test/java/com/google/firebase/perf/metrics/AppStartTraceTest.java
  firebase-perf/src/test/java/com/google/firebase/perf/metrics/HttpMetricTest.java
  firebase-perf/src/test/java/com/google/firebase/perf/metrics/NetworkRequestMetricBuilderTest.java
  firebase-perf/src/test/java/com/google/firebase/perf/metrics/TraceMetricBuilderTest.java
  firebase-perf/src/test/java/com/google/firebase/perf/metrics/TraceTest.java
  firebase-perf/src/test/java/com/google/firebase/perf/metrics/validator/FirebasePerfTraceValidatorTest.java
  firebase-perf/src/test/java/com/google/firebase/perf/network/FirebasePerfHttpClientTest.java
  firebase-perf/src/test/java/com/google/firebase/perf/network/FirebasePerfOkHttpClientTest.java
  firebase-perf/src/test/java/com/google/firebase/perf/network/FirebasePerfUrlConnectionTest.java
  firebase-perf/src/test/java/com/google/firebase/perf/network/InstrHttpInputStreamTest.java
  firebase-perf/src/test/java/com/google/firebase/perf/network/InstrHttpOutputStreamTest.java
  firebase-perf/src/test/java/com/google/firebase/perf/network/InstrHttpURLConnectionTest.java
  firebase-perf/src/test/java/com/google/firebase/perf/network/InstrHttpsURLConnectionTest.java
  firebase-perf/src/test/java/com/google/firebase/perf/network/InstrURLConnectionBaseTest.java
  firebase-perf/src/test/java/com/google/firebase/perf/session/PerfSessionTest.java
  firebase-perf/src/test/java/com/google/firebase/perf/session/gauges/GaugeMetadataManagerTest.java
  firebase-perf/src/test/java/com/google/firebase/perf/transport/RateLimiterTest.java
  firebase-perf/src/test/java/com/google/testing/timing/FakeDirectExecutorService.java
  firebase-perf/src/test/java/com/google/testing/timing/FakeScheduledExecutorService.java
Labels: cla: yes, size/XXL

#2545 Updating variable names from the source classes to follow Java's code convention (b/177441811)
  firebase-perf/src/main/java/com/google/firebase/perf/FirebasePerformance.java
  firebase-perf/src/main/java/com/google/firebase/perf/application/AppStateMonitor.java
  firebase-perf/src/main/java/com/google/firebase/perf/application/AppStateUpdateHandler.java
  firebase-perf/src/main/java/com/google/firebase/perf/config/ConfigResolver.java
  firebase-perf/src/main/java/com/google/firebase/perf/config/DeviceCacheManager.java
  firebase-perf/src/main/java/com/google/firebase/perf/config/RemoteConfigManager.java
  firebase-perf/src/main/java/com/google/firebase/perf/metrics/AppStartTrace.java
  firebase-perf/src/main/java/com/google/firebase/perf/metrics/Counter.java
  firebase-perf/src/main/java/com/google/firebase/perf/metrics/HttpMetric.java
  firebase-perf/src/main/java/com/google/firebase/perf/metrics/NetworkRequestMetricBuilder.java
  firebase-perf/src/main/java/com/google/firebase/perf/metrics/Trace.java
  firebase-perf/src/main/java/com/google/firebase/perf/metrics/TraceMetricBuilder.java
  firebase-perf/src/main/java/com/google/firebase/perf/metrics/validator/FirebasePerfApplicationInfoValidator.java
  firebase-perf/src/main/java/com/google/firebase/perf/metrics/validator/FirebasePerfGaugeMetricValidator.java
  firebase-perf/src/main/java/com/google/firebase/perf/metrics/validator/FirebasePerfNetworkValidator.java
  firebase-perf/src/main/java/com/google/firebase/perf/metrics/validator/FirebasePerfTraceValidator.java
  firebase-perf/src/main/java/com/google/firebase/perf/network/FirebasePerfHttpClient.java
  firebase-perf/src/main/java/com/google/firebase/perf/network/FirebasePerfOkHttpClient.java
  firebase-perf/src/main/java/com/google/firebase/perf/network/FirebasePerfUrlConnection.java
  firebase-perf/src/main/java/com/google/firebase/perf/network/InstrHttpInputStream.java
  firebase-perf/src/main/java/com/google/firebase/perf/network/InstrHttpOutputStream.java
  firebase-perf/src/main/java/com/google/firebase/perf/network/InstrHttpURLConnection.java
  firebase-perf/src/main/java/com/google/firebase/perf/network/InstrHttpsURLConnection.java
  firebase-perf/src/main/java/com/google/firebase/perf/network/InstrURLConnectionBase.java
  firebase-perf/src/main/java/com/google/firebase/perf/network/InstrumentApacheHttpResponseHandler.java
  firebase-perf/src/main/java/com/google/firebase/perf/network/InstrumentOkHttpEnqueueCallback.java
  firebase-perf/src/main/java/com/google/firebase/perf/provider/FirebasePerfProvider.java
  firebase-perf/src/main/java/com/google/firebase/perf/session/PerfSession.java
  firebase-perf/src/main/java/com/google/firebase/perf/session/SessionManager.java
  firebase-perf/src/main/java/com/google/firebase/perf/session/gauges/CpuGaugeCollector.java
  firebase-perf/src/main/java/com/google/firebase/perf/session/gauges/GaugeManager.java
  firebase-perf/src/main/java/com/google/firebase/perf/session/gauges/GaugeMetadataManager.java
  firebase-perf/src/main/java/com/google/firebase/perf/session/gauges/MemoryGaugeCollector.java
  firebase-perf/src/main/java/com/google/firebase/perf/transport/RateLimiter.java
  firebase-perf/src/main/java/com/google/firebase/perf/transport/TransportManager.java
  firebase-perf/src/main/java/com/google/firebase/perf/util/Constants.java
  firebase-perf/src/main/java/com/google/firebase/perf/util/Timer.java
  firebase-perf/src/main/java/com/google/firebase/perf/util/URLAllowlist.java
  firebase-perf/src/main/java/com/google/firebase/perf/util/URLWrapper.java
  firebase-perf/src/main/java/com/google/firebase/perf/util/Utils.java
  firebase-perf/src/test/java/com/google/firebase/perf/application/AppStateMonitorTest.java
Labels: cla: yes, size/XXL

#2547 Add dynamic module support to Remote Config.
  firebase-config/src/main/java/com/google/firebase/remoteconfig/RemoteConfigComponent.java
  firebase-config/src/main/java/com/google/firebase/remoteconfig/RemoteConfigRegistrar.java
  firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigFetchHandler.java
  firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/Personalization.java
  firebase-config/src/test/java/com/google/firebase/remoteconfig/FirebaseRemoteConfigTest.java
  firebase-config/src/test/java/com/google/firebase/remoteconfig/RemoteConfigComponentTest.java
  firebase-config/src/test/java/com/google/firebase/remoteconfig/internal/ConfigFetchHandlerTest.java
  firebase-config/src/test/java/com/google/firebase/remoteconfig/internal/PersonalizationTest.java
Labels: cla: yes, size/M
