Repository firebase/firebase-android-sdk, pull requests merged in 2021-02, with the labels that each got.

#2381 Add another layer of url expiry checking.
  firebase-ml-modeldownloader/src/main/java/com/google/firebase/ml/modeldownloader/internal/CustomModelDownloadService.java
  firebase-ml-modeldownloader/src/main/java/com/google/firebase/ml/modeldownloader/internal/FirebaseMlLogEvent.java
  firebase-ml-modeldownloader/src/main/java/com/google/firebase/ml/modeldownloader/internal/ModelFileDownloadService.java
  firebase-ml-modeldownloader/src/test/java/com/google/firebase/ml/modeldownloader/internal/ModelFileDownloadServiceTest.java
  firebase-ml-modeldownloader/src/test/proto/firebase/ml/modeldownloader/firebase_ml_log_sdk.proto
Labels: cla: yes, size/L

#2346 Implement BundleLoader
  firebase-firestore/api.txt
  firebase-firestore/src/main/java/com/google/firebase/firestore/LoadBundleTaskProgress.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/bundle/BundleCallback.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/bundle/BundleLoader.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/bundle/BundleMetadata.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/LocalStore.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteBundleCache.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/util/ByteBufferInputStream.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/bundle/BundleLoaderTest.java
Labels: api: firestore, cla: yes, size/XL

#2390 Add javadoc gradle plugins.
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/JavadocPlugin.java
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/ProjectUtils.kt
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/Tasks.kt
Labels: cla: yes, size/L

#2384 Update getModelDownloadId based on API review.
  firebase-ml-modeldownloader/api.txt
  firebase-ml-modeldownloader/src/main/java/com/google/firebase/ml/modeldownloader/FirebaseModelDownloader.java
  firebase-ml-modeldownloader/src/test/java/com/google/firebase/ml/modeldownloader/FirebaseModelDownloaderTest.java
Labels: cla: yes, size/L

#2391 Configure dependency injection.
  encoders/protoc-gen-firebase-encoders/protoc-gen-firebase-encoders.gradle
  encoders/protoc-gen-firebase-encoders/src/main/kotlin/com/google/firebase/encoders/proto/codegen/CodeGenerator.kt
  encoders/protoc-gen-firebase-encoders/src/main/kotlin/com/google/firebase/encoders/proto/codegen/Main.kt
  encoders/protoc-gen-firebase-encoders/src/main/kotlin/com/google/firebase/encoders/proto/codegen/Parsing.kt
Labels: cla: yes, size/M

#2393 update scheduling alogirthm to handle reschedules
  transport/transport-runtime/src/androidTest/java/com/google/android/datatransport/runtime/TestWorkScheduler.java
  transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/scheduling/jobscheduling/AlarmManagerScheduler.java
  transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/scheduling/jobscheduling/JobInfoScheduler.java
  transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/scheduling/jobscheduling/Uploader.java
  transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/scheduling/jobscheduling/WorkScheduler.java
  transport/transport-runtime/src/test/java/com/google/android/datatransport/runtime/scheduling/jobscheduling/AlarmManagerSchedulerTest.java
  transport/transport-runtime/src/test/java/com/google/android/datatransport/runtime/scheduling/jobscheduling/JobInfoSchedulerTest.java
  transport/transport-runtime/src/test/java/com/google/android/datatransport/runtime/scheduling/jobscheduling/UploaderTest.java
Labels: cla: yes, size/M

#2369 Expose Firestore Bundles
  firebase-firestore/CHANGELOG.md
  firebase-firestore/api.txt
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/BundleTest.java
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/testutil/EventAccumulator.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/FirebaseFirestore.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/LoadBundleTask.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/LoadBundleTaskProgress.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/OnProgressListener.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/bundle/BundleLoader.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/bundle/BundleMetadata.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/bundle/BundleReader.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/bundle/BundleSerializer.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/FirestoreClient.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/SyncEngine.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/Target.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/LocalStore.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteBundleCache.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteSchema.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/remote/RemoteSerializer.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/bundle/BundleLoaderTest.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/bundle/BundleReaderTest.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/bundle/BundleSerializerTest.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/BundleCacheTestCase.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/LocalStoreTestCase.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/PersistenceTestHelpers.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/remote/RemoteSerializerTest.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/spec/SpecTestCase.java
  firebase-firestore/src/test/resources/json/bundle_spec_test.json
Labels: api: firestore, cla: yes, size/XXL

#2399 Don't fail Bundle loading if nanos/seconds not set
  firebase-firestore/src/main/java/com/google/firebase/firestore/bundle/BundleSerializer.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/bundle/BundleSerializerTest.java
Labels: api: firestore, cla: yes, size/M

#2403 Define javadoc-only dependencies in projects gradle files.
  firebase-common/firebase-common.gradle
  firebase-config/firebase-config.gradle
  firebase-database/firebase-database.gradle
  firebase-dynamic-links/firebase-dynamic-links.gradle
  firebase-firestore/firebase-firestore.gradle
  firebase-functions/firebase-functions.gradle
  firebase-installations/firebase-installations.gradle
  firebase-messaging/firebase-messaging.gradle
  firebase-segmentation/firebase-segmentation.gradle
  firebase-storage/firebase-storage.gradle
Labels: cla: yes, size/S

#2405 Updating docs and enabling javadocs
  firebase-ml-modeldownloader/api.txt
  firebase-ml-modeldownloader/firebase-ml-modeldownloader.gradle
  firebase-ml-modeldownloader/src/main/java/com/google/firebase/ml/modeldownloader/FirebaseMlException.java
  firebase-ml-modeldownloader/src/main/java/com/google/firebase/ml/modeldownloader/FirebaseModelDownloader.java
  firebase-ml-modeldownloader/src/main/java/com/google/firebase/ml/modeldownloader/internal/CustomModelDownloadService.java
  firebase-ml-modeldownloader/src/main/java/com/google/firebase/ml/modeldownloader/internal/ModelFileDownloadService.java
  firebase-ml-modeldownloader/src/test/java/com/google/firebase/ml/modeldownloader/internal/CustomModelDownloadServiceTest.java
  firebase-ml-modeldownloader/src/test/java/com/google/firebase/ml/modeldownloader/internal/ModelFileDownloadServiceTest.java
Labels: cla: yes, size/M

#2402 Fixing BadTokenException while showing FIAM
  firebase-inappmessaging-display/src/main/java/com/google/firebase/inappmessaging/display/internal/FiamWindowManager.java
Labels: cla: yes, size/XS

#2409 Adding deleteModel logging and retrieve download success events.
  firebase-ml-modeldownloader/src/main/java/com/google/firebase/ml/modeldownloader/FirebaseModelDownloader.java
  firebase-ml-modeldownloader/src/main/java/com/google/firebase/ml/modeldownloader/internal/CustomModelDownloadService.java
  firebase-ml-modeldownloader/src/main/java/com/google/firebase/ml/modeldownloader/internal/FirebaseMlLogEvent.java
  firebase-ml-modeldownloader/src/main/java/com/google/firebase/ml/modeldownloader/internal/FirebaseMlLogger.java
  firebase-ml-modeldownloader/src/main/java/com/google/firebase/ml/modeldownloader/internal/ModelFileManager.java
  firebase-ml-modeldownloader/src/test/java/com/google/firebase/ml/modeldownloader/FirebaseModelDownloaderTest.java
  firebase-ml-modeldownloader/src/test/java/com/google/firebase/ml/modeldownloader/internal/CustomModelDownloadServiceTest.java
  firebase-ml-modeldownloader/src/test/java/com/google/firebase/ml/modeldownloader/internal/FirebaseMlLogEventTest.java
  firebase-ml-modeldownloader/src/test/java/com/google/firebase/ml/modeldownloader/internal/FirebaseMlLoggerTest.java
  firebase-ml-modeldownloader/src/test/proto/firebase/ml/modeldownloader/firebase_ml_log_sdk.proto
Labels: cla: yes, size/L

#2392 Update logging flag to match recommended style and execution.
  firebase-ml-modeldownloader/api.txt
  firebase-ml-modeldownloader/src/main/java/com/google/firebase/ml/modeldownloader/FirebaseModelDownloader.java
  firebase-ml-modeldownloader/src/main/java/com/google/firebase/ml/modeldownloader/internal/SharedPreferencesUtil.java
  firebase-ml-modeldownloader/src/test/java/com/google/firebase/ml/modeldownloader/FirebaseModelDownloaderTest.java
  firebase-ml-modeldownloader/src/test/java/com/google/firebase/ml/modeldownloader/internal/SharedPreferencesUtilTest.java
Labels: cla: yes, size/M

#2411 update model Version for release
  firebase-ml-modeldownloader/gradle.properties
Labels: cla: yes, size/XS

#2404 Dequeue limbo resolutions when their respective queries are stopped
  firebase-firestore/CHANGELOG.md
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/SyncEngine.java
  firebase-firestore/src/test/resources/json/limbo_spec_test.json
Labels: api: firestore, cla: yes, size/XXL

#2413 Adjust returned information from url errorStream
  firebase-ml-modeldownloader/src/androidTest/java/com/google/firebase/ml/modeldownloader/TestPublicApi.java
  firebase-ml-modeldownloader/src/main/java/com/google/firebase/ml/modeldownloader/CustomModel.java
  firebase-ml-modeldownloader/src/main/java/com/google/firebase/ml/modeldownloader/CustomModelDownloadConditions.java
  firebase-ml-modeldownloader/src/main/java/com/google/firebase/ml/modeldownloader/FirebaseModelDownloader.java
  firebase-ml-modeldownloader/src/main/java/com/google/firebase/ml/modeldownloader/internal/CustomModelDownloadService.java
  firebase-ml-modeldownloader/src/test/java/com/google/firebase/ml/modeldownloader/internal/CustomModelDownloadServiceTest.java
Labels: cla: yes, size/L

#2421 Fix error log
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsController.java
Labels: cla: yes, size/XS

#2419 Update Test Runners to AS 4.1.2 format
  .idea/runConfigurations/Firestore_Integration_Tests__Firestore_Emulator_.xml
  .idea/runConfigurations/Firestore_Unit_Tests.xml
Labels: api: firestore, cla: yes, size/S

#2422 Maybe Deflake RTDB tests
  firebase-database/src/androidTest/java/com/google/firebase/database/DataTest.java
  firebase-database/src/androidTest/java/com/google/firebase/database/EventTest.java
  firebase-database/src/androidTest/java/com/google/firebase/database/FirebaseDatabaseTest.java
  firebase-database/src/androidTest/java/com/google/firebase/database/InfoTest.java
  firebase-database/src/androidTest/java/com/google/firebase/database/IntegrationTestHelpers.java
  firebase-database/src/androidTest/java/com/google/firebase/database/OrderByTest.java
  firebase-database/src/androidTest/java/com/google/firebase/database/OrderTest.java
  firebase-database/src/androidTest/java/com/google/firebase/database/QueryTest.java
  firebase-database/src/androidTest/java/com/google/firebase/database/RealtimeTest.java
  firebase-database/src/androidTest/java/com/google/firebase/database/TransactionTest.java
  firebase-database/src/main/java/com/google/firebase/database/core/RepoManager.java
Labels: api: database, cla: yes, size/M

#2416 Add plugin to update license in proprietary sdks.
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/FirebaseProprietaryLibraryPlugin.kt
Labels: cla: yes, size/M

#2415 Add missing dependency on javadoc task.
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/JavadocPlugin.java
Labels: cla: yes, size/XS

#2414 Don't go idle if there are outstanding gets()
  firebase-database/CHANGELOG.md
  firebase-database/src/main/java/com/google/firebase/database/connection/PersistentConnectionImpl.java
Labels: api: database, cla: yes, size/XS

#2380 Add build number to Remote Config
  firebase-config/src/main/java/com/google/firebase/remoteconfig/RemoteConfigConstants.java
  firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigFetchHttpClient.java
  firebase-config/src/test/java/com/google/firebase/remoteconfig/internal/ConfigFetchHttpClientTest.java
Labels: cla: yes, size/S

#2428 Make TransformResult non-nullable
  firebase-firestore/src/main/java/com/google/firebase/firestore/model/mutation/DeleteMutation.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/model/mutation/MutationResult.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/model/mutation/PatchMutation.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/model/mutation/SetMutation.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/remote/RemoteSerializer.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/LocalStoreTestCase.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/model/MutationTest.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/spec/SpecTestCase.java
  firebase-firestore/src/testUtil/java/com/google/firebase/firestore/testutil/TestUtil.java
Labels: api: database, cla: yes, size/M

#2417 turn off logging in functional tests.
  firebase-ml-modeldownloader/src/androidTest/java/com/google/firebase/ml/modeldownloader/TestGetModelLocal.java
  firebase-ml-modeldownloader/src/androidTest/java/com/google/firebase/ml/modeldownloader/TestPublicApi.java
Labels: cla: yes, size/XS

#2430 Use the right name for firebase library plugin
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/FirebaseProprietaryLibraryPlugin.kt
Labels: cla: yes, size/XS

#2376 Fix startAfter/endBefore for orderByKeys queries
  firebase-database/src/androidTest/java/com/google/firebase/database/QueryTest.java
  firebase-database/src/main/java/com/google/firebase/database/Query.java
  firebase-database/src/main/java/com/google/firebase/database/core/Repo.java
  firebase-database/src/main/java/com/google/firebase/database/core/SyncPoint.java
  firebase-database/src/main/java/com/google/firebase/database/core/SyncTree.java
Labels: cla: yes, size/L

#2429 Update functions instances used by device-tests and smoke-tests.
  firebase-functions/src/androidTest/backend/functions/package.json
  smoke-tests/src/androidTest/backend/functions/.firebaserc
  smoke-tests/src/androidTest/backend/functions/.gitignore
  smoke-tests/src/androidTest/backend/functions/README.md
  smoke-tests/src/androidTest/backend/functions/firebase.json
  smoke-tests/src/androidTest/backend/functions/functions/.eslintrc.js
  smoke-tests/src/androidTest/backend/functions/functions/index.js
  smoke-tests/src/androidTest/backend/functions/functions/package-lock.json
  smoke-tests/src/androidTest/backend/functions/functions/package.json
Labels: cla: yes, size/XXL

#2412 Update Bundle API documentation
  firebase-firestore/src/main/java/com/google/firebase/firestore/FirebaseFirestore.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/LoadBundleTask.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/LoadBundleTaskProgress.java
Labels: api: firestore, cla: yes, size/L

#2406 Add DI to FirebasePerfRegistrar.java
  firebase-perf/firebase-perf.gradle
  firebase-perf/src/main/java/com/google/firebase/perf/FirebasePerfRegistrar.java
  firebase-perf/src/main/java/com/google/firebase/perf/FirebasePerformance.java
  firebase-perf/src/main/java/com/google/firebase/perf/injection/components/FirebasePerformanceComponent.java
  firebase-perf/src/main/java/com/google/firebase/perf/injection/modules/FirebasePerformanceModule.java
Labels: cla: yes, size/L

#2436 Replace gRPC Status#equals() with Status#isOk().
  firebase-firestore/src/main/java/com/google/firebase/firestore/remote/AbstractStream.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/remote/RemoteStore.java
Labels: cla: yes, ok-to-test, size/XS

#2437 Update latest released versions
  firebase-config/gradle.properties
  firebase-crashlytics-ndk/gradle.properties
  firebase-crashlytics/gradle.properties
  firebase-datatransport/gradle.properties
  firebase-firestore/gradle.properties
  firebase-inappmessaging-display/gradle.properties
  firebase-inappmessaging/gradle.properties
  firebase-perf/gradle.properties
  transport/transport-runtime/gradle.properties
Labels: cla: yes, size/M

#2439 remove unused proto value.
  firebase-ml-modeldownloader/src/test/proto/firebase/ml/modeldownloader/firebase_ml_log_sdk.proto
Labels: cla: yes, size/XS

#2423 add manifest flag for model downloader data collection
  firebase-ml-modeldownloader/src/main/java/com/google/firebase/ml/modeldownloader/internal/SharedPreferencesUtil.java
Labels: cla: yes, size/M

#2445 Add getUtmParameters api method to PendingDynamicLinkData
  firebase-dynamic-links/api.txt
  firebase-dynamic-links/src/main/java/com/google/firebase/dynamiclinks/PendingDynamicLinkData.java
  firebase-dynamic-links/src/main/java/com/google/firebase/dynamiclinks/internal/DynamicLinkUTMParams.java
  firebase-dynamic-links/src/test/java/com/google/firebase/dynamiclinks/PendingDynamicLinkDataTest.java
  firebase-dynamic-links/src/test/java/com/google/firebase/dynamiclinks/internal/DynamicLinkUTMParamsTest.java
Labels: cla: yes, size/L

#2447 Add dummy task in javadoc plugin to generate an empty api.txt file
  buildSrc/build.gradle
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/Dokka.java
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/JavadocPlugin.java
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/ci/ContinuousIntegrationPlugin.java
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/ci/device/FirebaseTestLabExtension.java
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/license/GenerateLicensesTask.java
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/license/LicenseResolverPlugin.java
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/license/ThirdPartyLicensesExtension.java
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/publish/Publisher.java
Labels: cla: yes, size/L

#2448 Add missing javadoc dependency.
  firebase-ml-modeldownloader/firebase-ml-modeldownloader.gradle
Labels: cla: yes, size/XS

#2450 Additional javadoc fixes.
  firebase-crashlytics/firebase-crashlytics.gradle
  firebase-perf/firebase-perf.gradle
  firebase-perf/src/main/java/com/google/firebase/perf/internal/SessionAwareObject.java
Labels: cla: yes, size/XS

#2452 Add FireEscapeArtifactPlugin
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/FireEscapeArtifactPlugin.java
Labels: cla: yes, size/L

#2454 First commit, removed root files and moved configuration to BomGenera…
  buildSrc/build.gradle
  buildSrc/src/main/java/com/google/firebase/gradle/bomgenerator/BomGeneratorTask.java
  buildSrc/src/main/java/com/google/firebase/gradle/bomgenerator/MarkdownDocumentationWriter.java
  buildSrc/src/main/java/com/google/firebase/gradle/bomgenerator/PomXmlWriter.java
  buildSrc/src/main/java/com/google/firebase/gradle/bomgenerator/RecipeVersionWriter.java
  buildSrc/src/main/java/com/google/firebase/gradle/bomgenerator/RepositoryClient.java
  buildSrc/src/main/java/com/google/firebase/gradle/bomgenerator/model/Dependency.java
  buildSrc/src/main/java/com/google/firebase/gradle/bomgenerator/model/VersionBump.java
Labels: cla: yes, size/XXL

#2455 Add MultiProjectReleasePlugin
  alternative-root-project.gradle
  alternative-settings.gradle
  buildSrc/src/main/java/com/google/firebase/gradle/MultiProjectReleasePlugin.java
Labels: cla: yes, size/L

#2456 Add missing transformation file.
  alternative-settings.gradle
  buildSrc/build.gradle
  buildSrc/devsite_transform.sh
  buildSrc/gms_transform.sh
Labels: cla: yes, size/L

#2446 add manifest flag unit tests.
  firebase-ml-modeldownloader/ml-data-collection-tests/ml-data-collection-tests.gradle
  firebase-ml-modeldownloader/ml-data-collection-tests/src/main/AndroidManifest.xml
  firebase-ml-modeldownloader/ml-data-collection-tests/src/test/java/com/google/firebase/ml_data_collection_tests/MlDataCollectionDefaultDisabledTest.java
  firebase-ml-modeldownloader/ml-data-collection-tests/src/test/java/com/google/firebase/ml_data_collection_tests/MlDataCollectionTestUtil.java
  firebase-ml-modeldownloader/src/main/java/com/google/firebase/ml/modeldownloader/internal/SharedPreferencesUtil.java
  subprojects.cfg
Labels: cla: yes, size/L

#2432 Add dynamic module support to Firestore
  firebase-firestore/firebase-firestore.gradle
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/remote/StreamTest.java
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/testutil/IntegrationTestUtil.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/FirebaseFirestore.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/FirestoreMultiDbComponent.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/FirestoreRegistrar.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/auth/FirebaseAuthCredentialsProvider.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/FirestoreMultiDbComponentTest.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/auth/FirebaseAuthCredentialsProviderTest.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/remote/MockDatastore.java
  firebase-firestore/src/testUtil/java/com/google/firebase/firestore/testutil/DelayedDeferred.java
  firebase-firestore/src/testUtil/java/com/google/firebase/firestore/testutil/EmptyCredentialsProvider.java
  firebase-firestore/src/testUtil/java/com/google/firebase/firestore/testutil/ImmediateDeferred.java
  firebase-firestore/src/testUtil/java/com/google/firebase/firestore/testutil/UnavailableDeferred.java
Labels: cla: yes, size/XL

#2458 Removing the isPerformanceMonitoringEnabled check in FirebasePerfProvider and moving the getSharedPreferences to a separate thread.
  firebase-perf/src/main/java/com/google/firebase/perf/config/ConfigResolver.java
  firebase-perf/src/main/java/com/google/firebase/perf/config/DeviceCacheManager.java
  firebase-perf/src/main/java/com/google/firebase/perf/provider/FirebasePerfProvider.java
  firebase-perf/src/test/java/com/google/firebase/perf/FirebasePerformanceTest.java
  firebase-perf/src/test/java/com/google/firebase/perf/config/DeviceCacheManagerTest.java
  firebase-perf/src/test/java/com/google/firebase/perf/internal/AppStateMonitorTest.java
  firebase-perf/src/test/java/com/google/firebase/perf/metrics/TraceTest.java
  firebase-perf/src/test/java/com/google/testing/timing/FakeDirectExecutorService.java
Labels: cla: yes, size/L

#2463 Accept Proto3 JSON limits in Bundled Queries
  firebase-firestore/CHANGELOG.md
  firebase-firestore/src/main/java/com/google/firebase/firestore/bundle/BundleSerializer.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/bundle/BundleSerializerTest.java
Labels: api: firestore, cla: yes, size/S

#2443 New class and methods to implement bulk custom key/value logging.
  firebase-crashlytics-ndk/api.txt
  firebase-crashlytics/CHANGELOG.md
  firebase-crashlytics/api.txt
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/CrashlyticsCoreTest.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/CustomKeysAndValues.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/FirebaseCrashlytics.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsController.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsCore.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/UserMetadata.java
Labels: cla: yes, size/L

#2453 smoke tests for ml modeldownloader
  smoke-tests/build.gradle
  smoke-tests/src/main/java/com/google/firebase/testing/BuildOnlyTest.java
Labels: cla: yes, size/XS

#2469 Requested doc updated.
  firebase-ml-modeldownloader/src/main/java/com/google/firebase/ml/modeldownloader/CustomModel.java
  firebase-ml-modeldownloader/src/main/java/com/google/firebase/ml/modeldownloader/DownloadType.java
  firebase-ml-modeldownloader/src/main/java/com/google/firebase/ml/modeldownloader/FirebaseMlException.java
  firebase-ml-modeldownloader/src/main/java/com/google/firebase/ml/modeldownloader/FirebaseModelDownloader.java
  firebase-ml-modeldownloader/src/main/java/com/google/firebase/ml/modeldownloader/internal/DataTransportMlEventSender.java
  firebase-ml-modeldownloader/src/main/java/com/google/firebase/ml/modeldownloader/internal/FirebaseMlLogEvent.java
  firebase-ml-modeldownloader/src/main/java/com/google/firebase/ml/modeldownloader/internal/FirebaseMlLogger.java
  firebase-ml-modeldownloader/src/test/proto/firebase/ml/modeldownloader/firebase_ml_log_sdk.proto
Labels: cla: yes, size/L

#2468 Post-Merge cleanup of MutableDocuments
  firebase-firestore/ktx/src/test/java/com/google/firebase/firestore/testutil/TestUtil.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/bundle/BundleLoader.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/bundle/BundleSerializer.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/SyncEngine.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/LocalDocumentsView.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/LocalSerializer.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/LocalStore.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/MemoryRemoteDocumentCache.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteRemoteDocumentCache.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/model/Document.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/model/MutableDocument.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/model/mutation/MutationBatch.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/remote/RemoteSerializer.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/remote/WatchChangeAggregator.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/bundle/BundleSerializerTest.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/LruGarbageCollectorTestCase.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/RemoteDocumentCacheTestCase.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/model/DocumentTest.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/model/MutableObjectValueTest.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/model/MutationTest.java
  firebase-firestore/src/testUtil/java/com/google/firebase/firestore/testutil/TestUtil.java
Labels: api: firestore, cla: yes, size/L

#2471 Revert "smoke tests for ml modeldownloader"
  smoke-tests/build.gradle
  smoke-tests/src/main/java/com/google/firebase/testing/BuildOnlyTest.java
Labels: cla: yes, size/XS

#2470 Change bundle protos package
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/LocalSerializer.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteBundleCache.java
  firebase-firestore/src/proto/google/firebase/firestore/proto/bundle.proto
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/LocalSerializerTest.java
Labels: cla: yes, size/S
