Repository firebase/firebase-android-sdk, pull requests merged in 2021-04, with the labels that each got.

#2562 Fix personalization test and add check for optionalProvider.
  firebase-config/firebase-config.gradle
  firebase-config/src/test/java/com/google/firebase/remoteconfig/FirebaseRemoteConfigTest.java
Labels: cla: yes, size/M

#2563 Add a tools:remove rule to the discovery service definition.
  firebase-common/src/main/AndroidManifest.xml
  firebase-components/firebase-dynamic-module-support/src/main/AndroidManifest.xml
Labels: cla: yes, size/S

#2564 Test Remote config personalization provider more dynamically.
  firebase-config/src/test/java/com/google/firebase/remoteconfig/FirebaseRemoteConfigTest.java
Labels: cla: yes, size/S

#2571 Register LibraryVersionComponent for the dynamic module loading SDK.
  firebase-components/firebase-dynamic-module-support/src/main/java/com/google/firebase/dynamicloading/DynamicLoadingRegistrar.java
Labels: cla: yes, size/XS

#2516 implement firebase-ml-modeldownloader-ktx
  firebase-ml-modeldownloader/ktx/api.txt
  firebase-ml-modeldownloader/ktx/gradle.properties
  firebase-ml-modeldownloader/ktx/ktx.gradle
  firebase-ml-modeldownloader/ktx/src/main/AndroidManifest.xml
  firebase-ml-modeldownloader/ktx/src/main/kotlin/com/google/firebase/ml/modeldownloader/ktx/ModelDownloader.kt
  firebase-ml-modeldownloader/ktx/src/test/kotlin/com/google/firebase/ml/modeldownloader/ktx/ModelDownloaderTests.kt
  subprojects.cfg
Labels: cla: yes, ok-to-test, size/L

#2585 Add flag for collecting ANRs to Settings Feature Data
  firebase-crashlytics/src/androidTest/assets/firebase_settings_collect_anrs.json
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/settings/SettingsV3JsonTransformTest.java
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/settings/TestSettingsData.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/settings/DefaultSettingsJsonTransform.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/settings/SettingsJsonConstants.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/settings/SettingsV3JsonTransform.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/settings/model/FeaturesSettingsData.java
Labels: cla: yes, size/M

#2590 test change to test mirror update
  empty-api.txt
Labels: cla: yes, size/XS

#2591 Cleanup dead code in fireci, refactor.
  ci/fireci/fireci/commands.py
  ci/fireci/fireci/emulator.py
  ci/fireci/fireci/internal.py
  ci/fireci/fireci/main.py
  ci/fireci/fireci/stats.py
  ci/fireci/fireciplugins/api_information.py
  ci/fireci/setup.py
  ci/fireci/tests/emulator_test.py
  ci/fireci/tests/integ_tests.py
  ci/run.sh
Labels: cla: yes, size/XL

#2559 Disable desugaring.
  alternative-root-project.gradle
  build.gradle
  smoke-tests/build.gradle
Labels: cla: yes, size/S

#2592 Remove dead code.
  alternative-root-project.gradle
  build.gradle
  buildSrc/build.gradle
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/ci/metrics/DrainingBuildListener.java
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/ci/metrics/MeasuringTaskExecutionListener.java
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/ci/metrics/Metrics.java
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/ci/metrics/MetricsPlugin.java
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/ci/metrics/StackdriverMetrics.java
Labels: cla: yes, size/L

#2442 Add useEmulator support for Firebase Storage
  firebase-storage/api.txt
  firebase-storage/src/main/java/com/google/firebase/storage/DeleteStorageTask.java
  firebase-storage/src/main/java/com/google/firebase/storage/FileDownloadTask.java
  firebase-storage/src/main/java/com/google/firebase/storage/FirebaseStorage.java
  firebase-storage/src/main/java/com/google/firebase/storage/GetDownloadUrlTask.java
  firebase-storage/src/main/java/com/google/firebase/storage/GetMetadataTask.java
  firebase-storage/src/main/java/com/google/firebase/storage/ListTask.java
  firebase-storage/src/main/java/com/google/firebase/storage/StorageReference.java
  firebase-storage/src/main/java/com/google/firebase/storage/StreamDownloadTask.java
  firebase-storage/src/main/java/com/google/firebase/storage/UpdateMetadataTask.java
  firebase-storage/src/main/java/com/google/firebase/storage/UploadTask.java
  firebase-storage/src/main/java/com/google/firebase/storage/internal/StorageReferenceUri.java
  firebase-storage/src/main/java/com/google/firebase/storage/internal/Util.java
  firebase-storage/src/main/java/com/google/firebase/storage/network/DeleteNetworkRequest.java
  firebase-storage/src/main/java/com/google/firebase/storage/network/GetMetadataNetworkRequest.java
  firebase-storage/src/main/java/com/google/firebase/storage/network/GetNetworkRequest.java
  firebase-storage/src/main/java/com/google/firebase/storage/network/ListNetworkRequest.java
  firebase-storage/src/main/java/com/google/firebase/storage/network/NetworkRequest.java
  firebase-storage/src/main/java/com/google/firebase/storage/network/ResumableNetworkRequest.java
  firebase-storage/src/main/java/com/google/firebase/storage/network/ResumableUploadByteRequest.java
  firebase-storage/src/main/java/com/google/firebase/storage/network/ResumableUploadCancelRequest.java
  firebase-storage/src/main/java/com/google/firebase/storage/network/ResumableUploadQueryRequest.java
  firebase-storage/src/main/java/com/google/firebase/storage/network/ResumableUploadStartRequest.java
  firebase-storage/src/main/java/com/google/firebase/storage/network/UpdateMetadataNetworkRequest.java
  firebase-storage/src/test/java/com/google/firebase/storage/NetworkRequestTest.java
  firebase-storage/src/test/java/com/google/firebase/storage/StorageReferenceTest.java
  firebase-storage/src/test/java/com/google/firebase/storage/internal/StorageReferenceUriTest.java
  firebase-storage/test-app/src/main/AndroidManifest.xml
  firebase-storage/test-app/src/main/java/com/example/storage/MainActivity.java
  firebase-storage/test-app/src/main/res/layout/content_main.xml
  firebase-storage/test-app/test-app.gradle
Labels: cla: yes, size/XL

#2555 Using deferred Analytics with Crashlytics.
  firebase-crashlytics/firebase-crashlytics.gradle
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/CrashlyticsAnalyticsListenerTest.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/AnalyticsDeferredProxy.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/CrashlyticsRegistrar.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/FirebaseCrashlytics.java
Labels: cla: yes, size/L

#2532 Create native proxy object to check provider on each call and mediate…
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/ProviderProxyNativeComponentTest.java
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/CrashlyticsControllerTest.java
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/CrashlyticsCoreInitializationTest.java
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/CrashlyticsCoreTest.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/CrashlyticsRegistrar.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/FirebaseCrashlytics.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/ProviderProxyNativeComponent.java
Labels: cla: yes, size/L

#2587 Add ability to easily get the startTimestampMs of a session
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/persistence/CrashlyticsReportPersistenceTest.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsController.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsReportDataCapture.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/SessionReportingCoordinator.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/persistence/CrashlyticsReportPersistence.java
Labels: cla: yes, size/M

#2603 Relax state handling in AppCheck
  firebase-database/src/main/java/com/google/firebase/database/connection/PersistentConnectionImpl.java
Labels: api: database, cla: yes, size/XS

#2609 Updated test dependencies and fixed JUnit4 test runner error.
  firebase-crashlytics-ndk/firebase-crashlytics-ndk.gradle
  firebase-crashlytics/firebase-crashlytics.gradle
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/ProviderProxyNativeComponentTest.java
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/CrashlyticsReportDataCaptureTest.java
Labels: cla: yes, size/M

#2612 Fix dexing.
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/FirebaseLibraryPlugin.java
Labels: cla: yes, size/XS

#2616 Update versions
  firebase-annotations/gradle.properties
  firebase-config/gradle.properties
  firebase-crashlytics-ndk/gradle.properties
  firebase-crashlytics/gradle.properties
  firebase-database/gradle.properties
  firebase-firestore/gradle.properties
  firebase-inappmessaging-display/gradle.properties
  firebase-inappmessaging/gradle.properties
  firebase-messaging-directboot/gradle.properties
  firebase-messaging/gradle.properties
  firebase-ml-modeldownloader/gradle.properties
  firebase-storage/gradle.properties
Labels: cla: yes, size/M

#2613 Re-enable App Check integration tests
  appcheck/firebase-appcheck-debug-testing/firebase-appcheck-debug-testing.gradle
  appcheck/firebase-appcheck-debug-testing/src/androidTest/java/com/google/firebase/appcheck/debug/testing/FirebaseAppCheckTest.java
Labels: cla: yes, size/XS

#2617 Update default token refresh rate
  appcheck/firebase-appcheck/src/main/java/com/google/firebase/appcheck/internal/DefaultAppCheckToken.java
  appcheck/firebase-appcheck/src/main/java/com/google/firebase/appcheck/internal/TokenRefreshManager.java
  appcheck/firebase-appcheck/src/test/java/com/google/firebase/appcheck/internal/TokenRefreshManagerTest.java
Labels: cla: yes, size/S

#2597 Add artifacts to bom generator task
  buildSrc/src/main/java/com/google/firebase/gradle/bomgenerator/BomGeneratorTask.java
Labels: cla: yes, size/XS

#2602 Add ApplicationExitInfo to CrashlyticsReport
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsController.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/model/CrashlyticsReport.java
  firebase-crashlytics/src/test/java/com/google/firebase/crashlytics/internal/model/CrashlyticsReportTest.java
Labels: cla: yes, size/L

#2624 Add jsr305 javadocClasspath dep implicitly.
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/Dokka.java
Labels: cla: yes, size/XS

#2619 Implement platform logging for App Check
  appcheck/firebase-appcheck-debug/src/main/java/com/google/firebase/appcheck/debug/internal/DebugAppCheckProvider.java
  appcheck/firebase-appcheck-safetynet/src/main/java/com/google/firebase/appcheck/safetynet/internal/SafetyNetAppCheckProvider.java
  appcheck/firebase-appcheck/src/main/java/com/google/firebase/appcheck/FirebaseAppCheckRegistrar.java
  appcheck/firebase-appcheck/src/main/java/com/google/firebase/appcheck/internal/DefaultFirebaseAppCheck.java
  appcheck/firebase-appcheck/src/main/java/com/google/firebase/appcheck/internal/NetworkClient.java
  appcheck/firebase-appcheck/src/test/java/com/google/firebase/appcheck/FirebaseAppCheckRegistrarTest.java
  appcheck/firebase-appcheck/src/test/java/com/google/firebase/appcheck/internal/DefaultFirebaseAppCheckTest.java
  appcheck/firebase-appcheck/src/test/java/com/google/firebase/appcheck/internal/NetworkClientTest.java
Labels: cla: yes, size/L

#2621 AppCheck javadoc nits
  appcheck/firebase-appcheck/src/main/java/com/google/firebase/appcheck/AppCheckProvider.java
  appcheck/firebase-appcheck/src/main/java/com/google/firebase/appcheck/FirebaseAppCheck.java
Labels: cla: yes, size/S

#2626 Add javadoc dependency on autovalue for appcheck
  appcheck/firebase-appcheck-debug/firebase-appcheck-debug.gradle
  appcheck/firebase-appcheck-safetynet/firebase-appcheck-safetynet.gradle
  appcheck/firebase-appcheck/firebase-appcheck.gradle
Labels: cla: yes, size/XS

#2628 Fixing FIAM Java doc issues
  firebase-inappmessaging/src/main/java/com/google/firebase/inappmessaging/internal/ForegroundNotifier.java
  firebase-inappmessaging/src/main/java/com/google/firebase/inappmessaging/model/InAppMessage.java
Labels: cla: yes, size/XS
