Repository firebase/firebase-android-sdk, pull requests merged in 2021-09, with the labels that each got.

#2937 Measure per-architecture sizes for firebase crashlytics ndk.
  apk-size/app/build.gradle
  apk-size/app/configure.gradle
  apk-size/app/default.gradle
  apk-size/app/src/base/base.gradle
  apk-size/gradle.properties
  ci/fireci/fireciplugins/binary_size.py
Labels: size/M, cla: yes

#2935 Fix comments from Internal review
  firebase-firestore/firebase-firestore.gradle
  firebase-firestore/src/main/java/com/google/firebase/firestore/index/FirestoreIndexValueWriter.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/index/OrderedCodeReader.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/index/OrderedCodeWriter.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/model/FieldIndex.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/model/TargetIndexMatcher.java
Labels: size/M, cla: yes, api: firestore

#2944 Add validation for checking if a Screen Trace has non-positive totalFrames
  firebase-perf/src/main/java/com/google/firebase/perf/metrics/validator/FirebasePerfTraceValidator.java
  firebase-perf/src/test/java/com/google/firebase/perf/metrics/validator/FirebasePerfTraceValidatorTest.java
Labels: size/S, cla: yes

#2951 Fad api changes
  firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/FirebaseAppDistribution.java
  firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/FirebaseAppDistributionNotificationsManager.java
  firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/FirebaseAppDistributionTesterApiClient.java
  firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/UpdateApkClient.java
  firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/UpdateProgress.java
  firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/UpdateStatus.java
  firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/UpdateTaskImpl.java
  firebase-app-distribution/src/test/java/com/google/firebase/appdistribution/FirebaseAppDistributionTest.java
Labels: size/L, cla: yes

#2948 Don't send placeholder FAC token to Cloud Functions
  firebase-functions/src/androidTest/java/com/google/firebase/functions/FirebaseContextProviderTest.java
  firebase-functions/src/androidTest/java/com/google/firebase/functions/TestInternalAppCheckTokenProvider.java
  firebase-functions/src/main/java/com/google/firebase/functions/FirebaseContextProvider.java
Labels: size/M, cla: yes

#2956 FAD Changing names to be more consistent with API council change request
  firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/CheckForNewReleaseClient.java
  firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/FirebaseAppDistribution.java
  firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/FirebaseAppDistributionTesterApiClient.java
  firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/ReleaseIdentifierStorage.java
  firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/UpdateApkClient.java
  firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/UpdateAppClient.java
  firebase-app-distribution/src/test/java/com/google/firebase/appdistribution/CheckForNewReleaseClientTest.java
  firebase-app-distribution/src/test/java/com/google/firebase/appdistribution/FirebaseAppDistributionTest.java
  firebase-app-distribution/src/test/java/com/google/firebase/appdistribution/FirebaseAppDistributionTesterApiClientTest.java
  firebase-app-distribution/src/test/java/com/google/firebase/appdistribution/UpdateAppClientTest.java
Labels: size/L, cla: yes

#2960 Remove index_value from primary key of index_entries
  firebase-firestore/firebase-firestore.gradle
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteSchema.java
Labels: size/XS, cla: yes, api: firestore

#2961 Revert removal of index_value
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteSchema.java
Labels: size/XS, cla: yes, api: firestore

#2950 Initial base classes for index backfill
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/ComponentProvider.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/FirestoreClient.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/MemoryComponentProvider.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/SQLiteComponentProvider.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/index/IndexEntry.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/IndexBackfiller.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/LocalStore.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/LruGarbageCollector.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLitePersistence.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/Scheduler.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/util/AsyncQueue.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/SQLiteIndexBackfillerTest.java
Labels: size/L, cla: yes

#2965 Fix bug where `cacheSizeBytes` was sometimes not initialized correctly in `FirebaseFirestoreSettings`
  firebase-firestore/CHANGELOG.md
  firebase-firestore/src/main/java/com/google/firebase/firestore/FirebaseFirestoreSettings.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/FirebaseFirestoreSettingsTest.java
Labels: size/M, cla: yes, api: firestore

#2969 Speed up SpecTest
  firebase-firestore/src/main/java/com/google/firebase/firestore/remote/Datastore.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/remote/MockDatastore.java
Labels: size/M, cla: yes, api: firestore

#2972 FAD fixing file provider path bug
  firebase-app-distribution/src/main/AndroidManifest.xml
  firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/InstallActivity.java
  firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/UpdateApkClient.java
  firebase-app-distribution/src/main/res/xml/appdistro_provider_paths.xml
Labels: size/M, cla: yes

#2968 Fireperf: create a random delay before initiating a remote config fetch.
  firebase-perf/src/main/java/com/google/firebase/perf/config/RemoteConfigManager.java
  firebase-perf/src/test/java/com/google/firebase/perf/config/RemoteConfigManagerTest.java
Labels: size/L, cla: yes

#2963 Index Evaluation
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/Bound.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/FieldFilter.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/Target.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/index/IndexByteEncoder.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/index/IndexEntry.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/IndexBackfiller.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/IndexManager.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/LocalSerializer.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/MemoryIndexManager.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteIndexManager.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteSchema.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/model/DocumentKey.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/model/FieldIndex.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/core/QueryTest.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/core/TargetTest.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/IndexManagerTestCase.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/SQLiteIndexBackfillerTest.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/SQLiteIndexManagerTest.java
  firebase-firestore/src/testUtil/java/com/google/firebase/firestore/testutil/TestUtil.java
Labels: size/XL, cla: yes, api: firestore

#2979 Tighten the query bounds
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/Target.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/index/FirestoreIndexValueWriter.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteIndexManager.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/model/DatabaseId.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/model/Values.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/core/TargetTest.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/model/ValuesTest.java
Labels: size/L, cla: yes, api: firestore

#2980 Add X-Android-Package and X-Android-Cert headers.
  appcheck/firebase-appcheck/src/main/java/com/google/firebase/appcheck/internal/NetworkClient.java
  appcheck/firebase-appcheck/src/test/java/com/google/firebase/appcheck/internal/NetworkClientTest.java
Labels: size/M, cla: yes

#2977 Add workflow to update Firebase C++ SDK deps when Android SDK "latest released version" changes
  .github/workflows/update-cpp-sdk-on-release.yml
Labels: size/M, cla: yes

#2981 Change Bound's before to inclusive
  firebase-firestore/src/main/java/com/google/firebase/firestore/Query.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/bundle/BundleSerializer.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/Bound.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/Query.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/Target.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteIndexManager.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/remote/RemoteSerializer.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/bundle/BundleSerializerTest.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/core/QueryTest.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/core/TargetTest.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/SQLiteIndexManagerTest.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/remote/RemoteSerializerTest.java
  firebase-firestore/src/testUtil/java/com/google/firebase/firestore/testutil/TestUtil.java
Labels: size/L, cla: yes, api: firestore

#2983 Remove FieldMask
  firebase-firestore/src/main/java/com/google/firebase/firestore/model/MutableDocument.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/model/mutation/DeleteMutation.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/model/mutation/FieldMask.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/model/mutation/Mutation.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/model/mutation/PatchMutation.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/model/mutation/SetMutation.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/model/mutation/VerifyMutation.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/model/MutationTest.java
Labels: size/L, cla: yes

#2984 add update time to FieldIndex
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/LocalSerializer.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteIndexManager.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/model/FieldIndex.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/model/TargetIndexMatcher.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/SQLiteIndexManagerTest.java
Labels: size/L, cla: yes, api: firestore

#2987 FAD Changing provider paths
  firebase-app-distribution/src/main/AndroidManifest.xml
  firebase-app-distribution/src/main/res/xml/firebase_app_distribution_provider_paths.xml
Labels: size/XS, cla: yes

#2988 Add headers to support Android-application restricted API keys
  firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/CheckForNewReleaseClient.java
  firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/FirebaseAppDistributionTesterApiClient.java
  firebase-app-distribution/src/test/java/com/google/firebase/appdistribution/CheckForNewReleaseClientTest.java
  firebase-app-distribution/src/test/java/com/google/firebase/appdistribution/FirebaseAppDistributionTesterApiClientTest.java
Labels: size/M, cla: yes

#2990 Fix typo
  firebase-crashlytics/src/test/java/com/google/firebase/crashlytics/internal/common/CrashlyticsControllerRobolectricTest.java
Labels: size/XS, cla: yes

#2991 FAD Fixing file provider conflict
  firebase-app-distribution/src/main/AndroidManifest.xml
  firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/FirebaseAppDistributionFileProvider.java
Labels: size/S, cla: yes

#2982 Run one instead of n queries
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteIndexManager.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/util/Util.java
Labels: size/L, cla: yes, api: firestore

#2993 Remove special handling in Mutations
  firebase-firestore/src/main/java/com/google/firebase/firestore/model/mutation/DeleteMutation.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/model/mutation/Mutation.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/model/mutation/PatchMutation.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/model/mutation/SetMutation.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/LocalStoreTestCase.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/model/MutationTest.java
Labels: size/M, cla: yes, api: firestore

#2986 Enable deferred installation of Crashlytics NDK signal handler.
  firebase-crashlytics-ndk/src/androidTest/java/com/google/firebase/crashlytics/ndk/FirebaseCrashlyticsNdkTest.java
  firebase-crashlytics-ndk/src/main/java/com/google/firebase/crashlytics/ndk/CrashlyticsNdkRegistrar.java
  firebase-crashlytics-ndk/src/main/java/com/google/firebase/crashlytics/ndk/FirebaseCrashlyticsNdk.java
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/CrashlyticsNativeComponentDeferredProxyTest.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/CrashlyticsNativeComponent.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/CrashlyticsNativeComponentDeferredProxy.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CommonUtils.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsController.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/unity/ResourceUnityVersionProvider.java
Labels: size/L, cla: yes

#2962 Overlay on top of mutation list
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/LocalDocumentsView.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/model/ObjectValue.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/model/mutation/DeleteMutation.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/model/mutation/Mutation.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/model/mutation/MutationBatch.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/model/mutation/PatchMutation.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/model/mutation/SetMutation.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/model/mutation/VerifyMutation.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/model/mutation/MutationTest.java
Labels: size/XL, cla: yes

#2994 Add logic to use the apk hash
  firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/CheckForNewReleaseClient.java
  firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/FirebaseAppDistributionTesterApiClient.java
  firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/UpdateApkClient.java
  firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/internal/AppDistributionReleaseInternal.java
  firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/internal/ReleaseIdentificationUtils.java
  firebase-app-distribution/src/test/assets/testApkReleaseResponse.json
  firebase-app-distribution/src/test/java/com/google/firebase/appdistribution/CheckForNewReleaseClientTest.java
  firebase-app-distribution/src/test/java/com/google/firebase/appdistribution/FirebaseAppDistributionTesterApiClientTest.java
Labels: size/L, cla: yes

#2999 Fad logs file provider
  firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/CheckForNewReleaseClient.java
  firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/FirebaseAppDistributionTesterApiClient.java
  firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/InstallActivity.java
  firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/LogWrapper.java
  firebase-app-distribution/src/main/java/com/google/firebase/appdistribution/internal/ReleaseIdentificationUtils.java
Labels: size/M, cla: yes

#2629 FDL getDynamicLink(Intent) method to accept null intent.
  firebase-dynamic-links/src/main/java/com/google/firebase/dynamiclinks/FirebaseDynamicLinks.java
  firebase-dynamic-links/src/main/java/com/google/firebase/dynamiclinks/internal/FirebaseDynamicLinksImpl.java
  firebase-dynamic-links/src/test/java/com/google/firebase/dynamiclinks/internal/FirebaseDynamicLinksImplTest.java
Labels: size/S, cla: yes

#3003 Remove unused code
  firebase-firestore/src/main/java/com/google/firebase/firestore/index/OrderedCodeReader.java
Labels: size/L, cla: yes, api: firestore

#2995 Add ordering to Index implementation
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/OrderBy.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/Target.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/index/IndexEntry.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/IndexBackfiller.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/LocalSerializer.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteIndexManager.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteSchema.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/model/FieldIndex.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/core/TargetTest.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/SQLiteIndexBackfillerTest.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/SQLiteIndexManagerTest.java
Labels: size/L, cla: yes

#3002 Fix IN filters
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteIndexManager.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteSchema.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/SQLiteIndexManagerTest.java
Labels: size/M, cla: yes, api: firestore

#3007 DocumentOverlays schema and scaffolding
  firebase-firestore/firebase-firestore.gradle
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/testutil/IntegrationTestUtil.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/DocumentOverlay.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/LocalSerializer.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/MemoryDocumentOverlay.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/MemoryPersistence.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/Persistence.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteDocumentOverlay.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLitePersistence.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteSchema.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/DocumentOverlayTestCase.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/MemoryDocumentOverlayTestCase.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/SQLiteDocumentOverlayTestCase.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/SQLiteSchemaTest.java
Labels: size/L, cla: yes

#3008 Move app start trace build logic into a non-main thread.
  firebase-perf/src/main/java/com/google/firebase/perf/metrics/AppStartTrace.java
  firebase-perf/src/test/java/com/google/firebase/perf/metrics/AppStartTraceTest.java
Labels: size/L, cla: yes
