Repository firebase/firebase-android-sdk, pull requests merged in 2022-06, with the labels that each got.

#3773 Fix javadoc post Gradle 6.9 upgrade.
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/JavadocPlugin.java
Labels: size/XS

#3771 Refactor FID logic into FirebaseAppDistributionTesterApiClient
  firebase-appdistribution/firebase-appdistribution.gradle
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/ErrorMessages.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionRegistrar.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionTesterApiClient.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/NewReleaseFetcher.java
  firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/AabUpdaterTest.java
  firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionTesterApiClientTest.java
  firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/NewReleaseFetcherTest.java
  firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/TestUtils.java
Labels: size/XL

#3768 Fireperf: significantly simplify android instrumentation tests
  firebase-perf/e2e-app/src/androidTest/java/com/google/firebase/testing/fireperf/FirebasePerformanceFragmentScreenTracesTest.java
  firebase-perf/e2e-app/src/androidTest/java/com/google/firebase/testing/fireperf/FirebasePerformanceScreenTracesTest.java
  firebase-perf/e2e-app/src/androidTest/java/com/google/firebase/testing/fireperf/FirebasePerformanceTest.java
  firebase-perf/e2e-app/src/main/java/com/google/firebase/testing/fireperf/FirebasePerfActivity.java
  firebase-perf/e2e-app/src/main/java/com/google/firebase/testing/fireperf/FirebasePerfScreenTracesActivity.java
  firebase-perf/e2e-app/src/main/java/com/google/firebase/testing/fireperf/FireperfUtils.java
  firebase-perf/e2e-app/src/main/java/com/google/firebase/testing/fireperf/NetworkRequestGenerator.java
  firebase-perf/e2e-app/src/main/java/com/google/firebase/testing/fireperf/SlowListAdapter.java
  firebase-perf/e2e-app/src/main/java/com/google/firebase/testing/fireperf/TraceGenerator.java
Labels: size/L

#3778 Add in-app feedback requests to FirebaseAppDistributionTesterApiClient
  firebase-appdistribution-api/src/main/java/com/google/firebase/appdistribution/FirebaseAppDistributionException.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/ErrorMessages.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionImpl.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionRegistrar.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionTesterApiClient.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/TesterApiHttpClient.java
  firebase-appdistribution/src/test/assets/testSimpleResponse.json
  firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionServiceImplTest.java
  firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionTesterApiClientTest.java
  firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/TestUtils.java
  firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/TesterApiHttpClientTest.java
Labels: size/XXL

#3769 Fixes NullPointerException at updateFidListener
  firebase-installations/src/main/java/com/google/firebase/installations/FirebaseInstallations.java
Labels: size/XS

#3783 Add POST_NOTIFICATIONS permission for Android 13/T.
  firebase-messaging/src/main/AndroidManifest.xml
Labels: size/XS

#3789 Move transaction options to right release
  firebase-firestore/CHANGELOG.md
Labels: size/XS

#3797 Refactor IndexBackfiller constructor
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/remote/RemoteStoreTest.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/ComponentProvider.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/MemoryComponentProvider.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/SQLiteComponentProvider.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/IndexBackfiller.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/LocalStore.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/util/Assert.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/IndexBackfillerTest.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/LocalStoreTestCase.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/SQLiteOverlayMigrationManagerTest.java
Labels: size/L

#3743 Rc realtime dev
  firebase-config/api.txt
  firebase-config/src/main/java/com/google/firebase/remoteconfig/FirebaseRemoteConfigRealtimeUpdateFetchException.java
  firebase-config/src/main/java/com/google/firebase/remoteconfig/FirebaseRemoteConfigRealtimeUpdateStreamException.java
  firebase-config/src/main/java/com/google/firebase/remoteconfig/RemoteConfigConstants.java
  firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigAutoFetch.java
  firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigContainer.java
  firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigFetchHandler.java
  firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigFetchHttpClient.java
  firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigRealtimeHttpClient.java
  firebase-config/src/test/java/com/google/firebase/remoteconfig/FirebaseRemoteConfigTest.java
Labels: size/XL

#3807 Refactor out ReleaseIdentifier
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionImpl.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionRegistrar.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/NewReleaseFetcher.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/PackageInfoUtils.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/ReleaseIdentifier.java
  firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/ApkHashExtractorTest.java
  firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionServiceImplTest.java
  firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/NewReleaseFetcherTest.java
  firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/ReleaseIdentifierTest.java
Labels: size/L

#3809 Remove unnecessary type param
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionLifecycleNotifier.java
Labels: size/XS

#3794 Serving OR Queries from the client-side index.
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteIndexManager.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/QueryEngineTestCase.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/SQLiteIndexManagerTest.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/SQLiteQueryEngineTest.java
Labels: size/L

#3810 Add upload request to TesterApiHttpClient
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/TesterApiHttpClient.java
  firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/TesterApiHttpClientTest.java
Labels: size/L

#3814 Add uploadScreenshot to FirebaseAppDistributionTesterApiClient
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionTesterApiClient.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/TesterApiHttpClient.java
  firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionTesterApiClientTest.java
  firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/TestUtils.java
  firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/TesterApiHttpClientTest.java
Labels: size/L

#3811 added pending intent mutability
  transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/scheduling/jobscheduling/AlarmManagerScheduler.java
Labels: size/S

#3817 Ywmei/parallel unit tests
  firebase-firestore/firebase-firestore.gradle
  firebase-firestore/ktx/ktx.gradle
Labels: size/XS

#3816 Implement collectAndSendFeedback()
  firebase-appdistribution-api/api.txt
  firebase-appdistribution-api/src/main/java/com/google/firebase/appdistribution/FirebaseAppDistribution.java
  firebase-appdistribution-api/src/main/java/com/google/firebase/appdistribution/UpdateProgress.java
  firebase-appdistribution-api/src/main/java/com/google/firebase/appdistribution/internal/FirebaseAppDistributionProxy.java
  firebase-appdistribution-api/src/main/java/com/google/firebase/appdistribution/internal/FirebaseAppDistributionStub.java
  firebase-appdistribution/firebase-appdistribution.gradle
  firebase-appdistribution/src/main/AndroidManifest.xml
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/ErrorMessages.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FeedbackActivity.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FeedbackSender.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionImpl.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionRegistrar.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/ReleaseIdentifier.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/ScreenshotTaker.java
  firebase-appdistribution/src/main/res/layout/activity_feedback.xml
  firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/FeedbackSenderTest.java
  firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionServiceImplTest.java
  firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/TesterApiHttpClientTest.java
Labels: size/L

#3818 Change comments and test instances in QueryEngine
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/QueryEngine.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/QueryEngineTestCase.java
Labels: size/S

#3801 Ywmei/windows build
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/license/ThirdPartyLicensesExtension.java
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/publish/PublishingPlugin.java
  buildSrc/src/test/kotlin/com/google/firebase/gradle/plugins/LicenseResolverPluginTests.kt
  firebase-crashlytics-ndk/firebase-crashlytics-ndk.gradle
  firebase-crashlytics/firebase-crashlytics.gradle
  firebase-inappmessaging-display/firebase-inappmessaging-display.gradle
  firebase-inappmessaging/firebase-inappmessaging.gradle
  transport/transport-runtime/transport-runtime.gradle
Labels: size/M

#3822 Changing condition statement API version < 26 for log limit
  transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/logging/Logging.java
Labels: size/XS

#3812 Update the orderBy filtering mechanism for OR queries.
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/Query.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/QueryEngineTestCase.java
Labels: size/M

#3831 Add support for return values to applyToForegroundActivity()
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/AabUpdater.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionImpl.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionLifecycleNotifier.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/TesterSignInManager.java
  firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/AabUpdaterTest.java
  firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/ApkUpdaterTest.java
  firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionLifecycleNotifierTest.java
  firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionServiceImplTest.java
  firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/TestUtils.java
  firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/TesterSignInManagerTest.java
Labels: size/L

#3840 Remove Android ID check heuristic from isEmulator check.
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/CommonUtilsTest.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CommonUtils.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsController.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsReportDataCapture.java
Labels: size/M

#3835 Take actual screenshots when giving feedback
  firebase-appdistribution/firebase-appdistribution.gradle
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FeedbackActivity.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FeedbackSender.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionImpl.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionRegistrar.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionTesterApiClient.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/ImageUtils.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/ScreenshotTaker.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/TesterApiHttpClient.java
  firebase-appdistribution/src/main/res/layout/activity_feedback.xml
  firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/FeedbackSenderTest.java
  firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionServiceImplTest.java
  firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionTesterApiClientTest.java
  firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/ImageUtilsTest.java
  firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/NewReleaseFetcherTest.java
  firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/ScreenshotTakerTest.java
  firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/TestOnCompleteListener.java
  firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/TestUtils.java
  firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/TesterApiHttpClientTest.java
  firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/TesterSignInManagerTest.java
Labels: size/XL

#3837 Rename keep.xml to avoid merge conflict with dynamic features
  firebase-common/src/main/res/raw/firebase_common_keep.xml
Labels: size/XS, ok-to-test

#3841 Update IDE URL to troubleshooting page
  firebase-perf/src/main/java/com/google/firebase/perf/logging/ConsoleUrlGenerator.java
  firebase-perf/src/test/java/com/google/firebase/perf/logging/ConsoleUrlGeneratorTest.java
Labels: size/XS

#3827 Firestore Apple Silicon fixes.
  firebase-firestore/firebase-firestore.gradle
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/LoadBundleTaskTest.java
Labels: size/L

#3854 Increase the Data Transfer read timeout default to 130 seconds
  transport/transport-backend-cct/src/main/java/com/google/android/datatransport/cct/CctTransportBackend.java
Labels: size/XS

#3808 Rc realtime dev
  firebase-config/api.txt
  firebase-config/ktx/src/test/kotlin/com/google/firebase/remoteconfig/TestConstructorUtil.kt
  firebase-config/ktx/src/test/kotlin/com/google/firebase/remoteconfig/ktx/RemoteConfigTests.kt
  firebase-config/src/androidTest/java/com/google/firebase/remoteconfig/FirebaseRemoteConfigIntegrationTest.java
  firebase-config/src/main/java/com/google/firebase/remoteconfig/FirebaseRemoteConfig.java
  firebase-config/src/main/java/com/google/firebase/remoteconfig/RemoteConfigComponent.java
  firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigAutoFetch.java
  firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigRealtimeHttpClient.java
  firebase-config/src/test/java/com/google/firebase/remoteconfig/FirebaseRemoteConfigTest.java
Labels: size/L
