Repository firebase/firebase-android-sdk, pull requests merged in 2022-08, with the labels that each got.

#3955 Upgrade numpy version to 1.23.1
  ci/README.md
  ci/fireci/setup.cfg
Labels: size/XS

#3959 Clean up code in IndexBackfiller
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/IndexBackfillerTest.java
Labels: size/XS

#3961 Install NDK r21 on GitHub Actions
  .github/workflows/ci_tests_experimental.yml
Labels: size/S

#3960 Add workflow definition for smoke tests
  .github/workflows/smoke-tests.yml
Labels: size/M

#3967 Add an extension point to ComponentRuntime.
  firebase-components/src/main/java/com/google/firebase/components/Component.java
  firebase-components/src/main/java/com/google/firebase/components/ComponentRegistrarProcessor.java
  firebase-components/src/main/java/com/google/firebase/components/ComponentRuntime.java
  firebase-components/src/test/java/com/google/firebase/components/ComponentRuntimeTest.java
  firebase-components/src/test/java/com/google/firebase/components/ComponentTest.java
Labels: size/L

#3964 Fix transport telemetry support
  transport/transport-runtime/src/androidTest/java/com/google/android/datatransport/runtime/scheduling/persistence/SQLiteEventStoreTest.java
  transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/scheduling/jobscheduling/SchedulerConfig.java
  transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/scheduling/persistence/EventStore.java
  transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/scheduling/persistence/SQLiteEventStore.java
Labels: size/M

#3971 Add info text argument to startFeedback
  firebase-appdistribution-api/api.txt
  firebase-appdistribution-api/src/main/java/com/google/firebase/appdistribution/FirebaseAppDistribution.java
  firebase-appdistribution-api/src/main/java/com/google/firebase/appdistribution/internal/FirebaseAppDistributionProxy.java
  firebase-appdistribution-api/src/main/java/com/google/firebase/appdistribution/internal/FirebaseAppDistributionStub.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FeedbackActivity.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionImpl.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionRegistrar.java
  firebase-appdistribution/src/main/res/layout/activity_feedback.xml
  firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionServiceImplTest.java
  firebase-appdistribution/test-app/src/main/java/com/googletest/firebase/appdistribution/testapp/MainActivity.kt
  firebase-appdistribution/test-app/src/main/res/values/strings.xml
Labels: size/L

#3976 Make @PreviewApi a documented annotation.
  firebase-annotations/src/main/java/com/google/firebase/annotations/PreviewApi.java
Labels: size/XS

#3970 Enable api-information check on GitHub Actions
  .github/workflows/api-information.yml
Labels: size/M

#3973 Remove Firebase Predictions from the Firebase installation ID delete …
  firebase-installations-interop/src/main/java/com/google/firebase/installations/FirebaseInstallationsApi.java
  firebase-installations/src/main/java/com/google/firebase/installations/FirebaseInstallations.java
Labels: size/XS

#3985 Update project.path var to new location.
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/JavadocPlugin.java
Labels: size/XS

#3969 Add workflow definition for fireperf end-to-end tests
  .github/workflows/fireperf-e2e.yml
  ci/fireci/fireciplugins/fireperf.py
Labels: size/L

#1252 Add 'toFlow()' extensions to DocumentSnapshot and Query
  firebase-firestore/ktx/api.txt
  firebase-firestore/ktx/ktx.gradle
  firebase-firestore/ktx/src/main/kotlin/com/google/firebase/firestore/ktx/Firestore.kt
Labels: size/M, cla: yes, ok-to-test

#3978 Enable oss master to private main branch sync on GitHub Actions
  .github/workflows/private-mirror-sync.yml
Labels: size/S

#3902 Add OR Query integration tests and check matching online and offline behavior
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/QueryTest.java
Labels: size/L

#3889 Tests for OR queries with IN, NOT-IN, ARRAY-CONTAINS, ARRAY-CONTAINS-ANY
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/QueryEngineTestCase.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/SQLiteQueryEngineTest.java
Labels: size/L

#3988 Fix sync job between OSS and private repository
  .github/workflows/private-mirror-sync.yml
Labels: size/XS

#3954 Add workflow definition for health metric tests
  .github/workflows/health-metrics.yml
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/ci/AffectedProjectFinder.java
  ci/fireci/fireci/ci_utils.py
  ci/fireci/fireci/uploader.py
  ci/fireci/fireciplugins/binary_size.py
  ci/fireci/fireciplugins/coverage.py
  ci/fireci/fireciplugins/macrobenchmark.py
  health-metrics/apk-size/gradle.properties
Labels: size/L

#3965 Realtime rc failsafe
  firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigAutoFetch.java
  firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigRealtimeHttpClient.java
  firebase-config/src/test/java/com/google/firebase/remoteconfig/FirebaseRemoteConfigTest.java
Labels: size/L

#3996 Remove obsolete build cache.
  buildSrc/settings.gradle
  gradle/buildCache.gradle
  settings.gradle
Labels: size/M

#3993 fix perf apps unit tests
  firebase-perf/dev-app/dev-app.gradle
  firebase-perf/e2e-app/e2e-app.gradle
  gradle/googleServices.gradle
Labels: size/XS

#3994 Create Gradle cache-compliant metalava tasks.
  appcheck/firebase-appcheck/ktx/api.txt
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/FirebaseJavaLibraryPlugin.java
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/FirebaseLibraryPlugin.java
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/Metalava.kt
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/apiinfo/ApiInformationTask.java
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/apiinfo/GenerateApiTxtFileTask.java
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/apiinfo/GetMetalavaJarTask.java
  encoders/firebase-encoders-proto/api.txt
  firebase-appdistribution-api/ktx/api.txt
  firebase-common/ktx/api.txt
  firebase-config/ktx/api.txt
  firebase-crashlytics/ktx/api.txt
  firebase-database/ktx/api.txt
  firebase-dynamic-links/api.txt
  firebase-dynamic-links/ktx/api.txt
  firebase-firestore/api.txt
  firebase-firestore/ktx/api.txt
  firebase-functions/ktx/api.txt
  firebase-inappmessaging-display/ktx/api.txt
  firebase-inappmessaging/ktx/api.txt
  firebase-installations-interop/api.txt
  firebase-installations/ktx/api.txt
  firebase-messaging/api.txt
  firebase-messaging/ktx/api.txt
  firebase-ml-modeldownloader/ktx/api.txt
  firebase-perf/api.txt
  firebase-perf/ktx/api.txt
  firebase-storage/api.txt
  firebase-storage/ktx/api.txt
Labels: size/XL

#3995 Fix vendoring plugin issues in future AGP versions
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/VendorPlugin.kt
  firebase-inappmessaging/src/androidTest/java/com/google/firebase/inappmessaging/TestApiClientModule.java
  firebase-inappmessaging/src/main/java/com/google/firebase/inappmessaging/internal/ApiClient.java
  firebase-inappmessaging/src/main/java/com/google/firebase/inappmessaging/internal/injection/modules/ApiClientModule.java
  transport/transport-runtime/src/androidTest/java/com/google/android/datatransport/runtime/scheduling/persistence/SQLiteEventStoreTest.java
  transport/transport-runtime/src/androidTest/java/com/google/android/datatransport/runtime/scheduling/persistence/SpyEventStoreModule.java
  transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/scheduling/persistence/EventStoreModule.java
  transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/scheduling/persistence/SQLiteEventStore.java
  transport/transport-runtime/src/test/java/com/google/android/datatransport/runtime/scheduling/persistence/SchemaManagerTest.java
Labels: size/M

#3999 Use kotlin script for buildSrc gradle file.
  .github/workflows/build-src-check.yml
  buildSrc/build.gradle
  buildSrc/build.gradle.kts
  buildSrc/settings.gradle.kts
Labels: size/L

#3997 Use more explanatory name for API information job
  .github/workflows/api-information.yml
Labels: size/XS

#3962 Fixed get() to propagate events to listeners
  firebase-database/src/androidTest/java/com/google/firebase/database/IntegrationTestHelpers.java
  firebase-database/src/androidTest/java/com/google/firebase/database/QueryTest.java
  firebase-database/src/main/java/com/google/firebase/database/core/Repo.java
  firebase-database/src/main/java/com/google/firebase/database/core/SyncTree.java
Labels: size/XL

#4000 bump versions of play-services-basement for release
  firebase-abt/firebase-abt.gradle
  firebase-common/firebase-common.gradle
  firebase-config/bandwagoner/bandwagoner.gradle
  firebase-crashlytics-ndk/firebase-crashlytics-ndk.gradle
  firebase-database/firebase-database.gradle
  firebase-dynamic-links/firebase-dynamic-links.gradle
  firebase-firestore/firebase-firestore.gradle
  firebase-firestore/ktx/ktx.gradle
  firebase-functions/firebase-functions.gradle
  firebase-messaging/firebase-messaging.gradle
  firebase-messaging/ktx/ktx.gradle
  firebase-storage/test-app/test-app.gradle
Labels: size/S

#4002 Use the more common stdlib dep now that we ship java8 bytecode.
  appcheck/firebase-appcheck/ktx/ktx.gradle
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/Dokka.java
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/publish/Publisher.java
  firebase-appdistribution-api/ktx/ktx.gradle
  firebase-common/firebase-common.gradle
  firebase-config/ktx/ktx.gradle
  firebase-crashlytics/ktx/ktx.gradle
  firebase-database/ktx/ktx.gradle
  firebase-dynamic-links/ktx/ktx.gradle
  firebase-firestore/ktx/ktx.gradle
  firebase-functions/ktx/ktx.gradle
  firebase-inappmessaging-display/ktx/ktx.gradle
  firebase-inappmessaging/ktx/ktx.gradle
  firebase-installations/ktx/ktx.gradle
  firebase-messaging/ktx/ktx.gradle
  firebase-ml-modeldownloader/ktx/ktx.gradle
  firebase-perf/ktx/ktx.gradle
  firebase-storage/ktx/ktx.gradle
Labels: size/M

#4003 add FirebaseAppCheckKtxRegistrar to appcheck-ktx
  appcheck/firebase-appcheck/ktx/src/main/kotlin/com/google/firebase/appcheck/ktx/FirebaseAppCheck.kt
Labels: size/S

#3986 Add basic component initialization tracing
  firebase-common/src/main/java/com/google/firebase/FirebaseApp.java
  firebase-common/src/main/java/com/google/firebase/tracing/ComponentMonitor.java
  firebase-common/src/main/java/com/google/firebase/tracing/FirebaseTrace.java
  firebase-common/src/main/java/com/google/firebase/tracing/package-info.java
  firebase-common/src/test/java/com/google/firebase/tracing/ComponentMonitorTest.java
Labels: size/L

#4016 Prevent gradle daemon from crashing
  smoke-tests/gradle.properties
Labels: size/XS

#4019 Fix robolectric SQLite issue with Apple Silicon
  firebase-firestore/firebase-firestore.gradle
Labels: size/XS

#4022 Configure artifact upload for workflows
  .github/workflows/fireperf-e2e.yml
  .github/workflows/smoke-tests.yml
Labels: size/S

#4023 Add a new plugin for Dackka
  appcheck/firebase-appcheck/ktx/src/main/kotlin/com/google/firebase/appcheck/ktx/FirebaseAppCheck.kt
  build.gradle
  buildSrc/build.gradle.kts
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/DackkaGenerationTask.kt
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/DackkaPlugin.kt
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/FirebaseLibraryPlugin.java
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/FiresiteTransformTask.kt
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/JavadocPlugin.java
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/KotlinUtils.kt
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/ProjectUtils.kt
  buildSrc/src/test/kotlin/com/google/firebase/gradle/plugins/PublishingPluginTests.kt
  firebase-firestore/src/main/java/com/google/firebase/firestore/DocumentId.java
  firebase-inappmessaging/src/main/java/com/google/firebase/inappmessaging/FirebaseInAppMessaging.java
  firebase-inappmessaging/src/main/java/com/google/firebase/inappmessaging/model/CampaignMetadata.java
Labels: size/XL

#4027 [Fireperf] Fix `RateLimiter` by avoiding manually setting time
  firebase-perf/src/main/java/com/google/firebase/perf/transport/RateLimiter.java
  firebase-perf/src/test/java/com/google/firebase/perf/transport/RateLimiterTest.java
Labels: size/L

#3975 Upgrade gRPC and remove OkHttp dependency
  build.gradle
  firebase-firestore/firebase-firestore.gradle
Labels: size/XS

#3847 Online Count with tentative package private api
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/CountTest.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/AggregateQuery.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/AggregateQuerySnapshot.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/AggregateSource.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/Query.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/FirestoreClient.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/SyncEngine.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/remote/Datastore.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/remote/RemoteStore.java
  firebase-firestore/src/proto/google/firestore/v1/aggregation_result.proto
  firebase-firestore/src/proto/google/firestore/v1/firestore.proto
  firebase-firestore/src/proto/google/firestore/v1/query.proto
  firebase-firestore/src/test/java/com/google/firebase/firestore/AggregateQueryTest.java
Labels: size/XL

#3992 fix synchrnoized wrong object while manipulating appColdStartSubscribers
  firebase-perf/src/main/java/com/google/firebase/perf/application/AppStateMonitor.java
Labels: size/XS, ok-to-test

#4037 Only reset retries when the realtime connection successfully opens.
  firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigRealtimeHttpClient.java
Labels: size/M

#4017 Work around an upcoming JDK change.
  firebase-messaging/src/test/java/com/google/firebase/iid/FirebaseInstanceIdWithFcmReceiverRoboTest.java
Labels: size/S

#4038 Upgrade count upto to use int64
  firebase-firestore/src/proto/google/firestore/v1/query.proto
Labels: size/XS

#4043 Clean up unused methods.
  firebase-messaging/src/main/java/com/google/firebase/messaging/CommonNotificationBuilder.java
  firebase-messaging/src/main/java/com/google/firebase/messaging/FcmBroadcastProcessor.java
Labels: size/M

#4018 Implement CHANGELOG check
  .github/workflows/changelog.yml
  ci/danger/Dangerfile
  ci/danger/Gemfile
  ci/danger/Gemfile.lock
  ci/danger/setup_bundler.sh
Labels: size/L
