Repository firebase/firebase-android-sdk, pull requests merged in 2022-04, with the labels that each got.

#3607 Initial App Check <> Play Integrity commit
  appcheck/firebase-appcheck-playintegrity/firebase-appcheck-playintegrity.gradle
  appcheck/firebase-appcheck-playintegrity/gradle.properties
  appcheck/firebase-appcheck-playintegrity/src/main/AndroidManifest.xml
  appcheck/firebase-appcheck-playintegrity/src/main/java/com/google/firebase/appcheck/playintegrity/PlayIntegrityAppCheckProviderFactory.java
  appcheck/firebase-appcheck-playintegrity/src/main/java/com/google/firebase/appcheck/playintegrity/internal/PlayIntegrityAppCheckProvider.java
  subprojects.cfg
Labels: size/L

#3612 Adding support for serializing URIs and URLs
  firebase-firestore/src/main/java/com/google/firebase/firestore/util/CustomClassMapper.java
Labels: size/XS, ok-to-test

#3619 specify export in main activity to support api 32
  firebase-appdistribution/test-app/release/test-app.aab
  firebase-appdistribution/test-app/src/main/AndroidManifest.xml
Labels: size/XS

#3614 Fix App Check version numbers in `gradle.properties`
  appcheck/firebase-appcheck-debug-testing/gradle.properties
  appcheck/firebase-appcheck-debug/gradle.properties
  appcheck/firebase-appcheck-interop/gradle.properties
  appcheck/firebase-appcheck-safetynet/gradle.properties
  appcheck/firebase-appcheck/gradle.properties
Labels: size/S

#3609 Fix validation bug for composite filters.
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/ValidationTest.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/Query.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/CompositeFilter.java
Labels: size/L

#3616 Add Changelog for #3612
  firebase-firestore/CHANGELOG.md
Labels: size/XS, api: firestore

#3618 Implement Play Integrity attestation flow.
  appcheck/firebase-appcheck-playintegrity/src/main/java/com/google/firebase/appcheck/playintegrity/internal/GeneratePlayIntegrityChallengeRequest.java
  appcheck/firebase-appcheck-playintegrity/src/main/java/com/google/firebase/appcheck/playintegrity/internal/GeneratePlayIntegrityChallengeResponse.java
  appcheck/firebase-appcheck-playintegrity/src/main/java/com/google/firebase/appcheck/playintegrity/internal/PlayIntegrityAppCheckProvider.java
  appcheck/firebase-appcheck-playintegrity/src/test/java/com/google/firebase/appcheck/playintegrity/internal/GeneratePlayIntegrityChallengeRequestTest.java
  appcheck/firebase-appcheck-playintegrity/src/test/java/com/google/firebase/appcheck/playintegrity/internal/GeneratePlayIntegrityChallengeResponseTest.java
  appcheck/firebase-appcheck-playintegrity/src/test/java/com/google/firebase/appcheck/playintegrity/internal/PlayIntegrityAppCheckProviderTest.java
  appcheck/firebase-appcheck/src/main/java/com/google/firebase/appcheck/internal/NetworkClient.java
  appcheck/firebase-appcheck/src/test/java/com/google/firebase/appcheck/internal/NetworkClientTest.java
Labels: size/XL

#3625 Simplify Crashlytics settings
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/CrashlyticsControllerTest.java
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/CrashlyticsCoreInitializationTest.java
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/CrashlyticsCoreTest.java
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/persistence/CrashlyticsReportPersistenceTest.java
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/settings/DefaultSettingsControllerTest.java
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/settings/DefaultSettingsJsonTransformTest.java
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/settings/DefaultSettingsSpiCallTest.java
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/settings/SettingsJsonParserTest.java
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/settings/SettingsV3JsonTransformTest.java
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/settings/TestSettings.java
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/settings/TestSettingsData.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsController.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsCore.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsUncaughtExceptionHandler.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/SessionReportingCoordinator.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/persistence/CrashlyticsReportPersistence.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/send/DataTransportCrashlyticsReportSender.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/send/ReportQueue.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/settings/DefaultSettingsJsonTransform.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/settings/DefaultSettingsSpiCall.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/settings/Settings.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/settings/SettingsController.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/settings/SettingsJsonConstants.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/settings/SettingsJsonParser.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/settings/SettingsJsonTransform.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/settings/SettingsProvider.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/settings/SettingsRequest.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/settings/SettingsSpiCall.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/settings/SettingsV3JsonTransform.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/settings/model/AppSettingsData.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/settings/model/FeaturesSettingsData.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/settings/model/Settings.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/settings/model/SettingsRequest.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/settings/model/package-info.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/settings/network/SettingsSpiCall.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/settings/network/package-info.java
  firebase-crashlytics/src/test/java/com/google/firebase/crashlytics/internal/common/CrashlyticsControllerRobolectricTest.java
Labels: size/XXL

#3591 Fireperf: Add Fragment Screen Performance Support
  firebase-perf/CHANGELOG.md
  firebase-perf/dev-app/src/main/AndroidManifest.xml
  firebase-perf/e2e-app/src/main/AndroidManifest.xml
  firebase-perf/src/main/java/com/google/firebase/perf/application/AppStateMonitor.java
  firebase-perf/src/main/java/com/google/firebase/perf/application/FragmentStateMonitor.java
  firebase-perf/src/main/java/com/google/firebase/perf/config/ConfigResolver.java
  firebase-perf/src/main/java/com/google/firebase/perf/config/ConfigurationConstants.java
  firebase-perf/src/main/java/com/google/firebase/perf/metrics/FrameMetricsCalculator.java
  firebase-perf/src/main/java/com/google/firebase/perf/metrics/Trace.java
  firebase-perf/src/main/java/com/google/firebase/perf/transport/RateLimiter.java
  firebase-perf/src/main/java/com/google/firebase/perf/util/Constants.java
  firebase-perf/src/main/java/com/google/firebase/perf/util/ScreenTraceUtil.java
  firebase-perf/src/test/java/com/google/firebase/perf/application/FragmentStateMonitorTest.java
  firebase-perf/src/test/java/com/google/firebase/perf/config/ConfigResolverTest.java
  firebase-perf/src/test/java/com/google/firebase/perf/config/ConfigurationConstantsTest.java
  firebase-perf/src/test/java/com/google/firebase/perf/metrics/FrameMetricsCalculatorTest.java
  firebase-perf/src/test/java/com/google/firebase/perf/transport/RateLimiterTest.java
Labels: size/XXL

#3631 Check for a specific flutter asset file instead of listing the path
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/DevelopmentPlatformProviderTest.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/DevelopmentPlatformProvider.java
Labels: size/S

#3623 Fix overlay bug with multiple field patches
  firebase-firestore/CHANGELOG.md
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/LocalDocumentsResult.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/LocalDocumentsView.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/LocalStore.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/OverlayedDocument.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/model/mutation/DeleteMutation.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/model/mutation/Mutation.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/model/mutation/MutationBatch.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/model/mutation/PatchMutation.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/model/mutation/SetMutation.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/model/mutation/VerifyMutation.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/remote/RemoteSerializer.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/LocalStoreTestCase.java
Labels: size/L

#3636 Use correct proto encoding
  firebase-messaging/src/main/java/com/google/firebase/messaging/MessagingAnalytics.java
Labels: size/XS

#3622 SDK support for logical termination in Firestore BatchGetDocuments
  firebase-firestore/src/main/java/com/google/firebase/firestore/remote/Datastore.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/remote/FirestoreChannel.java
Labels: size/M

#3638 Fireperf: trigger `sendScreenTrace` by starting new activity in `FirebasePerformanceScreenTracesTest`
  firebase-perf/e2e-app/src/androidTest/java/com/google/firebase/testing/fireperf/FirebasePerformanceScreenTracesTest.java
Labels: size/S

#3583 Do not apply SQL LIMIT if a partial index is used.
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/Target.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/IndexManager.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/MemoryIndexManager.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/QueryEngine.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteIndexManager.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/model/TargetIndexMatcher.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/SQLiteIndexManagerTest.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/SQLiteQueryEngineTest.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/model/TargetIndexMatcherTest.java
Labels: size/L

#3479 - Changes to protoc version to make it working for m1 macs.
  build.gradle
Labels: size/XS

#3644 Simplify segment count calculation
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteIndexManager.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/model/TargetIndexMatcher.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/model/TargetIndexMatcherTest.java
Labels: size/M, api: firestore

#3645 Timeout when blocking tasks on any thread.
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsController.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/Utils.java
Labels: size/S

#3646 QueryEngine clean up
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/QueryEngine.java
Labels: size/XS

#3650 Move getIndexType() test
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/SQLiteIndexManagerTest.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/SQLiteQueryEngineTest.java
Labels: size/L, api: firestore

#3655 Update test app.
  appcheck/firebase-appcheck/test-app/src/main/java/com/googletest/firebase/appcheck/MainActivity.java
  appcheck/firebase-appcheck/test-app/src/main/res/layout/activity_main.xml
  appcheck/firebase-appcheck/test-app/src/main/res/values/strings.xml
  appcheck/firebase-appcheck/test-app/test-app.gradle
Labels: size/S

#3656 Return the minimum index type from all targets
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/IndexManager.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteIndexManager.java
Labels: size/S

#3627 Update App Check SDKs to use `v1` API.
  appcheck/firebase-appcheck-debug-testing/gradle.properties
  appcheck/firebase-appcheck-debug/gradle.properties
  appcheck/firebase-appcheck-debug/src/test/java/com/google/firebase/appcheck/debug/internal/DebugAppCheckProviderTest.java
  appcheck/firebase-appcheck-interop/gradle.properties
  appcheck/firebase-appcheck-safetynet/gradle.properties
  appcheck/firebase-appcheck-safetynet/src/test/java/com/google/firebase/appcheck/safetynet/internal/SafetyNetAppCheckProviderTest.java
  appcheck/firebase-appcheck/gradle.properties
  appcheck/firebase-appcheck/src/main/java/com/google/firebase/appcheck/internal/AppCheckTokenResponse.java
  appcheck/firebase-appcheck/src/main/java/com/google/firebase/appcheck/internal/DefaultAppCheckToken.java
  appcheck/firebase-appcheck/src/main/java/com/google/firebase/appcheck/internal/NetworkClient.java
  appcheck/firebase-appcheck/src/test/java/com/google/firebase/appcheck/internal/AppCheckTokenResponseTest.java
  appcheck/firebase-appcheck/src/test/java/com/google/firebase/appcheck/internal/DefaultAppCheckTokenTest.java
  appcheck/firebase-appcheck/src/test/java/com/google/firebase/appcheck/internal/NetworkClientTest.java
Labels: size/M

#3654 Test rename
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/SQLiteIndexManagerTest.java
Labels: size/XS, api: firestore

#3649 More comment fixes
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/QueryEngine.java
Labels: size/XS, api: firestore

#3659 Add FirebaseFunctions.getHttpsCallableFromURL
  firebase-functions/api.txt
  firebase-functions/src/main/java/com/google/firebase/functions/FirebaseFunctions.java
  firebase-functions/src/main/java/com/google/firebase/functions/HttpsCallableReference.java
Labels: size/M

#3653 Add first-open time to Remote Config fetch request.
  firebase-config/src/main/java/com/google/firebase/remoteconfig/RemoteConfigConstants.java
  firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigFetchHandler.java
  firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigFetchHttpClient.java
  firebase-config/src/test/java/com/google/firebase/remoteconfig/internal/ConfigFetchHandlerTest.java
  firebase-config/src/test/java/com/google/firebase/remoteconfig/internal/ConfigFetchHttpClientTest.java
Labels: size/L

#3663 Add keeps for strict resource shrinking.
  firebase-common/src/main/res/raw/keep.xml
Labels: size/XS

#3668 Fix a bug with limitToLast and cursors
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/QueryTest.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/Query.java
Labels: size/M

#3660 Skip custom attributes when the length of the key or the value is 0
  firebase-perf/CHANGELOG.md
  firebase-perf/src/main/java/com/google/firebase/perf/FirebasePerformance.java
  firebase-perf/src/main/java/com/google/firebase/perf/metrics/HttpMetric.java
  firebase-perf/src/main/java/com/google/firebase/perf/metrics/Trace.java
  firebase-perf/src/main/java/com/google/firebase/perf/metrics/validator/FirebasePerfTraceValidator.java
  firebase-perf/src/main/java/com/google/firebase/perf/metrics/validator/PerfMetricValidator.java
  firebase-perf/src/test/java/com/google/firebase/perf/metrics/validator/FirebasePerfTraceValidatorTest.java
Labels: size/L

#3669 Add user agents for fdl, appcheck debug, safetynet and play integrity
  appcheck/firebase-appcheck-debug/src/main/AndroidManifest.xml
  appcheck/firebase-appcheck-debug/src/main/java/com/google/firebase/appcheck/debug/FirebaseAppCheckDebugRegistrar.java
  appcheck/firebase-appcheck-playintegrity/src/main/AndroidManifest.xml
  appcheck/firebase-appcheck-playintegrity/src/main/java/com/google/firebase/appcheck/playintegrity/FirebaseAppCheckPlayIntegrityRegistrar.java
  appcheck/firebase-appcheck-safetynet/src/main/AndroidManifest.xml
  appcheck/firebase-appcheck-safetynet/src/main/java/com/google/firebase/appcheck/safetynet/FirebaseAppCheckSafetyNetRegistrar.java
  firebase-dynamic-links/src/main/java/com/google/firebase/dynamiclinks/internal/FirebaseDynamicLinkRegistrar.java
Labels: size/L

#3670 Add better testing support for TransportRuntime.
  subprojects.cfg
  transport/transport-runtime-testing/src/main/AndroidManifest.xml
  transport/transport-runtime-testing/src/main/java/com/google/android/datatransport/runtime/TransportRuntimeTesting.java
  transport/transport-runtime-testing/src/main/java/com/google/android/datatransport/runtime/scheduling/jobscheduling/UploadTestSupport.java
  transport/transport-runtime-testing/transport-runtime-testing.gradle
  transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/TransportContext.java
  transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/TransportRuntime.java
  transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/scheduling/jobscheduling/Uploader.java
Labels: size/L

#3672 Remove shrinkMode attribute
  firebase-common/src/main/res/raw/keep.xml
Labels: size/XS

#3674 Add missing javadoc classpath declaration.
  appcheck/firebase-appcheck-playintegrity/firebase-appcheck-playintegrity.gradle
Labels: size/XS

#3673 Fix cursor expanding result set bug.
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/Target.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteIndexManager.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/model/Values.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/core/TargetTest.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/SQLiteIndexManagerTest.java
Labels: size/L

#3675 Avoid using wildcards in imports.
  firebase-perf/src/main/java/com/google/firebase/perf/FirebasePerformance.java
  firebase-perf/src/main/java/com/google/firebase/perf/metrics/HttpMetric.java
  firebase-perf/src/main/java/com/google/firebase/perf/metrics/Trace.java
  firebase-perf/src/main/java/com/google/firebase/perf/metrics/validator/FirebasePerfTraceValidator.java
Labels: size/S

#3680 Fix the appdistro test app check for update button
  firebase-appdistribution/test-app/src/main/java/com/googletest/firebase/appdistribution/testapp/MainActivity.kt
Labels: size/S
