Repository firebase/firebase-android-sdk, pull requests merged in 2022-05, with the labels that each got.

#3689 Minor refactor of IndexBackfiller to eliminate private property.
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/IndexBackfiller.java
Labels: size/XS

#3579 Log notification open after onActivityCreated() on Android 7.1.
  firebase-messaging/src/main/java/com/google/firebase/messaging/FcmLifecycleCallbacks.java
Labels: size/XS

#3697 Rename minBatchId to maxBatchId
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteIndexManager.java
Labels: size/XS

#3683 Fireperf: use the new class `FrameMetricsRecorder` in `AppStateMonitor` and `FragmentStateMonitor`
  firebase-perf/src/main/java/com/google/firebase/perf/application/AppStateMonitor.java
  firebase-perf/src/main/java/com/google/firebase/perf/application/FragmentStateMonitor.java
  firebase-perf/src/main/java/com/google/firebase/perf/application/FrameMetricsRecorder.java
  firebase-perf/src/test/java/com/google/firebase/perf/application/AppStateMonitorTest.java
  firebase-perf/src/test/java/com/google/firebase/perf/application/FragmentStateMonitorTest.java
Labels: size/L

#3698 Abstract FrameMetricsAggregator to FrameMetricsRecorder class
  firebase-perf/src/main/java/com/google/firebase/perf/application/AppStateMonitor.java
  firebase-perf/src/main/java/com/google/firebase/perf/application/FragmentStateMonitor.java
  firebase-perf/src/main/java/com/google/firebase/perf/application/FrameMetricsRecorder.java
  firebase-perf/src/main/java/com/google/firebase/perf/metrics/FrameMetricsCalculator.java
  firebase-perf/src/test/java/com/google/firebase/perf/application/AppStateMonitorTest.java
  firebase-perf/src/test/java/com/google/firebase/perf/application/FragmentStateMonitorTest.java
  firebase-perf/src/test/java/com/google/firebase/perf/application/FrameMetricsRecorderTest.java
Labels: size/XL

#3691 Backport some changes for overlays
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/LocalDocumentsView.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/LocalStoreTestCase.java
Labels: size/M

#3704 Actually skips overlay migration when run a second time.
  firebase-firestore/CHANGELOG.md
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteOverlayMigrationManager.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/SQLiteOverlayMigrationManagerTest.java
Labels: size/M

#3711 Attempt to fix flaky E2E screen trace by relaunching the activity.
  firebase-perf/e2e-app/src/androidTest/java/com/google/firebase/testing/fireperf/FirebasePerformanceFragmentScreenTracesTest.java
Labels: size/XS

#3721 Add protobuf dep to fireci
  ci/fireci/setup.py
Labels: size/XS

#3725 Update version of dexmaker now that we removed jcenter
  firebase-common/firebase-common.gradle
  firebase-config/firebase-config.gradle
  firebase-crashlytics-ndk/firebase-crashlytics-ndk.gradle
  firebase-crashlytics/firebase-crashlytics.gradle
  firebase-functions/firebase-functions.gradle
  firebase-inappmessaging-display/firebase-inappmessaging-display.gradle
  firebase-inappmessaging/firebase-inappmessaging.gradle
Labels: size/S

#3715 Update Crashlytics file system to support multi-process apps
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/persistence/FileStoreTest.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/persistence/CrashlyticsReportPersistence.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/persistence/FileStore.java
Labels: size/M

#3726 Migrate away from deprecated ShadowPackageManager.getPackageInfoForTesting
  firebase-messaging/src/test/java/com/google/firebase/messaging/DisplayNotificationRoboTest.java
Labels: size/XS, ok-to-test

#3714 Upgrade Firelog priority from telemetry to data
  firebase-messaging/src/main/java/com/google/firebase/messaging/MessagingAnalytics.java
Labels: size/XS

#3732 Update comment of logToFirelog method
  firebase-messaging/src/main/java/com/google/firebase/messaging/MessagingAnalytics.java
Labels: size/XS

#3731 Add app-check to BoM as they leave beta
  buildSrc/src/main/java/com/google/firebase/gradle/bomgenerator/BomGeneratorTask.java
Labels: size/S

#3734 Dependabot High severity alerts
  smoke-tests/src/androidTest/backend/functions/functions/package-lock.json
  smoke-tests/src/androidTest/backend/functions/functions/package.json
Labels: size/XXL

#3738 Disable javadoc for undocumented sdks.
  firebase-appdistribution/firebase-appdistribution.gradle
  firebase-messaging-directboot/firebase-messaging-directboot.gradle
Labels: size/XS

#3739 add destructuring declarations to Firebase App Distribution KTX
  firebase-appdistribution-api/ktx/api.txt
  firebase-appdistribution-api/ktx/src/androidTest/kotlin/com/google/firebase/app/distribution/ktx/FirebaseAppDistributionTests.kt
  firebase-appdistribution-api/ktx/src/main/kotlin/com/google/firebase/appdistribution/ktx/FirebaseAppDistribution.kt
Labels: size/M

#3657 Re-run limit queries without limit if they need to be re-filled
  firebase-firestore/src/main/java/com/google/firebase/firestore/Query.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/Query.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/View.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/QueryEngine.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/bundle/BundleSerializerTest.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/SQLiteLocalStoreTest.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/SQLiteQueryEngineTest.java
Labels: size/L, api: firestore

#3742 JavaDoc fix: "this methods" → "this method".
  firebase-appdistribution-api/src/main/java/com/google/firebase/appdistribution/FirebaseAppDistribution.java
Labels: size/S

#3730 Rc realtime
  firebase-config/api.txt
  firebase-config/src/main/java/com/google/firebase/remoteconfig/ConfigUpdateListener.java
  firebase-config/src/main/java/com/google/firebase/remoteconfig/ConfigUpdateListenerRegistration.java
  firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigRealtimeHttpClient.java
Labels: size/L

#3745 Hides the constructors for FirebaseAppDistributionException.
  firebase-appdistribution-api/api.txt
  firebase-appdistribution-api/src/main/java/com/google/firebase/appdistribution/FirebaseAppDistributionException.java
Labels: size/S

#3752 Post release version updates
  appcheck/firebase-appcheck-debug-testing/gradle.properties
  appcheck/firebase-appcheck-debug/gradle.properties
  appcheck/firebase-appcheck-interop/gradle.properties
  appcheck/firebase-appcheck-playintegrity/gradle.properties
  appcheck/firebase-appcheck-safetynet/gradle.properties
  appcheck/firebase-appcheck/gradle.properties
  firebase-annotations/gradle.properties
  firebase-common/gradle.properties
  firebase-config/gradle.properties
  firebase-crashlytics-ndk/gradle.properties
  firebase-crashlytics/gradle.properties
  firebase-database/gradle.properties
  firebase-datatransport/gradle.properties
  firebase-firestore/gradle.properties
  firebase-functions/gradle.properties
  firebase-messaging-directboot/gradle.properties
  firebase-messaging/gradle.properties
  firebase-perf/gradle.properties
  transport/transport-backend-cct/gradle.properties
  transport/transport-runtime/gradle.properties
Labels: size/M

#3751 Ignore appdistro-api since it's still in beta.
  buildSrc/src/main/java/com/google/firebase/gradle/bomgenerator/BomGeneratorTask.java
Labels: size/XS

#3762 Upgrade kotlin version to 1.6.20
  build.gradle
  buildSrc/build.gradle
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/LibraryType.java
  encoders/protoc-gen-firebase-encoders/protoc-gen-firebase-encoders.gradle
  firebase-common/ktx/ktx.gradle
  tools/lint/lint.gradle
Labels: size/S
