Repository firebase/firebase-android-sdk, pull requests merged in 2022-09, with the labels that each got.

#4028 Fix: Cannot mark as impressed more than one message almost same time
  firebase-inappmessaging/src/main/java/com/google/firebase/inappmessaging/internal/DisplayCallbacksImpl.java
  firebase-inappmessaging/src/test/java/com/google/firebase/inappmessaging/internal/DisplayCallbacksImplTest.java
Labels: size/S

#4052 Update latest released version.
  appcheck/firebase-appcheck-debug-testing/gradle.properties
  appcheck/firebase-appcheck-debug/gradle.properties
  appcheck/firebase-appcheck-interop/gradle.properties
  appcheck/firebase-appcheck-safetynet/gradle.properties
  appcheck/firebase-appcheck/gradle.properties
  firebase-abt/gradle.properties
  firebase-common/gradle.properties
  firebase-components/firebase-dynamic-module-support/gradle.properties
  firebase-components/gradle.properties
  firebase-config/gradle.properties
  firebase-crashlytics-ndk/gradle.properties
  firebase-crashlytics/gradle.properties
  firebase-database/gradle.properties
  firebase-dynamic-links/gradle.properties
  firebase-firestore/gradle.properties
  firebase-functions/gradle.properties
  firebase-inappmessaging-display/gradle.properties
  firebase-inappmessaging/gradle.properties
  firebase-installations-interop/gradle.properties
  firebase-installations/gradle.properties
  firebase-messaging-directboot/gradle.properties
  firebase-messaging/gradle.properties
  firebase-ml-modeldownloader/gradle.properties
  firebase-perf/gradle.properties
  firebase-storage/gradle.properties
Labels: size/M, no-changelog

#4049 Resolved strict mode violations in firebase-installations
  firebase-installations/src/androidTest/java/com/google/firebase/installations/StrictModeTest.java
  firebase-installations/src/main/java/com/google/firebase/installations/FirebaseInstallations.java
  firebase-installations/src/test/java/com/google/firebase/installations/FirebaseInstallationsTest.java
Labels: size/S, no-changelog

#4055 Add missing latestReleasedVersion to appcheck* sdks
  appcheck/firebase-appcheck-debug-testing/gradle.properties
  appcheck/firebase-appcheck-debug/gradle.properties
  appcheck/firebase-appcheck-playintegrity/gradle.properties
  appcheck/firebase-appcheck/gradle.properties
Labels: size/XS, no-changelog

#4024 [Fireperf][AASA] change timebase to `elapsedRealtime`
  firebase-perf/src/main/java/com/google/firebase/perf/util/Timer.java
  firebase-perf/src/test/java/com/google/firebase/perf/metrics/AppStartTraceTest.java
  firebase-perf/src/test/java/com/google/firebase/perf/util/TimerTest.java
Labels: size/L

#4041 [Fireperf][AASA] `FirstDrawDoneListener`
  firebase-perf/src/main/java/com/google/firebase/perf/util/FirstDrawDoneListener.java
  firebase-perf/src/test/java/com/google/firebase/perf/util/FirstDrawDoneListenerTest.java
Labels: size/L

#4061 Implement Metalava with Dackka
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/DackkaPlugin.kt
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/Metalava.kt
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/ProjectUtils.kt
Labels: size/M

#4065 Properly encode http params.
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/network/HttpGetRequest.java
Labels: size/S

#4033 Move external documentation links to a task input in Dackka
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/DackkaGenerationTask.kt
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/DackkaPlugin.kt
Labels: size/M

#4031 Remove Dokka Plugin
  buildSrc/build.gradle.kts
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/Dokka.java
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/FirebaseJavaLibraryPlugin.java
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/JavadocPlugin.java
Labels: size/L

#4051 Realtime RC Store Template Version
  firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigContainer.java
  firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigFetchHandler.java
  firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigMetadataClient.java
  firebase-config/src/test/java/com/google/firebase/remoteconfig/internal/ConfigMetadataClientTest.java
Labels: size/M

#4072 Make dackka task depend on docStubs task.
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/DackkaGenerationTask.kt
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/DackkaPlugin.kt
Labels: size/S

#4074 Remove timestamps from fireci log output on CI
  ci/fireci/fireci/main.py
Labels: size/XS

#4073 Revert "Update project.path var to new location."
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/JavadocPlugin.java
Labels: size/XS

#4026 Add documentation for DackkaPlugin
  buildSrc/README.md
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/DackkaPlugin.kt
Labels: size/L

#4066 Realtime rc NO_CHANGE bug
  firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigAutoFetch.java
  firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigFetchHandler.java
  firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigFetchHttpClient.java
  firebase-config/src/test/java/com/google/firebase/remoteconfig/FirebaseRemoteConfigTest.java
  firebase-config/src/test/java/com/google/firebase/remoteconfig/internal/ConfigFetchHandlerTest.java
  firebase-config/src/test/java/com/google/firebase/remoteconfig/internal/ConfigFetchHttpClientTest.java
Labels: size/L

#3974 Upgrade AGP to 7.2.2
  build.gradle
  buildSrc/build.gradle.kts
  buildSrc/settings.gradle.kts
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/FirebaseJavaLibraryPlugin.java
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/FirebaseLibraryExtension.java
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/FirebaseLibraryPlugin.java
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/JavadocPlugin.java
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/LibraryType.java
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/license/GenerateLicensesTask.java
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/publish/PublishingPlugin.java
  encoders/protoc-gen-firebase-encoders/protoc-gen-firebase-encoders.gradle
  firebase-firestore/firebase-firestore.gradle
  firebase-firestore/ktx/ktx.gradle
  firebase-perf/dev-app/dev-app.gradle
  firebase-perf/firebase-perf.gradle
  firebase-perf/lint-baseline.xml
  gradle.properties
  gradle/wrapper/gradle-wrapper.properties
  smoke-tests/build.gradle
  tools/lint/lint.gradle
  tools/lint/src/main/kotlin/KotlinInteropDetector.kt
  tools/lint/src/main/kotlin/NonAndroidxNullabilityDetector.kt
Labels: size/L

#4088 Minor updates to the App Distribution test app.
  firebase-appdistribution/test-app/src/main/java/com/googletest/firebase/appdistribution/testapp/MainActivity.kt
  firebase-appdistribution/test-app/test-app.gradle
Labels: size/S

#4083 Deflake firebase_common HeartBeat tests.
  firebase-common/src/test/java/com/google/firebase/heartbeatinfo/DefaultHeartBeatControllerTest.java
  firebase-common/src/test/java/com/google/firebase/heartbeatinfo/TaskWaiter.java
  firebase-common/src/test/java/com/google/firebase/heartbeatinfo/TestOnCompleteListener.java
Labels: size/L

#4089 Update fad/in-app-feedback with latest from fad/next
  firebase-appdistribution/test-app/src/main/java/com/googletest/firebase/appdistribution/testapp/MainActivity.kt
  firebase-appdistribution/test-app/test-app.gradle
Labels: size/S

#4082 Add Javadoc support to the DackkaPlugin
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/DackkaPlugin.kt
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/GradleUtils.kt
Labels: size/M

#4090 Update various versions
  firebase-appdistribution/test-app/test-app.gradle
Labels: size/S

#4098 Merge branch 'fad/next' into fad/in-app-feedback
  firebase-appdistribution/test-app/test-app.gradle
Labels: size/S

#4093 Add Kotlin stdlib to the precompiled package-lists
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/DackkaGenerationTask.kt
  kotlindoc/package-lists/kotlin/package-list
Labels: size/L, no-changelog

#4091 Update with latest changes from master
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/DackkaGenerationTask.kt
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/DackkaPlugin.kt
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/GradleUtils.kt
  firebase-common/src/test/java/com/google/firebase/heartbeatinfo/DefaultHeartBeatControllerTest.java
  firebase-common/src/test/java/com/google/firebase/heartbeatinfo/TaskWaiter.java
  firebase-common/src/test/java/com/google/firebase/heartbeatinfo/TestOnCompleteListener.java
  kotlindoc/package-lists/kotlin/package-list
Labels: size/XL

#4092 Resolve strict mode violations in firebase-appdistribution
  firebase-appdistribution/firebase-appdistribution.gradle
  firebase-appdistribution/src/androidTest/AndroidManifest.xml
  firebase-appdistribution/src/androidTest/java/com/google/firebase/appdistribution/StrictModeTest.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/SignInStorage.java
Labels: size/M

#4101 merge fad/next into fad/in-app-feedback
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/DackkaGenerationTask.kt
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/DackkaPlugin.kt
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/GradleUtils.kt
  firebase-common/src/test/java/com/google/firebase/heartbeatinfo/DefaultHeartBeatControllerTest.java
  firebase-common/src/test/java/com/google/firebase/heartbeatinfo/TaskWaiter.java
  firebase-common/src/test/java/com/google/firebase/heartbeatinfo/TestOnCompleteListener.java
  kotlindoc/package-lists/kotlin/package-list
Labels: size/XL

#4104 update appcompat (1.3.0 -> 1.5.1) to fix lint
  firebase-appdistribution/firebase-appdistribution.gradle
Labels: size/XS

#4081 Add appcheck-ktx to bom config
  buildSrc/src/main/java/com/google/firebase/gradle/bomgenerator/BomGeneratorTask.java
Labels: size/XS

#4107 merge fad/next into fad/in-app-feedback
  firebase-appdistribution/firebase-appdistribution.gradle
  firebase-appdistribution/src/androidTest/AndroidManifest.xml
  firebase-appdistribution/src/androidTest/java/com/google/firebase/appdistribution/StrictModeTest.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/SignInStorage.java
Labels: size/M

#4057 Removing getRunningAppProcesses since the process_name isn't used
  firebase-perf/src/main/java/com/google/firebase/perf/session/gauges/GaugeManager.java
  firebase-perf/src/main/java/com/google/firebase/perf/session/gauges/GaugeMetadataManager.java
  firebase-perf/src/main/proto/firebase/perf/v1/perf_metric.proto
  firebase-perf/src/test/java/com/google/firebase/perf/metrics/validator/FirebasePerfGaugeManagerValidatorTest.java
  firebase-perf/src/test/java/com/google/firebase/perf/session/gauges/GaugeManagerTest.java
  firebase-perf/src/test/java/com/google/firebase/perf/session/gauges/GaugeMetadataManagerTest.java
Labels: size/M

#4110 Add projectSpecificSources back to the DackkaPlugin
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/DackkaPlugin.kt
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/ProjectUtils.kt
Labels: size/M, no-changelog

#4123 Fix dependabot security alerts
  smoke-tests/src/androidTest/backend/functions/functions/package-lock.json
Labels: size/XL

#4124 Make FiresiteTransform a Cacheable task
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/DackkaPlugin.kt
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/FiresiteTransformTask.kt
Labels: size/M

#4121 Realtime RC - Check HTTP status before listening and retrying
  firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigAutoFetch.java
  firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigRealtimeHttpClient.java
  firebase-config/src/test/java/com/google/firebase/remoteconfig/FirebaseRemoteConfigTest.java
Labels: size/L

#4132 Fix tests by downgrading AppCompat and fixing lint issue
  firebase-appdistribution/firebase-appdistribution.gradle
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FeedbackActivity.java
  firebase-appdistribution/src/main/res/layout/activity_feedback.xml
Labels: size/XS

#4133 Fix links in FeedbackActivity info text
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionImpl.java
Labels: size/XS

#4044 add coroutines-play-services as a transitive dep to firebase-common-ktx
  build.gradle
  firebase-common/ktx/ktx.gradle
  firebase-common/ktx/src/test/kotlin/com/google/firebase/ktx/Tests.kt
  firebase-firestore/ktx/ktx.gradle
Labels: size/M

#4012 database-ktx: add callbackFlow for eventlisteners
  firebase-database/ktx/api.txt
  firebase-database/ktx/ktx.gradle
  firebase-database/ktx/src/main/kotlin/com/google/firebase/database/ktx/ChildEvent.kt
  firebase-database/ktx/src/main/kotlin/com/google/firebase/database/ktx/Database.kt
Labels: size/L

#4135 Update released versions
  appcheck/firebase-appcheck-debug-testing/gradle.properties
  appcheck/firebase-appcheck-debug/gradle.properties
  appcheck/firebase-appcheck-interop/gradle.properties
  appcheck/firebase-appcheck-playintegrity/gradle.properties
  appcheck/firebase-appcheck-safetynet/gradle.properties
  appcheck/firebase-appcheck/gradle.properties
  firebase-firestore/gradle.properties
  firebase-installations/gradle.properties
Labels: size/M

#4141 Upgrade Dackka to 1.0.3
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/ProjectUtils.kt
Labels: size/XS

#4117 Add names to all Firebase components
  appcheck/firebase-appcheck-debug/src/main/java/com/google/firebase/appcheck/debug/FirebaseAppCheckDebugRegistrar.java
  appcheck/firebase-appcheck-playintegrity/src/main/java/com/google/firebase/appcheck/playintegrity/FirebaseAppCheckPlayIntegrityRegistrar.java
  appcheck/firebase-appcheck-safetynet/src/main/java/com/google/firebase/appcheck/safetynet/FirebaseAppCheckSafetyNetRegistrar.java
  appcheck/firebase-appcheck/src/main/java/com/google/firebase/appcheck/FirebaseAppCheckRegistrar.java
  firebase-abt/src/main/java/com/google/firebase/abt/component/AbtRegistrar.java
  firebase-appdistribution-api/src/main/java/com/google/firebase/appdistribution/FirebaseAppDistributionApiRegistrar.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionRegistrar.java
  firebase-components/firebase-dynamic-module-support/src/main/java/com/google/firebase/dynamicloading/DynamicLoadingRegistrar.java
  firebase-config/src/main/java/com/google/firebase/remoteconfig/RemoteConfigRegistrar.java
  firebase-crashlytics-ndk/src/main/java/com/google/firebase/crashlytics/ndk/CrashlyticsNdkRegistrar.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/CrashlyticsRegistrar.java
  firebase-database/src/main/java/com/google/firebase/database/DatabaseRegistrar.java
  firebase-datatransport/src/main/java/com/google/firebase/datatransport/TransportRegistrar.java
  firebase-dynamic-links/src/main/java/com/google/firebase/dynamiclinks/internal/FirebaseDynamicLinkRegistrar.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/FirestoreRegistrar.java
  firebase-functions/src/main/java/com/google/firebase/functions/FunctionsRegistrar.java
  firebase-inappmessaging-display/src/main/java/com/google/firebase/inappmessaging/display/FirebaseInAppMessagingDisplayRegistrar.java
  firebase-inappmessaging/src/main/java/com/google/firebase/inappmessaging/FirebaseInAppMessagingRegistrar.java
  firebase-installations/src/main/java/com/google/firebase/installations/FirebaseInstallationsRegistrar.java
  firebase-messaging/src/main/java/com/google/firebase/messaging/FirebaseMessagingRegistrar.java
  firebase-ml-modeldownloader/src/main/java/com/google/firebase/ml/modeldownloader/FirebaseModelDownloaderRegistrar.java
  firebase-perf/src/main/java/com/google/firebase/perf/FirebasePerfRegistrar.java
  firebase-segmentation/src/main/java/com/google/firebase/segmentation/FirebaseSegmentationRegistrar.java
  firebase-storage/src/main/java/com/google/firebase/storage/StorageRegistrar.java
Labels: size/L, no-changelog

#4142 Fix appcheck-ktx doc generation
  kotlindoc/package-lists/firebase/package-list
Labels: size/XS, no-changelog

#4095 Add strict mode testing in firebase-messaging
  firebase-messaging/firebase-messaging.gradle
  firebase-messaging/src/androidTest/AndroidManifest.xml
  firebase-messaging/src/androidTest/java/com/google/firebase/messaging/StrictModeTest.java
Labels: size/M

#4144 Add gradle property to instrument Fireperf E2E test
  ci/fireci/fireciplugins/fireperf.py
Labels: size/XS

#4085 Resolve StrictMode violation in App Check.
  appcheck/firebase-appcheck/src/main/java/com/google/firebase/appcheck/internal/DefaultFirebaseAppCheck.java
  appcheck/firebase-appcheck/src/test/java/com/google/firebase/appcheck/internal/DefaultFirebaseAppCheckTest.java
Labels: size/L

#4087 Implemented exponential backoff and max retry with resumable uploads
  firebase-storage/CHANGELOG.md
  firebase-storage/src/main/java/com/google/firebase/storage/FirebaseStorage.java
  firebase-storage/src/main/java/com/google/firebase/storage/StorageTaskScheduler.java
  firebase-storage/src/main/java/com/google/firebase/storage/UploadTask.java
  firebase-storage/src/main/java/com/google/firebase/storage/network/NetworkRequest.java
  firebase-storage/src/test/java/com/google/firebase/storage/TestUtil.java
  firebase-storage/src/test/java/com/google/firebase/storage/UploadTest.java
  firebase-storage/src/test/resources/activitylogs/fileUploadWith500_network.txt
  firebase-storage/src/test/resources/activitylogs/fileUploadWith500_task.txt
  firebase-storage/src/testUtil/java/com/google/firebase/storage/TestDownloadHelper.java
  firebase-storage/src/testUtil/java/com/google/firebase/storage/TestUploadHelper.java
Labels: size/XL

#4143 Firestore: Re-write API javadocs for COUNT API
  firebase-firestore/src/main/java/com/google/firebase/firestore/AggregateQuery.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/AggregateQuerySnapshot.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/AggregateSource.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/Query.java
Labels: size/L, api: firestore, no-changelog

#4139 storage-ktx: add callbackFlow for upload/download progress
  firebase-storage/ktx/api.txt
  firebase-storage/ktx/ktx.gradle
  firebase-storage/ktx/src/main/kotlin/com/google/firebase/storage/ktx/Storage.kt
  firebase-storage/ktx/src/main/kotlin/com/google/firebase/storage/ktx/TaskState.kt
Labels: size/M

#4122 Add a screenshot-based trigger for in-app feedback
  firebase-appdistribution-api/api.txt
  firebase-appdistribution-api/src/main/java/com/google/firebase/appdistribution/FirebaseAppDistribution.java
  firebase-appdistribution-api/src/main/java/com/google/firebase/appdistribution/internal/FirebaseAppDistributionProxy.java
  firebase-appdistribution-api/src/main/java/com/google/firebase/appdistribution/internal/FirebaseAppDistributionStub.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FeedbackActivity.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FeedbackSender.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionImpl.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionTesterApiClient.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/ImageUtils.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/LogWrapper.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/ScreenshotTaker.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/TesterApiHttpClient.java
  firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/FeedbackSenderTest.java
  firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionServiceImplTest.java
  firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionTesterApiClientTest.java
  firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/ImageUtilsTest.java
  firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/ScreenshotTakerTest.java
  firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/TesterApiHttpClientTest.java
  firebase-appdistribution/test-app/src/main/AndroidManifest.xml
  firebase-appdistribution/test-app/src/main/java/com/googletest/firebase/appdistribution/testapp/MainActivity.kt
  firebase-appdistribution/test-app/src/main/java/com/googletest/firebase/appdistribution/testapp/ScreenshotDetectionFeedbackTrigger.java
  firebase-appdistribution/test-app/test-app.gradle
Labels: size/XL

#4112 Make a best effort attempt to flush reports at crash time
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/Utils.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/send/ReportQueue.java
  transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/ForcedSender.java
  transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/TransportImpl.java
  transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/scheduling/jobscheduling/Uploader.java
  transport/transport-runtime/transport-runtime.gradle
Labels: size/M

#4137 Only allow one feedback flow to be active
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionImpl.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionLifecycleNotifier.java
  firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionServiceImplTest.java
Labels: size/L

#4138 Add shake for feedback to test app
  firebase-appdistribution/test-app/src/main/AndroidManifest.xml
  firebase-appdistribution/test-app/src/main/java/com/googletest/firebase/appdistribution/testapp/AppDistroTestApplication.kt
  firebase-appdistribution/test-app/src/main/java/com/googletest/firebase/appdistribution/testapp/ShakeForFeedback.kt
  firebase-appdistribution/test-app/test-app.gradle
Labels: size/M

#4130 Public Count
  firebase-firestore/CHANGELOG.md
  firebase-firestore/api.txt
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/CountTest.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/AggregateQuery.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/AggregateQuerySnapshot.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/AggregateSource.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/Query.java
Labels: size/L

#4114 [Fireperf][AASA] send `_experiment_app_start_ttid` trace, controlled by RC flag
  firebase-perf/dev-app/src/main/AndroidManifest.xml
  firebase-perf/src/main/java/com/google/firebase/perf/config/ConfigResolver.java
  firebase-perf/src/main/java/com/google/firebase/perf/config/ConfigurationConstants.java
  firebase-perf/src/main/java/com/google/firebase/perf/config/RemoteConfigManager.java
  firebase-perf/src/main/java/com/google/firebase/perf/metrics/AppStartTrace.java
  firebase-perf/src/test/java/com/google/firebase/perf/config/RemoteConfigManagerTest.java
  firebase-perf/src/test/java/com/google/firebase/perf/metrics/AppStartTraceTest.java
Labels: size/L

#4150 Add menu to test app for selecting feedback trigger
  firebase-appdistribution/test-app/src/main/java/com/googletest/firebase/appdistribution/testapp/AppDistroTestApplication.kt
  firebase-appdistribution/test-app/src/main/java/com/googletest/firebase/appdistribution/testapp/MainActivity.kt
  firebase-appdistribution/test-app/src/main/java/com/googletest/firebase/appdistribution/testapp/SecondActivity.kt
  firebase-appdistribution/test-app/src/main/java/com/googletest/firebase/appdistribution/testapp/ShakeForFeedback.kt
  firebase-appdistribution/test-app/src/main/res/layout/activity_main.xml
  firebase-appdistribution/test-app/src/main/res/layout/list_item.xml
  firebase-appdistribution/test-app/src/main/res/menu/action_menu.xml
  firebase-appdistribution/test-app/src/main/res/values/strings.xml
Labels: size/L

#4151 Hook screenshot trigger to test app menu
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionImpl.java
  firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionServiceImplTest.java
  firebase-appdistribution/test-app/src/main/java/com/googletest/firebase/appdistribution/testapp/AppDistroTestApplication.kt
  firebase-appdistribution/test-app/src/main/java/com/googletest/firebase/appdistribution/testapp/MainActivity.kt
  firebase-appdistribution/test-app/src/main/java/com/googletest/firebase/appdistribution/testapp/ScreenshotDetectionFeedbackTrigger.java
Labels: size/L

#4152 Reimplement screenshot trigger in Kotlin
  firebase-appdistribution/test-app/src/main/java/com/googletest/firebase/appdistribution/testapp/MainActivity.kt
  firebase-appdistribution/test-app/src/main/java/com/googletest/firebase/appdistribution/testapp/ScreenshotDetectionFeedbackTrigger.java
  firebase-appdistribution/test-app/src/main/java/com/googletest/firebase/appdistribution/testapp/ScreenshotDetectionFeedbackTrigger.kt
Labels: size/XL

#4153 Fix ApkUpdaterTest flake
  firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/ApkUpdaterTest.java
Labels: size/XS

#4149 Specify unique ref tags in Dackka output
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/DackkaPlugin.kt
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/FiresiteTransformTask.kt
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/GradleUtils.kt
  buildSrc/src/test/kotlin/com/google/firebase/gradle/plugins/publishing.kt
  firebase-abt/firebase-abt.gradle
  firebase-components/firebase-components.gradle
  firebase-components/firebase-dynamic-module-support/firebase-dynamic-module-support.gradle
  firebase-database-collection/firebase-database-collection.gradle
Labels: size/L, no-changelog

#4136 Add strict mode tests to inappmessaging and inappmessaging-display
  firebase-inappmessaging-display/firebase-inappmessaging-display.gradle
  firebase-inappmessaging-display/src/androidTest/java/com/google/firebase/inappmessaging/display/StrictModeTest.java
  firebase-inappmessaging/firebase-inappmessaging.gradle
  firebase-inappmessaging/src/androidTest/java/com/google/firebase/inappmessaging/StrictModeTest.java
Labels: size/L

#4148 Fix strict mode violations for appcheck
  appcheck/firebase-appcheck/firebase-appcheck.gradle
  appcheck/firebase-appcheck/src/androidTest/java/AndroidManifest.xml
  appcheck/firebase-appcheck/src/androidTest/java/com/google/firebase/appcheck/StrictModeTest.java
  appcheck/firebase-appcheck/src/main/java/com/google/firebase/appcheck/internal/StorageHelper.java
Labels: size/M
