Repository firebase/firebase-android-sdk, pull requests merged in 2022-07, with the labels that each got.

#3843 Update versions in gradle.properties
  firebase-datatransport/gradle.properties
  firebase-firestore/gradle.properties
  firebase-messaging-directboot/gradle.properties
  firebase-messaging/gradle.properties
  transport/transport-backend-cct/gradle.properties
  transport/transport-runtime/gradle.properties
Labels: size/S

#3865 Adding file path check to avoid NumberFormatException due to empt path
  firebase-ml-modeldownloader/src/main/java/com/google/firebase/ml/modeldownloader/internal/ModelFileManager.java
  firebase-ml-modeldownloader/src/test/java/com/google/firebase/ml/modeldownloader/internal/ModelFileManagerTest.java
Labels: size/S, ok-to-test

#3871 Support leaf modules in changed modules task.
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/ci/ChangedModulesTask.kt
Labels: size/XS

#3872 Firestore: Add @CanIgnoreReturnValue annotations in tests
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/TransactionTest.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/LocalSerializerTest.java
  firebase-firestore/src/testUtil/java/com/google/firebase/firestore/testutil/ComparatorTester.java
Labels: size/S, api: firestore

#3870 Fix dynamic module support bug https://github.com/firebase/firebase-android-sdk/issues/3860
  firebase-components/firebase-dynamic-module-support/firebase-dynamic-module-support.gradle
Labels: size/XS

#3877 Pass "Locale-US" to SimpleDateFormat while formatting first-open time…
  firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigFetchHttpClient.java
  firebase-config/src/test/java/com/google/firebase/remoteconfig/internal/ConfigFetchHttpClientTest.java
Labels: size/S

#3882 Patch background state checker.
  firebase-config/src/main/java/com/google/firebase/remoteconfig/RemoteConfigComponent.java
  firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigRealtimeHttpClient.java
Labels: size/S

#3881 Use unmodifiableList for CompositeFilters.
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/CompositeFilter.java
Labels: size/XS

#3880 Update the query protos.
  firebase-firestore/src/proto/google/firestore/v1/query.proto
Labels: size/XS

#3899 Fix reports endpoint URL
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionTesterApiClient.java
  firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionTesterApiClientTest.java
Labels: size/S

#3901 Update name of file in CPP repo.
  .github/workflows/update-cpp-sdk-on-release.yml
Labels: size/XS

#3792 Basic Encoder handle Object & List
  firebase-firestore/ktx/api.txt
  firebase-firestore/ktx/ktx.gradle
  firebase-firestore/ktx/src/androidTest/java/com/google/firebase/firestore/FirestoreMapEncoderIntegrationTest.kt
  firebase-firestore/ktx/src/androidTest/java/com/google/firebase/firestore/testutil/IntegrationTestUtil.kt
  firebase-firestore/ktx/src/main/kotlin/com/google/firebase/firestore/ktx/annotations/FirestoreSerializationKtxAnnotations.kt
  firebase-firestore/ktx/src/main/kotlin/com/google/firebase/firestore/ktx/annotations/package-info.java
  firebase-firestore/ktx/src/main/kotlin/com/google/firebase/firestore/ktx/serialization/ExtensionFunctions.kt
  firebase-firestore/ktx/src/main/kotlin/com/google/firebase/firestore/ktx/serialization/FirestoreMapEncoder.kt
  firebase-firestore/ktx/src/main/kotlin/com/google/firebase/firestore/ktx/serialization/package-info.java
  firebase-firestore/ktx/src/test/kotlin/com/google/firebase/firestore/ktx/FirestoreMapEncoderTests.kt
Labels: size/XXL

#3900 Ensure Client exists
  firebase-firestore/CHANGELOG.md
  firebase-firestore/src/main/java/com/google/firebase/firestore/FirebaseFirestore.java
Labels: size/XS

#3886 Ywmei/serialization feature branch support ktx in java
  firebase-firestore/api.txt
  firebase-firestore/firebase-firestore.gradle
  firebase-firestore/gradle.properties
  firebase-firestore/ktx/ktx.gradle
  firebase-firestore/ktx/src/test/kotlin/com/google/firebase/firestore/TestUtil.kt
  firebase-firestore/ktx/src/test/kotlin/com/google/firebase/firestore/ktx/JavaLibKtxSupportTests.kt
  firebase-firestore/ktx/src/test/kotlin/com/google/firebase/firestore/ktx/TestListEncoder.kt
  firebase-firestore/proguard.txt
  firebase-firestore/src/main/java/com/google/firebase/Timestamp.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/DocumentId.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/DocumentId.kt
  firebase-firestore/src/main/java/com/google/firebase/firestore/DocumentReference.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/GeoPoint.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/IgnoreExtraProperties.kt
  firebase-firestore/src/main/java/com/google/firebase/firestore/ServerTimestamp.kt
  firebase-firestore/src/main/java/com/google/firebase/firestore/ThrowOnExtraProperties.kt
  firebase-firestore/src/main/java/com/google/firebase/firestore/encoding/FirestoreAbstractDecoder.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/encoding/FirestoreAbstractEncoder.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/encoding/FirestoreNativeDataTypeSerializer.kt
  firebase-firestore/src/main/java/com/google/firebase/firestore/encoding/FirestoreSerializersModule.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/encoding/package-info.java
Labels: size/XL

#3888 Remove usage of OPERATOR_UNSPECIFIED and use the real OR operator.
  firebase-firestore/src/main/java/com/google/firebase/firestore/remote/RemoteSerializer.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/util/LogicUtils.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/remote/RemoteSerializerTest.java
Labels: size/S

#3849 Ywmei/serialization dev registry
  firebase-firestore/ktx/src/androidTest/java/com/google/firebase/firestore/ComponentRegistrarTest.kt
  firebase-firestore/ktx/src/androidTest/java/com/google/firebase/firestore/FirestoreMapEncoderIntegrationTest.kt
  firebase-firestore/ktx/src/androidTest/java/com/google/firebase/firestore/IntegrationTestUtil.kt
  firebase-firestore/ktx/src/main/kotlin/com/google/firebase/firestore/ktx/Firestore.kt
  firebase-firestore/ktx/src/main/kotlin/com/google/firebase/firestore/ktx/serialization/MapEncoderKtxImp.kt
  firebase-firestore/proguard.txt
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/AccessHelper.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/DocumentReference.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/FirebaseFirestore.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/FirestoreMultiDbComponent.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/FirestoreRegistrar.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/encoding/MapEncoder.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/FirestoreMultiDbComponentTest.java
Labels: size/L

#3878 basic decoder
  firebase-firestore/ktx/ktx.gradle
  firebase-firestore/ktx/src/androidTest/java/com/google/firebase/firestore/FirestoreMapEncoderIntegrationTest.kt
  firebase-firestore/ktx/src/main/kotlin/com/google/firebase/firestore/ktx/serialization/FirestoreMapDecoder.kt
  firebase-firestore/ktx/src/test/kotlin/com/google/firebase/firestore/TestUtil.kt
  firebase-firestore/ktx/src/test/kotlin/com/google/firebase/firestore/ktx/FirestoreMapDecoderTests.kt
  firebase-firestore/ktx/src/test/kotlin/com/google/firebase/firestore/ktx/FirestoreMapEncoderTests.kt
  firebase-firestore/ktx/src/test/kotlin/com/google/firebase/firestore/ktx/JavaLibKtxSupportTests.kt
Labels: size/XL

#3912 Update FirebaseMessagingDirectBootReceiver to match FCM's FirebaseIns…
  firebase-messaging-directboot/firebase-messaging-directboot.gradle
  firebase-messaging-directboot/src/main/java/com/google/firebase/messaging/directboot/FirebaseMessagingDirectBootReceiver.java
Labels: size/L

#3920 Fix broken firebase-appdistribution test
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/AabUpdater.java
  firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/AabUpdaterTest.java
  firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/TestOnProgressListener.java
Labels: size/M

#3905 Add instructions to enable `test-app` in subprojects.cfg
  firebase-appdistribution/test-app/README.md
Labels: size/S

#3921 Some cleanup in AabUpdaterTest
  firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/AabUpdaterTest.java
  firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/TestOnProgressListener.java
Labels: size/S

#3917 Handle API disabled errors in firebase-appdistribution
  firebase-appdistribution-api/api.txt
  firebase-appdistribution-api/src/main/java/com/google/firebase/appdistribution/FirebaseAppDistributionException.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/ErrorMessages.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/TesterApiDisabledErrorDetails.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/TesterApiHttpClient.java
  firebase-appdistribution/src/test/assets/apiDisabledBadLinkResponse.json
  firebase-appdistribution/src/test/assets/apiDisabledResponse.json
  firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/TestUtils.java
  firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/TesterApiDisabledErrorDetailsTest.java
  firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/TesterApiHttpClientTest.java
Labels: size/L

#3925 Remove binary.
  firebase-appdistribution/test-app/release/test-app.aab
Labels: size/XS

#3926 Remove In-App Feedback functionality from firebase-appdistribution
  firebase-appdistribution-api/api.txt
  firebase-appdistribution-api/src/main/java/com/google/firebase/appdistribution/FirebaseAppDistribution.java
  firebase-appdistribution-api/src/main/java/com/google/firebase/appdistribution/internal/FirebaseAppDistributionProxy.java
  firebase-appdistribution-api/src/main/java/com/google/firebase/appdistribution/internal/FirebaseAppDistributionStub.java
  firebase-appdistribution/src/main/AndroidManifest.xml
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FeedbackActivity.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FeedbackSender.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionImpl.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionRegistrar.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/ImageUtils.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/ScreenshotTaker.java
  firebase-appdistribution/src/main/res/layout/activity_feedback.xml
  firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/FeedbackSenderTest.java
  firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionServiceImplTest.java
  firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/ImageUtilsTest.java
  firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/ScreenshotTakerTest.java
Labels: size/XL

#3927 Revert "Remove In-App Feedback functionality from firebase-appdistribution (#3926)
  firebase-appdistribution-api/api.txt
  firebase-appdistribution-api/src/main/java/com/google/firebase/appdistribution/FirebaseAppDistribution.java
  firebase-appdistribution-api/src/main/java/com/google/firebase/appdistribution/internal/FirebaseAppDistributionProxy.java
  firebase-appdistribution-api/src/main/java/com/google/firebase/appdistribution/internal/FirebaseAppDistributionStub.java
  firebase-appdistribution/src/main/AndroidManifest.xml
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FeedbackActivity.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FeedbackSender.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionImpl.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionRegistrar.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/ImageUtils.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/ScreenshotTaker.java
  firebase-appdistribution/src/main/res/layout/activity_feedback.xml
  firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/FeedbackSenderTest.java
  firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionServiceImplTest.java
  firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/ImageUtilsTest.java
  firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/ScreenshotTakerTest.java
Labels: size/XL

#3924 Add feedback button to app-distribution/test-app
  build.gradle
  firebase-appdistribution/test-app/README.md
  firebase-appdistribution/test-app/src/main/java/com/googletest/firebase/appdistribution/testapp/MainActivity.kt
  firebase-appdistribution/test-app/src/main/res/layout/activity_main.xml
  firebase-appdistribution/test-app/test-app.gradle
Labels: size/M

#3919 Finish message broadcast after sending Intent to bound Service.
  firebase-messaging/src/main/java/com/google/firebase/messaging/FcmBroadcastProcessor.java
  firebase-messaging/src/main/java/com/google/firebase/messaging/WakeLockHolder.java
  firebase-messaging/src/main/java/com/google/firebase/messaging/WithinAppServiceConnection.java
  firebase-messaging/src/test/java/com/google/firebase/messaging/FcmBroadcastProcessorRoboTest.java
  firebase-messaging/src/test/java/com/google/firebase/messaging/WakeLockHolderRoboTest.java
  firebase-messaging/src/test/java/com/google/firebase/messaging/WithinAppServiceConnectionRoboTest.java
Labels: size/L

#3893 feat: implement Firebase App Check KTX
  appcheck/firebase-appcheck/ktx/api.txt
  appcheck/firebase-appcheck/ktx/gradle.properties
  appcheck/firebase-appcheck/ktx/ktx.gradle
  appcheck/firebase-appcheck/ktx/src/androidTest/AndroidManifest.xml
  appcheck/firebase-appcheck/ktx/src/androidTest/kotlin/com/google/firebase/appcheck/ktx/FirebaseAppCheckTests.kt
  appcheck/firebase-appcheck/ktx/src/main/AndroidManifest.xml
  appcheck/firebase-appcheck/ktx/src/main/kotlin/com/google/firebase/appcheck/ktx/FirebaseAppCheck.kt
  subprojects.cfg
Labels: size/L

#3930 Add some more details to firebase-appdistribution/test-app/README.md
  firebase-appdistribution/test-app/README.md
Labels: size/S

#3932 Rename collectAndSendFeedback to startFeedback
  firebase-appdistribution-api/api.txt
  firebase-appdistribution-api/src/main/java/com/google/firebase/appdistribution/FirebaseAppDistribution.java
  firebase-appdistribution-api/src/main/java/com/google/firebase/appdistribution/internal/FirebaseAppDistributionProxy.java
  firebase-appdistribution-api/src/main/java/com/google/firebase/appdistribution/internal/FirebaseAppDistributionStub.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionImpl.java
  firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionServiceImplTest.java
  firebase-appdistribution/test-app/src/main/java/com/googletest/firebase/appdistribution/testapp/MainActivity.kt
Labels: size/S

#3937 Update messaging around API_DISABLED status
  firebase-appdistribution-api/src/main/java/com/google/firebase/appdistribution/FirebaseAppDistributionException.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/ErrorMessages.java
Labels: size/S

#3906 remove app indexing from the firebase-tutorial-bundle generator
  buildSrc/src/main/java/com/google/firebase/gradle/bomgenerator/RecipeVersionWriter.java
Labels: size/XS

#3855 update kotlin from 1.3.72 to 1.4.32
  build.gradle
  buildSrc/build.gradle
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/LibraryType.java
  encoders/protoc-gen-firebase-encoders/protoc-gen-firebase-encoders.gradle
  firebase-common/ktx/ktx.gradle
  tools/lint/lint.gradle
Labels: size/S

#3943 Realtime rc merge refactor
  firebase-config/ktx/src/test/kotlin/com/google/firebase/remoteconfig/TestConstructorUtil.kt
  firebase-config/ktx/src/test/kotlin/com/google/firebase/remoteconfig/ktx/RemoteConfigTests.kt
  firebase-config/src/androidTest/java/com/google/firebase/remoteconfig/FirebaseRemoteConfigIntegrationTest.java
  firebase-config/src/main/java/com/google/firebase/remoteconfig/FirebaseRemoteConfig.java
  firebase-config/src/main/java/com/google/firebase/remoteconfig/RemoteConfigComponent.java
  firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigAutoFetch.java
  firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigRealtimeHandler.java
  firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigRealtimeHttpClient.java
  firebase-config/src/test/java/com/google/firebase/remoteconfig/FirebaseRemoteConfigTest.java
Labels: size/L

#3941 If modelHash is null pass emptyString to logger which requires non-nu…
  firebase-ml-modeldownloader/src/main/java/com/google/firebase/ml/modeldownloader/internal/CustomModelDownloadService.java
  firebase-ml-modeldownloader/src/test/java/com/google/firebase/ml/modeldownloader/internal/CustomModelDownloadServiceTest.java
Labels: size/M, ok-to-test

#3936 provides more tests
  firebase-firestore/ktx/src/test/kotlin/com/google/firebase/firestore/ktx/CustomSerializerTests.kt
  firebase-firestore/ktx/src/test/kotlin/com/google/firebase/firestore/ktx/FirestoreMapDecoderTests.kt
Labels: size/L

#3923 support transaction, writebatch, query
  firebase-firestore/ktx/src/androidTest/java/com/google/firebase/firestore/BatchOperationIntegrationTests.kt
  firebase-firestore/ktx/src/androidTest/java/com/google/firebase/firestore/ComponentRegistrarTest.kt
  firebase-firestore/ktx/src/androidTest/java/com/google/firebase/firestore/DocumentIdIntegrationTests.kt
  firebase-firestore/ktx/src/androidTest/java/com/google/firebase/firestore/FirestoreMapEncoderIntegrationTest.kt
  firebase-firestore/ktx/src/androidTest/java/com/google/firebase/firestore/IgnoreOnExtraPropertiesTest.kt
  firebase-firestore/ktx/src/androidTest/java/com/google/firebase/firestore/IntegrationTestUtil.kt
  firebase-firestore/ktx/src/androidTest/java/com/google/firebase/firestore/ServerTimestampIntegrationTests.kt
  firebase-firestore/ktx/src/test/kotlin/com/google/firebase/firestore/ktx/CustomSerializerTests.kt
  firebase-firestore/ktx/src/test/kotlin/com/google/firebase/firestore/ktx/FirestoreMapDecoderTests.kt
  firebase-firestore/src/main/java/com/google/firebase/firestore/Transaction.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/WriteBatch.java
Labels: size/XL

#3922 share annotations between java and kotlin
  firebase-firestore/api.txt
  firebase-firestore/ktx/src/androidTest/java/com/google/firebase/firestore/BatchOperationIntegrationTests.kt
  firebase-firestore/ktx/src/androidTest/java/com/google/firebase/firestore/ComponentRegistrarTest.kt
  firebase-firestore/ktx/src/androidTest/java/com/google/firebase/firestore/DocumentIdIntegrationTests.kt
  firebase-firestore/ktx/src/androidTest/java/com/google/firebase/firestore/FirestoreMapEncoderIntegrationTest.kt
  firebase-firestore/ktx/src/androidTest/java/com/google/firebase/firestore/IgnoreOnExtraPropertiesTest.kt
  firebase-firestore/ktx/src/androidTest/java/com/google/firebase/firestore/IntegrationTestUtil.kt
  firebase-firestore/ktx/src/androidTest/java/com/google/firebase/firestore/ServerTimestampIntegrationTests.kt
  firebase-firestore/ktx/src/main/kotlin/com/google/firebase/firestore/ktx/annotations/FirestoreSerializationKtxAnnotations.kt
  firebase-firestore/ktx/src/main/kotlin/com/google/firebase/firestore/ktx/annotations/package-info.java
  firebase-firestore/ktx/src/main/kotlin/com/google/firebase/firestore/ktx/serialization/FirestoreMapDecoder.kt
  firebase-firestore/ktx/src/main/kotlin/com/google/firebase/firestore/ktx/serialization/FirestoreMapEncoder.kt
  firebase-firestore/ktx/src/test/kotlin/com/google/firebase/firestore/ktx/CustomSerializerTests.kt
  firebase-firestore/ktx/src/test/kotlin/com/google/firebase/firestore/ktx/DocumentIdTests.kt
  firebase-firestore/ktx/src/test/kotlin/com/google/firebase/firestore/ktx/FirestoreMapDecoderTests.kt
  firebase-firestore/ktx/src/test/kotlin/com/google/firebase/firestore/ktx/JavaLibKtxSupportTests.kt
  firebase-firestore/ktx/src/test/kotlin/com/google/firebase/firestore/ktx/ServerTimestampTests.kt
  firebase-firestore/src/main/java/com/google/firebase/firestore/DocumentId.kt
  firebase-firestore/src/main/java/com/google/firebase/firestore/ServerTimestamp.kt
  firebase-firestore/src/main/java/com/google/firebase/firestore/Transaction.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/WriteBatch.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/util/CustomClassMapper.java
Labels: size/XXL

#3913 Ywmei/handle annotation during decoding
  firebase-firestore/api.txt
  firebase-firestore/ktx/src/androidTest/java/com/google/firebase/firestore/BatchOperationIntegrationTests.kt
  firebase-firestore/ktx/src/androidTest/java/com/google/firebase/firestore/ComponentRegistrarTest.kt
  firebase-firestore/ktx/src/androidTest/java/com/google/firebase/firestore/DocumentIdIntegrationTests.kt
  firebase-firestore/ktx/src/androidTest/java/com/google/firebase/firestore/FirestoreMapEncoderIntegrationTest.kt
  firebase-firestore/ktx/src/androidTest/java/com/google/firebase/firestore/IgnoreOnExtraPropertiesTest.kt
  firebase-firestore/ktx/src/androidTest/java/com/google/firebase/firestore/IntegrationTestUtil.kt
  firebase-firestore/ktx/src/androidTest/java/com/google/firebase/firestore/ServerTimestampIntegrationTests.kt
  firebase-firestore/ktx/src/main/kotlin/com/google/firebase/firestore/ktx/annotations/FirestoreSerializationKtxAnnotations.kt
  firebase-firestore/ktx/src/main/kotlin/com/google/firebase/firestore/ktx/annotations/package-info.java
  firebase-firestore/ktx/src/main/kotlin/com/google/firebase/firestore/ktx/serialization/FirestoreMapDecoder.kt
  firebase-firestore/ktx/src/main/kotlin/com/google/firebase/firestore/ktx/serialization/FirestoreMapEncoder.kt
  firebase-firestore/ktx/src/main/kotlin/com/google/firebase/firestore/ktx/serialization/MapEncoderKtxImp.kt
  firebase-firestore/ktx/src/test/kotlin/com/google/firebase/firestore/ktx/CustomSerializerTests.kt
  firebase-firestore/ktx/src/test/kotlin/com/google/firebase/firestore/ktx/DocumentIdTests.kt
  firebase-firestore/ktx/src/test/kotlin/com/google/firebase/firestore/ktx/FirestoreMapDecoderTests.kt
  firebase-firestore/ktx/src/test/kotlin/com/google/firebase/firestore/ktx/JavaLibKtxSupportTests.kt
  firebase-firestore/ktx/src/test/kotlin/com/google/firebase/firestore/ktx/ServerTimestampTests.kt
  firebase-firestore/src/main/java/com/google/firebase/firestore/DocumentId.kt
  firebase-firestore/src/main/java/com/google/firebase/firestore/DocumentSnapshot.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/ServerTimestamp.kt
  firebase-firestore/src/main/java/com/google/firebase/firestore/Transaction.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/WriteBatch.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/encoding/MapEncoder.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/util/CustomClassMapper.java
Labels: size/XXL

#3911 Handle Annotations during encoding
  firebase-firestore/api.txt
  firebase-firestore/ktx/src/androidTest/java/com/google/firebase/firestore/BatchOperationIntegrationTests.kt
  firebase-firestore/ktx/src/androidTest/java/com/google/firebase/firestore/ComponentRegistrarTest.kt
  firebase-firestore/ktx/src/androidTest/java/com/google/firebase/firestore/DocumentIdIntegrationTests.kt
  firebase-firestore/ktx/src/androidTest/java/com/google/firebase/firestore/FirestoreMapEncoderIntegrationTest.kt
  firebase-firestore/ktx/src/androidTest/java/com/google/firebase/firestore/IgnoreOnExtraPropertiesTest.kt
  firebase-firestore/ktx/src/androidTest/java/com/google/firebase/firestore/IntegrationTestUtil.kt
  firebase-firestore/ktx/src/androidTest/java/com/google/firebase/firestore/ServerTimestampIntegrationTests.kt
  firebase-firestore/ktx/src/main/kotlin/com/google/firebase/firestore/ktx/annotations/FirestoreSerializationKtxAnnotations.kt
  firebase-firestore/ktx/src/main/kotlin/com/google/firebase/firestore/ktx/annotations/package-info.java
  firebase-firestore/ktx/src/main/kotlin/com/google/firebase/firestore/ktx/serialization/FirestoreMapDecoder.kt
  firebase-firestore/ktx/src/main/kotlin/com/google/firebase/firestore/ktx/serialization/FirestoreMapEncoder.kt
  firebase-firestore/ktx/src/main/kotlin/com/google/firebase/firestore/ktx/serialization/MapEncoderKtxImp.kt
  firebase-firestore/ktx/src/test/kotlin/com/google/firebase/firestore/ktx/CustomSerializerTests.kt
  firebase-firestore/ktx/src/test/kotlin/com/google/firebase/firestore/ktx/DocumentIdTests.kt
  firebase-firestore/ktx/src/test/kotlin/com/google/firebase/firestore/ktx/FirestoreMapDecoderTests.kt
  firebase-firestore/ktx/src/test/kotlin/com/google/firebase/firestore/ktx/FirestoreMapEncoderTests.kt
  firebase-firestore/ktx/src/test/kotlin/com/google/firebase/firestore/ktx/ServerTimestampTests.kt
  firebase-firestore/src/main/java/com/google/firebase/firestore/DocumentId.kt
  firebase-firestore/src/main/java/com/google/firebase/firestore/DocumentSnapshot.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/ServerTimestamp.kt
  firebase-firestore/src/main/java/com/google/firebase/firestore/Transaction.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/WriteBatch.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/encoding/MapEncoder.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/util/CustomClassMapper.java
Labels: size/XXL

#3953 Update kotlindoc package-list of firebase.google.com
  kotlindoc/package-lists/firebase/package-list
Labels: size/M

#3887 get() reimplementation
  firebase-database/src/androidTest/java/com/google/firebase/database/IntegrationTestHelpers.java
  firebase-database/src/androidTest/java/com/google/firebase/database/QueryTest.java
  firebase-database/src/androidTest/java/com/google/firebase/database/future/ReadFuture.java
  firebase-database/src/main/java/com/google/firebase/database/android/SqlPersistenceStorageEngine.java
  firebase-database/src/main/java/com/google/firebase/database/connection/PersistentConnectionImpl.java
  firebase-database/src/main/java/com/google/firebase/database/core/Path.java
  firebase-database/src/main/java/com/google/firebase/database/core/Repo.java
  firebase-database/src/main/java/com/google/firebase/database/core/SyncPoint.java
  firebase-database/src/main/java/com/google/firebase/database/core/SyncTree.java
  firebase-database/src/main/java/com/google/firebase/database/core/ZombieEventManager.java
Labels: size/L
