Repository firebase/firebase-android-sdk, pull requests merged in 2022-02, with the labels that each got.

#3385 Update `performance-gradle` to `perf-plugin`
  ci/fireci/fireciplugins/fireperf.py
Labels: size/XS

#3388 firebase-messaging-directboot to release with firebase-messaging
  README.md
  firebase-messaging-directboot/firebase-messaging-directboot.gradle
Labels: size/XS

#3012 Clarify the log statements so that it differentiates between sampling…
  firebase-perf/src/main/java/com/google/firebase/perf/transport/RateLimiter.java
  firebase-perf/src/main/java/com/google/firebase/perf/transport/TransportManager.java
  firebase-perf/src/test/java/com/google/firebase/perf/transport/RateLimiterTest.java
  firebase-perf/src/test/java/com/google/firebase/perf/transport/TransportManagerTest.java
Labels: size/L, cla: yes

#3389 Removing unused status
  firebase-appdistribution-stub/api.txt
  firebase-appdistribution-stub/src/main/java/com/google/firebase/appdistribution/FirebaseAppDistributionException.java
  firebase-appdistribution/api.txt
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/FirebaseAppDistributionException.java
Labels: size/S

#3394 Use buildOrThrow instead of build for ImmutableMap.
  encoders/firebase-encoders-proto/firebase-encoders-proto.gradle
  encoders/firebase-encoders-proto/src/test/java/com/google/firebase/encoders/proto/WithCollectionsTests.java
Labels: size/XS

#3393 Edit java docs for Firebase App Distribution
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/AppDistributionRelease.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/BinaryType.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/FirebaseAppDistribution.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/FirebaseAppDistributionException.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/OnProgressListener.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/UpdateProgress.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/UpdateStatus.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/UpdateTask.java
Labels: size/L

#3339 Support encoding and decoding Composite Filters.
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/CompositeFilter.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/remote/RemoteSerializer.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/remote/RemoteSerializerTest.java
  firebase-firestore/src/testUtil/java/com/google/firebase/firestore/testutil/TestUtil.java
Labels: size/L

#3287 Add keep on ComponentRegistrar to prevent renaming of key lookup
  firebase-components/proguard.txt
Labels: size/XS, ok-to-test

#3404 Misc naming fixes
  firebase-firestore/src/test/java/com/google/firebase/firestore/model/TargetIndexMatcherTest.java
Labels: api: firestore

#3405 Better comment about not returning partial batch overlays.
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteDocumentOverlayCache.java
Labels: size/XS

#3368 Serve OR queries from the index.
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/IndexBackfiller.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/IndexManager.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/MemoryIndexManager.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/QueryEngine.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteIndexManager.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/util/LogicUtils.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/IndexBackfillerTest.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/SQLiteIndexManagerTest.java
Labels: size/L

#3413 Fix heartbeat tests
  firebase-common/src/test/java/com/google/firebase/heartbeatinfo/DefaultHeartBeatControllerTest.java
  firebase-common/src/test/java/com/google/firebase/heartbeatinfo/HeartBeatInfoStorageTest.java
Labels: size/M

#3418 Fix flaky PerfSessionTest due to async access to SharedPrefs
  firebase-perf/src/test/java/com/google/firebase/perf/session/PerfSessionTest.java
Labels: size/XS

#3416 Remove AccessHelper.clearPersistence()
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/AccessHelper.java
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/FirestoreTest.java
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/testutil/IntegrationTestUtil.java
Labels: size/S, api: firestore

#3415 Adding null checks for instantiating InstrHttpInputStream/InstrHttpOutputStream
  firebase-perf/src/main/java/com/google/firebase/perf/network/InstrURLConnectionBase.java
  firebase-perf/src/test/java/com/google/firebase/perf/network/InstrURLConnectionBaseTest.java
Labels: size/M

#3417 Add Offset logline
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/IndexBackfiller.java
Labels: size/XS, api: firestore

#3421 Use tryWithResources
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLitePersistence.java
Labels: size/S, api: firestore

#3422 Start backend query processing before local cache processing
  firebase-firestore/CHANGELOG.md
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/SyncEngine.java
Labels: size/XS

#3419 Documentation Fix to FM.RemoteMessage.getMessageId
  firebase-messaging/src/main/java/com/google/firebase/messaging/RemoteMessage.java
Labels: size/XS

#3425 Update Javadoc references from gcm to fcm.
  firebase-messaging/src/main/java/com/google/firebase/messaging/Constants.java
  firebase-messaging/src/main/java/com/google/firebase/messaging/FirebaseMessaging.java
  firebase-messaging/src/main/java/com/google/firebase/messaging/MessagingAnalytics.java
  firebase-messaging/src/main/java/com/google/firebase/messaging/RemoteMessage.java
Labels: size/S

#3426 Stop image download by canceling a Future.
  firebase-messaging/src/main/java/com/google/firebase/messaging/DisplayNotification.java
  firebase-messaging/src/main/java/com/google/firebase/messaging/ImageDownload.java
  firebase-messaging/src/test/java/com/google/firebase/messaging/DisplayNotificationChannelRoboTest.java
  firebase-messaging/src/test/java/com/google/firebase/messaging/DisplayNotificationRoboTest.java
  firebase-messaging/src/test/java/com/google/firebase/messaging/ImageDownloadRoboTest.java
Labels: size/M

#3429 Drunk Sebastian
  firebase-firestore/src/main/java/com/google/firebase/firestore/model/TargetIndexMatcher.java
Labels: size/S, api: firestore

#3434 Remove firebase-appdistribution-stub
  firebase-appdistribution-stub/api.txt
  firebase-appdistribution-stub/firebase-appdistribution-stub.gradle
  firebase-appdistribution-stub/gradle.properties
  firebase-appdistribution-stub/ktx/api.txt
  firebase-appdistribution-stub/ktx/gradle.properties
  firebase-appdistribution-stub/ktx/ktx.gradle
  firebase-appdistribution-stub/ktx/src/androidTest/AndroidManifest.xml
  firebase-appdistribution-stub/ktx/src/androidTest/kotlin/com/google/firebase/appdistribution/ktx/FirebaseAppDistributionTests.kt
  firebase-appdistribution-stub/ktx/src/main/AndroidManifest.xml
  firebase-appdistribution-stub/ktx/src/main/kotlin/com/google/firebase/appdistribution/ktx/FirebaseAppDistribution.kt
  firebase-appdistribution-stub/src/main/AndroidManifest.xml
  firebase-appdistribution-stub/src/main/java/com/google/firebase/appdistribution/AppDistributionRelease.java
  firebase-appdistribution-stub/src/main/java/com/google/firebase/appdistribution/BinaryType.java
  firebase-appdistribution-stub/src/main/java/com/google/firebase/appdistribution/FirebaseAppDistribution.java
  firebase-appdistribution-stub/src/main/java/com/google/firebase/appdistribution/FirebaseAppDistributionException.java
  firebase-appdistribution-stub/src/main/java/com/google/firebase/appdistribution/OnProgressListener.java
  firebase-appdistribution-stub/src/main/java/com/google/firebase/appdistribution/UpdateProgress.java
  firebase-appdistribution-stub/src/main/java/com/google/firebase/appdistribution/UpdateStatus.java
  firebase-appdistribution-stub/src/main/java/com/google/firebase/appdistribution/UpdateTask.java
  firebase-appdistribution-stub/src/test/java/com/google/firebase/appdistribution/FirebaseAppDistributionTest.java
  firebase-appdistribution-stub/src/test/java/com/google/firebase/appdistribution/TestOnCompleteListener.java
  subprojects.cfg
Labels: size/XXL

#3435 Prefer arrayValue when sorting FieldIndex
  firebase-firestore/src/main/java/com/google/firebase/firestore/index/IndexEntry.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/util/Util.java
Labels: size/S

#3122 Fireperf: fix incorrect `sessionId`s for `_fs` and `_bs` traces
  firebase-perf/src/main/java/com/google/firebase/perf/application/AppStateMonitor.java
  firebase-perf/src/main/java/com/google/firebase/perf/application/AppStateUpdateHandler.java
  firebase-perf/src/test/java/com/google/firebase/perf/application/AppStateMonitorTest.java
Labels: size/M, cla: yes

#3432 Log notification open after onActivityCreated() on Android 7.0 and ea…
  firebase-messaging/src/main/java/com/google/firebase/messaging/FcmLifecycleCallbacks.java
Labels: size/S

#3442 Update play services dependencies
  appcheck/firebase-appcheck-debug-testing/firebase-appcheck-debug-testing.gradle
  appcheck/firebase-appcheck-debug/firebase-appcheck-debug.gradle
  appcheck/firebase-appcheck-interop/firebase-appcheck-interop.gradle
  appcheck/firebase-appcheck-safetynet/firebase-appcheck-safetynet.gradle
  appcheck/firebase-appcheck/firebase-appcheck.gradle
  appcheck/firebase-appcheck/test-app/test-app.gradle
  firebase-abt/firebase-abt.gradle
  firebase-appdistribution/firebase-appdistribution.gradle
  firebase-appdistribution/test-app/test-app.gradle
  firebase-common/firebase-common.gradle
  firebase-config/bandwagoner/bandwagoner.gradle
  firebase-config/firebase-config.gradle
  firebase-crashlytics-ndk/firebase-crashlytics-ndk.gradle
  firebase-crashlytics/firebase-crashlytics.gradle
  firebase-database-collection/firebase-database-collection.gradle
  firebase-database/firebase-database.gradle
  firebase-database/ktx/ktx.gradle
  firebase-dynamic-links/firebase-dynamic-links.gradle
  firebase-dynamic-links/ktx/ktx.gradle
  firebase-firestore/firebase-firestore.gradle
  firebase-firestore/ktx/ktx.gradle
  firebase-functions/firebase-functions.gradle
  firebase-functions/ktx/ktx.gradle
  firebase-inappmessaging-display/firebase-inappmessaging-display.gradle
  firebase-inappmessaging/firebase-inappmessaging.gradle
  firebase-inappmessaging/ktx/ktx.gradle
  firebase-installations-interop/firebase-installations-interop.gradle
  firebase-installations/firebase-installations.gradle
  firebase-messaging-directboot/firebase-messaging-directboot.gradle
  firebase-messaging/firebase-messaging.gradle
  firebase-messaging/ktx/ktx.gradle
  firebase-ml-modeldownloader/firebase-ml-modeldownloader.gradle
  firebase-perf/dev-app/dev-app.gradle
  firebase-perf/e2e-app/e2e-app.gradle
  firebase-perf/firebase-perf.gradle
  firebase-segmentation/firebase-segmentation.gradle
  firebase-storage/firebase-storage.gradle
  firebase-storage/ktx/ktx.gradle
  firebase-storage/test-app/test-app.gradle
Labels: size/L

#3447 Fix index deletion bug
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteIndexManager.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/SQLiteIndexManagerTest.java
Labels: size/M, api: firestore

#3450 Support backgrounding browser during sign in on Android 10 and below
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/TesterSignInManager.java
Labels: size/XS

#3449 Update released versions
  firebase-crashlytics-ndk/gradle.properties
  firebase-crashlytics/gradle.properties
  firebase-database/gradle.properties
  firebase-datatransport/gradle.properties
  firebase-firestore/gradle.properties
  firebase-ml-modeldownloader/gradle.properties
  firebase-perf/gradle.properties
  transport/transport-backend-cct/gradle.properties
  transport/transport-runtime/gradle.properties
Labels: size/M

#3444 Remove canServeFromIndex
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/Target.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/IndexManager.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/MemoryIndexManager.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/QueryEngine.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteIndexManager.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/IndexBackfillerTest.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/SQLiteIndexManagerTest.java
Labels: size/M, api: firestore

#3454 Support > and != on the same field
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/Target.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteIndexManager.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/model/Values.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/SQLiteIndexManagerTest.java
Labels: size/M, api: firestore

#3464 Show dialogs on UI thread
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/FirebaseAppDistribution.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/FirebaseAppDistributionLifecycleNotifier.java
  firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/FirebaseAppDistributionTest.java
Labels: size/L

#3462 Revert "Re-establish streams when App Check token expires. (#3328)"
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/FirestoreClient.java
Labels: size/XS

#3463 DocumentOverlayCacheTestCase.testUpdateDocumentOverlay() added
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/DocumentOverlayCacheTestCase.java
Labels: size/S, api: firestore

#3461 Add changelog for initial beta release
  firebase-appdistribution/CHANGELOG.md
Labels: size/XS

#3427 App Distribution Reference Docs Edits
  firebase-appdistribution/api.txt
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/AabUpdater.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/ApkInstaller.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/ApkUpdater.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/AppDistributionRelease.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/AppDistributionReleaseInternal.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/BinaryType.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/Constants.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/FirebaseAppDistribution.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/FirebaseAppDistributionException.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/FirebaseAppDistributionLifecycleNotifier.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/FirebaseAppDistributionRegistrar.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/FirebaseAppDistributionTesterApiClient.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/ReleaseIdentificationUtils.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/TaskUtils.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/TesterSignInManager.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/UpdateProgress.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/internal/InstallActivity.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/internal/SignInResultActivity.java
  firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/AabUpdaterTest.java
  firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/ApkInstallerTests.java
  firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/ApkUpdaterTest.java
  firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/FirebaseAppDistributionTest.java
  firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/FirebaseAppDistributionTesterApiClientTest.java
  firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/NewReleaseFetcherTest.java
  firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/TesterSignInManagerTest.java
Labels: size/L

#3460 call DROP_GLOBAL_LOG_EVENT_STATE_SQL before inserting during migration
  transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/scheduling/persistence/SchemaManager.java
Labels: size/XS

#3473 Upgrade grpc to 1.44.1
  build.gradle
  firebase-database/src/test/java/com/google/firebase/database/util/ComparatorTester.java
  firebase-firestore/CHANGELOG.md
  firebase-firestore/firebase-firestore.gradle
  firebase-firestore/src/testUtil/java/com/google/firebase/firestore/testutil/ComparatorTester.java
  firebase-inappmessaging/firebase-inappmessaging.gradle
  firebase-messaging/firebase-messaging.gradle
  firebase-perf/e2e-app/e2e-app.gradle
Labels: size/S

#3478 Add missing javadoc classpath declarations.
  firebase-database/firebase-database.gradle
  firebase-storage/firebase-storage.gradle
Labels: size/XS

#3474 Backport tests from Web
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/SQLiteIndexManagerTest.java
Labels: size/L

#3484 Make next collection group to update more deterministic
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteIndexManager.java
Labels: size/S

#3438 Refine the project setup for SDK health metrics
  apk-size/README.md
  ci/README.md
  ci/fireci/fireciplugins/binary_size.py
  ci/fireci/fireciplugins/macrobenchmark.py
  health-metrics/README.md
  health-metrics/apk-size/README.md
  health-metrics/apk-size/apk-size.gradle
  health-metrics/apk-size/app/build.gradle
  health-metrics/apk-size/app/configure.gradle
  health-metrics/apk-size/app/default.gradle
  health-metrics/apk-size/app/proguard-rules-aggressive.pro
  health-metrics/apk-size/app/src/base/base.gradle
  health-metrics/apk-size/app/src/main/AndroidManifest.xml
  health-metrics/apk-size/app/src/main/java/com.google.apksize/MainActivity.java
  health-metrics/apk-size/app/src/main/res/layout/activity_main.xml
  health-metrics/apk-size/app/src/main/res/mipmap-hdpi/ic_launcher.png
  health-metrics/apk-size/app/src/main/res/values/colors.xml
  health-metrics/apk-size/app/src/main/res/values/dimens.xml
  health-metrics/apk-size/app/src/main/res/values/strings.xml
  health-metrics/apk-size/app/src/main/res/values/styles.xml
  health-metrics/apk-size/app/src/main/res/xml/remote_config_defaults.xml
  health-metrics/apk-size/gradle.properties
  health-metrics/apk-size/gradle/wrapper/gradle-wrapper.jar
  health-metrics/apk-size/gradle/wrapper/gradle-wrapper.properties
  health-metrics/apk-size/gradlew
  health-metrics/apk-size/gradlew.bat
  health-metrics/apk-size/settings.gradle
  health-metrics/macrobenchmark/config.yaml
  health-metrics/macrobenchmark/template/app/build.gradle.mustache
  health-metrics/macrobenchmark/template/app/proguard-rules.pro
  health-metrics/macrobenchmark/template/app/src/main/AndroidManifest.xml
  health-metrics/macrobenchmark/template/app/src/main/java/com/google/firebase/benchmark/MainActivity.kt
  health-metrics/macrobenchmark/template/app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  health-metrics/macrobenchmark/template/app/src/main/res/drawable/ic_launcher_background.xml
  health-metrics/macrobenchmark/template/app/src/main/res/layout/activity_main.xml
  health-metrics/macrobenchmark/template/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  health-metrics/macrobenchmark/template/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  health-metrics/macrobenchmark/template/app/src/main/res/mipmap-hdpi/ic_launcher.png
  health-metrics/macrobenchmark/template/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  health-metrics/macrobenchmark/template/app/src/main/res/mipmap-mdpi/ic_launcher.png
  health-metrics/macrobenchmark/template/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  health-metrics/macrobenchmark/template/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  health-metrics/macrobenchmark/template/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  health-metrics/macrobenchmark/template/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  health-metrics/macrobenchmark/template/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  health-metrics/macrobenchmark/template/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  health-metrics/macrobenchmark/template/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  health-metrics/macrobenchmark/template/app/src/main/res/values-night/themes.xml
  health-metrics/macrobenchmark/template/app/src/main/res/values/colors.xml
  health-metrics/macrobenchmark/template/app/src/main/res/values/strings.xml
  health-metrics/macrobenchmark/template/app/src/main/res/values/themes.xml
  health-metrics/macrobenchmark/template/benchmark/build.gradle
  health-metrics/macrobenchmark/template/benchmark/proguard-rules.pro
  health-metrics/macrobenchmark/template/benchmark/src/androidTest/AndroidManifest.xml
  health-metrics/macrobenchmark/template/benchmark/src/androidTest/java/com/google/firebase/benchmark/BenchmarkTest.kt.mustache
  health-metrics/macrobenchmark/template/benchmark/src/main/AndroidManifest.xml.mustache
  health-metrics/macrobenchmark/template/build.gradle
  health-metrics/macrobenchmark/template/gradle.properties
  health-metrics/macrobenchmark/template/settings.gradle
Labels: size/M

#3483 Don't generate javadoc for internal code in directboot.
  firebase-messaging-directboot/api.txt
  firebase-messaging-directboot/src/main/java/com/google/firebase/messaging/directboot/threads/package-info.java
Labels: size/M

#3496 Add hide annotation to exclude from doc generation
  firebase-perf/src/main/java/com/google/firebase/perf/application/AppStateUpdateHandler.java
Labels: size/XS

#3472 Integrate V2 heartbeat with app check.
  appcheck/firebase-appcheck/src/main/java/com/google/firebase/appcheck/FirebaseAppCheckRegistrar.java
  appcheck/firebase-appcheck/src/main/java/com/google/firebase/appcheck/internal/DefaultFirebaseAppCheck.java
  appcheck/firebase-appcheck/src/main/java/com/google/firebase/appcheck/internal/NetworkClient.java
  appcheck/firebase-appcheck/src/test/java/com/google/firebase/appcheck/FirebaseAppCheckRegistrarTest.java
  appcheck/firebase-appcheck/src/test/java/com/google/firebase/appcheck/internal/DefaultFirebaseAppCheckTest.java
  appcheck/firebase-appcheck/src/test/java/com/google/firebase/appcheck/internal/NetworkClientTest.java
Labels: size/L

#3495 Fix overlay recalculation bug with multiple batches
  firebase-firestore/CHANGELOG.md
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/LocalDocumentsView.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/LocalStoreTestCase.java
Labels: size/S
