Repository firebase/firebase-android-sdk, pull requests merged in 2022-03, with the labels that each got.

#3497 Always use array_valye
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteIndexManager.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/model/TargetIndexMatcherTest.java
Labels: size/M, api: firestore

#3498 Add new cloud routing header
  firebase-firestore/src/main/java/com/google/firebase/firestore/remote/FirestoreChannel.java
Labels: size/XS

#3485 `Query.get` should wait for backend connection
  firebase-database/CHANGELOG.md
  firebase-database/src/androidTest/java/com/google/firebase/database/QueryTest.java
  firebase-database/src/main/java/com/google/firebase/database/connection/PersistentConnectionImpl.java
  firebase-database/src/main/java/com/google/firebase/database/core/Repo.java
Labels: size/M

#3506 Possible fix for FIAM crash when trying to clear image loading
  firebase-inappmessaging-display/src/main/java/com/google/firebase/inappmessaging/display/FirebaseInAppMessagingDisplay.java
  firebase-inappmessaging-display/src/test/java/com/google/firebase/inappmessaging/display/FirebaseInAppMessagingDisplayTest.java
Labels: size/XS

#3311 Fireperf: fix screen trace in multi-activity apps
  firebase-perf/src/main/java/com/google/firebase/perf/application/AppStateMonitor.java
  firebase-perf/src/test/java/com/google/firebase/perf/application/AppStateMonitorTest.java
Labels: size/S

#3488 Remove need for alternative build script.
  alternative-settings.gradle
  build.gradle
Labels: size/XS

#3489 Fixing sign in cancellation bug
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/TesterSignInManager.java
  firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/TesterSignInManagerTest.java
Labels: size/XS

#3516 Remove unused gradle files.
  alternative-root-project.gradle
  alternative-settings.gradle
Labels: size/M

#3515 Adding more specific notification messages
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/ApkUpdater.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/FirebaseAppDistributionNotificationsManager.java
  firebase-appdistribution/src/main/res/values/strings.xml
  firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/ApkUpdaterTest.java
  firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/FirebaseAppDistributionNotificationsManagerTest.java
Labels: size/M

#3524 Add autovalue to appcheck debug's javadoc classpath
  appcheck/firebase-appcheck-debug-testing/firebase-appcheck-debug-testing.gradle
Labels: size/XS

#3499 Support descending queries
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/Target.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/IndexManager.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/MemoryIndexManager.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/QueryEngine.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteIndexManager.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/core/TargetTest.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/IndexBackfillerTest.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/SQLiteIndexManagerTest.java
Labels: size/L, api: firestore

#3476 Make indexing public
  firebase-annotations/src/main/java/com/google/firebase/annotations/PreviewApi.java
  firebase-firestore/CHANGELOG.md
  firebase-firestore/api.txt
  firebase-firestore/firebase-firestore.gradle
  firebase-firestore/src/main/java/com/google/firebase/firestore/FirebaseFirestore.java
Labels: size/M, api: firestore

#3512 Fireperf m112 changelog
  firebase-perf/CHANGELOG.md
Labels: size/S

#3531 Workaround to make smoke-test pass.
  smoke-tests/build.gradle
Labels: size/XS

#3402 Implement on-demand fatals internally
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/SessionReportingCoordinatorTest.java
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/send/DataTransportCrashlyticsReportSenderTest.java
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/settings/TestSettingsData.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsController.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsCore.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/OnDemandCounter.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/SessionReportingCoordinator.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/send/DataTransportCrashlyticsReportSender.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/send/ReportQueue.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/settings/DefaultSettingsJsonTransform.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/settings/SettingsJsonConstants.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/settings/SettingsV3JsonTransform.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/settings/model/Settings.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/settings/model/SettingsData.java
Labels: size/L

#3533 Fix fcm dependency
  firebase-common/src/main/java/com/google/firebase/FirebaseApp.java
  firebase-messaging/firebase-messaging.gradle
  firebase-messaging/src/main/java/com/google/firebase/messaging/ByteStreams.java
  firebase-messaging/src/main/java/com/google/firebase/messaging/FcmBroadcastProcessor.java
  firebase-messaging/src/main/java/com/google/firebase/messaging/FirebaseMessaging.java
  firebase-messaging/src/main/java/com/google/firebase/messaging/ImageDownload.java
  firebase-messaging/src/main/java/com/google/firebase/messaging/Metadata.java
  firebase-messaging/src/main/java/com/google/firebase/messaging/RequestDeduplicator.java
  firebase-messaging/src/main/java/com/google/firebase/messaging/ServiceStarter.java
  firebase-messaging/src/main/java/com/google/firebase/messaging/SyncTask.java
  firebase-messaging/src/main/java/com/google/firebase/messaging/WakeLockHolder.java
Labels: size/L

#3520 App Check as a heartbeat Consumer since backend works now
  appcheck/firebase-appcheck/src/main/java/com/google/firebase/appcheck/FirebaseAppCheckRegistrar.java
  appcheck/firebase-appcheck/src/test/java/com/google/firebase/appcheck/FirebaseAppCheckRegistrarTest.java
Labels: size/XS

#3537 Fix overlay bug when offline
  firebase-firestore/CHANGELOG.md
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/QueryTest.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/LocalDocumentsView.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/LocalStore.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/model/mutation/MutationBatch.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/LocalStoreTestCase.java
Labels: size/M

#3544 directboot fix
  firebase-messaging-directboot/firebase-messaging-directboot.gradle
Labels: size/XS

#3541 Do not throw when FileStore cannot create a dir.
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/persistence/FileStore.java
Labels: size/XS

#3553 Fix IgnoredPureGetter violation in CrashlyticsReport
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/model/CrashlyticsReport.java
Labels: size/XS, ok-to-test

#3546 Add fragment trace sampling rate config flag
  firebase-perf/src/main/java/com/google/firebase/perf/config/ConfigResolver.java
  firebase-perf/src/main/java/com/google/firebase/perf/config/ConfigurationConstants.java
  firebase-perf/src/test/java/com/google/firebase/perf/config/ConfigResolverTest.java
  firebase-perf/src/test/java/com/google/firebase/perf/config/ConfigurationConstantsTest.java
Labels: size/L

#3547 Update CHANGELOG from m112 release
  firebase-appdistribution/CHANGELOG.md
Labels: size/S

#3518 Change DocumentOverlayCache.saveOverlays() to require non-null values in the given Map
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/LocalDocumentsView.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/MemoryDocumentOverlayCache.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteDocumentOverlayCache.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/model/mutation/Mutation.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/model/mutation/MutationBatch.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/util/Preconditions.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/DocumentOverlayCacheTestCase.java
Labels: size/M, api: firestore

#3549 Don't use Indexes for outdated limit queries
  firebase-firestore/CHANGELOG.md
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/QueryEngine.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/CountingQueryEngine.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/SQLiteLocalStoreTest.java
Labels: size/L, api: firestore

#3555 Add Firebase App Distribution to smoke tests
  smoke-tests/build.gradle
  smoke-tests/src/main/java/com/google/firebase/testing/BuildOnlyTest.java
Labels: size/XS

#3564 Catch RuntimeException when getting analytics Bundle.
  firebase-messaging/src/main/java/com/google/firebase/messaging/FcmLifecycleCallbacks.java
Labels: size/S

#3572 Use assertThrows() in StorageReferenceTest
  firebase-storage/src/test/java/com/google/firebase/storage/StorageReferenceTest.java
Labels: size/S, ok-to-test

#3565 Fireperf: fragment lifecycle callbacks
  firebase-perf/src/main/java/com/google/firebase/perf/application/AppStateMonitor.java
  firebase-perf/src/main/java/com/google/firebase/perf/application/FragmentStateMonitor.java
Labels: size/M

#3532 Fireperf: start screen trace in `onResume`
  firebase-perf/src/main/java/com/google/firebase/perf/application/AppStateMonitor.java
  firebase-perf/src/test/java/com/google/firebase/perf/application/AppStateMonitorTest.java
Labels: size/M

#3576 Revert "Add Firebase App Distribution to smoke tests"
  smoke-tests/build.gradle
  smoke-tests/src/main/java/com/google/firebase/testing/BuildOnlyTest.java
Labels: size/XS

#3580 Java doc updates as per b/190099349
  firebase-dynamic-links/src/main/java/com/google/firebase/dynamiclinks/PendingDynamicLinkData.java
Labels: size/S

#3582 Fix refresh logic for App Check custom providers.
  appcheck/firebase-appcheck/src/main/java/com/google/firebase/appcheck/internal/DefaultAppCheckToken.java
  appcheck/firebase-appcheck/src/test/java/com/google/firebase/appcheck/internal/DefaultAppCheckTokenTest.java
  appcheck/firebase-appcheck/src/test/java/com/google/firebase/appcheck/internal/StorageHelperTest.java
Labels: size/S

#3575 Fireperf fragments: trace creation and adding custom attributes
  firebase-perf/src/main/java/com/google/firebase/perf/application/AppStateMonitor.java
  firebase-perf/src/main/java/com/google/firebase/perf/application/FragmentStateMonitor.java
  firebase-perf/src/main/java/com/google/firebase/perf/util/Constants.java
  firebase-perf/src/test/java/com/google/firebase/perf/application/FragmentStateMonitorTest.java
Labels: size/L

#3543 Revert "[firehorn] Workaround to make smoke-test pass. (#3531)"
  smoke-tests/build.gradle
Labels: size/XS

#3581 Extending test-app to have buttons for all sdk methods
  firebase-appdistribution/test-app/src/main/AndroidManifest.xml
  firebase-appdistribution/test-app/src/main/java/com/googletest/firebase/appdistribution/testapp/MainActivity.kt
  firebase-appdistribution/test-app/src/main/res/layout/activity_main.xml
  firebase-appdistribution/test-app/test-app.gradle
Labels: size/L

#3585 Support App Distribution in smoke tests
  smoke-tests/build.gradle
  smoke-tests/configure.gradle
  smoke-tests/src/main/java/com/google/firebase/testing/BuildOnlyTest.java
Labels: size/XS

#3592 Add frame metrics to fragment traces
  firebase-perf/src/main/java/com/google/firebase/perf/application/AppStateMonitor.java
  firebase-perf/src/main/java/com/google/firebase/perf/application/FragmentStateMonitor.java
  firebase-perf/src/main/java/com/google/firebase/perf/metrics/FrameMetricsCalculator.java
  firebase-perf/src/main/java/com/google/firebase/perf/util/ScreenTraceUtil.java
  firebase-perf/src/test/java/com/google/firebase/perf/application/FragmentStateMonitorTest.java
  firebase-perf/src/test/java/com/google/firebase/perf/metrics/FrameMetricsCalculatorTest.java
Labels: size/L

#3595 Backport early exit from Web
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/Target.java
Labels: size/XS, api: firestore

#3599 Fix screen trace logging by printing the trace name.
  firebase-perf/src/main/java/com/google/firebase/perf/metrics/Trace.java
  firebase-perf/src/main/java/com/google/firebase/perf/util/ScreenTraceUtil.java
Labels: size/XS

#3493 Implement disjunctive normal form (DNF) transform.
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/CompositeFilter.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/FieldFilter.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteIndexManager.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/util/LogicUtils.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/core/FilterTest.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/core/QueryTest.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/QueryEngineTestCase.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/util/LogicUtilsTest.java
Labels: size/XL

#3594 Adding unit tests to ApkUpdater class
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/ApkUpdater.java
  firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/ApkUpdaterTest.java
Labels: size/M

#3598 Add createNotificationInfo() that takes a calling and an app Context.
  firebase-messaging/src/main/java/com/google/firebase/messaging/CommonNotificationBuilder.java
  firebase-messaging/src/test/java/com/google/firebase/messaging/CommonNotificationBuilderRoboTest.java
Labels: size/L

#3604 Fireperf fragments eap: change version number
  firebase-perf/CHANGELOG.md
  firebase-perf/gradle.properties
Labels: size/XS

#3606 Update the gradle properties to match the EAP release branch
  firebase-perf/gradle.properties
Labels: size/S

#3603 Add test for b/226360573
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/QueryEngineTestCase.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/SQLiteQueryEngineTest.java
Labels: size/M, api: firestore
