Repository firebase/firebase-android-sdk, pull requests merged in 2022-12, with the labels that each got.

#4328 Realtime Fetch ID
  firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigAutoFetch.java
  firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigFetchHandler.java
  firebase-config/src/test/java/com/google/firebase/remoteconfig/FirebaseRemoteConfigTest.java
Labels: size/L

#4384 Add spinner when sending feedback
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FeedbackActivity.java
  firebase-appdistribution/src/main/res/layout/activity_feedback.xml
  firebase-appdistribution/src/main/res/values/themes.xml
Labels: size/S

#4363 Add lint check that detects UI thread continuations.
  appcheck/firebase-appcheck-debug/src/main/java/com/google/firebase/appcheck/debug/internal/DebugAppCheckProvider.java
  appcheck/firebase-appcheck-playintegrity/src/main/java/com/google/firebase/appcheck/playintegrity/internal/PlayIntegrityAppCheckProvider.java
  appcheck/firebase-appcheck-safetynet/src/main/java/com/google/firebase/appcheck/safetynet/internal/SafetyNetAppCheckProvider.java
  appcheck/firebase-appcheck/src/main/java/com/google/firebase/appcheck/internal/DefaultFirebaseAppCheck.java
  appcheck/firebase-appcheck/src/main/java/com/google/firebase/appcheck/internal/DefaultTokenRefresher.java
  firebase-appdistribution-api/src/main/java/com/google/firebase/appdistribution/internal/FirebaseAppDistributionStub.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/AabUpdater.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/ApkUpdater.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionImpl.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionTesterApiClient.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/NewReleaseFetcher.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/TesterSignInManager.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/UpdateTaskImpl.java
  firebase-config/src/main/java/com/google/firebase/remoteconfig/FirebaseRemoteConfig.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsController.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/Utils.java
  firebase-database/src/main/java/com/google/firebase/database/android/AndroidAppCheckTokenProvider.java
  firebase-database/src/main/java/com/google/firebase/database/android/AndroidAuthTokenProvider.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/FirebaseFirestore.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/LoadBundleTask.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/FirestoreClient.java
  firebase-inappmessaging/src/main/java/com/google/firebase/inappmessaging/FirebaseInAppMessaging.java
  firebase-inappmessaging/src/main/java/com/google/firebase/inappmessaging/internal/InAppMessageStreamManager.java
  firebase-inappmessaging/src/main/java/com/google/firebase/inappmessaging/internal/MetricsLoggerClient.java
  firebase-messaging/src/main/java/com/google/firebase/messaging/FirebaseMessaging.java
  firebase-messaging/src/main/java/com/google/firebase/messaging/WakeLockHolder.java
  firebase-storage/src/main/java/com/google/firebase/storage/StorageTask.java
  tools/lint/src/main/kotlin/CheckRegistry.kt
  tools/lint/src/main/kotlin/TasksMainThreadDetector.kt
Labels: size/L

#4386 Fix copyrights
  .github/workflows/copyright-check.yml
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/DackkaGenerationTask.kt
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/DackkaPlugin.kt
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/FiresiteTransformTask.kt
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/GradleUtils.kt
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/KotlinUtils.kt
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/ci/ChangedModulesTask.kt
  firebase-appdistribution/test-app/src/main/java/com/googletest/firebase/appdistribution/testapp/MainActivity.kt
  firebase-appdistribution/test-app/src/main/java/com/googletest/firebase/appdistribution/testapp/SecondActivity.kt
  firebase-database/ktx/src/main/kotlin/com/google/firebase/database/ktx/ChildEvent.kt
  firebase-storage/ktx/src/main/kotlin/com/google/firebase/storage/ktx/TaskState.kt
  tools/lint/src/main/kotlin/TasksMainThreadDetector.kt
  tools/lint/src/main/kotlin/ThreadPoolDetector.kt
Labels: size/L

#4385 Forbid creating ui thread Handler.
  firebase-common/src/main/java/com/google/firebase/concurrent/UiExecutor.java
  firebase-database/src/main/java/com/google/firebase/database/android/AndroidEventTarget.java
  firebase-database/src/main/java/com/google/firebase/database/android/AndroidPlatform.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/util/AsyncQueue.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/util/Util.java
  firebase-messaging/src/main/java/com/google/firebase/messaging/FcmLifecycleCallbacks.java
  firebase-perf/firebase-perf.gradle
  firebase-perf/src/main/java/com/google/firebase/perf/FirebasePerfEarly.java
  firebase-perf/src/main/java/com/google/firebase/perf/FirebasePerfRegistrar.java
  firebase-perf/src/main/java/com/google/firebase/perf/util/FirstDrawDoneListener.java
  firebase-perf/src/main/java/com/google/firebase/perf/util/PreDrawListener.java
  firebase-perf/src/test/java/com/google/firebase/perf/FirebasePerfRegistrarTest.java
  firebase-storage/src/main/java/com/google/firebase/storage/internal/SmartHandler.java
  tools/lint/src/main/kotlin/ThreadPoolDetector.kt
Labels: size/M

#4375 Inject executor service for Realtime components.
  firebase-config/src/main/java/com/google/firebase/remoteconfig/RemoteConfigComponent.java
  firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigAutoFetch.java
  firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigRealtimeHandler.java
  firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigRealtimeHttpClient.java
  firebase-config/src/test/java/com/google/firebase/remoteconfig/FirebaseRemoteConfigTest.java
  firebase-config/src/test/java/com/google/firebase/remoteconfig/RemoteConfigComponentTest.java
Labels: size/M, no-changelog

#4379 Add workflow triggers for startup time test
  .github/workflows/health-metrics.yml
  ci/fireci/fireci/uploader.py
  ci/fireci/fireciplugins/macrobenchmark/commands.py
  ci/fireci/fireciplugins/macrobenchmark/run/test_project.py
Labels: size/L

#4392 Enable for Kotlin Gradle dsl.
  build.gradle
  firebase-common/ktx/ktx.gradle
  firebase-common/ktx/ktx.gradle.kts
  gradle/libs.versions.toml
  gradle/projectSettings.gradle
  settings.gradle
Labels: size/L

#4393 Migrate RC to common executors.
  firebase-config/firebase-config.gradle
  firebase-config/src/main/java/com/google/firebase/remoteconfig/FirebaseRemoteConfig.java
  firebase-config/src/main/java/com/google/firebase/remoteconfig/RemoteConfigComponent.java
  firebase-config/src/main/java/com/google/firebase/remoteconfig/RemoteConfigRegistrar.java
  firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigCacheClient.java
Labels: size/M

#4394 Allow task subclasses to implement overloads.
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/UpdateTaskImpl.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/LoadBundleTask.java
  tools/lint/src/main/kotlin/TasksMainThreadDetector.kt
  tools/lint/src/test/kotlin/TasksMainThreadDetectorTests.kt
Labels: size/L

#4383 Remove unused Executor classes.
  firebase-messaging-directboot/CHANGELOG.md
  firebase-messaging-directboot/src/main/java/com/google/firebase/messaging/directboot/threads/ExecutorFactory.java
  firebase-messaging-directboot/src/main/java/com/google/firebase/messaging/directboot/threads/PoolableExecutors.java
  firebase-messaging-directboot/src/main/java/com/google/firebase/messaging/directboot/threads/ThreadPriority.java
  firebase-messaging-directboot/src/main/java/com/google/firebase/messaging/directboot/threads/package-info.java
Labels: size/L

#4423 Upgrade JaCoCo plugin version
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/ci/Coverage.java
Labels: size/XS

#4427 Initial setup for Github Pages
  .github/workflows/jekyll-gh-pages.yml
  contributor-docs/README.md
  contributor-docs/_config.yml
  contributor-docs/_includes/favicon.html
  contributor-docs/_includes/nav_footer_custom.html
  contributor-docs/how_firebase_works.md
  contributor-docs/in_depth/components.md
  contributor-docs/in_depth/in_depth.md
  contributor-docs/onboarding/as_open_project.png
  contributor-docs/onboarding/env_setup.md
  contributor-docs/onboarding/new_sdk.md
  contributor-docs/onboarding/onboarding.md
Labels: size/XL

#4429 Add Component documentation
  contributor-docs/README.md
  contributor-docs/_config.yml
  contributor-docs/components/components.md
  contributor-docs/components/dependencies.md
  contributor-docs/components/multibindings.md
  contributor-docs/how_firebase_works.md
  contributor-docs/in_depth/components.md
  contributor-docs/in_depth/in_depth.md
Labels: size/L

#4428 Change concurrency group for health metrics test to "github.sha"
  .github/workflows/health-metrics.yml
Labels: size/XS

#4434 Port app.get() check from errorprone to lint
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/FirebaseJavaLibraryPlugin.java
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/FirebaseLibraryExtension.java
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/FirebaseLibraryPlugin.java
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/FirebaseStaticAnalysis.java
  gradle.properties
  subprojects.cfg
  tools/errorprone/errorprone.gradle
  tools/errorprone/src/main/java/com/google/firebase/errorprone/ComponentsAppGetCheck.java
  tools/errorprone/src/test/java/com/google/firebase/FirebaseApp.java
  tools/errorprone/src/test/java/com/google/firebase/errorprone/ComponentsAppGetCheckTest.java
  tools/errorprone/src/test/resources/com/google/firebase/errorprone/FirebaseUseExplicitDependenciesNegativeCases.java
  tools/errorprone/src/test/resources/com/google/firebase/errorprone/FirebaseUseExplicitDependenciesPositiveCases.java
  tools/lint/src/main/kotlin/CheckRegistry.kt
  tools/lint/src/main/kotlin/FirebaseAppGetDetector.kt
  tools/lint/src/test/kotlin/FirebaseAppGetDetectorTests.kt
Labels: size/XL

#4437 Added more docs
  contributor-docs/_config.yml
  contributor-docs/best_practices/best_practices.md
  contributor-docs/components/components.md
  contributor-docs/components/dependencies.md
  contributor-docs/components/dynamic_modules.md
  contributor-docs/components/executors.md
  contributor-docs/how_firebase_works.md
  contributor-docs/onboarding/new_sdk.md
  contributor-docs/onboarding/onboarding.md
  docs/executors.md
Labels: size/XL

#4430 Use sequential executor in place of synchronized blocks for cached new release
  firebase-appdistribution/firebase-appdistribution.gradle
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/AppDistributionReleaseInternal.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionImpl.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionRegistrar.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/SequentialReference.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/TaskUtils.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/UpdateTaskImpl.java
  firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionServiceImplTest.java
  firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/TestUtils.java
Labels: size/XL

#4431 Migrate `firebase-appcheck` to use standard executors provided by Firebase Common.
  appcheck/firebase-appcheck/CHANGELOG.md
  appcheck/firebase-appcheck/firebase-appcheck.gradle
  appcheck/firebase-appcheck/src/main/java/com/google/firebase/appcheck/FirebaseAppCheckRegistrar.java
  appcheck/firebase-appcheck/src/main/java/com/google/firebase/appcheck/internal/DefaultFirebaseAppCheck.java
  appcheck/firebase-appcheck/src/main/java/com/google/firebase/appcheck/internal/DefaultTokenRefresher.java
  appcheck/firebase-appcheck/src/main/java/com/google/firebase/appcheck/internal/TokenRefreshManager.java
  appcheck/firebase-appcheck/src/test/java/com/google/firebase/appcheck/FirebaseAppCheckRegistrarTest.java
  appcheck/firebase-appcheck/src/test/java/com/google/firebase/appcheck/internal/DefaultFirebaseAppCheckTest.java
Labels: size/M

#4395 Fix RC Executor annotation
  firebase-config/src/main/java/com/google/firebase/remoteconfig/RemoteConfigComponent.java
Labels: size/XS

#4449 Migrate remaining App Check SDKs to go/firebase-android-executors.
  appcheck/firebase-appcheck-debug-testing/CHANGELOG.md
  appcheck/firebase-appcheck-debug/CHANGELOG.md
  appcheck/firebase-appcheck-debug/firebase-appcheck-debug.gradle
  appcheck/firebase-appcheck-debug/src/main/java/com/google/firebase/appcheck/debug/FirebaseAppCheckDebugRegistrar.java
  appcheck/firebase-appcheck-debug/src/main/java/com/google/firebase/appcheck/debug/internal/DebugAppCheckProvider.java
  appcheck/firebase-appcheck-debug/src/test/java/com/google/firebase/appcheck/debug/FirebaseAppCheckDebugRegistrarTest.java
  appcheck/firebase-appcheck-debug/src/test/java/com/google/firebase/appcheck/debug/internal/DebugAppCheckProviderTest.java
  appcheck/firebase-appcheck-playintegrity/CHANGELOG.md
  appcheck/firebase-appcheck-playintegrity/firebase-appcheck-playintegrity.gradle
  appcheck/firebase-appcheck-playintegrity/src/main/java/com/google/firebase/appcheck/playintegrity/FirebaseAppCheckPlayIntegrityRegistrar.java
  appcheck/firebase-appcheck-playintegrity/src/main/java/com/google/firebase/appcheck/playintegrity/internal/PlayIntegrityAppCheckProvider.java
  appcheck/firebase-appcheck-playintegrity/src/test/java/com/google/firebase/appcheck/playintegrity/FirebaseAppCheckPlayIntegrityRegistrarTest.java
  appcheck/firebase-appcheck-playintegrity/src/test/java/com/google/firebase/appcheck/playintegrity/internal/PlayIntegrityAppCheckProviderTest.java
  appcheck/firebase-appcheck-safetynet/CHANGELOG.md
  appcheck/firebase-appcheck-safetynet/firebase-appcheck-safetynet.gradle
  appcheck/firebase-appcheck-safetynet/src/main/java/com/google/firebase/appcheck/safetynet/FirebaseAppCheckSafetyNetRegistrar.java
  appcheck/firebase-appcheck-safetynet/src/main/java/com/google/firebase/appcheck/safetynet/internal/SafetyNetAppCheckProvider.java
  appcheck/firebase-appcheck-safetynet/src/test/java/com/google/firebase/appcheck/safetynet/FirebaseAppCheckSafetyNetRegistrarTest.java
  appcheck/firebase-appcheck-safetynet/src/test/java/com/google/firebase/appcheck/safetynet/internal/SafetyNetAppCheckProviderTest.java
  appcheck/firebase-appcheck/CHANGELOG.md
Labels: size/L

#4452 Migrate core libraries to Gradle Kotlin DSL.
  appcheck/firebase-appcheck-debug-testing/firebase-appcheck-debug-testing.gradle
  appcheck/firebase-appcheck/firebase-appcheck.gradle
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/ProjectUtils.kt
  contributor-docs/best_practices/dependency_injection.md
  firebase-annotations/firebase-annotations.gradle.kts
  firebase-common/data-collection-tests/data-collection-tests.gradle
  firebase-common/data-collection-tests/data-collection-tests.gradle.kts
  firebase-common/firebase-common.gradle
  firebase-common/firebase-common.gradle.kts
  firebase-common/lint-baseline.xml
  firebase-components/firebase-components.gradle
  firebase-components/firebase-components.gradle.kts
  firebase-components/firebase-dynamic-module-support/firebase-dynamic-module-support.gradle
  firebase-components/firebase-dynamic-module-support/firebase-dynamic-module-support.gradle.kts
  firebase-functions/firebase-functions.gradle
  firebase-functions/firebase-functions.gradle.kts
  firebase-functions/ktx/ktx.gradle
  firebase-functions/ktx/ktx.gradle.kts
  gradle/libs.versions.toml
  tools/lint/lint.gradle
  tools/lint/lint.gradle.kts
Labels: size/XL

#4456 Remove unused jetbrains annotations dependencies
  firebase-appdistribution-api/firebase-appdistribution-api.gradle
  firebase-appdistribution/firebase-appdistribution.gradle
Labels: size/XS

#4442 Fix overlay bug leas to patch mutation optimization not being applied
  firebase-firestore/CHANGELOG.md
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/LocalDocumentsView.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/OverlayedDocument.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/model/mutation/MutationBatch.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/CountingQueryEngine.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/LocalStoreTestCase.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/SQLiteLocalStoreTest.java
  firebase-firestore/src/testUtil/java/com/google/firebase/firestore/testutil/TestUtil.java
Labels: size/L

#4426 Add Diff Javadoc workflow
  .github/workflows/diff-javadoc.yml
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/ci/ChangedModulesTask.kt
Labels: size/M

#4453 Move continuations off main thread for App Check SDKs.
  appcheck/firebase-appcheck-debug/CHANGELOG.md
  appcheck/firebase-appcheck-debug/src/main/java/com/google/firebase/appcheck/debug/FirebaseAppCheckDebugRegistrar.java
  appcheck/firebase-appcheck-debug/src/main/java/com/google/firebase/appcheck/debug/internal/DebugAppCheckProvider.java
  appcheck/firebase-appcheck-debug/src/test/java/com/google/firebase/appcheck/debug/FirebaseAppCheckDebugRegistrarTest.java
  appcheck/firebase-appcheck-debug/src/test/java/com/google/firebase/appcheck/debug/internal/DebugAppCheckProviderTest.java
  appcheck/firebase-appcheck-playintegrity/CHANGELOG.md
  appcheck/firebase-appcheck-playintegrity/src/main/java/com/google/firebase/appcheck/playintegrity/FirebaseAppCheckPlayIntegrityRegistrar.java
  appcheck/firebase-appcheck-playintegrity/src/main/java/com/google/firebase/appcheck/playintegrity/internal/PlayIntegrityAppCheckProvider.java
  appcheck/firebase-appcheck-playintegrity/src/test/java/com/google/firebase/appcheck/playintegrity/FirebaseAppCheckPlayIntegrityRegistrarTest.java
  appcheck/firebase-appcheck-playintegrity/src/test/java/com/google/firebase/appcheck/playintegrity/internal/PlayIntegrityAppCheckProviderTest.java
  appcheck/firebase-appcheck-safetynet/CHANGELOG.md
  appcheck/firebase-appcheck-safetynet/src/main/java/com/google/firebase/appcheck/safetynet/FirebaseAppCheckSafetyNetRegistrar.java
  appcheck/firebase-appcheck-safetynet/src/main/java/com/google/firebase/appcheck/safetynet/internal/SafetyNetAppCheckProvider.java
  appcheck/firebase-appcheck-safetynet/src/test/java/com/google/firebase/appcheck/safetynet/FirebaseAppCheckSafetyNetRegistrarTest.java
  appcheck/firebase-appcheck-safetynet/src/test/java/com/google/firebase/appcheck/safetynet/internal/SafetyNetAppCheckProviderTest.java
  appcheck/firebase-appcheck/CHANGELOG.md
  appcheck/firebase-appcheck/src/main/java/com/google/firebase/appcheck/FirebaseAppCheckRegistrar.java
  appcheck/firebase-appcheck/src/main/java/com/google/firebase/appcheck/internal/DefaultFirebaseAppCheck.java
  appcheck/firebase-appcheck/src/main/java/com/google/firebase/appcheck/internal/DefaultTokenRefresher.java
  appcheck/firebase-appcheck/src/main/java/com/google/firebase/appcheck/internal/TokenRefreshManager.java
  appcheck/firebase-appcheck/src/test/java/com/google/firebase/appcheck/FirebaseAppCheckRegistrarTest.java
  appcheck/firebase-appcheck/src/test/java/com/google/firebase/appcheck/internal/DefaultFirebaseAppCheckTest.java
  appcheck/firebase-appcheck/src/test/java/com/google/firebase/appcheck/internal/DefaultTokenRefresherTest.java
Labels: size/L

#4382 update mlkitdownloader to use executors
  firebase-ml-modeldownloader/firebase-ml-modeldownloader.gradle
  firebase-ml-modeldownloader/src/main/java/com/google/firebase/ml/modeldownloader/FirebaseModelDownloader.java
  firebase-ml-modeldownloader/src/main/java/com/google/firebase/ml/modeldownloader/FirebaseModelDownloaderRegistrar.java
  firebase-ml-modeldownloader/src/main/java/com/google/firebase/ml/modeldownloader/ModelDownloaderComponent.java
  firebase-ml-modeldownloader/src/main/java/com/google/firebase/ml/modeldownloader/internal/CustomModelDownloadService.java
  firebase-ml-modeldownloader/src/test/java/com/google/firebase/ml/modeldownloader/FirebaseModelDownloaderTest.java
Labels: size/L

#4460 Secure external Github Actions
  .github/workflows/build-src-check.yml
  .github/workflows/create_releases.yml
  .github/workflows/diff-javadoc.yml
  .github/workflows/merge-to-main.yml
  .github/workflows/update-cpp-sdk-on-release.yml
Labels: size/S

#4465 clean up logging
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/AabUpdater.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/ApkInstaller.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/ApkUpdater.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/AppIconSource.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FeedbackActivity.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionImpl.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionNotificationsManager.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionRegistrar.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionTesterApiClient.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/ImageUtils.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/InstallActivity.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/LogWrapper.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/NewReleaseFetcher.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/ReleaseIdentifier.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/SignInResultActivity.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/TakeScreenshotAndStartFeedbackActivity.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/TaskUtils.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/TesterApiHttpClient.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/TesterSignInManager.java
Labels: size/L

#4462 Fix typo in comments.
  firebase-firestore/src/main/java/com/google/firebase/firestore/Filter.java
Labels: size/XS

#4477 Fix errors after rebase on fad/next
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FeedbackActivity.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FeedbackSender.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionImpl.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionLifecycleNotifier.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/ScreenshotTaker.java
  firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionNotificationsManagerTest.java
Labels: size/S, no-changelog

#4446 FIAM: Reduce load on app's Main thread [fiam]
  firebase-inappmessaging-display/CHANGELOG.md
  firebase-inappmessaging/CHANGELOG.md
  firebase-inappmessaging/src/androidTest/java/com/google/firebase/inappmessaging/FirebaseInAppMessagingFlowableTest.java
  firebase-inappmessaging/src/androidTest/java/com/google/firebase/inappmessaging/TestEngagementMetricsLoggerClientModule.java
  firebase-inappmessaging/src/main/java/com/google/firebase/inappmessaging/FirebaseInAppMessaging.java
  firebase-inappmessaging/src/main/java/com/google/firebase/inappmessaging/FirebaseInAppMessagingRegistrar.java
  firebase-inappmessaging/src/main/java/com/google/firebase/inappmessaging/internal/InAppMessageStreamManager.java
  firebase-inappmessaging/src/main/java/com/google/firebase/inappmessaging/internal/MetricsLoggerClient.java
  firebase-inappmessaging/src/main/java/com/google/firebase/inappmessaging/internal/injection/components/UniversalComponent.java
  firebase-inappmessaging/src/main/java/com/google/firebase/inappmessaging/internal/injection/modules/ExecutorsModule.java
  firebase-inappmessaging/src/main/java/com/google/firebase/inappmessaging/internal/injection/modules/TransportClientModule.java
  firebase-inappmessaging/src/test/java/com/google/firebase/inappmessaging/FirebaseInAppMessagingTest.java
  firebase-inappmessaging/src/test/java/com/google/firebase/inappmessaging/internal/InAppMessageStreamManagerTest.java
  firebase-inappmessaging/src/test/java/com/google/firebase/inappmessaging/internal/MetricsLoggerClientTest.java
Labels: size/L

#4350 Migrate some executors in fad/in-app-feedback
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionImpl.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionRegistrar.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/ScreenshotTaker.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/SignInStorage.java
Labels: size/M

#4480 Move SharedPreferences usage to background thread
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionImpl.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionRegistrar.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/SignInStorage.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/TaskUtils.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/TesterSignInManager.java
  firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionServiceImplTest.java
  firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/TestUtils.java
  firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/TesterSignInManagerTest.java
Labels: size/L

#4482 Clean up ApkUpdater
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/ApkUpdater.java
  firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/ApkUpdaterTest.java
Labels: size/M

#4490 Do not wait to store state when signing out
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionImpl.java
  firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionServiceImplTest.java
Labels: size/M

#4491 Clean up sign in state management
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/SignInStorage.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/TesterSignInManager.java
  firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/TesterSignInManagerTest.java
Labels: size/L

#4483 Added reference to contributor doc in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: size/XS, no-changelog
