Repository firebase/firebase-android-sdk, pull requests merged in 2023-10, with the labels that each got.

#5346 Clean up and re-enable OR query integration tests.
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/QueryTest.java
Labels: size/M

#5149 Bump Robolectric to 4.10.3
  firebase-perf/firebase-perf.gradle
  gradle/libs.versions.toml
Labels: size/XS

#5352 Testing composite index queries against production
  .github/workflows/ci_tests.yml
  .gitignore
  firebase-firestore/firestore_index_config.tf
  firebase-firestore/main.tf
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/CompositeIndexQueryTest.java
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/QueryTest.java
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/testutil/CompositeIndexTestHelper.java
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/testutil/IntegrationTestUtil.java
Labels: size/XL, no-changelog

#5382 Update RecipeVersionWriter.java
  buildSrc/src/main/java/com/google/firebase/gradle/bomgenerator/RecipeVersionWriter.java
Labels: size/XS

#5385 Don't include ktx entries in generated recipes
  buildSrc/src/main/java/com/google/firebase/gradle/bomgenerator/RecipeVersionWriter.java
Labels: size/M

#5389 update deprecation message for common
  appcheck/firebase-appcheck/CHANGELOG.md
  appcheck/firebase-appcheck/src/main/java/com/google/firebase/appcheck/ktx/FirebaseAppCheck.kt
  firebase-appdistribution-api/CHANGELOG.md
  firebase-appdistribution-api/src/main/java/com/google/firebase/appdistribution/ktx/FirebaseAppDistribution.kt
  firebase-common/CHANGELOG.md
  firebase-common/src/main/java/com/google/firebase/ktx/Firebase.kt
  firebase-config/CHANGELOG.md
  firebase-config/src/main/java/com/google/firebase/remoteconfig/ktx/RemoteConfig.kt
  firebase-crashlytics/CHANGELOG.md
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/ktx/FirebaseCrashlytics.kt
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/ktx/KeyValueBuilder.kt
  firebase-database/CHANGELOG.md
  firebase-database/src/main/java/com/google/firebase/database/ktx/ChildEvent.kt
  firebase-database/src/main/java/com/google/firebase/database/ktx/Database.kt
  firebase-dynamic-links/CHANGELOG.md
  firebase-dynamic-links/src/main/java/com/google/firebase/dynamiclinks/ktx/FirebaseDynamicLinks.kt
  firebase-firestore/CHANGELOG.md
  firebase-firestore/src/main/java/com/google/firebase/firestore/ktx/Firestore.kt
  firebase-functions/CHANGELOG.md
  firebase-functions/src/main/java/com/google/firebase/functions/ktx/Functions.kt
  firebase-inappmessaging-display/CHANGELOG.md
  firebase-inappmessaging-display/src/main/java/com/google/firebase/inappmessaging/display/ktx/InAppMessagingDisplay.kt
  firebase-inappmessaging/CHANGELOG.md
  firebase-inappmessaging/src/main/java/com/google/firebase/inappmessaging/ktx/InAppMessaging.kt
  firebase-installations/CHANGELOG.md
  firebase-installations/src/main/java/com/google/firebase/installations/ktx/Installations.kt
  firebase-messaging/CHANGELOG.md
  firebase-messaging/src/main/java/com/google/firebase/messaging/ktx/Messaging.kt
  firebase-ml-modeldownloader/CHANGELOG.md
  firebase-ml-modeldownloader/src/main/java/com/google/firebase/ml/modeldownloader/ktx/ModelDownloader.kt
  firebase-perf/CHANGELOG.md
  firebase-perf/src/main/java/com/google/firebase/perf/ktx/Performance.kt
  firebase-storage/CHANGELOG.md
  firebase-storage/src/main/java/com/google/firebase/storage/ktx/Storage.kt
  firebase-storage/src/main/java/com/google/firebase/storage/ktx/TaskState.kt
Labels: size/L

#5388 Remove unnecessary custom shadow annotations.
  firebase-messaging/src/test/java/com/google/firebase/messaging/FirebaseMessagingServiceRoboTest.java
  firebase-messaging/src/test/java/com/google/firebase/messaging/TopicsStoreRoboTest.java
Labels: size/XS, no-changelog

#5392 Add NonNull annotation to qualified and unqualified
  firebase-components/src/main/java/com/google/firebase/components/Qualified.java
Labels: size/XS, no-changelog, main-merge-ack

#5391 Remove deprecated ktx packages from sessions
  firebase-sessions/firebase-sessions.gradle.kts
  firebase-sessions/src/androidTest/kotlin/com/google/firebase/sessions/FirebaseSessionsTests.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/FirebaseSessions.kt
  firebase-sessions/src/test/kotlin/com/google/firebase/sessions/ApplicationInfoTest.kt
  firebase-sessions/src/test/kotlin/com/google/firebase/sessions/testing/FakeFirebaseApp.kt
Labels: size/S, no-changelog, main-merge-ack

#5393 Setup scaffolding for SessionMaintainer
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/FirebaseSessions.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/FirebaseSessionsRegistrar.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionMaintainer.kt
Labels: size/M, no-changelog

#5390 Update common version
  appcheck/firebase-appcheck/firebase-appcheck.gradle
  appcheck/firebase-appcheck/ktx/ktx.gradle
  contributor-docs/onboarding/new_sdk.md
  firebase-appdistribution-api/firebase-appdistribution-api.gradle
  firebase-appdistribution-api/ktx/ktx.gradle
  firebase-common/gradle.properties
  firebase-common/ktx/ktx.gradle.kts
  firebase-components/gradle.properties
  firebase-config/bandwagoner/bandwagoner.gradle
  firebase-config/firebase-config.gradle
  firebase-config/ktx/ktx.gradle
  firebase-crashlytics-ndk/firebase-crashlytics-ndk.gradle
  firebase-crashlytics/firebase-crashlytics.gradle
  firebase-crashlytics/ktx/ktx.gradle
  firebase-database/firebase-database.gradle.kts
  firebase-database/ktx/ktx.gradle.kts
  firebase-dynamic-links/firebase-dynamic-links.gradle
  firebase-dynamic-links/ktx/ktx.gradle
  firebase-firestore/firebase-firestore.gradle
  firebase-firestore/ktx/ktx.gradle
  firebase-functions/firebase-functions.gradle.kts
  firebase-functions/ktx/ktx.gradle.kts
  firebase-inappmessaging-display/firebase-inappmessaging-display.gradle
  firebase-inappmessaging-display/ktx/ktx.gradle
  firebase-inappmessaging/firebase-inappmessaging.gradle
  firebase-inappmessaging/ktx/ktx.gradle
  firebase-installations/firebase-installations.gradle
  firebase-installations/ktx/ktx.gradle
  firebase-messaging/firebase-messaging.gradle
  firebase-messaging/ktx/ktx.gradle
  firebase-ml-modeldownloader/firebase-ml-modeldownloader.gradle
  firebase-ml-modeldownloader/ktx/ktx.gradle
  firebase-perf/dev-app/dev-app.gradle
  firebase-perf/firebase-perf.gradle
  firebase-perf/ktx/ktx.gradle
  firebase-sessions/firebase-sessions.gradle.kts
  firebase-storage/firebase-storage.gradle
  firebase-storage/ktx/ktx.gradle
  integ-testing/integ-testing.gradle.kts
Labels: size/L

#5397 Introduces a SessionDataService which is bound to by clients in each …
  firebase-sessions/src/main/AndroidManifest.xml
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/FirebaseSessions.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionDataService.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionInitiator.kt
Labels: size/L

#5399 New datastore for holding session id and timestamp
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionDatastore.kt
Labels: size/M, no-changelog

#5398 add version dependeny for RC interop
  firebase-config-interop/gradle.properties
  firebase-config/firebase-config.gradle
Labels: size/XS

#5405 Declare firebase-common dependency as api in firebase-appcheck
  appcheck/firebase-appcheck/CHANGELOG.md
  appcheck/firebase-appcheck/firebase-appcheck.gradle
  appcheck/firebase-appcheck/test-app/src/main/AndroidManifest.xml
  appcheck/firebase-appcheck/test-app/test-app.gradle
Labels: size/XS

#5403 Splits the SessionDataService into a service and client
  firebase-sessions/src/main/AndroidManifest.xml
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/FirebaseSessions.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionDataService.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionInitiator.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionLifecycleClient.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionLifecycleService.kt
Labels: size/XL

#5406 Avoid changing api surface
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionDatastore.kt
Labels: size/XS, no-changelog

#5407 Rename SessionCoordinator to SessionFirelogPublisher and add `getInstance` so it can be accessed from a bound service.
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/FirebaseSessions.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/FirebaseSessionsRegistrar.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionFirelogPublisher.kt
  firebase-sessions/src/test/kotlin/com/google/firebase/sessions/SessionFirelogPublisherTest.kt
Labels: size/M, no-changelog

#5408 Add FINISHED_AFTER_HANDLED metadata to FirebaseInstanceIdReceiver.
  firebase-messaging/CHANGELOG.md
  firebase-messaging/src/main/AndroidManifest.xml
Labels: size/XS

#5365 swap out the datatransport backend for ml modeldownloader
  firebase-ml-modeldownloader/CHANGELOG.md
  firebase-ml-modeldownloader/firebase-ml-modeldownloader.gradle
  firebase-ml-modeldownloader/src/main/java/com/google/firebase/ml/modeldownloader/FirebaseModelDownloaderRegistrar.java
Labels: size/S

#5412 Make SessionGenerator injectable
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/FirebaseSessions.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/FirebaseSessionsRegistrar.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionGenerator.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/TimeProvider.kt
  firebase-sessions/src/test/kotlin/com/google/firebase/sessions/SessionGeneratorTest.kt
  firebase-sessions/src/test/kotlin/com/google/firebase/sessions/SessionInitiatorTest.kt
Labels: size/M, no-changelog

#5411 Notify subscribers on session update.
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/FirebaseSessions.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionLifecycleClient.kt
Labels: size/S, no-changelog

#5413 Fix a bunch of warnings on this class so that bryan can continue to have vimean superpowers.
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionInitiator.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionLifecycleClient.kt
Labels: size/S, no-changelog

#5410 Specify notification's dismiss intent target via action instead of co…
  firebase-messaging/CHANGELOG.md
  firebase-messaging/src/main/java/com/google/firebase/messaging/CommonNotificationBuilder.java
  firebase-messaging/src/test/java/com/google/firebase/messaging/CommonNotificationBuilderRoboTest.java
  firebase-messaging/src/test/java/com/google/firebase/messaging/FirebaseMessagingServiceRoboTest.java
Labels: size/S

#5409 fix deprecation message
  appcheck/firebase-appcheck/src/main/java/com/google/firebase/appcheck/ktx/FirebaseAppCheck.kt
  firebase-appdistribution-api/src/main/java/com/google/firebase/appdistribution/ktx/FirebaseAppDistribution.kt
  firebase-common/src/main/java/com/google/firebase/ktx/Firebase.kt
  firebase-config/src/main/java/com/google/firebase/remoteconfig/ktx/RemoteConfig.kt
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/ktx/FirebaseCrashlytics.kt
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/ktx/KeyValueBuilder.kt
  firebase-database/src/main/java/com/google/firebase/database/ktx/ChildEvent.kt
  firebase-database/src/main/java/com/google/firebase/database/ktx/Database.kt
  firebase-dynamic-links/src/main/java/com/google/firebase/dynamiclinks/ktx/FirebaseDynamicLinks.kt
  firebase-firestore/src/main/java/com/google/firebase/firestore/ktx/Firestore.kt
  firebase-functions/src/main/java/com/google/firebase/functions/ktx/Functions.kt
  firebase-inappmessaging-display/src/main/java/com/google/firebase/inappmessaging/display/ktx/InAppMessagingDisplay.kt
  firebase-inappmessaging/src/main/java/com/google/firebase/inappmessaging/ktx/InAppMessaging.kt
  firebase-installations/src/main/java/com/google/firebase/installations/ktx/Installations.kt
  firebase-messaging/src/main/java/com/google/firebase/messaging/ktx/Messaging.kt
  firebase-ml-modeldownloader/src/main/java/com/google/firebase/ml/modeldownloader/ktx/ModelDownloader.kt
  firebase-perf/src/main/java/com/google/firebase/perf/ktx/Performance.kt
  firebase-storage/src/main/java/com/google/firebase/storage/ktx/Storage.kt
  firebase-storage/src/main/java/com/google/firebase/storage/ktx/TaskState.kt
Labels: size/XXL

#5416 Hooks up the SessionGenerator to the SessionLifecycleService
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionLifecycleService.kt
Labels: size/M

#5418 Remove annotation from FirebaseOptions accessor
  firebase-common/src/main/java/com/google/firebase/ktx/Firebase.kt
Labels: size/XS

#5415 Make SessionsSettings injectable
  firebase-sessions/src/androidTest/kotlin/com/google/firebase/sessions/FirebaseSessionsTests.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/FirebaseSessions.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/FirebaseSessionsRegistrar.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionFirelogPublisher.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionInitiateListener.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionMaintainer.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/settings/SessionsSettings.kt
Labels: size/L, no-changelog

#5419 update firebase sdks to depend on the new version of common
  appcheck/firebase-appcheck-debug-testing/firebase-appcheck-debug-testing.gradle
  appcheck/firebase-appcheck-debug/firebase-appcheck-debug.gradle
  appcheck/firebase-appcheck-playintegrity/firebase-appcheck-playintegrity.gradle
  appcheck/firebase-appcheck-safetynet/firebase-appcheck-safetynet.gradle
  appcheck/firebase-appcheck/firebase-appcheck.gradle
  appcheck/firebase-appcheck/ktx/ktx.gradle
  contributor-docs/onboarding/new_sdk.md
  firebase-appdistribution-api/firebase-appdistribution-api.gradle
  firebase-appdistribution-api/ktx/ktx.gradle
  firebase-common/gradle.properties
  firebase-common/ktx/ktx.gradle.kts
  firebase-components/gradle.properties
  firebase-config/bandwagoner/bandwagoner.gradle
  firebase-config/firebase-config.gradle
  firebase-config/ktx/ktx.gradle
  firebase-crashlytics-ndk/firebase-crashlytics-ndk.gradle
  firebase-crashlytics/firebase-crashlytics.gradle
  firebase-crashlytics/ktx/ktx.gradle
  firebase-database/firebase-database.gradle.kts
  firebase-database/ktx/ktx.gradle.kts
  firebase-dynamic-links/firebase-dynamic-links.gradle
  firebase-dynamic-links/ktx/ktx.gradle
  firebase-firestore/firebase-firestore.gradle
  firebase-firestore/ktx/ktx.gradle
  firebase-functions/firebase-functions.gradle.kts
  firebase-functions/ktx/ktx.gradle.kts
  firebase-inappmessaging-display/firebase-inappmessaging-display.gradle
  firebase-inappmessaging-display/ktx/ktx.gradle
  firebase-inappmessaging/firebase-inappmessaging.gradle
  firebase-inappmessaging/ktx/ktx.gradle
  firebase-installations/firebase-installations.gradle
  firebase-installations/ktx/ktx.gradle
  firebase-messaging/firebase-messaging.gradle
  firebase-messaging/ktx/ktx.gradle
  firebase-ml-modeldownloader/firebase-ml-modeldownloader.gradle
  firebase-ml-modeldownloader/ktx/ktx.gradle
  firebase-ml-modeldownloader/ml-data-collection-tests/ml-data-collection-tests.gradle
  firebase-perf/dev-app/dev-app.gradle
  firebase-perf/firebase-perf.gradle
  firebase-perf/ktx/ktx.gradle
  firebase-sessions/firebase-sessions.gradle.kts
  firebase-storage/firebase-storage.gradle
  firebase-storage/ktx/ktx.gradle
  integ-testing/integ-testing.gradle.kts
Labels: size/L

#5420 Wire datastore in to FirebaseLifecycleService
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionDatastore.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionLifecycleClient.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionLifecycleService.kt
Labels: size/M

#5217 Public sum/avg
  firebase-firestore/CHANGELOG.md
  firebase-firestore/api.txt
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/AggregationTest.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/AggregateField.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/AggregateQuery.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/AggregateQuerySnapshot.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/Query.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/Query.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/remote/Datastore.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/core/QueryTest.java
Labels: size/XL

#5395 Fix client-side throttling for Play Integrity flows
  appcheck/firebase-appcheck-playintegrity/CHANGELOG.md
  appcheck/firebase-appcheck/CHANGELOG.md
  appcheck/firebase-appcheck/src/main/java/com/google/firebase/appcheck/internal/DefaultFirebaseAppCheck.java
  appcheck/firebase-appcheck/src/main/java/com/google/firebase/appcheck/internal/NetworkClient.java
  appcheck/firebase-appcheck/src/main/java/com/google/firebase/appcheck/internal/RetryManager.java
  appcheck/firebase-appcheck/src/test/java/com/google/firebase/appcheck/internal/NetworkClientTest.java
  appcheck/firebase-appcheck/src/test/java/com/google/firebase/appcheck/internal/RetryManagerTest.java
Labels: size/M

#5422 Only support the default Firebase app
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/FirebaseSessions.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionFirelogPublisher.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionGenerator.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/settings/SessionsSettings.kt
Labels: size/M, no-changelog

#5427 Hooks up the SessionLifecycleService to the FirelogPublisher, and has…
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/FirebaseSessions.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/FirebaseSessionsRegistrar.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionEvents.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionFirelogPublisher.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionLifecycleService.kt
  firebase-sessions/src/test/kotlin/com/google/firebase/sessions/EventGDTLoggerTest.kt
  firebase-sessions/src/test/kotlin/com/google/firebase/sessions/SessionEventEncoderTest.kt
  firebase-sessions/src/test/kotlin/com/google/firebase/sessions/SessionEventTest.kt
  firebase-sessions/src/test/kotlin/com/google/firebase/sessions/SessionFirelogPublisherTest.kt
Labels: size/L

#5433 Update SessionDatastore.kt's name
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionDatastore.kt
Labels: size/XS

#5431 Updates the service to run on a looper on it's own thread and not use…
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionFirelogPublisher.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionLifecycleService.kt
Labels: size/S

#5432 User id fix
  firebase-crashlytics/CHANGELOG.md
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/CrashlyticsControllerTest.java
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/metadata/MetaDataStoreTest.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsController.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/metadata/UserMetadata.java
Labels: size/L

#5434 Refactors SessionLifecycleService to make the message handler static …
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionLifecycleService.kt
Labels: size/L

#5435 Bump Play Integrity API dependency.
  appcheck/firebase-appcheck-playintegrity/CHANGELOG.md
  appcheck/firebase-appcheck-playintegrity/firebase-appcheck-playintegrity.gradle
Labels: size/XS

#5436 Removes unecessary setup code from FirebaseSessions and SessionInitia…
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/Dispatchers.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/FirebaseSessions.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/FirebaseSessionsRegistrar.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionInitiator.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionLifecycleClient.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionLifecycleService.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionsActivityLifecycleCallbacks.kt
  firebase-sessions/src/test/kotlin/com/google/firebase/sessions/SessionInitiatorTest.kt
Labels: size/L

#5442 Replaces info level log messages with debug messages and adds a coupl…
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionFirelogPublisher.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionLifecycleClient.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionLifecycleService.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/api/FirebaseSessionsDependencies.kt
Labels: size/M

#5438 Update version numbers for M139 release.
  appcheck/firebase-appcheck-debug-testing/gradle.properties
  appcheck/firebase-appcheck-debug/gradle.properties
  appcheck/firebase-appcheck-interop/gradle.properties
  appcheck/firebase-appcheck-playintegrity/gradle.properties
  appcheck/firebase-appcheck/gradle.properties
Labels: size/S, no-changelog

#5443 Controls whether or not the sessions SDK hooks up any lifecycle callb…
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/FirebaseSessions.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/FirebaseSessionsRegistrar.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/settings/RemoteSettings.kt
Labels: size/M

#5450 Fix changelogs after M138 mergeback.
  appcheck/firebase-appcheck-debug-testing/CHANGELOG.md
  appcheck/firebase-appcheck-debug/CHANGELOG.md
Labels: size/XS

#5453 fix versions and dependencies for m139
  appcheck/firebase-appcheck/firebase-appcheck.gradle
  appcheck/firebase-appcheck/ktx/ktx.gradle
  firebase-appdistribution-api/gradle.properties
  firebase-appdistribution/gradle.properties
Labels: size/XS

#5421 Add composite index testing guidance to ReadMe
  .github/workflows/ci_tests.yml
  firebase-firestore/README.md
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/CompositeIndexQueryTest.java
Labels: size/M, no-changelog

#5452 Remove passthrough `register` method from `FirebaseSessions` since `F…
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/CrashlyticsRegistrar.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/FirebaseCrashlytics.java
  firebase-perf/src/main/java/com/google/firebase/perf/FirebasePerfEarly.java
  firebase-perf/src/main/java/com/google/firebase/perf/FirebasePerfRegistrar.java
  firebase-sessions/api.txt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/FirebaseSessions.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/api/FirebaseSessionsDependencies.kt
  firebase-sessions/test-app/src/androidTest/kotlin/com/google/firebase/testing/sessions/FirebaseSessionsTest.kt
Labels: size/M, no-changelog

#5451 Add sampling, data collection, and disabled checks to newSession
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionEvent.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionEvents.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionFirelogPublisher.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionLifecycleClient.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionLifecycleService.kt
  firebase-sessions/src/test/kotlin/com/google/firebase/sessions/SessionFirelogPublisherTest.kt
  firebase-sessions/test-app/test-app.gradle.kts
Labels: size/L, no-changelog

#5447 Looper on a different thread for the SessionLifecycleClient's callbacks
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionLifecycleClient.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionsActivityLifecycleCallbacks.kt
Labels: size/S, no-changelog

#5461 Moves SessionFirelogPublisher and SessionDatastore behind an interfac…
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/FirebaseSessions.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/FirebaseSessionsRegistrar.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionDatastore.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionFirelogPublisher.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionLifecycleClient.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionLifecycleService.kt
  firebase-sessions/src/test/kotlin/com/google/firebase/sessions/SessionFirelogPublisherTest.kt
Labels: size/L

#5463 Don't wrap sendLifecycleEvents twice
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionLifecycleClient.kt
Labels: size/S

#5464 Sessions fake registrar
  firebase-sessions/src/test/AndroidManifest.xml
  firebase-sessions/src/test/kotlin/com/google/firebase/sessions/testing/FakeFirelogPublisher.kt
  firebase-sessions/src/test/kotlin/com/google/firebase/sessions/testing/FakeSessionDatastore.kt
  firebase-sessions/src/test/kotlin/com/google/firebase/sessions/testing/FirebaseSessionsFakeRegistrar.kt
Labels: size/L

#5459 opt installations into m139
  firebase-installations-interop/CHANGELOG.md
  firebase-installations-interop/gradle.properties
Labels: size/XS

#5460 Project level dep on sessions
  firebase-crashlytics/CHANGELOG.md
  firebase-crashlytics/firebase-crashlytics.gradle
Labels: size/XS

#5468 Fixes issue where handler thread is started/stopped based on activity…
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionLifecycleClient.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionsActivityLifecycleCallbacks.kt
Labels: size/S

#5462 Update latestReleasedVersion on version bump
  appcheck/firebase-appcheck-debug-testing/gradle.properties
  appcheck/firebase-appcheck-debug/gradle.properties
  appcheck/firebase-appcheck-interop/gradle.properties
  appcheck/firebase-appcheck-playintegrity/gradle.properties
  appcheck/firebase-appcheck/gradle.properties
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/PostReleasePlugin.kt
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/VersionBumpTask.kt
  firebase-config/gradle.properties
  firebase-crashlytics-ndk/gradle.properties
  firebase-crashlytics/gradle.properties
  firebase-database/gradle.properties
  firebase-dynamic-links/gradle.properties
  firebase-firestore/gradle.properties
  firebase-functions/gradle.properties
  firebase-inappmessaging-display/gradle.properties
  firebase-inappmessaging/gradle.properties
  firebase-installations/gradle.properties
  firebase-messaging-directboot/gradle.properties
  firebase-messaging/gradle.properties
  firebase-ml-modeldownloader/gradle.properties
  firebase-perf/gradle.properties
  firebase-sessions/gradle.properties
  firebase-storage/gradle.properties
Labels: size/M, no-changelog

#5471 Fix sessions test app android test
  firebase-perf/firebase-perf.gradle
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/FirebaseSessions.kt
  firebase-sessions/test-app/src/androidTest/kotlin/com/google/firebase/testing/sessions/FirebaseSessionsTest.kt
  firebase-sessions/test-app/test-app.gradle.kts
Labels: size/M, no-changelog

#5469 Add common Firebase logging interface
  firebase-common/src/main/java/com/google/firebase/logger/Logger.kt
  firebase-common/src/main/java/com/google/firebase/logger/package-info.java
Labels: size/L, no-changelog, main-merge-ack

#5445 Add process details to Crashlytics events
  firebase-crashlytics/CHANGELOG.md
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/CommonUtilsTest.java
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/persistence/CrashlyticsReportPersistenceTest.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/ProcessDetailsProvider.kt
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CommonUtils.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsReportDataCapture.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/model/CrashlyticsReport.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/model/serialization/CrashlyticsReportJsonTransform.java
Labels: size/L, main-merge-ack

#5470 Move sum&avg composite index tests to compositeIndexQueryTest.java
  firebase-firestore/firestore_collection_group_index_config.tf
  firebase-firestore/firestore_composite_index_config.tf
  firebase-firestore/main.tf
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/AggregationTest.java
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/CompositeIndexQueryTest.java
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/testutil/CompositeIndexTestHelper.java
Labels: size/L, no-changelog

#5474 Make Logger a normal abstract class
  firebase-common/src/main/java/com/google/firebase/logger/Logger.kt
Labels: size/XS, no-changelog, main-merge-ack

#5465 Adds unit test for SessionLifecycleService using the fake registrar i…
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionLifecycleService.kt
  firebase-sessions/src/test/kotlin/com/google/firebase/sessions/SessionLifecycleServiceTest.kt
Labels: size/L

#5476 Fix tests and network exception in gradle task config
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/FirebaseLibraryPlugin.kt
  firebase-sessions/src/test/kotlin/com/google/firebase/sessions/testing/FirebaseSessionsFakeRegistrar.kt
Labels: size/XS

#5478 Convert CrashlyticsRemoteConfigListener from java to kotlin
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/CrashlyticsRemoteConfigListener.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/CrashlyticsRemoteConfigListener.kt
Labels: size/M

#5482 Keep track of pending foreground before settings fetched
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/FirebaseSessions.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionsActivityLifecycleCallbacks.kt
  firebase-sessions/src/test/kotlin/com/google/firebase/sessions/SessionsActivityLifecycleCallbacksTest.kt
Labels: size/L, no-changelog

#5454 Remove AQS based session ID dependency from Fireperf.
  firebase-perf/CHANGELOG.md
  firebase-perf/src/main/java/com/google/firebase/perf/FirebasePerfEarly.java
  firebase-perf/src/main/java/com/google/firebase/perf/FirebasePerfRegistrar.java
  firebase-perf/src/main/java/com/google/firebase/perf/session/SessionManager.java
  firebase-perf/src/test/java/com/google/firebase/perf/FirebasePerfRegistrarTest.java
  firebase-perf/src/test/java/com/google/firebase/perf/session/SessionManagerTest.java
Labels: size/L

#5485 Add support for productId in transport
  transport/transport-api/CHANGELOG.md
  transport/transport-api/gradle.properties
  transport/transport-api/src/main/java/com/google/android/datatransport/Event.java
  transport/transport-api/src/main/java/com/google/android/datatransport/ProductData.java
  transport/transport-backend-cct/CHANGELOG.md
  transport/transport-backend-cct/gradle.properties
  transport/transport-backend-cct/src/main/java/com/google/android/datatransport/cct/CctTransportBackend.java
  transport/transport-backend-cct/src/main/java/com/google/android/datatransport/cct/internal/ComplianceData.java
  transport/transport-backend-cct/src/main/java/com/google/android/datatransport/cct/internal/ExternalPRequestContext.java
  transport/transport-backend-cct/src/main/java/com/google/android/datatransport/cct/internal/ExternalPrivacyContext.java
  transport/transport-backend-cct/src/main/java/com/google/android/datatransport/cct/internal/LogEvent.java
  transport/transport-backend-cct/src/test/java/com/google/android/datatransport/cct/CctTransportBackendTest.java
  transport/transport-backend-cct/transport-backend-cct.gradle
  transport/transport-runtime/CHANGELOG.md
  transport/transport-runtime/gradle.properties
  transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/EventInternal.java
  transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/TransportRuntime.java
  transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/scheduling/persistence/SQLiteEventStore.java
  transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/scheduling/persistence/SchemaManager.java
  transport/transport-runtime/src/test/java/com/google/android/datatransport/runtime/TransportRuntimeTest.java
  transport/transport-runtime/src/test/java/com/google/android/datatransport/runtime/scheduling/persistence/SchemaManagerMigrationTest.java
  transport/transport-runtime/src/test/java/com/google/android/datatransport/runtime/scheduling/persistence/SchemaManagerTest.java
  transport/transport-runtime/src/test/java/com/google/android/datatransport/runtime/scheduling/persistence/StateSimulations.java
  transport/transport-runtime/transport-runtime.gradle
Labels: size/L

#5486 Bump firebase-datatransport dependencies
  firebase-datatransport/firebase-datatransport.gradle
Labels: size/XS

#5487 Don't use immutablemap in testing
  transport/transport-runtime/src/test/java/com/google/android/datatransport/runtime/scheduling/persistence/SchemaManagerMigrationTest.java
Labels: size/S

#5492 Explicitly only get details for this app's running processes
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/ProcessDetailsProvider.kt
Labels: size/M, no-changelog, main-merge-ack
