Repository firebase/firebase-android-sdk, pull requests merged in 2023-08, with the labels that each got.

#5216 update version for m134
  firebase-appdistribution-api/CHANGELOG.md
  firebase-appdistribution-api/gradle.properties
  firebase-appdistribution/CHANGELOG.md
  firebase-appdistribution/gradle.properties
  firebase-config/CHANGELOG.md
  firebase-config/gradle.properties
  firebase-crashlytics-ndk/CHANGELOG.md
  firebase-crashlytics-ndk/gradle.properties
  firebase-crashlytics/CHANGELOG.md
  firebase-crashlytics/gradle.properties
  firebase-firestore/CHANGELOG.md
  firebase-firestore/gradle.properties
  firebase-messaging-directboot/gradle.properties
  firebase-messaging/CHANGELOG.md
  firebase-messaging/gradle.properties
  firebase-perf/CHANGELOG.md
  firebase-perf/gradle.properties
Labels: size/M

#5215 Clean up documentation wording.
  firebase-messaging/src/main/java/com/google/firebase/messaging/FirebaseMessaging.java
Labels: size/XS, no-changelog

#5219 Fix comment in testDoesNotAutoCreateIndexesWhenIndexLookUpIsExpensive
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/SQLiteLocalStoreTest.java
Labels: size/XS, api: firestore, no-changelog, main-merge-ack

#5223 refactor the LG check into its own task, minor rewrite for kotlin con…
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/PublishingPlugin.kt
Labels: size/M

#5220 Simplify code and improve test coverage
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/ValidationTest.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/CompositeFilter.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/FieldFilter.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/Filter.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/Query.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/core/QueryTest.java
  firebase-firestore/src/testUtil/java/com/google/firebase/firestore/testutil/TestUtil.java
Labels: size/L

#5229 Mergeback for m135
  firebase-appdistribution-api/gradle.properties
  firebase-appdistribution/CHANGELOG.md
  firebase-appdistribution/gradle.properties
  firebase-inappmessaging-display/CHANGELOG.md
  firebase-inappmessaging-display/gradle.properties
  firebase-inappmessaging/CHANGELOG.md
  firebase-inappmessaging/gradle.properties
  firebase-installations/gradle.properties
  firebase-messaging-directboot/gradle.properties
  firebase-messaging/CHANGELOG.md
  firebase-messaging/gradle.properties
  firebase-ml-modeldownloader/CHANGELOG.md
  firebase-ml-modeldownloader/gradle.properties
  firebase-sessions/gradle.properties
Labels: size/M

#5241 Fix semver check
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/FirebaseLibraryPlugin.kt
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/GmavenHelper.kt
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/PublishingPlugin.kt
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/semver/GmavenCopier.kt
Labels: size/M

#5242 Update firebase-datatransport dependencies
  firebase-datatransport/firebase-datatransport.gradle
Labels: size/XS

#5202 Make sure the data collection state is reliable for App Quality Sessions library
  firebase-perf/CHANGELOG.md
  firebase-perf/src/main/java/com/google/firebase/perf/FirebasePerfEarly.java
  firebase-perf/src/main/java/com/google/firebase/perf/config/ConfigResolver.java
  firebase-perf/src/test/java/com/google/firebase/perf/config/ConfigResolverTest.java
Labels: size/M

#5246 Minor version bump firebase-datatransport since new classes are added
  firebase-datatransport/gradle.properties
Labels: no-changelog

#5238 Make Sessions resilient to the FirebaseApp instance being deleted
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/DataCollectionArbiter.java
  firebase-perf/src/main/java/com/google/firebase/perf/FirebasePerformanceInitializer.java
  firebase-sessions/CHANGELOG.md
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/FirebaseSessions.kt
Labels: size/M, main-merge-ack

#5244 Add Sessions dep version change to Crashlytics CHANGELOG file
  firebase-crashlytics/CHANGELOG.md
Labels: size/XS, main-merge-ack

#5248 remove FDL from firebase-tutorial-bundle
  buildSrc/src/main/java/com/google/firebase/gradle/bomgenerator/RecipeVersionWriter.java
Labels: size/S

#5245 [FIAM] Firelog to clearcut migration
  firebase-inappmessaging-display/CHANGELOG.md
  firebase-inappmessaging/CHANGELOG.md
  firebase-inappmessaging/firebase-inappmessaging.gradle
  firebase-inappmessaging/src/main/java/com/google/firebase/inappmessaging/FirebaseInAppMessagingRegistrar.java
Labels: size/S

#5251 Bump smoke-tests compileSdk to 33
  smoke-tests/build.gradle
Labels: size/XS

#5227 Update release commands in README files
  README.md
  buildSrc/README.md
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/PublishingPlugin.kt
  firebase-firestore/README.md
  firebase-perf/README.md
Labels: size/M, no-changelog

#5230 Add Firebase Remote Config Test App for Feature Rollouts
  firebase-config/test-app/.gitignore
  firebase-config/test-app/README.md
  firebase-config/test-app/src/androidTest/kotlin/com/google/firebase/testing/config/FirebaseConfigTest.kt
  firebase-config/test-app/src/main/AndroidManifest.xml
  firebase-config/test-app/src/main/kotlin/com/google/firebase/testing/config/MainActivity.kt
  firebase-config/test-app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  firebase-config/test-app/src/main/res/drawable/ic_launcher_background.xml
  firebase-config/test-app/src/main/res/drawable/sensor_window.xml
  firebase-config/test-app/src/main/res/layout/activity_main.xml
  firebase-config/test-app/src/main/res/values-night/themes.xml
  firebase-config/test-app/src/main/res/values/colors.xml
  firebase-config/test-app/src/main/res/values/strings.xml
  firebase-config/test-app/src/main/res/values/themes.xml
  firebase-config/test-app/test-app.gradle.kts
  subprojects.cfg
Labels: size/XL, no-changelog

#5213 Increase test coverage for persistent cache indexing
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/FirestoreTest.java
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/IndexingTest.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/QueryEngine.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/model/TargetIndexMatcher.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/SQLiteIndexManagerTest.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/SQLiteLocalStoreTest.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/model/TargetIndexMatcherTest.java
Labels: size/L, no-changelog

#5225 Enable gradle metadata publishing
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/FirebaseLibraryPlugin.kt
Labels: size/XS

#5262 Add a 40 second sleep at the end of each Fireperf e2e test to ensure that events are sent before the app exits.
  firebase-perf/e2e-app/src/androidTest/java/com/google/firebase/testing/fireperf/FirebasePerformanceFragmentScreenTracesTest.java
  firebase-perf/e2e-app/src/androidTest/java/com/google/firebase/testing/fireperf/FirebasePerformanceScreenTracesTest.java
  firebase-perf/e2e-app/src/androidTest/java/com/google/firebase/testing/fireperf/FirebasePerformanceTest.java
Labels: size/XS

#5257 Add GMaven Version test
  .github/workflows/version-check.yml
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/FirebaseJavaLibraryPlugin.kt
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/FirebaseLibraryPlugin.kt
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/GmavenHelper.kt
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/GmavenVersionChecker.kt
  firebase-messaging/gradle.properties
  transport/transport-backend-cct/gradle.properties
  transport/transport-runtime/gradle.properties
Labels: size/L, no-changelog

#5268 Fix missing throw Exception in test for Thread.sleep().
  firebase-perf/e2e-app/src/androidTest/java/com/google/firebase/testing/fireperf/FirebasePerformanceFragmentScreenTracesTest.java
  firebase-perf/e2e-app/src/androidTest/java/com/google/firebase/testing/fireperf/FirebasePerformanceScreenTracesTest.java
  firebase-perf/e2e-app/src/androidTest/java/com/google/firebase/testing/fireperf/FirebasePerformanceTest.java
Labels: size/S

#5252 Associate Rollouts with Fatal and non-fatals
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/SessionReportingCoordinatorTest.java
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/metadata/RolloutAssignmentListTest.java
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/model/serialization/CrashlyticsReportJsonTransformTest.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsController.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/FileBackedNativeSessionFile.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/SessionReportingCoordinator.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/metadata/MetaDataStore.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/metadata/RolloutAssignment.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/metadata/RolloutAssignmentList.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/metadata/UserMetadata.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/model/serialization/CrashlyticsReportJsonTransform.java
Labels: size/L

#5255 Initial commit of firebase-config-interop SDK.
  firebase-config-interop/.gitignore
  firebase-config-interop/api.txt
  firebase-config-interop/firebase-config-interop.gradle.kts
  firebase-config-interop/src/main/AndroidManifest.xml
  firebase-config-interop/src/main/java/com/google/firebase/remoteconfig/interop/FirebaseRemoteConfigInterop.java
  firebase-config-interop/src/main/java/com/google/firebase/remoteconfig/interop/rollouts/RolloutAssignment.java
  firebase-config-interop/src/main/java/com/google/firebase/remoteconfig/interop/rollouts/RolloutsState.java
  firebase-config-interop/src/main/java/com/google/firebase/remoteconfig/interop/rollouts/RolloutsStateSubscriber.java
  firebase-config-interop/src/test/java/com/google/firebase/remoteconfig/interop/rollouts/RolloutAssignmentTest.java
  subprojects.cfg
Labels: size/L, no-changelog

#5264 Add RC test app e2e config file
  .github/workflows/config-e2e.yml
Labels: size/M

#5270 Feature Rollouts RC Fetch Integration
  firebase-config/src/main/java/com/google/firebase/remoteconfig/RemoteConfigConstants.java
  firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigContainer.java
  firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigFetchHttpClient.java
  firebase-config/src/test/java/com/google/firebase/remoteconfig/FirebaseRemoteConfigTest.java
  firebase-config/src/test/java/com/google/firebase/remoteconfig/internal/ConfigContainerTest.java
  firebase-config/src/test/java/com/google/firebase/remoteconfig/internal/ConfigFetchHandlerTest.java
  firebase-config/src/test/java/com/google/firebase/remoteconfig/internal/ConfigFetchHttpClientTest.java
Labels: size/L

#5277 Add RC Interop to RC SDK with a stubbed implementation.
  firebase-config/firebase-config.gradle
  firebase-config/ktx/src/test/kotlin/com/google/firebase/remoteconfig/TestConstructorUtil.kt
  firebase-config/ktx/src/test/kotlin/com/google/firebase/remoteconfig/ktx/RemoteConfigTests.kt
  firebase-config/src/androidTest/java/com/google/firebase/remoteconfig/FirebaseRemoteConfigIntegrationTest.java
  firebase-config/src/main/java/com/google/firebase/remoteconfig/FirebaseRemoteConfig.java
  firebase-config/src/main/java/com/google/firebase/remoteconfig/RemoteConfigComponent.java
  firebase-config/src/main/java/com/google/firebase/remoteconfig/RemoteConfigRegistrar.java
  firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigMetadataClient.java
  firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/rollouts/RolloutsStateSubscriptionsHandler.java
  firebase-config/src/test/java/com/google/firebase/remoteconfig/FirebaseRemoteConfigTest.java
  firebase-config/src/test/java/com/google/firebase/remoteconfig/RemoteConfigComponentTest.java
  firebase-config/src/test/java/com/google/firebase/remoteconfig/internal/rollouts/RolloutsStateSubscriptionsHandlerTest.java
Labels: size/L, no-changelog

#5285 Mergeback for M136
  firebase-crashlytics-ndk/CHANGELOG.md
  firebase-crashlytics-ndk/gradle.properties
  firebase-crashlytics/CHANGELOG.md
  firebase-crashlytics/gradle.properties
  firebase-datatransport/CHANGELOG.md
  firebase-datatransport/gradle.properties
  firebase-firestore/CHANGELOG.md
  firebase-firestore/gradle.properties
  firebase-perf/CHANGELOG.md
  firebase-perf/gradle.properties
  firebase-sessions/CHANGELOG.md
  firebase-sessions/gradle.properties
Labels: size/M

#5274 Persist the aqs session id on new aqs session
  firebase-crashlytics/CHANGELOG.md
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/CrashlyticsAppQualitySessionsStoreTest.java
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/CrashlyticsAppQualitySessionsSubscriberTest.java
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/CrashlyticsControllerTest.java
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/persistence/CrashlyticsReportPersistenceTest.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/FirebaseCrashlytics.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsAppQualitySessionsStore.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsAppQualitySessionsSubscriber.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsController.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsCore.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/model/CrashlyticsReport.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/model/serialization/CrashlyticsReportJsonTransform.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/persistence/CrashlyticsReportPersistence.java
  firebase-crashlytics/src/test/java/com/google/firebase/crashlytics/internal/common/CrashlyticsControllerRobolectricTest.java
Labels: size/XL, main-merge-ack

#5286 Integrate interop with Crashlytics sdk
  firebase-crashlytics/firebase-crashlytics.gradle
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/CrashlyticsRemoteConfigListenerTest.java
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/RemoteConfigDeferredProxyTest.java
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/CrashlyticsCoreInitializationTest.java
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/CrashlyticsCoreTest.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/CrashlyticsRegistrar.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/FirebaseCrashlytics.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/CrashlyticsRemoteConfigListener.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/RemoteConfigDeferredProxy.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsCore.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/metadata/RolloutAssignment.java
Labels: size/L

#5289 Update FTL default device to pixel7 api 33
  README.md
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/ci/device/FirebaseTestLabExtension.java
  firebase-config/bandwagoner/bandwagoner.gradle
  firebase-crashlytics/firebase-crashlytics.gradle
  transport/transport-runtime/transport-runtime.gradle
Labels: size/S

#5256 Public Auto Persistent Index Creation API
  firebase-firestore/CHANGELOG.md
  firebase-firestore/api.txt
  firebase-firestore/src/main/java/com/google/firebase/firestore/FirebaseFirestore.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/PersistentCacheIndexManager.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/QueryEngine.java
Labels: size/S, api: firestore, main-merge-ack
