Repository firebase/firebase-android-sdk, pull requests merged in 2023-06, with the labels that each got.

#5028 Clean up how we launch suspend functions
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/FirebaseSessions.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionEvents.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionGenerator.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionInitiateListener.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionInitiator.kt
  firebase-sessions/src/test/kotlin/com/google/firebase/sessions/EventGDTLoggerTest.kt
  firebase-sessions/src/test/kotlin/com/google/firebase/sessions/SessionCoordinatorTest.kt
  firebase-sessions/src/test/kotlin/com/google/firebase/sessions/SessionEventEncoderTest.kt
  firebase-sessions/src/test/kotlin/com/google/firebase/sessions/SessionEventTest.kt
  firebase-sessions/src/test/kotlin/com/google/firebase/sessions/SessionGeneratorTest.kt
  firebase-sessions/src/test/kotlin/com/google/firebase/sessions/SessionInitiatorTest.kt
  firebase-sessions/src/test/kotlin/com/google/firebase/sessions/testing/TestSessionEventData.kt
Labels: no-changelog

#5045 Add and populate appQualitySessionId in Crashlytics reports
  firebase-crashlytics/ktx/ktx.gradle
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/CrashlyticsCoreInitializationTest.java
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/CrashlyticsCoreTest.java
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/persistence/CrashlyticsReportPersistenceTest.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/FirebaseCrashlytics.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsAppQualitySessionsSubscriber.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsCore.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/SessionReportingCoordinator.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/model/CrashlyticsReport.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/model/serialization/CrashlyticsReportJsonTransform.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/persistence/CrashlyticsReportPersistence.java
Labels: no-changelog

#5056 Pin perf dependency on firebase-datatransport
  firebase-perf/firebase-perf.gradle
Labels: no-changelog

#5063 Add comments and asserts that didn't merge with PR 5059
  firebase-perf/src/main/java/com/google/firebase/perf/config/ConfigurationConstants.java
  firebase-perf/src/test/java/com/google/firebase/perf/config/ConfigurationConstantsTest.java
Labels: no-changelog

#5070 Pin sessions datatransport dep
  firebase-sessions/firebase-sessions.gradle.kts
Labels: no-changelog

#5071 Make default sampling rates for when RC fetch failed 1/1000 typical
  firebase-perf/src/main/java/com/google/firebase/perf/config/ConfigurationConstants.java
  firebase-perf/src/main/java/com/google/firebase/perf/config/RemoteConfigManager.java
  firebase-perf/src/test/java/com/google/firebase/perf/config/ConfigResolverTest.java
  firebase-perf/src/test/java/com/google/firebase/perf/config/ConfigurationConstantsTest.java
Labels: no-changelog

#5074 Comment out failing messaging tests
  firebase-messaging/src/test/java/com/google/firebase/messaging/FirebaseMessagingRoboTest.java
Labels: no-changelog

#5060 Use AQS provided sessionId for Fireperf events.
  firebase-perf/src/main/java/com/google/firebase/perf/FirebasePerfEarly.java
  firebase-perf/src/main/java/com/google/firebase/perf/FirebasePerfRegistrar.java
  firebase-perf/src/main/java/com/google/firebase/perf/FirebasePerformance.java
  firebase-perf/src/main/java/com/google/firebase/perf/injection/modules/FirebasePerformanceModule.java
  firebase-perf/src/main/java/com/google/firebase/perf/session/PerfSession.java
  firebase-perf/src/main/java/com/google/firebase/perf/session/SessionManager.java
  firebase-perf/src/main/java/com/google/firebase/perf/transport/TransportManager.java
  firebase-perf/src/test/java/com/google/firebase/perf/FirebasePerfRegistrarTest.java
  firebase-perf/src/test/java/com/google/firebase/perf/FirebasePerformanceTest.java
  firebase-perf/src/test/java/com/google/firebase/perf/FirebasePerformanceTestBase.java
  firebase-perf/src/test/java/com/google/firebase/perf/application/AppStateMonitorTest.java
  firebase-perf/src/test/java/com/google/firebase/perf/metrics/AppStartTraceTest.java
  firebase-perf/src/test/java/com/google/firebase/perf/metrics/NetworkRequestMetricBuilderTest.java
  firebase-perf/src/test/java/com/google/firebase/perf/metrics/TraceTest.java
  firebase-perf/src/test/java/com/google/firebase/perf/session/PerfSessionTest.java
  firebase-perf/src/test/java/com/google/firebase/perf/session/SessionManagerTest.java
  firebase-perf/src/test/java/com/google/firebase/perf/transport/TransportManagerTest.java
  firebase-sessions/test-app/test-app.gradle.kts
Labels: no-changelog

#5068 Fix firebase-crashlytics-ktx instrumented tests
  firebase-crashlytics/ktx/ktx.gradle
  firebase-crashlytics/ktx/src/androidTest/AndroidManifest.xml
  firebase-crashlytics/ktx/src/androidTest/kotlin/com/google/firebase/crashlytics/ktx/CrashlyticsTests.kt
  firebase-crashlytics/ktx/src/main/kotlin/com/google/firebase/crashlytics/ktx/FirebaseCrashlytics.kt
  health-metrics/apk-size/app/default.gradle
Labels: size/L, no-changelog

#5061 Add check if Sessions is disabled
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/FirebaseSessions.kt
Labels: size/XS, no-changelog

#5052 Add fid to Crashlytics report
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/IdManagerTest.java
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/SessionReportingCoordinatorTest.java
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/settings/DefaultSettingsControllerTest.java
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/settings/DefaultSettingsSpiCallTest.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CLSUUID.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsController.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsReportDataCapture.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/IdManager.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/InstallIdProvider.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/SessionReportingCoordinator.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/model/CrashlyticsReport.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/settings/DefaultSettingsSpiCall.java
  firebase-crashlytics/src/test/java/com/google/firebase/crashlytics/internal/common/SessionReportingCoordinatorRobolectricTest.java
Labels: size/L, no-changelog

#5088 Firestore Spec Tests: Port JS PR 7372 (remove no-ios tag from bloom filter tests)
  firebase-firestore/src/test/resources/json/existence_filter_spec_test.json
  firebase-firestore/src/test/resources/json/limbo_spec_test.json
  firebase-firestore/src/test/resources/json/listen_spec_test.json
Labels: size/S, api: firestore, no-changelog, main-merge-ack

#5092 Handle IOExceptions when fetching remote settings
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/settings/RemoteSettings.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/settings/RemoteSettingsFetcher.kt
  firebase-sessions/src/test/kotlin/com/google/firebase/sessions/RemoteSettingsTest.kt
  firebase-sessions/src/test/kotlin/com/google/firebase/sessions/testing/FakeRemoteConfigFetcher.kt
  firebase-sessions/src/test/kotlin/com/google/firebase/sessions/testing/TestSessionEventData.kt
Labels: size/L, no-changelog

#5095 Make remote settings fetch non-blocking
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/FirebaseSessions.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/settings/RemoteSettings.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/settings/RemoteSettingsFetcher.kt
  firebase-sessions/src/test/kotlin/com/google/firebase/sessions/RemoteSettingsTest.kt
  firebase-sessions/src/test/kotlin/com/google/firebase/sessions/SessionsSettingsTest.kt
  firebase-sessions/src/test/kotlin/com/google/firebase/sessions/SettingsCacheTest.kt
  firebase-sessions/src/test/kotlin/com/google/firebase/sessions/api/FirebaseSessionsDependenciesTest.kt
Labels: size/L, no-changelog

#5077 Release generator improvements
  .github/workflows/create_releases.yml
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/PublishingPlugin.kt
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/ReleaseGenerator.kt
Labels: size/L

#5103 Ensure the settings cache has loaded from disk before reading any values
  firebase-sessions/firebase-sessions.gradle.kts
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/FirebaseSessions.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/settings/LocalOverrideSettings.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/settings/RemoteSettings.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/settings/SessionsSettings.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/settings/SettingsCache.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/settings/SettingsProvider.kt
  firebase-sessions/src/test/kotlin/com/google/firebase/sessions/EventGDTLoggerTest.kt
  firebase-sessions/src/test/kotlin/com/google/firebase/sessions/RemoteSettingsTest.kt
  firebase-sessions/src/test/kotlin/com/google/firebase/sessions/SessionCoordinatorTest.kt
  firebase-sessions/src/test/kotlin/com/google/firebase/sessions/SessionEventEncoderTest.kt
  firebase-sessions/src/test/kotlin/com/google/firebase/sessions/SessionEventTest.kt
  firebase-sessions/src/test/kotlin/com/google/firebase/sessions/SessionInitiatorTest.kt
  firebase-sessions/src/test/kotlin/com/google/firebase/sessions/SessionsSettingsTest.kt
  firebase-sessions/src/test/kotlin/com/google/firebase/sessions/settings/LocalOverrideSettingsTest.kt
  firebase-sessions/src/test/kotlin/com/google/firebase/sessions/settings/RemoteSettingsTest.kt
  firebase-sessions/src/test/kotlin/com/google/firebase/sessions/settings/SessionsSettingsTest.kt
  firebase-sessions/src/test/kotlin/com/google/firebase/sessions/settings/SettingsCacheTest.kt
  firebase-sessions/src/test/kotlin/com/google/firebase/sessions/testing/FakeSettingsProvider.kt
Labels: size/XXL, no-changelog

#5107 Fetch remote settings on session, not on launch
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/FirebaseSessions.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/settings/RemoteSettings.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/settings/SessionsSettings.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/settings/SettingsProvider.kt
  firebase-sessions/src/test/kotlin/com/google/firebase/sessions/api/FirebaseSessionsDependenciesTest.kt
  firebase-sessions/src/test/kotlin/com/google/firebase/sessions/settings/RemoteSettingsTest.kt
  firebase-sessions/src/test/kotlin/com/google/firebase/sessions/testing/FakeRemoteConfigFetcher.kt
Labels: size/L, no-changelog

#5093 Refactor real-time RC to use tasks for auth token requests
  firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigRealtimeHttpClient.java
  firebase-config/src/test/java/com/google/firebase/remoteconfig/FirebaseRemoteConfigTest.java
Labels: size/L

#5078 Do not require sign in to use developer mode
  firebase-appdistribution/CHANGELOG.md
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/DevModeDetector.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FeedbackActivity.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/NewReleaseFetcher.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/ReleaseIdentifier.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/SignInStorage.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/TesterSignInManager.java
  firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionServiceImplTest.java
  firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/NewReleaseFetcherTest.java
  firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/ReleaseIdentifierTest.java
  firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/TesterSignInManagerTest.java
Labels: size/L

#5112 Deprecate send.
  firebase-messaging/CHANGELOG.md
  firebase-messaging/src/main/java/com/google/firebase/messaging/FirebaseMessaging.java
Labels: size/XS

#5099 Making methods in core.Query that memoize results thread safe.
  firebase-firestore/CHANGELOG.md
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/Query.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/core/QueryTest.java
Labels: size/L

#5109 Bump Firebase Sessions version
  .github/workflows/sessions-e2e.yml
  firebase-sessions/gradle.properties
  firebase-sessions/src/test/kotlin/com/google/firebase/sessions/SessionEventEncoderTest.kt
Labels: size/XS, no-changelog, main-merge-ack

#5115 Have Perf report data collection disabled to Sessions
  firebase-perf/src/main/java/com/google/firebase/perf/FirebasePerfEarly.java
Labels: size/XS, no-changelog, main-merge-ack

#5111 Update App Distro API CHANGELOG.md
  firebase-appdistribution-api/CHANGELOG.md
Labels: size/XS

#5116 Update deprecated @VisibleForTesting annotation.
  firebase-messaging/src/main/java/com/google/firebase/messaging/FcmBroadcastProcessor.java
  firebase-messaging/src/main/java/com/google/firebase/messaging/SyncTask.java
Labels: size/XS

#5117 specify the bom dir as an output property of the BomGeneratorTask
  buildSrc/src/main/java/com/google/firebase/gradle/bomgenerator/BomGeneratorTask.java
  buildSrc/src/main/java/com/google/firebase/gradle/bomgenerator/PomXmlWriter.java
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/PublishingPlugin.kt
Labels: size/S

#5113 Add FID into real-time RC requests
  firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigRealtimeHttpClient.java
  firebase-config/src/test/java/com/google/firebase/remoteconfig/FirebaseRemoteConfigTest.java
Labels: size/L

#5124 Use spaces instead of tabs in protolite-well-known-types build file.
  protolite-well-known-types/protolite-well-known-types.gradle
Labels: size/XS, no-changelog

#5123 Add changelog for Crashlytics and Perf integrating with Sessions
  firebase-crashlytics/CHANGELOG.md
  firebase-perf/CHANGELOG.md
Labels: size/XS, main-merge-ack

#5125 Add initial Firebase sessions library changelog
  firebase-sessions/CHANGELOG.md
Labels: size/XS, main-merge-ack

#5126 Add changelog entry for Remote Config real-time request improvements.
  firebase-config/CHANGELOG.md
Labels: size/XS, main-merge-ack
