Repository firebase/firebase-android-sdk, pull requests merged in 2023-11, with the labels that each got.

#5497 Adds instrumentation tests to trigger crashes, non fatals and ANRs on…
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionLifecycleService.kt
  firebase-sessions/test-app/src/androidTest/kotlin/com/google/firebase/testing/sessions/FirebaseSessionsIntegrationTest.kt
  firebase-sessions/test-app/src/androidTest/kotlin/com/google/firebase/testing/sessions/FirebaseSessionsTest.kt
  firebase-sessions/test-app/src/main/AndroidManifest.xml
  firebase-sessions/test-app/src/main/kotlin/com/google/firebase/testing/sessions/FirstFragment.kt
  firebase-sessions/test-app/src/main/kotlin/com/google/firebase/testing/sessions/SecondActivity.kt
  firebase-sessions/test-app/src/main/kotlin/com/google/firebase/testing/sessions/TestApplication.kt
  firebase-sessions/test-app/src/main/res/layout/activity_second.xml
  firebase-sessions/test-app/src/main/res/layout/fragment_first.xml
  firebase-sessions/test-app/src/main/res/values/strings.xml
  firebase-sessions/test-app/test-app.gradle.kts
Labels: size/XL

#5507 Fix sessions test app build file
  firebase-sessions/test-app/test-app.gradle.kts
Labels: size/XS, no-changelog

#5508 Adds support for skipping tests that actually crash or ANR the test a…
  firebase-sessions/test-app/src/androidTest/kotlin/com/google/firebase/testing/sessions/FirebaseSessionsIntegrationTest.kt
  firebase-sessions/test-app/test-app.gradle.kts
Labels: size/S

#5509 Use the latest release bom in the sessions test app
  firebase-sessions/test-app/src/main/kotlin/com/google/firebase/testing/sessions/FirstFragment.kt
  firebase-sessions/test-app/src/main/kotlin/com/google/firebase/testing/sessions/SecondActivity.kt
  firebase-sessions/test-app/src/main/kotlin/com/google/firebase/testing/sessions/TestApplication.kt
  firebase-sessions/test-app/test-app.gradle.kts
Labels: size/M, no-changelog

#5515 Clean up a few things before merging
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/FirebaseLibraryPlugin.kt
  firebase-crashlytics/CHANGELOG.md
  firebase-sessions/CHANGELOG.md
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/EventGDTLogger.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/FirebaseSessions.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/FirebaseSessionsRegistrar.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionDatastore.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionFirelogPublisher.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionGenerator.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionLifecycleService.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionLifecycleServiceBinder.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/settings/RemoteSettings.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/settings/RemoteSettingsFetcher.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/settings/SessionsSettings.kt
Labels: size/M

#5501 Add process details to AQS event.
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/ProcessDetailsProvider.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionEvent.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionEvents.kt
  firebase-sessions/src/test/kotlin/com/google/firebase/sessions/EventGDTLoggerTest.kt
  firebase-sessions/src/test/kotlin/com/google/firebase/sessions/ProcessDetailsProviderTest.kt
  firebase-sessions/src/test/kotlin/com/google/firebase/sessions/SessionEventEncoderTest.kt
  firebase-sessions/src/test/kotlin/com/google/firebase/sessions/SessionEventTest.kt
  firebase-sessions/src/test/kotlin/com/google/firebase/sessions/testing/FakeFirebaseApp.kt
  firebase-sessions/src/test/kotlin/com/google/firebase/sessions/testing/TestSessionEventData.kt
Labels: size/L, no-changelog

#5516 Fix build
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionFirelogPublisher.kt
Labels: size/XS

#5494 Make data store pref configs multi-process safe
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/ProcessDetailsProvider.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionDataStoreConfigs.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionDatastore.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/settings/SessionsSettings.kt
  firebase-sessions/src/test/kotlin/com/google/firebase/sessions/settings/SessionsSettingsTest.kt
Labels: size/L, no-changelog

#5518 Remove process-details for now.
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionEvent.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionEvents.kt
  firebase-sessions/src/test/kotlin/com/google/firebase/sessions/SessionEventEncoderTest.kt
  firebase-sessions/src/test/kotlin/com/google/firebase/sessions/testing/TestSessionEventData.kt
Labels: size/M, no-changelog

#5523 fix unit tests
  firebase-config/src/test/java/com/google/firebase/remoteconfig/RemoteConfigTests.kt
  firebase-config/src/test/java/com/google/firebase/remoteconfig/TestConstructorUtil.kt
  firebase-config/src/test/java/com/google/firebase/remoteconfig/ktx/RemoteConfigTests.kt
Labels: size/S, no-changelog

#5524 Rollouts unit tests fix
  firebase-config/bandwagoner/bandwagoner.gradle
Labels: size/XS

#5520 Reintroduce process info in the AndroidAppInfo message. This is compatible with the backend.
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/ApplicationInfo.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/ProcessDetailsProvider.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionEvent.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionEvents.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/settings/SessionsSettings.kt
  firebase-sessions/src/test/kotlin/com/google/firebase/sessions/ApplicationInfoTest.kt
  firebase-sessions/src/test/kotlin/com/google/firebase/sessions/SessionEventEncoderTest.kt
  firebase-sessions/src/test/kotlin/com/google/firebase/sessions/testing/TestSessionEventData.kt
Labels: size/M, no-changelog

#5526 Set eagerInDefaultApp for Firebase Sessions
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/FirebaseSessionsRegistrar.kt
Labels: size/XS, no-changelog, main-merge-ack

#5527 Fixes broken fireperf unit test by preventing binding when no subscri…
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/FirebaseSessions.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionLifecycleClient.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionLifecycleService.kt
Labels: size/M

#5530 Add changelog entries for rollouts.
  firebase-config/CHANGELOG.md
  firebase-crashlytics/CHANGELOG.md
Labels: size/XS, api: rollouts

#5531 Bump Crashlytics, Remote Config, Sessions for next version to minor release.
  firebase-config/gradle.properties
  firebase-crashlytics/gradle.properties
  firebase-sessions/gradle.properties
Labels: size/XS, no-changelog, api: rollouts

#5529 Sessions test app run on min api level 16
  firebase-sessions/test-app/multidex-config.pro
  firebase-sessions/test-app/src/androidTest/AndroidManifest.xml
  firebase-sessions/test-app/src/main/kotlin/com/google/firebase/testing/sessions/TestApplication.kt
  firebase-sessions/test-app/src/main/res/values/strings.xml
  firebase-sessions/test-app/test-app.gradle.kts
Labels: size/M, no-changelog, main-merge-ack

#5528 update source code to maintain sync with google3
  encoders/firebase-encoders-processor/src/main/java/com/google/firebase/encoders/processor/EncodableProcessor.java
  encoders/firebase-encoders-processor/src/test/resources/ExpectedGenericsEncoder.java
  encoders/firebase-encoders-processor/src/test/resources/ExpectedGenericsEncoderWithUnknownType.java
  encoders/firebase-encoders-processor/src/test/resources/ExpectedMyClassEncoderWithExtraProperty.java
  encoders/firebase-encoders-processor/src/test/resources/ExpectedRecursiveGenericEncoder.java
  encoders/firebase-encoders-processor/src/test/resources/ExpectedSimpleClassEncoder.java
  encoders/firebase-encoders-processor/src/test/resources/ExpectedTypeWithListEncoder.java
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionGenerator.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionLifecycleClient.kt
Labels: size/S, no-changelog

#5533 Ignore transport changes from m140
  ignoreCommits.txt
Labels: size/XS

#5535 Bump transport versions
  firebase-datatransport/firebase-datatransport.gradle
  transport/transport-api/gradle.properties
  transport/transport-backend-cct/gradle.properties
  transport/transport-runtime/gradle.properties
Labels: size/S

#5539 Fix release config for config-interop
  firebase-config-interop/CHANGELOG.md
  firebase-config-interop/gradle.properties
Labels: size/XS

#5543 Create package-info.java for rollouts package.
  firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/rollouts/package-info.java
Labels: size/S, no-changelog, api: rollouts

#5536 Clean up some warnings in Sessions code
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/CrashlyticsRegistrar.java
  firebase-sessions/api.txt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/EventGDTLogger.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/FirebaseSessionsRegistrar.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionDataStoreConfigs.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionEvents.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionFirelogPublisher.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionLifecycleService.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/api/FirebaseSessionsDependencies.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/api/SessionSubscriber.kt
  firebase-sessions/src/test/kotlin/com/google/firebase/sessions/EventGDTLoggerTest.kt
  firebase-sessions/src/test/kotlin/com/google/firebase/sessions/SessionEventEncoderTest.kt
  firebase-sessions/src/test/kotlin/com/google/firebase/sessions/SessionEventTest.kt
Labels: size/M, no-changelog, main-merge-ack

#5550 Update FiresiteTransform
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/DackkaGenerationTask.kt
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/DackkaPlugin.kt
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/FiresiteTransformTask.kt
Labels: size/M, no-changelog

#5551 Add an internal identifier to Firelog logging for compliance.
  firebase-messaging/CHANGELOG.md
  firebase-messaging/firebase-messaging.gradle
  firebase-messaging/src/main/java/com/google/firebase/messaging/Constants.java
  firebase-messaging/src/main/java/com/google/firebase/messaging/MessagingAnalytics.java
  firebase-messaging/src/test/java/com/google/firebase/messaging/MessagingAnalyticsRoboTest.java
Labels: size/M

#5554 Update libs.versions.toml
  gradle/libs.versions.toml
Labels: size/XS

#5495 Bump gradle & agp version in apk-size test app
  health-metrics/apk-size/apk-size.gradle
  health-metrics/apk-size/app/src/main/AndroidManifest.xml
  health-metrics/apk-size/gradle/wrapper/gradle-wrapper.jar
  health-metrics/apk-size/gradle/wrapper/gradle-wrapper.properties
  health-metrics/apk-size/gradlew
  health-metrics/apk-size/gradlew.bat
Labels: size/M

#5548 Migrate firebase-config build config from Groovy to Kotlin.
  firebase-config/firebase-config.gradle
  firebase-config/firebase-config.gradle.kts
Labels: size/L, no-changelog

#5557 Update BomGeneratorTask.java to ignore config-interop
  buildSrc/src/main/java/com/google/firebase/gradle/bomgenerator/BomGeneratorTask.java
Labels: size/XS

#5558 Fix crashlytics copybara
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsCore.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsReportDataCapture.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/Utils.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/metadata/RolloutAssignmentList.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/metadata/UserMetadata.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/model/CrashlyticsReport.java
Labels: size/S, cla: yes

#5506 Fix docs unnecessarily undergo limbo resolution while resuming query bug
  firebase-firestore/CHANGELOG.md
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/SyncEngine.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/View.java
  firebase-firestore/src/test/resources/json/limbo_spec_test.json
  firebase-firestore/src/test/resources/json/limit_spec_test.json
Labels: size/L

#5570 Call messageHandled after a message has been handled.
  firebase-messaging/CHANGELOG.md
  firebase-messaging/src/main/java/com/google/firebase/messaging/FirebaseMessagingService.java
  firebase-messaging/src/test/java/com/google/firebase/messaging/FirebaseMessagingServiceRoboTest.java
Labels: size/M
