Repository firebase/firebase-android-sdk, pull requests merged in 2023-07, with the labels that each got.

#5132 Firestore: remove unused compareTo() computation
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/View.java
Labels: size/XS, api: firestore, no-changelog, main-merge-ack

#5133 Update semver tests and the pom validator tests to handle new sdk
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/FirebaseLibraryPlugin.kt
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/PomValidator.kt
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/semver/ApiDiffer.kt
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/semver/GmavenCopier.kt
  firebase-config/ktx/ktx.gradle
Labels: size/M

#5136 Remove Firebase Sessions from Javadoc
  firebase-sessions/firebase-sessions.gradle.kts
Labels: size/XS

#5139 Fix doc format for multi-db
  firebase-firestore/src/main/java/com/google/firebase/firestore/FirebaseFirestore.java
Labels: size/S

#5135 Firestore: add test bloomFilterShouldCorrectlyEncodeComplexUnicodeCharacters() to QueryTest.java
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/QueryTest.java
Labels: size/L, api: firestore, no-changelog, main-merge-ack

#5140 Change send deprecation link to hyperlinked text.
  firebase-messaging/src/main/java/com/google/firebase/messaging/FirebaseMessaging.java
Labels: size/XS, no-changelog

#5144 update version
  firebase-firestore/gradle.properties
Labels: size/XS

#5147 Add documentation to onMessageReceived on the time to handle a message.
  firebase-messaging/src/main/java/com/google/firebase/messaging/FirebaseMessagingService.java
Labels: size/XS, no-changelog

#5151 update versions
  firebase-crashlytics-ndk/gradle.properties
  firebase-crashlytics/gradle.properties
  firebase-perf/gradle.properties
Labels: size/XS

#5152 Update messaging versions
  firebase-messaging-directboot/gradle.properties
  firebase-messaging/gradle.properties
Labels: size/XS

#5142 Finish background FCM broadcasts after handling the message.
  firebase-messaging/CHANGELOG.md
  firebase-messaging/src/main/java/com/google/firebase/messaging/EnhancedIntentService.java
  firebase-messaging/src/main/java/com/google/firebase/messaging/FcmBroadcastProcessor.java
  firebase-messaging/src/main/java/com/google/firebase/messaging/WithinAppServiceConnection.java
  firebase-messaging/src/test/java/com/google/firebase/messaging/FcmBroadcastProcessorRoboTest.java
  firebase-messaging/src/test/java/com/google/firebase/messaging/WithinAppServiceConnectionRoboTest.java
Labels: size/L

#5155 Clean up documentation.
  firebase-messaging/src/main/java/com/google/firebase/messaging/FirebaseMessaging.java
Labels: size/S, no-changelog

#5160 update ignore artifacts
  buildSrc/src/main/java/com/google/firebase/gradle/bomgenerator/BomGeneratorTask.java
Labels: size/XS

#5127 Upgrade to agp 7.4.2
  buildSrc/build.gradle.kts
  firebase-firestore/firebase-firestore.gradle
Labels: size/M, no-changelog

#5145 Firestore: Update test bloomFilterShouldCorrectlyEncodeComplexUnicodeCharacters() in QueryTest.java
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/QueryTest.java
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/remote/TestingHooksUtil.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/remote/BloomFilter.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/remote/TestingHooks.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/remote/WatchChangeAggregator.java
Labels: size/L, api: firestore, no-changelog, main-merge-ack

#5163 Add missing list of valid backend values.
  firebase-firestore/firebase-firestore.gradle
Labels: size/XS, no-changelog

#5158 Clarify multi db documentation
  firebase-firestore/src/main/java/com/google/firebase/firestore/FirebaseFirestore.java
Labels: size/S, no-changelog

#5165 Connect PostReleasePlugin with PublishingPlugin
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/FirebaseLibraryPlugin.kt
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/GradleUtils.kt
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/PublishingPlugin.kt
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/VersionBumpTask.kt
Labels: size/M, no-changelog

#5167 Firestore: QueryTest.java: Use a WriteBatch to delete documents rather than a transaction
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/QueryTest.java
Labels: size/M, api: firestore, no-changelog, main-merge-ack

#5161 Fix return type of Builder.set
  firebase-firestore/api.txt
  firebase-firestore/src/main/java/com/google/firebase/firestore/MemoryEagerGcSettings.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/MemoryLruGcSettings.java
Labels: size/M

#5168 Firestore: Disable bloom filter integration tests when using Firestore emulator
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/QueryTest.java
Labels: size/M, api: firestore, no-changelog, main-merge-ack

#5175 Add minsdk version in manifest file commented
  firebase-installations-interop/src/main/AndroidManifest.xml
Labels: size/XS

#5178 Add third party license to aars
  firebase-appdistribution/CHANGELOG.md
  firebase-appdistribution/firebase-appdistribution.gradle
  firebase-ml-modeldownloader/CHANGELOG.md
  firebase-ml-modeldownloader/firebase-ml-modeldownloader.gradle
Labels: size/S

#5179 Update vendor plugin to use non-deprecated api
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/VendorPlugin.kt
  firebase-inappmessaging-display/CHANGELOG.md
  firebase-inappmessaging-display/firebase-inappmessaging-display.gradle
  firebase-inappmessaging/CHANGELOG.md
  firebase-inappmessaging/firebase-inappmessaging.gradle
  firebase-ml-modeldownloader/CHANGELOG.md
  firebase-ml-modeldownloader/firebase-ml-modeldownloader.gradle
  transport/transport-runtime/CHANGELOG.md
  transport/transport-runtime/transport-runtime.gradle
Labels: size/L

#5177 Firestore: Bloom filter minor code cleanup for consistency with web sdk
  firebase-firestore/src/main/java/com/google/firebase/firestore/remote/TestingHooks.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/remote/WatchChangeAggregator.java
Labels: size/S, api: firestore, no-changelog, main-merge-ack

#5169 Bump AXT dependencies to 1.5.0
  appcheck/firebase-appcheck-debug-testing/firebase-appcheck-debug-testing.gradle
  appcheck/firebase-appcheck-debug/firebase-appcheck-debug.gradle
  appcheck/firebase-appcheck-interop/firebase-appcheck-interop.gradle
  appcheck/firebase-appcheck-playintegrity/firebase-appcheck-playintegrity.gradle
  appcheck/firebase-appcheck-safetynet/firebase-appcheck-safetynet.gradle
  appcheck/firebase-appcheck/firebase-appcheck.gradle
  appcheck/firebase-appcheck/ktx/ktx.gradle
  build.gradle
  encoders/firebase-decoders-json/firebase-decoders-json.gradle
  encoders/firebase-encoders-json/firebase-encoders-json.gradle
  encoders/firebase-encoders-reflective/firebase-encoders-reflective.gradle
  firebase-appdistribution-api/firebase-appdistribution-api.gradle
  firebase-appdistribution-api/ktx/ktx.gradle
  firebase-appdistribution/firebase-appdistribution.gradle
  firebase-config/firebase-config.gradle
  firebase-config/ktx/ktx.gradle
  firebase-crashlytics-ndk/firebase-crashlytics-ndk.gradle
  firebase-crashlytics/firebase-crashlytics.gradle
  firebase-datatransport/firebase-datatransport.gradle
  firebase-dynamic-links/firebase-dynamic-links.gradle
  firebase-dynamic-links/ktx/ktx.gradle
  firebase-firestore/firebase-firestore.gradle
  firebase-firestore/ktx/ktx.gradle
  firebase-inappmessaging-display/firebase-inappmessaging-display.gradle
  firebase-inappmessaging-display/ktx/ktx.gradle
  firebase-inappmessaging/firebase-inappmessaging.gradle
  firebase-inappmessaging/ktx/ktx.gradle
  firebase-installations/firebase-installations.gradle
  firebase-installations/ktx/ktx.gradle
  firebase-messaging/firebase-messaging.gradle
  firebase-messaging/ktx/ktx.gradle
  firebase-ml-modeldownloader/firebase-ml-modeldownloader.gradle
  firebase-ml-modeldownloader/ktx/ktx.gradle
  firebase-ml-modeldownloader/ml-data-collection-tests/ml-data-collection-tests.gradle
  firebase-perf/e2e-app/e2e-app.gradle
  firebase-perf/firebase-perf.gradle
  firebase-perf/ktx/ktx.gradle
  firebase-segmentation/firebase-segmentation.gradle
  firebase-storage/firebase-storage.gradle
  firebase-storage/ktx/ktx.gradle
  gradle/libs.versions.toml
  health-metrics/benchmark/template/app/build.gradle.mustache
  health-metrics/benchmark/template/macrobenchmark/build.gradle
  smoke-tests/build.gradle
  transport/transport-backend-cct/transport-backend-cct.gradle
  transport/transport-runtime-testing/transport-runtime-testing.gradle
  transport/transport-runtime/transport-runtime.gradle
Labels: size/L

#5181 Implement a task for updating changelog files after a release
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/Changelog.kt
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/GradleUtils.kt
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/MakeReleaseNotesTask.kt
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/MoveUnreleasedChangesTask.kt
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/PostReleasePlugin.kt
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/SdkUtil.kt
  buildSrc/src/test/kotlin/com/google/firebase/gradle/plugins/MakeReleaseNotesTests.kt
  buildSrc/src/test/kotlin/com/google/firebase/gradle/plugins/MoveUnreleasedChangesTests.kt
  buildSrc/src/test/resources/BasicProject/build.gradle
  buildSrc/src/test/resources/BasicProject/firebase-storage/CHANGELOG.md
  buildSrc/src/test/resources/BasicProject/firebase-storage/build.gradle
  buildSrc/src/test/resources/BasicProject/firebase-storage/gradle.properties
  buildSrc/src/test/resources/BasicProject/settings.gradle
  buildSrc/src/test/resources/MakeReleaseNotes/release-notes.md
  buildSrc/src/test/resources/MoveUnreleasedChanges/basic.md
  buildSrc/src/test/resources/MoveUnreleasedChanges/release.json
  firebase-appdistribution-api/CHANGELOG.md
  firebase-appdistribution/CHANGELOG.md
  firebase-config/CHANGELOG.md
  firebase-crashlytics/CHANGELOG.md
  firebase-firestore/CHANGELOG.md
  firebase-messaging/CHANGELOG.md
  firebase-perf/CHANGELOG.md
Labels: size/XL, no-changelog

#5182 Update report to getRequired instead of deprecated alternative.
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/ci/Coverage.java
Labels: size/XS, no-changelog

#5183 Use actual version for androidx.core.test inside smoke-tests
  smoke-tests/build.gradle
Labels: size/XS, no-changelog

#5185 Make TestActivity exported for firebase-inappmessaging-display
  firebase-inappmessaging-display/src/androidTest/AndroidManifest.xml
Labels: size/XS

#5184 Firestore: QueryTest.java: use a different Firestore instance instead of a WriteBatch
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/QueryTest.java
Labels: size/S, api: firestore, no-changelog, main-merge-ack

#5187 Mitigation for issue 5024
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/settings/RemoteSettingsFetcher.kt
Labels: size/S

#5189 ci: Migrate set-output to GITHUB_OUTPUT
  .github/workflows/ci_tests.yml
  .github/workflows/update-cpp-sdk-on-release.yml
Labels: size/XS

#5193 Rename jobs to reflect what they do
  .github/workflows/check-head-dependencies.yml
  .github/workflows/semver-check.yml
Labels: size/XS, no-changelog

#5188 Add lint-base files for some sub-projects
  firebase-inappmessaging-display/firebase-inappmessaging-display.gradle
  firebase-inappmessaging-display/lint-baseline.xml
  firebase-ml-modeldownloader/firebase-ml-modeldownloader.gradle
  firebase-ml-modeldownloader/lint-baseline.xml
Labels: size/L

#5200 Add support to ignore specific commits from the release generator.
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/PublishingPlugin.kt
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/ReleaseGenerator.kt
Labels: size/S

#5201 Update checkout action to version 3.5.3
  .github/workflows/api-information.yml
  .github/workflows/build-release-artifacts.yml
  .github/workflows/build-src-check.yml
  .github/workflows/changelog.yml
  .github/workflows/check-head-dependencies.yml
  .github/workflows/ci_tests.yml
  .github/workflows/create_releases.yml
  .github/workflows/diff-javadoc.yml
  .github/workflows/fireci.yml
  .github/workflows/fireperf-e2e.yml
  .github/workflows/health-metrics.yml
  .github/workflows/jekyll-gh-pages.yml
  .github/workflows/make-bom.yml
  .github/workflows/private-mirror-sync.yml
  .github/workflows/release-note-changes.yml
  .github/workflows/scorecards.yml
  .github/workflows/semver-check.yml
  .github/workflows/sessions-e2e.yml
  .github/workflows/smoke-tests.yml
  .github/workflows/update-cpp-sdk-on-release.yml
  .github/workflows/validate-dependencies.yml
Labels: size/M

#4987 Add option to allow SDK create cache indexes automatically to improve query execution locally
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/IndexingTest.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/FirebaseFirestore.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/PersistentCacheIndexManager.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/FirestoreClient.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/IndexManager.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/LocalDocumentsView.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/LocalStore.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/MemoryIndexManager.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/MemoryRemoteDocumentCache.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/QueryContext.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/QueryEngine.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/RemoteDocumentCache.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteIndexManager.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteRemoteDocumentCache.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/model/TargetIndexMatcher.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/CountingQueryEngine.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/LocalStoreTestCase.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/SQLiteLocalStoreTest.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/model/TargetIndexMatcherTest.java
Labels: size/XL, no-changelog

#5198 Fix NPE when no version name is set
  firebase-sessions/CHANGELOG.md
  firebase-sessions/gradle.properties
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionEvents.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/settings/LocalOverrideSettings.kt
  firebase-sessions/src/test/kotlin/com/google/firebase/sessions/ApplicationInfoTest.kt
Labels: size/M, main-merge-ack

#5204 add new check in validateProjectsToPublishTask
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/PublishingPlugin.kt
Labels: size/S

#5207 Bump Auto Service Annotations version to match regex
  encoders/firebase-encoders-processor/firebase-encoders-processor.gradle
  firebase-ml-modeldownloader/firebase-ml-modeldownloader.gradle
Labels: size/XS

#5208 Ignore auto-service-annotations in pom validator
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/PomValidator.kt
Labels: size/XS

#5162 Support deleteAllIndexes in PersistentCacheIndexManager
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/IndexingTest.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/PersistentCacheIndexManager.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/FirestoreClient.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/IndexManager.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/LocalStore.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/MemoryIndexManager.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteIndexManager.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/LocalStoreTestCase.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/SQLiteLocalStoreTest.java
Labels: size/L, no-changelog

#5209 Rename variable to keep naming convention
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/FirestoreClient.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/LocalStore.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/QueryEngine.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/model/TargetIndexMatcher.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/CountingQueryEngine.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/LocalStoreTestCase.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/model/TargetIndexMatcherTest.java
Labels: size/S, no-changelog, main-merge-ack

#5205 Populate DataCollectionStatus for Crashlytics and Perf in Sessions
  firebase-sessions/CHANGELOG.md
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/FirebaseSessions.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionEvent.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionEvents.kt
  firebase-sessions/src/test/kotlin/com/google/firebase/sessions/SessionEventEncoderTest.kt
  firebase-sessions/src/test/kotlin/com/google/firebase/sessions/testing/TestSessionEventData.kt
Labels: size/M, main-merge-ack

#5210 Implement Filter equals method.
  firebase-firestore/CHANGELOG.md
  firebase-firestore/src/main/java/com/google/firebase/firestore/Filter.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/FilterTest.java
Labels: size/L

#5206 Setup CI for named db tests
  .github/workflows/ci_tests.yml
  firebase-firestore/firebase-firestore.gradle
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/BundleTest.java
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/CountTest.java
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/ValidationTest.java
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/testutil/IntegrationTestUtil.java
Labels: size/M
