Repository firebase/firebase-android-sdk, pull requests merged in 2023-09, with the labels that each got.

#5254 Finish PostReleasePlugin
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/BaseFirebaseLibraryPlugin.kt
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/KotlinUtils.kt
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/PostReleasePlugin.kt
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/UpdatePinnedDependenciesTask.kt
  buildSrc/src/test/kotlin/com/google/firebase/gradle/plugins/FirebaseTestController.kt
  buildSrc/src/test/kotlin/com/google/firebase/gradle/plugins/PublishingPluginTests.kt
  buildSrc/src/test/kotlin/com/google/firebase/gradle/plugins/UpdatePinnedDependenciesTests.kt
  buildSrc/src/test/kotlin/com/google/firebase/gradle/plugins/publishing.kt
Labels: size/XXL

#5150 Update target to SDK 33
  sdkProperties.gradle
Labels: size/XS

#5293 Fix Changelog Error
  firebase-firestore/CHANGELOG.md
Labels: size/XS

#5298 Improve auto cache index creation documentation readability
  firebase-firestore/CHANGELOG.md
  firebase-firestore/src/main/java/com/google/firebase/firestore/FirebaseFirestore.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/PersistentCacheIndexManager.java
Labels: size/S, main-merge-ack

#5299 Calculate total ram using MemoryInfo instead of `/proc/meminfo`
  firebase-crashlytics/CHANGELOG.md
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/CommonUtilsTest.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CommonUtils.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsController.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsReportDataCapture.java
Labels: size/L, main-merge-ack

#5283 Add Rollouts as a field to diff in Realtime RC
  firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigContainer.java
  firebase-config/src/test/java/com/google/firebase/remoteconfig/internal/ConfigContainerTest.java
Labels: size/L, do-not-merge/work-in-progress, api: rollouts

#5296 Integrate rollouts with on-demand fatals
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/metadata/MetaDataStoreTest.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/metadata/MetaDataStore.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/metadata/UserMetadata.java
Labels: size/M

#5300 Update component runtime to pick up any one of the couroutine dispatcher interface
  firebase-components/CHANGELOG.md
  firebase-components/src/main/java/com/google/firebase/components/ComponentRuntime.java
Labels: size/S

#5305 Update project level deps from M136
  firebase-crashlytics/firebase-crashlytics.gradle
  firebase-inappmessaging/firebase-inappmessaging.gradle
Labels: size/XS

#5306 Add missing changelog entry to firebase-crashlytics-ndk
  firebase-crashlytics-ndk/CHANGELOG.md
Labels: size/XS

#5309 Minor bump for firestore
  firebase-firestore/gradle.properties
Labels: size/XS

#5303 Add fetch and crash buttons to test app. Fix transitive deps.
  firebase-config/test-app/src/main/kotlin/com/google/firebase/testing/config/MainActivity.kt
  firebase-config/test-app/src/main/res/layout/activity_main.xml
  firebase-config/test-app/src/main/res/values/strings.xml
  firebase-config/test-app/test-app.gradle.kts
Labels: size/M, no-changelog, api: rollouts

#5308 Add test cases for existence filter with updated, removed, added documents
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/QueryTest.java
  firebase-firestore/src/test/resources/json/existence_filter_spec_test.json
Labels: size/XXL, no-changelog

#5315 adding more test cases
  firebase-config/test-app/.gitignore
  firebase-config/test-app/src/main/cpp/CMakeLists.txt
  firebase-config/test-app/src/main/cpp/config.cpp
  firebase-config/test-app/src/main/kotlin/com/google/firebase/crashlytics/OnDemandFatals.kt
  firebase-config/test-app/src/main/kotlin/com/google/firebase/testing/config/MainActivity.kt
  firebase-config/test-app/src/main/res/layout/activity_main.xml
  firebase-config/test-app/src/main/res/values/strings.xml
  firebase-config/test-app/test-app.gradle.kts
Labels: size/L

#5318 Reference ConfigContainer metadata for Rollouts constants.
  firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigContainer.java
  firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/rollouts/RolloutsStateFactory.java
  firebase-config/src/test/java/com/google/firebase/remoteconfig/internal/rollouts/RolloutsStateFactoryTest.java
Labels: size/S, no-changelog

#5327 Remove Remote Config reset call.
  firebase-config/test-app/src/main/kotlin/com/google/firebase/testing/config/MainActivity.kt
Labels: size/XS, no-changelog

#5297 Restructure library group logic in buildSrc
  build.gradle
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/FirebaseLibraryExtension.java
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/LibraryGroupRegistrar.kt
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/LibraryGroups.kt
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/PublishingPlugin.kt
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/ReleaseGenerator.kt
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/UpdatePinnedDependenciesTask.kt
  buildSrc/src/test/kotlin/com/google/firebase/gradle/plugins/UpdatePinnedDependenciesTests.kt
Labels: size/L, no-changelog

#5330 Update CHANGELOG entries according to CL review for m137
  firebase-crashlytics/CHANGELOG.md
  firebase-firestore/CHANGELOG.md
  firebase-inappmessaging-display/CHANGELOG.md
  firebase-inappmessaging/CHANGELOG.md
Labels: size/S

#5332 m137 mergeback
  firebase-components/gradle.properties
  firebase-crashlytics-ndk/CHANGELOG.md
  firebase-crashlytics-ndk/gradle.properties
  firebase-crashlytics/CHANGELOG.md
  firebase-crashlytics/gradle.properties
  firebase-firestore/CHANGELOG.md
  firebase-firestore/gradle.properties
  firebase-inappmessaging-display/CHANGELOG.md
  firebase-inappmessaging-display/gradle.properties
  firebase-inappmessaging/CHANGELOG.md
  firebase-inappmessaging/gradle.properties
Labels: size/M

#5337 Fix m137 release
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/FirebaseLibraryPlugin.kt
  firebase-crashlytics-ndk/CHANGELOG.md
  firebase-crashlytics/CHANGELOG.md
  firebase-firestore/CHANGELOG.md
  firebase-inappmessaging-display/CHANGELOG.md
  firebase-inappmessaging/CHANGELOG.md
Labels: size/S

#5312 firebase-perf: Add custom method to set final static method for test
  firebase-perf/src/test/java/com/google/firebase/perf/config/ConfigResolverTest.java
Labels: size/M

#5329 Use constants for library group task name
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/PublishingPlugin.kt
Labels: size/XS, no-changelog

#5342 m137_1 mergeback
  firebase-components/CHANGELOG.md
  firebase-components/gradle.properties
  firebase-crashlytics-ndk/CHANGELOG.md
  firebase-crashlytics-ndk/gradle.properties
  firebase-crashlytics/CHANGELOG.md
  firebase-crashlytics/gradle.properties
  firebase-firestore/CHANGELOG.md
  firebase-firestore/gradle.properties
  firebase-inappmessaging-display/CHANGELOG.md
  firebase-inappmessaging-display/gradle.properties
  firebase-inappmessaging/CHANGELOG.md
  firebase-inappmessaging/gradle.properties
Labels: size/M

#5331 Add deep transitive projects to release
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/PublishingPlugin.kt
  buildSrc/src/test/kotlin/com/google/firebase/gradle/plugins/PublishingPluginTests.kt
Labels: size/M

#5359 Add useReleasedVersions property to sessions e2e test app
  .github/workflows/sessions-e2e.yml
  firebase-sessions/test-app/src/main/AndroidManifest.xml
  firebase-sessions/test-app/test-app.gradle.kts
Labels: size/M, no-changelog, main-merge-ack

#5356 Create post release plugin workflow
  .github/workflows/post_release_cleanup.yml
Labels: size/M

#5317 Add ProcessDetails to sessions sdk
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/ProcessDetails.kt
  firebase-sessions/src/test/kotlin/com/google/firebase/sessions/testing/FakeProcessDetails.kt
Labels: size/M, no-changelog, main-merge-ack

#5360 Extract SessionMaintainer interface to allow for different types of S…
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/FirebaseSessions.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionMaintainer.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/api/FirebaseSessionsDependencies.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/leader/SessionMaintainerLeader.kt
Labels: size/L, no-changelog

#5366 Automatically add NO_RELEASE_CHANGE to mergeback
  .github/workflows/post_release_cleanup.yml
Labels: size/XS

#5369 Add importance to FakeFirebaseApp
  firebase-sessions/src/test/kotlin/com/google/firebase/sessions/testing/FakeFirebaseApp.kt
Labels: size/S, no-changelog

#5353 Fixed issue where Storage reported the wrong SDK version
  README.md
  firebase-storage/CHANGELOG.md
  firebase-storage/src/androidTest/java/com/google/firebase/storage/IntegrationTest.java
  firebase-storage/src/main/java/com/google/firebase/storage/network/NetworkRequest.java
  firebase-storage/src/test/java/com/google/firebase/storage/network/MockConnectionFactory.java
Labels: size/L

#5370 add common release notes
  firebase-common/CHANGELOG.md
  firebase-common/src/main/java/com/google/firebase/ktx/Firebase.kt
Labels: size/M

#5323 Fix documentation according to cl/563780077 feedback.
  firebase-firestore/src/main/java/com/google/firebase/firestore/FirebaseFirestore.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/PersistentCacheIndexManager.java
Labels: size/S, no-changelog
