Repository firebase/firebase-android-sdk, pull requests merged in 2023-03, with the labels that each got.

#4719 add check to diff pom files and see if any dependency is downgraded
  .github/workflows/validate-dependencies.yml
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/BaseFirebaseLibraryPlugin.kt
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/FirebaseJavaLibraryPlugin.kt
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/FirebaseLibraryPlugin.kt
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/GmavenHelper.kt
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/PomValidator.kt
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/publish/PublishingPlugin.java
Labels: size/L

#4734 Remove irrelevant exceptions and update tests
  firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigAutoFetch.java
  firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigRealtimeHttpClient.java
  firebase-config/src/test/java/com/google/firebase/remoteconfig/FirebaseRemoteConfigTest.java
Labels: size/M

#4733 Use kotlin.time.Duration instead of Long for time intervals
  firebase-sessions/firebase-sessions.gradle.kts
  firebase-sessions/src/androidTest/kotlin/com/google/firebase/sessions/FirebaseSessionsTests.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/FirebaseSessions.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionInitiator.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/WallClock.kt
  firebase-sessions/src/test/kotlin/com/google/firebase/sessions/SessionInitiatorTest.kt
Labels: size/L

#4742 update changelogs for release
  appcheck/firebase-appcheck-debug-testing/CHANGELOG.md
  appcheck/firebase-appcheck-debug/CHANGELOG.md
  appcheck/firebase-appcheck-playintegrity/CHANGELOG.md
  appcheck/firebase-appcheck-safetynet/CHANGELOG.md
  appcheck/firebase-appcheck/CHANGELOG.md
  firebase-appdistribution-api/CHANGELOG.md
  firebase-firestore/CHANGELOG.md
  firebase-inappmessaging-display/CHANGELOG.md
  firebase-inappmessaging/CHANGELOG.md
  firebase-installations/CHANGELOG.md
  firebase-messaging-directboot/CHANGELOG.md
  firebase-messaging/CHANGELOG.md
Labels: size/S

#4692 Make OR APIs public
  firebase-firestore/CHANGELOG.md
  firebase-firestore/api.txt
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/QueryTest.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/Filter.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/Query.java
Labels: size/L, main-merge-ack

#4533 updating target cache when there is a local change
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/LocalStore.java
Labels: size/S

#4739 Check Project level dependencies for release
  .github/workflows/check-head-dependencies.yml
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/CheckHeadDependencies.kt
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/GmavenHelper.kt
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/publish/PublishingPlugin.java
Labels: size/L

#4741 update versions post release
  appcheck/firebase-appcheck-debug-testing/gradle.properties
  appcheck/firebase-appcheck-debug/gradle.properties
  appcheck/firebase-appcheck-playintegrity/gradle.properties
  appcheck/firebase-appcheck-safetynet/gradle.properties
  appcheck/firebase-appcheck/gradle.properties
  firebase-common/gradle.properties
  firebase-firestore/gradle.properties
  firebase-inappmessaging-display/gradle.properties
  firebase-inappmessaging/gradle.properties
  firebase-installations/gradle.properties
  firebase-messaging-directboot/gradle.properties
  firebase-messaging/gradle.properties
Labels: size/M

#4747 Add SessionGenerator to generate the Session ID
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/FirebaseSessions.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionGenerator.kt
  firebase-sessions/src/test/kotlin/com/google/firebase/sessions/SessionGeneratorTest.kt
Labels: size/L, no-changelog

#4753 Update Realtime RC javadocs to align with iOS docs.
  firebase-config/src/main/java/com/google/firebase/remoteconfig/ConfigUpdateListener.java
  firebase-config/src/main/java/com/google/firebase/remoteconfig/ConfigUpdateListenerRegistration.java
  firebase-config/src/main/java/com/google/firebase/remoteconfig/FirebaseRemoteConfig.java
  firebase-config/src/main/java/com/google/firebase/remoteconfig/FirebaseRemoteConfigException.java
Labels: size/M, no-changelog

#4715 Fix StackOverflowError by deeply nested server-timestamps.
  firebase-firestore/CHANGELOG.md
  firebase-firestore/src/main/java/com/google/firebase/firestore/model/ServerTimestamps.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/SQLiteLocalStoreTest.java
Labels: size/M

#4761 Roll back PR#4715.
  firebase-firestore/CHANGELOG.md
  firebase-firestore/src/main/java/com/google/firebase/firestore/model/ServerTimestamps.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/SQLiteLocalStoreTest.java
Labels: size/M, main-merge-ack

#4721 Add support for GWP-ASan crashes
  firebase-crashlytics-ndk/firebase-crashlytics-ndk.gradle
  firebase-crashlytics-ndk/src/main/java/com/google/firebase/crashlytics/ndk/CrashpadController.java
  firebase-crashlytics-ndk/src/main/java/com/google/firebase/crashlytics/ndk/SessionFiles.java
  firebase-crashlytics-ndk/src/main/java/com/google/firebase/crashlytics/ndk/SessionFilesProvider.java
  firebase-crashlytics/firebase-crashlytics.gradle
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/CrashlyticsControllerTest.java
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/SessionReportingCoordinatorTest.java
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/persistence/CrashlyticsReportPersistenceTest.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/CrashlyticsNativeComponentDeferredProxy.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/NativeSessionFileProvider.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsController.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/SessionReportingCoordinator.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/model/CrashlyticsReport.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/model/serialization/CrashlyticsReportJsonTransform.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/persistence/CrashlyticsReportPersistence.java
Labels: size/L

#4743 Tool that calculate workflow/job failure rate and collect failure logs
  ci/workflow_summary/README.md
  ci/workflow_summary/collect_ci_test_logs.py
  ci/workflow_summary/github.py
  ci/workflow_summary/workflow_information.py
Labels: size/XL, main-merge-ack

#4697 Davidmotson.pin versions
  appcheck/firebase-appcheck-debug-testing/firebase-appcheck-debug-testing.gradle
  appcheck/firebase-appcheck-debug/firebase-appcheck-debug.gradle
  appcheck/firebase-appcheck-interop/firebase-appcheck-interop.gradle
  appcheck/firebase-appcheck-playintegrity/firebase-appcheck-playintegrity.gradle
  appcheck/firebase-appcheck-safetynet/firebase-appcheck-safetynet.gradle
  appcheck/firebase-appcheck/firebase-appcheck.gradle
  appcheck/firebase-appcheck/ktx/ktx.gradle
  encoders/firebase-encoders-json/firebase-encoders-json.gradle
  encoders/firebase-encoders-processor/firebase-encoders-processor.gradle
  encoders/firebase-encoders-proto/firebase-encoders-proto.gradle
  encoders/firebase-encoders-reflective/firebase-encoders-reflective.gradle
  firebase-abt/firebase-abt.gradle
  firebase-appdistribution-api/firebase-appdistribution-api.gradle
  firebase-appdistribution-api/ktx/ktx.gradle
  firebase-appdistribution/firebase-appdistribution.gradle
  firebase-common/data-collection-tests/data-collection-tests.gradle.kts
  firebase-common/firebase-common.gradle.kts
  firebase-common/ktx/ktx.gradle.kts
  firebase-components/firebase-components.gradle.kts
  firebase-components/firebase-dynamic-module-support/firebase-dynamic-module-support.gradle.kts
  firebase-config/bandwagoner/bandwagoner.gradle
  firebase-config/firebase-config.gradle
  firebase-config/ktx/ktx.gradle
  firebase-crashlytics-ndk/firebase-crashlytics-ndk.gradle
  firebase-crashlytics/firebase-crashlytics.gradle
  firebase-crashlytics/ktx/ktx.gradle
  firebase-database/firebase-database.gradle
  firebase-database/ktx/ktx.gradle
  firebase-datatransport/firebase-datatransport.gradle
  firebase-dynamic-links/firebase-dynamic-links.gradle
  firebase-dynamic-links/ktx/ktx.gradle
  firebase-firestore/firebase-firestore.gradle
  firebase-firestore/ktx/ktx.gradle
  firebase-functions/firebase-functions.gradle.kts
  firebase-functions/ktx/ktx.gradle.kts
  firebase-inappmessaging-display/firebase-inappmessaging-display.gradle
  firebase-inappmessaging-display/ktx/ktx.gradle
  firebase-inappmessaging/firebase-inappmessaging.gradle
  firebase-inappmessaging/ktx/ktx.gradle
  firebase-installations-interop/firebase-installations-interop.gradle
  firebase-installations/firebase-installations.gradle
  firebase-installations/ktx/ktx.gradle
  firebase-messaging/firebase-messaging.gradle
  firebase-messaging/ktx/ktx.gradle
  firebase-ml-modeldownloader/firebase-ml-modeldownloader.gradle
  firebase-ml-modeldownloader/ktx/ktx.gradle
  firebase-ml-modeldownloader/ml-data-collection-tests/ml-data-collection-tests.gradle
  firebase-perf/firebase-perf.gradle
  firebase-perf/ktx/ktx.gradle
  firebase-segmentation/firebase-segmentation.gradle
  firebase-storage/firebase-storage.gradle
  firebase-storage/ktx/ktx.gradle
  integ-testing/integ-testing.gradle
  protolite-well-known-types/README.md
  transport/transport-backend-cct/transport-backend-cct.gradle
  transport/transport-runtime-testing/transport-runtime-testing.gradle
  transport/transport-runtime/transport-runtime.gradle
Labels: size/L

#4767 Default template_version_number_key to 0 when it is not cached.
  firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigContainer.java
  firebase-config/src/test/java/com/google/firebase/remoteconfig/internal/ConfigContainerTest.java
Labels: size/S, no-changelog

#4770 Validate query purpose in spec tests
  firebase-firestore/src/test/java/com/google/firebase/firestore/spec/SpecTestCase.java
  firebase-firestore/src/test/resources/json/bundle_spec_test.json
  firebase-firestore/src/test/resources/json/existence_filter_spec_test.json
  firebase-firestore/src/test/resources/json/limbo_spec_test.json
  firebase-firestore/src/test/resources/json/limit_spec_test.json
  firebase-firestore/src/test/resources/json/recovery_spec_test.json
Labels: size/L

#4769 Add NumberedEnum interface
  encoders/firebase-encoders-json/firebase-encoders-json.gradle
  encoders/firebase-encoders-json/src/main/java/com/google/firebase/encoders/json/JsonValueObjectEncoderContext.java
  encoders/firebase-encoders-json/src/main/java/com/google/firebase/encoders/json/NumberedEnum.kt
  encoders/firebase-encoders-json/src/test/java/com/google/firebase/encoders/json/DummyEnum.kt
  encoders/firebase-encoders-json/src/test/java/com/google/firebase/encoders/json/JsonValueObjectEncoderContextTest.java
Labels: size/M, main-merge-ack

#4763 Add SessionEvent data class
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/FirebaseSessions.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionEvent.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionGenerator.kt
  firebase-sessions/src/test/kotlin/com/google/firebase/sessions/SessionEventTest.kt
  firebase-sessions/src/test/kotlin/com/google/firebase/sessions/SessionGeneratorTest.kt
Labels: size/L, no-changelog

#4776 Make NumberedEnum public, not internal
  encoders/firebase-encoders-json/src/main/java/com/google/firebase/encoders/json/NumberedEnum.kt
Labels: size/XS, no-changelog, main-merge-ack

#4758 A simple refactor on LocalStore.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/LocalStore.java
Labels: size/S, main-merge-ack

#4773 Add changelog entry for real-time updates.
  firebase-config/CHANGELOG.md
Labels: size/XS

#4779 Correct hyphenation for real-time.
  firebase-config/src/main/java/com/google/firebase/remoteconfig/ConfigUpdateListener.java
  firebase-config/src/main/java/com/google/firebase/remoteconfig/ConfigUpdateListenerRegistration.java
  firebase-config/src/main/java/com/google/firebase/remoteconfig/FirebaseRemoteConfig.java
  firebase-config/src/main/java/com/google/firebase/remoteconfig/FirebaseRemoteConfigException.java
  firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigRealtimeHttpClient.java
Labels: size/M, no-changelog

#4772 Ignore invalidations and stop listening when there are no listeners.
  firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigAutoFetch.java
Labels: size/S, no-changelog

#3944 Add Realtime RC to firebase-config.
  firebase-config/CHANGELOG.md
  firebase-config/api.txt
  firebase-config/firebase-config.gradle
  firebase-config/ktx/src/test/kotlin/com/google/firebase/remoteconfig/TestConstructorUtil.kt
  firebase-config/ktx/src/test/kotlin/com/google/firebase/remoteconfig/ktx/RemoteConfigTests.kt
  firebase-config/src/androidTest/java/com/google/firebase/remoteconfig/FirebaseRemoteConfigIntegrationTest.java
  firebase-config/src/main/java/com/google/firebase/remoteconfig/ConfigUpdate.java
  firebase-config/src/main/java/com/google/firebase/remoteconfig/ConfigUpdateListener.java
  firebase-config/src/main/java/com/google/firebase/remoteconfig/ConfigUpdateListenerRegistration.java
  firebase-config/src/main/java/com/google/firebase/remoteconfig/FirebaseRemoteConfig.java
  firebase-config/src/main/java/com/google/firebase/remoteconfig/FirebaseRemoteConfigClientException.java
  firebase-config/src/main/java/com/google/firebase/remoteconfig/FirebaseRemoteConfigException.java
  firebase-config/src/main/java/com/google/firebase/remoteconfig/FirebaseRemoteConfigServerException.java
  firebase-config/src/main/java/com/google/firebase/remoteconfig/RemoteConfigComponent.java
  firebase-config/src/main/java/com/google/firebase/remoteconfig/RemoteConfigConstants.java
  firebase-config/src/main/java/com/google/firebase/remoteconfig/RemoteConfigRegistrar.java
  firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigAutoFetch.java
  firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigContainer.java
  firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigFetchHandler.java
  firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigFetchHttpClient.java
  firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigMetadataClient.java
  firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigRealtimeHandler.java
  firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigRealtimeHttpClient.java
  firebase-config/src/test/java/com/google/firebase/remoteconfig/FirebaseRemoteConfigTest.java
  firebase-config/src/test/java/com/google/firebase/remoteconfig/RemoteConfigComponentTest.java
  firebase-config/src/test/java/com/google/firebase/remoteconfig/internal/ConfigContainerTest.java
  firebase-config/src/test/java/com/google/firebase/remoteconfig/internal/ConfigFetchHandlerTest.java
  firebase-config/src/test/java/com/google/firebase/remoteconfig/internal/ConfigFetchHttpClientTest.java
  firebase-config/src/test/java/com/google/firebase/remoteconfig/internal/ConfigMetadataClientTest.java
Labels: size/XXL

#4775 Add Firebase Sessions Test App
  firebase-sessions/test-app/.gitignore
  firebase-sessions/test-app/src/main/AndroidManifest.xml
  firebase-sessions/test-app/src/main/kotlin/com/google/firebase/testing/sessions/MainActivity.kt
  firebase-sessions/test-app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  firebase-sessions/test-app/src/main/res/drawable/ic_launcher_background.xml
  firebase-sessions/test-app/src/main/res/drawable/sensor_window.xml
  firebase-sessions/test-app/src/main/res/layout/activity_main.xml
  firebase-sessions/test-app/src/main/res/values-night/themes.xml
  firebase-sessions/test-app/src/main/res/values/colors.xml
  firebase-sessions/test-app/src/main/res/values/strings.xml
  firebase-sessions/test-app/src/main/res/values/themes.xml
  firebase-sessions/test-app/test-app.gradle.kts
  subprojects.cfg
Labels: size/XL, no-changelog

#4780 Update the missing build id message
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsCore.java
Labels: size/XS, no-changelog, main-merge-ack

#4765 Temp fix for Release Artifact generation
  .github/workflows/build-release-artifacts.yml
Labels: size/XS, no-changelog, main-merge-ack

#4781 Make more app distro deps static
  firebase-appdistribution/firebase-appdistribution.gradle
  firebase-appdistribution/test-app/test-app.gradle
Labels: size/XS, main-merge-ack

#4778 Add JSON encoder for SessionEvents
  firebase-sessions/firebase-sessions.gradle.kts
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/FirebaseSessions.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionEvent.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionEvents.kt
  firebase-sessions/src/test/kotlin/com/google/firebase/sessions/SessionEventEncoderTest.kt
  firebase-sessions/src/test/kotlin/com/google/firebase/sessions/SessionEventTest.kt
Labels: size/L, no-changelog

#4784 Merge fad/next into master to prepare for next release
  firebase-appdistribution-api/src/main/java/com/google/firebase/appdistribution/FirebaseAppDistribution.java
  firebase-appdistribution/CHANGELOG.md
  firebase-appdistribution/gradle.properties
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/AppDistroComponent.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FeedbackActivity.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FeedbackSender.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionImpl.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionTesterApiClient.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/TesterApiHttpClient.java
  firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/FeedbackSenderTest.java
  firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionTesterApiClientTest.java
  firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/TesterApiHttpClientTest.java
Labels: size/XL, main-merge-ack

#4786 Only attempt to flush reports for start up crashes
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/send/ReportQueue.java
Labels: size/S, no-changelog, main-merge-ack

#4789 Update next firebase-config version to 21.3.0
  firebase-config/gradle.properties
Labels: size/XS, no-changelog, main-merge-ack

#4777 Add new goog-listen-tag for bloom filter
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/SyncEngine.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/LocalStore.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/QueryPurpose.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/remote/RemoteEvent.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/remote/RemoteSerializer.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/remote/RemoteStore.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/remote/WatchChangeAggregator.java
  firebase-firestore/src/test/resources/json/bundle_spec_test.json
  firebase-firestore/src/test/resources/json/existence_filter_spec_test.json
  firebase-firestore/src/test/resources/json/limbo_spec_test.json
  firebase-firestore/src/test/resources/json/limit_spec_test.json
  firebase-firestore/src/test/resources/json/offline_spec_test.json
  firebase-firestore/src/test/resources/json/recovery_spec_test.json
Labels: size/XL, no-changelog

#4768 Update the integration test to verify that bloom filter averted full requery
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/QueryTest.java
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/remote/WatchChangeAggregatorTestingHooksAccessor.java
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/testutil/IntegrationTestUtil.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/remote/WatchChangeAggregator.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/remote/WatchChangeAggregatorTestingHooks.java
Labels: size/XL, api: firestore

#4795 Update app-distribution-api gradle.properties and CHANGELOG
  firebase-appdistribution-api/CHANGELOG.md
  firebase-appdistribution-api/gradle.properties
Labels: size/XS, main-merge-ack

#4785 Use the private setter pattern on SessionGenerator.currentSession
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionGenerator.kt
  firebase-sessions/src/test/kotlin/com/google/firebase/sessions/SessionGeneratorTest.kt
Labels: size/L, no-changelog

#4792 Ensure Java 11 is used in macos runners
  .github/workflows/build-release-artifacts.yml
  .github/workflows/diff-javadoc.yml
Labels: size/XS, main-merge-ack

#4796 Integrate with FirebaseInstallations.
  firebase-sessions/firebase-sessions.gradle.kts
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/FirebaseSessions.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/FirebaseSessionsRegistrar.kt
Labels: size/S, no-changelog

#4793 Ignore non-firebase libraries from release configuration
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/publish/PublishingPlugin.java
Labels: size/S, main-merge-ack

#4771 Fix StackOverflowError by deeply nested server-timestamps.
  firebase-firestore/CHANGELOG.md
  firebase-firestore/src/main/java/com/google/firebase/firestore/model/ServerTimestamps.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/SQLiteLocalStoreTest.java
Labels: size/M, main-merge-ack

#4799 Firestore: QueryTest.java: add a test that resumes a query with existence filter
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/QueryTest.java
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/testutil/IntegrationTestUtil.java
Labels: size/M, api: firestore, no-changelog, main-merge-ack

#4801 Populate firebaseInstallationId field in session
  firebase-sessions/firebase-sessions.gradle.kts
  firebase-sessions/src/androidTest/kotlin/com/google/firebase/sessions/FirebaseSessionsTests.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/FirebaseSessions.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/FirebaseSessionsRegistrar.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionCoordinator.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionEvent.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionEvents.kt
  firebase-sessions/src/test/kotlin/com/google/firebase/sessions/SessionCoordinatorTest.kt
  firebase-sessions/src/test/kotlin/com/google/firebase/sessions/SessionEventEncoderTest.kt
  firebase-sessions/src/test/kotlin/com/google/firebase/sessions/testing/FakeFirebaseInstallations.kt
Labels: size/L, no-changelog

#4807 pin these for M129
  firebase-appdistribution/firebase-appdistribution.gradle
  firebase-crashlytics/firebase-crashlytics.gradle
Labels: size/XS

#4808 Improve real-time reference docs.
  firebase-config/src/main/java/com/google/firebase/remoteconfig/ConfigUpdate.java
  firebase-config/src/main/java/com/google/firebase/remoteconfig/ConfigUpdateListener.java
  firebase-config/src/main/java/com/google/firebase/remoteconfig/FirebaseRemoteConfig.java
  firebase-config/src/main/java/com/google/firebase/remoteconfig/FirebaseRemoteConfigClientException.java
  firebase-config/src/main/java/com/google/firebase/remoteconfig/FirebaseRemoteConfigServerException.java
Labels: size/M, no-changelog, main-merge-ack

#4809 Add GWP-ASan blurb to changelog
  firebase-crashlytics/CHANGELOG.md
Labels: size/XS, main-merge-ack

#4810 Change "user" to "tester" in app distro javadocs
  firebase-appdistribution-api/src/main/java/com/google/firebase/appdistribution/FirebaseAppDistribution.java
Labels: size/XS

#4811 fix log
  firebase-crashlytics/CHANGELOG.md
Labels: size/XS

#4814 Use >API30 for crashlytics ndk device testing
  firebase-crashlytics-ndk/firebase-crashlytics-ndk.gradle
Labels: size/XS, no-changelog, main-merge-ack

#4813 Firestore: QueryTest.java: improve the test that resumes a query with existence filter to actually validate the existence filter.
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/QueryTest.java
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/remote/ExistenceFilterMismatchListener.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/remote/TestingHooks.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/remote/WatchChangeAggregator.java
Labels: size/L, api: firestore, no-changelog, main-merge-ack

#4819 Update functions engine for testing.
  firebase-functions/src/androidTest/backend/functions/package.json
Labels: size/XS, no-changelog, main-merge-ack

#4812 Remove a call to UAST inline function
  tools/lint/src/main/kotlin/ProviderAssignmentDetector.kt
Labels: size/XS, no-changelog, main-merge-ack

#4816 Migrate Database to KTS + VC
  firebase-database-collection/firebase-database-collection.gradle
  firebase-database-collection/firebase-database-collection.gradle.kts
  firebase-database/firebase-database.gradle
  firebase-database/firebase-database.gradle.kts
  firebase-database/ktx/ktx.gradle
  firebase-database/ktx/ktx.gradle.kts
  firebase-database/src/androidTest/java/com/google/firebase/database/IntegrationTestValues.java
  gradle/libs.versions.toml
Labels: size/L, no-changelog, main-merge-ack

#4828 Improve bloom filter application test coverage
  firebase-firestore/src/main/java/com/google/firebase/firestore/remote/RemoteSerializer.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/LocalSerializerTest.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/remote/RemoteEventTest.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/remote/RemoteSerializerTest.java
  firebase-firestore/src/testUtil/java/com/google/firebase/firestore/testutil/TestTargetMetadataProvider.java
Labels: size/L

#4833 Remove Javadoc + Fireescape artifacts from releasing jars
  .github/workflows/build-release-artifacts.yml
  .github/workflows/check-head-dependencies.yml
  .github/workflows/validate-dependencies.yml
  buildSrc/src/main/java/com/google/firebase/gradle/MultiProjectReleasePlugin.java
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/FireEscapeArtifactPlugin.kt
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/JavadocPlugin.java
Labels: size/L, no-changelog, main-merge-ack
