Repository firebase/firebase-android-sdk, pull requests merged in 2023-02, with the labels that each got.

#4308 Persist Realtime RC backoffs
  firebase-config/src/main/java/com/google/firebase/remoteconfig/RemoteConfigComponent.java
  firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigMetadataClient.java
  firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigRealtimeHandler.java
  firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigRealtimeHttpClient.java
  firebase-config/src/test/java/com/google/firebase/remoteconfig/FirebaseRemoteConfigTest.java
  firebase-config/src/test/java/com/google/firebase/remoteconfig/RemoteConfigComponentTest.java
  firebase-config/src/test/java/com/google/firebase/remoteconfig/internal/ConfigMetadataClientTest.java
Labels: size/L

#4621 Fix typo in FirebaseAppDistributionNotificationManager
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionNotificationsManager.java
Labels: size/XS

#4620 Make FetchType header capitalized to match backend
  firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigFetchHandler.java
Labels: size/XS

#4629 Add change log entry missing from previous commit
  firebase-crashlytics/CHANGELOG.md
Labels: size/XS, main-merge-ack

#4622 Revert "Migrate vendor plugin to new transform api. (#4424)"
  appcheck/firebase-appcheck/ktx/src/androidTest/AndroidManifest.xml
  buildSrc/build.gradle.kts
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/FirebaseLibraryPlugin.java
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/VendorPlugin.kt
  buildSrc/src/test/kotlin/com/google/firebase/gradle/plugins/VendorTests.kt
  firebase-appdistribution-api/ktx/src/androidTest/AndroidManifest.xml
  firebase-crashlytics-ndk/firebase-crashlytics-ndk.gradle
  firebase-crashlytics/ktx/src/androidTest/AndroidManifest.xml
  firebase-firestore/firebase-firestore.gradle
  firebase-firestore/src/androidTest/AndroidManifest.xml
  firebase-functions/ktx/src/androidTest/AndroidManifest.xml
  firebase-functions/src/androidTest/AndroidManifest.xml
  firebase-inappmessaging/src/androidTest/AndroidManifest.xml
  firebase-installations/src/androidTest/AndroidManifest.xml
  firebase-messaging/src/androidTest/AndroidManifest.xml
  transport/transport-runtime/transport-runtime.gradle
Labels: size/XL, main-merge-ack

#4623 Implement the GitSubmodulePlugin
  buildSrc/src/main/java/com/google/firebase/gradle/bomgenerator/tagging/ShellExecutor.java
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/FirebaseLibraryPlugin.java
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/GitSubmodulePlugin.kt
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/GradleUtils.kt
Labels: size/L, no-changelog, main-merge-ack

#4631 Pass feedback trigger type to create feedback call
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FeedbackActivity.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FeedbackSender.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FeedbackTrigger.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionImpl.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionTesterApiClient.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/TakeScreenshotAndStartFeedbackActivity.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/TesterApiHttpClient.java
  firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/FeedbackSenderTest.java
  firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionServiceImplTest.java
  firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionTesterApiClientTest.java
Labels: size/L

#4632 Pass trigger header on commit feedback call
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FeedbackSender.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionTesterApiClient.java
  firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/FeedbackSenderTest.java
  firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionTesterApiClientTest.java
Labels: size/M

#4630 disable device test on blueline-28 for transport-runtime
  transport/transport-runtime/transport-runtime.gradle
Labels: size/XS, main-merge-ack

#4601 Apply bloom filter on existence filter mismatch
  firebase-firestore/src/main/java/com/google/firebase/firestore/remote/BloomFilter.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/remote/BloomFilterException.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/remote/ExistenceFilter.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/remote/RemoteSerializer.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/remote/RemoteStore.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/remote/WatchChangeAggregator.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/remote/BloomFilterTest.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/spec/SpecTestCase.java
  firebase-firestore/src/test/resources/json/existence_filter_spec_test.json
  firebase-firestore/src/test/resources/json/limbo_spec_test.json
  firebase-firestore/src/test/resources/json/limit_spec_test.json
  firebase-firestore/src/testUtil/java/com/google/firebase/firestore/testutil/TestTargetMetadataProvider.java
  firebase-firestore/src/testUtil/java/com/google/firebase/firestore/testutil/TestUtil.java
Labels: size/XXL

#4640 release notes for #4514
  firebase-installations/CHANGELOG.md
Labels: size/XS, main-merge-ack

#4670 Commented out flaky tests for Storage
  firebase-storage/src/test/java/com/google/firebase/storage/UploadTest.java
Labels: size/L, main-merge-ack

#4635 Add missing parameter.
  firebase-storage/src/testUtil/java/com/google/firebase/storage/TestUploadHelper.java
Labels: size/XS, main-merge-ack

#4603 Bump google-services from 4.3.3 to 4.3.15
  build.gradle
Labels: size/XS, main-merge-ack

#4672 Store feedback trigger state on screen rotation
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FeedbackActivity.java
Labels: size/XS

#4588 Updating grpc version to 1.52.1
  build.gradle
  encoders/firebase-encoders-proto/firebase-encoders-proto.gradle
  firebase-ml-modeldownloader/firebase-ml-modeldownloader.gradle
  firebase-ml-modeldownloader/src/androidTest/java/com/google/firebase/ml/modeldownloader/TestGetModelLocal.java
  gradle/libs.versions.toml
  transport/transport-backend-cct/transport-backend-cct.gradle
Labels: size/S, main-merge-ack

#4634 Fix firebase-storage UploadTest flakes
  firebase-storage/src/test/java/com/google/firebase/storage/UploadTest.java
  firebase-storage/src/testUtil/java/com/google/firebase/storage/ControllableSchedulerHelper.java
Labels: size/M, no-changelog, main-merge-ack

#4677 Add proto for Sum and Avg
  firebase-firestore/src/proto/google/firestore/v1/query.proto
Labels: size/M, no-changelog, main-merge-ack

#4678 Update module versions to align with gmaven
  appcheck/firebase-appcheck-debug-testing/gradle.properties
  appcheck/firebase-appcheck-debug/gradle.properties
  appcheck/firebase-appcheck-interop/gradle.properties
  appcheck/firebase-appcheck-playintegrity/gradle.properties
  appcheck/firebase-appcheck-safetynet/gradle.properties
  appcheck/firebase-appcheck/gradle.properties
  firebase-abt/gradle.properties
  firebase-annotations/gradle.properties
  firebase-common/gradle.properties
  firebase-components/gradle.properties
  firebase-config/gradle.properties
  firebase-crashlytics-ndk/gradle.properties
  firebase-crashlytics/gradle.properties
  firebase-firestore/gradle.properties
  firebase-functions/gradle.properties
  firebase-inappmessaging-display/gradle.properties
  firebase-inappmessaging/gradle.properties
  firebase-installations/gradle.properties
  firebase-messaging-directboot/gradle.properties
  firebase-messaging/gradle.properties
  firebase-ml-modeldownloader/gradle.properties
  firebase-perf/gradle.properties
Labels: size/M, no-changelog, main-merge-ack

#4676 Change coverage check to only warning on unit test failures
  ci/fireci/fireciplugins/coverage.py
Labels: size/XS, main-merge-ack

#4675 Changes from API review
  firebase-appdistribution-api/src/main/java/com/google/firebase/appdistribution/FirebaseAppDistribution.java
  firebase-appdistribution-api/src/main/java/com/google/firebase/appdistribution/internal/FirebaseAppDistributionProxy.java
  firebase-appdistribution-api/src/main/java/com/google/firebase/appdistribution/internal/FirebaseAppDistributionStub.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FeedbackActivity.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionImpl.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionNotificationsManager.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/ScreenshotTaker.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/TakeScreenshotAndStartFeedbackActivity.java
  firebase-appdistribution/src/main/res/layout/activity_feedback.xml
  firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionNotificationsManagerTest.java
  firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionServiceImplTest.java
  firebase-appdistribution/test-app/src/main/kotlin/com/googletest/firebase/appdistribution/testapp/CustomNotificationFeedbackTrigger.kt
  firebase-appdistribution/test-app/src/main/kotlin/com/googletest/firebase/appdistribution/testapp/MainActivity.kt
  firebase-appdistribution/test-app/src/main/kotlin/com/googletest/firebase/appdistribution/testapp/ScreenshotDetectionActivity.kt
  firebase-appdistribution/test-app/src/main/kotlin/com/googletest/firebase/appdistribution/testapp/ScreenshotDetectionFeedbackTrigger.kt
  firebase-appdistribution/test-app/src/main/kotlin/com/googletest/firebase/appdistribution/testapp/SecondActivity.kt
  firebase-appdistribution/test-app/src/main/kotlin/com/googletest/firebase/appdistribution/testapp/ShakeDetectionFeedbackTrigger.kt
  firebase-appdistribution/test-app/src/main/res/values/strings.xml
Labels: size/L

#4231 Remove some query restrictions and add integration tests
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/QueryTest.java
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/ValidationTest.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/Query.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/Query.java
Labels: size/L, main-merge-ack

#4686 Add deprecation tagging to `SafetyNetAppCheckProviderFactory`.
  appcheck/firebase-appcheck-debug-testing/CHANGELOG.md
  appcheck/firebase-appcheck-debug/CHANGELOG.md
  appcheck/firebase-appcheck-playintegrity/CHANGELOG.md
  appcheck/firebase-appcheck-safetynet/CHANGELOG.md
  appcheck/firebase-appcheck-safetynet/src/main/java/com/google/firebase/appcheck/safetynet/SafetyNetAppCheckProviderFactory.java
  appcheck/firebase-appcheck/CHANGELOG.md
Labels: size/S, main-merge-ack

#4688 update versions and merge back changelog from release
  firebase-crashlytics-ndk/CHANGELOG.md
  firebase-crashlytics-ndk/gradle.properties
  firebase-crashlytics/CHANGELOG.md
  firebase-crashlytics/gradle.properties
  firebase-installations/CHANGELOG.md
  firebase-installations/gradle.properties
Labels: size/S

#4646 Fix related to BigLargeIcon to be set using an Icon
  firebase-messaging/CHANGELOG.md
  firebase-messaging/src/main/java/com/google/firebase/messaging/DisplayNotification.java
Labels: size/XS

#4685 Reduce default timeout on main thread by 1 second to avoid ANRs.
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsCore.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/Utils.java
Labels: size/M, main-merge-ack

#4627 Converty library plugins to kotlin
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/BaseFirebaseLibraryPlugin.kt
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/FirebaseJavaLibraryPlugin.java
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/FirebaseJavaLibraryPlugin.kt
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/FirebaseLibraryPlugin.java
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/FirebaseLibraryPlugin.kt
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/GradleUtils.kt
Labels: size/XL

#4691 Fiam crash fix
  firebase-inappmessaging-display/src/main/java/com/google/firebase/inappmessaging/display/FirebaseInAppMessagingDisplay.java
Labels: size/XS, main-merge-ack

#4694 Update heartbeat to have the most recent useragent for a given day
  firebase-common/src/main/java/com/google/firebase/heartbeatinfo/HeartBeatInfoStorage.java
  firebase-common/src/test/java/com/google/firebase/heartbeatinfo/HeartBeatInfoStorageTest.java
Labels: size/M

#4704 Updating changelog for FIAM
  firebase-inappmessaging-display/CHANGELOG.md
  firebase-inappmessaging/CHANGELOG.md
Labels: size/XS, main-merge-ack

#4706 Update changelog entries
  appcheck/firebase-appcheck/CHANGELOG.md
  firebase-abt/CHANGELOG.md
  firebase-config/CHANGELOG.md
  firebase-crashlytics-ndk/CHANGELOG.md
  firebase-crashlytics/CHANGELOG.md
  firebase-firestore/CHANGELOG.md
  firebase-functions/CHANGELOG.md
  firebase-inappmessaging-display/CHANGELOG.md
  firebase-inappmessaging/CHANGELOG.md
  firebase-ml-modeldownloader/CHANGELOG.md
  firebase-perf/CHANGELOG.md
Labels: size/L, main-merge-ack

#4709 Rl.fixrel
  firebase-appdistribution-api/gradle.properties
  firebase-appdistribution/gradle.properties
  firebase-crashlytics-ndk/CHANGELOG.md
  firebase-firestore/CHANGELOG.md
  firebase-messaging/CHANGELOG.md
  firebase-ml-modeldownloader/CHANGELOG.md
  firebase-perf/CHANGELOG.md
Labels: size/S, main-merge-ack

#4713 Initial commit for Firebase Sessions SDK
  firebase-sessions/api.txt
  firebase-sessions/firebase-sessions.gradle.kts
  firebase-sessions/gradle.properties
  firebase-sessions/src/androidTest/kotlin/com/google/firebase/sessions/FirebaseSessionsTests.kt
  firebase-sessions/src/main/AndroidManifest.xml
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/FirebaseSessions.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/FirebaseSessionsRegistrar.kt
  firebase-sessions/src/test/kotlin/com/google/firebase/sessions/FirebaseSessionsTest.kt
  subprojects.cfg
Labels: size/L

#4695 Return Server produced error if Http status code is 403
  firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigRealtimeHttpClient.java
  firebase-config/src/test/java/com/google/firebase/remoteconfig/FirebaseRemoteConfigTest.java
Labels: size/M

#4714 Update DackkaPlugin to use 1.2.0
  .github/workflows/diff-javadoc.yml
  appcheck/firebase-appcheck-debug-testing/src/main/java/com/google/firebase/appcheck/debug/testing/DebugAppCheckTestHelper.java
  appcheck/firebase-appcheck-debug/src/main/java/com/google/firebase/appcheck/debug/DebugAppCheckProviderFactory.java
  appcheck/firebase-appcheck-interop/api.txt
  appcheck/firebase-appcheck-interop/src/main/java/com/google/firebase/appcheck/interop/InternalAppCheckTokenProvider.java
  appcheck/firebase-appcheck-playintegrity/src/main/java/com/google/firebase/appcheck/playintegrity/PlayIntegrityAppCheckProviderFactory.java
  appcheck/firebase-appcheck-safetynet/src/main/java/com/google/firebase/appcheck/safetynet/SafetyNetAppCheckProviderFactory.java
  appcheck/firebase-appcheck/src/main/java/com/google/firebase/appcheck/AppCheckProvider.java
  buildSrc/firesite_transform.sh
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/DackkaGenerationTask.kt
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/DackkaPlugin.kt
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/FirebaseJavaLibraryPlugin.kt
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/FirebaseLibraryExtension.java
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/FiresiteTransformTask.kt
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/GradleUtils.kt
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/ProjectUtils.kt
  firebase-annotations/CHANGELOG.md
  firebase-annotations/api.txt
  firebase-annotations/src/main/java/com/google/firebase/annotations/concurrent/Blocking.java
  firebase-annotations/src/main/java/com/google/firebase/annotations/concurrent/Lightweight.java
  firebase-annotations/src/main/java/com/google/firebase/annotations/concurrent/UiThread.java
  firebase-appdistribution-api/src/main/java/com/google/firebase/appdistribution/FirebaseAppDistributionException.java
  firebase-common/src/main/java/com/google/firebase/FirebaseApp.java
  firebase-common/src/main/java/com/google/firebase/FirebaseOptions.java
  firebase-common/src/main/java/com/google/firebase/provider/FirebaseInitProvider.java
  firebase-config/src/main/java/com/google/firebase/remoteconfig/FirebaseRemoteConfig.java
  firebase-database/src/main/java/com/google/firebase/database/DataSnapshot.java
  firebase-database/src/main/java/com/google/firebase/database/FirebaseDatabase.java
  firebase-database/src/main/java/com/google/firebase/database/MutableData.java
  firebase-database/src/main/java/com/google/firebase/database/Transaction.java
  firebase-dynamic-links/src/main/java/com/google/firebase/dynamiclinks/FirebaseDynamicLinks.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/DocumentId.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/DocumentReference.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/QuerySnapshot.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/TransactionOptions.java
  firebase-inappmessaging/src/main/java/com/google/firebase/inappmessaging/internal/injection/modules/ExecutorsModule.java
  firebase-messaging/src/main/java/com/google/firebase/messaging/Constants.java
  firebase-messaging/src/main/java/com/google/firebase/messaging/FirebaseMessaging.java
  firebase-perf/src/main/java/com/google/firebase/perf/application/AppStateUpdateHandler.java
  firebase-storage/src/main/java/com/google/firebase/storage/ListResult.java
  firebase-storage/src/main/java/com/google/firebase/storage/StorageReference.java
  kotlindoc/package-lists/android/package-list
  kotlindoc/package-lists/androidx/package-list
Labels: size/XXL, no-changelog, main-merge-ack

#4696 Add integration test for bloom filter
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/QueryTest.java
Labels: size/M, no-changelog

#4459 Limited concurrency/pausable executors
  firebase-common/src/main/java/com/google/firebase/concurrent/ExecutorsRegistrar.java
  firebase-common/src/main/java/com/google/firebase/concurrent/FirebaseExecutors.java
  firebase-common/src/main/java/com/google/firebase/concurrent/LimitedConcurrencyExecutor.java
  firebase-common/src/main/java/com/google/firebase/concurrent/LimitedConcurrencyExecutorService.java
  firebase-common/src/main/java/com/google/firebase/concurrent/PausableExecutor.java
  firebase-common/src/main/java/com/google/firebase/concurrent/PausableExecutorImpl.java
  firebase-common/src/main/java/com/google/firebase/concurrent/PausableExecutorService.java
  firebase-common/src/main/java/com/google/firebase/concurrent/PausableExecutorServiceImpl.java
  firebase-common/src/main/java/com/google/firebase/concurrent/PausableScheduledExecutorService.java
  firebase-common/src/main/java/com/google/firebase/concurrent/PausableScheduledExecutorServiceImpl.java
  firebase-common/src/test/java/com/google/firebase/concurrent/LimitedConcurrencyExecutorTests.java
  firebase-common/src/test/java/com/google/firebase/concurrent/PausableExecutorImplTests.java
  firebase-common/src/test/java/com/google/firebase/concurrent/TestExecutor.java
Labels: size/XL

#4723 Implement SessionInitiator and hook it up to lifecycle events
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/FirebaseSessions.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/FirebaseSessionsRegistrar.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionInitiator.kt
  firebase-sessions/src/test/kotlin/com/google/firebase/sessions/FirebaseSessionsTest.kt
  firebase-sessions/src/test/kotlin/com/google/firebase/sessions/SessionInitiatorTest.kt
Labels: size/L
