Repository firebase/firebase-android-sdk, pull requests merged in 2023-01, with the labels that each got.

#4502 Fix apiInformation check not warning of added methods/fields/classes
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/Metalava.kt
  firebase-annotations/api.txt
  firebase-messaging/api.txt
  firebase-storage/api.txt
Labels: size/S, no-changelog

#4503 Update changelog versions in messaging.
  firebase-messaging/CHANGELOG.md
Labels: size/XS

#4493 Make isTesterSignedIn more reliable
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionImpl.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/SignInStorage.java
  firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionServiceImplTest.java
Labels: size/L

#4484 Release Generator Rebuilt PR
  .github/workflows/create_releases.yml
  buildSrc/build.gradle.kts
  buildSrc/src/main/java/com/google/firebase/gradle/MultiProjectReleasePlugin.java
  buildSrc/src/main/java/com/google/firebase/gradle/ReleaseGenerator.kt
Labels: size/L

#4486 Remove synchronized blocks from ApkInstaller
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/ApkInstaller.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionRegistrar.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/TaskCompletionSourceCache.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/TaskUtils.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/UpdateTaskImpl.java
  firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/ApkInstallerTests.java
  firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionServiceImplTest.java
Labels: size/L

#4509 Remove synchronized usage in TaskCache
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionImpl.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/TaskCache.java
Labels: size/M

#4518 Improve readability of a test in ApkUpdaterTest
  firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/ApkUpdaterTest.java
  firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionServiceImplTest.java
  firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/TestUtils.java
Labels: size/L

#4492 Added api for removing dismiss listener.
  firebase-inappmessaging/CHANGELOG.md
  firebase-inappmessaging/api.txt
  firebase-inappmessaging/gradle.properties
  firebase-inappmessaging/src/androidTest/java/com/google/firebase/inappmessaging/FirebaseInAppMessagingFlowableTest.java
  firebase-inappmessaging/src/main/java/com/google/firebase/inappmessaging/FirebaseInAppMessaging.java
  firebase-inappmessaging/src/main/java/com/google/firebase/inappmessaging/internal/DeveloperListenerManager.java
  firebase-inappmessaging/src/test/java/com/google/firebase/inappmessaging/FirebaseInAppMessagingTest.java
Labels: size/L

#4519 Some improvements to the task caches
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/TaskCompletionSourceCache.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/UpdateTaskCache.java
Labels: size/L

#4523 Support multiple progress listeners on an UpdateTask
  firebase-appdistribution/CHANGELOG.md
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/UpdateTaskImpl.java
  firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/UpdateTaskImplTest.java
Labels: size/L

#4525 add past branch checkout
  .github/workflows/create_releases.yml
Labels: size/XS

#4528 Some final synchronized block cleanup
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/AabUpdater.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionImpl.java
Labels: size/XS

#4529 De-flake some tests by waiting for UpdateTasks to complete
  firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/AabUpdaterTest.java
  firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionLifecycleNotifierTest.java
  firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/TestUtils.java
  firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/TesterSignInManagerTest.java
Labels: size/M

#4526 Focus some synchronized blocks in lifecycle notifier
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionLifecycleNotifier.java
Labels: size/M

#4531 Always call foreground activity callbacks on the UI thread
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/AabUpdater.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/ApkInstaller.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/ApkUpdater.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionLifecycleNotifier.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionRegistrar.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/TesterSignInManager.java
  firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/ApkUpdaterTest.java
  firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionLifecycleNotifierTest.java
Labels: size/L

#4534 Extract APK hash on the background thread
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionRegistrar.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/NewReleaseFetcher.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/ReleaseIdentifier.java
  firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/NewReleaseFetcherTest.java
  firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/ReleaseIdentifierTest.java
Labels: size/L

#4535 Use explicit executors in more App Distro continuations
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FeedbackSender.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionImpl.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionRegistrar.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/ScreenshotTaker.java
  firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/FeedbackSenderTest.java
  firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionServiceImplTest.java
  firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/ScreenshotTakerTest.java
Labels: size/L

#4538 Use BufferedOutputStream to prevent StrictMode violations
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/ScreenshotTaker.java
Labels: size/S

#4537 Move release notes script to Android repo
  docs/make_release_notes.py
Labels: size/L

#4539 Read file length on background thread to avoid StrictMode violation
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/ApkUpdater.java
Labels: size/XS

#4541 Request notification permissions in test app
  firebase-appdistribution/test-app/src/main/kotlin/com/googletest/firebase/appdistribution/testapp/MainActivity.kt
Labels: size/M

#4457 [Fireperf][AASA] Experiment time-to-initial-display 3
  firebase-perf/firebase-perf.gradle
  firebase-perf/src/main/java/com/google/firebase/perf/metrics/AppStartTrace.java
  firebase-perf/src/main/java/com/google/firebase/perf/util/PreDrawListener.java
  firebase-perf/src/main/java/com/google/firebase/perf/util/Timer.java
  firebase-perf/src/test/java/com/google/firebase/perf/metrics/AppStartTraceTest.java
  firebase-perf/src/test/java/com/google/firebase/perf/util/TimerTest.java
Labels: size/L, no-changelog

#4545 Update infoText javadoc description
  firebase-appdistribution-api/src/main/java/com/google/firebase/appdistribution/FirebaseAppDistribution.java
Labels: size/M

#4548 Use the create pull request action to commit the changes
  .github/workflows/create_releases.yml
Labels: size/S

#4551 Allow per-app language preferences to simplify SDK i18n testing.
  firebase-appdistribution/test-app/src/main/AndroidManifest.xml
  firebase-appdistribution/test-app/src/main/res/xml/locales_config.xml
Labels: size/S

#4444 Adds support to read the build ids
  firebase-crashlytics/src/androidTest/assets/firebase_settings_collect_build_ids.json
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/CommonUtilsTest.java
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/CrashlyticsControllerTest.java
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/CrashlyticsCoreInitializationTest.java
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/CrashlyticsCoreTest.java
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/CrashlyticsReportDataCaptureTest.java
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/model/serialization/CrashlyticsReportJsonTransformTest.java
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/persistence/CrashlyticsReportPersistenceTest.java
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/settings/SettingsV3JsonTransformTest.java
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/settings/TestSettings.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/FirebaseCrashlytics.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/AppData.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/BuildIdInfo.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CommonUtils.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsReportDataCapture.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/SessionReportingCoordinator.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/model/CrashlyticsReport.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/model/serialization/CrashlyticsReportJsonTransform.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/settings/DefaultSettingsJsonTransform.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/settings/Settings.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/settings/SettingsJsonConstants.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/settings/SettingsV3JsonTransform.java
  firebase-crashlytics/src/test/java/com/google/firebase/crashlytics/internal/common/CrashlyticsControllerRobolectricTest.java
Labels: size/XL

#4514 Move Firebase Installations to the new, injected executors
  firebase-installations/firebase-installations.gradle
  firebase-installations/src/main/java/com/google/firebase/installations/FirebaseInstallations.java
  firebase-installations/src/main/java/com/google/firebase/installations/FirebaseInstallationsRegistrar.java
  firebase-installations/src/test/java/com/google/firebase/installations/FirebaseInstallationsTest.java
Labels: size/L

#4556 Wrap target backend property in double quotes
  firebase-firestore/firebase-firestore.gradle
Labels: size/XS

#4552 Extend publishing plugin to support release configFiles.
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/publish/PublishingPlugin.java
Labels: size/M

#4553 Use file-based release configuration for the build release action.
  .github/workflows/build-release-artifacts.yml
Labels: size/XS

#4558 Update testlab devices for transport-runtime test
  transport/transport-runtime/transport-runtime.gradle
Labels: size/XS

#4557 Rename updatedParams to updatedKeys in ConfigUpdate.
  firebase-config/api.txt
  firebase-config/src/main/java/com/google/firebase/remoteconfig/ConfigUpdate.java
  firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigAutoFetch.java
  firebase-config/src/test/java/com/google/firebase/remoteconfig/FirebaseRemoteConfigTest.java
Labels: size/S, no-changelog

#4560 Update buildsrc unit test action to 1.6
  .github/workflows/build-src-check.yml
Labels: size/XS

#4561 Use an executor for Realtime HTTP onSuccess task.
  firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigRealtimeHttpClient.java
Labels: size/XS, no-changelog

#4555 Report updated experiments if either experiment id or variant id changes.
  firebase-abt/CHANGELOG.md
  firebase-abt/src/main/java/com/google/firebase/abt/FirebaseABTesting.java
  firebase-abt/src/test/java/com/google/firebase/abt/FirebaseABTestingTest.java
Labels: size/L

#4564 Update protos to include bloom filter
  firebase-abt/CHANGELOG.md
  firebase-abt/src/main/java/com/google/firebase/abt/FirebaseABTesting.java
  firebase-abt/src/test/java/com/google/firebase/abt/FirebaseABTestingTest.java
  firebase-firestore/src/proto/google/firestore/v1/bloom_filter.proto
  firebase-firestore/src/proto/google/firestore/v1/firestore.proto
  firebase-firestore/src/proto/google/firestore/v1/write.proto
Labels: size/L

#4565 Update make_release_notes to generate based on the release config
  docs/make_release_notes.py
Labels: size/XL, no-changelog, main-merge-ack

#4554 Migrate FireEscapeArtifactPlugin to Kotlin
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/FireEscapeArtifactPlugin.java
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/FireEscapeArtifactPlugin.kt
Labels: size/L

#4424 Migrate vendor plugin to new transform api.
  appcheck/firebase-appcheck/ktx/src/androidTest/AndroidManifest.xml
  buildSrc/build.gradle.kts
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/FirebaseLibraryPlugin.java
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/VendorPlugin.kt
  buildSrc/src/test/kotlin/com/google/firebase/gradle/plugins/VendorTests.kt
  firebase-appdistribution-api/ktx/src/androidTest/AndroidManifest.xml
  firebase-crashlytics-ndk/firebase-crashlytics-ndk.gradle
  firebase-crashlytics/ktx/src/androidTest/AndroidManifest.xml
  firebase-firestore/firebase-firestore.gradle
  firebase-firestore/src/androidTest/AndroidManifest.xml
  firebase-functions/ktx/src/androidTest/AndroidManifest.xml
  firebase-functions/src/androidTest/AndroidManifest.xml
  firebase-inappmessaging/src/androidTest/AndroidManifest.xml
  firebase-installations/src/androidTest/AndroidManifest.xml
  firebase-messaging/src/androidTest/AndroidManifest.xml
  gradle/wrapper/gradle-wrapper.properties
  transport/transport-runtime/transport-runtime.gradle
Labels: size/XL

#4573 Update Realtime RC service URL.
  firebase-config/src/main/java/com/google/firebase/remoteconfig/RemoteConfigConstants.java
Labels: size/XS, no-changelog

#4567 Read release name from release config file.
  docs/make_release_notes.py
Labels: size/S, no-changelog, main-merge-ack

#4568 Update build release artifacts workflow to include release notes
  .github/workflows/build-release-artifacts.yml
Labels: size/XS, main-merge-ack

#4579 Replace Android version with SDK version in the Realtime stream request.
  firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigRealtimeHttpClient.java
Labels: size/XS, no-changelog

#4524 Implement BloomFilter class
  firebase-firestore/src/main/java/com/google/firebase/firestore/remote/BloomFilter.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/remote/BloomFilterTest.java
  firebase-firestore/src/test/resources/bloom_filter_golden_test_data/Validation_BloomFilterTest_MD5_1_0001_bloom_filter_proto.json
  firebase-firestore/src/test/resources/bloom_filter_golden_test_data/Validation_BloomFilterTest_MD5_1_0001_membership_test_result.json
  firebase-firestore/src/test/resources/bloom_filter_golden_test_data/Validation_BloomFilterTest_MD5_1_01_bloom_filter_proto.json
  firebase-firestore/src/test/resources/bloom_filter_golden_test_data/Validation_BloomFilterTest_MD5_1_01_membership_test_result.json
  firebase-firestore/src/test/resources/bloom_filter_golden_test_data/Validation_BloomFilterTest_MD5_1_1_bloom_filter_proto.json
  firebase-firestore/src/test/resources/bloom_filter_golden_test_data/Validation_BloomFilterTest_MD5_1_1_membership_test_result.json
  firebase-firestore/src/test/resources/bloom_filter_golden_test_data/Validation_BloomFilterTest_MD5_50000_0001_bloom_filter_proto.json
  firebase-firestore/src/test/resources/bloom_filter_golden_test_data/Validation_BloomFilterTest_MD5_50000_0001_membership_test_result.json
  firebase-firestore/src/test/resources/bloom_filter_golden_test_data/Validation_BloomFilterTest_MD5_50000_01_bloom_filter_proto.json
  firebase-firestore/src/test/resources/bloom_filter_golden_test_data/Validation_BloomFilterTest_MD5_50000_01_membership_test_result.json
  firebase-firestore/src/test/resources/bloom_filter_golden_test_data/Validation_BloomFilterTest_MD5_50000_1_bloom_filter_proto.json
  firebase-firestore/src/test/resources/bloom_filter_golden_test_data/Validation_BloomFilterTest_MD5_50000_1_membership_test_result.json
  firebase-firestore/src/test/resources/bloom_filter_golden_test_data/Validation_BloomFilterTest_MD5_5000_0001_bloom_filter_proto.json
  firebase-firestore/src/test/resources/bloom_filter_golden_test_data/Validation_BloomFilterTest_MD5_5000_0001_membership_test_result.json
  firebase-firestore/src/test/resources/bloom_filter_golden_test_data/Validation_BloomFilterTest_MD5_5000_01_bloom_filter_proto.json
  firebase-firestore/src/test/resources/bloom_filter_golden_test_data/Validation_BloomFilterTest_MD5_5000_01_membership_test_result.json
  firebase-firestore/src/test/resources/bloom_filter_golden_test_data/Validation_BloomFilterTest_MD5_5000_1_bloom_filter_proto.json
  firebase-firestore/src/test/resources/bloom_filter_golden_test_data/Validation_BloomFilterTest_MD5_5000_1_membership_test_result.json
  firebase-firestore/src/test/resources/bloom_filter_golden_test_data/Validation_BloomFilterTest_MD5_500_0001_bloom_filter_proto.json
  firebase-firestore/src/test/resources/bloom_filter_golden_test_data/Validation_BloomFilterTest_MD5_500_0001_membership_test_result.json
  firebase-firestore/src/test/resources/bloom_filter_golden_test_data/Validation_BloomFilterTest_MD5_500_01_bloom_filter_proto.json
  firebase-firestore/src/test/resources/bloom_filter_golden_test_data/Validation_BloomFilterTest_MD5_500_01_membership_test_result.json
  firebase-firestore/src/test/resources/bloom_filter_golden_test_data/Validation_BloomFilterTest_MD5_500_1_bloom_filter_proto.json
  firebase-firestore/src/test/resources/bloom_filter_golden_test_data/Validation_BloomFilterTest_MD5_500_1_membership_test_result.json
Labels: size/L, no-changelog

#4569 Realtime RC 1P Bug Fix: Remove thread interruption logic
  firebase-config/src/main/java/com/google/firebase/remoteconfig/FirebaseRemoteConfig.java
  firebase-config/src/main/java/com/google/firebase/remoteconfig/RemoteConfigComponent.java
  firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigAutoFetch.java
  firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigRealtimeHandler.java
  firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigRealtimeHttpClient.java
  firebase-config/src/test/java/com/google/firebase/remoteconfig/FirebaseRemoteConfigTest.java
Labels: size/L

#4580 Remove deprecated setting
  settings.gradle
Labels: size/XS, no-changelog, main-merge-ack

#4584 Don't diff experiment metadata to determine updated keys.
  firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigContainer.java
  firebase-config/src/test/java/com/google/firebase/remoteconfig/internal/ConfigContainerTest.java
Labels: size/S, no-changelog

#4590 Fix Dex error due to conflicting packages
  firebase-appdistribution/src/androidTest/AndroidManifest.xml
Labels: size/XS

#4589 Remove now-unnecessary lint suppression
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/UpdateTaskImpl.java
Labels: size/XS

#4593 Some cleanup in App Distro's Dagger usage
  firebase-appdistribution/firebase-appdistribution.gradle
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/AabUpdater.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/ApkInstaller.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/ApkUpdater.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionImpl.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionLifecycleNotifier.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionRegistrar.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/ScreenshotTaker.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/SignInStorage.java
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/TesterSignInManager.java
  firebase-appdistribution/src/test/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionLifecycleNotifierTest.java
Labels: size/L

#4595 Update test app readme
  firebase-appdistribution/test-app/README.md
Labels: size/XS

#4597 Add bug to comment about multiple FirebaseApps
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/AppDistroComponent.java
Labels: size/XS

#4563 Clean up integration test checks for target backend.
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/testutil/IntegrationTestUtil.java
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/testutil/prod_provider/FirestoreProvider.java
Labels: size/M

#4574 Add expected count to target
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/SyncEngine.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/LocalSerializer.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/TargetData.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/remote/RemoteSerializer.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/remote/RemoteStore.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/LocalSerializerTest.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/TargetCacheTestCase.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/spec/SpecTestCase.java
  firebase-firestore/src/test/resources/json/listen_spec_test.json
Labels: size/XL

#4602 Realtime RC Bug Patch: Fixes deadlock issue that caused app to freeze when transitioning from background to foreground
  firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigRealtimeHttpClient.java
  firebase-config/src/test/java/com/google/firebase/remoteconfig/FirebaseRemoteConfigTest.java
Labels: size/M

#4605 Make a deep copy of the other config before modifying it to compute changes.
  firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigContainer.java
  firebase-config/src/test/java/com/google/firebase/remoteconfig/internal/ConfigContainerTest.java
Labels: size/M, no-changelog

#4608 Catch SQLException when doing best effort forced send in Crashlytics.
  firebase-crashlytics/CHANGELOG.md
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/send/ReportQueue.java
Labels: size/XS, main-merge-ack
