Repository firebase/firebase-android-sdk, pull requests merged in 2023-04, with the labels that each got.

#4843 Merge fad/next into master to prepare for M130 release
  firebase-appdistribution-api/CHANGELOG.md
  firebase-appdistribution-api/gradle.properties
  firebase-appdistribution-api/src/main/java/com/google/firebase/appdistribution/FirebaseAppDistribution.java
  firebase-appdistribution/CHANGELOG.md
  firebase-appdistribution/gradle.properties
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionNotificationsManager.java
  firebase-appdistribution/src/main/res/drawable-anydpi-v24/ic_rate_review.xml
  firebase-appdistribution/src/main/res/drawable-hdpi/ic_rate_review.png
  firebase-appdistribution/src/main/res/drawable-mdpi/ic_rate_review.png
  firebase-appdistribution/src/main/res/drawable-xhdpi/ic_rate_review.png
  firebase-appdistribution/src/main/res/drawable-xxhdpi/ic_rate_review.png
  firebase-appdistribution/src/main/res/drawable/ic_baseline_rate_review_24.xml
Labels: size/M, main-merge-ack

#4735 Support Sum/Avg in Android SDK
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/AggregationTest.java
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/CountTest.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/AggregateField.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/AggregateQuery.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/AggregateQuerySnapshot.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/Query.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/UserDataWriter.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/FirestoreClient.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/SyncEngine.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/remote/Datastore.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/remote/RemoteSerializer.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/remote/RemoteStore.java
Labels: size/XXL, no-changelog, main-merge-ack

#4844 Update sdk versions
  appcheck/firebase-appcheck/CHANGELOG.md
  firebase-appdistribution-api/CHANGELOG.md
  firebase-appdistribution/CHANGELOG.md
  firebase-common/gradle.properties
  firebase-config/CHANGELOG.md
  firebase-config/gradle.properties
  firebase-crashlytics-ndk/CHANGELOG.md
  firebase-crashlytics-ndk/gradle.properties
  firebase-crashlytics/CHANGELOG.md
  firebase-crashlytics/gradle.properties
  firebase-firestore/gradle.properties
  firebase-inappmessaging-display/CHANGELOG.md
  firebase-inappmessaging/CHANGELOG.md
  firebase-messaging-directboot/CHANGELOG.md
  firebase-messaging/CHANGELOG.md
Labels: size/L, main-merge-ack

#4804 feat(rtdb, firestore): create values() and dataObjects() Flows
  firebase-database/CHANGELOG.md
  firebase-database/ktx/api.txt
  firebase-database/ktx/src/main/kotlin/com/google/firebase/database/ktx/Database.kt
  firebase-firestore/CHANGELOG.md
  firebase-firestore/ktx/api.txt
  firebase-firestore/ktx/src/main/kotlin/com/google/firebase/firestore/ktx/Firestore.kt
Labels: size/M, main-merge-ack

#4847 Include Kotlin directories in the Dackka plugin
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/DackkaPlugin.kt
Labels: size/XS, no-changelog, main-merge-ack

#4852 Add comparability to ModuleVersion and use it to fix a behavior bug i…
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/LibraryGroupRegistrar.kt
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/ModuleVersion.kt
  buildSrc/src/test/kotlin/com/google/firebase/gradle/plugins/PublishingPluginTests.kt
Labels: size/M, main-merge-ack

#4848 Make ktx headers h4 instead of h3
  docs/make_release_notes.py
Labels: size/XS

#4838 Remove the need to ack the merge-to-main check
  .github/workflows/merge-to-main.yml
Labels: size/S

#4841 Fix workflows for Firebase Sessions
  firebase-sessions/firebase-sessions.gradle.kts
  firebase-sessions/src/androidTest/AndroidManifest.xml
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/ApplicationInfo.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionEvents.kt
  firebase-sessions/src/test/kotlin/com/google/firebase/sessions/ApplicationInfoTest.kt
  firebase-sessions/test-app/test-app.gradle.kts
Labels: size/M, no-changelog

#4802 Add support for version control information forwarding
  firebase-crashlytics/CHANGELOG.md
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsController.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsCore.java
Labels: size/M, main-merge-ack

#4854 Fix storage test dependency on appcheck
  firebase-storage/firebase-storage.gradle
Labels: size/XS

#4853 Setup configuration layer for the library.
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionInitiator.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionsSettings.kt
  firebase-sessions/src/test/kotlin/com/google/firebase/sessions/SessionsSettingsTest.kt
Labels: size/M, no-changelog

#4858 Fix Firebase Sessions test app temporarily
  firebase-sessions/test-app/src/main/kotlin/com/google/firebase/testing/sessions/MainActivity.kt
  firebase-sessions/test-app/test-app.gradle.kts
Labels: size/XS

#4857 Add README files
  firebase-sessions/README.md
  firebase-sessions/test-app/README.md
Labels: size/M, no-changelog

#4862 Fix pinned dependencies in crashlytics and messaging
  firebase-crashlytics/firebase-crashlytics.gradle
  firebase-messaging/firebase-messaging.gradle
Labels: size/XS

#4868 Add the integration test's google-services.json file to unit tests
  .github/workflows/ci_tests.yml
  firebase-sessions/test-app/test-app.gradle.kts
Labels: size/S, no-changelog

#4850 Firestore: add a Kotlin unit test for PropertyName
  firebase-firestore/ktx/src/test/kotlin/com/google/firebase/firestore/ktx/FirestoreTests.kt
Labels: size/S, api: firestore, no-changelog, main-merge-ack

#4826 Semver check for firebase sdks
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/FirebaseJavaLibraryPlugin.kt
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/FirebaseLibraryPlugin.kt
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/GmavenHelper.kt
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/semver/AccessDescriptor.kt
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/semver/ApiDiffer.kt
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/semver/ClassInfo.kt
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/semver/Delta.kt
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/semver/DeltaType.kt
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/semver/GmavenCopier.kt
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/semver/UtilityClass.kt
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/semver/VersionDelta.kt
Labels: size/XXL

#4859 Setup sessions e2e workflow
  .github/workflows/sessions-e2e.yml
Labels: size/M

#4875 Removing former team members from the Fireperf e2e assignee list
  .github/workflows/fireperf-e2e.yml
Labels: size/XS

#4856 fix @see
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/ModuleVersion.kt
Labels: size/XS, main-merge-ack

#4870 Fix encoding for Session Events
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/EventGDTLogger.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionCoordinator.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionEvent.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionEvents.kt
  firebase-sessions/src/test/kotlin/com/google/firebase/sessions/EventGDTLoggerTest.kt
  firebase-sessions/src/test/kotlin/com/google/firebase/sessions/SessionCoordinatorTest.kt
  firebase-sessions/src/test/kotlin/com/google/firebase/sessions/SessionEventEncoderTest.kt
  firebase-sessions/src/test/kotlin/com/google/firebase/sessions/SessionEventTest.kt
  firebase-sessions/src/test/kotlin/com/google/firebase/sessions/testing/TestSessionEventData.kt
Labels: size/L, no-changelog

#4874 Changing Fireperf's SDK Floats to Doubles
  firebase-perf/CHANGELOG.md
  firebase-perf/src/main/java/com/google/firebase/perf/config/ConfigResolver.java
  firebase-perf/src/main/java/com/google/firebase/perf/config/ConfigurationConstants.java
  firebase-perf/src/main/java/com/google/firebase/perf/config/DeviceCacheManager.java
  firebase-perf/src/main/java/com/google/firebase/perf/config/RemoteConfigManager.java
  firebase-perf/src/main/java/com/google/firebase/perf/transport/RateLimiter.java
  firebase-perf/src/main/java/com/google/firebase/perf/util/Constants.java
  firebase-perf/src/main/java/com/google/firebase/perf/util/ImmutableBundle.java
  firebase-perf/src/test/java/com/google/firebase/perf/config/ConfigResolverTest.java
  firebase-perf/src/test/java/com/google/firebase/perf/config/ConfigurationConstantsTest.java
  firebase-perf/src/test/java/com/google/firebase/perf/config/DeviceCacheManagerTest.java
  firebase-perf/src/test/java/com/google/firebase/perf/config/RemoteConfigManagerTest.java
  firebase-perf/src/test/java/com/google/firebase/perf/session/PerfSessionTest.java
  firebase-perf/src/test/java/com/google/firebase/perf/transport/RateLimiterTest.java
  firebase-perf/src/test/java/com/google/firebase/perf/util/ImmutableBundleTest.java
Labels: size/XL

#4881 Use test app for Sessions e2e test
  .github/workflows/sessions-e2e.yml
  firebase-sessions/test-app/src/androidTest/kotlin/com/google/firebase/testing/sessions/FirebaseSessionsTest.kt
  firebase-sessions/test-app/test-app.gradle.kts
Labels: size/M, no-changelog

#4876 Implement limited-use App Check tokens.
  appcheck/firebase-appcheck/CHANGELOG.md
  appcheck/firebase-appcheck/api.txt
  appcheck/firebase-appcheck/src/main/java/com/google/firebase/appcheck/FirebaseAppCheck.java
  appcheck/firebase-appcheck/src/main/java/com/google/firebase/appcheck/internal/DefaultFirebaseAppCheck.java
  appcheck/firebase-appcheck/src/test/java/com/google/firebase/appcheck/internal/DefaultFirebaseAppCheckTest.java
  appcheck/firebase-appcheck/test-app/src/main/java/com/googletest/firebase/appcheck/MainActivity.java
  appcheck/firebase-appcheck/test-app/src/main/res/layout/activity_main.xml
  appcheck/firebase-appcheck/test-app/src/main/res/values/strings.xml
Labels: size/L

#4885 Merge sessions-e2e.yml from firebase-sessions so it can run on schedule
  .github/workflows/sessions-e2e.yml
Labels: size/M, no-changelog, main-merge-ack

#4890 Move currentTimeUs into WallClock
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionEvents.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/WallClock.kt
Labels: size/S, no-changelog

#4891 Populate sampling rate in session event
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/FirebaseSessions.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionEvents.kt
  firebase-sessions/src/test/kotlin/com/google/firebase/sessions/ApplicationInfoTest.kt
  firebase-sessions/src/test/kotlin/com/google/firebase/sessions/EventGDTLoggerTest.kt
  firebase-sessions/src/test/kotlin/com/google/firebase/sessions/LocalOverrideSettingsTest.kt
  firebase-sessions/src/test/kotlin/com/google/firebase/sessions/SessionCoordinatorTest.kt
  firebase-sessions/src/test/kotlin/com/google/firebase/sessions/SessionEventEncoderTest.kt
  firebase-sessions/src/test/kotlin/com/google/firebase/sessions/SessionEventTest.kt
  firebase-sessions/src/test/kotlin/com/google/firebase/sessions/SessionInitiatorTest.kt
  firebase-sessions/src/test/kotlin/com/google/firebase/sessions/SessionsSettingsTest.kt
  firebase-sessions/src/test/kotlin/com/google/firebase/sessions/testing/FakeFirebaseApp.kt
  firebase-sessions/src/test/kotlin/com/google/firebase/sessions/testing/TestSessionEventData.kt
Labels: size/L

#4869 New cache config API
  firebase-firestore/CHANGELOG.md
  firebase-firestore/api.txt
  firebase-firestore/ktx/api.txt
  firebase-firestore/ktx/src/main/kotlin/com/google/firebase/firestore/ktx/Firestore.kt
  firebase-firestore/ktx/src/test/kotlin/com/google/firebase/firestore/ktx/FirestoreTests.kt
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/BundleTest.java
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/FirestoreTest.java
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/testutil/IntegrationTestUtil.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/FirebaseFirestoreSettings.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/LocalCacheSettings.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/MemoryCacheSettings.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/PersistentCacheSettings.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/FirebaseFirestoreSettingsTest.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/FirebaseFirestoreTest.java
Labels: size/XL, main-merge-ack

#4824 Fix bundle query resume issue
  firebase-firestore/src/main/java/com/google/firebase/firestore/bundle/BundleSerializer.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/bundle/BundleReaderTest.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/bundle/BundleSerializerTest.java
Labels: size/L, main-merge-ack

#4897 add github actions for semver check
  .github/workflows/semver-check.yml
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/FirebaseLibraryPlugin.kt
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/publish/PublishingPlugin.java
Labels: size/M

#4895 Fix some gradle deprecation warnings
  build.gradle
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/ci/Coverage.java
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/license/GenerateLicensesTask.java
Labels: size/XS

#4898 Suppress warnings in delegatingScheduled code
  firebase-common/src/main/java/com/google/firebase/concurrent/DelegatingScheduledExecutorService.java
  firebase-common/src/main/java/com/google/firebase/concurrent/DelegatingScheduledFuture.java
Labels: size/XS, no-changelog

#4902 Use to setup-java@v3 to Node16 (@v2 uses node12 which is deprecated)
  .github/workflows/api-information.yml
  .github/workflows/build-src-check.yml
  .github/workflows/ci_tests.yml
  .github/workflows/fireperf-e2e.yml
  .github/workflows/health-metrics.yml
  .github/workflows/make-bom.yml
  .github/workflows/smoke-tests.yml
Labels: size/S

#4904 Prefer immutable set for test initialization
  firebase-common/src/test/java/com/google/firebase/heartbeatinfo/DefaultHeartBeatControllerTest.java
Labels: size/XS, no-changelog, main-merge-ack

#4879 Refactor Publisher
  buildSrc/src/main/java/com/google/firebase/gradle/MultiProjectReleasePlugin.java
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/BaseFirebaseLibraryPlugin.kt
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/CheckHeadDependencies.kt
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/GradleUtils.kt
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/KotlinUtils.kt
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/ci/SmokeTestsPlugin.java
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/publish/Mode.java
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/publish/Publisher.java
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/publish/PublishingPlugin.java
  buildSrc/src/test/kotlin/com/google/firebase/gradle/plugins/PublishingPluginTests.kt
  firebase-installations/firebase-installations.gradle
Labels: size/XL, no-changelog

#4906 Don't rely on transitive dependency for guava test.
  firebase-common/firebase-common.gradle.kts
Labels: size/XS, no-changelog

#4909 Update versions
  encoders/firebase-encoders-json/gradle.properties
  firebase-appdistribution-api/gradle.properties
  firebase-appdistribution/gradle.properties
  firebase-database/gradle.properties
  firebase-datatransport/gradle.properties
  firebase-firestore/gradle.properties
Labels: size/S

#4908 Update changelog entries
  firebase-appdistribution-api/CHANGELOG.md
  firebase-appdistribution/CHANGELOG.md
  firebase-database/CHANGELOG.md
  firebase-firestore/CHANGELOG.md
Labels: size/M

#4905 Add TimeProvider interface to abstract away the clock
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/FirebaseSessions.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionEvents.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionInitiator.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/Time.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/WallClock.kt
  firebase-sessions/src/test/kotlin/com/google/firebase/sessions/EventGDTLoggerTest.kt
  firebase-sessions/src/test/kotlin/com/google/firebase/sessions/SessionCoordinatorTest.kt
  firebase-sessions/src/test/kotlin/com/google/firebase/sessions/SessionEventEncoderTest.kt
  firebase-sessions/src/test/kotlin/com/google/firebase/sessions/SessionEventTest.kt
  firebase-sessions/src/test/kotlin/com/google/firebase/sessions/SessionInitiatorTest.kt
  firebase-sessions/src/test/kotlin/com/google/firebase/sessions/testing/FakeTimeProvider.kt
Labels: size/L, no-changelog

#4913 Fix Fiam crash at AbtIntegrationHelper
  firebase-inappmessaging-display/CHANGELOG.md
  firebase-inappmessaging/CHANGELOG.md
  firebase-inappmessaging/src/main/java/com/google/firebase/inappmessaging/FirebaseInAppMessagingRegistrar.java
  firebase-inappmessaging/src/main/java/com/google/firebase/inappmessaging/internal/AbtIntegrationHelper.java
  firebase-inappmessaging/src/main/java/com/google/firebase/inappmessaging/internal/injection/components/UniversalComponent.java
  firebase-inappmessaging/src/test/java/com/google/firebase/inappmessaging/internal/AbtIntegrationHelperTest.java
Labels: size/S

#4915 bom update
  buildSrc/src/main/java/com/google/firebase/gradle/bomgenerator/BomGeneratorTask.java
Labels: size/XS

#4916 Use empty string when handling null mcc_mnc
  transport/transport-backend-cct/src/main/java/com/google/android/datatransport/cct/CctTransportBackend.java
Labels: size/S

#4892 Fill in device_model field for AQS
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionEvents.kt
  firebase-sessions/src/test/kotlin/com/google/firebase/sessions/ApplicationInfoTest.kt
  firebase-sessions/src/test/kotlin/com/google/firebase/sessions/SessionEventEncoderTest.kt
  firebase-sessions/src/test/kotlin/com/google/firebase/sessions/testing/TestSessionEventData.kt
Labels: size/S, no-changelog

#4896 Implement sampling
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/FirebaseSessions.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionGenerator.kt
  firebase-sessions/src/test/kotlin/com/google/firebase/sessions/SessionGeneratorTest.kt
  firebase-sessions/src/test/kotlin/com/google/firebase/sessions/testing/TestSessionEventData.kt
Labels: size/M, no-changelog

#4914 Add Sessions to benchmark config
  ci/fireci/fireciplugins/macrobenchmark/run/runner.py
  health-metrics/benchmark/config.yaml
Labels: size/XS, no-changelog

#4917 Introduce remote config cache for storing configs fetched remotely.
  firebase-sessions/firebase-sessions.gradle.kts
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/settings/LocalOverrideSettings.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/settings/RemoteSettings.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/settings/SessionsSettings.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/settings/SettingsCache.kt
  firebase-sessions/src/test/kotlin/com/google/firebase/sessions/SettingsCacheTest.kt
Labels: size/L, no-changelog

#4919 Make Sessions logging consistent with Apple SDK
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/EventGDTLogger.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/FirebaseSessions.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionCoordinator.kt
Labels: size/S, api: sessions

#4882 Add release_report.md to release brach
  .github/workflows/create_releases.yml
Labels: size/XS

#4925 Address few nits in transport-runtime
  transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/scheduling/jobscheduling/Uploader.java
  transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/scheduling/persistence/SQLiteEventStore.java
  transport/transport-runtime/transport-runtime.gradle
Labels: size/S

#4924 Refactor PomValidator
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/BaseFirebaseLibraryPlugin.kt
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/PomValidator.kt
Labels: size/M, no-changelog

#4922 Firestore: Internal method AggregateQuerySnapshot.createWithCount() added for CPP SDK
  firebase-firestore/src/main/java/com/google/firebase/firestore/AggregateQuerySnapshot.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/AggregateQuerySnapshotTest.java
Labels: size/M, api: firestore, no-changelog, main-merge-ack

#4929 Firestore Spec Tests: Port JS PR 7229 (optimized query resumption using bloom filter)
  firebase-firestore/src/test/java/com/google/firebase/firestore/spec/SpecTestCase.java
  firebase-firestore/src/test/resources/json/bundle_spec_test.json
  firebase-firestore/src/test/resources/json/existence_filter_spec_test.json
  firebase-firestore/src/test/resources/json/limbo_spec_test.json
  firebase-firestore/src/test/resources/json/limit_spec_test.json
  firebase-firestore/src/test/resources/json/listen_spec_test.json
  firebase-firestore/src/test/resources/json/offline_spec_test.json
  firebase-firestore/src/test/resources/json/recovery_spec_test.json
Labels: size/XXL, api: firestore, no-changelog, main-merge-ack

#4921 M131 release prepare
  appcheck/firebase-appcheck-debug-testing/firebase-appcheck-debug-testing.gradle
  appcheck/firebase-appcheck/firebase-appcheck.gradle
  firebase-firestore/firebase-firestore.gradle
  firebase-storage/firebase-storage.gradle
Labels: size/S, no-changelog

#4934 Bump storage test dep on appcheck
  firebase-storage/firebase-storage.gradle
Labels: size/XS, no-changelog

#4935 Release notes for memory lru
  firebase-firestore/CHANGELOG.md
Labels: size/XS

#4923 Refactor PublishingPlugin
  .github/workflows/build-release-artifacts.yml
  .github/workflows/check-head-dependencies.yml
  .github/workflows/create_releases.yml
  .github/workflows/semver-check.yml
  .github/workflows/validate-dependencies.yml
  build.gradle
  buildSrc/build.gradle.kts
  buildSrc/src/main/java/com/google/firebase/gradle/MultiProjectReleasePlugin.java
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/CheckHeadDependencies.kt
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/DackkaPlugin.kt
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/GmavenHelper.kt
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/GradleUtils.kt
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/ProjectUtils.kt
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/PublishingPlugin.kt
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/ReleaseConfig.kt
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/ReleaseGenerator.kt
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/ci/SmokeTestsPlugin.java
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/publish/PublishingPlugin.java
  docs/make_release_notes.py
  gradle/libs.versions.toml
Labels: size/XXL, no-changelog

#4936 update firestore version
  firebase-firestore/gradle.properties
Labels: size/XS

#4830 Implement Android Executors for Storage
  firebase-storage/CHANGELOG.md
  firebase-storage/firebase-storage.gradle
  firebase-storage/src/main/java/com/google/firebase/storage/FirebaseStorageComponent.java
  firebase-storage/src/main/java/com/google/firebase/storage/StorageRegistrar.java
  firebase-storage/src/main/java/com/google/firebase/storage/StorageTaskScheduler.java
  firebase-storage/src/main/java/com/google/firebase/storage/UploadTask.java
  firebase-storage/src/main/java/com/google/firebase/storage/internal/SmartHandler.java
  firebase-storage/src/test/java/com/google/firebase/storage/TestUtil.java
  firebase-storage/src/testUtil/java/com/google/firebase/storage/ControllableSchedulerHelper.java
Labels: size/L, main-merge-ack

#4937 Revert "Refactor PublishingPlugin"
  .github/workflows/build-release-artifacts.yml
  .github/workflows/check-head-dependencies.yml
  .github/workflows/create_releases.yml
  .github/workflows/semver-check.yml
  .github/workflows/validate-dependencies.yml
  build.gradle
  buildSrc/build.gradle.kts
  buildSrc/src/main/java/com/google/firebase/gradle/MultiProjectReleasePlugin.java
  buildSrc/src/main/java/com/google/firebase/gradle/ReleaseGenerator.kt
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/CheckHeadDependencies.kt
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/DackkaPlugin.kt
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/GmavenHelper.kt
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/GradleUtils.kt
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/ProjectUtils.kt
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/PublishingPlugin.kt
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/ReleaseConfig.kt
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/ci/SmokeTestsPlugin.java
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/publish/PublishingPlugin.java
  docs/make_release_notes.py
  gradle/libs.versions.toml
Labels: size/XXL

#4938 Revert "Implement Android Executors for Storage (#4830)"
  firebase-storage/CHANGELOG.md
  firebase-storage/firebase-storage.gradle
  firebase-storage/src/main/java/com/google/firebase/storage/FirebaseStorageComponent.java
  firebase-storage/src/main/java/com/google/firebase/storage/StorageRegistrar.java
  firebase-storage/src/main/java/com/google/firebase/storage/StorageTaskScheduler.java
  firebase-storage/src/main/java/com/google/firebase/storage/UploadTask.java
  firebase-storage/src/main/java/com/google/firebase/storage/internal/SmartHandler.java
  firebase-storage/src/test/java/com/google/firebase/storage/TestUtil.java
  firebase-storage/src/testUtil/java/com/google/firebase/storage/ControllableSchedulerHelper.java
Labels: size/L

#4944 Bump version for firebase-config to 21.4.0 (minor bump).
  firebase-config/gradle.properties
Labels: size/XS, no-changelog, main-merge-ack

#4952 Fix changelog files for several products
  firebase-appdistribution-api/CHANGELOG.md
  firebase-appdistribution/CHANGELOG.md
  firebase-database/CHANGELOG.md
  firebase-firestore/CHANGELOG.md
Labels: size/XS

#4954 Updating changelog
  firebase-inappmessaging/CHANGELOG.md
Labels: size/XS

#4955 Updating changelog
  firebase-inappmessaging-display/CHANGELOG.md
Labels: size/XS

#4950 Pass a CoroutineContext, not CoroutineDispatcher, to SessionCoordinator
  firebase-sessions/firebase-sessions.gradle.kts
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionCoordinator.kt
  firebase-sessions/src/test/kotlin/com/google/firebase/sessions/SessionCoordinatorTest.kt
Labels: size/S, no-changelog

#4956 Update changelogs
  appcheck/firebase-appcheck-debug-testing/CHANGELOG.md
  appcheck/firebase-appcheck-debug/CHANGELOG.md
  appcheck/firebase-appcheck-playintegrity/CHANGELOG.md
  appcheck/firebase-appcheck/CHANGELOG.md
  firebase-database/CHANGELOG.md
  firebase-firestore/CHANGELOG.md
  firebase-functions/CHANGELOG.md
  firebase-storage/CHANGELOG.md
Labels: size/S

#4959 More doc fixes for 24.6.0
  firebase-firestore/CHANGELOG.md
  firebase-firestore/src/main/java/com/google/firebase/firestore/FirebaseFirestoreSettings.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/LocalCacheSettings.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/MemoryCacheSettings.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/PersistentCacheSettings.java
Labels: size/M

#4963 Change ConfigUpdateListener docs link to code reference.
  firebase-config/src/main/java/com/google/firebase/remoteconfig/ConfigUpdateListener.java
Labels: size/XS, no-changelog, main-merge-ack

#4962 Fix pom dependencies
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/BaseFirebaseLibraryPlugin.kt
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/KotlinUtils.kt
Labels: size/M, no-changelog

#4964 Fix various issues and inconsistencies in the Remote Config ref docs.
  firebase-config/src/main/java/com/google/firebase/remoteconfig/FirebaseRemoteConfig.java
  firebase-config/src/main/java/com/google/firebase/remoteconfig/FirebaseRemoteConfigClientException.java
  firebase-config/src/main/java/com/google/firebase/remoteconfig/FirebaseRemoteConfigException.java
  firebase-config/src/main/java/com/google/firebase/remoteconfig/FirebaseRemoteConfigInfo.java
  firebase-config/src/main/java/com/google/firebase/remoteconfig/FirebaseRemoteConfigServerException.java
  firebase-config/src/main/java/com/google/firebase/remoteconfig/FirebaseRemoteConfigSettings.java
Labels: size/M, no-changelog, main-merge-ack
