Repository firebase/firebase-android-sdk, pull requests merged in 2024-09, with the labels that each got.

#6224 Add issue link to changelog entry
  firebase-crashlytics/CHANGELOG.md
Labels: size/XS, main-merge-ack

#6226 Fix sessions test app for target api 34
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionLifecycleServiceBinder.kt
  firebase-sessions/test-app/src/main/AndroidManifest.xml
  firebase-sessions/test-app/src/main/kotlin/com/google/firebase/testing/sessions/ForegroundService.kt
  firebase-sessions/test-app/src/main/kotlin/com/google/firebase/testing/sessions/TestApplication.kt
Labels: size/M, no-changelog, main-merge-ack

#6229 Update firebase-appdistribution/test-app to target API level 34
  firebase-appdistribution/test-app/src/main/AndroidManifest.xml
  firebase-appdistribution/test-app/src/main/kotlin/com/googletest/firebase/appdistribution/testapp/CustomNotificationActivity.kt
  firebase-appdistribution/test-app/src/main/kotlin/com/googletest/firebase/appdistribution/testapp/CustomNotificationFeedbackTrigger.kt
  firebase-appdistribution/test-app/src/main/kotlin/com/googletest/firebase/appdistribution/testapp/MainActivity.kt
  firebase-appdistribution/test-app/src/main/kotlin/com/googletest/firebase/appdistribution/testapp/ScreenshotDetectionActivity.kt
  firebase-appdistribution/test-app/src/main/kotlin/com/googletest/firebase/appdistribution/testapp/SecondActivity.kt
  firebase-appdistribution/test-app/src/main/kotlin/com/googletest/firebase/appdistribution/testapp/ShakeDetectionFeedbackTrigger.kt
  firebase-appdistribution/test-app/test-app.gradle
Labels: size/S, no-changelog

#6231 Update CHANGELOG
  firebase-crashlytics/CHANGELOG.md
Labels: size/S

#6240 Ignore removed entries in CHANGED_FROM_STATIC
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/semver/DeltaType.kt
Labels: size/XS

#6241 Bump latest released version of vertexai
  firebase-vertexai/gradle.properties
Labels: size/XS

#6242 Pin appcheck-interop dependency to latest released version
  firebase-functions/firebase-functions.gradle.kts
Labels: size/XS

#6243 Add entry in the changelog for next release
  firebase-appdistribution-api/CHANGELOG.md
  firebase-appdistribution/CHANGELOG.md
  firebase-crashlytics-ndk/CHANGELOG.md
Labels: size/XS

#6227 Include message priority when logging to Firelog.
  firebase-messaging/CHANGELOG.md
  firebase-messaging/src/main/java/com/google/firebase/messaging/MessagingAnalytics.java
  firebase-messaging/src/test/java/com/google/firebase/messaging/MessagingAnalyticsRoboTest.java
Labels: size/S

#6250 Fix typo in GenerationConfig.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/GenerationConfig.kt
Labels: size/XS

#6246 Fix typo in class made final check in semver
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/semver/DeltaType.kt
Labels: size/XS

#6252 Fix Javadoc in FirebaseCrashlytics
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/FirebaseCrashlytics.java
Labels: size/S, no-changelog, main-merge-ack

#6216 Fix `putBytes()`API to use `maxUploadRetryTimeMillis` parameter
  firebase-storage/CHANGELOG.md
  firebase-storage/src/main/java/com/google/firebase/storage/UploadTask.java
Labels: size/XS

#6254 Move Kotlin serialization gradle plugin into libs.versions.toml
  build.gradle
  firebase-vertexai/firebase-vertexai.gradle.kts
  gradle/libs.versions.toml
Labels: size/S, main-merge-ack

#6255 protoc-gen-firebase-encoders.gradle: use libs.versions.toml
  encoders/protoc-gen-firebase-encoders/protoc-gen-firebase-encoders.gradle
  gradle/libs.versions.toml
Labels: size/S, main-merge-ack

#6261 Improve kdoc for GenerationConfig
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/GenerationConfig.kt
Labels: size/M

#6268 Add support for blockReasonMessage
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/common/server/Types.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/internal/util/conversions.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/PromptFeedback.kt
  firebase-vertexai/src/test/java/com/google/firebase/vertexai/StreamingSnapshotTests.kt
  firebase-vertexai/src/test/java/com/google/firebase/vertexai/UnarySnapshotTests.kt
Labels: size/S

#6257 Add new line at the end of release note files
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/MakeReleaseNotesTask.kt
  docs/make_release_notes.py
Labels: size/L

#6273 Add support for allowed_function_names
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/common/client/Types.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/internal/util/conversions.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/FunctionCallingConfig.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/ToolConfig.kt
  firebase-vertexai/src/test/java/com/google/firebase/vertexai/common/APIControllerTests.kt
Labels: size/M

#6272 fix(vertexai): export the firebase-common dependency
  firebase-vertexai/firebase-vertexai.gradle.kts
Labels: size/XS

#6269 Fix visibility on Firebase Functions
  firebase-functions/api.txt
  firebase-functions/src/androidTest/java/com/google/firebase/functions/FirebaseFunctionsTest.java
  firebase-functions/src/androidTest/java/com/google/firebase/functions/FirebaseFunctionsTest.kt
  firebase-functions/src/main/java/com/google/firebase/functions/FirebaseFunctions.kt
Labels: size/L

#6276 Wrap citations inside CitationMetadata
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/internal/util/conversions.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/Candidate.kt
  firebase-vertexai/src/test/java/com/google/firebase/vertexai/StreamingSnapshotTests.kt
  firebase-vertexai/src/test/java/com/google/firebase/vertexai/UnarySnapshotTests.kt
Labels: size/M

#6258 Revamp Schema declaration
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/internal/util/conversions.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/FunctionDeclaration.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/FunctionDeclarations.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/FunctionParameter.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/GenerationConfig.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/Schema.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/Type.kt
  firebase-vertexai/src/test/java/com/google/firebase/vertexai/SchemaTests.kt
Labels: size/XL

#6281 Remove redundant null declaration
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/GenerationConfig.kt
Labels: size/XS

#6283 Overhaul AnyScalarIntegrationTest.kt
  firebase-dataconnect/emulator/dataconnect/connector/alltypes/alltypes_ops.gql
  firebase-dataconnect/emulator/dataconnect/connector/demo/demo_ops.gql
  firebase-dataconnect/emulator/dataconnect/schema/alltypes_schema.gql
  firebase-dataconnect/emulator/dataconnect/schema/demo_schema.gql
  firebase-dataconnect/src/androidTest/kotlin/com/google/firebase/dataconnect/AnyScalarIntegrationTest.kt
  firebase-dataconnect/testutil/src/main/kotlin/com/google/firebase/dataconnect/testutil/AnyScalarTestUtils.kt
  firebase-dataconnect/testutil/src/main/kotlin/com/google/firebase/dataconnect/testutil/Arbs.kt
  firebase-dataconnect/testutil/src/main/kotlin/com/google/firebase/dataconnect/testutil/EdgeCases.kt
  gradle/libs.versions.toml
Labels: size/XXL

#6280 Fixed exception propagation on null default uncaught exception handler
  firebase-crashlytics/CHANGELOG.md
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsUncaughtExceptionHandler.java
Labels: size/S, main-merge-ack

#6285 AnyValue and AnyValueSerializer added
  firebase-dataconnect/api.txt
  firebase-dataconnect/src/main/kotlin/com/google/firebase/dataconnect/AnyValue.kt
  firebase-dataconnect/src/main/kotlin/com/google/firebase/dataconnect/FirebaseDataConnect.kt
  firebase-dataconnect/src/main/kotlin/com/google/firebase/dataconnect/serializers/AnyValueSerializer.kt
  firebase-dataconnect/src/main/kotlin/com/google/firebase/dataconnect/util/ProtoStructDecoder.kt
  firebase-dataconnect/src/main/kotlin/com/google/firebase/dataconnect/util/ProtoStructEncoder.kt
  firebase-dataconnect/src/main/kotlin/com/google/firebase/dataconnect/util/ProtoUtil.kt
  firebase-dataconnect/src/test/kotlin/com/google/firebase/dataconnect/AnyValueSerializerUnitTest.kt
  firebase-dataconnect/src/test/kotlin/com/google/firebase/dataconnect/AnyValueUnitTest.kt
  firebase-dataconnect/src/test/kotlin/com/google/firebase/dataconnect/testutil/DataConnectAnySerializer.kt
  firebase-dataconnect/testutil/src/main/kotlin/com/google/firebase/dataconnect/testutil/Arbs.kt
Labels: size/XXL

#6291 RemoteConfigComponentTest.java: fix flaky test
  firebase-config/src/test/java/com/google/firebase/remoteconfig/RemoteConfigComponentTest.java
Labels: size/XS

#6289 Switch `RequestOption` to accept long timeout only
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/GenerativeModel.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/common/APIController.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/common/RequestOptions.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/internal/util/conversions.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/RequestOptions.kt
  firebase-vertexai/src/test/java/com/google/firebase/vertexai/common/APIControllerTests.kt
  firebase-vertexai/src/test/java/com/google/firebase/vertexai/common/util/tests.kt
  firebase-vertexai/src/test/java/com/google/firebase/vertexai/util/tests.kt
Labels: size/M

#6297 Add SerializersModule support to QueryRef and MutationRef
  firebase-dataconnect/CHANGELOG.md
  firebase-dataconnect/api.txt
  firebase-dataconnect/src/main/kotlin/com/google/firebase/dataconnect/AnyValue.kt
  firebase-dataconnect/src/main/kotlin/com/google/firebase/dataconnect/FirebaseDataConnect.kt
  firebase-dataconnect/src/main/kotlin/com/google/firebase/dataconnect/OperationRef.kt
  firebase-dataconnect/src/main/kotlin/com/google/firebase/dataconnect/core/DataConnectGrpcClient.kt
  firebase-dataconnect/src/main/kotlin/com/google/firebase/dataconnect/core/FirebaseDataConnectImpl.kt
  firebase-dataconnect/src/main/kotlin/com/google/firebase/dataconnect/core/MutationRefImpl.kt
  firebase-dataconnect/src/main/kotlin/com/google/firebase/dataconnect/core/OperationRefImpl.kt
  firebase-dataconnect/src/main/kotlin/com/google/firebase/dataconnect/core/QueryRefImpl.kt
  firebase-dataconnect/src/main/kotlin/com/google/firebase/dataconnect/generated/GeneratedMutation.kt
  firebase-dataconnect/src/main/kotlin/com/google/firebase/dataconnect/generated/GeneratedQuery.kt
  firebase-dataconnect/src/main/kotlin/com/google/firebase/dataconnect/querymgr/LiveQueries.kt
  firebase-dataconnect/src/main/kotlin/com/google/firebase/dataconnect/querymgr/LiveQuery.kt
  firebase-dataconnect/src/main/kotlin/com/google/firebase/dataconnect/querymgr/QueryManager.kt
  firebase-dataconnect/src/main/kotlin/com/google/firebase/dataconnect/querymgr/RegisteredDataDeserialzer.kt
  firebase-dataconnect/src/main/kotlin/com/google/firebase/dataconnect/util/ProtoStructDecoder.kt
  firebase-dataconnect/src/main/kotlin/com/google/firebase/dataconnect/util/ProtoStructEncoder.kt
  firebase-dataconnect/src/main/kotlin/com/google/firebase/dataconnect/util/Util.kt
  firebase-dataconnect/src/test/kotlin/com/google/firebase/dataconnect/AnyValueUnitTest.kt
  firebase-dataconnect/src/test/kotlin/com/google/firebase/dataconnect/core/DataConnectGrpcClientUnitTest.kt
  firebase-dataconnect/src/test/kotlin/com/google/firebase/dataconnect/core/DataConnectGrpcMetadataUnitTest.kt
  firebase-dataconnect/src/test/kotlin/com/google/firebase/dataconnect/core/FirebaseDataConnectImplUnitTest.kt
  firebase-dataconnect/src/test/kotlin/com/google/firebase/dataconnect/core/MutationRefImplUnitTest.kt
  firebase-dataconnect/src/test/kotlin/com/google/firebase/dataconnect/core/MutationResultUnitTest.kt
  firebase-dataconnect/src/test/kotlin/com/google/firebase/dataconnect/core/OperationRefImplUnitTest.kt
  firebase-dataconnect/src/test/kotlin/com/google/firebase/dataconnect/core/QueryRefImplUnitTest.kt
  firebase-dataconnect/src/test/kotlin/com/google/firebase/dataconnect/core/QueryResultUnitTest.kt
  firebase-dataconnect/src/test/kotlin/com/google/firebase/dataconnect/testutil/Arbs.kt
  firebase-dataconnect/src/test/kotlin/com/google/firebase/dataconnect/testutil/Stubs.kt
Labels: size/XXL

#6298 CallerSdkType added
  firebase-dataconnect/CHANGELOG.md
  firebase-dataconnect/api.txt
  firebase-dataconnect/src/main/kotlin/com/google/firebase/dataconnect/FirebaseDataConnect.kt
  firebase-dataconnect/src/main/kotlin/com/google/firebase/dataconnect/OperationRef.kt
  firebase-dataconnect/src/main/kotlin/com/google/firebase/dataconnect/core/DataConnectGrpcClient.kt
  firebase-dataconnect/src/main/kotlin/com/google/firebase/dataconnect/core/DataConnectGrpcMetadata.kt
  firebase-dataconnect/src/main/kotlin/com/google/firebase/dataconnect/core/DataConnectGrpcRPCs.kt
  firebase-dataconnect/src/main/kotlin/com/google/firebase/dataconnect/core/FirebaseDataConnectImpl.kt
  firebase-dataconnect/src/main/kotlin/com/google/firebase/dataconnect/core/MutationRefImpl.kt
  firebase-dataconnect/src/main/kotlin/com/google/firebase/dataconnect/core/OperationRefImpl.kt
  firebase-dataconnect/src/main/kotlin/com/google/firebase/dataconnect/core/QueryRefImpl.kt
  firebase-dataconnect/src/main/kotlin/com/google/firebase/dataconnect/generated/GeneratedMutation.kt
  firebase-dataconnect/src/main/kotlin/com/google/firebase/dataconnect/generated/GeneratedQuery.kt
  firebase-dataconnect/src/main/kotlin/com/google/firebase/dataconnect/querymgr/LiveQuery.kt
  firebase-dataconnect/src/main/kotlin/com/google/firebase/dataconnect/querymgr/QueryManager.kt
  firebase-dataconnect/src/main/kotlin/com/google/firebase/dataconnect/serializers/UUIDSerializer.kt
  firebase-dataconnect/src/test/kotlin/com/google/firebase/dataconnect/core/DataConnectGrpcClientUnitTest.kt
  firebase-dataconnect/src/test/kotlin/com/google/firebase/dataconnect/core/DataConnectGrpcMetadataUnitTest.kt
  firebase-dataconnect/src/test/kotlin/com/google/firebase/dataconnect/core/FirebaseDataConnectImplUnitTest.kt
  firebase-dataconnect/src/test/kotlin/com/google/firebase/dataconnect/core/MutationRefImplUnitTest.kt
  firebase-dataconnect/src/test/kotlin/com/google/firebase/dataconnect/core/MutationResultUnitTest.kt
  firebase-dataconnect/src/test/kotlin/com/google/firebase/dataconnect/core/OperationRefImplUnitTest.kt
  firebase-dataconnect/src/test/kotlin/com/google/firebase/dataconnect/core/QueryRefImplUnitTest.kt
  firebase-dataconnect/src/test/kotlin/com/google/firebase/dataconnect/core/QueryResultUnitTest.kt
  firebase-dataconnect/src/test/kotlin/com/google/firebase/dataconnect/testutil/Arbs.kt
  firebase-dataconnect/src/test/kotlin/com/google/firebase/dataconnect/testutil/Stubs.kt
  firebase-dataconnect/testutil/src/main/kotlin/com/google/firebase/dataconnect/testutil/Arbs.kt
Labels: size/XL

#6299 v1alpha -> v1beta
  firebase-dataconnect/CHANGELOG.md
  firebase-dataconnect/emulator/dataconnect/dataconnect.yaml
  firebase-dataconnect/src/main/proto/google/firebase/dataconnect/proto/connector_service.proto
  firebase-dataconnect/src/main/proto/google/firebase/dataconnect/proto/graphql_error.proto
Labels: size/XS

#6292 Move requestOptions to be the last positional argument
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/FirebaseVertexAI.kt
Labels: size/XS

#6294 Several small changes to enums API
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/internal/util/conversions.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/Candidate.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/CountTokensResponse.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/HarmBlockThreshold.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/HarmProbability.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/HarmSeverity.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/PromptFeedback.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/SafetySetting.kt
Labels: size/M

#6301 Add missing `FirstOrdinalSerializer` to enum
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/common/server/Types.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/common/shared/Types.kt
  firebase-vertexai/src/test/java/com/google/firebase/vertexai/common/UnarySnapshotTests.kt
Labels: size/M

#6141 remove javax.annotation.Nonnull from files containing a different Non…
  firebase-config/bandwagoner/src/main/java/com/googletest/firebase/remoteconfig/bandwagoner/RealtimeFragment.java
  firebase-config/src/main/java/com/google/firebase/remoteconfig/ConfigUpdateListener.java
  firebase-config/src/main/java/com/google/firebase/remoteconfig/FirebaseRemoteConfigServerException.java
  firebase-config/src/test/java/com/google/firebase/remoteconfig/FirebaseRemoteConfigTest.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/AggregateQuerySnapshot.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/MemoryRemoteDocumentCache.java
  firebase-inappmessaging/src/main/java/com/google/firebase/inappmessaging/model/ProtoMarshallerClient.java
Labels: size/M

#6302 Create the function declaration schema at construction time
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/internal/util/conversions.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/FunctionDeclaration.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/Schema.kt
Labels: size/S

#6304 Remove unnecessary excludes from gradle.kts files
  firebase-dataconnect/androidTestutil/androidTestutil.gradle.kts
  firebase-dataconnect/firebase-dataconnect.gradle.kts
  firebase-dataconnect/testutil/testutil.gradle.kts
Labels: size/M

#6307 Add OrderDirection support
  firebase-dataconnect/CHANGELOG.md
  firebase-dataconnect/emulator/dataconnect/connector/alltypes/alltypes_ops.gql
  firebase-dataconnect/emulator/dataconnect/schema/alltypes_schema.gql
  firebase-dataconnect/src/androidTest/kotlin/com/google/firebase/dataconnect/OrderDirectionIntegrationTest.kt
  firebase-dataconnect/src/main/kotlin/com/google/firebase/dataconnect/util/ProtoStructDecoder.kt
  firebase-dataconnect/src/main/kotlin/com/google/firebase/dataconnect/util/ProtoStructEncoder.kt
  firebase-dataconnect/testutil/src/main/kotlin/com/google/firebase/dataconnect/testutil/Arbs.kt
  firebase-dataconnect/testutil/src/main/kotlin/com/google/firebase/dataconnect/testutil/TestUtils.kt
Labels: size/L, main-merge-ack

#6306 ConfigCacheClientTest.java: fix flaky test due to race condition
  firebase-config/src/test/java/com/google/firebase/remoteconfig/internal/ConfigCacheClientTest.java
Labels: size/S, api: remoteconfig, main-merge-ack

#6279 Add consumer proguard rules
  firebase-vertexai/consumer-rules.pro
  firebase-vertexai/firebase-vertexai.gradle.kts
  firebase-vertexai/proguard-rules.pro
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/common/APIController.kt
  firebase-vertexai/src/test/java/com/google/firebase/vertexai/common/util/tests.kt
  firebase-vertexai/src/test/java/com/google/firebase/vertexai/util/tests.kt
Labels: size/M

#6312 dataconnect: upgrade toolkit version to 1.4.0 (was 1.3.8)
  firebase-dataconnect/gradleplugin/plugin/src/main/kotlin/com/google/firebase/dataconnect/gradle/plugin/DataConnectExecutable.kt
  firebase-dataconnect/gradleplugin/plugin/src/main/kotlin/com/google/firebase/dataconnect/gradle/plugin/DataConnectProviders.kt
Labels: size/S, no-changelog, main-merge-ack

#6300 Update endpoint
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/common/APIController.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/common/server/Types.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/RequestOptions.kt
  firebase-vertexai/src/test/java/com/google/firebase/vertexai/common/APIControllerTests.kt
Labels: size/M

#6320 dataconnect: gradleplugin now gets kotlin version from the main libs.versions.toml
  firebase-dataconnect/gradleplugin/gradle/libs.versions.toml
  firebase-dataconnect/gradleplugin/plugin/build.gradle.kts
  firebase-dataconnect/gradleplugin/settings.gradle.kts
  gradle/libs.versions.toml
Labels: size/S, no-changelog, main-merge-ack

#6311 Introduce `FunctionCall` and `FunctionResponse` types
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/internal/util/conversions.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/Part.kt
  firebase-vertexai/src/test/java/com/google/firebase/vertexai/UnarySnapshotTests.kt
Labels: size/L

#6313 Use kotlin's explicit API in vertexAI
  firebase-vertexai/firebase-vertexai.gradle.kts
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/Chat.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/FirebaseVertexAI.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/GenerativeModel.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/common/shared/Types.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/java/ChatFutures.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/java/GenerativeModelFutures.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/Candidate.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/Content.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/CountTokensResponse.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/Exceptions.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/FunctionCallingConfig.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/FunctionDeclaration.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/GenerateContentResponse.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/GenerationConfig.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/HarmBlockMethod.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/HarmBlockThreshold.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/HarmCategory.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/HarmProbability.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/HarmSeverity.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/Part.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/PromptFeedback.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/RequestOptions.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/SafetySetting.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/Schema.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/Tool.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/ToolConfig.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/UsageMetadata.kt
Labels: size/L

#6262 Rename BlockThreshold to HarmBlockThreshold
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/HarmBlockThreshold.kt
Labels: size/XS

#6324 Update vertex version
  firebase-vertexai/gradle.properties
Labels: size/XS

#6321 Use gradle/libs.versions.toml to specify the Android Gradle Plugin version
  buildSrc/build.gradle.kts
  firebase-dataconnect/gradleplugin/gradle/libs.versions.toml
  firebase-dataconnect/gradleplugin/plugin/build.gradle.kts
  gradle/libs.versions.toml
Labels: size/S, no-changelog, main-merge-ack

#6327 dataconnect: fix gradle plugin to gracefully handle schemaExtensionsOutputEnabled not being explicitly specified
  firebase-dataconnect/gradleplugin/plugin/src/main/kotlin/com/google/firebase/dataconnect/gradle/plugin/DataConnectRunEmulatorTask.kt
Labels: size/XS, no-changelog, main-merge-ack

#6325 dataconnect: Add toolkit versions to gradle plugin: 1.4.1, 1.4.2, and 1.4.3
  firebase-dataconnect/gradleplugin/plugin/src/main/kotlin/com/google/firebase/dataconnect/gradle/plugin/DataConnectExecutable.kt
Labels: size/S, no-changelog, main-merge-ack

#6326 Update service disabled wording
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/common/APIController.kt
Labels: size/S

#6316 Bump `action-create-branch` action
  .github/workflows/create_releases.yml
Labels: size/XS

#6308 dataconnect: Add OrderDirection codegen integration test
  firebase-dataconnect/connectors/src/androidTest/kotlin/com/google/firebase/dataconnect/connectors/demo/OrderDirectionIntegrationTest.kt
  firebase-dataconnect/emulator/dataconnect/connector/alltypes/alltypes_ops.gql
  firebase-dataconnect/emulator/dataconnect/connector/demo/demo_ops.gql
  firebase-dataconnect/emulator/dataconnect/schema/alltypes_schema.gql
  firebase-dataconnect/emulator/dataconnect/schema/demo_schema.gql
  firebase-dataconnect/src/androidTest/kotlin/com/google/firebase/dataconnect/OrderDirectionIntegrationTest.kt
Labels: size/L, no-changelog, main-merge-ack, api: dataconnect

#6328 Use gradle/libs.versions.toml to specify the Spotless version
  build.gradle
  firebase-dataconnect/gradleplugin/gradle/libs.versions.toml
  firebase-dataconnect/gradleplugin/plugin/build.gradle.kts
  gradle/libs.versions.toml
Labels: size/XS, no-changelog, main-merge-ack

#6331 dataconnect: gradle plugin modified to load executable versions from a json file
  firebase-dataconnect/gradleplugin/plugin/build.gradle.kts
  firebase-dataconnect/gradleplugin/plugin/src/main/kotlin/com/google/firebase/dataconnect/gradle/plugin/DataConnectExecutable.kt
  firebase-dataconnect/gradleplugin/plugin/src/main/resources/com/google/firebase/dataconnect/gradle/plugin/DataConnectExecutableVersions.json
Labels: size/L, no-changelog, main-merge-ack, api: dataconnect

#6329 FirebaseDataConnectIntegrationTest.kt: refactor to use more modern kotlin testing facilities
  firebase-dataconnect/src/androidTest/kotlin/com/google/firebase/dataconnect/FirebaseDataConnectIntegrationTest.kt
  firebase-dataconnect/testutil/src/main/kotlin/com/google/firebase/dataconnect/testutil/TestUtils.kt
Labels: size/L, no-changelog, main-merge-ack, api: dataconnect

#6330 buildSrc/build.gradle.kts: Use kotlin serialization library from libs.versions.toml
  buildSrc/build.gradle.kts
Labels: size/XS, no-changelog, main-merge-ack
