Repository firebase/firebase-android-sdk, pull requests merged in 2024-12, with the labels that each got.

#6553 Minor bump vertex-ai version
  firebase-vertexai/gradle.properties
Labels: size/XS

#6551 Prevent whole session events from logging to logcat
  firebase-sessions/CHANGELOG.md
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/EventGDTLogger.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionFirelogPublisher.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionLifecycleClient.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionLifecycleService.kt
Labels: size/S

#6557 Make repo sync a pull operation
  .github/workflows/private-mirror-sync.yml
Labels: size/S

#6528 Add an overload to FirebaseCrashlytics.recordException to attach additional custom key value pairs
  firebase-crashlytics/CHANGELOG.md
  firebase-crashlytics/api.txt
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/CrashlyticsControllerTest.java
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/CrashlyticsCoreTest.java
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/SessionReportingCoordinatorTest.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/FirebaseCrashlytics.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsController.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsCore.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/SessionReportingCoordinator.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/metadata/EventMetadata.kt
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/metadata/KeysMap.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/metadata/UserMetadata.java
Labels: size/XL

#6546 Add a kotlin method for recording an exception with custom keys
  firebase-crashlytics/api.txt
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/CrashlyticsTests.kt
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/FirebaseCrashlytics.kt
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/KeyValueBuilder.kt
Labels: size/M

#6561 firebase-dataconnect minimal demo app added
  firebase-dataconnect/demo/.gitignore
  firebase-dataconnect/demo/.idea/runConfigurations/spotlessApply.xml
  firebase-dataconnect/demo/build.gradle.kts
  firebase-dataconnect/demo/firebase/.firebaserc
  firebase-dataconnect/demo/firebase/dataconnect/.gitignore
  firebase-dataconnect/demo/firebase/dataconnect/connector/connector.yaml
  firebase-dataconnect/demo/firebase/dataconnect/connector/operations.gql
  firebase-dataconnect/demo/firebase/dataconnect/dataconnect.yaml
  firebase-dataconnect/demo/firebase/dataconnect/schema/schema.gql
  firebase-dataconnect/demo/firebase/firebase.json
  firebase-dataconnect/demo/google-services.json
  firebase-dataconnect/demo/gradle.properties
  firebase-dataconnect/demo/gradle/wrapper/gradle-wrapper.jar
  firebase-dataconnect/demo/gradle/wrapper/gradle-wrapper.properties
  firebase-dataconnect/demo/gradlew
  firebase-dataconnect/demo/gradlew.bat
  firebase-dataconnect/demo/settings.gradle.kts
  firebase-dataconnect/demo/src/main/AndroidManifest.xml
  firebase-dataconnect/demo/src/main/kotlin/com/google/firebase/dataconnect/minimaldemo/MainActivity.kt
  firebase-dataconnect/demo/src/main/kotlin/com/google/firebase/dataconnect/minimaldemo/MainActivityViewModel.kt
  firebase-dataconnect/demo/src/main/kotlin/com/google/firebase/dataconnect/minimaldemo/MyApplication.kt
  firebase-dataconnect/demo/src/main/kotlin/com/google/firebase/dataconnect/minimaldemo/arbs.kt
  firebase-dataconnect/demo/src/main/kotlin/com/google/firebase/dataconnect/minimaldemo/strings.kt
  firebase-dataconnect/demo/src/main/res/layout/activity_main.xml
Labels: size/XXL, no-changelog, main-merge-ack, api: dataconnect

#6568 dataconnect: .github/workflows/dataconnect_demo_app.yml added
  .github/workflows/dataconnect_demo_app.yml
  firebase-dataconnect/demo/.gitignore
  firebase-dataconnect/demo/build.gradle.kts
  firebase-dataconnect/demo/firebase/dataconnect/connector/connector.yaml
Labels: size/L, no-changelog, main-merge-ack, api: dataconnect

#6570 Use version catalog for encoders
  encoders/firebase-decoders-json/firebase-decoders-json.gradle
  encoders/firebase-encoders-json/firebase-encoders-json.gradle
  encoders/firebase-encoders-reflective/firebase-encoders-reflective.gradle
  encoders/firebase-encoders/firebase-encoders.gradle
  encoders/protoc-gen-firebase-encoders/tests/tests.gradle
Labels: size/M

#6571 dataconnect: demo: make codegen gradle task cacheable
  firebase-dataconnect/demo/build.gradle.kts
Labels: size/M, no-changelog, main-merge-ack, api: dataconnect

#6579 dataconnect: DataConnectExecutableVersions.json updated with versions 1.7.1, 1.7.2, 1.7.3, and 1.7.4
  firebase-dataconnect/gradleplugin/plugin/src/main/resources/com/google/firebase/dataconnect/gradle/plugin/DataConnectExecutableVersions.json
Labels: size/M, no-changelog, main-merge-ack, api: dataconnect

#6581 Fix "duplicate class" errors when running `./gradlew :appcheck:firebase-appcheck-debug:deviceCheck`
  appcheck/firebase-appcheck-debug/firebase-appcheck-debug.gradle
Labels: size/XS, no-changelog, main-merge-ack

#6410 Add custom signals support in Remote Config.
  firebase-config/api.txt
  firebase-config/src/main/java/com/google/firebase/remoteconfig/CustomSignals.java
  firebase-config/src/main/java/com/google/firebase/remoteconfig/FirebaseRemoteConfig.java
  firebase-config/src/main/java/com/google/firebase/remoteconfig/RemoteConfig.kt
  firebase-config/src/main/java/com/google/firebase/remoteconfig/RemoteConfigComponent.java
  firebase-config/src/main/java/com/google/firebase/remoteconfig/RemoteConfigConstants.java
  firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigFetchHttpClient.java
  firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigSharedPrefsClient.java
  firebase-config/src/test/java/com/google/firebase/remoteconfig/CustomSignalsTest.java
  firebase-config/src/test/java/com/google/firebase/remoteconfig/FirebaseRemoteConfigTest.java
  firebase-config/src/test/java/com/google/firebase/remoteconfig/RemoteConfigTests.kt
  firebase-config/src/test/java/com/google/firebase/remoteconfig/internal/ConfigFetchHttpClientTest.java
  firebase-config/src/test/java/com/google/firebase/remoteconfig/internal/ConfigSharedPrefsClientTest.java
Labels: size/L

#6577 dataconnect: demo: upgrade firebase-tools to v13.28.0
  .github/workflows/dataconnect_demo_app.yml
  firebase-dataconnect/demo/firebase/dataconnect/connector/operations.gql
Labels: size/S, no-changelog, main-merge-ack, api: dataconnect

#6585 dataconnect: demo: add "Delete" button an "List Items" screen.
  firebase-dataconnect/demo/firebase/dataconnect/connector/operations.gql
  firebase-dataconnect/demo/src/main/AndroidManifest.xml
  firebase-dataconnect/demo/src/main/kotlin/com/google/firebase/dataconnect/minimaldemo/ListItemsActivity.kt
  firebase-dataconnect/demo/src/main/kotlin/com/google/firebase/dataconnect/minimaldemo/ListItemsViewModel.kt
  firebase-dataconnect/demo/src/main/kotlin/com/google/firebase/dataconnect/minimaldemo/MainActivity.kt
  firebase-dataconnect/demo/src/main/kotlin/com/google/firebase/dataconnect/minimaldemo/MainActivityViewModel.kt
  firebase-dataconnect/demo/src/main/kotlin/com/google/firebase/dataconnect/minimaldemo/MainViewModel.kt
  firebase-dataconnect/demo/src/main/res/layout/activity_list_items.xml
  firebase-dataconnect/demo/src/main/res/layout/activity_main.xml
  firebase-dataconnect/demo/src/main/res/layout/list_item.xml
  firebase-dataconnect/demo/src/main/res/menu/menu_main.xml
Labels: size/XXL, no-changelog, main-merge-ack, api: dataconnect

#6582 Update fetch to utilize latest custom signals
  firebase-config/src/main/java/com/google/firebase/remoteconfig/RemoteConfigComponent.java
  firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigFetchHandler.java
  firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigFetchHttpClient.java
  firebase-config/src/test/java/com/google/firebase/remoteconfig/internal/ConfigFetchHandlerTest.java
  firebase-config/src/test/java/com/google/firebase/remoteconfig/internal/ConfigFetchHttpClientTest.java
Labels: size/L

#6584 Move all SDKs dependencies to use the version catalog
  firebase-abt/firebase-abt.gradle
  firebase-appdistribution-api/firebase-appdistribution-api.gradle
  firebase-appdistribution/firebase-appdistribution.gradle
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/FirebaseAppDistributionNotificationsManager.java
  firebase-config/bandwagoner/bandwagoner.gradle
  firebase-config/firebase-config.gradle.kts
  firebase-crashlytics-ndk/firebase-crashlytics-ndk.gradle
  firebase-crashlytics/firebase-crashlytics.gradle
  firebase-database/firebase-database.gradle.kts
  firebase-datatransport/firebase-datatransport.gradle
  firebase-dynamic-links/firebase-dynamic-links.gradle
  firebase-dynamic-links/src/test/java/com/google/firebase/dynamiclinks/PendingDynamicLinkDataTest.java
  firebase-dynamic-links/src/test/java/com/google/firebase/dynamiclinks/internal/FirebaseDynamicLinksImplTest.java
  firebase-firestore/firebase-firestore.gradle
  firebase-inappmessaging-display/firebase-inappmessaging-display.gradle
  firebase-inappmessaging/firebase-inappmessaging.gradle
  firebase-installations-interop/firebase-installations-interop.gradle
  firebase-installations/firebase-installations.gradle
  firebase-messaging-directboot/firebase-messaging-directboot.gradle
  firebase-messaging/firebase-messaging.gradle
  firebase-messaging/src/test/java/com/google/firebase/messaging/CommonNotificationBuilderRoboTest.java
  firebase-ml-modeldownloader/firebase-ml-modeldownloader.gradle
  firebase-ml-modeldownloader/ml-data-collection-tests/ml-data-collection-tests.gradle
  firebase-ml-modeldownloader/src/main/java/com/google/firebase/ml/modeldownloader/internal/FirebaseMlLogEvent.java
  firebase-perf/firebase-perf.gradle
  firebase-sessions/test-app/src/main/kotlin/com/google/firebase/testing/sessions/FirstFragment.kt
  firebase-storage/firebase-storage.gradle
  firebase-vertexai/firebase-vertexai.gradle.kts
  gradle/libs.versions.toml
Labels: size/XL

#6586 dataconnect: `FirebaseDataConnect.logLevel` changed to `MutableStateFlow`
  firebase-dataconnect/CHANGELOG.md
  firebase-dataconnect/api.txt
  firebase-dataconnect/src/main/kotlin/com/google/firebase/dataconnect/FirebaseDataConnect.kt
  firebase-dataconnect/src/main/kotlin/com/google/firebase/dataconnect/LogLevel.kt
  firebase-dataconnect/src/main/kotlin/com/google/firebase/dataconnect/core/Logger.kt
  firebase-dataconnect/src/test/kotlin/com/google/firebase/dataconnect/LogLevelUnitTest.kt
  firebase-dataconnect/testutil/src/main/kotlin/com/google/firebase/dataconnect/testutil/DataConnectLogLevelRule.kt
Labels: size/L, main-merge-ack, api: dataconnect

#6563 Add clean command to fireci
  ci/README.md
  ci/fireci/fireci/ci_utils.py
  ci/fireci/fireci/dir_utils.py
  ci/fireci/fireci/internal.py
  ci/fireci/fireci/main.py
  ci/fireci/fireciplugins/clean.py
  ci/fireci/setup.cfg
Labels: size/L, no-changelog, main-merge-ack

#6594 Fix: sort document reference by long type id
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/FirestoreTest.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/model/BasePath.java
Labels: size/L, no-changelog

#6606 Cleanup root build files
  build.gradle
  build.gradle.kts
  buildSrc/build.gradle.kts
  gradle/libs.versions.toml
  gradle/projectSettings.gradle
  health-metrics/apk-size/apk-size.gradle
  health-metrics/apk-size/app/default.gradle
  sdkProperties.gradle
  settings.gradle
  settings.gradle.kts
Labels: size/L, no-changelog, main-merge-ack

#6431 fix(firebase-perf): Update device cache only if RC value is different from cached value
  firebase-perf/CHANGELOG.md
  firebase-perf/src/main/java/com/google/firebase/perf/config/ConfigResolver.java
  firebase-perf/src/test/java/com/google/firebase/perf/config/ConfigResolverTest.java
Labels: size/M

#6449 Adjust Functions Kotlin docs for release
  firebase-functions/api.txt
  firebase-functions/ktx/src/androidTest/kotlin/com/google/firebase/functions/ktx/CallTests.kt
  firebase-functions/ktx/src/test/kotlin/com/google/firebase/functions/TestVisibilityUtil.kt
  firebase-functions/ktx/src/test/kotlin/com/google/firebase/functions/ktx/FunctionsTests.kt
  firebase-functions/src/main/java/com/google/firebase/functions/FirebaseFunctions.kt
  firebase-functions/src/main/java/com/google/firebase/functions/FirebaseFunctionsException.kt
  firebase-functions/src/main/java/com/google/firebase/functions/HttpsCallOptions.kt
  firebase-functions/src/main/java/com/google/firebase/functions/HttpsCallableOptions.kt
  firebase-functions/src/main/java/com/google/firebase/functions/HttpsCallableReference.kt
  firebase-functions/src/main/java/com/google/firebase/functions/HttpsCallableResult.kt
  firebase-functions/src/main/java/com/google/firebase/functions/Serializer.kt
Labels: size/L
