Repository firebase/firebase-android-sdk, pull requests merged in 2024-05, with the labels that each got.

#5916 add kotlin version for the request being made to vertex backend
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/GenerativeModel.kt
Labels: size/XS, cla: no

#5885 openStream should not be intercepted if Firebase Perf is not initialized
  firebase-perf/CHANGELOG.md
  firebase-perf/src/main/java/com/google/firebase/perf/network/FirebasePerfUrlConnection.java
Labels: size/XS

#5918 Use java 17 in release note changes check
  .github/workflows/release-note-changes.yml
Labels: size/XS

#5917 Add auth header integration to vertexai
  firebase-vertexai/firebase-vertexai.gradle.kts
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/FirebaseVertexAI.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/FirebaseVertexAIRegistrar.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/GenerativeModel.kt
Labels: size/M

#5921 reexpose tools
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/GenerativeModel.kt
Labels: size/S, cla: no

#5922 Make controller private in GenerativeModel
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/GenerativeModel.kt
Labels: size/XS

#5924 makes post release cleanup job run on java 17
  .github/workflows/post_release_cleanup.yml
Labels: size/XS

#5931 add GenerativeContentResponse#functionCalls
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/GenerateContentResponse.kt
Labels: size/S

#5926 fix versions
  firebase-appdistribution-api/gradle.properties
  firebase-appdistribution/gradle.properties
Labels: size/XS

#5942 ScalarVariablesAndDataIntegrationTest.kt: add tests for float, int, and boolean
  firebase-dataconnect/connectors/src/androidTest/kotlin/com/google/firebase/dataconnect/connectors/demo/ScalarVariablesAndDataIntegrationTest.kt
  firebase-dataconnect/emulator/dataconnect/connector/demo/demo_ops.gql
  firebase-dataconnect/emulator/dataconnect/schema/demo_schema.gql
  firebase-dataconnect/testutil/src/main/kotlin/com/google/firebase/dataconnect/testutil/DateTimeTestUtils.kt
  firebase-dataconnect/testutil/src/main/kotlin/com/google/firebase/dataconnect/testutil/TestUtils.kt
Labels: size/L

#5943 ListVariablesAndDataIntegrationTest.kt added
  firebase-dataconnect/connectors/src/androidTest/kotlin/com/google/firebase/dataconnect/connectors/demo/ListVariablesAndDataIntegrationTest.kt
  firebase-dataconnect/emulator/dataconnect/connector/demo/demo_ops.gql
  firebase-dataconnect/emulator/dataconnect/schema/demo_schema.gql
Labels: size/XL

#5935 delete the vertexai quickstart sample app
  firebase-vertexai-quickstart/.gitignore
  firebase-vertexai-quickstart/.google/packaging.yaml
  firebase-vertexai-quickstart/README.md
  firebase-vertexai-quickstart/app/build.gradle.kts
  firebase-vertexai-quickstart/app/src/main/AndroidManifest.xml
  firebase-vertexai-quickstart/app/src/main/kotlin/com/google/firebase/quickstart/vertexai/GenerativeAiViewModelFactory.kt
  firebase-vertexai-quickstart/app/src/main/kotlin/com/google/firebase/quickstart/vertexai/MainActivity.kt
  firebase-vertexai-quickstart/app/src/main/kotlin/com/google/firebase/quickstart/vertexai/MenuScreen.kt
  firebase-vertexai-quickstart/app/src/main/kotlin/com/google/firebase/quickstart/vertexai/feature/chat/ChatMessage.kt
  firebase-vertexai-quickstart/app/src/main/kotlin/com/google/firebase/quickstart/vertexai/feature/chat/ChatScreen.kt
  firebase-vertexai-quickstart/app/src/main/kotlin/com/google/firebase/quickstart/vertexai/feature/chat/ChatUiState.kt
  firebase-vertexai-quickstart/app/src/main/kotlin/com/google/firebase/quickstart/vertexai/feature/chat/ChatViewModel.kt
  firebase-vertexai-quickstart/app/src/main/kotlin/com/google/firebase/quickstart/vertexai/feature/functioncalling/FunctionsChatMessage.kt
  firebase-vertexai-quickstart/app/src/main/kotlin/com/google/firebase/quickstart/vertexai/feature/functioncalling/FunctionsChatScreen.kt
  firebase-vertexai-quickstart/app/src/main/kotlin/com/google/firebase/quickstart/vertexai/feature/functioncalling/FunctionsChatUiState.kt
  firebase-vertexai-quickstart/app/src/main/kotlin/com/google/firebase/quickstart/vertexai/feature/functioncalling/FunctionsChatViewModel.kt
  firebase-vertexai-quickstart/app/src/main/kotlin/com/google/firebase/quickstart/vertexai/feature/multimodal/PhotoReasoningScreen.kt
  firebase-vertexai-quickstart/app/src/main/kotlin/com/google/firebase/quickstart/vertexai/feature/multimodal/PhotoReasoningUiState.kt
  firebase-vertexai-quickstart/app/src/main/kotlin/com/google/firebase/quickstart/vertexai/feature/multimodal/PhotoReasoningViewModel.kt
  firebase-vertexai-quickstart/app/src/main/kotlin/com/google/firebase/quickstart/vertexai/feature/text/SummarizeScreen.kt
  firebase-vertexai-quickstart/app/src/main/kotlin/com/google/firebase/quickstart/vertexai/feature/text/SummarizeUiState.kt
  firebase-vertexai-quickstart/app/src/main/kotlin/com/google/firebase/quickstart/vertexai/feature/text/SummarizeViewModel.kt
  firebase-vertexai-quickstart/app/src/main/kotlin/com/google/firebase/quickstart/vertexai/ui/theme/Color.kt
  firebase-vertexai-quickstart/app/src/main/kotlin/com/google/firebase/quickstart/vertexai/ui/theme/Theme.kt
  firebase-vertexai-quickstart/app/src/main/kotlin/com/google/firebase/quickstart/vertexai/ui/theme/Type.kt
  firebase-vertexai-quickstart/app/src/main/kotlin/com/google/firebase/quickstart/vertexai/util/UriSaver.kt
  firebase-vertexai-quickstart/app/src/main/res/drawable/ic_launcher_background.xml
  firebase-vertexai-quickstart/app/src/main/res/drawable/ic_launcher_foreground.xml
  firebase-vertexai-quickstart/app/src/main/res/mipmap-anydpi/ic_launcher.xml
  firebase-vertexai-quickstart/app/src/main/res/mipmap-anydpi/ic_launcher_round.xml
  firebase-vertexai-quickstart/app/src/main/res/mipmap-hdpi/ic_launcher.webp
  firebase-vertexai-quickstart/app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  firebase-vertexai-quickstart/app/src/main/res/mipmap-mdpi/ic_launcher.webp
  firebase-vertexai-quickstart/app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  firebase-vertexai-quickstart/app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  firebase-vertexai-quickstart/app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  firebase-vertexai-quickstart/app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  firebase-vertexai-quickstart/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  firebase-vertexai-quickstart/app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  firebase-vertexai-quickstart/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  firebase-vertexai-quickstart/app/src/main/res/values/colors.xml
  firebase-vertexai-quickstart/app/src/main/res/values/strings.xml
  firebase-vertexai-quickstart/app/src/main/res/values/themes.xml
  firebase-vertexai-quickstart/app/src/main/res/xml/backup_rules.xml
  firebase-vertexai-quickstart/app/src/main/res/xml/data_extraction_rules.xml
  firebase-vertexai-quickstart/build.gradle.kts
  firebase-vertexai-quickstart/gradle.properties
  firebase-vertexai-quickstart/gradle/wrapper/gradle-wrapper.jar
  firebase-vertexai-quickstart/gradle/wrapper/gradle-wrapper.properties
  firebase-vertexai-quickstart/gradlew
  firebase-vertexai-quickstart/gradlew.bat
  firebase-vertexai-quickstart/quickstart.zip
  firebase-vertexai-quickstart/screenshots/screenshots.png
  firebase-vertexai-quickstart/settings.gradle.kts
Labels: size/XXL, no-changelog

#5944 Add responseMimeType support
  firebase-vertexai/CHANGELOG.md
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/internal/util/conversions.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/GenerationConfig.kt
Labels: size/S

#5950 change text behavior to concatonate all text parts
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/GenerateContentResponse.kt
Labels: size/XS

#5949 Add filedata support in vertex
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/internal/util/conversions.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/Content.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/Part.kt
Labels: size/S

#5952 Rename Vertex exception
  firebase-vertexai/CHANGELOG.md
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/GenerativeModel.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/Exceptions.kt
Labels: size/M

#5954 Include Preview disclaimer in README
  firebase-vertexai/README.md
Labels: size/XS

#5955 Vertex Javadocs/Kotlindocs fixes
  firebase-vertexai/CHANGELOG.md
  firebase-vertexai/firebase-vertexai.gradle.kts
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/Chat.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/FirebaseVertexAI.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/GenerativeModel.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/java/ChatFutures.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/java/GenerativeModelFutures.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/BlockThreshold.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/Candidate.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/Content.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/Exceptions.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/FunctionCallingConfig.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/FunctionDeclarations.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/GenerationConfig.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/Part.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/PromptFeedback.kt
Labels: size/L

#5958 Vertex ai
  firebase-vertexai/CHANGELOG.md
  firebase-vertexai/README.md
  firebase-vertexai/firebase-vertexai.gradle.kts
  firebase-vertexai/gradle.properties
  firebase-vertexai/src/main/AndroidManifest.xml
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/Chat.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/FirebaseVertexAI.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/FirebaseVertexAIMultiResourceComponent.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/FirebaseVertexAIRegistrar.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/GenerativeModel.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/internal/util/conversions.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/internal/util/kotlin.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/java/ChatFutures.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/java/GenerativeModelFutures.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/BlockThreshold.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/Candidate.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/Content.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/CountTokensResponse.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/Exceptions.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/FunctionCallingConfig.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/FunctionDeclarations.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/FunctionParameter.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/GenerateContentResponse.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/GenerationConfig.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/HarmCategory.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/HarmProbability.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/HarmSeverity.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/Part.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/PromptFeedback.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/RequestOptions.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/SafetySetting.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/Tool.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/ToolConfig.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/Type.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/UsageMetadata.kt
  subprojects.cfg
Labels: size/XXL, cla: yes

#5946 Add +/- time zone support in TimestampSerializer
  firebase-dataconnect/src/main/kotlin/com/google/firebase/dataconnect/serializers/TimestampSerializer.kt
  firebase-dataconnect/src/test/kotlin/com/google/firebase/dataconnect/serializers/TimestampSerializerUnitTest.kt
Labels: size/L, no-changelog

#5933 add gMaven check to prevent an artifact from unintentionally exiting …
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/FirebaseLibraryExtension.java
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/PublishingPlugin.kt
  firebase-appdistribution-api/firebase-appdistribution-api.gradle
  firebase-appdistribution-api/ktx/ktx.gradle
  firebase-appdistribution/firebase-appdistribution.gradle
  firebase-vertexai/firebase-vertexai.gradle.kts
Labels: size/S

#5963 firebase-dataconnect.gradle.kts: set previewMode = "alpha"
  firebase-dataconnect/firebase-dataconnect.gradle.kts
Labels: size/XS

#5961 delete segmentation
  firebase-segmentation/api.txt
  firebase-segmentation/firebase-segmentation.gradle
  firebase-segmentation/gradle.properties
  firebase-segmentation/lint.xml
  firebase-segmentation/src/main/AndroidManifest.xml
  firebase-segmentation/src/main/java/com/google/firebase/segmentation/FirebaseSegmentation.java
  firebase-segmentation/src/main/java/com/google/firebase/segmentation/FirebaseSegmentationRegistrar.java
  firebase-segmentation/src/main/java/com/google/firebase/segmentation/SetCustomInstallationIdException.java
  firebase-segmentation/src/main/java/com/google/firebase/segmentation/Utils.java
  firebase-segmentation/src/main/java/com/google/firebase/segmentation/local/CustomInstallationIdCache.java
  firebase-segmentation/src/main/java/com/google/firebase/segmentation/local/CustomInstallationIdCacheEntryValue.java
  firebase-segmentation/src/main/java/com/google/firebase/segmentation/remote/SegmentationServiceClient.java
  firebase-segmentation/src/test/java/com/google/firebase/segmentation/FirebaseSegmentationRegistrarTest.java
  firebase-segmentation/src/test/java/com/google/firebase/segmentation/FirebaseSegmentationTest.java
  firebase-segmentation/src/test/java/com/google/firebase/segmentation/TestOnCompleteListener.java
  firebase-segmentation/src/test/java/com/google/firebase/segmentation/local/CustomInstallationIdCacheTest.java
  subprojects.cfg
Labels: size/XXL

#5968 add vertexai to firebase_tutorial_bundle generator
  buildSrc/src/main/java/com/google/firebase/gradle/bomgenerator/RecipeVersionWriter.java
Labels: size/XS

#5970 Comment the equals() and hashCode() methods in GeneratedConnector and GeneratedConnector
  firebase-dataconnect/src/main/kotlin/com/google/firebase/dataconnect/generated/GeneratedConnector.kt
  firebase-dataconnect/src/main/kotlin/com/google/firebase/dataconnect/generated/GeneratedOperation.kt
Labels: size/S

#5974 Make the settings cache load lazy, improving init time
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/settings/RemoteSettings.kt
Labels: size/XS, no-changelog, main-merge-ack

#5969 Fix health metrics failures
  health-metrics/apk-size/apk-size.gradle
  health-metrics/apk-size/app/build.gradle
  health-metrics/apk-size/app/default.gradle
  health-metrics/apk-size/gradle/wrapper/gradle-wrapper.jar
  health-metrics/apk-size/gradle/wrapper/gradle-wrapper.properties
  health-metrics/benchmark/template/build.gradle
Labels: size/S, no-changelog

#5976 DateSerializer.kt: fix time zone issues
  firebase-dataconnect/connectors/src/androidTest/kotlin/com/google/firebase/dataconnect/connectors/demo/ListVariablesAndDataIntegrationTest.kt
  firebase-dataconnect/connectors/src/androidTest/kotlin/com/google/firebase/dataconnect/connectors/demo/ScalarVariablesAndDataIntegrationTest.kt
  firebase-dataconnect/src/main/kotlin/com/google/firebase/dataconnect/FirebaseDataConnect.kt
  firebase-dataconnect/src/main/kotlin/com/google/firebase/dataconnect/serializers/DateSerializer.kt
  firebase-dataconnect/testutil/src/main/kotlin/com/google/firebase/dataconnect/testutil/DateTimeTestUtils.kt
Labels: size/L

#5981 Update scorecards.yml
  .github/workflows/scorecards.yml
Labels: size/M

#5984 Fix compatibility issues with Crashlytics
  firebase-crashlytics/CHANGELOG.md
  firebase-crashlytics/firebase-crashlytics.gradle
Labels: size/XS, main-merge-ack

#5986 Improve cold initialization time
  firebase-crashlytics/CHANGELOG.md
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/SessionReportingCoordinatorTest.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/IdManager.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/SessionReportingCoordinator.java
Labels: size/S, main-merge-ack

#5988 Add namespace to firebase-appdistribution/test-app/test-app.gradle
  firebase-appdistribution/test-app/test-app.gradle
Labels: size/XS

#5990 Annotate FDL public API
  firebase-dynamic-links/src/main/java/com/google/firebase/dynamiclinks/DynamicLink.java
  firebase-dynamic-links/src/main/java/com/google/firebase/dynamiclinks/FirebaseDynamicLinks.java
  firebase-dynamic-links/src/main/java/com/google/firebase/dynamiclinks/FirebaseDynamicLinks.kt
  firebase-dynamic-links/src/main/java/com/google/firebase/dynamiclinks/PendingDynamicLinkData.java
  firebase-dynamic-links/src/main/java/com/google/firebase/dynamiclinks/ShortDynamicLink.java
Labels: size/XL

#5994 Update appdistribution* changelog entries
  firebase-appdistribution-api/CHANGELOG.md
  firebase-appdistribution/CHANGELOG.md
Labels: size/XS

#5995 Update versions in common, components & vertexai
  firebase-common/gradle.properties
  firebase-components/gradle.properties
  firebase-vertexai/gradle.properties
Labels: size/S

#5971 wire through new exception type from common
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/Exceptions.kt
Labels: size/XS

#5996 Change default port of useEmulator() to 9399 (was 9510).
  firebase-dataconnect/emulator/emulator_noauth.sh
  firebase-dataconnect/src/main/kotlin/com/google/firebase/dataconnect/FirebaseDataConnect.kt
Labels: size/XS

#5991 Update the URL for the Metric Service
  ci/fireci/fireciplugins/binary_size.py
  ci/fireci/fireciplugins/coverage.py
  ci/fireci/fireciplugins/macrobenchmark/commands.py
Labels: size/XS

#6002 Adjust FDL deprecation wording.
  firebase-dynamic-links/src/main/java/com/google/firebase/dynamiclinks/DynamicLink.java
  firebase-dynamic-links/src/main/java/com/google/firebase/dynamiclinks/FirebaseDynamicLinks.java
  firebase-dynamic-links/src/main/java/com/google/firebase/dynamiclinks/PendingDynamicLinkData.java
  firebase-dynamic-links/src/main/java/com/google/firebase/dynamiclinks/ShortDynamicLink.java
Labels: size/L

#6004 Add dataconnect to ignore in the bom
  buildSrc/src/main/java/com/google/firebase/gradle/bomgenerator/BomGeneratorTask.java
Labels: size/XS

#6005 DataConnectGrpcRPCs.kt: fix strict mode violations when initializing grpc
  firebase-dataconnect/src/main/kotlin/com/google/firebase/dataconnect/FirebaseDataConnect.kt
  firebase-dataconnect/src/main/kotlin/com/google/firebase/dataconnect/core/DataConnectGrpcRPCs.kt
Labels: size/M

#6006 Improve debug logging of GRPC requests and responses
  firebase-dataconnect/src/main/kotlin/com/google/firebase/dataconnect/FirebaseDataConnect.kt
  firebase-dataconnect/src/main/kotlin/com/google/firebase/dataconnect/core/DataConnectGrpcClient.kt
  firebase-dataconnect/src/main/kotlin/com/google/firebase/dataconnect/util/ProtoUtil.kt
Labels: size/L
