Repository firebase/firebase-android-sdk, pull requests merged in 2024-01, with the labels that each got.

#5624 Remove list of SDKs from README.md
  README.md
Labels: size/M

#5619 Added @Deprecated annotation on unused crashlytics from ktx api.
  firebase-crashlytics/CHANGELOG.md
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/ktx/FirebaseCrashlytics.kt
Labels: size/XS

#5628 Revert "Added @Deprecated annotation on unused crashlytics from ktx api."
  firebase-crashlytics/CHANGELOG.md
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/ktx/FirebaseCrashlytics.kt
Labels: size/XS

#5579 Restore Sessions test cases
  firebase-sessions/test-app/src/androidTest/kotlin/com/google/firebase/testing/sessions/FirebaseSessionsIntegrationTest.kt
  firebase-sessions/test-app/src/main/kotlin/com/google/firebase/testing/sessions/FirstFragment.kt
  firebase-sessions/test-app/src/main/kotlin/com/google/firebase/testing/sessions/SecondActivity.kt
  firebase-sessions/test-app/src/main/kotlin/com/google/firebase/testing/sessions/TestApplication.kt
Labels: size/L, no-changelog, main-merge-ack

#5633 Handle corruption in DataStore Preferences gracefully
  firebase-sessions/CHANGELOG.md
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionDatastore.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/settings/SessionsSettings.kt
Labels: size/M, main-merge-ack

#5636 add release notes to crashlytics and pin config-interop version
  firebase-crashlytics/CHANGELOG.md
  firebase-crashlytics/firebase-crashlytics.gradle
Labels: size/XS

#5634 Firestore: Small Count API documentation improvements
  firebase-firestore/src/main/java/com/google/firebase/firestore/AggregateSource.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/Query.java
Labels: size/S, api: firestore, no-changelog, main-merge-ack

#5649 Deprecate Dynamic Links
  firebase-dynamic-links/README.md
Labels: size/XS, no-changelog

#5653 Fix package prefix removal in doc generation
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/DackkaGenerationTask.kt
Labels: size/XS

#5654 Migrate macos runners to ubuntu
  .github/workflows/build-release-artifacts.yml
  .github/workflows/diff-javadoc.yml
Labels: size/XS

#5660 Add test coverage for bundle to verify the support for empty array and map
  firebase-firestore/src/test/java/com/google/firebase/firestore/bundle/BundleReaderTest.java
Labels: size/S, no-changelog, main-merge-ack

#5665 Migrate to a supported version of gcloud action
  .github/workflows/ci_tests.yml
  .github/workflows/config-e2e.yml
  .github/workflows/fireperf-e2e.yml
  .github/workflows/health-metrics.yml
  .github/workflows/sessions-e2e.yml
  .github/workflows/smoke-tests.yml
Labels: size/S

#5661 Misc build fixes
  appcheck/firebase-appcheck-safetynet/firebase-appcheck-safetynet.gradle
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/Metalava.kt
  firebase-config/bandwagoner/bandwagoner.gradle
  firebase-perf/dev-app/dev-app.gradle
  firebase-perf/e2e-app/e2e-app.gradle
Labels: size/XS

#5672 Fix perf devapp namespace
  firebase-perf/dev-app/dev-app.gradle
Labels: size/XS

#5666 Missing action upgrades
  .github/workflows/ci_tests.yml
  .github/workflows/config-e2e.yml
  .github/workflows/fireperf-e2e.yml
  .github/workflows/health-metrics.yml
  .github/workflows/sessions-e2e.yml
  .github/workflows/smoke-tests.yml
Labels: size/S

#5631 Bump internal dependencies
  appcheck/firebase-appcheck/CHANGELOG.md
  appcheck/firebase-appcheck/firebase-appcheck.gradle
  firebase-abt/CHANGELOG.md
  firebase-abt/firebase-abt.gradle
  firebase-appdistribution-api/CHANGELOG.md
  firebase-appdistribution/CHANGELOG.md
  firebase-appdistribution/firebase-appdistribution.gradle
  firebase-common/data-collection-tests/data-collection-tests.gradle.kts
  firebase-config-interop/CHANGELOG.md
  firebase-config/CHANGELOG.md
  firebase-config/firebase-config.gradle.kts
  firebase-crashlytics/CHANGELOG.md
  firebase-crashlytics/firebase-crashlytics.gradle
  firebase-datatransport/CHANGELOG.md
  firebase-datatransport/firebase-datatransport.gradle
  firebase-firestore/CHANGELOG.md
  firebase-messaging/CHANGELOG.md
  firebase-messaging/firebase-messaging.gradle
  firebase-ml-modeldownloader/CHANGELOG.md
  firebase-ml-modeldownloader/firebase-ml-modeldownloader.gradle
  firebase-perf/CHANGELOG.md
  firebase-perf/firebase-perf.gradle
  firebase-sessions/CHANGELOG.md
  firebase-sessions/firebase-sessions.gradle.kts
  gradle/libs.versions.toml
Labels: size/M

#5686 Add missing changelog entries for m143
  appcheck/firebase-appcheck-debug-testing/CHANGELOG.md
  appcheck/firebase-appcheck-debug/CHANGELOG.md
  appcheck/firebase-appcheck-playintegrity/CHANGELOG.md
Labels: size/XS

#5626 Handle bridge methods while mapping
  firebase-database/CHANGELOG.md
  firebase-database/src/main/java/com/google/firebase/database/core/utilities/encoding/CustomClassMapper.java
  firebase-database/src/test/java/com/google/firebase/database/KotlinEntities.kt
  firebase-database/src/test/java/com/google/firebase/database/MapperTest.java
  firebase-firestore/CHANGELOG.md
  firebase-firestore/src/main/java/com/google/firebase/firestore/util/CustomClassMapper.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/util/KotlinEntities.kt
  firebase-firestore/src/test/java/com/google/firebase/firestore/util/MapperTest.java
Labels: size/L
