Repository firebase/firebase-android-sdk, pull requests merged in 2024-04, with the labels that each got.

#5818 RandomUtil added to firebase-common
  firebase-common/CHANGELOG.md
  firebase-common/src/main/java/com/google/firebase/util/RandomUtil.kt
  firebase-common/src/test/java/com/google/firebase/util/RandomUtilTest.kt
Labels: size/L, no-changelog, main-merge-ack

#5828 Update vertexai gradle build file
  firebase-vertexai/firebase-vertexai.gradle.kts
Labels: size/XS

#5829 Format fixes for vertex code
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/FirebaseVertexAI.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/internal/util/conversions.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/FunctionDeclarations.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/FunctionParameter.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/Tool.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/Type.kt
Labels: size/L

#5830 Set the right apiClient value
  firebase-vertexai/gradle.properties
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/GenerativeModel.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/UsageMetadata.kt
Labels: size/S

#5834 Remove location and apiVersion from user visible configuration
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/FirebaseVertexAI.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/RequestOptions.kt
Labels: size/S

#5835 Add support for appcheck
  firebase-vertexai/firebase-vertexai.gradle.kts
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/FirebaseVertexAI.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/FirebaseVertexAIRegistrar.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/GenerativeModel.kt
Labels: size/M

#5837 Add support for constrain decoding
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/FirebaseVertexAI.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/GenerativeModel.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/internal/util/conversions.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/FunctionCallingConfig.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/ToolConfig.kt
Labels: size/L

#5842 Move Timestamp to common
  firebase-common/api.txt
  firebase-common/src/main/java/com/google/firebase/Timestamp.java
  firebase-common/src/main/java/com/google/firebase/util/package-info.java
  firebase-common/src/test/java/com/google/firebase/TimestampTest.java
  firebase-firestore/api.txt
  firebase-firestore/firebase-firestore.gradle
  subprojects.cfg
Labels: size/M, no-changelog

#5846 Remove Timestamp workarounds from doc generation
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/DackkaPlugin.kt
Labels: size/M, no-changelog

#5841 Add SystemInstruction
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/FirebaseVertexAI.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/GenerativeModel.kt
Labels: size/S

#5844 use the same parameter order as Google AI
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/FirebaseVertexAI.kt
Labels: size/XS

#5838 improve java interoperability
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/FirebaseVertexAI.kt
Labels: size/XS

#5848 Update vertexai's common dependency
  firebase-vertexai/firebase-vertexai.gradle.kts
Labels: size/XS

#5854 Updating changelog
  firebase-inappmessaging-display/CHANGELOG.md
  firebase-inappmessaging/CHANGELOG.md
Labels: size/S

#5851 Major bump all SDKs
  appcheck/firebase-appcheck-debug-testing/gradle.properties
  appcheck/firebase-appcheck-debug/gradle.properties
  appcheck/firebase-appcheck-interop/gradle.properties
  appcheck/firebase-appcheck-playintegrity/gradle.properties
  appcheck/firebase-appcheck/gradle.properties
  firebase-abt/gradle.properties
  firebase-annotations/gradle.properties
  firebase-appdistribution-api/gradle.properties
  firebase-appdistribution/gradle.properties
  firebase-common/gradle.properties
  firebase-components/gradle.properties
  firebase-config-interop/gradle.properties
  firebase-config/gradle.properties
  firebase-crashlytics-ndk/gradle.properties
  firebase-crashlytics/gradle.properties
  firebase-database-collection/gradle.properties
  firebase-database/gradle.properties
  firebase-datatransport/gradle.properties
  firebase-dynamic-links/gradle.properties
  firebase-firestore/gradle.properties
  firebase-functions/gradle.properties
  firebase-inappmessaging-display/gradle.properties
  firebase-inappmessaging/gradle.properties
  firebase-installations-interop/gradle.properties
  firebase-installations/gradle.properties
  firebase-messaging-directboot/gradle.properties
  firebase-messaging/gradle.properties
  firebase-ml-modeldownloader/gradle.properties
  firebase-perf/gradle.properties
  firebase-sessions/gradle.properties
  firebase-storage/gradle.properties
  transport/transport-api/gradle.properties
  transport/transport-backend-cct/gradle.properties
  transport/transport-runtime/gradle.properties
Labels: size/M, no-changelog

#5861 ignore vertex ai
  buildSrc/src/main/java/com/google/firebase/gradle/bomgenerator/BomGeneratorTask.java
Labels: size/XS

#5696 Remove unnecessary custom shadow annotations.
  firebase-messaging/src/test/java/com/google/firebase/messaging/GmsRpcRoboTest.java
Labels: size/XS, no-changelog

#5717 Switch Firelog to use the new TransportBackend.
  firebase-messaging/CHANGELOG.md
  firebase-messaging/firebase-messaging.gradle
  firebase-messaging/src/main/java/com/google/firebase/messaging/FirebaseMessaging.java
  firebase-messaging/src/main/java/com/google/firebase/messaging/FirebaseMessagingRegistrar.java
  firebase-messaging/src/test/java/com/google/firebase/messaging/FirebaseMessagingRegistrarRoboTest.java
  firebase-messaging/src/test/java/com/google/firebase/messaging/FirebaseMessagingRoboTest.java
  firebase-messaging/src/test/java/com/google/firebase/messaging/MessagingAnalyticsRoboTest.java
Labels: size/M

#5840 Refactor Timestamp
  firebase-common/api.txt
  firebase-common/src/main/java/com/google/firebase/Timestamp.java
  firebase-common/src/main/java/com/google/firebase/Timestamp.kt
Labels: size/L, no-changelog

#5853 Support for java.time.Instant in Firebase Timestamp
  firebase-common/api.txt
  firebase-common/src/main/java/com/google/firebase/Timestamp.kt
  firebase-common/src/test/java/com/google/firebase/TimestampTest.java
  firebase-firestore/CHANGELOG.md
Labels: size/S

#5833 Try catch for datastore write
  firebase-sessions/CHANGELOG.md
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionDatastore.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/settings/SettingsCache.kt
Labels: size/S

#5876 Make license optional and startIndex default 0 in CitationMetadata
  firebase-vertexai/gradle.properties
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/Candidate.kt
Labels: size/XS

#5862 Remove SafetyNet
  appcheck/firebase-appcheck-debug-testing/firebase-appcheck-debug-testing.gradle
  appcheck/firebase-appcheck-debug-testing/src/test/java/com/google/firebase/appcheck/debug/testing/DebugAppCheckTestHelperTest.java
  appcheck/firebase-appcheck-safetynet/CHANGELOG.md
  appcheck/firebase-appcheck-safetynet/api.txt
  appcheck/firebase-appcheck-safetynet/firebase-appcheck-safetynet.gradle
  appcheck/firebase-appcheck-safetynet/gradle.properties
  appcheck/firebase-appcheck-safetynet/src/main/AndroidManifest.xml
  appcheck/firebase-appcheck-safetynet/src/main/java/com/google/firebase/appcheck/safetynet/FirebaseAppCheckSafetyNetRegistrar.java
  appcheck/firebase-appcheck-safetynet/src/main/java/com/google/firebase/appcheck/safetynet/SafetyNetAppCheckProviderFactory.java
  appcheck/firebase-appcheck-safetynet/src/main/java/com/google/firebase/appcheck/safetynet/internal/ExchangeSafetyNetTokenRequest.java
  appcheck/firebase-appcheck-safetynet/src/main/java/com/google/firebase/appcheck/safetynet/internal/SafetyNetAppCheckProvider.java
  appcheck/firebase-appcheck-safetynet/src/main/java/com/google/firebase/appcheck/safetynet/internal/package-info.java
  appcheck/firebase-appcheck-safetynet/src/test/java/com/google/firebase/appcheck/safetynet/FirebaseAppCheckSafetyNetRegistrarTest.java
  appcheck/firebase-appcheck-safetynet/src/test/java/com/google/firebase/appcheck/safetynet/SafetyNetAppCheckProviderFactoryTest.java
  appcheck/firebase-appcheck-safetynet/src/test/java/com/google/firebase/appcheck/safetynet/internal/ExchangeSafetyNetTokenRequestTest.java
  appcheck/firebase-appcheck-safetynet/src/test/java/com/google/firebase/appcheck/safetynet/internal/SafetyNetAppCheckProviderTest.java
  appcheck/firebase-appcheck/CHANGELOG.md
  appcheck/firebase-appcheck/src/main/java/com/google/firebase/appcheck/internal/NetworkClient.java
  appcheck/firebase-appcheck/src/test/java/com/google/firebase/appcheck/internal/NetworkClientTest.java
  appcheck/firebase-appcheck/test-app/src/main/java/com/googletest/firebase/appcheck/MainActivity.java
  appcheck/firebase-appcheck/test-app/src/main/res/values/strings.xml
  appcheck/firebase-appcheck/test-app/test-app.gradle
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/SdkUtil.kt
  docs/make_release_notes.py
  subprojects.cfg
Labels: size/XXL

#5878 Log analytics for proxied notifications.
  firebase-messaging/CHANGELOG.md
  firebase-messaging/firebase-messaging.gradle
  firebase-messaging/src/main/java/com/google/firebase/messaging/FirebaseMessaging.java
  firebase-messaging/src/main/java/com/google/firebase/messaging/GmsRpc.java
  firebase-messaging/src/main/java/com/google/firebase/messaging/ProxyNotificationPreferences.java
  firebase-messaging/src/test/java/com/google/firebase/messaging/FirebaseMessagingRoboTest.java
  firebase-messaging/src/test/java/com/google/firebase/messaging/GmsRpcRoboTest.java
  firebase-messaging/src/test/java/com/google/firebase/messaging/ProxyNotificationPreferencesRoboTest.java
Labels: size/XL

#5880 Add support for HarmSeverity
  firebase-vertexai/firebase-vertexai.gradle.kts
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/internal/util/conversions.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/Candidate.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/HarmSeverity.kt
Labels: size/M

#5882 Added keep rule for Crashlytics Build ID resource names
  firebase-crashlytics/CHANGELOG.md
  firebase-crashlytics/src/main/res/raw/firebase_crashlytics_keep.xml
Labels: size/S

#5884 Safely handle unbinding service connection
  firebase-sessions/CHANGELOG.md
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionLifecycleServiceBinder.kt
Labels: size/S

#5887 generate release should use java 17
  .github/workflows/create_releases.yml
Labels: size/XS

#5891 Add build setting to generate IDL classes for FDL and transport-runtime
  firebase-dynamic-links/firebase-dynamic-links.gradle
  subprojects.cfg
  transport/transport-runtime/transport-runtime.gradle
Labels: size/XS

#5895 Fix copyRootGoogleServices task
  appcheck/firebase-appcheck-debug-testing/firebase-appcheck-debug-testing.gradle
  appcheck/firebase-appcheck/test-app/test-app.gradle
  buildSrc/build.gradle.kts
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/BaseFirebaseLibraryPlugin.kt
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/CopyGoogleServicesPlugin.kt
  buildSrc/src/main/java/com/google/firebase/gradle/plugins/FirebaseLibraryPlugin.kt
  firebase-appdistribution/test-app/test-app.gradle
  firebase-config/bandwagoner/bandwagoner.gradle
  firebase-config/test-app/test-app.gradle.kts
  firebase-database/firebase-database.gradle.kts
  firebase-firestore/firebase-firestore.gradle
  firebase-functions/firebase-functions.gradle.kts
  firebase-ml-modeldownloader/firebase-ml-modeldownloader.gradle
  firebase-perf/dev-app/README.md
  firebase-perf/dev-app/dev-app.gradle
  firebase-perf/e2e-app/README.md
  firebase-perf/e2e-app/e2e-app.gradle
  firebase-sessions/test-app/test-app.gradle.kts
  firebase-storage/firebase-storage.gradle
  firebase-storage/test-app/test-app.gradle
  gradle/googleServices.gradle
Labels: size/L, no-changelog

#5901 Bump common dependency in ml-data-collection-tests
  firebase-ml-modeldownloader/ml-data-collection-tests/ml-data-collection-tests.gradle
Labels: size/XS

#5899 Upgrade lint version to resolve kotlin test error
  gradle/libs.versions.toml
Labels: size/XS

#5900 Remove jvmToolchain declaration in firebase-config:test-app
  firebase-config/test-app/test-app.gradle.kts
  firebase-sessions/test-app/test-app.gradle.kts
Labels: size/XS

#5904 Update checkout action and java-setup version
  .github/workflows/api-information.yml
  .github/workflows/build-release-artifacts.yml
  .github/workflows/build-src-check.yml
  .github/workflows/changelog.yml
  .github/workflows/check-head-dependencies.yml
  .github/workflows/ci_tests.yml
  .github/workflows/config-e2e.yml
  .github/workflows/copyright-check.yml
  .github/workflows/create_releases.yml
  .github/workflows/diff-javadoc.yml
  .github/workflows/fireci.yml
  .github/workflows/fireperf-e2e.yml
  .github/workflows/health-metrics.yml
  .github/workflows/jekyll-gh-pages.yml
  .github/workflows/make-bom.yml
  .github/workflows/post_release_cleanup.yml
  .github/workflows/private-mirror-sync.yml
  .github/workflows/release-note-changes.yml
  .github/workflows/scorecards.yml
  .github/workflows/semver-check.yml
  .github/workflows/sessions-e2e.yml
  .github/workflows/smoke-tests.yml
  .github/workflows/update-cpp-sdk-on-release.yml
  .github/workflows/validate-dependencies.yml
  .github/workflows/version-check.yml
Labels: size/L

#5909 Refdocs review
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/Chat.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/FirebaseVertexAI.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/GenerativeModel.kt
Labels: size/M

#5910 Additional refdocs changes for vertex
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/FirebaseVertexAI.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/GenerativeModel.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/Candidate.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/Content.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/CountTokensResponse.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/Exceptions.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/FunctionDeclarations.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/Part.kt
Labels: size/L

#5893 Update config-e2e.yml
  .github/workflows/config-e2e.yml
Labels: size/XS

#5913 fix smoke tests
  smoke-tests/build.gradle
  smoke-tests/src/main/AndroidManifest.xml
Labels: size/S, cla: yes
