Repository firebase/firebase-android-sdk, pull requests merged in 2024-03, with the labels that each got.

#5758 Add support for experimentid and cookie in transport
  transport/transport-api/CHANGELOG.md
  transport/transport-api/gradle.properties
  transport/transport-api/src/main/java/com/google/android/datatransport/Event.java
  transport/transport-api/src/main/java/com/google/android/datatransport/EventContext.java
  transport/transport-backend-cct/CHANGELOG.md
  transport/transport-backend-cct/gradle.properties
  transport/transport-backend-cct/src/main/java/com/google/android/datatransport/cct/CctTransportBackend.java
  transport/transport-backend-cct/src/main/java/com/google/android/datatransport/cct/internal/ExperimentIds.java
  transport/transport-backend-cct/src/main/java/com/google/android/datatransport/cct/internal/LogEvent.java
  transport/transport-backend-cct/src/test/java/com/google/android/datatransport/cct/CctTransportBackendTest.java
  transport/transport-backend-cct/src/test/java/com/google/android/datatransport/cct/internal/LogRequestTest.java
  transport/transport-backend-cct/src/test/proto/google/cct/google_cct.proto
  transport/transport-runtime/CHANGELOG.md
  transport/transport-runtime/gradle.properties
  transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/EventInternal.java
  transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/TransportContext.java
  transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/TransportRuntime.java
  transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/backends/BackendRequest.java
  transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/scheduling/persistence/SQLiteEventStore.java
  transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/scheduling/persistence/SchemaManager.java
  transport/transport-runtime/src/test/java/com/google/android/datatransport/runtime/TransportRuntimeTest.java
  transport/transport-runtime/src/test/java/com/google/android/datatransport/runtime/scheduling/persistence/SchemaManagerMigrationTest.java
  transport/transport-runtime/src/test/java/com/google/android/datatransport/runtime/scheduling/persistence/SchemaManagerTest.java
  transport/transport-runtime/src/test/java/com/google/android/datatransport/runtime/scheduling/persistence/StateSimulations.java
Labels: size/L

#5753 Revert "Disconnect from RC real-time server when app is backgrounded."
  firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigAutoFetch.java
  firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigRealtimeHandler.java
  firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigRealtimeHttpClient.java
  firebase-config/src/test/java/com/google/firebase/remoteconfig/FirebaseRemoteConfigTest.java
Labels: size/L

#5762 Add Remote Config changelog for PR #5753
  firebase-config/CHANGELOG.md
Labels: size/XS, main-merge-ack

#5770 Remove unused transport field
  transport/transport-backend-cct/src/main/java/com/google/android/datatransport/cct/CctTransportBackend.java
  transport/transport-backend-cct/src/main/java/com/google/android/datatransport/cct/internal/LogEvent.java
  transport/transport-backend-cct/src/test/java/com/google/android/datatransport/cct/CctTransportBackendTest.java
  transport/transport-backend-cct/src/test/java/com/google/android/datatransport/cct/internal/LogRequestTest.java
  transport/transport-backend-cct/src/test/proto/google/cct/google_cct.proto
Labels: size/S

#5690 Snapshot listener source from cache
  firebase-firestore/CHANGELOG.md
  firebase-firestore/api.txt
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/SnapshotListenerSourceTest.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/DocumentReference.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/ListenSource.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/Query.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/SnapshotListenOptions.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/EventManager.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/QueryListener.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/SyncEngine.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/core/EventManagerTest.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/spec/SpecTestCase.java
  firebase-firestore/src/test/resources/json/listen_source_spec_test.json
Labels: size/XXL, do-not-merge/work-in-progress

#5777 Handle when the session lifecycle service binding fails
  firebase-sessions/firebase-sessions.gradle.kts
  firebase-sessions/src/androidTest/kotlin/com/google/firebase/sessions/SessionLifecycleServiceBinderTest.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionLifecycleServiceBinder.kt
Labels: size/M, no-changelog, main-merge-ack

#5784 Add test cases for when fid or authToken are null
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/InstallationId.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionFirelogPublisher.kt
  firebase-sessions/src/test/kotlin/com/google/firebase/sessions/SessionFirelogPublisherTest.kt
  firebase-sessions/src/test/kotlin/com/google/firebase/sessions/testing/FakeFirebaseInstallations.kt
Labels: size/M, no-changelog, main-merge-ack

#5773 Add support for new batching
  transport/transport-backend-cct/src/main/java/com/google/android/datatransport/cct/CctTransportBackend.java
  transport/transport-backend-cct/src/test/java/com/google/android/datatransport/cct/CctTransportBackendTest.java
  transport/transport-runtime/src/androidTest/java/com/google/android/datatransport/runtime/UploaderIntegrationTest.java
  transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/scheduling/jobscheduling/AlarmManagerScheduler.java
  transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/scheduling/jobscheduling/JobInfoScheduler.java
  transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/scheduling/jobscheduling/SchedulerConfig.java
  transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/scheduling/jobscheduling/Uploader.java
  transport/transport-runtime/src/test/java/com/google/android/datatransport/runtime/scheduling/jobscheduling/AlarmManagerSchedulerTest.java
  transport/transport-runtime/src/test/java/com/google/android/datatransport/runtime/scheduling/jobscheduling/JobInfoSchedulerTest.java
  transport/transport-runtime/src/test/java/com/google/android/datatransport/runtime/scheduling/jobscheduling/UploaderTest.java
Labels: size/L

#5787 Add sessions to crashlytics library group.
  firebase-sessions/firebase-sessions.gradle.kts
Labels: size/XS

#5788 m144_1 mergeback
  firebase-config/CHANGELOG.md
  firebase-config/gradle.properties
Labels: size/S

#5789 Stop mocking EventInternal
  transport/transport-runtime/src/test/java/com/google/android/datatransport/runtime/scheduling/jobscheduling/AlarmManagerSchedulerTest.java
  transport/transport-runtime/src/test/java/com/google/android/datatransport/runtime/scheduling/jobscheduling/JobInfoSchedulerTest.java
Labels: size/M

#5792 Add missing changelog entries
  firebase-crashlytics-ndk/CHANGELOG.md
  firebase-crashlytics/CHANGELOG.md
  firebase-crashlytics/firebase-crashlytics.gradle
Labels: size/XS

#5793 Cleanup Uploader tests
  transport/transport-runtime/src/test/java/com/google/android/datatransport/runtime/scheduling/jobscheduling/UploaderTest.java
  transport/transport-runtime/src/test/java/com/google/android/datatransport/runtime/scheduling/persistence/InMemoryEventStore.java
Labels: size/S

#5796 Fix smoke test failures
  smoke-tests/build.gradle
Labels: size/XS, no-changelog

#5799 Add usage metadata support
  firebase-vertex/src/main/kotlin/com/google/firebase/vertex/FirebaseVertex.kt
  firebase-vertex/src/main/kotlin/com/google/firebase/vertex/internal/util/conversions.kt
  firebase-vertex/src/main/kotlin/com/google/firebase/vertex/type/GenerateContentResponse.kt
  firebase-vertex/src/main/kotlin/com/google/firebase/vertex/type/UsageMetadata.kt
Labels: size/M

#5800 Add missing parameters to model builder
  firebase-vertex/src/main/kotlin/com/google/firebase/vertex/FirebaseVertex.kt
Labels: size/S

#5804 Fix: FIAM Bad token exception (b/330727156)
  firebase-inappmessaging-display/CHANGELOG.md
  firebase-inappmessaging-display/src/main/java/com/google/firebase/inappmessaging/display/internal/FiamWindowManager.java
  firebase-inappmessaging/CHANGELOG.md
Labels: size/XS

#5805 Fix flaky test
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/analytics/BlockingAnalyticsEventLoggerTest.java
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/FirebaseSessions.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/FirebaseSessionsRegistrar.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionLifecycleClient.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionLifecycleServiceBinder.kt
  firebase-sessions/src/test/kotlin/com/google/firebase/sessions/SessionLifecycleClientTest.kt
  firebase-sessions/src/test/kotlin/com/google/firebase/sessions/SessionsActivityLifecycleCallbacksTest.kt
Labels: size/M, no-changelog, main-merge-ack

#5809 Add kotlindocs fo the entry point of the SDK
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/FirebaseVertexAI.kt
Labels: size/S

#5808 Gracefully handle unsupported parts returned by the model
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/internal/util/conversions.kt
Labels: size/XS

#5810 Use long.compare since we are on API 19 now.
  firebase-firestore/src/main/java/com/google/cloud/datastore/core/number/NumberComparisonHelper.java
Labels: size/S

#5813 Add missing functionality necessary to get function calling to work
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/Chat.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/internal/util/conversions.kt
Labels: size/S

#5814 Bump futures dependency
  firebase-vertexai/firebase-vertexai.gradle.kts
Labels: size/XS

#5811 add function calling to vertex
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/Chat.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/FirebaseVertexAI.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/GenerativeModel.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/internal/util/conversions.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/FunctionDeclarations.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/FunctionParameter.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/GenerateContentResponse.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/Part.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/Tool.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/Type.kt
Labels: size/L

#5812 Force validation or rotation of FIDs
  firebase-crashlytics/CHANGELOG.md
  firebase-crashlytics/ktx/src/androidTest/kotlin/com/google/firebase/crashlytics/ktx/CrashlyticsTests.kt
  firebase-crashlytics/src/androidTest/AndroidManifest.xml
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/CrashlyticsTests.kt
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/common/SessionReportingCoordinatorTest.java
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/internal/persistence/CrashlyticsReportPersistenceTest.java
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/ktx/CrashlyticsTests.kt
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsReportDataCapture.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/FirebaseInstallationId.kt
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/IdManager.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/InstallIdProvider.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/SessionReportingCoordinator.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/model/CrashlyticsReport.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/model/serialization/CrashlyticsReportJsonTransform.java
  firebase-sessions/CHANGELOG.md
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/FirebaseSessions.kt
Labels: size/L, main-merge-ack

#5729 Move mieq composite index tests
  firebase-firestore/CHANGELOG.md
  firebase-firestore/firestore_collection_group_index_config.tf
  firebase-firestore/firestore_composite_index_config.tf
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/CompositeIndexQueryTest.java
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/QueryTest.java
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/testutil/CompositeIndexTestHelper.java
Labels: size/XXL
