Repository firebase/firebase-android-sdk, pull requests merged in 2024-06, with the labels that each got.

#6008 Mergeback for release m148
  firebase-appdistribution-api/CHANGELOG.md
  firebase-appdistribution-api/gradle.properties
  firebase-appdistribution/CHANGELOG.md
  firebase-appdistribution/gradle.properties
  firebase-crashlytics-ndk/CHANGELOG.md
  firebase-crashlytics-ndk/gradle.properties
  firebase-crashlytics/CHANGELOG.md
  firebase-crashlytics/gradle.properties
  firebase-dynamic-links/CHANGELOG.md
  firebase-dynamic-links/gradle.properties
  firebase-perf/CHANGELOG.md
  firebase-perf/gradle.properties
  firebase-sessions/gradle.properties
Labels: size/M

#6013 Make default schema objects explicitly non-nullable, and add helpers …
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/FunctionDeclarations.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/Part.kt
Labels: size/M

#6020 Update scripts for Data Connect Emulator v1.2.0
  firebase-dataconnect/emulator/.gitignore
  firebase-dataconnect/emulator/cli_wrapper.sh
  firebase-dataconnect/emulator/emulator.sh
  firebase-dataconnect/emulator/emulator_noauth.sh
  firebase-dataconnect/emulator/firebase.json
  firebase-dataconnect/emulator/start_postgres_pod.sh
Labels: size/M

#5785 Update libcrashlytics to support 16 kb page sizes
  firebase-crashlytics-ndk/CHANGELOG.md
  firebase-crashlytics-ndk/src/main/jni/libcrashlytics-common/Android.mk
  firebase-crashlytics-ndk/src/main/jni/libcrashlytics-handler/Android.mk
  firebase-crashlytics-ndk/src/main/jni/libcrashlytics-trampoline/Android.mk
  firebase-crashlytics-ndk/src/main/jni/libcrashlytics/Android.mk
Labels: size/S, main-merge-ack

#6022 Changing caught exception type to fail safely on any exception type.
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/send/ReportQueue.java
Labels: size/XS, no-changelog, main-merge-ack

#6025 pin firebase-common
  firebase-firestore/firebase-firestore.gradle
Labels: size/S

#6027 Add missing direct dependency in `firebase-common` from firestore
  firebase-firestore/firebase-firestore.gradle
Labels: size/XS

#6031 bump genai common
  firebase-vertexai/firebase-vertexai.gradle.kts
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/GenerativeModel.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/internal/util/conversions.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/Exceptions.kt
Labels: size/S

#6033 Fix JSON literal parsing in VertexAI
  firebase-vertexai/CHANGELOG.md
  firebase-vertexai/firebase-vertexai.gradle.kts
Labels: size/XS

#6036 Change references from master to main
  contributor-docs/_config.yml
  contributor-docs/how_firebase_works.md
  docs/README.md
  firebase-appdistribution/test-app/README.md
  firebase-messaging/CHANGELOG.md
  firebase-perf/README.md
  firebase-perf/dev-app/README.md
  firebase-perf/e2e-app/README.md
  firebase-perf/src/test/java/com/google/firebase/perf/shadows/ShadowPreconditions.java
  firebase-storage/test-app/README.md
  tools/lint/src/main/kotlin/ThreadPoolDetector.kt
Labels: size/S

#6045 Update vertexai changelog
  firebase-vertexai/CHANGELOG.md
Labels: size/XS

#6041 fix int type, add long type, rename double type
  firebase-vertexai/CHANGELOG.md
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/FunctionDeclarations.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/Type.kt
Labels: size/M

#6038 Fix timezone calculation in Timestamp
  firebase-dataconnect/src/main/kotlin/com/google/firebase/dataconnect/FirebaseDataConnect.kt
  firebase-dataconnect/src/main/kotlin/com/google/firebase/dataconnect/serializers/TimestampSerializer.kt
  firebase-dataconnect/src/test/kotlin/com/google/firebase/dataconnect/serializers/TimestampSerializerUnitTest.kt
Labels: size/M

#5941 sessionToken Persistence
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/GlobalsCache.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/LocalStore.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/MemoryGlobalsCache.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/MemoryPersistence.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/Persistence.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteGlobalsCache.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLitePersistence.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/local/SQLiteSchema.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/GlobalsCacheTest.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/MemoryGlobalsCacheTest.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/SQLiteGlobalCacheTest.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/local/SQLiteSchemaTest.java
Labels: size/L

#6046 Update vertexAI changelog entries around schema changes
  firebase-vertexai/CHANGELOG.md
Labels: size/XS

#6040 Refactor startup executor
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/FirebaseCrashlytics.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/ExecutorUtils.java
Labels: size/S

#6052 Retry requests that fail with UNAUTHENTICATED with a fresh auth token
  firebase-dataconnect/src/main/kotlin/com/google/firebase/dataconnect/FirebaseDataConnect.kt
  firebase-dataconnect/src/main/kotlin/com/google/firebase/dataconnect/core/DataConnectGrpcClient.kt
  firebase-dataconnect/src/main/kotlin/com/google/firebase/dataconnect/core/FirebaseDataConnectImpl.kt
  firebase-dataconnect/src/test/kotlin/com/google/firebase/dataconnect/core/DataConnectGrpcClientUnitTest.kt
Labels: size/L

#6044 Explicitly keep default constructor in subtypes of ComponentRegistrar
  firebase-components/proguard.txt
Labels: size/XS

#6060 Update Vertex docs in line with m149
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/Exceptions.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/Part.kt
Labels: size/S, no-changelog

#6057 Faster tests
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/AggregationTest.java
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/ArrayTransformsServerApplicationTest.java
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/ArrayTransformsTest.java
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/BundleTest.java
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/CompositeIndexQueryTest.java
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/CountTest.java
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/CursorTest.java
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/DocumentSnapshotTest.java
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/FieldsTest.java
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/FirestoreTest.java
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/IndexingTest.java
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/ListenerRegistrationTest.java
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/NumericTransformsTest.java
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/POJOTest.java
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/QueryTest.java
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/ServerTimestampTest.java
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/SmokeTest.java
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/SnapshotListenerSourceTest.java
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/SourceTest.java
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/TransactionTest.java
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/TypeTest.java
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/ValidationTest.java
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/WriteBatchTest.java
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/testutil/IntegrationTestUtil.java
Labels: size/L

#6061 add pulling firebase common to vertexai tests
  .github/workflows/ci_tests.yml
Labels: size/XS, no-changelog

#6063 Fix main branch name in various CI tasks
  .github/workflows/ci_tests.yml
  .github/workflows/diff-javadoc.yml
  .github/workflows/health-metrics.yml
  .github/workflows/jekyll-gh-pages.yml
  .github/workflows/merge-to-main.yml
  .github/workflows/post_release_cleanup.yml
  .github/workflows/private-mirror-sync.yml
  .github/workflows/release-note-changes.yml
  .github/workflows/update-cpp-sdk-on-release.yml
Labels: size/S, no-changelog
