Repository firebase/firebase-android-sdk, pull requests merged in 2025-05, with the labels that each got.

#6903 Add Java VertexAI bidi compile tests
  firebase-ai/src/testUtil/java/com/google/firebase/ai/JavaCompileTests.java
  firebase-vertexai/src/testUtil/java/com/google/firebase/vertexai/JavaCompileTests.java
Labels: size/L

#6925 [Ai] Add workaround for invalid SafetyRating from the backend.
  firebase-ai/src/main/kotlin/com/google/firebase/ai/type/Candidate.kt
  firebase-ai/src/main/kotlin/com/google/firebase/ai/type/PromptFeedback.kt
  firebase-ai/src/test/java/com/google/firebase/ai/VertexAIStreamingSnapshotTests.kt
  firebase-ai/src/test/java/com/google/firebase/ai/VertexAIUnarySnapshotTests.kt
Labels: size/M

#6937 fix more strict mode violation
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CommonUtils.java
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsController.java
Labels: size/S

#6930 Fix AI builders for Java consumers
  firebase-ai/CHANGELOG.md
  firebase-ai/api.txt
  firebase-ai/src/main/kotlin/com/google/firebase/ai/type/Content.kt
  firebase-ai/src/main/kotlin/com/google/firebase/ai/type/GenerationConfig.kt
  firebase-ai/src/testUtil/java/com/google/firebase/ai/JavaCompileTests.java
Labels: size/M

#6932 [Ai] Fix test code to point to the right resource dir
  firebase-ai/src/main/kotlin/com/google/firebase/ai/common/APIController.kt
  firebase-ai/src/test/java/com/google/firebase/ai/DevAPIStreamingSnapshotTests.kt
  firebase-ai/src/test/java/com/google/firebase/ai/VertexAIStreamingSnapshotTests.kt
  firebase-ai/src/test/java/com/google/firebase/ai/util/tests.kt
  firebase-ai/update_responses.sh
Labels: size/M

#6926 [Ai] Update test response check to verify firebase-ai
  .github/workflows/check-firebaseai-responses.yml
Labels: size/S

#6939 Add headers to be able to track bidi usage
  firebase-ai/src/main/kotlin/com/google/firebase/ai/common/APIController.kt
Labels: size/S

#6927 [Storage] Migrate from Robolectric.flushForegroundThreadScheduler to ShadowLooper.runToEndOfTasks
  firebase-storage/CHANGELOG.md
  firebase-storage/src/test/java/com/google/firebase/storage/DownloadTest.java
  firebase-storage/src/test/java/com/google/firebase/storage/TestUtil.java
Labels: size/S

#6902 dataconnect: include relevant logcat snippets in github actions logs when androidTest tests fail
  .github/workflows/dataconnect.yml
  firebase-dataconnect/ci/README.md
  firebase-dataconnect/ci/logcat_error_report.py
  firebase-dataconnect/ci/logcat_error_report_test.py
  firebase-dataconnect/ci/pyproject.toml
Labels: size/L, no-changelog, main-merge-ack, api: dataconnect

#6940 Fix NetworkOnMainThreadException for API levels below 26
  firebase-config/CHANGELOG.md
  firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigRealtimeHttpClient.java
Labels: size/S

#6941 Prepare VertexAI SDK for release
  firebase-vertexai/CHANGELOG.md
  firebase-vertexai/api.txt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/Chat.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/FirebaseVertexAI.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/FirebaseVertexAIMultiResourceComponent.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/GenerativeModel.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/ImagenModel.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/LiveGenerativeModel.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/common/APIController.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/java/ChatFutures.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/java/GenerativeModelFutures.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/java/ImagenModelFutures.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/java/LiveModelFutures.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/java/LiveSessionFutures.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/Candidate.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/Content.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/ContentModality.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/CountTokensResponse.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/Exceptions.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/FunctionCallingConfig.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/FunctionDeclaration.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/GenerateContentResponse.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/GenerationConfig.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/HarmBlockMethod.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/HarmBlockThreshold.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/HarmCategory.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/HarmProbability.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/HarmSeverity.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/ImagenAspectRatio.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/ImagenGenerationConfig.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/ImagenGenerationResponse.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/ImagenImageFormat.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/ImagenInlineImage.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/ImagenPersonFilterLevel.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/ImagenSafetyFilterLevel.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/ImagenSafetySettings.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/LiveContentResponse.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/LiveGenerationConfig.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/LiveServerMessage.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/LiveSession.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/MediaData.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/ModalityTokenCount.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/Part.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/PromptFeedback.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/RequestOptions.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/ResponseModality.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/SafetySetting.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/Schema.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/SpeechConfig.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/Tool.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/ToolConfig.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/UsageMetadata.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/Voices.kt
  firebase-vertexai/src/test/java/com/google/firebase/vertexai/VertexAIStreamingSnapshotTests.kt
  firebase-vertexai/src/test/java/com/google/firebase/vertexai/VertexAIUnarySnapshotTests.kt
  firebase-vertexai/src/testUtil/java/com/google/firebase/vertexai/JavaCompileTests.java
  firebase-vertexai/update_responses.sh
Labels: size/XXL, main-merge-ack

#6944 Update headers to track vertex ai/developer usage in kotlin
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/GenerativeModel.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/ImagenModel.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/LiveGenerativeModel.kt
Labels: size/XS

#6945 Update Crashlytics changelog
  firebase-crashlytics/CHANGELOG.md
Labels: size/XS, main-merge-ack

#6946 Add crashlytics-ndk changelog entry
  firebase-crashlytics-ndk/CHANGELOG.md
Labels: size/XS, main-merge-ack

#6948 update headers in the correct location
  firebase-ai/src/main/kotlin/com/google/firebase/ai/GenerativeModel.kt
  firebase-ai/src/main/kotlin/com/google/firebase/ai/ImagenModel.kt
  firebase-ai/src/main/kotlin/com/google/firebase/ai/LiveGenerativeModel.kt
Labels: size/XS

#6949 Revert "Update headers to track vertex ai/developer usage in kotlin (…
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/GenerativeModel.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/ImagenModel.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/LiveGenerativeModel.kt
Labels: size/XS, no-changelog, main-merge-ack

#6950 Implement new cold app start detection heuristic
  firebase-sessions/CHANGELOG.md
  firebase-sessions/firebase-sessions.gradle.kts
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/FirebaseSessionsComponent.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/ProcessDataManager.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionData.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SharedSessionRepository.kt
  firebase-sessions/src/test/kotlin/com/google/firebase/sessions/ProcessDataManagerTest.kt
  firebase-sessions/src/test/kotlin/com/google/firebase/sessions/SharedSessionRepositoryTest.kt
  firebase-sessions/src/test/kotlin/com/google/firebase/sessions/testing/FakeFirebaseApp.kt
  firebase-sessions/src/test/kotlin/com/google/firebase/sessions/testing/FakeProcessDataManager.kt
  firebase-sessions/src/test/kotlin/com/google/firebase/sessions/testing/FakeRunningAppProcessInfo.kt
  firebase-sessions/src/test/kotlin/com/google/firebase/sessions/testing/FakeUuidGenerator.kt
Labels: size/L

#6951 Add Firebase AI to recipe version generation
  plugins/src/main/java/com/google/firebase/gradle/bomgenerator/GenerateTutorialBundleTask.kt
  plugins/src/main/java/com/google/firebase/gradle/plugins/PublishingPlugin.kt
Labels: size/XS, no-changelog, main-merge-ack

#6954 [ai] Include missing dependency suffix to firebase-ai
  plugins/src/main/java/com/google/firebase/gradle/bomgenerator/GenerateTutorialBundleTask.kt
Labels: size/XS

#6955 [action] Only include merge message on sdk changes
  .github/workflows/merge-to-main.yml
Labels: size/M

#6961 Implement ProcessDataManager
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/ProcessDataManager.kt
  firebase-sessions/src/test/kotlin/com/google/firebase/sessions/ProcessDataManagerTest.kt
  firebase-sessions/src/test/kotlin/com/google/firebase/sessions/testing/FakeProcessDataManager.kt
Labels: size/L

#6963 Refactor usage of ProcessName in Fireperf.
  firebase-perf/src/main/java/com/google/firebase/perf/metrics/AppStartTrace.java
  firebase-perf/src/main/java/com/google/firebase/perf/transport/TransportManager.java
  firebase-perf/src/main/java/com/google/firebase/perf/util/AppProcessesProvider.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/ProcessDetailsProvider.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionEvent.kt
Labels: size/L, no-changelog

#6966 Add missing `GaugeCounter` increment.
  firebase-perf/src/main/java/com/google/firebase/perf/session/gauges/CpuGaugeCollector.java
  firebase-perf/src/main/java/com/google/firebase/perf/session/gauges/MemoryGaugeCollector.java
  firebase-perf/src/test/java/com/google/firebase/perf/session/gauges/GaugeManagerTest.java
Labels: size/XS, no-changelog

#6957 fix(ai): pass FunctionDeclaration#description arg to internal class
  firebase-ai/CHANGELOG.md
  firebase-ai/src/main/kotlin/com/google/firebase/ai/type/FunctionDeclaration.kt
  firebase-ai/src/test/java/com/google/firebase/ai/type/FunctionDeclarationTest.kt
Labels: size/L

#6972 Fix Firebase AI StackOverflow
  firebase-ai/CHANGELOG.md
  firebase-ai/src/main/kotlin/com/google/firebase/ai/FirebaseAI.kt
Labels: size/XS

#6976 [vertexai] Use correct name in release notes for vertexai
  firebase-vertexai/firebase-vertexai.gradle.kts
Labels: size/XS

#6982 Add macrobenchmark module for sessions test app
  firebase-sessions/benchmark/README.md
  firebase-sessions/benchmark/benchmark.gradle.kts
  firebase-sessions/benchmark/src/main/AndroidManifest.xml
  firebase-sessions/benchmark/src/main/kotlin/com/google/firebase/benchmark/sessions/StartupBenchmark.kt
  firebase-sessions/test-app/src/main/AndroidManifest.xml
  firebase-sessions/test-app/test-app.gradle.kts
  gradle/libs.versions.toml
  subprojects.cfg
Labels: size/L, no-changelog, main-merge-ack

#6918 Migrate from Robolectric.flushForegroundThreadScheduler to ShadowLooper.runToEndOfTasks
  firebase-inappmessaging/src/test/java/com/google/firebase/inappmessaging/internal/ForegroundNotifierTest.java
Labels: size/XS

#6988 Do not notify subscribers when session didn't change
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SharedSessionRepository.kt
Labels: size/XS

#6991 Add gauge counter to collector tests
  firebase-perf/src/main/java/com/google/firebase/perf/session/gauges/CpuGaugeCollector.java
  firebase-perf/src/main/java/com/google/firebase/perf/session/gauges/GaugeCounter.kt
  firebase-perf/src/main/java/com/google/firebase/perf/session/gauges/GaugeManager.java
  firebase-perf/src/main/java/com/google/firebase/perf/session/gauges/MemoryGaugeCollector.java
  firebase-perf/src/test/java/com/google/firebase/perf/FirebasePerformanceTestBase.java
  firebase-perf/src/test/java/com/google/firebase/perf/session/gauges/CpuGaugeCollectorTest.java
  firebase-perf/src/test/java/com/google/firebase/perf/session/gauges/GaugeManagerTest.java
  firebase-perf/src/test/java/com/google/firebase/perf/session/gauges/MemoryGaugeCollectorTest.java
Labels: size/M, no-changelog

#6992 Update Gauge logging to better match the existing implementation
  firebase-perf/src/main/java/com/google/firebase/perf/session/FirebasePerformanceSessionSubscriber.kt
  firebase-perf/src/main/java/com/google/firebase/perf/session/SessionManager.java
  firebase-perf/src/main/java/com/google/firebase/perf/session/gauges/GaugeCounter.kt
  firebase-perf/src/main/java/com/google/firebase/perf/session/gauges/GaugeManager.java
  firebase-perf/src/main/java/com/google/firebase/perf/transport/TransportManager.java
  firebase-perf/src/test/java/com/google/firebase/perf/session/gauges/GaugeManagerTest.java
Labels: size/L, no-changelog

#6995 Update ImagenPersonFilterLevel refdocs to match the iOS SDK
  firebase-ai/src/main/kotlin/com/google/firebase/ai/type/ImagenPersonFilterLevel.kt
Labels: size/S

#7002 Use the same tag for all logs in sessions
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/EventGDTLogger.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/FirebaseSessions.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/FirebaseSessionsComponent.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/FirebaseSessionsRegistrar.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/InstallationId.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionFirelogPublisher.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SharedSessionRepository.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/api/FirebaseSessionsDependencies.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/settings/RemoteSettings.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/settings/SettingsCache.kt
Labels: size/M

#7001 dataconnect: Fixed occasional `NullPointerException` leading to erroneous UNAUTHENTICATED exceptions
  firebase-dataconnect/CHANGELOG.md
  firebase-dataconnect/src/main/kotlin/com/google/firebase/dataconnect/core/DataConnectCredentialsTokenManager.kt
  firebase-dataconnect/src/main/kotlin/com/google/firebase/dataconnect/core/FirebaseDataConnectImpl.kt
  firebase-dataconnect/src/test/kotlin/com/google/firebase/dataconnect/core/DataConnectAuthUnitTest.kt
Labels: size/L, main-merge-ack, api: dataconnect

#7003 dataconnect: DataConnectExecutableVersions.json updated with versions 2.3.0, 2.3.1, 2.4.0, 2.4.1, 2.5.0, 2.6.0, 2.6.1, and 2.6.2
  .github/workflows/dataconnect.yml
  .github/workflows/dataconnect_demo_app.yml
  firebase-dataconnect/emulator/dataconnect/connector/person/person_ops.gql
  firebase-dataconnect/gradleplugin/plugin/src/main/resources/com/google/firebase/dataconnect/gradle/plugin/DataConnectExecutableVersions.json
  firebase-dataconnect/src/androidTest/kotlin/com/google/firebase/dataconnect/OperationExecutionErrorsIntegrationTest.kt
Labels: size/L, no-changelog, main-merge-ack, api: dataconnect
