Repository firebase/firebase-android-sdk, pull requests merged in 2025-04, with the labels that each got.

#6825 Update changelog file
  firebase-dataconnect/CHANGELOG.md
Labels: size/XS

#6827 dataconnect: QuerySubscriptionIntegrationTest.kt: fix flaky test using backgroundScope
  firebase-dataconnect/src/androidTest/kotlin/com/google/firebase/dataconnect/QuerySubscriptionIntegrationTest.kt
Labels: size/XS, no-changelog, main-merge-ack, api: dataconnect

#6829 dataconnect: github actions cache key fix
  .github/workflows/dataconnect.yml
Labels: size/XS, no-changelog, main-merge-ack, api: dataconnect

#6839 dataconnect: fix flaky test that ensures deserialize() throws IllegalArgumentException on invalid input
  firebase-dataconnect/src/test/kotlin/com/google/firebase/dataconnect/serializers/LocalDateSerializerUnitTest.kt
Labels: size/XS, no-changelog, main-merge-ack, api: dataconnect

#6838 dataconnect: dataconnect.yml: some minor improvements
  .github/workflows/dataconnect.yml
Labels: size/M, no-changelog, main-merge-ack, api: dataconnect

#6832 convert perf session to use aqs support session id
  firebase-perf/src/main/java/com/google/firebase/perf/FirebasePerformance.java
  firebase-perf/src/main/java/com/google/firebase/perf/logging/DebugEnforcementCheck.kt
  firebase-perf/src/main/java/com/google/firebase/perf/session/FirebasePerformanceSessionSubscriber.kt
  firebase-perf/src/main/java/com/google/firebase/perf/session/PerfSession.java
  firebase-perf/src/main/java/com/google/firebase/perf/session/SessionManager.java
  firebase-perf/src/test/java/com/google/firebase/perf/application/AppStateMonitorTest.java
  firebase-perf/src/test/java/com/google/firebase/perf/session/PerfSessionTest.java
  firebase-perf/src/test/java/com/google/firebase/perf/session/SessionManagerTest.java
  firebase-perf/src/test/java/com/google/firebase/perf/session/gauges/GaugeManagerTest.java
  firebase-perf/src/test/java/com/google/firebase/perf/transport/TransportManagerTest.java
Labels: size/L

#6845 [encoders] Replace deprecated Kotlin Stdlib functions with recommended ones
  encoders/protoc-gen-firebase-encoders/src/main/kotlin/com/google/firebase/encoders/proto/codegen/Types.kt
Labels: size/XS

#6847 use bytestream instead of bytearray
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/LiveSession.kt
Labels: size/S

#6835 dataconnect: fix two flaky tests due to their failure to wait for FirebaseAuth to be initialized
  firebase-dataconnect/src/androidTest/kotlin/com/google/firebase/dataconnect/AuthIntegrationTest.kt
Labels: size/XS, no-changelog, main-merge-ack, api: dataconnect

#6844 Create SharedSessionRepository and remove bound service
  firebase-sessions/src/androidTest/kotlin/com/google/firebase/sessions/FirebaseSessionsTests.kt
  firebase-sessions/src/androidTest/kotlin/com/google/firebase/sessions/SessionLifecycleServiceBinderTest.kt
  firebase-sessions/src/main/AndroidManifest.xml
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/FirebaseSessions.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/FirebaseSessionsComponent.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionData.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionDatastore.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionDetails.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionGenerator.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionLifecycleClient.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionLifecycleService.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionLifecycleServiceBinder.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionsActivityLifecycleCallbacks.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SharedSessionRepository.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/TimeProvider.kt
  firebase-sessions/src/test/AndroidManifest.xml
  firebase-sessions/src/test/kotlin/com/google/firebase/sessions/ApplicationInfoTest.kt
  firebase-sessions/src/test/kotlin/com/google/firebase/sessions/EventGDTLoggerTest.kt
  firebase-sessions/src/test/kotlin/com/google/firebase/sessions/SessionDatastoreTest.kt
  firebase-sessions/src/test/kotlin/com/google/firebase/sessions/SessionEventEncoderTest.kt
  firebase-sessions/src/test/kotlin/com/google/firebase/sessions/SessionEventTest.kt
  firebase-sessions/src/test/kotlin/com/google/firebase/sessions/SessionGeneratorTest.kt
  firebase-sessions/src/test/kotlin/com/google/firebase/sessions/SessionLifecycleClientTest.kt
  firebase-sessions/src/test/kotlin/com/google/firebase/sessions/SessionLifecycleServiceTest.kt
  firebase-sessions/src/test/kotlin/com/google/firebase/sessions/SessionsActivityLifecycleCallbacksTest.kt
  firebase-sessions/src/test/kotlin/com/google/firebase/sessions/api/FirebaseSessionsDependenciesTest.kt
  firebase-sessions/src/test/kotlin/com/google/firebase/sessions/testing/FakeFirelogPublisher.kt
  firebase-sessions/src/test/kotlin/com/google/firebase/sessions/testing/FakeSessionLifecycleServiceBinder.kt
  firebase-sessions/src/test/kotlin/com/google/firebase/sessions/testing/FakeTransportFactory.kt
  firebase-sessions/src/test/kotlin/com/google/firebase/sessions/testing/FirebaseSessionsFakeComponent.kt
  firebase-sessions/src/test/kotlin/com/google/firebase/sessions/testing/FirebaseSessionsFakeRegistrar.kt
Labels: size/XXL

#6851 [fireci] Update fireci setup declaration
  .github/workflows/fireci.yml
  ci/fireci/pyproject.toml
  ci/fireci/setup.cfg
  ci/run.sh
Labels: size/M

#6852 send session event based on data collection and setting config
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionFirelogPublisher.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SharedSessionRepository.kt
  firebase-sessions/src/test/kotlin/com/google/firebase/sessions/SessionFirelogPublisherTest.kt
Labels: size/S

#6816 Disconnect from Remote Config real-time server when app is backgrounded.
  firebase-config/CHANGELOG.md
  firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigAutoFetch.java
  firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigRealtimeHandler.java
  firebase-config/src/main/java/com/google/firebase/remoteconfig/internal/ConfigRealtimeHttpClient.java
  firebase-config/src/test/java/com/google/firebase/remoteconfig/FirebaseRemoteConfigTest.java
Labels: size/L

#6843 Add support for HarmBlockThreshold.OFF
  firebase-vertexai/CHANGELOG.md
  firebase-vertexai/api.txt
  firebase-vertexai/gradle.properties
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/HarmBlockThreshold.kt
Labels: size/S, main-merge-ack

#6854 dataconnect: AuthIntegrationTest.kt: add missing import for FirebaseDataConnectInternal
  firebase-dataconnect/src/androidTest/kotlin/com/google/firebase/dataconnect/AuthIntegrationTest.kt
Labels: size/XS, no-changelog, main-merge-ack, api: dataconnect

#6837 upate release notes
  firebase-vertexai/CHANGELOG.md
Labels: size/XS

#6855 Fix firelog send
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SharedSessionRepository.kt
Labels: size/XS

#6841 Improve the integration test coverage for online vs offline comparisons.
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/CompositeIndexQueryTest.java
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/FirestoreTest.java
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/QueryTest.java
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/VectorTest.java
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/testutil/CompositeIndexTestHelper.java
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/testutil/IntegrationTestUtil.java
Labels: size/L, no-changelog

#6865 [Perf] Cache attribute key validation regex
  firebase-perf/src/main/java/com/google/firebase/perf/metrics/validator/PerfMetricValidator.java
Labels: size/XS

#6859 fix: remove null value inclusion from `whereNotEqualTo` and `whereNotIn` filter results
  firebase-firestore/CHANGELOG.md
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/QueryTest.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/FieldFilter.java
  firebase-firestore/src/main/java/com/google/firebase/firestore/core/NotInFilter.java
  firebase-firestore/src/test/java/com/google/firebase/firestore/core/QueryTest.java
Labels: size/M

#6848 update javadocs
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/LiveContentResponse.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/LiveSession.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/ResponseModality.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/SpeechConfig.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/Voices.kt
Labels: size/M

#6866 [plugins] Remove JavaPluginConvention from FirebaseJavaLibraryPlugin
  plugins/src/main/java/com/google/firebase/gradle/plugins/FirebaseJavaLibraryPlugin.kt
Labels: size/XS

#6869 Add write permisison to VertexAI Response Checking task
  .github/workflows/check-vertexai-responses.yml
Labels: size/XS

#6867 Update PerfSession and SessionManager to identify Legacy sessions.
  firebase-perf/firebase-perf.gradle
  firebase-perf/src/main/java/com/google/firebase/perf/FirebasePerformance.java
  firebase-perf/src/main/java/com/google/firebase/perf/logging/FirebaseSessionsEnforcementCheck.kt
  firebase-perf/src/main/java/com/google/firebase/perf/session/FirebasePerformanceSessionSubscriber.kt
  firebase-perf/src/main/java/com/google/firebase/perf/session/FirebaseSessionsHelper.kt
  firebase-perf/src/main/java/com/google/firebase/perf/session/PerfSession.java
  firebase-perf/src/main/java/com/google/firebase/perf/session/SessionManager.java
  firebase-perf/src/main/java/com/google/firebase/perf/util/Constants.java
  firebase-perf/src/test/java/com/google/firebase/perf/session/FirebaseSessionsTestHelper.kt
  firebase-perf/src/test/java/com/google/firebase/perf/session/PerfSessionTest.java
  firebase-perf/src/test/java/com/google/firebase/perf/session/SessionManagerTest.java
  firebase-perf/src/test/java/com/google/firebase/perf/session/gauges/GaugeManagerTest.java
  firebase-perf/src/test/java/com/google/firebase/perf/transport/TransportManagerTest.java
Labels: size/L

#6874 Implement fake datastore for unit tests
  firebase-sessions/src/test/kotlin/com/google/firebase/sessions/FakeDataStoreTest.kt
  firebase-sessions/src/test/kotlin/com/google/firebase/sessions/testing/FakeDataStore.kt
Labels: size/L

#6875 [RC] Remove package declaration from testapp manifest
  firebase-config/bandwagoner/src/main/AndroidManifest.xml
Labels: size/M

#6868 fix: Improve efficiency of online/offline composite index tests.
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/testutil/CompositeIndexTestHelper.java
  firebase-firestore/src/androidTest/java/com/google/firebase/firestore/testutil/IntegrationTestUtil.java
Labels: size/XS, no-changelog

#6834 Update LiveModelFutures to return LiveSessionFutures instead of LiveSession
  firebase-vertexai/CHANGELOG.md
  firebase-vertexai/api.txt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/java/LiveModelFutures.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/java/LiveSessionFutures.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/LiveGenerationConfig.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/ResponseModality.kt
Labels: size/M

#6870 Refactor live bidi
  firebase-vertexai/CHANGELOG.md
  firebase-vertexai/api.txt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/FirebaseVertexAI.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/FirebaseVertexAIMultiResourceComponent.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/FirebaseVertexAIRegistrar.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/LiveGenerativeModel.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/common/APIController.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/common/util/android.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/common/util/kotlin.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/java/LiveSessionFutures.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/AudioHelper.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/Exceptions.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/LiveClientSetupMessage.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/LiveGenerationConfig.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/LiveSession.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/Part.kt
  firebase-vertexai/src/test/java/com/google/firebase/vertexai/util/tests.kt
Labels: size/XXL, main-merge-ack

#6822 fix: avoid android.os.strictmode.UnbufferedIoViolation (resubmission of PR #6565)
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/SessionReportingCoordinator.java
Labels: size/S, main-merge-ack

#6886 background time nullable
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionData.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SharedSessionRepository.kt
  firebase-sessions/src/test/kotlin/com/google/firebase/sessions/SharedSessionRepositoryTest.kt
Labels: size/M

#6877 Disable the activity lifecycle callbacks on app delete
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/FirebaseSessions.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionsActivityLifecycleCallbacks.kt
Labels: size/M

#6840 dataconnect: Improve usage of MutableStateFlow to improve readability
  firebase-dataconnect/src/main/kotlin/com/google/firebase/dataconnect/core/DataConnectCredentialsTokenManager.kt
  firebase-dataconnect/src/main/kotlin/com/google/firebase/dataconnect/core/FirebaseDataConnectImpl.kt
  firebase-dataconnect/src/main/kotlin/com/google/firebase/dataconnect/core/QuerySubscriptionImpl.kt
  firebase-dataconnect/src/main/kotlin/com/google/firebase/dataconnect/querymgr/RegisteredDataDeserialzer.kt
  firebase-dataconnect/testutil/src/main/kotlin/com/google/firebase/dataconnect/testutil/SuspendingCountDownLatch.kt
Labels: size/L, no-changelog, main-merge-ack, api: dataconnect

#6890 Add process name to application info
  firebase-perf/src/main/java/com/google/firebase/perf/transport/TransportManager.java
  firebase-perf/src/main/proto/firebase/perf/v1/perf_metric.proto
  firebase-perf/src/test/java/com/google/firebase/perf/transport/TransportManagerTest.java
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/ProcessDetailsProvider.kt
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionEvent.kt
Labels: size/S

#6880 dataconnect: create python script to post comments about scheduled runs
  .github/actions/dataconnect-send-notifications/action.yml
  .github/workflows/dataconnect.yml
  .github/workflows/dataconnect_demo_app.yml
  firebase-dataconnect/ci/README.md
  firebase-dataconnect/ci/calculate_github_issue_for_commenting.py
  firebase-dataconnect/ci/calculate_github_issue_for_commenting_test.py
  firebase-dataconnect/ci/post_comment_for_job_results.py
  firebase-dataconnect/ci/pyproject.toml
  firebase-dataconnect/ci/requirements.txt
  firebase-dataconnect/ci/util.py
Labels: size/XL, no-changelog, main-merge-ack, api: dataconnect

#6896 dataconnect: use firebase-tools to launch fdc emulator instead of launching it directly
  .github/workflows/dataconnect.yml
  .github/workflows/dataconnect_demo_app.yml
  firebase-dataconnect/gradleplugin/plugin/src/main/resources/com/google/firebase/dataconnect/gradle/plugin/DataConnectExecutableVersions.json
Labels: size/M, do-not-merge/work-in-progress, no-changelog, main-merge-ack, api: dataconnect

#6894 Handle error when stream was cancelled prior to calling halfClose.
  firebase-firestore/CHANGELOG.md
  firebase-firestore/src/main/java/com/google/firebase/firestore/remote/AbstractStream.java
Labels: size/S

#6861 FirebaseDataConnectImpl.kt: use MutableStateFlow to store state, rather than mutexes
  firebase-dataconnect/CHANGELOG.md
  firebase-dataconnect/src/main/kotlin/com/google/firebase/dataconnect/core/FirebaseDataConnectImpl.kt
  firebase-dataconnect/src/main/kotlin/com/google/firebase/dataconnect/core/MutationRefImpl.kt
  firebase-dataconnect/src/main/kotlin/com/google/firebase/dataconnect/core/QueryRefImpl.kt
  firebase-dataconnect/src/main/kotlin/com/google/firebase/dataconnect/core/QuerySubscriptionImpl.kt
  firebase-dataconnect/src/test/kotlin/com/google/firebase/dataconnect/core/MutationRefImplUnitTest.kt
  firebase-dataconnect/src/test/kotlin/com/google/firebase/dataconnect/core/QueryRefImplUnitTest.kt
Labels: size/L, no-changelog, main-merge-ack, api: dataconnect

#6901 Enable multimodal response generation in android
  firebase-vertexai/CHANGELOG.md
  firebase-vertexai/api.txt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/GenerateContentResponse.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/GenerationConfig.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/Part.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/ResponseModality.kt
Labels: size/M

#6905 Refactor: Rename encodeBitmapToBase64Png to encodeBitmapToBase64Jpeg
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/Part.kt
Labels: size/XS

#6908 Pin protolite-well-known-types
  protolite-well-known-types/gradle.properties
Labels: size/XS

#6906 Migrate LiveContentResponse.Status to properties
  firebase-vertexai/CHANGELOG.md
  firebase-vertexai/api.txt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/LiveContentResponse.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/LiveSession.kt
Labels: size/M, main-merge-ack

#6912 encodeBitmapToBase64Png -> encodeBitmapToBase64Jpeg
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/Part.kt
Labels: size/XS

#6915 [ai] Address most tests failures
  firebase-ai/src/test/java/com/google/firebase/ai/DevAPIUnarySnapshotTests.kt
  firebase-ai/src/test/java/com/google/firebase/ai/util/tests.kt
  firebase-ai/update_responses.sh
Labels: size/S

#6909 Exclude protolite well known types from version bump.
  plugins/src/main/java/com/google/firebase/gradle/plugins/PostReleasePlugin.kt
  plugins/src/main/java/com/google/firebase/gradle/plugins/VersionBumpTask.kt
Labels: size/S, no-changelog, main-merge-ack

#6916 [ai] Use .json for unary tests instead of .txt
  firebase-ai/src/test/java/com/google/firebase/ai/DevAPIUnarySnapshotTests.kt
Labels: size/XS

#6922 Add inlineDataParts helper property
  firebase-ai/CHANGELOG.md
  firebase-ai/api.txt
  firebase-ai/src/main/kotlin/com/google/firebase/ai/type/GenerateContentResponse.kt
Labels: size/S, main-merge-ack

#6921 Add ResponseModality support to GenerationConfig
  firebase-ai/CHANGELOG.md
  firebase-ai/api.txt
  firebase-ai/src/main/kotlin/com/google/firebase/ai/type/GenerationConfig.kt
Labels: size/S, main-merge-ack

#6917 Fix AI test timeout
  firebase-ai/src/test/java/com/google/firebase/ai/util/tests.kt
  firebase-vertexai/src/test/java/com/google/firebase/vertexai/util/tests.kt
Labels: size/S, no-changelog, main-merge-ack

#6910 Align LiveSeverMessage related protos
  firebase-ai/CHANGELOG.md
  firebase-ai/api.txt
  firebase-ai/src/main/kotlin/com/google/firebase/ai/java/LiveSessionFutures.kt
  firebase-ai/src/main/kotlin/com/google/firebase/ai/type/LiveContentResponse.kt
  firebase-ai/src/main/kotlin/com/google/firebase/ai/type/LiveServerMessage.kt
  firebase-ai/src/main/kotlin/com/google/firebase/ai/type/LiveSession.kt
  firebase-ai/src/main/kotlin/com/google/firebase/ai/type/Part.kt
Labels: size/XL, main-merge-ack
