Repository firebase/firebase-android-sdk, pull requests merged in 2025-06, with the labels that each got.

#7011 Davidmotson.google count token modelname
  firebase-ai/CHANGELOG.md
  firebase-ai/src/main/kotlin/com/google/firebase/ai/common/Request.kt
  firebase-ai/src/main/kotlin/com/google/firebase/ai/common/util/util.kt
Labels: size/XS

#7014 Add more trace buttons to sessions test app
  firebase-sessions/test-app/src/main/kotlin/com/google/firebase/testing/sessions/FirstFragment.kt
  firebase-sessions/test-app/src/main/res/layout/fragment_first.xml
  firebase-sessions/test-app/src/main/res/values/strings.xml
  firebase-sessions/test-app/test-app.gradle.kts
Labels: size/M

#7005 Change docs for m165
  firebase-ai/src/main/kotlin/com/google/firebase/ai/type/ImagenPersonFilterLevel.kt
  firebase-ai/src/main/kotlin/com/google/firebase/ai/type/Voice.kt
  firebase-ai/src/main/kotlin/com/google/firebase/ai/type/Voices.kt
  plugins/src/main/java/com/google/firebase/gradle/bomgenerator/GenerateTutorialBundleTask.kt
Labels: size/S

#7036 Delete a sentence I missed in 7035
  firebase-perf/README.md
Labels: no-changelog

#7029 Fix sessions e2e test
  .github/workflows/sessions-e2e.yml
Labels: size/XS, no-changelog, main-merge-ack

#7031 dataconnect: demo: build.gradle.kts: update dependencies
  firebase-dataconnect/demo/build.gradle.kts
Labels: size/S, no-changelog, main-merge-ack, api: dataconnect

#7032 dataconnect: demo: build.gradle.kts: add ability to specify the Data Connect emulator executable to use
  .github/workflows/dataconnect_demo_app.yml
  firebase-dataconnect/demo/build.gradle.kts
  firebase-dataconnect/demo/gradle.properties
Labels: size/M, no-changelog, main-merge-ack, api: dataconnect

#7068 dataconnect: dataconnect.yml: add more files to the list of files whose changes trigger integration tests in PRs
  .github/workflows/dataconnect.yml
Labels: no-changelog, main-merge-ack, api: dataconnect

#7079 dataconnect: demo: upgrade Android Gradle Plugin to 8.11.0 (was 8.10.1) and Gradle wrapper to 8.13 (was 8.11.1)
  firebase-dataconnect/demo/build.gradle.kts
  firebase-dataconnect/demo/gradle/wrapper/gradle-wrapper.properties
Labels: no-changelog, main-merge-ack, api: dataconnect

#6924 Removed deprecated public constructor KeyValueBuilder
  firebase-crashlytics/CHANGELOG.md
  firebase-crashlytics/api.txt
  firebase-crashlytics/gradle.properties
  firebase-crashlytics/src/androidTest/java/com/google/firebase/crashlytics/CrashlyticsTests.kt
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/KeyValueBuilder.kt
Labels: size/M

#6801 Migrate common from SharedPreferences to DataStore
  firebase-common/CHANGELOG.md
  firebase-common/firebase-common.gradle.kts
  firebase-common/src/main/java/com/google/firebase/datastorage/JavaDataStorage.kt
  firebase-common/src/main/java/com/google/firebase/datastorage/package-info.java
  firebase-common/src/main/java/com/google/firebase/heartbeatinfo/DefaultHeartBeatController.java
  firebase-common/src/main/java/com/google/firebase/heartbeatinfo/HeartBeatInfoStorage.java
  firebase-common/src/test/java/com/google/firebase/heartbeatinfo/DefaultHeartBeatControllerTest.java
  firebase-common/src/test/java/com/google/firebase/heartbeatinfo/HeartBeatInfoStorageTest.java
Labels: size/XL
