Repository firebase/firebase-android-sdk, pull requests merged in 2025-02, with the labels that each got.

#6663 Update create pull request version
  .github/workflows/create_releases.yml
Labels: size/XS

#6672 Update changelogs for m150
  firebase-firestore/CHANGELOG.md
  firebase-vertexai/CHANGELOG.md
Labels: size/XS, main-merge-ack

#6670 dataconnect.yml: ensure that test logs are uploaded even when the tests fail
  .github/workflows/dataconnect.yml
Labels: size/S, no-changelog, main-merge-ack, api: dataconnect

#6671 Update Metalava and api.txt files
  appcheck/firebase-appcheck-debug-testing/api.txt
  appcheck/firebase-appcheck-debug/api.txt
  appcheck/firebase-appcheck-interop/api.txt
  appcheck/firebase-appcheck-playintegrity/api.txt
  appcheck/firebase-appcheck/api.txt
  appcheck/firebase-appcheck/ktx/api.txt
  encoders/firebase-decoders-json/api.txt
  encoders/firebase-encoders-json/api.txt
  encoders/firebase-encoders-proto/api.txt
  encoders/firebase-encoders-reflective/api.txt
  encoders/firebase-encoders/api.txt
  firebase-abt/api.txt
  firebase-annotations/api.txt
  firebase-appdistribution-api/api.txt
  firebase-appdistribution-api/ktx/api.txt
  firebase-appdistribution/api.txt
  firebase-common/api.txt
  firebase-common/ktx/api.txt
  firebase-components/api.txt
  firebase-components/firebase-dynamic-module-support/api.txt
  firebase-config-interop/api.txt
  firebase-config/api.txt
  firebase-config/ktx/api.txt
  firebase-crashlytics-ndk/api.txt
  firebase-crashlytics/api.txt
  firebase-crashlytics/ktx/api.txt
  firebase-database-collection/api.txt
  firebase-database/api.txt
  firebase-database/ktx/api.txt
  firebase-dataconnect/api.txt
  firebase-datatransport/api.txt
  firebase-dynamic-links/api.txt
  firebase-dynamic-links/ktx/api.txt
  firebase-firestore/api.txt
  firebase-firestore/ktx/api.txt
  firebase-functions/api.txt
  firebase-functions/ktx/api.txt
  firebase-inappmessaging-display/api.txt
  firebase-inappmessaging-display/ktx/api.txt
  firebase-inappmessaging/api.txt
  firebase-inappmessaging/ktx/api.txt
  firebase-installations-interop/api.txt
  firebase-installations/api.txt
  firebase-installations/ktx/api.txt
  firebase-messaging-directboot/api.txt
  firebase-messaging/api.txt
  firebase-messaging/ktx/api.txt
  firebase-ml-modeldownloader/api.txt
  firebase-ml-modeldownloader/ktx/api.txt
  firebase-perf/api.txt
  firebase-perf/ktx/api.txt
  firebase-sessions/api.txt
  firebase-storage/api.txt
  firebase-storage/ktx/api.txt
  firebase-vertexai/api.txt
  plugins/src/main/java/com/google/firebase/gradle/plugins/Metalava.kt
  protolite-well-known-types/api.txt
  transport/transport-api/api.txt
  transport/transport-backend-cct/api.txt
  transport/transport-runtime/api.txt
Labels: size/XXL

#6675 Refactor bom generation
  plugins/src/main/java/com/google/firebase/gradle/bomgenerator/BomGeneratorTask.java
  plugins/src/main/java/com/google/firebase/gradle/bomgenerator/GenerateBomReleaseNotesTask.kt
  plugins/src/main/java/com/google/firebase/gradle/bomgenerator/GenerateBomTask.kt
  plugins/src/main/java/com/google/firebase/gradle/bomgenerator/GenerateTutorialBundleTask.kt
  plugins/src/main/java/com/google/firebase/gradle/bomgenerator/MarkdownDocumentationWriter.java
  plugins/src/main/java/com/google/firebase/gradle/bomgenerator/PomXmlWriter.java
  plugins/src/main/java/com/google/firebase/gradle/bomgenerator/RecipeVersionWriter.java
  plugins/src/main/java/com/google/firebase/gradle/bomgenerator/RepositoryClient.java
  plugins/src/main/java/com/google/firebase/gradle/bomgenerator/model/Dependency.java
  plugins/src/main/java/com/google/firebase/gradle/bomgenerator/model/VersionBump.java
  plugins/src/main/java/com/google/firebase/gradle/plugins/GradleExtensions.kt
  plugins/src/main/java/com/google/firebase/gradle/plugins/KotlinExtensions.kt
  plugins/src/main/java/com/google/firebase/gradle/plugins/ModuleVersion.kt
  plugins/src/main/java/com/google/firebase/gradle/plugins/PostReleasePlugin.kt
  plugins/src/main/java/com/google/firebase/gradle/plugins/PublishingPlugin.kt
  plugins/src/main/java/com/google/firebase/gradle/plugins/datamodels/PomElement.kt
  plugins/src/test/kotlin/com/google/firebase/gradle/TestUtil.kt
  plugins/src/test/kotlin/com/google/firebase/gradle/plugins/GenerateBomReleaseNotesTests.kt
  plugins/src/test/kotlin/com/google/firebase/gradle/plugins/GenerateBomTests.kt
  plugins/src/test/kotlin/com/google/firebase/gradle/plugins/GenerateTutorialBundleTests.kt
  plugins/src/test/resources/Bom/empty-bom.pom
  plugins/src/test/resources/Bom/filled-bom.pom
Labels: size/XXL, no-changelog, main-merge-ack

#6679 Fix ModuleVersion bumping
  .github/workflows/make-bom.yml
  plugins/src/main/java/com/google/firebase/gradle/bomgenerator/GenerateBomReleaseNotesTask.kt
  plugins/src/main/java/com/google/firebase/gradle/bomgenerator/GenerateBomTask.kt
  plugins/src/main/java/com/google/firebase/gradle/plugins/KotlinExtensions.kt
  plugins/src/main/java/com/google/firebase/gradle/plugins/ModuleVersion.kt
  plugins/src/main/java/com/google/firebase/gradle/plugins/PublishingPlugin.kt
  plugins/src/main/java/com/google/firebase/gradle/plugins/datamodels/PomElement.kt
  plugins/src/test/kotlin/com/google/firebase/gradle/plugins/GenerateBomReleaseNotesTests.kt
  plugins/src/test/kotlin/com/google/firebase/gradle/plugins/GenerateBomTests.kt
  plugins/src/test/kotlin/com/google/firebase/gradle/plugins/ModuleVersionTests.kt
Labels: size/L, no-changelog, main-merge-ack

#6678 Remove the logging of GaugeMetadata to allow using AQS
  firebase-perf/src/main/java/com/google/firebase/perf/FirebasePerformance.java
  firebase-perf/src/main/java/com/google/firebase/perf/session/SessionManager.java
  firebase-perf/src/main/java/com/google/firebase/perf/session/gauges/CpuGaugeCollector.java
  firebase-perf/src/main/java/com/google/firebase/perf/session/gauges/GaugeManager.java
  firebase-perf/src/main/java/com/google/firebase/perf/session/gauges/GaugeMetadataManager.java
  firebase-perf/src/main/java/com/google/firebase/perf/session/gauges/MemoryGaugeCollector.java
  firebase-perf/src/test/java/com/google/firebase/perf/session/SessionManagerTest.java
  firebase-perf/src/test/java/com/google/firebase/perf/session/gauges/GaugeMetadataManagerTest.java
Labels: size/L

#6684 dataconnect: DataConnectExecutableVersions.json updated with versions 1.7.6 and 1.7.7
  firebase-dataconnect/gradleplugin/plugin/src/main/resources/com/google/firebase/dataconnect/gradle/plugin/DataConnectExecutableVersions.json
Labels: size/M, no-changelog, main-merge-ack, api: dataconnect

#6669 dataconnect.yaml: improve readability of the output of the "tool versions" step
  .github/workflows/dataconnect.yml
  .github/workflows/dataconnect_demo_app.yml
Labels: size/M, no-changelog, main-merge-ack, api: dataconnect

#6667 dataconnect: fix cache key conflict on nighty integration tests runs
  .github/workflows/dataconnect.yml
Labels: size/XS, no-changelog, main-merge-ack, api: dataconnect

#6658 Add support for token-based usage metrics
  firebase-vertexai/CHANGELOG.md
  firebase-vertexai/api.txt
  firebase-vertexai/gradle.properties
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/ContentModality.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/CountTokensResponse.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/ModalityTokenCount.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/UsageMetadata.kt
  firebase-vertexai/src/test/java/com/google/firebase/vertexai/UnarySnapshotTests.kt
  firebase-vertexai/update_responses.sh
Labels: size/L

#6691 Fix deprecated message in KeyValueBuilder to render properly
  firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/KeyValueBuilder.kt
Labels: size/XS, no-changelog, main-merge-ack

#6683 Implement a SessionSubscriber for Firebase Performance
  firebase-perf/firebase-perf.gradle
  firebase-perf/src/main/java/com/google/firebase/perf/FirebasePerfRegistrar.java
  firebase-perf/src/main/java/com/google/firebase/perf/FirebasePerformance.java
  firebase-perf/src/main/java/com/google/firebase/perf/session/FirebasePerformanceSessionSubscriber.kt
  firebase-perf/src/main/java/com/google/firebase/perf/session/PerfSession.java
  firebase-perf/src/main/java/com/google/firebase/perf/session/SessionManager.java
  firebase-perf/src/main/java/com/google/firebase/perf/session/gauges/GaugeManager.java
  firebase-perf/src/main/java/com/google/firebase/perf/transport/TransportManager.java
  firebase-perf/src/test/java/com/google/firebase/perf/session/SessionManagerTest.java
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/api/FirebaseSessionsDependencies.kt
Labels: size/L

#6694 Add functions changelog
  firebase-functions/CHANGELOG.md
Labels: size/XS

#6697 dataconnect: improve cache restoration in github actions workflow
  .github/workflows/dataconnect.yml
Labels: size/S, no-changelog, main-merge-ack

#6701 Followup to #6699
  firebase-sessions/src/main/kotlin/com/google/firebase/sessions/SessionLifecycleService.kt
Labels: size/S, no-changelog, main-merge-ack

#6681 docs: update ImagePart refdocs
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/Part.kt
Labels: size/XS

#6607 Initial implementation to API spec
  firebase-vertexai/CHANGELOG.md
  firebase-vertexai/api.txt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/FirebaseVertexAI.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/GenerativeModel.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/ImagenModel.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/common/APIController.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/common/AppCheckHeaderProvider.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/common/Exceptions.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/common/Request.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/internal/util/kotlin.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/java/ImagenModelFutures.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/Exceptions.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/ImagenAspectRatio.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/ImagenGCSImage.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/ImagenGenerationConfig.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/ImagenGenerationResponse.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/ImagenImageFormat.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/ImagenInlineImage.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/ImagenPersonFilterLevel.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/ImagenSafetyFilterLevel.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/ImagenSafetySettings.kt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/PublicPreviewAPI.kt
  firebase-vertexai/src/test/java/com/google/firebase/vertexai/StreamingSnapshotTests.kt
  firebase-vertexai/src/test/java/com/google/firebase/vertexai/UnarySnapshotTests.kt
  firebase-vertexai/src/test/java/com/google/firebase/vertexai/common/StreamingSnapshotTests.kt
  firebase-vertexai/src/test/java/com/google/firebase/vertexai/common/UnarySnapshotTests.kt
  firebase-vertexai/src/test/java/com/google/firebase/vertexai/util/tests.kt
Labels: size/XXL

#6702 add new recipe entries to BoM generator
  plugins/src/main/java/com/google/firebase/gradle/bomgenerator/GenerateTutorialBundleTask.kt
  plugins/src/main/java/com/google/firebase/gradle/plugins/PublishingPlugin.kt
Labels: size/S

#6717 Remove test code left by mistake
  firebase-vertexai/api.txt
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/ImagenGenerationConfig.kt
Labels: size/S

#6705 Support custom tabs in more browsers
  firebase-appdistribution/src/main/AndroidManifest.xml
  firebase-appdistribution/src/main/java/com/google/firebase/appdistribution/impl/TesterSignInManager.java
Labels: size/S

#6719 Update CHANGELOG for Crashlytics and NDK
  firebase-crashlytics-ndk/CHANGELOG.md
  firebase-crashlytics/CHANGELOG.md
Labels: size/XS, main-merge-ack

#6716 Bump well known types
  firebase-firestore/CHANGELOG.md
  firebase-inappmessaging-display/CHANGELOG.md
  firebase-inappmessaging/CHANGELOG.md
  firebase-perf/CHANGELOG.md
  firebase-perf/firebase-perf.gradle
  protolite-well-known-types/CHANGELOG.md
  protolite-well-known-types/README.md
  protolite-well-known-types/gradle.properties
  protolite-well-known-types/protolite-well-known-types.gradle
Labels: size/S, main-merge-ack

#6718 Update CHANGELOG.md
  firebase-appdistribution/CHANGELOG.md
Labels: size/XS

#6728 Fix documentation for ImagenGenerationResponse
  firebase-vertexai/src/main/kotlin/com/google/firebase/vertexai/type/ImagenGenerationResponse.kt
Labels: size/XS

#6724 Add copyApiTxtFile task
  plugins/src/main/java/com/google/firebase/gradle/plugins/CopyApiTask.kt
  plugins/src/main/java/com/google/firebase/gradle/plugins/FirebaseAndroidLibraryPlugin.kt
  plugins/src/main/java/com/google/firebase/gradle/plugins/FirebaseJavaLibraryPlugin.kt
  plugins/src/main/java/com/google/firebase/gradle/plugins/FirebaseLibraryExtension.kt
Labels: size/M

#6727 dataconnect: minor cosmetic changes to the github actions workflow
  .github/workflows/dataconnect.yml
Labels: size/XS, no-changelog, main-merge-ack, api: dataconnect

#6729 dataconnect: change grpc api version from "v1beta" to "v1"
  firebase-dataconnect/CHANGELOG.md
  firebase-dataconnect/demo/firebase/dataconnect/dataconnect.yaml
  firebase-dataconnect/emulator/dataconnect/dataconnect.yaml
  firebase-dataconnect/src/main/proto/google/firebase/dataconnect/proto/connector_service.proto
  firebase-dataconnect/src/main/proto/google/firebase/dataconnect/proto/graphql_error.proto
Labels: size/S, main-merge-ack, api: dataconnect

#6725 Add Metalava SemVer Task
  .github/workflows/metalava-semver-check.yml
  plugins/src/main/java/com/google/firebase/gradle/plugins/FirebaseAndroidLibraryPlugin.kt
  plugins/src/main/java/com/google/firebase/gradle/plugins/FirebaseJavaLibraryPlugin.kt
  plugins/src/main/java/com/google/firebase/gradle/plugins/Metalava.kt
  plugins/src/main/java/com/google/firebase/gradle/plugins/SemVerTask.kt
Labels: size/L
